import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {spawn} from 'node:child_process'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql,SCHEMA_VERSION} from '../server/schema.mjs'
import {listAddressAnalysis,previewAddress,useSuggestedAddress} from '../server/addressAnalysisService.mjs'
import {bootstrapAccount,changePassword,createAccount,login} from '../server/authService.mjs'
import {messages} from '../src/translations.js'

function fixture(){const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;${schemaSql}`);db.prepare("INSERT INTO zone_groups(id,code,name,is_active) VALUES(99,'Z99','Kuching Test',1)").run();db.prepare("INSERT INTO areas(id,jodoo_area_id,name,zone_group_id,confirmed_zone_group_id,zone_assignment_status,is_active) VALUES(99,'A99','Tabuan',99,99,'confirmed',1),(100,'A100','Pending Area',99,99,'pending_confirmation',1)").run();db.prepare("INSERT INTO customers(id,jodoo_customer_id,name) VALUES(1,'100','Alpha Customer'),(2,'200','Beta Customer')").run();db.prepare(`INSERT INTO branches(id,jodoo_branch_id,customer_id,area_id,branch_name,address,latitude,longitude,gps_street,gps_postal_code,lifecycle_status,is_active,status) VALUES
    (1,'101',1,99,'Missing Official','',1.5000,110.3000,'Jalan Tabuan','93350','ACTIVE',1,'active'),
    (2,'102',1,99,'Missing No GPS','',NULL,NULL,'','','ACTIVE',1,'active'),
    (3,'103',2,99,'Landmark Only','Mall',1.5001,110.3001,'','','ACTIVE',1,'active'),
    (4,'104',2,99,'Complete Address','12 Jalan Tabuan Kuching 93350',1.5002,110.3002,'Jalan Tabuan','93350','ACTIVE',1,'active'),
    (5,'105',2,99,'Inactive Nearby','12 Jalan Tabuan',1.50021,110.30021,'Jalan Tabuan','93350','CLOSED',0,'closed')`).run();db.prepare("INSERT INTO temporary_locations(branch_id,latitude,longitude,verification_status,location_source) VALUES(2,1.6,110.4,'pending','mobile')").run();return db}

test('dashboard buckets Active Branches, supports raw/B typed search and makes no writes',()=>{const db=fixture(),before=db.prepare('SELECT total_changes() n').get().n,all=listAddressAnalysis({},db);assert.equal(all.counts.missing_with_gps,1);assert.equal(all.counts.missing_without_gps,1);assert.equal(all.counts.incomplete,1);assert.equal(all.items.length,4);assert.equal(listAddressAnalysis({search:'104'},db).items[0].branchId,'B104');assert.equal(listAddressAnalysis({search:'B104'},db).items[0].branchId,'B104');assert.equal(db.prepare('SELECT total_changes() n').get().n,before)})

test('Pending GPS is ignored and inactive or unconfirmed nearby evidence is excluded',()=>{const db=fixture(),missing=listAddressAnalysis({search:'B102'},db).items[0],target=listAddressAnalysis({search:'B104'},db).items[0];assert.equal(missing.officialGps.available,false);assert.equal(missing.pendingGps.ignored,true);assert.equal(missing.proposedArea.manualReviewRequired,true);assert.ok(!target.nearbyBranches.some(item=>item.branchId==='B105'));assert.ok(target.nearbyBranches.every(item=>item.areaId===99))})

test('nearby Official GPS is supporting only and cannot combine with address tokens to become HIGH',()=>{const item=listAddressAnalysis({search:'B104'},fixture()).items[0];assert.ok(item.nearbyBranches.some(branch=>branch.areaId===item.currentAreaId));assert.deepEqual(item.proposedArea.independentEvidence,['address_area_tokens']);assert.equal(item.proposedArea.confidence,'medium');assert.equal(item.proposedArea.manualReviewRequired,true)})

test('address Area candidates exclude pending or unconfirmed Areas',()=>{const db=fixture();db.prepare("UPDATE branches SET address='12 Pending Area Kuching 93350' WHERE id=4").run();const item=listAddressAnalysis({search:'B104'},db).items[0];assert.ok(!item.addressEvidence.areaCandidates.some(area=>area.id===100))})

test('Reviewed/unchanged matches only the latest audited current address state and fails closed when stale or invalid',()=>{const db=fixture();db.prepare("INSERT INTO zone_boundaries(zone_group_id,boundary_version,polygon_json,center_latitude,center_longitude,effective_date,is_active,created_by) VALUES(99,1,'[{\"lat\":1.4,\"lng\":110.2},{\"lat\":1.4,\"lng\":110.4},{\"lat\":1.6,\"lng\":110.4},{\"lat\":1.6,\"lng\":110.2}]',1.5,110.3,'2026-01-01',1,'Test')").run();db.prepare("INSERT INTO gps_zone_recommendations(branch_id,official_latitude,official_longitude,current_area_id,current_zone_group_id,recommended_area_id,recommended_zone_group_id,match_type,confidence,reason_json,status) VALUES(4,1.5002,110.3002,99,99,99,99,'inside','low','{}','kept_original')").run();let item=listAddressAnalysis({search:'B104'},db).items[0];assert.equal(item.reviewed,false);const after={address:'12 Jalan Tabuan Kuching 93350',gps_address:null,gps_state:null,gps_street:'Jalan Tabuan',gps_city:null,gps_street_number:null,gps_postal_code:'93350'};db.prepare("INSERT INTO master_change_history(entity_type,entity_id,change_type,field_name,before_json,after_json,reason,changed_by) VALUES('branch','104','address_analysis_address_updated','address','{}',?,'Reviewed','Supervisor')").run(JSON.stringify(after));item=listAddressAnalysis({search:'B104'},db).items[0];assert.equal(item.reviewed,true);assert.equal(item.bucket,'reviewed_unchanged');db.prepare("UPDATE branches SET address='' WHERE id=4").run();item=listAddressAnalysis({search:'B104'},db).items[0];assert.equal(item.reviewed,false);assert.equal(item.bucket,'missing_with_gps');db.prepare("UPDATE branches SET address='Changed current address' WHERE id=4").run();db.prepare("INSERT INTO master_change_history(entity_type,entity_id,change_type,field_name,before_json,after_json,reason,changed_by) VALUES('branch','104','address_analysis_address_updated','address','{}','not-json','Bad','Supervisor')").run();item=listAddressAnalysis({search:'B104'},db).items[0];assert.equal(item.reviewed,false);assert.notEqual(item.bucket,'reviewed_unchanged')})

test('Google preview is explicit, unavailable safely, and candidate is not proof',async()=>{const db=fixture();await assert.rejects(previewAddress('B101',{geocoder:async()=>{throw Object.assign(new Error('Address lookup is unavailable because the Google Geocoding key is not configured.'),{statusCode:503})}},db),/not configured/);const preview=await previewAddress('B101',{geocoder:async()=>({address:'10 Jalan Tabuan, Kuching 93350',street:'Jalan Tabuan',streetNumber:'10',city:'Kuching',state:'Sarawak',postalCode:'93350',provider:'Google Geocoding API'})},db);assert.equal(preview.previewOnly,true);assert.equal(preview.proof,false);assert.ok(preview.previewToken);assert.equal(db.prepare("SELECT address FROM branches WHERE id=1").get().address,'')})

test('preview rejects empty candidates and confirmation rejects tamper, expiry and stale Official GPS',async()=>{const db=fixture(),geocoder=async()=>({address:'10 Jalan Tabuan',street:'Jalan Tabuan',provider:'Google'});await assert.rejects(previewAddress('B101',{geocoder:async()=>({address:'  '})},db),/no usable address/);const valid=await previewAddress('B101',{geocoder},db);assert.throws(()=>useSuggestedAddress('B101',{previewToken:`${valid.previewToken}x`,reason:'Checked',changedBy:'Supervisor'},db),/invalid/);const expired=await previewAddress('B101',{geocoder,previewTtlMs:-1},db);assert.throws(()=>useSuggestedAddress('B101',{previewToken:expired.previewToken,reason:'Checked',changedBy:'Supervisor'},db),/expired/);db.prepare('UPDATE branches SET latitude=1.51 WHERE id=1').run();assert.throws(()=>useSuggestedAddress('B101',{previewToken:valid.previewToken,reason:'Checked',changedBy:'Supervisor'},db),/changed after preview/);assert.equal(db.prepare('SELECT address FROM branches WHERE id=1').get().address,'')})

test('address confirmation requires actor/reason, audits before/after and preserves operational relations',async()=>{const db=fixture();db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency) VALUES('S1',1,'101','Weekly')").run();db.prepare("INSERT INTO dispatches(id,dispatch_date,status) VALUES(1,'2099-01-01','draft')").run();db.prepare("INSERT INTO dispatch_stops(dispatch_id,branch_id,stop_sequence,status) VALUES(1,1,1,'locked')").run();db.prepare("INSERT INTO materials(id,material_code,material_name) VALUES(1,'M1','Paper')").run();db.prepare("INSERT INTO branch_material_prices(branch_id,material_id,special_price,assigned_by) VALUES(1,1,1.2,'Admin')").run();db.prepare("INSERT INTO branch_gps_history(branch_id,action,latitude,longitude,actor) VALUES(1,'approved',1.5,110.3,'GPS Admin')").run();const preview=await previewAddress('101',{geocoder:async()=>({address:'10 Jalan Tabuan, Kuching 93350',street:'Jalan Tabuan',streetNumber:'10',city:'Kuching',state:'Sarawak',postalCode:'93350',provider:'Google'})},db),related=()=>['branch_schedules','dispatch_stops','branch_material_prices','branch_gps_history'].map(table=>db.prepare(`SELECT COUNT(*) n FROM ${table} WHERE branch_id=1`).get().n),beforeRelated=related(),before=db.prepare('SELECT latitude,longitude,area_id,customer_id FROM branches WHERE id=1').get();assert.throws(()=>useSuggestedAddress('101',{previewToken:preview.previewToken,changedBy:'Session Supervisor'},db),/reason/);assert.throws(()=>useSuggestedAddress('101',{previewToken:preview.previewToken,reason:'Verified'},db),/actor/);useSuggestedAddress('B101',{previewToken:preview.previewToken,reason:'Compared with branch proof',changedBy:'Session Supervisor'},db);assert.deepEqual({...db.prepare('SELECT latitude,longitude,area_id,customer_id FROM branches WHERE id=1').get()},{...before});assert.deepEqual(related(),beforeRelated);const audit=db.prepare("SELECT before_json,after_json,reason,changed_by FROM master_change_history WHERE change_type='address_analysis_address_updated'").get();assert.equal(JSON.parse(audit.before_json).address,'');assert.equal(JSON.parse(audit.after_json).address,'10 Jalan Tabuan, Kuching 93350');assert.equal(audit.reason,'Compared with branch proof');assert.equal(audit.changed_by,'Session Supervisor')})

test('each actual address-analysis route returns 403 to a Session without gps_review',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'kcs-address-route-')),databasePath=path.join(directory,'route.db'),database=new DatabaseSync(databasePath);database.exec(`PRAGMA foreign_keys=ON;${schemaSql}`);const owner=bootstrapAccount({employeeName:'Owner',username:'owner',password:'OwnerPassword123!'}, {},database),employee=database.prepare("INSERT INTO employees(employee_code,name,job_role) VALUES('E-ROUTE','Route Office','Office')").run(),office=createAccount({employeeId:employee.lastInsertRowid,username:'route-office',password:'OfficePassword123!',role:'office'},owner,{},database);changePassword({id:office.id},{currentPassword:'OfficePassword123!',newPassword:'OfficeChanged123!'},database);const token=login({username:'route-office',password:'OfficeChanged123!'},{},database).token;database.close();const port=19000+Math.floor(Math.random()*1000),child=spawn(process.execPath,['server/index.mjs'],{cwd:path.resolve(new URL('..',import.meta.url).pathname),env:{...process.env,KCS_API_PORT:String(port),KCS_API_HOST:'127.0.0.1',KCS_DB_PATH:databasePath,KCS_DATA_DIR:directory}});t.after(()=>{child.kill('SIGTERM');fs.rmSync(directory,{recursive:true,force:true})});let output='';child.stdout.on('data',chunk=>{output+=chunk});for(let attempt=0;attempt<100&&!output.includes('[KCS API] ready');attempt++)await new Promise(resolve=>setTimeout(resolve,25));assert.match(output,/\[KCS API\] ready/);for(const [method,route] of [['GET','/api/address-analysis'],['GET','/api/address-analysis/B101'],['POST','/api/address-analysis/B101/reverse-geocode-preview'],['POST','/api/address-analysis/B101/use-suggested-address']]){const response=await fetch(`http://127.0.0.1:${port}${route}`,{method,headers:{cookie:`kcs_session=${token}`,'content-type':'application/json'},...(method==='POST'?{body:'{}'}:{})});assert.equal(response.status,403,`${method} ${route}`)}})

test('API/UI contract uses Session actor, localized session-only decisions, no known secret, no frontend actor, and no migration',()=>{const server=fs.readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8'),service=fs.readFileSync(new URL('../server/addressAnalysisService.mjs',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../src/AddressAnalysisPage.jsx',import.meta.url),'utf8'),translations=fs.readFileSync(new URL('../src/translations.js',import.meta.url),'utf8');assert.match(server,/changedBy:session\.employeeName\|\|session\.username/);assert.doesNotMatch(service,/kcs-local-address-preview/);assert.match(service,/crypto\.randomBytes\(32\)/);assert.doesNotMatch(ui,/changedBy|confirmedBy/);assert.match(ui,/onKeyDown=.*keyOpen/);assert.match(ui,/const keepCurrent=id=>setKept/);assert.match(ui,/keepFeedback/);for(const language of ['en','ms','zh']){const keys=Object.keys(messages[language]).filter(key=>key.startsWith('addressAnalysis.')||key==='hub.addressAnalysis');assert.ok(keys.length>=74);assert.ok(messages[language]['addressAnalysis.keepFeedback'])}assert.match(translations,/addressAnalysis\.previewGoogle/);assert.equal(SCHEMA_VERSION,41);assert.equal(fs.existsSync(new URL('../server/migrationV42.mjs',import.meta.url)),false)})
