import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql,SCHEMA_VERSION} from '../server/schema.mjs'
import {applyV39Migration} from '../server/migrationV39.mjs'
import {analyzeArea,confirmAreaRefinement,getAreaRefinement,updateAreaRefinement} from '../server/areaRefinementService.mjs'
import {messages} from '../src/translations.js'

function fixture(){const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;${schemaSql}`);db.prepare("INSERT INTO areas(id,jodoo_area_id,name,zone_group_id,confirmed_zone_group_id,zone_assignment_status) VALUES(20,'A20','TABUAN JAYA',1,1,'confirmed')").run();db.prepare("INSERT INTO customers(id,jodoo_customer_id,name) VALUES(1,'10001','Alpha'),(2,'10002','Beta')").run();db.prepare("INSERT INTO branches(id,jodoo_branch_id,customer_id,area_id,branch_name,address,latitude,longitude) VALUES(30,'10018',1,20,'BORNEO','Old A',1.5000,110.3000),(31,'10241',1,20,'PANDA','Old B',1.5002,110.3002),(32,'10240',2,20,'SWEETHEART','Old C',1.5004,110.3004),(33,'10001',2,20,'NO GPS','Old D',NULL,NULL)").run();return db}
const geocoder=async latitude=>({address:`${latitude} Jalan Test, Kuching`,street:latitude<1.5001?'Jln Test':latitude<1.5003?'Jalan Test':'Test',locality:'Kuching',sublocality:'Tabuan Jaya',postalCode:'93350'})

test('v38 to v39 is explicit, additive, idempotent and creates no analysis or business changes',()=>{const db=new DatabaseSync(':memory:');db.exec("PRAGMA foreign_keys=ON;CREATE TABLE schema_meta(version INTEGER PRIMARY KEY);INSERT INTO schema_meta VALUES(38);CREATE TABLE zone_groups(id INTEGER PRIMARY KEY);CREATE TABLE areas(id INTEGER PRIMARY KEY);CREATE TABLE branches(id INTEGER PRIMARY KEY);CREATE TABLE dispatches(id INTEGER PRIMARY KEY);CREATE TABLE dispatch_stops(id INTEGER PRIMARY KEY);INSERT INTO zone_groups VALUES(1);INSERT INTO areas VALUES(1);INSERT INTO branches VALUES(1);INSERT INTO dispatches VALUES(1);INSERT INTO dispatch_stops VALUES(1)");const first=applyV39Migration(db),second=applyV39Migration(db);assert.equal(first.schemaVersion,39);assert.deepEqual(first.before,first.after);assert.equal(second.noOp,true);assert.equal(db.prepare('SELECT COUNT(*) n FROM area_refinement_analyses').get().n,0);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})

test('Preview uses Official GPS only, normalizes Jln aliases and marks missing GPS without changing formal Areas',async()=>{const db=fixture(),before={areas:db.prepare('SELECT COUNT(*) n FROM areas').get().n,assignments:db.prepare('SELECT group_concat(area_id) ids FROM branches ORDER BY id').get().ids},preview=await analyzeArea(20,{createdBy:'Supervisor',geocoder},db);assert.equal(preview.counts.total,4);assert.equal(preview.counts.officialGps,3);assert.equal(preview.counts.needGps,1);assert.equal(preview.counts.move,3);assert.deepEqual([...new Set(preview.items.filter(item=>item.action==='move').map(item=>item.proposedAreaName))],['Jalan Test']);assert.equal(preview.items.find(item=>item.branchId==='10001').action,'need_gps');assert.deepEqual({areas:db.prepare('SELECT COUNT(*) n FROM areas').get().n,assignments:db.prepare('SELECT group_concat(area_id) ids FROM branches ORDER BY id').get().ids},before);assert.equal(db.prepare('SELECT COUNT(*) n FROM temporary_locations').get().n,0)})

test('Preview supports manual keep, rename or merge and Needs Review decisions',async()=>{const db=fixture(),preview=await analyzeArea(20,{createdBy:'Supervisor',geocoder},db),[first,second]=preview.items.filter(item=>item.action==='move'),updated=updateAreaRefinement(preview.id,{changedBy:'Supervisor',items:[{branchId:first.branchInternalId,action:'keep',proposedAreaName:'',reason:'Keep current operational Area'},{branchId:second.branchInternalId,action:'move',proposedAreaName:'Tabuan Jaya Central',reason:'Manual merge after map review'}]},db);assert.equal(updated.items.find(item=>item.branchInternalId===first.branchInternalId).action,'keep');assert.equal(updated.items.find(item=>item.branchInternalId===second.branchInternalId).proposedAreaName,'Tabuan Jaya Central')})

test('Confirm creates formal child Areas atomically and incremental analysis excludes stable children',async()=>{const db=fixture(),preview=await analyzeArea(20,{createdBy:'Supervisor',geocoder},db);updateAreaRefinement(preview.id,{changedBy:'Supervisor',items:[{branchId:33,action:'keep',proposedAreaName:'',reason:'Wait for GPS'}]},db);const result=confirmAreaRefinement(preview.id,{changedBy:'Supervisor',reason:'Reviewed Preview'},db);assert.equal(result.result.createdAreaIds.length,1);assert.equal(result.result.movedBranchCount,3);assert.equal(db.prepare('SELECT COUNT(DISTINCT area_id) n FROM branches WHERE id IN(30,31,32)').get().n,1);assert.equal(db.prepare('SELECT area_id FROM branches WHERE id=33').get().area_id,20);assert.equal(db.prepare("SELECT COUNT(*) n FROM master_change_history WHERE change_type='area_refinement_confirmed'").get().n,4);db.prepare("INSERT INTO branches(id,jodoo_branch_id,customer_id,area_id,branch_name,latitude,longitude) VALUES(34,'10999',1,20,'NEW GPS',1.6,110.4)").run();const incremental=await analyzeArea(20,{createdBy:'Supervisor',geocoder},db);assert.deepEqual(incremental.items.map(item=>item.branchInternalId).sort((a,b)=>a-b),[33,34]);const reanalysis=await analyzeArea(20,{includeExisting:true,createdBy:'Supervisor',geocoder},db);assert.equal(reanalysis.items.length,5)})

test('Confirm rollback protects Area and Branch data if an audit step fails',async()=>{const db=fixture(),preview=await analyzeArea(20,{createdBy:'Supervisor',geocoder},db),before=db.prepare('SELECT COUNT(*) n FROM areas').get().n;assert.throws(()=>confirmAreaRefinement(preview.id,{changedBy:'Supervisor',reason:'Test rollback',failBeforeAudit:true},db),/Simulated/);assert.equal(db.prepare('SELECT COUNT(*) n FROM areas').get().n,before);assert.equal(db.prepare('SELECT COUNT(*) n FROM branches WHERE area_id=20').get().n,4);assert.equal(getAreaRefinement(preview.id,db).status,'preview')})

test('routes enforce Session scheduling permission and UI exposes Preview, map and manual controls',()=>{const server=fs.readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../src/ZoneGroupManager.jsx',import.meta.url),'utf8');assert.match(server,/refinement\\\/analyze[\s\S]{0,300}canManageSchedules\(session\)/);assert.match(server,/area-refinements/);for(const token of ['areaRefinement.analyzeZone','AreaRefinementDialog','AreaRefinementMap','areaRefinement.savePreview','areaRefinement.confirm'])assert.match(ui,new RegExp(token));assert.match(ui,/includeExisting/);assert.equal(SCHEMA_VERSION,40)})

test('Area refinement labels are complete in English, Malay and Chinese without Malay fallback',()=>{const keys=['title','analyze','previewOnly','total','officialGps','needGps','createAreas','moveBranches','suggested','confidence','decision','high','medium','needsReview','keep','confirm'];for(const language of ['en','ms','zh'])for(const key of keys)assert.ok(messages[language][`areaRefinement.${key}`]);assert.notEqual(messages.ms['areaRefinement.analyze'],messages.en['areaRefinement.analyze'])})
