import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {bootstrapAccount,changePassword,createAccount,getSession,hashPassword,login,roleCan,updateAccount,verifyPassword} from '../server/authService.mjs'
import {commitGpsMigration,previewGpsMigration,resolveGpsMigrationRow} from '../server/gpsMigrationService.mjs'
import {captureBranchGps} from '../server/customerMasterService.mjs'
import {createEmployee,updateEmployee} from '../server/resourceService.mjs'

function database(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);return db}
function seedBranch(db,{id='0001',lat=null,lng=null}={}){const customer=db.prepare("INSERT INTO customers(jodoo_customer_id,name) VALUES('C001','Customer')").run();db.prepare('INSERT INTO branches(jodoo_branch_id,customer_id,branch_name,latitude,longitude) VALUES(?,?,?,?,?)').run(id,customer.lastInsertRowid,'Branch',lat,lng)}

test('密码使用加盐哈希，首次登录强制修改密码且Session可验证',()=>{const db=database(),account=bootstrapAccount({employeeName:'Admin',employeeCode:'A001',username:'admin',password:'Initial123!'}, {},db);assert.equal(account.mustChangePassword,true);const stored=db.prepare('SELECT password_hash FROM auth_accounts').get().password_hash;assert.notEqual(stored,'Initial123!');assert.equal(verifyPassword('Initial123!',stored),true);const signed=login({username:'admin',password:'Initial123!'}, {},db);assert.equal(getSession(signed.token,db).username,'admin');const changed=changePassword({id:account.id},{currentPassword:'Initial123!',newPassword:'Changed123!'},db);assert.equal(changed.account.mustChangePassword,false);assert.equal(db.prepare('SELECT must_change_password value FROM auth_accounts').get().value,0);assert.equal(getSession(signed.token,db).username,'admin');assert.equal(getSession(signed.token,db).mustChangePassword,false)})

test('主动修改密码保持Session，管理员重设后才再次要求首次修改',()=>{const db=database(),owner=bootstrapAccount({employeeName:'Owner',username:'kcadmin',password:'Initial123!'}, {},db);const employee=db.prepare("INSERT INTO employees(employee_code,name,job_role) VALUES('E001','Employee','Office')").run();const account=createAccount({employeeId:employee.lastInsertRowid,username:'employee',password:'Temporary123!',role:'office'},owner,{},db);const firstLogin=login({username:'employee',password:'Temporary123!'}, {},db);assert.equal(firstLogin.account.mustChangePassword,true);changePassword({id:account.id},{currentPassword:'Temporary123!',newPassword:'Personal123!'},db);assert.equal(getSession(firstLogin.token,db).mustChangePassword,false);updateAccount(account.id,{isActive:true},owner,{},db);assert.equal(getSession(firstLogin.token,db).mustChangePassword,false);updateAccount(account.id,{password:'Reset123!'},owner,{},db);assert.equal(getSession(firstLogin.token,db).mustChangePassword,true);const changed=changePassword({id:account.id},{currentPassword:'Reset123!',newPassword:'AfterReset123!'},db);assert.equal(changed.account.mustChangePassword,false);assert.equal(getSession(firstLogin.token,db).username,'employee')})

test('新账号Audit不保存临时密码明文且API结果不返回密码',()=>{const db=database(),owner=bootstrapAccount({employeeName:'Owner',username:'kcadmin',password:'Initial123!'}, {},db),employee=db.prepare("INSERT INTO employees(employee_code,name,job_role) VALUES('EMP-0008','Employee Eight','Office')").run(),account=createAccount({employeeId:employee.lastInsertRowid,username:'EMP-0008',password:'12345678',role:'office'},owner,{},db),audit=db.prepare("SELECT detail_json FROM auth_audit_logs WHERE action='account_created' AND account_id=?").get(account.id);assert.equal(account.password,undefined);assert.equal(account.passwordHash,undefined);assert.doesNotMatch(audit.detail_json||'',/12345678/);assert.equal(account.mustChangePassword,true)})

test('停用账号不能登录，失败五次锁定并保留登录审计',()=>{const db=database(),owner=bootstrapAccount({employeeName:'Admin',username:'admin',password:'Initial123!'}, {},db),employee=db.prepare("INSERT INTO employees(employee_code,name,job_role) VALUES('E010','Office','Office')").run(),account=createAccount({employeeId:employee.lastInsertRowid,username:'office-user',password:'Initial123!',role:'office'},owner,{},db);updateAccount(account.id,{isActive:false},owner,{},db);assert.throws(()=>login({username:'office-user',password:'Initial123!'}, {},db));updateAccount(account.id,{isActive:true,unlock:true},owner,{},db);for(let index=0;index<5;index+=1)assert.throws(()=>login({username:'office-user',password:'bad-password'}, {},db));assert.ok(db.prepare('SELECT locked_until FROM auth_accounts WHERE id=?').get(account.id).locked_until);assert.equal(db.prepare("SELECT COUNT(*) count FROM auth_audit_logs WHERE action='login' AND success=0").get().count,6)})

test('cannot disable the final owner and usernames remain case-insensitively unique',()=>{const db=database(),owner=bootstrapAccount({employeeName:'Owner',username:'KCAdmin',password:'Initial123!'}, {},db);assert.throws(()=>updateAccount(owner.id,{isActive:false},owner,{},db),/最后一个 Owner Admin/);const employee=db.prepare("INSERT INTO employees(employee_code,name,job_role) VALUES('E009','Office','Office')").run();assert.throws(()=>createAccount({employeeId:employee.lastInsertRowid,username:'kcadmin',password:'Temporary123!',role:'office'},owner,{},db),/用户名已经使用/)})

test('System Role与Employee Job Role分开，GPS采集与审批权限由后端角色限制',()=>{const db=database();bootstrapAccount({employeeName:'Admin',username:'admin',password:'Initial123!'}, {},db);const employee=db.prepare("INSERT INTO employees(employee_code,name,job_role) VALUES('D001','Driver One','Driver')").run();const account=createAccount({employeeId:employee.lastInsertRowid,username:'driver1',password:'Driver123!',role:'driver'},{username:'admin'}, {},db);assert.equal(account.role,'driver');assert.equal(db.prepare('SELECT job_role FROM employees WHERE id=?').get(employee.lastInsertRowid).job_role,'Driver');assert.equal(roleCan('driver','mobile'),true);assert.equal(roleCan('driver','desktop'),false);assert.equal(roleCan('driver','gps_capture'),true);assert.equal(roleCan('driver','gps_review'),false);assert.equal(roleCan('crew','gps_capture'),true);assert.equal(roleCan('supervisor','gps_capture'),true);assert.equal(roleCan('supervisor','gps_review'),true);assert.equal(roleCan('office','accounts'),false)})

test('现有Official GPS会锁住Collector且不建立temporary GPS',()=>{const db=database();seedBranch(db,{lat:1.55,lng:110.35});assert.throws(()=>captureBranchGps('0001',{latitude:1.56,longitude:110.36,accuracyM:8,deviceCapturedAt:'2026-07-22T10:00:00Z',capturedBy:'D001'},db),/Official GPS already exists/);assert.equal(db.prepare('SELECT COUNT(*) n FROM temporary_locations').get().n,0)})

test('GPS迁移预览分类、幂等及Conflict不自动覆盖',()=>{const db=database();seedBranch(db,{lat:1.55,lng:110.35});const customer=db.prepare("INSERT INTO customers(jodoo_customer_id,name) VALUES('C002','Other')").run();db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,branch_name) VALUES('0002',?,'No GPS')").run(customer.lastInsertRowid);const payload={fileName:'gps.xlsx',rows:[{BranchID:'0001',Latitude:1.6,Longitude:110.4},{BranchID:'0002',Latitude:1.7,Longitude:110.5},{BranchID:'9999',Latitude:1.8,Longitude:110.6},{BranchID:'0003',Latitude:'bad',Longitude:110.5}]};const preview=previewGpsMigration(payload,'Admin',db);assert.equal(preview.summary.conflict,1);assert.equal(preview.summary.new,1);assert.equal(preview.summary.branch_not_found,1);assert.equal(preview.summary.invalid_gps,1);assert.equal(previewGpsMigration(payload,'Admin',db).id,preview.id);commitGpsMigration(preview.id,'Admin',db);const one=db.prepare("SELECT latitude,longitude FROM branches WHERE jodoo_branch_id='0001'").get(),two=db.prepare("SELECT latitude,longitude FROM branches WHERE jodoo_branch_id='0002'").get();assert.equal(one.latitude,1.55);assert.equal(one.longitude,110.35);assert.equal(two.latitude,1.7);assert.equal(two.longitude,110.5)})

test('GPS Conflict只有主管明确决定后才覆盖',()=>{const db=database();seedBranch(db,{lat:1.55,lng:110.35});const preview=previewGpsMigration({fileName:'conflict.csv',rows:[{BranchID:'0001',Latitude:1.6,Longitude:110.4}]},'Admin',db),row=preview.rows[0];resolveGpsMigrationRow(row.id,{decision:'keep_official',reason:'现场正式GPS可信'},'Supervisor',db);assert.equal(db.prepare("SELECT latitude FROM branches WHERE jodoo_branch_id='0001'").get().latitude,1.55);resolveGpsMigrationRow(row.id,{decision:'use_imported',reason:'主管核对旧档'},'Supervisor',db);assert.equal(db.prepare("SELECT latitude FROM branches WHERE jodoo_branch_id='0001'").get().latitude,1.6)})

test('hashPassword拒绝过短密码',()=>assert.throws(()=>hashPassword('short')))

test('Employee主要岗位、兼任岗位与岗位历史分开保存',()=>{const db=database(),employee=createEmployee({employeeCode:'S001',name:'Supervisor Driver',jobRole:'Supervisor',additionalRoles:['Driver'],changedBy:'Admin',reason:'具备驾驶资格'},db);assert.equal(employee.jobRole,'Supervisor');assert.ok(employee.additionalRoles.includes('Driver'));updateEmployee(employee.id,{jobRole:'Office',additionalRoles:['Driver'],changedBy:'Admin',reason:'调任办公室'},db);const history=db.prepare('SELECT * FROM employee_role_history WHERE employee_id=? ORDER BY id DESC').all(employee.id);assert.equal(history.length,2);assert.equal(JSON.parse(history[0].new_roles_json)[0],'Office')})

test('GPS迁移同一Branch多组坐标标记Duplicate Source',()=>{const db=database();seedBranch(db);const preview=previewGpsMigration({fileName:'duplicate.csv',rows:[{BranchID:'0001',Latitude:1.5,Longitude:110.3},{BranchID:'0001',Latitude:1.6,Longitude:110.4}]},'Admin',db);assert.equal(preview.summary.duplicate_source,1)})
