import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql,SCHEMA_VERSION} from '../server/schema.mjs'
import {applyV41Migration} from '../server/migrationV41.mjs'
import {changeBranchLifecycle,listBranchLifecycleReview,listReplacementBranches} from '../server/branchLifecycleService.mjs'
import {captureBranchGps,gpsCollectionDashboard} from '../server/customerMasterService.mjs'
import {dashboardSummary} from '../server/queryService.mjs'
import {messages} from '../src/translations.js'

function fixture(){const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;${schemaSql}`);db.prepare("INSERT INTO customers(id,jodoo_customer_id,name) VALUES(1,'10001','Alpha Customer')").run();db.prepare("INSERT INTO areas(id,jodoo_area_id,name,zone_group_id) VALUES(10,'A10','BDC',1)").run();db.prepare("INSERT INTO branches(id,jodoo_branch_id,customer_id,area_id,branch_name,address,lifecycle_status,status,is_active) VALUES(1,'10001',1,10,'Alpha BDC','Road A','ACTIVE','active',1),(2,'10002',1,10,'Alpha Canonical','Road B','ACTIVE','active',1),(3,'10003',1,10,'Invalid Target','Road C','TEST_INVALID','paused',0)").run();return db}

test('v40 to v41 is explicit, preserves counts and maps legacy status conservatively',()=>{const db=new DatabaseSync(':memory:');db.exec("PRAGMA foreign_keys=ON;CREATE TABLE schema_meta(version INTEGER PRIMARY KEY);INSERT INTO schema_meta VALUES(40);CREATE TABLE branches(id INTEGER PRIMARY KEY,status TEXT,is_active INTEGER,latitude REAL,longitude REAL);INSERT INTO branches VALUES(1,'active',1,NULL,NULL),(2,'paused',0,NULL,NULL),(3,'closed',0,NULL,NULL)");const result=applyV41Migration(db);assert.equal(result.schemaVersion,41);assert.equal(result.before.branches,3);assert.equal(result.after.branches,3);assert.deepEqual(result.statusCounts,{ACTIVE:1,CLOSED:1,TEMPORARILY_PAUSED:1});assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})

test('all lifecycle transitions require reason, synchronize compatibility fields and audit',()=>{const db=fixture();for(const status of ['TEMPORARILY_PAUSED','CLOSED','NOT_COLLECTING','TEST_INVALID','ACTIVE']){if(status!=='ACTIVE')db.prepare("UPDATE branches SET lifecycle_status='ACTIVE',status='active',is_active=1 WHERE id=1").run();const result=changeBranchLifecycle('10001',{lifecycleStatus:status,reason:`Set ${status}`},{changedBy:'Owner Admin'},db),row=db.prepare('SELECT lifecycle_status,status,is_active,status_reason,status_changed_by FROM branches WHERE id=1').get();assert.equal(row.lifecycle_status,status);assert.equal(row.is_active,status==='ACTIVE'?1:0);assert.equal(row.status,status==='ACTIVE'?'active':status==='CLOSED'?'closed':'paused');assert.equal(row.status_reason,`Set ${status}`);assert.equal(row.status_changed_by,'Owner Admin');assert.equal(result.lifecycleStatus,status)}assert.equal(db.prepare("SELECT COUNT(*) n FROM master_change_history WHERE entity_id='10001' AND change_type='lifecycle_status_changed'").get().n,5);assert.throws(()=>changeBranchLifecycle('10001',{lifecycleStatus:'CLOSED',reason:''},{changedBy:'Owner'},db),/reason is required/i)})

test('duplicate replacement requires final valid target and never moves old history',()=>{const db=fixture();db.prepare("INSERT INTO branch_gps_history(branch_id,action,latitude,longitude,actor) VALUES(1,'approved',1,110,'Historical Reviewer')").run();assert.throws(()=>changeBranchLifecycle('10001',{lifecycleStatus:'DUPLICATE_REPLACED',reason:'Duplicate'},{changedBy:'Owner'},db),/required/);assert.throws(()=>changeBranchLifecycle('10001',{lifecycleStatus:'DUPLICATE_REPLACED',reason:'Self',replacedByBranchId:1},{changedBy:'Owner'},db),/itself/);assert.throws(()=>changeBranchLifecycle('10001',{lifecycleStatus:'DUPLICATE_REPLACED',reason:'Bad target',replacedByBranchId:3},{changedBy:'Owner'},db),/canonical/);changeBranchLifecycle('10001',{lifecycleStatus:'DUPLICATE_REPLACED',reason:'Confirmed duplicate',replacedByBranchId:2},{changedBy:'Owner'},db);assert.equal(db.prepare('SELECT replaced_by_branch_id FROM branches WHERE id=1').get().replaced_by_branch_id,2);assert.equal(db.prepare('SELECT COUNT(*) n FROM branch_gps_history WHERE branch_id=1').get().n,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM branch_gps_history WHERE branch_id=2').get().n,0);assert.equal(listBranchLifecycleReview({},db).items[0].replacedByBranchId,'10002');assert.ok(listReplacementBranches({},db).every(item=>item.internalId!==1))})

test('non-active Branch is excluded from GPS work and Active dashboard counts while official GPS remains',()=>{const db=fixture();db.prepare("UPDATE branches SET latitude=1.5,longitude=110.3 WHERE id=1").run();changeBranchLifecycle('10001',{lifecycleStatus:'CLOSED',reason:'Closed'},{changedBy:'Owner'},db);assert.equal(gpsCollectionDashboard({},db).summary.totalActiveBranches,1);assert.equal(dashboardSummary(db).branchCount,1);assert.equal(db.prepare('SELECT latitude,longitude FROM branches WHERE id=1').get().latitude,1.5);assert.throws(()=>captureBranchGps('10001',{latitude:1.6,longitude:110.4},db),/Only an Active/);assert.equal(db.prepare('SELECT COUNT(*) n FROM temporary_locations').get().n,0)})

test('ordinary Branch edit cannot bypass lifecycle action and future Stops are warning-only',()=>{const db=fixture();const source=fs.readFileSync(new URL('../server/customerMasterService.mjs',import.meta.url),'utf8');assert.match(source,/Use Change Status to update Branch lifecycle/);const before=db.prepare('SELECT COUNT(*) n FROM branches').get().n;changeBranchLifecycle('10001',{lifecycleStatus:'TEMPORARILY_PAUSED',reason:'Pause'},{changedBy:'Supervisor'},db);assert.equal(db.prepare('SELECT COUNT(*) n FROM branches').get().n,before)})

test('audit failure rolls the lifecycle transaction back without partial update',()=>{const db=fixture();db.exec("CREATE TRIGGER fail_lifecycle_audit BEFORE INSERT ON master_change_history WHEN NEW.change_type='lifecycle_status_changed' BEGIN SELECT RAISE(ABORT,'audit failure'); END");assert.throws(()=>changeBranchLifecycle('10001',{lifecycleStatus:'CLOSED',reason:'Must roll back'},{changedBy:'Owner'},db),/audit failure/);assert.deepEqual({...db.prepare('SELECT lifecycle_status,status,is_active FROM branches WHERE id=1').get()},{lifecycle_status:'ACTIVE',status:'active',is_active:1})})

test('review navigation, UI controls, permission and i18n are wired without a top-level menu',()=>{const hub=fs.readFileSync(new URL('../src/WorkspaceHub.jsx',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../src/BranchLifecycleReviewPage.jsx',import.meta.url),'utf8'),server=fs.readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8'),app=fs.readFileSync(new URL('../src/App.jsx',import.meta.url),'utf8');assert.match(hub,/\['branch-review',t\('branchLifecycle\.reviewTitle'\)\]/);assert.match(hub,/BranchLifecycleReviewPage/);assert.doesNotMatch(app,/branch-review.*visibleNavigation/);for(const token of ['restoreActive','withReplacement','lastCollection','formatBranchId','onOpenBranch'])assert.match(ui,new RegExp(token));assert.match(server,/lifecycle[\s\S]{0,250}canManageBranches\(session\)/);for(const language of ['en','ms','zh'])for(const key of ['reviewTitle','operationalStatus','restoreActive','status.ACTIVE','status.TEMPORARILY_PAUSED','status.CLOSED','status.DUPLICATE_REPLACED','status.NOT_COLLECTING','status.TEST_INVALID'])assert.ok(messages[language][`branchLifecycle.${key}`]);assert.notEqual(messages.ms['branchLifecycle.reviewTitle'],messages.en['branchLifecycle.reviewTitle']);assert.equal(SCHEMA_VERSION,41)})

test('new operational queries use lifecycle ACTIVE while historical reads remain intact',()=>{for(const file of ['areaRefinementService.mjs','dispatchService.mjs','queryService.mjs','routeTemplateService.mjs']){const source=fs.readFileSync(new URL(`../server/${file}`,import.meta.url),'utf8');assert.match(source,/lifecycle_status/)}const route=fs.readFileSync(new URL('../server/routeTemplateService.mjs',import.meta.url),'utf8');assert.match(route,/lifecycleWarning/);assert.match(route,/unplaced[\s\S]*lifecycleStatus==='ACTIVE'/)})
