import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'

const source=readFileSync(new URL('../src/MasterDataPage.jsx',import.meta.url),'utf8')
const css=readFileSync(new URL('../src/MasterDataPage.css',import.meta.url),'utf8')
const server=readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8')

test('Buyer Branch cards open the editor with mouse and keyboard feedback',()=>{assert.match(source,/className="interactive-card buyer-branch-card"/);assert.match(source,/onClick=\{\(\)=>openBranch\(branch\)\}/);assert.match(source,/event\.key==='Enter'\|\|event\.key===' '/);assert.match(css,/\.buyer-branch-card\{cursor:pointer/);assert.match(css,/@media\(max-width:600px\).*\.buyer-branch-card\{width:100%;max-width:100%\}/s)})
test('Buyer Branch cards show concise contact, GPS, materials and route summaries without empty labels',()=>{assert.match(source,/const hasContact=Boolean\(branch\.contactPerson\|\|branch\.phone\),hasGps=/);assert.match(source,/\[branch\.contactPerson,branch\.phone\]\.filter\(Boolean\)\.join\(' · '\)/);assert.match(source,/hasContact&&<p className="buyer-branch-contact"/);assert.match(source,/branch\.acceptedMaterials&&<span/);assert.match(source,/buyerBranch\.gpsSet/);assert.match(source,/buyerBranch\.gpsNotSet/);assert.match(source,/buyerBranch\.routeEndpoint/);assert.match(source,/buyerBranch\.status\.\$\{branch\.status\}/);assert.match(css,/\.buyer-branch-badges\{display:flex;flex-wrap:wrap/);assert.match(css,/@media\(max-width:600px\).*\.buyer-branch-badges span\{white-space:normal\}/s)})
test('Buyer Branch editor shows immutable typed identity and parent while exposing branch fields',()=>{assert.match(source,/\['buyerBranchId','Buyer Branch ID','readonly'\]/);assert.match(source,/\['parentBuyerDisplay','Parent Buyer','readonly'\]/);for(const field of ['branchName','address','latitude','longitude','contactPerson','phone','businessHours','acceptedMaterials','unloadingRestrictions','priceNotes','operationalNotes','canEnd','status'])assert.match(source,new RegExp(`\\['${field}'`));assert.match(source,/parentBuyerDisplay:`\$\{formatBuyerId\(selected\.id\)\} — \$\{selected\.buyerName\}`/)})
test('PATCH uses an explicit allowlist, refreshes on success, preserves modal errors, and prevents repeat submit',()=>{assert.match(source,/import \{buildBuyerBranchPatch\}/);assert.match(source,/if\(savingBranch\)return/);assert.match(source,/payload=\{\.\.\.buildBuyerBranchPatch\(form\),\.\.\.actor\}/);assert.match(source,/setEditingBranch\(null\);await open\(selected\)/);assert.match(source,/catch\(error\)\{setBranchSaveError\(error\.message\);fail\(error\.message\)\}/);assert.match(source,/saving=\{savingBranch\} error=\{branchSaveError\}/);assert.match(source,/disabled=\{saving\}>\{saving\?'Saving\.\.\.'/);assert.match(server,/canManageBuyers=session=>\['owner_admin','operations_admin','supervisor','office'\]/);assert.match(server,/if\(!canManageBuyers\(session\)\)return sendJson\(response,403/);assert.match(server,/request\.method === 'PATCH' && \/\^\\\/api\\\/buyer-branches/)} )
test('Buyer Branch save refresh keeps the card summary current and sibling branches remain independent',()=>{assert.match(source,/setEditingBranch\(null\);await open\(selected\);notify/);assert.match(source,/selected\.branches\.map\(branch=>/);assert.match(source,/branch\.contactPerson/);assert.match(source,/branch\.phone/)})
