import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV30Migration} from '../server/migrationV30.mjs'
import {getBuyerDetail,listBuyerBranches,saveBuyer,saveBuyerBranch} from '../server/customerMasterService.mjs'
import {masterExport} from '../server/masterTransferService.mjs'
import {formatBuyerBranchId,parseTypedId} from '../shared/typedIds.js'

const fresh=()=>{const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;${schemaSql}`);return db}
test('BB typed IDs are strict and distinct from B/BY',()=>{assert.equal(formatBuyerBranchId(1),'BB10001');assert.equal(parseTypedId('bb10001','buyerbranch'),'1');assert.throws(()=>parseTypedId('B10001','buyerbranch'),/Buyer Branch ID/);assert.throws(()=>parseTypedId('BY10001','buyerbranch'),/Buyer Branch ID/)})
test('Buyer owns multiple independent Branch locations with non-reused global IDs and audit',()=>{const db=fresh(),buyer=saveBuyer({buyerName:'Mill'},null,db),first=saveBuyerBranch({parentBuyerId:buyer.id,branchName:'Mill Kuching',latitude:1.5,longitude:110.3,acceptedMaterials:'OCC',canEnd:true,changedBy:'Office',reason:'Create'},null,db),second=saveBuyerBranch({parentBuyerId:buyer.id,branchName:'Mill Serian',acceptedMaterials:'Metal',changedBy:'Office'},null,db);assert.equal(first.buyerBranchId,'BB10001');assert.equal(second.buyerBranchId,'BB10002');assert.equal(getBuyerDetail(buyer.id,db).branches.length,2);assert.equal(listBuyerBranches({search:'B10001'},db).length,0);assert.equal(listBuyerBranches({search:'BB10001'},db)[0].acceptedMaterials,'OCC');db.prepare("UPDATE operational_locations SET status='closed',is_active=0 WHERE id=?").run(second.id);const third=saveBuyerBranch({parentBuyerId:buyer.id,branchName:'Mill Bau'},null,db);assert.equal(third.buyerBranchId,'BB10003');assert.equal(db.prepare("SELECT COUNT(*) n FROM master_change_history WHERE entity_type='buyer_branch'").get().n,3);assert.equal(masterExport('buyer_branch',{},db).rows[0]['Buyer ID'],'BY10001')})
test('Buyer Branch identity and parent are immutable while normal fields remain editable',()=>{const db=fresh(),buyer=saveBuyer({buyerName:'Mill'},null,db),branch=saveBuyerBranch({parentBuyerId:buyer.id,branchName:'Gate A'},null,db);assert.throws(()=>saveBuyerBranch({buyerBranchId:'BB10999',branchName:'Changed'},branch.id,db),/cannot be changed/);const changed=saveBuyerBranch({branchName:'Gate B',status:'paused',reason:'Pause',changedBy:'Supervisor'},branch.id,db);assert.equal(changed.buyerBranchId,'BB10001');assert.equal(changed.branchName,'Gate B');assert.equal(changed.status,'paused')})
test('editing one Buyer Branch updates all supported fields, keeps its sibling unchanged, and audits before/after',()=>{const db=fresh(),buyer=saveBuyer({buyerName:'Mill'},null,db),first=saveBuyerBranch({parentBuyerId:buyer.id,branchName:'A'},null,db),second=saveBuyerBranch({parentBuyerId:buyer.id,branchName:'B'},null,db);const updated=saveBuyerBranch({branchName:'A2',address:'Road 2',latitude:1.55,longitude:110.35,contactPerson:'Lee',phone:'0123',businessHours:'8-5',acceptedMaterials:'OCC',unloadingRestrictions:'Call first',priceNotes:'Contract',operationalNotes:'Gate 2',canEnd:false,status:'paused',changedBy:'Office',reason:'Branch review'},first.id,db);assert.equal(updated.branchName,'A2');assert.equal(updated.address,'Road 2');assert.equal(updated.latitude,1.55);assert.equal(updated.acceptedMaterials,'OCC');assert.equal(updated.canEnd,0);assert.equal(updated.status,'paused');assert.equal(listBuyerBranches({search:'BB10002'},db)[0].branchName,'B');const audit=db.prepare("SELECT before_json,after_json,changed_by,reason FROM master_change_history WHERE entity_type='buyer_branch' AND entity_id='BB10001' ORDER BY id DESC LIMIT 1").get();assert.equal(JSON.parse(audit.before_json).name,'A');assert.equal(JSON.parse(audit.after_json).branchName,'A2');assert.equal(audit.changed_by,'Office');assert.equal(audit.reason,'Branch review');assert.equal(second.buyerBranchId,'BB10002')})
test('v29 to v30 is additive, transactional and idempotent',()=>{const db=fresh();db.prepare('DELETE FROM schema_meta').run();db.prepare('INSERT INTO schema_meta(version) VALUES(29)').run();db.exec('DROP TABLE system_sequences');const first=applyV30Migration(db),second=applyV30Migration(db);assert.equal(first.schemaVersion,30);assert.equal(second.noOp,true);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');for(const column of ['accepted_materials','unloading_restrictions','pricing_notes'])assert.ok(db.prepare('PRAGMA table_info(operational_locations)').all().some(row=>row.name===column))})
