import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV71Migration} from '../server/migrationV71.mjs'
import {startCargoBatch,cargoContext,lookupCargoBatch,joinCargoBatch,acknowledgeCargo} from '../server/cargoBatchService.mjs'
import {confirmUnloadingWeight} from '../server/unloadingWeightService.mjs'
const today='2026-09-18',driver={employeeId:1,role:'driver',today},crew={employeeId:2,role:'crew',today}
function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.exec(`
INSERT INTO employees(id,employee_code,name,job_role,employment_status,is_active) VALUES(1,'D1','Driver A','Driver','active',1),(2,'C1','Attendant B','crew','active',1),(3,'D2','Driver C','Driver','active',1),(4,'C2','Attendant D','crew','active',1);
INSERT INTO vehicles(id,vehicle_code,registration_number,status,operational_status) VALUES(1,'V1','AAA111','available','active'),(2,'V2','BBB222','available','active');
INSERT INTO weekly_dispatch_plans(id,week_start,status) VALUES(1,'2026-09-14','approved');
INSERT INTO dispatch_days(id,weekly_plan_id,dispatch_date,status) VALUES(1,1,'2026-09-18','in_progress');
INSERT INTO dispatches(id,dispatch_date,vehicle_id,driver_id,status) VALUES(1,'2026-09-18',1,1,'in_progress'),(2,'2026-09-18',2,3,'in_progress');
INSERT INTO dispatch_trips(id,dispatch_day_id,dispatch_id,trip_number,execution_status) VALUES(1,1,1,1,'in_progress'),(2,1,2,1,'in_progress');
INSERT INTO dispatch_vehicle_assistants(dispatch_day_id,vehicle_id,employee_id) VALUES(1,1,2),(1,2,4);
`);return db}
function record(db,id=1,who=1,vehicle=1){db.prepare(`INSERT INTO unloading_weight_records(id,dispatch_trip_id,dispatch_day_id,vehicle_id,driver_employee_id,service_date,trip_number,vehicle_code_snapshot,driver_name_snapshot,photo_storage_key,photo_original_name,photo_content_type,photo_size_bytes,weighed_at) VALUES(?,1,1,?,?,?,1,'V1','Driver',?,'test.png','image/png',8,CURRENT_TIMESTAMP)`).run(id,vehicle,who,today,'test-'+id)}
test('one current code; attendant self-confirmation persists; other car and forged identity denied',()=>{const db=fixture();try{const b=startCargoBatch(db,driver,1);assert.match(b.code,/^H260918-\d{3}$/);assert.equal(startCargoBatch(db,driver,1).id,b.id);assert.equal(b.members.length,1);assert.equal(lookupCargoBatch(db,crew,b.code).id,b.id);joinCargoBatch(db,crew,b.code);joinCargoBatch(db,crew,b.code);assert.equal(cargoContext(db,crew).items[0].members.length,2);assert.throws(()=>joinCargoBatch(db,{...crew,employeeId:4},b.code),{code:'CARGO_NOT_FOUND'});assert.throws(()=>startCargoBatch(db,crew,1),{code:'CARGO_DENIED'});assert.throws(()=>startCargoBatch(db,driver,2),{code:'CARGO_TRIP'});assert.equal(cargoContext(db,driver).notifications.length,1);acknowledgeCargo(db,crew,b.id);assert.equal(cargoContext(db,driver).notifications.length,1);acknowledgeCargo(db,driver,b.id);assert.equal(cargoContext(db,driver).notifications.length,0)}finally{db.close()}})
test('partial retains code; full creates exactly one prepared code and replay does not close next batch',()=>{const db=fixture();try{const b=startCargoBatch(db,driver,1);joinCargoBatch(db,crew,b.code);record(db);const partial=confirmUnloadingWeight(1,{weightKg:500,batchId:b.id,ticketNumber:'TN1',unloadMode:'partial'},driver,db);assert.equal(partial.cargo.batch.status,'active');assert.equal(partial.cargo.nextBatch,null);record(db,2);const full=confirmUnloadingWeight(2,{weightKg:600,batchId:b.id,ticketNumber:'TN2',unloadMode:'full'},driver,db);assert.equal(full.cargo.batch.status,'closed');assert.equal(full.cargo.nextBatch.status,'prepared');assert.equal(full.cargo.nextBatch.members.length,0);assert.equal(full.cargo.nextBatch.driverName,null);const repeat=confirmUnloadingWeight(2,{weightKg:900,batchId:full.cargo.nextBatch.id,ticketNumber:'TN3',unloadMode:'full'},driver,db);assert.equal(repeat.cargo.nextBatch.id,full.cargo.nextBatch.id);assert.equal(db.prepare('SELECT COUNT(*) n FROM cargo_batches').get().n,2);assert.equal(db.prepare('SELECT confirmed_weight_kg n FROM unloading_weight_records WHERE id=2').get().n,600);const next=startCargoBatch(db,driver,1);assert.equal(next.id,full.cargo.nextBatch.id);assert.equal(next.status,'active');record(db,3);confirmUnloadingWeight(3,{weightKg:100,batchId:b.id,ticketNumber:'TN4',unloadMode:'supplement'},driver,db);assert.equal(db.prepare('SELECT status FROM cargo_batches WHERE id=?').get(next.id).status,'active')}finally{db.close()}})
test('overnight driver change preserves original participants and cross-vehicle unload cannot link',()=>{const db=fixture();try{const b=startCargoBatch(db,driver,1);joinCargoBatch(db,crew,b.code);db.exec("UPDATE dispatch_days SET dispatch_date='2026-09-19';UPDATE dispatches SET dispatch_date='2026-09-19',driver_id=3 WHERE id=1;UPDATE dispatch_vehicle_assistants SET employee_id=4 WHERE vehicle_id=1;");const tomorrow={employeeId:3,role:'driver',today:'2026-09-19'};assert.equal(startCargoBatch(db,tomorrow,1).driverName,'Driver A');assert.throws(()=>joinCargoBatch(db,{...tomorrow,employeeId:4,role:'crew'},b.code),{code:'CARGO_JOIN'});record(db,1,3);const result=confirmUnloadingWeight(1,{weightKg:1200,batchId:b.id,ticketNumber:'TN5',unloadMode:'full'},tomorrow,db);assert.deepEqual(result.cargo.batch.members.map(m=>m.name).sort(),['Attendant B','Driver A']);assert.ok(cargoContext(db,crew).items.some(i=>i.id===b.id));record(db,2,3,2);assert.throws(()=>confirmUnloadingWeight(2,{weightKg:10,batchId:b.id,ticketNumber:'TN6',unloadMode:'supplement'},tomorrow,db),{code:'CARGO_NOT_FOUND'})}finally{db.close()}})
test('validation and audit failure roll back weight, batch closure and next number',()=>{const db=fixture();try{const b=startCargoBatch(db,driver,1);record(db);assert.throws(()=>confirmUnloadingWeight(1,{weightKg:20,batchId:b.id,ticketNumber:'',unloadMode:'full'},driver,db),{code:'CARGO_TICKET'});db.exec("CREATE TRIGGER fail_cargo_audit BEFORE INSERT ON audit_logs WHEN NEW.action='cargo_unloaded' BEGIN SELECT RAISE(ABORT,'test'); END;");assert.throws(()=>confirmUnloadingWeight(1,{weightKg:20,batchId:b.id,ticketNumber:'TN7',unloadMode:'full'},driver,db));assert.equal(db.prepare('SELECT status FROM cargo_batches WHERE id=?').get(b.id).status,'active');assert.equal(db.prepare('SELECT COUNT(*) n FROM cargo_batches').get().n,1);assert.equal(db.prepare('SELECT status FROM unloading_weight_records WHERE id=1').get().status,'pending_confirmation')}finally{db.close()}})
test('migration 71 is repeatable and retains existing records',()=>{const db=fixture();try{db.exec('INSERT INTO schema_meta(version) VALUES(70)');applyV71Migration(db);applyV71Migration(db);assert.equal(db.prepare('SELECT MAX(version) v FROM schema_meta').get().v,71);assert.equal(db.prepare('SELECT COUNT(*) n FROM employees').get().n,4);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')}finally{db.close()}})

test('new codes use three digits, grow beyond 999, and do not rename existing codes',()=>{
 const db=fixture();try{
  db.exec("INSERT INTO sqlite_sequence(name,seq) VALUES('cargo_batches',35)")
  const b=startCargoBatch(db,driver,1);assert.equal(b.code,'H260918-036')
  db.prepare('UPDATE cargo_batches SET code=? WHERE id=?').run('H260918-000036',b.id)
  assert.equal(startCargoBatch(db,driver,1).code,'H260918-000036')
  assert.equal(lookupCargoBatch(db,crew,'H260918-000036').id,b.id)
  db.exec("UPDATE sqlite_sequence SET seq=999 WHERE name='cargo_batches'")
  const next=startCargoBatch(db,{...driver,employeeId:3},2);assert.equal(next.code,'H260918-1000')
  assert.equal(db.prepare('SELECT COUNT(DISTINCT code) n FROM cargo_batches').get().n,2)
 }finally{db.close()}
})
