import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV46Migration} from '../server/migrationV46.mjs'
import {addCashFloatExpense,addCashFloatTopUp,configureCashFloat,listCashFloatAccounts,listCashFloatAlerts,mobileCashFloat,recordCashPurchase} from '../server/cashFloatService.mjs'

function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.prepare('INSERT INTO schema_meta(version) VALUES(45)').run();db.prepare("INSERT INTO employees(id,employee_code,name,job_role,employment_status,is_active) VALUES(1,'SUP-1','Supervisor','supervisor','active',1),(2,'DRV-2','Driver Two','driver','active',1)").run();return db}
const office={employeeId:1,employeeName:'Supervisor',now:new Date('2026-09-03T00:00:00Z')}

test('v46 migration preserves operational records and advances schema',()=>{const db=fixture(),before=db.prepare('SELECT COUNT(*) n FROM unloading_weight_records').get().n,result=applyV46Migration(db);assert.equal(result.schemaVersion,46);assert.equal(db.prepare('SELECT MAX(version) version FROM schema_meta').get().version,46);assert.equal(db.prepare('SELECT COUNT(*) n FROM unloading_weight_records').get().n,before);db.close()})

test('rolling float deducts purchases and expenses, alerts once, and resolves after top up',()=>{const db=fixture();configureCashFloat(2,{targetFloat:500,lowBalanceThreshold:200,currentBalance:500,serviceDate:'2026-09-03'},office,db);assert.equal(mobileCashFloat(2,db).balanceCents,50000);db.exec('PRAGMA foreign_keys=OFF');recordCashPurchase({id:101,billNumber:'P1',paymentMethod:'Cash',totalCents:15000,serviceDate:'2026-09-03',driverEmployeeId:2,driverName:'Driver Two'},db,{now:office.now});recordCashPurchase({id:101,billNumber:'P1',paymentMethod:'Cash',totalCents:15000,serviceDate:'2026-09-03',driverEmployeeId:2,driverName:'Driver Two'},db,{now:office.now});addCashFloatExpense(2,{amount:160,description:'Fuel',serviceDate:'2026-09-03'},office,db);let summary=mobileCashFloat(2,db);assert.equal(summary.balanceCents,19000);assert.equal(summary.today.purchaseCents,15000);assert.equal(summary.today.expenseCents,16000);assert.equal(listCashFloatAlerts(db).items.length,1);assert.equal(listCashFloatAlerts(db).items[0].suggestedTopUpCents,31000);addCashFloatTopUp(2,{amount:310,paymentChannel:'TNG',referenceNumber:'TNG-1',serviceDate:'2026-09-03'},office,db);summary=mobileCashFloat(2,db);assert.equal(summary.balanceCents,50000);assert.equal(summary.today.topUpCents,31000);assert.equal(listCashFloatAlerts(db).items.length,0);assert.equal(listCashFloatAccounts({},db).items.find(item=>item.employeeId===2).suggestedTopUpCents,0);db.close()})

test('Credit purchases do not affect Cash Float and threshold must be below target',()=>{const db=fixture();configureCashFloat(2,{targetFloat:800,lowBalanceThreshold:250,currentBalance:300},office,db);assert.equal(recordCashPurchase({id:102,paymentMethod:'Credit',totalCents:9999,driverEmployeeId:2},db),null);assert.equal(mobileCashFloat(2,db).balanceCents,30000);assert.throws(()=>configureCashFloat(2,{targetFloat:500,lowBalanceThreshold:500},office,db),/lower than Target/);db.close()})

test('UI exposes separate Cash Float management, browser alert and compact employee balance',()=>{const app=fs.readFileSync(new URL('../src/App.jsx',import.meta.url),'utf8'),officePage=fs.readFileSync(new URL('../src/CashFloatPage.jsx',import.meta.url),'utf8'),mobile=fs.readFileSync(new URL('../src/AuthPages.jsx',import.meta.url),'utf8');assert.match(app,/cash-float/);assert.match(app,/CashFloatAlertWatcher/);assert.match(officePage,/Target Float/);assert.match(officePage,/Low Balance Alert/);assert.match(officePage,/Enable Browser Alerts/);assert.match(officePage,/Download Excel/);assert.match(mobile,/Current Balance/);assert.match(mobile,/Record Expense/)})
