import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV46Migration} from '../server/migrationV46.mjs'
import {applyV47Migration} from '../server/migrationV47.mjs'
import {applyV48Migration} from '../server/migrationV48.mjs'
import {addAdminExpense,addCashFloatExpense,addCashFloatTopUp,configureCashFloat,expenseRecordsWorkbook,listCashFloatAccounts,listCashFloatAlerts,listCashFloatEmployees,listExpenseRecords,mobileCashFloat,recordCashPurchase,setCashFloatEmployees} from '../server/cashFloatService.mjs'

function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.prepare('INSERT INTO schema_meta(version) VALUES(45)').run();db.prepare("INSERT INTO employees(id,employee_code,name,job_role,employment_status,is_active) VALUES(1,'SUP-1','Supervisor','supervisor','active',1),(2,'DRV-2','Driver Two','driver','active',1)").run();return db}
const office={employeeId:1,employeeName:'Supervisor',now:new Date('2026-09-03T00:00:00Z')}

test('v46 migration preserves operational records and advances schema',()=>{const db=fixture(),before=db.prepare('SELECT COUNT(*) n FROM unloading_weight_records').get().n,result=applyV46Migration(db);assert.equal(result.schemaVersion,46);assert.equal(db.prepare('SELECT MAX(version) version FROM schema_meta').get().version,46);assert.equal(db.prepare('SELECT COUNT(*) n FROM unloading_weight_records').get().n,before);db.close()})

test('rolling float deducts purchases and expenses, alerts once, and resolves after top up',()=>{const db=fixture();configureCashFloat(2,{targetFloat:500,lowBalanceThreshold:200,currentBalance:500,serviceDate:'2026-09-03'},office,db);assert.equal(mobileCashFloat(2,db).balanceCents,50000);db.exec('PRAGMA foreign_keys=OFF');recordCashPurchase({id:101,billNumber:'P1',paymentMethod:'Cash',totalCents:15000,serviceDate:'2026-09-03',driverEmployeeId:2,driverName:'Driver Two'},db,{now:office.now});recordCashPurchase({id:101,billNumber:'P1',paymentMethod:'Cash',totalCents:15000,serviceDate:'2026-09-03',driverEmployeeId:2,driverName:'Driver Two'},db,{now:office.now});addCashFloatExpense(2,{amount:160,description:'Fuel',serviceDate:'2026-09-03'},office,db);let summary=mobileCashFloat(2,db);assert.equal(summary.balanceCents,19000);assert.equal(summary.today.purchaseCents,15000);assert.equal(summary.today.expenseCents,16000);assert.equal(listCashFloatAlerts(db).items.length,1);assert.equal(listCashFloatAlerts(db).items[0].suggestedTopUpCents,31000);addCashFloatTopUp(2,{amount:310,paymentChannel:'TNG',referenceNumber:'TNG-1',serviceDate:'2026-09-03'},office,db);summary=mobileCashFloat(2,db);assert.equal(summary.balanceCents,50000);assert.equal(summary.today.topUpCents,31000);assert.equal(listCashFloatAlerts(db).items.length,0);assert.equal(listCashFloatAccounts({},db).items.find(item=>item.employeeId===2).suggestedTopUpCents,0);db.close()})

test('Credit purchases do not affect Cash Float and threshold must be below target',()=>{const db=fixture();configureCashFloat(2,{targetFloat:800,lowBalanceThreshold:250,currentBalance:300},office,db);assert.equal(recordCashPurchase({id:102,paymentMethod:'Credit',totalCents:9999,driverEmployeeId:2},db),null);assert.equal(mobileCashFloat(2,db).balanceCents,30000);assert.throws(()=>configureCashFloat(2,{targetFloat:500,lowBalanceThreshold:500},office,db),/lower than Target/);db.close()})

test('v47 employee selection hides cards without deleting balances and supports later reactivation',()=>{const db=fixture();applyV46Migration(db);configureCashFloat(2,{targetFloat:500,lowBalanceThreshold:200,currentBalance:350},office,db);db.exec('DROP TABLE cash_float_members');applyV47Migration(db);assert.equal(listCashFloatAccounts({},db).items.length,1);setCashFloatEmployees([],office,db);assert.equal(listCashFloatAccounts({},db).items.length,0);assert.equal(mobileCashFloat(2,db).configured,false);assert.equal(db.prepare('SELECT SUM(amount_cents) balance FROM cash_float_transactions WHERE employee_id=2').get().balance,35000);setCashFloatEmployees([2],office,db);assert.equal(listCashFloatAccounts({},db).items[0].balanceCents,35000);assert.equal(listCashFloatEmployees(db).items.find(item=>item.employeeId===2).selected,true);db.close()})

test('v48 migration adds Admin Expenses without changing operational records',()=>{const db=fixture();applyV46Migration(db);applyV47Migration(db);db.exec('DROP TABLE admin_expense_records');const result=applyV48Migration(db);assert.equal(result.schemaVersion,48);assert.equal(db.prepare('SELECT MAX(version) version FROM schema_meta').get().version,48);assert.ok(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='admin_expense_records'").get());assert.deepEqual(result.before,result.after);db.close()})

test('UI exposes Cash Float employee selection and a controlled mobile expense description',()=>{const app=fs.readFileSync(new URL('../src/App.jsx',import.meta.url),'utf8'),officePage=fs.readFileSync(new URL('../src/CashFloatPage.jsx',import.meta.url),'utf8'),mobile=fs.readFileSync(new URL('../src/AuthPages.jsx',import.meta.url),'utf8');assert.match(app,/cash-float/);assert.match(app,/CashFloatAlertWatcher/);assert.match(officePage,/Target Float/);assert.match(officePage,/Low Balance Alert/);assert.match(officePage,/Manage Employees/);assert.match(officePage,/Save Selection/);assert.match(officePage,/Enable Browser Alerts/);assert.match(officePage,/Download Excel/);assert.match(mobile,/Current Balance/);assert.match(mobile,/Record Expense/);for(const item of ['Fuel','Services','Repair','Spare Parts','Road Tax','Puspakom','Insurance','Other'])assert.match(mobile,new RegExp(`['"]${item}['"]`));assert.match(mobile,/Select description/);assert.match(mobile,/Other description/)})

test('Expense Records separates Employee and Admin expenses and only Employee expense deducts Cash Float',async()=>{const db=fixture();configureCashFloat(2,{targetFloat:500,lowBalanceThreshold:100,currentBalance:500,serviceDate:'2026-09-03'},office,db);db.prepare("INSERT INTO employees(id,employee_code,name,job_role,employment_status,is_active) VALUES(3,'CRW-3','Crew Three','crew','active',1)").run();db.prepare('INSERT INTO cash_float_members(employee_id,is_selected,updated_at) VALUES(3,1,CURRENT_TIMESTAMP)').run();addCashFloatTopUp(2,{amount:20,paymentChannel:'Cash',serviceDate:'2026-09-03'},office,db);addCashFloatExpense(2,{amount:70,description:'Fuel',referenceNumber:'F-1',serviceDate:'2026-09-03'},office,db);addCashFloatExpense(2,{amount:30,description:'Parking',serviceDate:'2026-09-02'},office,db);assert.equal(mobileCashFloat(2,db).balanceCents,42000);addAdminExpense({amount:50,category:'Services',description:'Services',paymentMethod:'Bank Transfer',referenceNumber:'A-1',serviceDate:'2026-09-03'},office,db);assert.equal(mobileCashFloat(2,db).balanceCents,42000);const all=listExpenseRecords({from:'2026-09-01',to:'2026-09-03'},db);assert.equal(all.items.length,3);assert.equal(all.totalCents,15000);assert.equal(all.employees.find(item=>item.employeeId===3).configured,false);assert.equal(listExpenseRecords({expenseType:'admin'},db).items[0].paymentMethod,'Bank Transfer');assert.equal(listExpenseRecords({expenseType:'employee'},db).items.length,2);assert.equal(listExpenseRecords({category:'Other'},db).items[0].description,'Parking');assert.equal(listExpenseRecords({search:'A-1'},db).items[0].expenseType,'admin');const workbook=await expenseRecordsWorkbook({},db);assert.ok(workbook.length>1000);db.close()})

test('office navigation exposes Employee and Admin Expense entry without summary cards',()=>{const app=fs.readFileSync(new URL('../src/App.jsx',import.meta.url),'utf8'),page=fs.readFileSync(new URL('../src/ExpenseRecordsPage.jsx',import.meta.url),'utf8');assert.match(app,/expense-records/);assert.match(app,/ExpenseRecordsPage/);assert.match(page,/Record Expense/);assert.match(page,/Employee Expense/);assert.match(page,/Admin Expense/);assert.match(page,/Payment Method/);assert.match(page,/Not Set Up/);assert.match(page,/Download Excel with Receipts/);assert.match(page,/View receipt/);assert.doesNotMatch(page,/Total Expenses/);for(const item of ['Fuel','Services','Repair','Spare Parts','Road Tax','Puspakom','Insurance','Other'])assert.match(page,new RegExp(`['"]${item}['"]`))})
