import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {getCollectionScheduleManagement,listCollectionScheduleManagement,saveCollectionScheduleManagement} from '../server/collectionScheduleManagementService.mjs'

function fixture({schedule=true,sundayCustomer=false}={}){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.exec(`INSERT INTO zone_groups(id,code,name) VALUES(101,'ZM1','Provisional'),(102,'ZM2','Confirmed');INSERT INTO areas(id,jodoo_area_id,name,zone_group_id,confirmed_zone_group_id) VALUES(101,'AM1','Area One',101,102);INSERT INTO customers(id,jodoo_customer_id,name) VALUES(1,'C1','${sundayCustomer?'Everrise':'Ordinary'}');INSERT INTO branches(id,jodoo_branch_id,customer_id,area_id,branch_name,collection_frequency,assigned_weekdays,lifecycle_status,status,is_active) VALUES(101,'1001',1,101,'Alpha','Once a week','["Monday"]','ACTIVE','active',1),(102,'1002',1,101,'No Schedule',NULL,NULL,'ACTIVE','active',1),(103,'1003',1,101,'Closed',NULL,NULL,'CLOSED','paused',0)`);if(schedule)db.exec(`INSERT INTO branch_schedules(id,jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week,is_active) VALUES(1,'S1',101,'1001','Once a week','["Monday"]',1)`);return db}
const payload=(item,extra={})=>({frequency:'Twice a week',weekdays:['Monday','Thursday'],reason:'Approved maintenance',expectedUpdatedAt:item.updatedAt,changedBy:'Supervisor',...extra})

test('twice weekly saves all days and atomically synchronizes Branch and Schedule',()=>{const db=fixture(),item=getCollectionScheduleManagement('B1001',db),result=saveCollectionScheduleManagement('B1001',payload(item),db);assert.deepEqual(result.after.weekdays,['Monday','Thursday']);assert.equal(db.prepare('SELECT collection_frequency f FROM branches WHERE id=101').get().f,'Twice a week');assert.equal(db.prepare('SELECT frequency f FROM branch_schedules WHERE id=1').get().f,'Twice a week')})
test('twice weekly with one day rejects',()=>{const db=fixture(),item=getCollectionScheduleManagement('1001',db);assert.throws(()=>saveCollectionScheduleManagement('1001',payload(item,{weekdays:['Monday']}),db),/exactly 2/)})
test('On Call clears weekdays',()=>{const db=fixture(),item=getCollectionScheduleManagement('1001',db);saveCollectionScheduleManagement('1001',payload(item,{frequency:'On Call',weekdays:['Monday']}),db);assert.equal(db.prepare('SELECT days_of_week d FROM branch_schedules').get().d,null)})
test('interval anchor mismatch and monthly missing occurrence reject',()=>{const db=fixture(),item=getCollectionScheduleManagement('1001',db);assert.throws(()=>saveCollectionScheduleManagement('1001',payload(item,{frequency:'Every 2 Weeks',weekdays:['Monday'],anchorDate:'2026-08-25'}),db),/fall on/);assert.throws(()=>saveCollectionScheduleManagement('1001',payload(item,{frequency:'Monthly',weekdays:['Monday'],anchorDate:'2026-08-24'}),db),/occurrence is required/)})
test('duplicate active schedules block',()=>{const db=fixture();db.exec(`INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,is_active) VALUES('S2',101,'1001','On Call',1)`);const item=getCollectionScheduleManagement('1001',db);assert.equal(item.blocked,true);assert.throws(()=>saveCollectionScheduleManagement('1001',payload(item),db),/Blocked/)})
test('missing Schedule creates one safely with source Branch ID',()=>{const db=fixture(),item=getCollectionScheduleManagement('1002',db),result=saveCollectionScheduleManagement('B1002',payload(item,{frequency:'Once a week',weekdays:['Tuesday']}),db);assert.equal(result.action,'create');assert.deepEqual({...db.prepare('SELECT COUNT(*) n,source_branch_id source FROM branch_schedules WHERE branch_id=102').get()},{n:1,source:'1002'})})
test('new Sunday is restricted while an existing Sunday is preserved',()=>{let db=fixture(),item=getCollectionScheduleManagement('1001',db);assert.throws(()=>saveCollectionScheduleManagement('1001',payload(item,{frequency:'Once a week',weekdays:['Sunday']}),db),/Sunday/);db=fixture({sundayCustomer:true});item=getCollectionScheduleManagement('1001',db);assert.doesNotThrow(()=>saveCollectionScheduleManagement('1001',payload(item,{frequency:'Once a week',weekdays:['Sunday']}),db))})
test('dry run has no database or audit mutation',()=>{const db=fixture(),item=getCollectionScheduleManagement('1001',db),changes=db.prepare('SELECT total_changes() n').get().n,result=saveCollectionScheduleManagement('1001',payload(item,{dryRun:true}),db);assert.equal(result.dryRun,true);assert.equal(db.prepare('SELECT total_changes() n').get().n,changes);assert.equal(db.prepare('SELECT COUNT(*) n FROM audit_logs').get().n,0)})
test('final save writes both audit systems',()=>{const db=fixture(),item=getCollectionScheduleManagement('1001',db);saveCollectionScheduleManagement('1001',payload(item),db);assert.equal(db.prepare('SELECT COUNT(*) n FROM master_change_history').get().n,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM audit_logs').get().n,1)})
test('expectedUpdatedAt conflict returns 409 and commits nothing',()=>{const db=fixture(),item=getCollectionScheduleManagement('1001',db);db.exec(`UPDATE branches SET updated_at='2099-01-01' WHERE id=101`);assert.throws(()=>saveCollectionScheduleManagement('1001',payload(item),db),error=>error.statusCode===409);assert.equal(db.prepare('SELECT frequency FROM branch_schedules').get().frequency,'Once a week')})
test('existing Dispatch Stops are unchanged and reported',()=>{const db=fixture(),item=getCollectionScheduleManagement('1001',db);db.exec(`INSERT INTO dispatches(id,dispatch_date,status) VALUES(1,'2099-01-01','released');INSERT INTO dispatch_stops(id,dispatch_id,branch_id,stop_sequence,status) VALUES(1,1,101,1,'locked')`);const result=saveCollectionScheduleManagement('1001',payload(item,{effectiveDate:'2026-01-01'}),db);assert.equal(result.futureStopCount,1);assert.deepEqual({...db.prepare('SELECT branch_id,status FROM dispatch_stops WHERE id=1').get()},{branch_id:101,status:'locked'})})
test('list includes active missing Schedule, excludes non-ACTIVE, and resolves confirmed Zone',()=>{const items=listCollectionScheduleManagement({},fixture());assert.deepEqual(items.map(x=>x.branchId),['1001','1002']);assert.equal(items[1].scheduleCount,0);assert.equal(items[0].zone,'Confirmed')})
test('list search accepts Branch ID with uppercase or lowercase B prefix',()=>{const db=fixture();for(const search of ['1001','B1001','b1001'])assert.deepEqual(listCollectionScheduleManagement({search},db).map(x=>x.branchId),['1001'])})
test('Schedule editor allows direct save once a reason is entered while preview remains optional',()=>{const source=readFileSync(new URL('../src/DataPages.jsx',import.meta.url),'utf8'),editor=source.slice(source.indexOf('function ScheduleEditor'),source.indexOf('const groupKeys'));assert.match(editor,/className="primary" disabled=\{busy\|\|!form\.reason\.trim\(\)\}/);assert.doesNotMatch(editor,/className="primary" disabled=\{busy\|\|!preview\}/)})
test('management PATCH route enforces schedule permission server-side',async()=>{const source=await import('node:fs').then(fs=>fs.readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8'));assert.match(source,/PATCH.*collection-schedule[\s\S]{0,250}!canManageSchedules\(session\).*403/)})
