import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {runCombinedImport} from '../scripts/import-occ-frequency-schedule-20260803.mjs'

function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.exec("DELETE FROM schema_meta; INSERT INTO schema_meta(version) VALUES(25); INSERT INTO customers(jodoo_customer_id,name,status,is_active) VALUES('C1','Customer','active',1); INSERT INTO branches(jodoo_branch_id,customer_id,branch_name,status,is_active,assigned_weekdays) VALUES('B1',1,'Branch','active',1,'[\"Monday\"]'); INSERT INTO materials(material_code,material_name,status) VALUES('OCC','OCC','active'); INSERT INTO occ_price_groups(material_id,item_code,price_amount,created_by) VALUES(1,'OCC-017',0.17,'test'),(1,'OCC-018',0.18,'test'); INSERT INTO branch_occ_price_assignments(branch_id,occ_price_group_id,assigned_by) VALUES(1,1,'test'); INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S1',1,'B1','Weekly','Monday')");return db}
const input={rows:[{excelRow:2,branchId:'B1',targetOccPrice:0.18,rawFrequency:'weekly'}],duplicateScheduleDecisions:[]}
test('combined import updates OCC and frequency, preserves weekday and is idempotent',()=>{const db=fixture(),weekday=db.prepare("SELECT assigned_weekdays v FROM branches WHERE jodoo_branch_id='B1'").get().v,first=runCombinedImport(db,input,{apply:true});assert.equal(first.write.occUpdated,1);assert.equal(first.write.frequencyAdded,1);assert.equal(first.write.weekdayWrites,0);assert.equal(db.prepare('SELECT occ_price_group_id id FROM branch_occ_price_assignments WHERE branch_id=1').get().id,2);assert.equal(db.prepare('SELECT assigned_weekdays v FROM branches WHERE id=1').get().v,weekday);const second=runCombinedImport(db,input,{apply:true});assert.equal(second.writes,0);db.close()})
test('transaction rolls back if OCC audit fails',()=>{const db=fixture();db.exec("CREATE TRIGGER reject_history BEFORE INSERT ON branch_occ_price_assignment_history BEGIN SELECT RAISE(ABORT,'blocked'); END");assert.throws(()=>runCombinedImport(db,input,{apply:true}),/blocked/);assert.equal(db.prepare('SELECT occ_price_group_id id FROM branch_occ_price_assignments WHERE branch_id=1').get().id,1);db.close()})
