import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {applyV61Migration,ensureV61Schema} from '../server/migrationV61.mjs'
import {readMenu,saveMenu} from '../server/menuLayoutService.mjs'
import {defaultMenuLayout,normalizeMenuLayout,validMenuLayout} from '../shared/menuLayout.js'
function fixture(){const db=new DatabaseSync(':memory:');db.exec("PRAGMA foreign_keys=ON;CREATE TABLE schema_meta(version INTEGER);INSERT INTO schema_meta VALUES(60);CREATE TABLE auth_accounts(id INTEGER PRIMARY KEY,username TEXT,is_active INTEGER);INSERT INTO auth_accounts VALUES(9,'kcadmin',1),(10,'another-admin',1);");applyV61Migration(db);return db}
test('only pinned account ID can write; admins and spoofed usernames cannot',()=>{const db=fixture(),payload={layout:defaultMenuLayout(),revision:0};assert.equal(readMenu(db,{id:9}).canEdit,true);for(const user of [{id:10,role:'owner_admin',username:'kcadmin'},{role:'owner_admin'},{}])assert.throws(()=>saveMenu(db,user,payload),e=>e.statusCode===403);assert.equal(db.prepare('SELECT COUNT(*) n FROM company_menu_audit').get().n,0);db.close()})
test('company order persists for other accounts, stale and invalid updates are atomic',()=>{const db=fixture(),layout=defaultMenuLayout();layout.top.reverse();layout.documents.reverse();saveMenu(db,{id:9},{layout,revision:0});assert.deepEqual(readMenu(db,{id:10}).layout,layout);assert.throws(()=>saveMenu(db,{id:9},{layout,revision:0}),e=>e.statusCode===409);assert.throws(()=>saveMenu(db,{id:9},{layout:{...layout,top:['sales']},revision:1}),e=>e.statusCode===400);assert.equal(readMenu(db,{id:9}).revision,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM company_menu_audit').get().n,1);db.close()})
test('owner binding survives username changes and migration reruns',()=>{const db=fixture();db.exec("UPDATE auth_accounts SET username='renamed' WHERE id=9;UPDATE auth_accounts SET username='kcadmin' WHERE id=10;");ensureV61Schema(db);assert.equal(readMenu(db,{id:9}).canEdit,true);assert.equal(readMenu(db,{id:10}).canEdit,false);assert.equal(db.prepare('SELECT MAX(version) v FROM schema_meta').get().v,61);db.close()})

test('custom folders persist names and every page, retain auditing and reject stale saves',()=>{const db=fixture(),layout=defaultMenuLayout();layout.folders=[{id:'folder-office',name:'Office 工作',items:['dashboard','sales']}];layout.top=layout.top.filter(id=>id!=='dashboard');layout.documents=layout.documents.filter(id=>id!=='sales');layout.top.unshift('folder-office');layout.documentName='Bills';assert(validMenuLayout(layout));saveMenu(db,{id:9},{layout,revision:0});assert.deepEqual(readMenu(db,{id:10}).layout,layout);assert.deepEqual(JSON.parse(db.prepare('SELECT after_json FROM company_menu_audit').get().after_json),layout);assert.throws(()=>saveMenu(db,{id:10},{layout,revision:1}),e=>e.statusCode===403);assert.throws(()=>saveMenu(db,{id:9},{layout,revision:0}),e=>e.statusCode===409);db.close()})
test('folder validation prevents lost/duplicate pages, cycles, unknown pages and invalid names',()=>{for(const alter of [l=>l.documents.pop(),l=>l.top.push('sales'),l=>l.top.push('unknown'),l=>{l.folders=[{id:'folder-a',name:'A',items:['folder-a']}];l.top.push('folder-a')},l=>{l.folders=[{id:'folder-a',name:' ',items:[]}];l.top.push('folder-a')},l=>{l.documentName='x'.repeat(61)}]){const layout=defaultMenuLayout();alter(layout);assert.equal(validMenuLayout(layout),false)}})
test('legacy menu order is retained and missing notice inserted without writing on read',()=>{const db=fixture(),old=defaultMenuLayout();old.top.reverse();old.top=old.top.filter(id=>id!=='notices');db.prepare('UPDATE company_menu SET layout_json=?').run(JSON.stringify(old));const before=db.prepare('SELECT total_changes() n').get().n,r=readMenu(db,{id:9});assert.equal(r.layout.top.filter(id=>id==='notices').length,1);assert.deepEqual(r.layout.top.filter(id=>id!=='notices'),old.top);assert.equal(db.prepare('SELECT total_changes() n').get().n,before);assert(validMenuLayout(normalizeMenuLayout(r.layout)));db.close()})
