import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV26Migration,ensureV26Schema} from '../server/migrationV26.mjs'
import {createScheduleException,createStop,generateDay,getDispatchDay} from '../server/dispatchService.mjs'
import {applyDuplicateScheduleCleanup,previewDuplicateScheduleCleanup} from '../server/duplicateScheduleCleanupService.mjs'
import {listBranchServiceDateConflicts} from '../server/branchServiceDateGuard.mjs'
import {createSpecialRequest,scheduleSpecialRequest} from '../server/specialRequestService.mjs'

function fixture({twoSchedules=true}={}){
  const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql)
  db.exec("INSERT INTO customers(jodoo_customer_id,name) VALUES('C1','Customer'); INSERT INTO branches(jodoo_branch_id,customer_id,branch_name,status,is_active) VALUES('B1',1,'Branch','active',1),('B2',1,'Other','active',1); INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week,is_active) VALUES('S1',1,'B1','Weekly','Monday',1)")
  if(twoSchedules)db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week,is_active) VALUES('S2',1,'B1','Weekly','Monday',1)").run()
  return db
}

test('two active schedules for one Branch create one Stop on one service date',()=>{const db=fixture();const result=generateDay({startDate:'2026-08-03'},db);assert.equal(db.prepare("SELECT COUNT(*) n FROM dispatch_stops WHERE status<>'cancelled'").get().n,1);assert.equal(result.duplicateStops.length,1);assert.equal(result.duplicateStops[0].code,'DUPLICATE_BRANCH_SERVICE_DATE')})
test('same schedule repeat remains idempotent',()=>{const db=fixture({twoSchedules:false});generateDay({startDate:'2026-08-03'},db);generateDay({startDate:'2026-08-03'},db);assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_stops').get().n,1)})
test('different Branches on one date and one Branch on different dates are valid',()=>{const db=fixture({twoSchedules:false});db.exec("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week,is_active) VALUES('S3',2,'B2','Weekly','Monday',1)");generateDay({startDate:'2026-08-03'},db);generateDay({startDate:'2026-08-10'},db);assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_stops').get().n,4)})
test('manual and special exception entry paths cannot add a duplicate Branch/date',()=>{const db=fixture({twoSchedules:false});generateDay({startDate:'2026-08-03'},db);assert.throws(()=>createStop({date:'2026-08-03',branchId:'B1'},db),error=>error.code==='DUPLICATE_BRANCH_SERVICE_DATE'&&error.existingStopId===1);createScheduleException({scheduleId:'S1',type:'add_extra_collection',targetDate:'2026-08-03',createdBy:'Supervisor'},db);generateDay({startDate:'2026-08-03'},db);assert.equal(db.prepare("SELECT COUNT(*) n FROM dispatch_stops WHERE status<>'cancelled'").get().n,1)})
test('a second special request cannot silently share an existing Branch/date Stop',()=>{const db=fixture({twoSchedules:false});generateDay({startDate:'2026-08-03'},db);const first=createSpecialRequest({existingBranchId:'B1',requestedCollectionDate:'2026-08-03',phone:'1'},db),second=createSpecialRequest({existingBranchId:'B1',requestedCollectionDate:'2026-08-03',phone:'2'},db),before=db.prepare('SELECT status FROM special_collection_requests WHERE id=?').get(second.id).status;scheduleSpecialRequest(first.id,{date:'2026-08-03'},db);assert.throws(()=>scheduleSpecialRequest(second.id,{date:'2026-08-03'},db),error=>error.code==='DUPLICATE_BRANCH_SERVICE_DATE');assert.equal(db.prepare('SELECT status FROM special_collection_requests WHERE id=?').get(second.id).status,before)})
test('cancelled Stop permits an audited replacement without displaying the cancelled route',()=>{const db=fixture({twoSchedules:false});generateDay({startDate:'2026-08-03'},db);db.prepare("UPDATE dispatch_stops SET status='cancelled' WHERE id=1").run();const replacement=createStop({date:'2026-08-03',branchId:'B1'},db);assert.ok(replacement.id>1);assert.equal(getDispatchDay('2026-08-03',db).stops.length,1)})
test('mid-transaction generation failure rolls back occurrence, Stop and day',()=>{const db=fixture({twoSchedules:false});db.exec("CREATE TRIGGER fail_stop BEFORE INSERT ON dispatch_stops BEGIN SELECT RAISE(ABORT,'forced stop failure'); END");assert.throws(()=>generateDay({startDate:'2026-08-03'},db),/forced stop failure/);assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_days').get().n,0);assert.equal(db.prepare('SELECT COUNT(*) n FROM schedule_occurrences').get().n,0)})
test('v25 migration detects legacy duplicates without deleting or half-enforcing them',()=>{const db=fixture({twoSchedules:false});db.exec("DELETE FROM schema_meta; INSERT INTO schema_meta(version) VALUES(25); INSERT INTO weekly_dispatch_plans(week_start) VALUES('2026-08-03'); INSERT INTO dispatch_days(weekly_plan_id,dispatch_date) VALUES(1,'2026-08-03'); INSERT INTO dispatches(dispatch_date) VALUES('2026-08-03'),('2026-08-03'); INSERT INTO dispatch_trips(dispatch_day_id,dispatch_id,trip_number) VALUES(1,1,0),(1,2,0); INSERT INTO dispatch_stops(dispatch_id,branch_id,stop_sequence,status,dispatch_trip_id,source_schedule_id,dedupe_enforced) VALUES(1,1,1,'locked',1,1,0),(2,1,1,'locked',2,1,0)");const result=applyV26Migration(db);assert.equal(result.routeGenerationBlocked,true);assert.equal(result.branchServiceDateConflicts.length,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_stops').get().n,2);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})
test('v25 database without schedule_occurrences upgrades atomically',()=>{const db=fixture({twoSchedules:false});db.exec('DROP TABLE schedule_occurrences; DELETE FROM schema_meta; INSERT INTO schema_meta(version) VALUES(25)');const result=applyV26Migration(db);assert.equal(result.schemaVersion,26);assert.equal(db.prepare("SELECT COUNT(*) n FROM pragma_table_info('schedule_occurrences') WHERE name='branch_id'").get().n,1);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})

function cleanupFixture(){
  const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql)
  ensureV26Schema(db)
  db.exec("INSERT INTO customers(jodoo_customer_id,name) VALUES('C1','DCH TECHNOLOGY'),('C2','SK HARDWARE'),('C3','DIY'),('C4','CCK LOCAL'),('C5','CARING FARMASI'),('C6','FARLEY'); INSERT INTO branches(jodoo_branch_id,customer_id,branch_name,status,is_active) VALUES('10050',1,'DCH TECHNOLOGY','active',1),('10278',2,'SK HARDWARE','active',1),('10084',3,'DIY KBH PUNCAK BORENO','active',1),('10033',4,'CCK LOCAL CITY MALL','active',1),('10030',5,'CARING FARMASI','active',1),('10146',6,'FARLEY BAKERY','active',1); INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week,is_active) VALUES('10069',1,'10050','Weekly','Monday,Thursday',1),('10330',1,'10050','Weekly','Monday,Thursday',1),('10280',2,'10278','Weekly','Monday,Wednesday,Friday',1),('10317',2,'10278','Weekly','Monday,Wednesday,Friday',1),('10321',3,'10084','Weekly','Tuesday,Friday',1),('10086',3,'10084','Weekly','Tuesday,Friday',1),('10346',4,'10033','Weekly','Wednesday',1),('10312',4,'10033','Weekly','Wednesday',1),('10410',5,'10030','Weekly','Friday,Tuesday',1),('10032',5,'10030','Weekly','Friday',1),('10391',6,'10146','Weekly','Wednesday',1),('10148',6,'10146','Weekly','Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',1)")
  const pairs=[['2026-07-20',1,1,2],['2026-07-23',1,1,2],['2026-07-27',1,1,2],['2026-07-20',2,3,4],['2026-07-22',2,3,4],['2026-07-24',2,3,4],['2026-07-27',2,3,4],['2026-07-21',3,5,6],['2026-07-24',3,5,6],['2026-07-22',4,7,8],['2026-07-24',5,9,10],['2026-07-22',6,11,12]]
  let seq=0
  const tripFor=date=>{db.prepare('INSERT OR IGNORE INTO weekly_dispatch_plans(week_start) VALUES(?)').run(date);const plan=Number(db.prepare('SELECT id FROM weekly_dispatch_plans WHERE week_start=?').get(date).id);db.prepare('INSERT OR IGNORE INTO dispatch_days(weekly_plan_id,dispatch_date) VALUES(?,?)').run(plan,date);const day=Number(db.prepare('SELECT id FROM dispatch_days WHERE dispatch_date=?').get(date).id);db.prepare("INSERT INTO dispatches(dispatch_date,status) VALUES(?,'draft')").run(date);const dispatch=Number(db.prepare('SELECT last_insert_rowid() id').get().id);db.prepare('INSERT INTO dispatch_trips(dispatch_day_id,dispatch_id,trip_number) VALUES(?,?,0)').run(day,dispatch);return{dispatch,trip:Number(db.prepare('SELECT last_insert_rowid() id').get().id)}}
  for(const [date,branch,canonical,superseded] of pairs){const {dispatch,trip}=tripFor(date);db.prepare("INSERT INTO dispatch_stops(dispatch_id,branch_id,stop_sequence,status,dispatch_trip_id,source_schedule_id,service_date,dedupe_enforced) VALUES(?,?,?,'locked',?,?,?,0),(?,?,?,'locked',?,?,?,0)").run(dispatch,branch,++seq,trip,canonical,date,dispatch,branch,++seq,trip,superseded,date)}
  for(const date of ['2026-07-20','2026-07-21','2026-07-23','2026-07-24','2026-07-25','2026-07-26','2026-07-27']){const {dispatch,trip}=tripFor(date);db.prepare("INSERT INTO dispatch_stops(dispatch_id,branch_id,stop_sequence,status,dispatch_trip_id,source_schedule_id,service_date,dedupe_enforced) VALUES(?,?,?,'locked',?,?,?,0)").run(dispatch,6,++seq,trip,12,date)}
  return db
}

test('approved cleanup resolves twelve conflicts and archives all eight FARLEY legacy drafts',()=>{const db=cleanupFixture(),preview=previewDuplicateScheduleCleanup(db);assert.equal(preview.counts.stopPairs,12);assert.equal(preview.counts.additionalDraftStops,7);assert.equal(preview.counts.completedStopsToModify,0);const result=applyDuplicateScheduleCleanup(db,{changedBy:'Technical Admin',reason:'Approved v26 duplicate resolution'});assert.equal(result.stopsCancelled,19);assert.equal(result.schedulesSuperseded,6);assert.equal(listBranchServiceDateConflicts(db).length,0);assert.equal(db.prepare("SELECT COUNT(*) n FROM branch_schedules WHERE jodoo_schedule_id='10391' AND is_active=1 AND days_of_week='Wednesday'").get().n,1);assert.equal(db.prepare("SELECT COUNT(*) n FROM branch_schedules WHERE jodoo_schedule_id='10148' AND is_active=0").get().n,1);assert.equal(db.prepare("SELECT COUNT(*) n FROM dispatch_stops WHERE source_schedule_id=12 AND status='cancelled'").get().n,8);assert.equal(applyDuplicateScheduleCleanup(db,{changedBy:'Technical Admin',reason:'Idempotency check'}).stopsCancelled,0)})
test('FARLEY cleanup rolls back when any superseded draft has business activity',()=>{const db=cleanupFixture();const stop=db.prepare('SELECT id FROM dispatch_stops WHERE source_schedule_id=12 ORDER BY id LIMIT 1').get();db.prepare("UPDATE dispatch_stops SET collected_weight_kg=1 WHERE id=?").run(stop.id);assert.throws(()=>applyDuplicateScheduleCleanup(db,{changedBy:'Technical Admin',reason:'Test'}),/blocked/);assert.equal(db.prepare("SELECT is_active FROM branch_schedules WHERE jodoo_schedule_id='10148'").get().is_active,1);assert.equal(db.prepare("SELECT COUNT(*) n FROM dispatch_stops WHERE status='cancelled'").get().n,0)})
test('cleanup never modifies a Completed historical Stop and supersedes its inactive counterpart',()=>{const db=cleanupFixture();db.prepare("UPDATE dispatch_stops SET status='completed' WHERE id=2").run();const result=applyDuplicateScheduleCleanup(db,{changedBy:'Technical Admin',reason:'Test'});assert.equal(result.completedStopsModified,0);assert.equal(db.prepare('SELECT status FROM dispatch_stops WHERE id=2').get().status,'completed');assert.equal(db.prepare('SELECT status FROM dispatch_stops WHERE id=1').get().status,'cancelled')})
