import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV42Migration} from '../server/migrationV42.mjs'

const v41Sql=schemaSql.replace("  price_type TEXT NOT NULL DEFAULT 'standard' CHECK(price_type IN ('standard','outstation')),\n",'').replace("  resolution_state TEXT NOT NULL DEFAULT 'ready' CHECK(resolution_state IN ('ready','review_required')),\n",'')
function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+v41Sql);db.prepare('INSERT INTO schema_meta(version) VALUES(41)').run();db.prepare("INSERT INTO customers(id,jodoo_customer_id,name) VALUES(1,'1','Standard'),(2,'2','Outstation'),(3,'3','Conflict'),(4,'4','Missing')").run();db.prepare("INSERT INTO branches(id,jodoo_branch_id,customer_id,branch_name) VALUES(1,'1',1,'S1'),(2,'2',1,'S2'),(3,'3',2,'O1'),(4,'4',2,'O2'),(5,'5',3,'C1'),(6,'6',3,'C2'),(7,'7',4,'M1')").run();db.prepare("INSERT INTO materials(id,material_code,material_name,status) VALUES(1,'OCC','OCC','active')").run();db.prepare("INSERT INTO material_price_levels(id,material_id,price_amount,effective_date,status) VALUES(1,1,.2,'2026-01-01','active'),(2,1,.3,'2026-01-01','active')").run();for(const id of [1,2,3,4])db.prepare('INSERT INTO customer_material_pricing(id,customer_id,material_id,standard_price_level_id,outstation_enabled,outstation_price_level_id) VALUES(?,?,1,1,1,2)').run(id,id);for(const [branch,type,cmp] of [[1,'standard',1],[2,'standard',1],[3,'outstation',2],[4,'outstation',2],[5,'standard',3],[6,'outstation',3]])db.prepare('INSERT INTO branch_material_price_selections(branch_id,material_id,customer_material_pricing_id,price_type) VALUES(?,1,?,?)').run(branch,cmp,type);db.prepare("INSERT INTO customer_material_pricing_history(customer_material_pricing_id,customer_id,material_id,after_json,reason,changed_by) VALUES(1,1,1,'{}','seed','test')").run();db.prepare("INSERT INTO branch_material_price_selection_history(branch_id,material_id,new_price_type,new_customer_material_pricing_id,reason,changed_by) VALUES(1,1,'standard',1,'seed','test')").run();return db}

test('v41 prerequisite is exact and v42 no-op fails closed on incomplete physical schema or constraints',()=>{for(const version of [40,43]){const db=fixture();db.exec(`DELETE FROM schema_meta;INSERT INTO schema_meta(version) VALUES(${version})`);if(version===40)assert.throws(()=>applyV42Migration(db),/v41 is required/);else assert.throws(()=>applyV42Migration(db),/contract is incomplete/)}const malformed=fixture();malformed.exec("ALTER TABLE customer_material_pricing ADD COLUMN price_type TEXT;ALTER TABLE customer_material_pricing ADD COLUMN resolution_state TEXT;DELETE FROM schema_meta;INSERT INTO schema_meta(version) VALUES(42)");assert.throws(()=>applyV42Migration(malformed),/constraint is missing/)})

test('v41 to v42 infers unanimous types and sends conflicting or missing selections to review',()=>{const db=fixture(),before={customers:4,branches:7,pricing:4,pricingHistory:1,selectionHistory:1};const result=applyV42Migration(db);assert.equal(result.schemaVersion,42);assert.deepEqual(db.prepare('SELECT customer_id customerId,price_type priceType,resolution_state resolutionState FROM customer_material_pricing ORDER BY customer_id').all().map(row=>({...row})),[{customerId:1,priceType:'standard',resolutionState:'ready'},{customerId:2,priceType:'outstation',resolutionState:'ready'},{customerId:3,priceType:'standard',resolutionState:'review_required'},{customerId:4,priceType:'standard',resolutionState:'review_required'}]);assert.deepEqual({customers:db.prepare('SELECT COUNT(*) n FROM customers').get().n,branches:db.prepare('SELECT COUNT(*) n FROM branches').get().n,pricing:db.prepare('SELECT COUNT(*) n FROM customer_material_pricing').get().n,pricingHistory:db.prepare('SELECT COUNT(*) n FROM customer_material_pricing_history').get().n,selectionHistory:db.prepare('SELECT COUNT(*) n FROM branch_material_price_selection_history').get().n},before);assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(),[]);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');const second=applyV42Migration(db);assert.equal(second.noOp,true);assert.deepEqual(second.before,second.after)})

test('injected migration failure rolls back columns, metadata and every row atomically',()=>{const db=fixture();assert.throws(()=>applyV42Migration(db,{afterSchema:()=>{throw new Error('injected failure')}}),/injected failure/);assert.equal(db.prepare('SELECT MAX(version) version FROM schema_meta').get().version,41);assert.equal(db.prepare("SELECT COUNT(*) n FROM pragma_table_info('customer_material_pricing') WHERE name IN ('price_type','resolution_state')").get().n,0);assert.equal(db.prepare('SELECT COUNT(*) n FROM customer_material_pricing').get().n,4);assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(),[]);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})
