import test from 'node:test'
import assert from 'node:assert/strict'
import { DatabaseSync } from 'node:sqlite'
import { schemaSql } from '../server/schema.mjs'
import { adoptBranchGps, areaCloseout, captureBranchGps, createBranch, createCustomer, getBranch, getCustomer, listBuyers, listGpsCollector, listOperationalLocations, saveBuyer, saveOperationalLocation, updateBranch, updateCustomer } from '../server/customerMasterService.mjs'
import { commitMasterImport, masterExport, masterTemplate, previewMasterImport } from '../server/masterTransferService.mjs'
import { approveDay, assignVehicleDay, generateDay, getDispatchDay, updateStop } from '../server/dispatchService.mjs'

function fixture(){const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;${schemaSql}`);db.prepare("UPDATE areas SET zone_assignment_status='confirmed',confirmed_zone_group_id=zone_group_id").run();db.prepare("INSERT INTO areas(jodoo_area_id,name,zone_group_id,confirmed_zone_group_id,zone_assignment_status) VALUES('A1','North',1,1,'confirmed')").run();db.prepare("INSERT INTO vehicles(vehicle_code,registration_number) VALUES('V1','ABC1')").run();db.prepare("INSERT INTO employees(employee_code,name,job_role) VALUES('D1','Driver One','driver')").run();return db}
function seed(db){createCustomer({customerId:'C1',customerName:'Alpha Trading',defaultPaymentType:'Cash',changedBy:'Manager'},db);createBranch({branchId:'B1',customerId:'C1',branchName:'Alpha Branch',areaId:'A1',address:'Road 1',occPrice:0.5,paymentType:'Cash',changedBy:'Manager'},db);db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S1',1,'B1','Weekly','Monday')").run()}

test('Customer 与 Branch 由 KCS 建立并保持唯一编号及多 Branch 关系',()=>{const db=fixture();seed(db);createBranch({branchId:'B2',customerId:'C1',branchName:'Second Branch',areaId:'A1'},db);assert.equal(getCustomer('C1',db).branches.length,2);assert.equal(getBranch('B1',db).sourceSystem,'KCS');assert.throws(()=>createCustomer({customerId:'C1',customerName:'Duplicate'},db),/UNIQUE/);assert.throws(()=>createBranch({branchId:'B1',customerId:'C1',branchName:'Duplicate'},db),/UNIQUE/)})

test('Customer 暂停、恢复、关闭与关键修改保留审计',()=>{const db=fixture();seed(db);updateCustomer('C1',{status:'paused',changedBy:'Supervisor',reason:'Credit review'},db);assert.equal(getCustomer('C1',db).status,'paused');updateCustomer('C1',{status:'active',changedBy:'Supervisor'},db);updateCustomer('C1',{status:'closed',changedBy:'Supervisor'},db);assert.equal(db.prepare("SELECT COUNT(*) n FROM master_change_history WHERE entity_type='customer' AND entity_id='C1'").get().n,4);assert.equal(db.prepare("SELECT COUNT(*) n FROM customers WHERE jodoo_customer_id='C1'").get().n,1)})

test('已批准路线涉及的价格或付款方式修改后要求重新批准',()=>{const db=fixture();seed(db);generateDay({startDate:'2026-08-03'},db);assignVehicleDay('2026-08-03',1,{driverId:1},db);const stop=getDispatchDay('2026-08-03',db).unassignedStops[0];updateStop(stop.id,{date:'2026-08-03',vehicleId:1,tripNumber:1},db);approveDay('2026-08-03',{},db);updateBranch('B1',{occPrice:0.65,changedBy:'Supervisor',reason:'New price'},db);assert.equal(getDispatchDay('2026-08-03',db).status,'reapproval_required');assert.equal(db.prepare("SELECT COUNT(*) n FROM dispatch_change_logs WHERE change_type='branch_master_changed'").get().n,1)})

test('GPS Collector 先保存 temporary GPS，不自动覆盖 official GPS',()=>{const db=fixture();seed(db);updateBranch('B1',{officialLatitude:1.5,officialLongitude:110.1,changedBy:'Supervisor'},db);captureBranchGps('B1',{latitude:1.6,longitude:110.2,locationSource:'Driver Captured',capturedBy:'Driver A'},db);const branch=getBranch('B1',db),queue=listGpsCollector({},db);assert.equal(branch.officialLatitude,1.5);assert.equal(branch.officialLongitude,110.1);assert.equal(queue[0].verificationStatus,'pending_supervisor')})

test('主管采用 temporary GPS 后保存旧新坐标、距离差异及审批记录',()=>{const db=fixture();seed(db);updateBranch('B1',{officialLatitude:1.5,officialLongitude:110.1,changedBy:'Supervisor'},db);const temporary=captureBranchGps('B1',{latitude:2.5,longitude:111.1,capturedBy:'Driver A'},db),result=adoptBranchGps(temporary.id,{adoptedBy:'Supervisor',reason:'现场确认'},db);assert.equal(getBranch('B1',db).officialLatitude,2.5);assert.equal(result.distanceWarning,true);assert.equal(db.prepare("SELECT COUNT(*) n FROM master_change_history WHERE change_type='official_gps_adopted'").get().n,1)})

test('Buyer Master 与 Customer Master 分开保存，Buyer 可成为营运终点',()=>{const db=fixture();const buyer=saveBuyer({buyerId:'BUY-1',buyerName:'Paper Mill',materialAccepted:'OCC',changedBy:'Supervisor'},null,db);saveOperationalLocation({locationId:'LOC-1',name:'Paper Mill Gate',locationType:'Buyer',buyerId:'BUY-1',canEnd:true,changedBy:'Supervisor'},null,db);assert.equal(listBuyers({},db)[0].buyerId,'BUY-1');assert.equal(listOperationalLocations({},db)[0].buyerInternalId,buyer.id);assert.equal(listOperationalLocations({},db)[0].canEnd,1)})

test('Customer 导入先预览、事务提交并保持幂等',()=>{const db=fixture(),rows=[{'Customer ID':'C100','Customer Name':'New Customer','Default Payment Type':'Credit','Status':'active'}],preview=previewMasterImport({module:'customer',fileName:'customers.xlsx',fileFormat:'xlsx',rows},db);assert.deepEqual(preview.summary,{total:1,new:1,update:0,unchanged:0,error:0});assert.equal(db.prepare('SELECT COUNT(*) n FROM customers').get().n,0);commitMasterImport(preview.batchId,{changedBy:'Admin'},db);commitMasterImport(preview.batchId,{changedBy:'Admin'},db);assert.equal(db.prepare("SELECT COUNT(*) n FROM customers WHERE jodoo_customer_id='C100'").get().n,1);const repeat=previewMasterImport({module:'customer',fileName:'customers.csv',fileFormat:'csv',rows},db);assert.equal(repeat.summary.unchanged,1);assert.equal(repeat.summary.new,0)})

test('重要导入错误阻止 commit 且不破坏原资料',()=>{const db=fixture();seed(db);const preview=previewMasterImport({module:'branch',fileName:'bad.csv',fileFormat:'csv',rows:[{'Branch ID':'B9','Customer ID':'MISSING','Branch Name':'Bad Branch'}]},db);assert.equal(preview.summary.error,1);assert.throws(()=>commitMasterImport(preview.batchId,{changedBy:'Admin'},db),/contains errors/);assert.equal(db.prepare('SELECT COUNT(*) n FROM branches').get().n,1)})

test('Area 收口统计、Area-Zone 导出和七类空白模板正确',()=>{const db=fixture(),summary=areaCloseout(db),exported=masterExport('area',{changedBy:'Admin'},db);assert.equal(summary.totalAreas,1);assert.equal(summary.confirmedAreas,1);assert.equal(summary.pendingAreas,0);assert.equal(exported.rows[0]['Area ID'],'A1');for(const module of ['customer','branch','zone','area','gps','buyer','operational_location'])assert.ok(masterTemplate(module).columns.length>3)})
