import test from 'node:test'
import assert from 'node:assert/strict'
import {randomUUID} from 'node:crypto'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {customerWorkspace,saveCustomerWorkspace,confirmCustomerSchedule} from '../server/customerWorkspaceService.mjs'
import {kuchingDate} from '../shared/kuchingTime.js'
const owner={id:1,role:'owner_admin',employeeName:'KC'},office={id:2,role:'office',employeeName:'Office'}
function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);return db}
const payload=()=>({requestId:randomUUID(),reason:'New customer setup',customer:{customerName:'New customer',defaultPaymentType:'Cash'},branch:{branchName:'New branch',address:'Road 1'},schedule:{frequency:'On Call',weekdays:[],routeNumber:'',effectiveDate:kuchingDate()},gps:{latitude:1.5,longitude:110.3,locationSource:'map_selection'}})
test('one save atomically creates customer, branch, official first GPS and schedule; replay creates nothing',()=>{const db=fixture(),p=payload(),r=saveCustomerWorkspace(p,owner,db);assert.equal(r.branch.officialLatitude,1.5);assert.equal(r.pending.length,0);assert.equal(r.schedule.frequency,'On Call');assert.equal(db.prepare('SELECT COUNT(*) n FROM customers').get().n,1);assert.equal(JSON.stringify(saveCustomerWorkspace(p,owner,db)),JSON.stringify(r));assert.equal(db.prepare('SELECT COUNT(*) n FROM branches').get().n,1);assert.throws(()=>saveCustomerWorkspace({...p,reason:'changed'},owner,db),/already used/);db.close()})
test('invalid schedule rolls back every master write; office cannot bypass pricing and driver cannot enter',()=>{const db=fixture();assert.throws(()=>saveCustomerWorkspace({...payload(),schedule:{frequency:'Once a week',weekdays:[],effectiveDate:kuchingDate()}},owner,db),/exactly/);assert.equal(db.prepare('SELECT COUNT(*) n FROM customers').get().n,0);assert.throws(()=>saveCustomerWorkspace({...payload(),customer:{customerName:'X',materialPricing:[]}},office,db),/Pricing permission/);assert.throws(()=>saveCustomerWorkspace(payload(),{id:3,role:'driver'},db),/permission/);assert.equal(db.prepare('SELECT COUNT(*) n FROM customers').get().n,0);db.close()})
test('existing records require a revision and keep official GPS immutable',()=>{const db=fixture(),r=saveCustomerWorkspace(payload(),owner,db);const p={...payload(),branchId:r.branch.branchId,customerId:r.customer.customerId,revision:r.revision,gps:null,customer:{customerName:'Renamed'}};const next=saveCustomerWorkspace(p,owner,db);assert.equal(next.customer.customerName,'Renamed');assert.equal(next.branch.branchId,r.branch.branchId);assert.throws(()=>saveCustomerWorkspace({...p,requestId:randomUUID()},owner,db),/Reload/);db.prepare('UPDATE branches SET latitude=1.4,longitude=110.2 WHERE id=?').run(r.branch.internalId);const fresh=customerWorkspace({branchId:r.branch.branchId},owner,db);const pending=saveCustomerWorkspace({...p,requestId:randomUUID(),revision:fresh.revision,gps:{latitude:1,longitude:110}},owner,db);assert.equal(pending.pending.length,1);assert.equal(db.prepare('SELECT latitude FROM branches').get().latitude,1.4);assert.throws(()=>confirmCustomerSchedule({branchId:r.branch.branchId,date:kuchingDate(),reason:'confirm'},office,db),/Supervisor/);db.close()})
test('weekly customer is added to the current planning window without duplicate stops',()=>{const db=fixture();const seed=saveCustomerWorkspace(payload(),owner,db);db.exec("INSERT INTO weekly_route_plans(name,source_name,created_by) VALUES('Current','Test','KC');INSERT INTO weekly_route_definitions(plan_id,route_number,display_name) VALUES(1,1,'Route A');INSERT INTO weekly_route_plan_stops(plan_id,weekday,branch_id,vehicle_registration_number,trip_number,stop_sequence,route_number) VALUES(1,1,1,'ABC123',1,1,1)");const p=payload(),today=kuchingDate(),weekday=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kuching',weekday:'long'}).format(new Date());p.schedule={frequency:'Once a week',weekdays:[weekday],routeNumber:1,effectiveDate:today,anchorDate:today};const r=saveCustomerWorkspace(p,owner,db);assert.ok(db.prepare("SELECT COUNT(*) n FROM dispatch_stops WHERE branch_id=? AND service_date=? AND status<>'cancelled'").get(r.branch.internalId,today).n===1);saveCustomerWorkspace(p,owner,db);assert.equal(db.prepare("SELECT COUNT(*) n FROM dispatch_stops WHERE branch_id=? AND service_date=? AND status<>'cancelled'").get(r.branch.internalId,today).n,1);db.close()})
test('approved day defers a new branch until supervisor confirmation and leaves other branches untouched',()=>{
 const db=fixture();saveCustomerWorkspace(payload(),owner,db);db.exec("INSERT INTO weekly_route_plans(name,source_name,created_by) VALUES('Current','Test','KC');INSERT INTO weekly_route_definitions(plan_id,route_number,display_name) VALUES(1,1,'Route A');INSERT INTO weekly_route_plan_stops(plan_id,weekday,branch_id,vehicle_registration_number,trip_number,stop_sequence,route_number) VALUES(1,1,1,'ABC123',1,1,1)")
 const today=kuchingDate(),weekday=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kuching',weekday:'long'}).format(new Date()),schedule={frequency:'Once a week',weekdays:[weekday],routeNumber:1,effectiveDate:today,anchorDate:today}
 const first=saveCustomerWorkspace({...payload(),schedule},owner,db)
 db.prepare("UPDATE dispatch_days SET status='approved' WHERE dispatch_date=?").run(today)
 const before=JSON.stringify(db.prepare('SELECT * FROM dispatch_stops WHERE branch_id=?').all(first.branch.internalId))
 const second=saveCustomerWorkspace({...payload(),schedule},owner,db),missing=second.review.find(r=>r.kind==='missing'&&r.date===today)
 assert.ok(missing);assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_stops WHERE branch_id=? AND service_date=?').get(second.branch.internalId,today).n,0)
 assert.throws(()=>confirmCustomerSchedule({branchId:second.branch.branchId,date:today,reason:'Approved addition',expectedRevision:missing.expectedRevision-1},owner,db),/刷新/)
 confirmCustomerSchedule({branchId:second.branch.branchId,date:today,reason:'Approved addition',expectedRevision:missing.expectedRevision},owner,db)
 assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_stops WHERE branch_id=? AND service_date=?').get(second.branch.internalId,today).n,1)
 assert.equal(JSON.stringify(db.prepare('SELECT * FROM dispatch_stops WHERE branch_id=?').all(first.branch.internalId)),before)
 db.close()
})
