import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV22Migration} from '../server/migrationV22.mjs'
import {applyV24Migration} from '../server/migrationV24.mjs'
import {applyV25Migration} from '../server/migrationV25.mjs'
import {runCustomerBranchRepair} from '../scripts/repair-customer-branch-20260803.mjs'

function fixture(){const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;${schemaSql}`);db.prepare('INSERT OR IGNORE INTO schema_meta(version) VALUES(21)').run();applyV22Migration(db);db.prepare('INSERT OR IGNORE INTO schema_meta(version) VALUES(23)').run();applyV24Migration(db);applyV25Migration(db);const customers=[['10004','ASTEEL'],['10039','DIY'],['10176','EMC TRADING'],['10184','WIJA PHARMACY'],['10172','WATSON'],['10185','PULLMAN'],['10213','CHURCH'],['10238','KINDERGARTEN KUCHING'],['10271','MIXUE']];for(const x of customers)db.prepare('INSERT INTO customers(jodoo_customer_id,name,status,is_active) VALUES(?,?,\'active\',1)').run(...x);const branches=[['10019',null,'10015','BS BAU'],['10021',null,'10015','BS DEPO'],['10020',null,'10015','BS BT7'],['10023',null,'10015','BS SATOK'],['10024',null,'10015','BS TAPAH'],['10007','10004','10004','AM STEEL'],['10427','10004','10004','ASTEEL DEMAK'],['10364','10184','10184','Samariang'],['10353','10176','10176','EMC BATU 2'],['10354','10176','10176','EMC BATU 2'],['10416','10172','10172','WATSON LUNDU'],['10421','10172','10172','WATSON LUNDU'],['10402','10213','10213','CHURCH STUTONG'],['10477','10213','10213','CHURCH STUTONG'],['10444','10238','10238','KINDERGARTEN KUCHING'],['10445','10238','10238','KINDERGARTEN KUCHING'],['10365','10185','10185','PULLMAN'],['10366','10185','10185','PULLMAN']];for(const [bid,cid,sid,name] of branches){const c=cid?db.prepare('SELECT id FROM customers WHERE jodoo_customer_id=?').get(cid):null;db.prepare('INSERT INTO branches(jodoo_branch_id,customer_id,source_customer_id,branch_name,status,is_active) VALUES(?,?,?,?,\'active\',1)').run(bid,c?.id||null,sid,name)}return db}
test('dry-run does not write and apply is atomic/idempotent',()=>{const db=fixture(),before=db.serialize();const dry=runCustomerBranchRepair(db);assert.equal(dry.writes,0);assert.deepEqual(db.serialize(),before);const first=runCustomerBranchRepair(db,{apply:true});assert.equal(first.write.customersCreated,3);assert.equal(first.write.branchesCreated,5);assert.equal(first.write.branchesPaused,12);assert.equal(first.write.branchesUnlinked,1);assert.equal(db.prepare("SELECT status FROM branches WHERE jodoo_branch_id='10007'").get().status,'paused');assert.equal(db.prepare("SELECT status FROM customers WHERE jodoo_customer_id='10004'").get().status,'active');assert.equal(db.prepare("SELECT c.jodoo_customer_id id FROM branches b JOIN customers c ON c.id=b.customer_id WHERE b.branch_name='DIY WFP'").get().id,'10039');assert.equal(db.prepare("SELECT customer_id FROM branches WHERE jodoo_branch_id='10364'").get().customer_id,null);const second=runCustomerBranchRepair(db,{apply:true});assert.equal(second.write.customersCreated,0);assert.equal(second.write.branchesCreated,0);assert.equal(second.write.branchesPaused,0);assert.equal(second.write.auditInserted,0);assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);db.close()})
test('unexpected retained record prevents all writes',()=>{const db=fixture();db.prepare("UPDATE branches SET branch_name='Changed' WHERE jodoo_branch_id='10353'").run();const before=db.serialize();assert.throws(()=>runCustomerBranchRepair(db,{apply:true}),/Retained Branch mismatch/);assert.deepEqual(db.serialize(),before);db.close()})
