import test,{after} from 'node:test'
import assert from 'node:assert/strict'
import React,{act} from 'react'
import {createServer} from 'vite'
import {JSDOM} from 'jsdom'
const dom=new JSDOM('<html><body><div id="root"></div></body></html>',{url:'https://localhost/'})
for(const k of ['window','document','Node','NodeFilter','HTMLElement','MutationObserver','Event','MouseEvent','localStorage','sessionStorage'])globalThis[k]=dom.window[k]
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true
const{createRoot}=await import('react-dom/client'),vite=await createServer({logLevel:'silent',server:{middlewareMode:true},appType:'custom'});after(()=>vite.close())
const{default:Report}=await vite.ssrLoadModule('/src/DailyReport.jsx'),{I18nProvider}=await vite.ssrLoadModule('/src/i18n.jsx')
const{reportWord:w}=await import('../shared/dailyReportWords.js')
const click=label=>{const button=[...document.querySelectorAll('button')].find(b=>b.textContent===label);assert.ok(button,'button: '+label);button.click()}
const result=date=>({date,generatedAt:'2026-09-15T03:00:00Z',access:{full:true,finance:true},summary:{weightKg:2500},missingSources:[],sections:{vehicles:[{id:'1',name:'Q123',kind:'vehicle',status:'running',quantity:2500,amountCents:null,actor:'KC',time:'',detail:{trips:2}}]}})
test('report loads in all languages; details and saved column order work; failures hide stale totals',async()=>{
 for(const language of ['en','ms','zh']){localStorage.clear();const root=createRoot(document.getElementById('root'));let fail=false;const calls=[];globalThis.fetch=async url=>{calls.push(url);if(fail)throw Error('offline');return{ok:true,json:async()=>result(new URL(url,'https://localhost').searchParams.get('date'))}}
 try{await act(async()=>root.render(React.createElement(I18nProvider,{language},React.createElement(Report,{account:{id:1}}))));assert.equal(calls.length,0);await act(async()=>click(w(language,'open')));assert.equal(document.querySelector('.daily-report-dialog'),null);const entry=[...document.querySelectorAll('.daily-report-summary button')].find(b=>b.textContent.includes(w(language,'vehicles')));entry.focus();await act(async()=>entry.click());assert.ok(document.querySelector('.daily-report-dialog'));assert.equal(document.body.style.overflow,'hidden');assert.match(document.querySelector('.daily-report-dialog').textContent,/Q123/);await act(async()=>document.querySelector('.daily-report-name').click());assert.match(document.body.textContent,/125.0%/)
 const title=language==='zh'?'调整栏目':language==='ms'?'Susun lajur':'Arrange columns';await act(async()=>click(title));assert.ok(document.querySelectorAll('.expense-column-row').length>0);assert.match(document.querySelector('.expense-column-list').textContent,new RegExp(w(language,'name')));await act(async()=>document.querySelector('.expense-column-row button:last-child').click());await act(async()=>document.querySelector('.expense-column-modal form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));assert.equal(JSON.parse(localStorage.getItem('kcs.daily-report.columns.1.vehicles'))[0],'kind')
 await act(async()=>document.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape',bubbles:true})));assert.equal(document.querySelector('.daily-report-dialog'),null);assert.equal(document.activeElement,entry);assert.equal(document.body.style.overflow,'');fail=true;await act(async()=>click(w(language,'refresh')));assert.ok(document.querySelector('[role="alert"]'));assert.equal(document.querySelector('.daily-report-summary'),null)
 }finally{await act(async()=>root.unmount())}}
})
test('a superseded request cannot replace a newer report',async()=>{const root=createRoot(document.getElementById('root'));const pending=[];globalThis.fetch=url=>new Promise(resolve=>pending.push({url,resolve}));try{await act(async()=>root.render(React.createElement(I18nProvider,{language:'en'},React.createElement(Report,{account:{id:1}}))));await act(async()=>click('Open report'));await act(async()=>click('Refresh'));assert.equal(pending.length,2);const date=new URL(pending[1].url,'https://localhost').searchParams.get('date');await act(async()=>pending[1].resolve({ok:true,json:async()=>({...result(date),summary:{weightKg:777}})}));await act(async()=>pending[0].resolve({ok:true,json:async()=>({...result(date),summary:{weightKg:999}})}));assert.match(document.querySelector('.daily-report-summary').textContent,/777/);assert.doesNotMatch(document.querySelector('.daily-report-summary').textContent,/999/)}finally{await act(async()=>root.unmount())}})

test('summary selection narrows no-goods, unfinished, cash and pending approval details',async()=>{const {reportSelection}=await vite.ssrLoadModule('/src/DailyReport.jsx');const data={date:'2026-09-15',sections:{stops:[{id:'1',status:'no_goods'},{id:'2',status:'active'},{id:'3',status:'cancelled'},{id:'4',status:'completed',detail:{hasIssuedBill:true}}],bills:[{id:'1',status:'issued',detail:{payment:'Cash'}},{id:'2',status:'issued',detail:{payment:'Credit'}},{id:'3',status:'voided',detail:{payment:'Cash'}}],approvals:[{id:'1',status:'pending'},{id:'2',status:'approved',detail:{reviewedAt:'2026-09-15T09:00:00+08:00'}}]}};assert.deepEqual(reportSelection(data,'noGoodsBranches').rows.map(r=>r.id),['1']);assert.deepEqual(reportSelection(data,'pendingBranches').rows.map(r=>r.id),['2']);assert.deepEqual(reportSelection(data,'cashCents').rows.map(r=>r.id),['1']);assert.deepEqual(reportSelection(data,'pendingApprovals').rows.map(r=>r.id),['1']);assert.deepEqual(reportSelection(data,'approvals').rows.map(r=>r.id),['2']);})
test('dialog scrollbar stays in its footer, wins over background tables and tracks horizontal position',async()=>{
 const {default:Scroll}=await vite.ssrLoadModule('/src/TableBottomScroll.jsx');const root=createRoot(document.getElementById('root'));let table
 function Fixture(){const scroll=React.useRef(null),dock=React.useRef(null),background=React.useRef(null);const setup=(ref,id)=>el=>{if(!el)return;ref.current=el;if(id==='dialog')table=el;Object.defineProperty(el,'clientWidth',{configurable:true,value:400});Object.defineProperty(el,'scrollWidth',{configurable:true,value:1600});el.getBoundingClientRect=()=>({left:30,right:430,top:50,bottom:550,height:500,width:400})};return React.createElement(React.Fragment,null,React.createElement('div',{ref:setup(background,'background')}),React.createElement(Scroll,{scrollRef:background}),React.createElement('section',{'data-dialog':'true'},React.createElement('div',{ref:setup(scroll,'dialog')}),React.createElement('footer',{ref:dock,className:'daily-report-scroll-dock'}),React.createElement(Scroll,{scrollRef:scroll,dockRef:dock})))}
 try{await act(async()=>root.render(React.createElement(I18nProvider,{language:'en'},React.createElement(Fixture))));const range=document.querySelector('.daily-report-scroll-dock input[type=range]');assert.ok(range);assert.equal(document.querySelectorAll('.table-bottom-scroll').length,1);assert.equal(range.max,'1200');assert.equal(range.parentElement.style.width,'100%');table.scrollLeft=900;await act(async()=>table.dispatchEvent(new Event('scroll')));assert.equal(range.value,'900');const setter=Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value').set;await act(async()=>{setter.call(range,'500');range.dispatchEvent(new Event('input',{bubbles:true}))});assert.equal(table.scrollLeft,500)}finally{await act(async()=>root.unmount())}
})
