import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {dailyReport,reportAccess,safeDetails,assertReportGrantChange} from '../server/dailyReport.mjs'
function fixture(){
 const db=new DatabaseSync(':memory:');db.exec(schemaSql);db.exec(`PRAGMA foreign_keys=OFF;
 INSERT INTO company_menu(id,owner_account_id) VALUES(1,1);
 INSERT INTO employees(id,employee_code,name) VALUES(1,'EMP','Driver');
 INSERT INTO vehicles(id,vehicle_code,registration_number) VALUES(1,'V1','Q123'),(2,'V2','Q456');
 INSERT INTO customers(id,jodoo_customer_id,name,created_at) VALUES(1,'C1','Customer','2026-09-14T16:01:00Z');
 INSERT INTO branches(id,jodoo_branch_id,branch_name,customer_id,created_at) VALUES(1,'B1','Branch One',1,'2026-09-14T16:02:00Z'),(2,'B2','Branch Two',1,'2026-09-10T00:00:00Z');
 INSERT INTO dispatches(id,dispatch_date,vehicle_id,driver_id) VALUES(1,'2026-09-15',1,1),(2,'2026-09-15',2,1);
 INSERT INTO dispatch_days(id,weekly_plan_id,dispatch_date) VALUES(1,1,'2026-09-15');
 INSERT INTO dispatch_trips(id,dispatch_day_id,dispatch_id,execution_status,started_at) VALUES(1,1,1,'in_progress','2026-09-15T08:00:00+08:00'),(2,1,2,'not_started',NULL);
 ALTER TABLE dispatch_stops ADD COLUMN completion_outcome TEXT;
 INSERT INTO dispatch_stops(id,dispatch_id,branch_id,stop_sequence,service_date,dispatch_trip_id,status,completion_outcome) VALUES(1,1,1,1,'2026-09-15',1,'completed','completed'),(2,1,2,2,'2026-09-15',1,'completed','no_goods_notice');
 INSERT INTO cash_float_transactions(employee_id,transaction_type,amount_cents,service_date,created_by_name_snapshot,created_at) VALUES(1,'expense',-15000,'2026-09-15','Office','2026-09-15T12:00:00+08:00'),(1,'top_up',90000,'2026-09-15','Office','2026-09-15T12:00:00+08:00');
 INSERT INTO admin_expense_records(service_date,category,description,amount_cents,payment_method,created_by_name_snapshot,created_at) VALUES('2026-09-15','Repair','repair',5000,'Cash','Office','2026-09-15T10:00:00+08:00');
 INSERT INTO audit_logs(action,entity_type,entity_id,before_json,after_json,created_at) VALUES('changed','branch','1','{"name":"Old"}','{"name":"New","password":"secret"}','2026-09-14T16:01:00Z');
 INSERT INTO dispatch_change_logs(dispatch_day_id,actor,change_type,entity_type,entity_id,before_json,after_json,created_at) VALUES(1,'1','move','dispatch_stop','1','{"service_date":"2026-09-13"}','{"service_date":"2026-09-16","total_cents":99999}','2026-09-14 16:02:00');
 `)
 const bill=db.prepare(`INSERT INTO purchase_bills(id,bill_number,dispatch_stop_id,dispatch_trip_id,dispatch_day_id,branch_id,driver_employee_id,vehicle_id,service_date,customer_name_snapshot,branch_code_snapshot,branch_name_snapshot,driver_name_snapshot,vehicle_code_snapshot,payment_method,weight_method,print_choice,subtotal_cents,total_cents,status,issued_at) VALUES(?,?,?,1,1,?,1,1,'2026-09-15','Customer','B','Branch','Driver','V1',?,'on_site','no_print',?,?,?,'2026-09-15T10:00:00+08:00')`)
 bill.run(1,'P1',1,1,'Cash',3000,3000,'issued');bill.run(2,'P2',3,1,'Credit',2000,2000,'issued');bill.run(3,'P3',1,1,'Cash',9900,9900,'voided')
 db.exec(`INSERT INTO purchase_bill_items(purchase_bill_id,product_id,product_code_snapshot,product_name_snapshot,unit_snapshot,quantity,unit_price_cents,line_total_cents) VALUES(1,1,'OCC','OCC','kg',100,20,2000),(1,2,'OTHER','OTHER','kg',50,20,1000),(2,3,'BOX','BOX','piece',2,1000,2000),(3,1,'OCC','OCC','kg',495,20,9900)`)
 return db
}
const owner={id:1,role:'owner_admin'}
test('totals do not multiply multi-line bills; exclude voids, non-kg units, topups and unstarted vehicles',()=>{const db=fixture();const before=db.prepare('SELECT total_changes() n').get().n,r=dailyReport(db,owner,'2026-09-15');assert.equal(r.summary.purchaseCents,5000);assert.equal(r.summary.cashCents,3000);assert.equal(r.summary.creditCents,2000);assert.equal(r.summary.weightKg,150);assert.equal(r.summary.collectedBranches,1);assert.equal(r.summary.vehicles,1);assert.equal(r.summary.trips,1);assert.equal(r.summary.noGoodsBranches,1);assert.equal(r.summary.expenseCents,20000);assert.equal(r.summary.topupCents,90000);assert.equal(r.summary.customers,1);assert.equal(db.prepare('SELECT total_changes() n').get().n,before);db.close()})
test('business dates and operation dates are separate and use Kuching midnight',()=>{const db=fixture();const r=dailyReport(db,owner,'2026-09-15');assert.equal(r.sections.changes.length,2);assert.equal(r.sections.changes.find(r=>r.kind==='dispatch_change_logs').detail.before_json.service_date,'2026-09-13');assert.equal(r.sections.changes.find(r=>r.kind==='audit_logs').detail.after_json.password,undefined);assert.equal(dailyReport(db,owner,'2026-09-14').sections.changes.length,0);db.close()})
test('only pinned owner defaults to full; financial grants are separate and revocation takes immediate effect',()=>{const db=fixture();for(const role of ['office','supervisor','operations_admin','owner_admin']){const r=dailyReport(db,{id:2,role},'2026-09-15');assert.equal(r.access.full,false);assert.equal(r.summary.purchaseCents,undefined);assert.equal(r.sections.bills,undefined);assert.ok(r.sections.goods.every(r=>r.amountCents==null));assert.ok(!JSON.stringify(r.sections.changes).includes('99999'))}assert.throws(()=>dailyReport(db,{id:1,role:'driver'},'2026-09-15'),{statusCode:403});db.prepare("INSERT INTO auth_account_permissions(account_id,permission,granted_by) VALUES(2,'daily_report_finance','Owner')").run();assert.equal(reportAccess(db,{id:2,role:'office'}).finance,true);assert.equal(reportAccess(db,{id:2,role:'office'}).full,false);db.exec('DELETE FROM auth_account_permissions');assert.equal(reportAccess(db,{id:2,role:'office'}).finance,false);assert.throws(()=>dailyReport(db,owner,'2026-02-30'),{statusCode:400});db.close()})
test('sanitizer excludes nested credentials and evidence paths',()=>{assert.deepEqual(safeDetails({password:'x',nested:[{token:'y',storage_key:'z',name:'A'}]}),{nested:[{name:'A'}]})})
test('sales delivery and settlement dates stay distinct; review uses actual approved date and route decisions are counted',()=>{const db=fixture();db.exec(`INSERT INTO sales_settlements(buyer_id,buyer_name,vehicle_id,vehicle_plate,bill_number,bill_key,settlement_date,lines_json,total_cents,storage_key,content_type,created_by) VALUES(1,'Buyer',1,'Q123','S1','S1','2026-09-15','[{"deliveryDate":"2026-09-14","weightKg":100,"unitPrice":0.30}]',3000,'private','image/png','Office');INSERT INTO driver_date_requests(id,dispatch_stop_id,employee_id,source_date,target_date,reason,status,requested_at,reviewed_at,reviewed_by) VALUES(1,1,1,'2026-09-13','2026-09-16','closed','approved','2026-09-13T08:00:00+08:00','2026-09-15T09:00:00+08:00','Boss');INSERT INTO driver_date_reviews(request_id,branch_id,approved_date,route_number,scope) VALUES(1,1,'2026-09-17',2,'once');INSERT INTO dispatch_change_logs(dispatch_day_id,actor,change_type,entity_type,entity_id,created_at) VALUES(1,'Boss','route_approved','daily_route','2','2026-09-15T08:00:00+08:00');`);const r=dailyReport(db,owner,'2026-09-15');assert.equal(r.summary.salesCents,3000);assert.equal(r.summary.deliveredKg,0);assert.equal(r.summary.approvals,2);assert.equal(r.summary.rescheduledBranches,1);assert.equal(r.sections.approvals.find(r=>r.kind==='driver_date_requests').detail.approvedDate,'2026-09-17');const yesterday=dailyReport(db,owner,'2026-09-14');assert.equal(yesterday.summary.salesCents,0);assert.equal(yesterday.summary.deliveredKg,100);assert.equal(yesterday.sections.deliveries[0].detail.paymentStatus,'not_recorded');db.close()})

test("report grants require the pinned owner, including revocation",()=>{const db=fixture();assert.throws(()=>assertReportGrantChange(db,{id:2,role:"owner_admin"},[],["daily_report_full"]),{statusCode:403});assert.throws(()=>assertReportGrantChange(db,{id:2,role:"owner_admin"},["daily_report_full"],[]),{statusCode:403});assert.throws(()=>assertReportGrantChange(db,{id:2,role:"owner_admin"},[],[" daily_report_full "]),{statusCode:403});assert.doesNotThrow(()=>assertReportGrantChange(db,owner,[],["daily_report_full"]));assert.doesNotThrow(()=>assertReportGrantChange(db,{id:2,role:"owner_admin"},["daily_report_full"],["daily_report_full","employee_manage"]));db.close()})
