import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {dashboardDataTasks} from '../server/dashboardDataTasks.mjs'

function fixture(){const db=new DatabaseSync(':memory:');db.exec(schemaSql);db.exec("INSERT INTO areas(id,name,zone_group_id) VALUES(1,'Area',1);INSERT INTO branches(id,jodoo_branch_id,branch_name,area_id,status,is_active,lifecycle_status) VALUES(1,'10001','Branch One',1,'active',1,'ACTIVE')");return db}
test('pending GPS remains a task even with valid official GPS and disappears only after approval',()=>{const db=fixture();db.exec("UPDATE branches SET latitude=1.5,longitude=110.3;INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency) VALUES('S',1,'10001','On Call');INSERT INTO temporary_locations(branch_id,latitude,longitude,location_source,verification_status) VALUES(1,1.6,110.4,'device','pending_supervisor')");assert.deepEqual(dashboardDataTasks(db).items[0].issues,['pendingGps']);db.exec("UPDATE temporary_locations SET verification_status='adopted'");assert.equal(dashboardDataTasks(db).total,0);db.close()})
test('persistent tasks deduplicate per branch and disappear only when the stored data is complete',()=>{const db=fixture();const before=db.prepare('SELECT total_changes() n').get().n;assert.deepEqual(dashboardDataTasks(db).items[0].issues,['missingGps','missingSchedule']);assert.deepEqual(dashboardDataTasks(db),dashboardDataTasks(db));assert.equal(db.prepare('SELECT total_changes() n').get().n,before);db.exec("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency) VALUES('S1',1,'10001','On Call')");assert.deepEqual(dashboardDataTasks(db).items[0].issues,['scheduledMissingGps']);db.exec('UPDATE branches SET latitude=1.5,longitude=110.3');assert.equal(dashboardDataTasks(db).total,0);db.exec('UPDATE branches SET longitude=NULL');assert.deepEqual(dashboardDataTasks(db).items[0].issues,['invalidGps']);db.close()})
test('closed, paused and inactive branches are excluded; disabled schedules and areas do not pass completeness',()=>{const db=fixture();for(const sql of ["UPDATE branches SET status='closed'","UPDATE branches SET status='active',is_active=0","UPDATE branches SET is_active=1,lifecycle_status='TEMPORARILY_PAUSED'"]){db.exec(sql);assert.equal(dashboardDataTasks(db).total,0)}db.exec("UPDATE branches SET lifecycle_status='ACTIVE',latitude=1,longitude=110;UPDATE areas SET is_active=0;INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,is_active) VALUES('S',1,'10001','Once a week',0)");assert.deepEqual(dashboardDataTasks(db).items[0].issues,['missingSchedule','missingArea']);db.close()})
test('all active unmatched schedules remain visible with stable internal keys; inactive ones do not',()=>{const db=fixture();db.exec("UPDATE branches SET is_active=0;INSERT INTO branch_schedules(jodoo_schedule_id,source_branch_id,frequency) VALUES('ORPHAN','missing','Once a week');INSERT INTO branch_schedules(jodoo_schedule_id,source_branch_id,frequency,is_active) VALUES('OLD','old','Once a week',0)");const result=dashboardDataTasks(db);assert.equal(result.total,1);assert.equal(result.items[0].sourceBranchId,'missing');assert.equal(result.items[0].kind,'schedule');assert.deepEqual(dashboardDataTasks(db),result);db.close()})
