import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql,SCHEMA_VERSION} from '../server/schema.mjs'
import {applyV36Migration} from '../server/migrationV36.mjs'
import {setDefaultVehicle} from '../server/defaultVehicleService.mjs'
import {generateDay,getDispatchDay,updateStop} from '../server/dispatchService.mjs'
import {messages} from '../src/translations.js'

function fixture(){const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;${schemaSql}`);db.prepare('INSERT INTO schema_meta(version) VALUES(36)').run();db.prepare("INSERT INTO vehicles(id,vehicle_code,registration_number,status,operational_status,is_temporary) VALUES(1,'Lorry 1','QAV3468','available','active',0),(2,'Lorry 2','QAA4293N','available','active',0),(3,'Sold','QTW2704','inactive','sold',0)").run();db.prepare("INSERT INTO customers(id,jodoo_customer_id,name) VALUES(1,'C1','Alpha')").run();db.prepare("INSERT INTO areas(id,jodoo_area_id,name,zone_group_id,confirmed_zone_group_id,zone_assignment_status) VALUES(20,'A20','BDC',1,1,'confirmed')").run();db.prepare("INSERT INTO branches(id,jodoo_branch_id,customer_id,area_id,branch_name,is_active,collection_frequency) VALUES(30,'B30',1,20,'Alpha BDC',1,'Weekly')").run();db.prepare("INSERT INTO branch_schedules(id,jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week,is_active) VALUES(40,'S40',30,'B30','Weekly','Monday',1)").run();return db}

test('v35 to v36 is additive, explicit, idempotent and preserves protected counts',()=>{const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;CREATE TABLE schema_meta(version INTEGER PRIMARY KEY);INSERT INTO schema_meta VALUES(35);CREATE TABLE vehicles(id INTEGER PRIMARY KEY);CREATE TABLE zone_groups(id INTEGER PRIMARY KEY,name TEXT);CREATE TABLE areas(id INTEGER PRIMARY KEY,name TEXT);CREATE TABLE dispatches(id INTEGER PRIMARY KEY);CREATE TABLE dispatch_stops(id INTEGER PRIMARY KEY);INSERT INTO vehicles VALUES(1);INSERT INTO zone_groups VALUES(1,'Z');INSERT INTO areas VALUES(1,'A');INSERT INTO dispatches VALUES(1);INSERT INTO dispatch_stops VALUES(1)`);const first=applyV36Migration(db),second=applyV36Migration(db);assert.equal(first.schemaVersion,36);assert.equal(second.noOp,true);assert.deepEqual(first.before,first.after);for(const table of ['zone_groups','areas'])assert.ok(db.prepare(`PRAGMA table_info(${table})`).all().some(row=>row.name==='default_vehicle_id'));assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})

test('future Draft uses Zone default, daily override stays local, and tomorrow returns to default',()=>{const db=fixture();setDefaultVehicle('zone',1,{vehicleId:1,reason:'Stable BDC vehicle',changedBy:'Supervisor'},db);generateDay({startDate:'2026-08-17'},db);let day=getDispatchDay('2026-08-17',db),stop=day.stops[0];assert.equal(stop.vehicleId,1);updateStop(stop.id,{date:'2026-08-17',vehicleId:2,tripNumber:1,changedBy:'Supervisor'},db);assert.equal(getDispatchDay('2026-08-17',db).stops[0].vehicleId,2);assert.equal(db.prepare('SELECT default_vehicle_id FROM zone_groups WHERE id=1').get().default_vehicle_id,1);generateDay({startDate:'2026-08-24'},db);assert.equal(getDispatchDay('2026-08-24',db).stops[0].vehicleId,1)})

test('Area default overrides Zone only after explicit update; clear and invalid vehicles are safe',()=>{const db=fixture();setDefaultVehicle('zone',1,{vehicleId:1,reason:'Zone default',changedBy:'Owner'},db);setDefaultVehicle('area',20,{vehicleId:2,reason:'Area exception',changedBy:'Owner'},db);generateDay({startDate:'2026-08-17'},db);assert.equal(getDispatchDay('2026-08-17',db).stops[0].vehicleId,2);assert.throws(()=>setDefaultVehicle('area',20,{vehicleId:3,reason:'Invalid',changedBy:'Owner'},db),/active dispatch vehicle/);setDefaultVehicle('area',20,{vehicleId:null,reason:'Return to Zone default',changedBy:'Owner'},db);assert.equal(db.prepare('SELECT default_vehicle_id FROM areas WHERE id=20').get().default_vehicle_id,null);setDefaultVehicle('zone',1,{vehicleId:null,reason:'No long-term assignment',changedBy:'Owner'},db);generateDay({startDate:'2026-08-24'},db);assert.equal(getDispatchDay('2026-08-24',db).unassignedStops.length,1)})

test('default changes write actor, reason and before/after once without touching historical Dispatch',()=>{const db=fixture();generateDay({startDate:'2026-08-17'},db);const oldDispatch={...db.prepare('SELECT id,vehicle_id FROM dispatches ORDER BY id LIMIT 1').get()};setDefaultVehicle('zone',1,{vehicleId:1,reason:'Approved stable route',changedBy:'Office Planner'},db);const audit=db.prepare("SELECT * FROM master_change_history WHERE change_type='default_vehicle_changed'").get();assert.equal(audit.changed_by,'Office Planner');assert.equal(audit.reason,'Approved stable route');assert.deepEqual(JSON.parse(audit.before_json),{defaultVehicleId:null});assert.deepEqual(JSON.parse(audit.after_json),{defaultVehicleId:1});assert.deepEqual({...db.prepare('SELECT id,vehicle_id FROM dispatches WHERE id=?').get(oldDispatch.id)},oldDispatch)})

test('API uses Session schedule permission and UI keeps Default separate from daily override',()=>{const api=fs.readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../src/WeeklyDispatchPage.jsx',import.meta.url),'utf8'),zone=fs.readFileSync(new URL('../src/ZoneGroupManager.jsx',import.meta.url),'utf8');assert.ok(api.includes('default-vehicle'));assert.ok(api.includes('setDefaultVehicle(parts[3],Number(parts[4])'));assert.match(api,/if\(!canManageSchedules\(session\)\)return sendJson\(response,403/);assert.match(api,/changedBy:session\.employeeName/);for(const token of ["defaultVehicle.label","defaultVehicle.changeToday"])assert.match(ui,new RegExp(token));assert.match(zone,/\/api\/default-vehicle\/\$\{scope\}\/\$\{selected\.id\}/);assert.match(zone,/defaultVehicle\.update/);assert.match(zone,/defaultVehicle\.clear/)})

test('all new labels are complete and Malay never falls back to English',()=>{assert.equal(SCHEMA_VERSION,36);const keys=['label','unassigned','changeToday','update','clear'];for(const language of ['en','ms','zh'])for(const key of keys)assert.ok(messages[language][`defaultVehicle.${key}`]);assert.equal(messages.ms['defaultVehicle.label'],'Kenderaan Lalai');assert.notEqual(messages.ms['defaultVehicle.update'],messages.en['defaultVehicle.update'])})
