import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql,SCHEMA_VERSION} from '../server/schema.mjs'
import {applyV35Migration} from '../server/migrationV35.mjs'
import {commercialOptions,resolveBuyerPayer,resolvePrimaryEndLocation} from '../server/dispatchCommercialService.mjs'
import {createTrip,updateTrip} from '../server/dispatchService.mjs'

function fixture(){const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;${schemaSql}`);db.exec(`INSERT INTO operational_locations(location_code,name,location_type,operational_type,address,latitude,longitude,can_start,can_end,status,is_active) VALUES('YARD','Lee Sai Ker Enterprise','depot','Company Yard','Yard',1.4449,110.3337,1,0,'active',1);INSERT INTO buyers(buyer_code,buyer_name,status) VALUES('BY10001','Triple C','active'),('BY10002','Multiple C','active'),('BY10003','Inactive Buyer','paused');INSERT INTO operational_locations(location_code,name,location_type,operational_type,address,latitude,longitude,buyer_id,can_end,status,is_active) VALUES('BB10001','10 Mile','factory','Buyer','Ten Mile',1.5,110.4,1,1,'active',1),('BB10002','Samarahan','factory','Buyer','Samarahan',1.6,110.5,2,1,'active',1),('BB10003','No GPS','factory','Buyer','Missing',NULL,NULL,1,1,'active',1),('BB10004','Disabled','factory','Buyer','Disabled',1.7,110.6,1,1,'closed',0);INSERT INTO weekly_dispatch_plans(week_start,status) VALUES('2026-08-03','draft');INSERT INTO dispatch_days(weekly_plan_id,dispatch_date,status) VALUES(1,'2026-08-09','draft')`);return db}

test('commercial dropdown options include only active Buyers and active GPS-valid delivery locations',()=>{const db=fixture(),options=commercialOptions(db);assert.deepEqual(options.buyers.map(x=>x.buyerName),['Multiple C','Triple C']);assert.deepEqual(new Set(options.endLocations.map(x=>x.locationName)),new Set(['10 Mile','Samarahan','Lee Sai Ker Enterprise']));assert.ok(options.endLocations.find(x=>x.locationType==='Company Yard'));assert.ok(!options.endLocations.some(x=>x.locationName==='No GPS'||x.locationName==='Disabled'))})

test('Buyer/Payer and Primary End Location are independent and Triple C plus Multiple C Samarahan is legal',()=>{const db=fixture(),buyer=resolveBuyerPayer({referenceId:1},db),end=resolvePrimaryEndLocation({referenceId:3},db);assert.equal(buyer.buyerName,'Triple C');assert.equal(end.endLocationParentName,'Multiple C');assert.throws(()=>resolveBuyerPayer({referenceId:3},db),/not active/);assert.throws(()=>resolvePrimaryEndLocation({referenceId:4},db),/valid GPS/);assert.throws(()=>resolvePrimaryEndLocation({referenceId:5},db),/active/);assert.equal(resolvePrimaryEndLocation({referenceId:1},db).endLocationName,'Lee Sai Ker Enterprise')})

test('Trip commercial snapshot freezes master values and records one audited transaction',()=>{const db=fixture(),trip=createTrip({date:'2026-08-09'},db);updateTrip(trip.id,{buyerPayer:{referenceId:1},primaryEndLocation:{referenceId:3},reason:'Planned sale and delivery',changedBy:'Supervisor'},db);db.prepare("UPDATE buyers SET buyer_name='Renamed' WHERE id=1").run();db.prepare("UPDATE operational_locations SET name='Changed',latitude=9 WHERE id=3").run();let row=db.prepare('SELECT * FROM dispatches WHERE id=?').get(trip.dispatch_id);assert.equal(row.buyer_name,'Triple C');assert.equal(row.end_location_name,'Samarahan');assert.equal(row.end_location_parent_name,'Multiple C');assert.equal(row.end_latitude,1.6);const audit=db.prepare("SELECT * FROM dispatch_change_logs WHERE change_type='trip_commercial_route_updated'").get();assert.equal(audit.actor,'Supervisor');assert.match(audit.after_json,/Planned sale and delivery/);db.exec("CREATE TRIGGER fail_commercial_audit BEFORE INSERT ON dispatch_change_logs WHEN NEW.change_type='trip_commercial_route_updated' BEGIN SELECT RAISE(ABORT,'audit failed'); END");assert.throws(()=>updateTrip(trip.id,{buyerPayer:{referenceId:2},primaryEndLocation:{referenceId:2},reason:'rollback',changedBy:'Supervisor'},db),/audit failed/);row=db.prepare('SELECT buyer_name,end_location_name FROM dispatches WHERE id=?').get(trip.dispatch_id);assert.deepEqual({...row},{buyer_name:'Triple C',end_location_name:'Samarahan'})})

test('Buyer choice never defaults or locks End Location and Company Yard remains an explicit fallback',()=>{const db=fixture(),trip=createTrip({date:'2026-08-09'},db),before=db.prepare('SELECT buyer_reference_id,end_location_reference_id FROM dispatches WHERE id=?').get(trip.dispatch_id);assert.deepEqual({...before},{buyer_reference_id:null,end_location_reference_id:null});updateTrip(trip.id,{buyerPayer:{referenceId:1},primaryEndLocation:{referenceId:1},reason:'Return to yard',changedBy:'Supervisor'},db);const row=db.prepare('SELECT buyer_name,end_location_name FROM dispatches WHERE id=?').get(trip.dispatch_id);assert.deepEqual({...row},{buyer_name:'Triple C',end_location_name:'Lee Sai Ker Enterprise'})})

test('v35 migration preserves legacy Dispatch/Stop counts and leaves snapshots NULL',()=>{const db=fixture();db.prepare("INSERT INTO dispatches(dispatch_date,status) VALUES('2026-08-08','completed')").run();db.exec('DELETE FROM schema_meta;INSERT INTO schema_meta(version) VALUES(34)');const result=applyV35Migration(db),legacy=db.prepare("SELECT * FROM dispatches WHERE dispatch_date='2026-08-08'").get();assert.equal(result.schemaVersion,35);assert.equal(result.before.dispatches,result.after.dispatches);assert.equal(result.before.stops,result.after.stops);assert.equal(legacy.buyer_reference_id,null);assert.equal(legacy.end_location_reference_id,null);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})

test('Trip UI exposes independent dropdowns and API keeps Session scheduling authorization',()=>{const ui=fs.readFileSync(new URL('../src/WeeklyDispatchPage.jsx',import.meta.url),'utf8'),server=fs.readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8');assert.equal(SCHEMA_VERSION,39);for(const token of ['TripCommercialControl','Buyer / Payer','Primary End Location','Recommended','Save Buyer & End Location'])assert.match(ui,new RegExp(token));assert.match(server,/canManageSchedules\(session\).*Schedule management permission is required/);assert.match(server,/changedBy:session\.employeeName,canViewEmployeeHome:canManageEmployees\(session\)/);assert.doesNotMatch(ui,/filter\([^\n]*buyerReferenceId===Number\(buyerId\)/)})
