import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql,SCHEMA_VERSION} from '../server/schema.mjs'
import {applyV34Migration} from '../server/migrationV34.mjs'
import {companyYard,resolveStartLocation,startLocationOptions} from '../server/dispatchStartLocationService.mjs'
import {createTrip,getDispatchDay,updateTrip} from '../server/dispatchService.mjs'

function fixture(){const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;${schemaSql}`);db.exec(`INSERT INTO operational_locations(location_code,name,location_type,operational_type,address,latitude,longitude,can_start,status,is_active) VALUES('YARD-1','Lee Sai Ker Enterprise','depot','Company Yard','Official yard',1.4449047,110.3337165,1,'active',1);INSERT INTO employees(employee_code,name,job_role,employment_status,is_active,home_address,home_latitude,home_longitude) VALUES('EMP-1','Driver One','driver','active',1,'Driver home',1.5,110.4),('EMP-2','No GPS Driver','driver','active',1,'Unknown',NULL,NULL);INSERT INTO customers(jodoo_customer_id,name,status,is_active) VALUES('10001','Customer','active',1);INSERT INTO branches(jodoo_branch_id,customer_id,branch_name,address,latitude,longitude,status,is_active) VALUES('10001',1,'Branch','Branch address',1.6,110.5,'active',1);INSERT INTO weekly_dispatch_plans(week_start,status) VALUES('2026-08-03','draft');INSERT INTO dispatch_days(weekly_plan_id,dispatch_date,status) VALUES(1,'2026-08-09','draft')`);return db}

test('new Trip defaults to the active Company Yard and freezes a complete Factory snapshot',()=>{const db=fixture(),trip=createTrip({date:'2026-08-09',changedBy:'Planner'},db),row=db.prepare('SELECT * FROM dispatches WHERE id=?').get(trip.dispatch_id);assert.equal(SCHEMA_VERSION,37);assert.equal(row.start_location_type,'factory');assert.equal(row.start_location_name,'Lee Sai Ker Enterprise');assert.equal(row.start_latitude,1.4449047);assert.equal(row.start_longitude,110.3337165);db.prepare("UPDATE operational_locations SET name='New Yard Name',latitude=2 WHERE id=1").run();const unchanged=db.prepare('SELECT start_location_name,start_latitude FROM dispatches WHERE id=?').get(trip.dispatch_id);assert.deepEqual({...unchanged},{start_location_name:'Lee Sai Ker Enterprise',start_latitude:1.4449047})})

test('Employee Home, Saved Location and Custom Location resolve valid snapshots without guessing GPS',()=>{const db=fixture();assert.throws(()=>resolveStartLocation({type:'employee_home',referenceId:1},{canViewEmployeeHome:false},db),/permission/);const home=resolveStartLocation({type:'employee_home',referenceId:1},{canViewEmployeeHome:true},db);assert.equal(home.startLocationName,'Driver One');assert.throws(()=>resolveStartLocation({type:'employee_home',referenceId:2},{canViewEmployeeHome:true},db),/Home GPS Not Set/);const branch=resolveStartLocation({type:'saved_location',referenceType:'customer_branch',referenceId:1},{},db);assert.equal(branch.startAddress,'Branch address');assert.throws(()=>resolveStartLocation({type:'saved_location',referenceType:'customer_branch',referenceId:999},{},db),/not available/);const custom=resolveStartLocation({type:'custom',name:'Temporary gate',address:'Map selected address',latitude:1.7,longitude:110.6},{},db);assert.equal(custom.startLocationReferenceId,null);assert.equal(custom.startLatitude,1.7)})

test('updating a Trip Start Location is transactional, audited and master changes do not alter its snapshot',()=>{const db=fixture(),trip=createTrip({date:'2026-08-09'},db);updateTrip(trip.id,{driverId:1,startLocation:{type:'employee_home',referenceId:1},canViewEmployeeHome:true,changedBy:'Supervisor'},db);db.prepare("UPDATE employees SET home_address='Changed',home_latitude=9 WHERE id=1").run();let row=db.prepare('SELECT * FROM dispatches WHERE id=?').get(trip.dispatch_id);assert.equal(row.start_address,'Driver home');assert.equal(row.start_latitude,1.5);assert.equal(db.prepare("SELECT COUNT(*) n FROM dispatch_change_logs WHERE change_type='trip_start_location_updated'").get().n,1);db.exec("CREATE TRIGGER fail_start_audit BEFORE INSERT ON dispatch_change_logs WHEN NEW.change_type='trip_start_location_updated' BEGIN SELECT RAISE(ABORT,'audit failed'); END");assert.throws(()=>updateTrip(trip.id,{startLocation:{type:'custom',name:'Bad',address:'Must rollback',latitude:2,longitude:111},changedBy:'Supervisor'},db),/audit failed/);row=db.prepare('SELECT * FROM dispatches WHERE id=?').get(trip.dispatch_id);assert.equal(row.start_address,'Driver home')})

test('v34 migration preserves legacy Dispatch and Stop counts and leaves historical snapshots NULL',()=>{const db=fixture();db.prepare("INSERT INTO dispatches(dispatch_date,status) VALUES('2026-08-08','completed')").run();db.exec('DELETE FROM schema_meta;INSERT INTO schema_meta(version) VALUES(33)');const before={dispatches:db.prepare('SELECT COUNT(*) n FROM dispatches').get().n,stops:db.prepare('SELECT COUNT(*) n FROM dispatch_stops').get().n},result=applyV34Migration(db),legacy=db.prepare("SELECT * FROM dispatches WHERE dispatch_date='2026-08-08'").get();assert.equal(result.schemaVersion,34);assert.equal(legacy.start_location_type,null);assert.deepEqual({dispatches:result.after.dispatches,stops:result.after.stops},before);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})

test('options expose Home only when explicitly authorized and planner UI uses per-Trip snapshot editor',()=>{const db=fixture(),hidden=startLocationOptions({driverId:1,includeEmployeeHome:false},db),visible=startLocationOptions({driverId:1,includeEmployeeHome:true},db),ui=fs.readFileSync(new URL('../src/WeeklyDispatchPage.jsx',import.meta.url),'utf8'),service=fs.readFileSync(new URL('../server/dispatchStartLocationService.mjs',import.meta.url),'utf8');assert.equal(hidden.employeeHome,null);assert.equal(visible.employeeHome.startLocationName,'Driver One');for(const token of ['StartLocationControl','Factory','Employee Home','Saved Location','Custom Location','SharedGpsInput'])assert.match(ui,new RegExp(token));assert.doesNotMatch(service,/1\.4449047|110\.3337165/);assert.equal(companyYard(db).name,'Lee Sai Ker Enterprise');const viewTrip=createTrip({date:'2026-08-09'},db);assert.equal(db.prepare('SELECT start_location_type value FROM dispatches WHERE id=?').get(viewTrip.dispatch_id).value,'factory');assert.ok(getDispatchDay('2026-08-09',db))})
