import test from 'node:test'
import assert from 'node:assert/strict'
import { DatabaseSync } from 'node:sqlite'
import { schemaSql } from '../server/schema.mjs'
import { approveDay, assignAreaStops, assignVehicleDay, createScheduleException, driverToday, generateDay, generateWeek, getDispatchDay, publishDay, updateStop } from '../server/dispatchService.mjs'
import { addTemporaryLocation, createSpecialRequest, scheduleSpecialRequest } from '../server/specialRequestService.mjs'
import { assignAreaZone, createEmployee, createVehicle, createZoneGroup, listResources, mergeZoneGroups, setZoneActive, splitZoneGroup } from '../server/resourceService.mjs'

function fixture(){
  const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql)
  db.prepare("INSERT INTO areas(jodoo_area_id,name) VALUES('A1','North')").run()
  db.prepare("INSERT INTO customers(jodoo_customer_id,name,payment_type,occ_price) VALUES('C1','Alpha','Cash',0.55)").run()
  db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,area_id,branch_name,address,latitude,longitude) VALUES('B1',1,1,'Alpha Branch','Address',3.1,101.6)").run()
  db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S1',1,'B1','Weekly','Monday')").run()
  db.prepare("INSERT INTO employees(employee_code,name,job_role) VALUES('D1','Driver One','driver'),('D2','Driver Two','driver')").run()
  db.prepare("INSERT INTO vehicles(vehicle_code,registration_number) VALUES('V1','ABC1')").run()
  return db
}
const prepareDay=(db,date='2026-07-20')=>{generateWeek({startDate:date},db);let day=getDispatchDay(date,db);assignVehicleDay(date,1,{driverId:1},db);for(const stop of day.unassignedStops)updateStop(stop.id,{date,vehicleId:1,tripNumber:1},db);return getDispatchDay(date,db)}

test('生成未来七天草稿且重复生成不会重复站点',()=>{const db=fixture();const first=generateWeek({startDate:'2026-07-20'},db);assert.equal(first.days.length,7);assert.equal(first.days[0].status,'draft');const count=db.prepare('SELECT COUNT(*) count FROM dispatch_stops').get().count;generateWeek({startDate:'2026-07-20'},db);assert.equal(db.prepare('SELECT COUNT(*) count FROM dispatch_stops').get().count,count)})
test('司机看不到未发布路线',()=>{const db=fixture();prepareDay(db);assert.equal(driverToday({driverId:1,date:'2026-07-20'},db).trips.length,0)})
test('司机只看到当天发布且分配给自己的路线',()=>{const db=fixture();prepareDay(db);approveDay('2026-07-20',{},db);publishDay('2026-07-20',{},db);assert.equal(driverToday({driverId:1,date:'2026-07-20'},db).trips.length,1);assert.equal(driverToday({driverId:2,date:'2026-07-20'},db).trips.length,0);assert.equal(driverToday({driverId:1,date:'2026-07-21'},db).trips.length,0)})
test('已批准路线改变后变成需要重新批准并保留修改记录',()=>{const db=fixture();const day=prepareDay(db);approveDay('2026-07-20',{},db);updateStop(day.stops[0].id,{stopSequence:2,changedBy:'Manager'},db);assert.equal(getDispatchDay('2026-07-20',db).status,'reapproval_required');assert.equal(db.prepare('SELECT COUNT(*) count FROM dispatch_change_logs').get().count>0,true)})
test('老客户临时请求可以直接加入路线且不会重复加入',()=>{const db=fixture();prepareDay(db);const request=createSpecialRequest({existingBranchId:'B1',requestedCollectionDate:'2026-07-20',createdBy:'Office'},db);scheduleSpecialRequest(request.id,{date:'2026-07-20',tripNumber:1},db);scheduleSpecialRequest(request.id,{date:'2026-07-20',tripNumber:1},db);assert.equal(db.prepare('SELECT COUNT(*) count FROM dispatch_stops WHERE source_special_request_id=?').get(request.id).count,1)})

for(const [field,,label] of [['customerId','CNEW','CustomerID'],['branchId','BNEW','BranchID'],['occPrice',0.5,'OCC Price'],['paymentType','Cash','Payment Type']]){
  test(`新客户缺少 ${label} 时不能发布`,()=>{const db=fixture();prepareDay(db);const complete={customerId:'CNEW',branchId:'BNEW',occPrice:0.5,paymentType:'Cash'};delete complete[field];const request=createSpecialRequest({temporaryCustomerName:'New Shop',address:'New address',requestedCollectionDate:'2026-07-20',createdBy:'Office',...complete},db);scheduleSpecialRequest(request.id,{date:'2026-07-20',vehicleId:1,tripNumber:1},db);approveDay('2026-07-20',{},db);assert.throws(()=>publishDay('2026-07-20',{},db),new RegExp(label.replace(' ','|')) )})
}

test('已承诺客户未安排时不能发布',()=>{const db=fixture();prepareDay(db);createSpecialRequest({existingBranchId:'B1',requestedCollectionDate:'2026-07-20',promisedToCustomer:true,createdBy:'Office'},db);approveDay('2026-07-20',{},db);assert.throws(()=>publishDay('2026-07-20',{},db),/已承诺客户/)})
test('临时改期建立 exception 但不修改固定排程',()=>{const db=fixture();createScheduleException({scheduleId:'S1',type:'move_date',originalDate:'2026-07-20',targetDate:'2026-07-21',createdBy:'Manager'},db);assert.equal(db.prepare("SELECT days_of_week value FROM branch_schedules WHERE jodoo_schedule_id='S1'").get().value,'Monday');assert.equal(db.prepare('SELECT permanent FROM schedule_exceptions').get().permanent,0)})
test('周计划拖到其他日期会自动建立 Schedule Exception',()=>{const db=fixture();const monday=prepareDay(db);updateStop(monday.stops[0].id,{date:'2026-07-21',vehicleId:1,tripNumber:1,changedBy:'Manager'},db);const exception=db.prepare("SELECT original_date originalDate,target_date targetDate,permanent FROM schedule_exceptions WHERE exception_type='move_date'").get();assert.deepEqual({...exception},{originalDate:'2026-07-20',targetDate:'2026-07-21',permanent:0});assert.equal(db.prepare("SELECT days_of_week value FROM branch_schedules WHERE jodoo_schedule_id='S1'").get().value,'Monday')})
test('单日生成只建立所选日期，周视图才返回七天',()=>{const db=fixture();const single=generateDay({startDate:'2026-07-20'},db);assert.equal(single.day.dispatch_date,'2026-07-20');assert.equal(db.prepare('SELECT COUNT(*) count FROM dispatch_days').get().count,1);const week=generateWeek({startDate:'2026-07-20'},db);assert.equal(week.days.length,7)})
test('车辆栏来自 Vehicle Master，Area 不会制造车辆栏',()=>{const db=fixture();db.prepare("INSERT INTO areas(jodoo_area_id,name) VALUES('A2','South'),('A3','East')").run();generateDay({startDate:'2026-07-20'},db);const day=getDispatchDay('2026-07-20',db);assert.equal(day.vehicleBoards.length,1);assert.equal(day.vehicleBoards[0].slots.length,3);assert.equal(day.unassignedStops.length,1)})
test('维修或停用车辆不会显示，但既有客户保留在未分配池',()=>{const db=fixture();prepareDay(db);db.prepare("UPDATE vehicles SET status='maintenance' WHERE id=1").run();let day=getDispatchDay('2026-07-20',db);assert.equal(day.vehicleBoards.length,0);assert.equal(day.unassignedStops.length,1);db.prepare("UPDATE vehicles SET status='inactive' WHERE id=1").run();day=getDispatchDay('2026-07-20',db);assert.equal(day.vehicleBoards.length,0);assert.equal(day.unassignedStops.length,1)})
test('同一司机同一天不能重复分配，解除后可以改派',()=>{const db=fixture();db.prepare("INSERT INTO vehicles(vehicle_code,status) VALUES('V2','available')").run();generateDay({startDate:'2026-07-20'},db);assignVehicleDay('2026-07-20',1,{driverId:1},db);assert.throws(()=>assignVehicleDay('2026-07-20',2,{driverId:1},db),/已分配给 V1/);assignVehicleDay('2026-07-20',1,{driverId:null},db);assert.doesNotThrow(()=>assignVehicleDay('2026-07-20',2,{driverId:1},db))})
test('车辆同一天支持多个 Assistant 和 Crew',()=>{const db=fixture();db.prepare("INSERT INTO employees(employee_code,name,job_role) VALUES('A1','Assistant One','assistant'),('A2','Crew Two','crew')").run();generateDay({startDate:'2026-07-20'},db);assignVehicleDay('2026-07-20',1,{assistantIds:[3,4]},db);const board=getDispatchDay('2026-07-20',db).vehicleBoards[0];assert.deepEqual(board.assistantIds,[3,4]);assert.equal(board.assistants.length,2)})
test('未分配池按 Zone Group 和 Area 汇总并可整组分配',()=>{const db=fixture();db.prepare("UPDATE branches SET time_restriction='Before 12pm' WHERE id=1").run();db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,area_id,branch_name,address) VALUES('B2',1,1,'Beta Branch','Address 2')").run();db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S2',2,'B2','Weekly','Monday')").run();generateDay({startDate:'2026-07-20'},db);db.prepare('UPDATE dispatch_stops SET estimated_weight_kg=25').run();let day=getDispatchDay('2026-07-20',db),group=day.unassignedGroups[0],zone=day.unassignedZones[0];assert.equal(zone.zoneGroupName,'古晋 A区');assert.equal(zone.areas.length,1);assert.equal(group.customerCount,2);assert.equal(zone.estimatedWeightKg,50);assert.equal(zone.missingGpsCount,1);assert.equal(zone.timeRestrictionCount,1);assignAreaStops('2026-07-20',{areaId:`zone:${zone.zoneGroupId}`,stopIds:zone.stops.map(x=>x.id),vehicleId:1,tripNumber:2},db);day=getDispatchDay('2026-07-20',db);assert.equal(day.unassignedStops.length,0);assert.equal(day.vehicleBoards[0].slots[1].stops.length,2)})
test('Vehicle 和 Employee Master 保存选择器所需提示资料',()=>{const db=fixture();db.prepare("INSERT INTO operational_locations(name,location_type,is_active) VALUES('Main Depot','depot',1)").run();createVehicle({vehicleCode:'V3',vehicleName:'Heavy Lorry',registrationNumber:'QAA123',capacityKg:5000,defaultBaseLocationId:1,preferredAreaIds:[1]},db);createEmployee({employeeCode:'DR3',name:'Driver Three',jobRole:'driver',employmentStatus:'active',defaultBaseLocationId:1,defaultAreaId:1},db);const resources=listResources(db),vehicle=resources.vehicles.find(x=>x.vehicleCode==='V3'),employee=resources.employees.find(x=>x.employeeCode==='DR3');assert.equal(vehicle.vehicleName,'Heavy Lorry');assert.deepEqual(vehicle.preferredAreas,['North']);assert.equal(vehicle.defaultBase,'Main Depot');assert.equal(employee.defaultArea,'North');assert.equal(employee.defaultBase,'Main Depot')})
test('系统初始化七个正确名称 Zone，数量可动态增加且 Area 可调整',()=>{const db=fixture(),names=db.prepare('SELECT name FROM zone_groups ORDER BY sort_order').all().map(item=>item.name);assert.deepEqual(names,['古晋 A区','古晋 B区','西连 A区','西连 B区','Samarahan A区','Samarahan B区','伦乐 / 石隆门区']);createZoneGroup({name:'伦乐区'},db);assert.equal(db.prepare('SELECT COUNT(*) count FROM zone_groups').get().count,8);assignAreaZone(1,2,{changedBy:'Supervisor'},db);const resources=listResources(db);assert.equal(resources.areas[0].zoneGroup,'古晋 B区');assert.equal(resources.areas[0].zoneAssignmentStatus,'confirmed')})
test('Zone 可停用、启用、拆分和合并且不删除历史 Zone',()=>{const db=fixture();const created=createZoneGroup({name:'石隆门区'},db);setZoneActive(created.id,false,{},db);assert.equal(db.prepare('SELECT is_active value FROM zone_groups WHERE id=?').get(created.id).value,0);setZoneActive(created.id,true,{},db);const split=splitZoneGroup({sourceZoneId:1,name:'伦乐区',areaIds:[1],changedBy:'Supervisor'},db);assert.equal(db.prepare('SELECT zone_group_id value FROM areas WHERE id=1').get().value,split.zone.id);mergeZoneGroups({sourceZoneIds:[split.zone.id],targetZoneId:7,changedBy:'Supervisor'},db);assert.equal(db.prepare('SELECT zone_group_id value FROM areas WHERE id=1').get().value,7);assert.equal(db.prepare('SELECT is_active value FROM zone_groups WHERE id=?').get(split.zone.id).value,0);assert.equal(db.prepare('SELECT COUNT(*) count FROM zone_groups WHERE id=?').get(split.zone.id).count,1)})
test('旧派车保留 Zone 快照，新派车使用 Area 最新归属',()=>{const db=fixture();generateDay({startDate:'2026-07-20'},db);assert.equal(getDispatchDay('2026-07-20',db).stops[0].zoneGroup,'古晋 A区');assignAreaZone(1,2,{changedBy:'Supervisor'},db);assert.equal(getDispatchDay('2026-07-20',db).stops[0].zoneGroup,'古晋 A区');generateDay({startDate:'2026-07-27'},db);assert.equal(getDispatchDay('2026-07-27',db).stops[0].zoneGroup,'古晋 B区')})
test('永久改期更新固定排程',()=>{const db=fixture();createScheduleException({scheduleId:'S1',type:'move_date',originalDate:'2026-07-20',targetDate:'2026-07-21',dayOfWeek:'Tuesday',permanent:true,createdBy:'Manager'},db);assert.equal(db.prepare("SELECT days_of_week value FROM branch_schedules WHERE jodoo_schedule_id='S1'").get().value,'Tuesday')})
test('临时 GPS 不会自动覆盖正式 GPS',()=>{const db=fixture();const before=db.prepare('SELECT latitude,longitude FROM branches WHERE id=1').get();addTemporaryLocation({branchId:1,latitude:4,longitude:102,locationSource:'Driver Captured'},db);assert.deepEqual(db.prepare('SELECT latitude,longitude FROM branches WHERE id=1').get(),before);assert.equal(db.prepare('SELECT verification_status status FROM temporary_locations').get().status,'pending_supervisor')})
test('相同临时请求不会重复建立',()=>{const db=fixture();const payload={existingBranchId:'B1',requestedCollectionDate:'2026-07-20',createdBy:'Office'};const a=createSpecialRequest(payload,db),b=createSpecialRequest(payload,db);assert.equal(a.id,b.id);assert.equal(b.deduplicated,true)})
