import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyDiyConfirmedSchedules} from '../server/diyConfirmedSchedules.mjs'
import {nextCollectionDate} from '../shared/scheduleRecurrence.js'
function fixture(){const db=new DatabaseSync(':memory:');db.exec(schemaSql);for(const [name,type] of [['superseded_by_schedule_id','INTEGER'],['superseded_reason','TEXT'],['superseded_at','TEXT'],['superseded_by','TEXT']])db.exec(`ALTER TABLE branch_schedules ADD COLUMN ${name} ${type}`);db.exec(`INSERT INTO branches(id,jodoo_branch_id,branch_name,is_active) VALUES(79,'10389','DIY TEBEDU',1),(78,'10408','DIY SJC',1);INSERT INTO branch_schedules(id,jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week,updated_at) VALUES(2,'10422',79,'10389','Weekly','Monday,Thursday','2026-07-19 10:07:16'),(5,'10419',79,'10389','Weekly','Tuesday,Friday','2026-07-19 10:07:16'),(1,'10423',78,'10408','Weekly','Wednesday,Saturday','2026-07-19 10:07:16'),(9,'10414',78,'10408','Weekly','Monday,Thursday','2026-07-19 10:07:16')`);return db}
test('preview rolls back; confirmed schedules persist with retained history and audit',()=>{const db=fixture();try{applyDiyConfirmedSchedules(db,{today:'2026-09-09'});assert.equal(db.prepare('SELECT COUNT(*) n FROM branch_schedules WHERE is_active=1').get().n,4);const result=applyDiyConfirmedSchedules(db,{apply:true,today:'2026-09-09'});assert.equal(result.items[0].nextCollectionDate,'2026-09-17');assert.equal(db.prepare('SELECT COUNT(*) n FROM branch_schedules WHERE is_active=1').get().n,2);assert.equal(db.prepare('SELECT COUNT(*) n FROM branch_schedules').get().n,4);assert.equal(db.prepare('SELECT COUNT(*) n FROM audit_logs').get().n,2);const schedule=db.prepare('SELECT * FROM branch_schedules WHERE id=2').get();assert.equal(nextCollectionDate(schedule,'2026-09-18'),'2026-10-01');assert.equal(applyDiyConfirmedSchedules(db,{apply:true}).items[0].status,'already_applied')}finally{db.close()}})
test('changed second branch aborts both repairs atomically',()=>{const db=fixture();try{db.exec("UPDATE branch_schedules SET days_of_week='Friday' WHERE id=9");assert.throws(()=>applyDiyConfirmedSchedules(db,{apply:true}),/changed/);assert.equal(db.prepare('SELECT COUNT(*) n FROM branch_schedules WHERE is_active=1').get().n,4);assert.equal(db.prepare('SELECT COUNT(*) n FROM audit_logs').get().n,0)}finally{db.close()}})
