import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {cancelDiyObsoleteStops} from '../server/diyObsoleteStops.mjs'
function fixture(){const db=new DatabaseSync(':memory:');db.exec(schemaSql);db.exec(`INSERT INTO branches(id,jodoo_branch_id,branch_name) VALUES(79,'10389','DIY TEBEDU'),(78,'10408','DIY SJC');INSERT INTO branch_schedules(id,jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week,anchor_date,effective_date,recurrence_type,interval_weeks,fixed_weekday) VALUES(2,'10422',79,'10389','Every 2 Weeks','Thursday','2026-09-17','2026-09-09','interval_weeks',2,'Thursday'),(9,'10414',78,'10408','Twice a week','Monday,Thursday',NULL,'2026-09-09','weekly',NULL,NULL)`);for(const[id,branch,date]of [[2873,78,'09'],[2980,78,'10'],[2981,79,'10'],[3090,79,'11'],[3197,78,'12'],[3333,78,'14'],[3334,79,'14'],[3447,79,'15']]){db.prepare('INSERT INTO dispatches(id,dispatch_date,status) VALUES(?,?,?)').run(id,'2026-09-'+date,id===2873?'in_progress':'draft');db.prepare("INSERT INTO dispatch_stops(id,dispatch_id,branch_id,stop_sequence,service_date,source_schedule_id) VALUES(?,?,?,1,?,?)").run(id,id,branch,'2026-09-'+date,branch===79?2:9)}return db}
test('preview preserves all rows; apply cancels only five, retains today and valid dates; retry is idempotent',()=>{const db=fixture();try{cancelDiyObsoleteStops(db,{today:'2026-09-09'});assert.equal(db.prepare("SELECT COUNT(*) n FROM dispatch_stops WHERE status='cancelled'").get().n,0);const result=cancelDiyObsoleteStops(db,{apply:true,today:'2026-09-09'});assert.equal(result.items.length,5);assert.ok(result.retained.every(s=>s.status==='locked'));assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_stops').get().n,8);assert.equal(db.prepare('SELECT COUNT(*) n FROM audit_logs').get().n,5);assert.ok(cancelDiyObsoleteStops(db,{apply:true}).items.every(s=>s.status==='already_cancelled'))}finally{db.close()}})
test('last stop receiving business activity rolls back the whole batch',()=>{const db=fixture();try{db.exec("UPDATE dispatch_stops SET arrived_at='2026-09-09' WHERE id=3447");assert.throws(()=>cancelDiyObsoleteStops(db,{apply:true,today:'2026-09-09'}),/business activity/);assert.equal(db.prepare("SELECT COUNT(*) n FROM dispatch_stops WHERE status='cancelled'").get().n,0)}finally{db.close()}})
test('released dispatch blocks cancellation',()=>{const db=fixture();try{db.exec("UPDATE dispatches SET status='released' WHERE id=2981");assert.throws(()=>cancelDiyObsoleteStops(db,{apply:true,today:'2026-09-09'}),/future draft/)}finally{db.close()}})
