import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV66Migration} from '../server/migrationV66.mjs'
import {driverGuideStatus,acknowledgeDriverGuide,GUIDE_VERSION} from '../server/driverGuideService.mjs'
function fixture(t){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.exec("INSERT INTO employees(id,employee_code,name,job_role,employment_status,is_active) VALUES(1,'D1','Driver','Driver','active',1),(2,'D2','Other','Driver','active',1),(3,'D3','Former','Driver','inactive',0)");t.after(()=>db.close());return db}
const ctx={employeeId:1,now:'2026-09-13T16:00:00Z'}
test('Malaysia midnight activates guide; reading does not acknowledge',t=>{const db=fixture(t);assert.equal(driverGuideStatus({...ctx,now:'2026-09-13T15:59:59Z'},db).active,false);assert.equal(driverGuideStatus(ctx,db).active,true);assert.equal(driverGuideStatus(ctx,db).readAt,null);assert.equal(driverGuideStatus(ctx,db).readAt,null);assert.throws(()=>acknowledgeDriverGuide({version:GUIDE_VERSION},{...ctx,now:'2026-09-13T15:59:59Z'},db),{code:'GUIDE_STALE'});assert.throws(()=>acknowledgeDriverGuide({version:'wrong'},ctx,db),{code:'GUIDE_STALE'});assert.equal(driverGuideStatus(ctx,db).readAt,null)})
test('explicit acknowledgement persists per employee and version across devices and retries',t=>{const db=fixture(t);const r=acknowledgeDriverGuide({version:GUIDE_VERSION,employeeId:2},ctx,db);assert(r.readAt);assert.equal(driverGuideStatus({...ctx},db).readAt,r.readAt);assert.equal(acknowledgeDriverGuide({version:GUIDE_VERSION},{...ctx,now:'2026-09-15T00:00:00Z'},db).readAt,r.readAt);assert.equal(driverGuideStatus({...ctx,employeeId:2},db).readAt,null);assert.throws(()=>driverGuideStatus({...ctx,employeeId:3},db),{code:'NOTICE_ACCESS'});assert.throws(()=>acknowledgeDriverGuide({version:GUIDE_VERSION},{...ctx,employeeId:999},db),{code:'NOTICE_ACCESS'})})
test('later hires receive first-use guide',t=>{const db=fixture(t);db.exec("INSERT INTO employees(id,employee_code,name,job_role,employment_status,is_active) VALUES(4,'D4','New Driver','Driver','active',1)");const s=driverGuideStatus({employeeId:4,now:'2026-10-01T00:00:00Z'},db);assert.equal(s.active,true);assert.equal(s.readAt,null)})
test('schema 65 migration and repeated startup preserve receipt',t=>{const db=fixture(t);db.exec('DROP TABLE employee_guide_reads;DELETE FROM schema_meta;INSERT INTO schema_meta(version) VALUES(65)');applyV66Migration(db);const r=acknowledgeDriverGuide({version:GUIDE_VERSION},ctx,db);applyV66Migration(db);assert.equal(driverGuideStatus(ctx,db).readAt,r.readAt);assert.equal(db.prepare('SELECT MAX(version) v FROM schema_meta').get().v,66);assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(),[])})
