import test from 'node:test'
import nodeAssert from 'node:assert/strict'
const assert={...nodeAssert,deepEqual:(actual,expected)=>nodeAssert.deepEqual({...actual},expected)}
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV28Migration} from '../server/migrationV28.mjs'
import {arriveAtStop,completeDriverStop,completeDriverTrip,confirmInvoiceCompleted,recordNoGoods,startDriverTrip} from '../server/driverExecutionService.mjs'
import {approveDay,generateWeek,saveDraftAdjustments} from '../server/dispatchService.mjs'

const date='2026-08-03',now=new Date('2026-08-03T01:00:00Z'),context={employeeId:1,role:'driver',today:date,now}
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='
function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);applyV28Migration(db);db.prepare("INSERT INTO areas(jodoo_area_id,name) VALUES('A','A')").run();db.prepare("INSERT INTO customers(jodoo_customer_id,name) VALUES('C','Customer')").run();db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,area_id,branch_name,address,latitude,longitude) VALUES('B1',1,1,'One','A',3.1,101.6),('B2',1,1,'Two','B',3.1,101.6)").run();db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S1',1,'B1','Weekly','Monday'),('S2',2,'B2','Weekly','Monday')").run();db.prepare("INSERT INTO vehicles(vehicle_code,status,operational_status) VALUES('V','available','active')").run();db.prepare("INSERT INTO employees(employee_code,name,job_role,employment_status,is_active) VALUES('D','Driver','Driver','active',1)").run();generateWeek({startDate:date},db);const stops=db.prepare('SELECT id FROM dispatch_stops ORDER BY id').all();saveDraftAdjustments({adjustments:stops.map(stop=>({stopId:stop.id,vehicleId:1,tripNumber:1})),reason:'test',changedBy:'test'},db);db.prepare('UPDATE dispatches SET driver_id=1').run();approveDay(date,{approvedBy:'Supervisor',reason:'ready'},db);const tripId=db.prepare('SELECT id FROM dispatch_trips WHERE EXISTS(SELECT 1 FROM dispatch_stops WHERE dispatch_trip_id=dispatch_trips.id)').get().id;startDriverTrip(tripId,context,db);return{db,tripId,stops:db.prepare('SELECT id FROM dispatch_stops WHERE dispatch_trip_id=? ORDER BY stop_sequence').all(tripId).map(x=>x.id)}}
const arrive=(db,id)=>arriveAtStop(id,{latitude:3.1001,longitude:101.6001,accuracy:10,captured_at:'2026-08-03T00:59:30Z'},context,db)

test('v28 is explicit, preserves records and is idempotent',()=>{const db=new DatabaseSync(':memory:');db.exec(schemaSql);const before=db.prepare('SELECT MAX(version) v FROM schema_meta').get().v;assert.equal(before,null);db.prepare('INSERT INTO schema_meta(version) VALUES(27)').run();assert.equal(applyV28Migration(db).schemaVersion,28);assert.equal(applyV28Migration(db).schemaVersion,28);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})
test('pending cannot complete; invoice confirmation then completion unlocks next stop',()=>{const{db,stops}=fixture();assert.throws(()=>completeDriverStop(stops[0],context,db),/Arrived/);arrive(db,stops[0]);assert.throws(()=>completeDriverStop(stops[0],context,db),/Invoice/);assert.equal(confirmInvoiceCompleted(stops[0],{},context,db).idempotent,false);assert.equal(confirmInvoiceCompleted(stops[0],{},context,db).idempotent,true);assert.equal(completeDriverStop(stops[0],context,db).nextStopId,stops[1]);assert.equal(completeDriverStop(stops[0],context,db).idempotent,true);assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_change_logs WHERE change_type=?').get('driver_stop_completed').n,1)})
test('no goods requires reason and real image, is idempotent and writes no invoice or weight',()=>{const{db,stops}=fixture(),root=fs.mkdtempSync(path.join(os.tmpdir(),'kcs-ng-'));arrive(db,stops[0]);assert.throws(()=>recordNoGoods(stops[0],{photo:{dataUrl:png}},context,db,{uploadsRoot:root}),/reason/);assert.throws(()=>recordNoGoods(stops[0],{reason:'None',photo:{dataUrl:'data:image/png;base64,SGVsbG8='}},context,db,{uploadsRoot:root}),/content/);const result=recordNoGoods(stops[0],{reason:'No stock',photo:{name:'..\\proof.png',dataUrl:png}},context,db,{uploadsRoot:root});assert.equal(result.status,'no_goods');assert.equal(recordNoGoods(stops[0],{reason:'No stock',photo:{dataUrl:png}},context,db,{uploadsRoot:root}).idempotent,true);const row=db.prepare('SELECT completion_outcome,collected_weight_kg,invoice_number FROM dispatch_stops WHERE id=?').get(stops[0]);assert.deepEqual(row,{completion_outcome:'no_goods',collected_weight_kg:null,invoice_number:null});assert.equal(db.prepare('SELECT COUNT(*) n FROM driver_no_goods_proofs').get().n,1);fs.rmSync(root,{recursive:true,force:true})})
test('trip completion requires all stops ended, is idempotent, and next trip ordering remains protected',()=>{const{db,tripId,stops}=fixture();arrive(db,stops[0]);confirmInvoiceCompleted(stops[0],{},context,db);completeDriverStop(stops[0],context,db);assert.throws(()=>completeDriverTrip(tripId,context,db),/unfinished/);arrive(db,stops[1]);const root=fs.mkdtempSync(path.join(os.tmpdir(),'kcs-ng-'));recordNoGoods(stops[1],{reason:'No stock',photo:{dataUrl:png}},context,db,{uploadsRoot:root});assert.equal(completeDriverTrip(tripId,context,db).status,'completed');assert.equal(completeDriverTrip(tripId,context,db).idempotent,true);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');fs.rmSync(root,{recursive:true,force:true})})
test('wrong driver, later stop and cross-outcome attempts are rejected',()=>{const{db,stops}=fixture();assert.throws(()=>arriveAtStop(stops[0],{latitude:3.1,longitude:101.6,accuracy:10,captured_at:'2026-08-03T00:59:30Z'},{...context,employeeId:2},db),/active driver/);assert.throws(()=>confirmInvoiceCompleted(stops[1],{},context,db),/handled first/);arrive(db,stops[0]);const root=fs.mkdtempSync(path.join(os.tmpdir(),'kcs-ng-'));recordNoGoods(stops[0],{reason:'None',photo:{dataUrl:png}},context,db,{uploadsRoot:root});assert.throws(()=>completeDriverStop(stops[0],context,db),/No Goods/);fs.rmSync(root,{recursive:true,force:true})})
