import test from 'node:test'
import nodeAssert from 'node:assert/strict'
const assert={...nodeAssert,deepEqual:(actual,expected)=>nodeAssert.deepEqual({...actual},expected)}
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV28Migration} from '../server/migrationV28.mjs'
import {arriveAtStop,completeDriverStop,completeDriverTrip,deferDriverStop,recordNoGoods,startDriverTrip} from '../server/driverExecutionService.mjs'
import {approveDay,driverToday,generateWeek,saveDraftAdjustments} from '../server/dispatchService.mjs'

const date='2026-08-03',now=new Date('2026-08-03T01:00:00Z'),context={employeeId:1,role:'driver',today:date,now}
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='
function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);applyV28Migration(db);db.prepare("INSERT INTO areas(jodoo_area_id,name) VALUES('A','A')").run();db.prepare("INSERT INTO customers(jodoo_customer_id,name) VALUES('C','Customer')").run();db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,area_id,branch_name,address,latitude,longitude) VALUES('B1',1,1,'One','A',3.1,101.6),('B2',1,1,'Two','B',3.1,101.6)").run();db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S1',1,'B1','Weekly','Monday'),('S2',2,'B2','Weekly','Monday')").run();db.prepare("INSERT INTO vehicles(vehicle_code,status,operational_status) VALUES('V','available','active')").run();db.prepare("INSERT INTO employees(employee_code,name,job_role,employment_status,is_active) VALUES('D','Driver','Driver','active',1)").run();generateWeek({startDate:date},db);const stops=db.prepare('SELECT id FROM dispatch_stops ORDER BY id').all();saveDraftAdjustments({adjustments:stops.map(stop=>({stopId:stop.id,vehicleId:1,tripNumber:1})),reason:'test',changedBy:'test'},db);db.prepare('UPDATE dispatches SET driver_id=1').run();approveDay(date,{approvedBy:'Supervisor',reason:'ready'},db);const tripId=db.prepare('SELECT id FROM dispatch_trips WHERE EXISTS(SELECT 1 FROM dispatch_stops WHERE dispatch_trip_id=dispatch_trips.id)').get().id;startDriverTrip(tripId,context,db);return{db,tripId,stops:db.prepare('SELECT id FROM dispatch_stops WHERE dispatch_trip_id=? ORDER BY stop_sequence').all(tripId).map(x=>x.id)}}
const arrive=(db,id)=>arriveAtStop(id,{latitude:3.1001,longitude:101.6001,accuracy:10,captured_at:'2026-08-03T00:59:30Z'},context,db)
const electronicBill=(db,stopId)=>{const row=db.prepare(`SELECT ds.id,ds.branch_id,ds.dispatch_trip_id,dt.dispatch_day_id,dd.dispatch_date,d.vehicle_id,d.driver_id,b.customer_id,b.jodoo_branch_id,b.branch_name,c.name customer_name,e.name driver_name,v.vehicle_code,v.registration_number FROM dispatch_stops ds JOIN dispatch_trips dt ON dt.id=ds.dispatch_trip_id JOIN dispatch_days dd ON dd.id=dt.dispatch_day_id JOIN dispatches d ON d.id=dt.dispatch_id JOIN branches b ON b.id=ds.branch_id JOIN customers c ON c.id=b.customer_id JOIN employees e ON e.id=d.driver_id JOIN vehicles v ON v.id=d.vehicle_id WHERE ds.id=?`).get(stopId);db.prepare(`INSERT INTO purchase_bills(bill_number,dispatch_stop_id,dispatch_trip_id,dispatch_day_id,branch_id,customer_id,driver_employee_id,vehicle_id,service_date,customer_name_snapshot,branch_code_snapshot,branch_name_snapshot,driver_name_snapshot,vehicle_code_snapshot,registration_number_snapshot,payment_method,weight_method,print_choice,subtotal_cents,total_cents,issued_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(`PTEST-${stopId}`,row.id,row.dispatch_trip_id,row.dispatch_day_id,row.branch_id,row.customer_id,row.driver_id,row.vehicle_id,row.dispatch_date,row.customer_name,row.jodoo_branch_id,row.branch_name,row.driver_name,row.vehicle_code,row.registration_number,'Credit','on_site','no_print',0,0,'2026-08-03T09:00:00+08:00')}

test('v28 is explicit, preserves records and is idempotent',()=>{const db=new DatabaseSync(':memory:');db.exec(schemaSql);const before=db.prepare('SELECT MAX(version) v FROM schema_meta').get().v;assert.equal(before,null);db.prepare('INSERT INTO schema_meta(version) VALUES(27)').run();assert.equal(applyV28Migration(db).schemaVersion,28);assert.equal(applyV28Migration(db).schemaVersion,28);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})
test('pending cannot complete; electronic Bill then completion unlocks next stop',()=>{const{db,stops}=fixture();assert.throws(()=>completeDriverStop(stops[0],context,db),/Arrived/);arrive(db,stops[0]);assert.throws(()=>completeDriverStop(stops[0],context,db),/Purchase Bill/);electronicBill(db,stops[0]);assert.equal(completeDriverStop(stops[0],context,db).nextStopId,stops[1]);assert.equal(completeDriverStop(stops[0],context,db).idempotent,true);assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_change_logs WHERE change_type=?').get('driver_stop_completed').n,1)})
test('deferred customer keeps its route position, stays selectable and opens the next customer',()=>{const{db,stops}=fixture();arrive(db,stops[0]);const moved=deferDriverStop(stops[0],{reason:'customer_requested_return'},context,db),ordered=db.prepare('SELECT id,stop_sequence stopSequence,arrived_at arrivedAt,override_note overrideNote FROM dispatch_stops WHERE status<>\'cancelled\' ORDER BY stop_sequence').all(),route=driverToday(context,db),shown=route.trips[0].stops;assert.equal(moved.nextStopId,stops[1]);assert.equal(ordered[0].id,stops[0]);assert.equal(ordered[1].id,stops[1]);assert.equal(ordered[0].stopSequence,1);assert.equal(ordered[0].arrivedAt,null);assert.equal(ordered[0].overrideNote,'driver_deferred');assert.equal(shown[0].id,stops[0]);assert.equal(shown[0].deferred,true);assert.equal(shown[0].canArrive,true);assert.equal(route.trips[0].currentStopId,stops[1]);assert.equal(shown[1].canArrive,true);assert.equal(JSON.parse(db.prepare("SELECT after_json value FROM dispatch_change_logs WHERE change_type='driver_stop_deferred'").get().value).sequencePreserved,true);arrive(db,stops[0]);electronicBill(db,stops[0]);assert.equal(completeDriverStop(stops[0],context,db).nextStopId,stops[1]);arrive(db,stops[1]);assert.throws(()=>deferDriverStop(stops[1],{reason:'invalid'},context,db),/valid reason/);electronicBill(db,stops[1]);assert.throws(()=>deferDriverStop(stops[1],{reason:'no_space_available'},context,db),/electronic Bill/)})
test('no goods requires reason and real image, is idempotent and writes no invoice or weight',()=>{const{db,stops}=fixture(),root=fs.mkdtempSync(path.join(os.tmpdir(),'kcs-ng-'));arrive(db,stops[0]);assert.throws(()=>recordNoGoods(stops[0],{photo:{dataUrl:png}},context,db,{uploadsRoot:root}),/reason/);assert.throws(()=>recordNoGoods(stops[0],{reason:'None',photo:{dataUrl:'data:image/png;base64,SGVsbG8='}},context,db,{uploadsRoot:root}),/content/);const result=recordNoGoods(stops[0],{reason:'No stock',photo:{name:'..\\proof.png',dataUrl:png}},context,db,{uploadsRoot:root});assert.equal(result.status,'no_goods');assert.equal(recordNoGoods(stops[0],{reason:'No stock',photo:{dataUrl:png}},context,db,{uploadsRoot:root}).idempotent,true);const row=db.prepare('SELECT completion_outcome,collected_weight_kg,invoice_number FROM dispatch_stops WHERE id=?').get(stops[0]);assert.deepEqual(row,{completion_outcome:'no_goods',collected_weight_kg:null,invoice_number:null});assert.equal(db.prepare('SELECT COUNT(*) n FROM driver_no_goods_proofs').get().n,1);fs.rmSync(root,{recursive:true,force:true})})
test('trip completion requires all stops ended, is idempotent, and next trip ordering remains protected',()=>{const{db,tripId,stops}=fixture();arrive(db,stops[0]);electronicBill(db,stops[0]);completeDriverStop(stops[0],context,db);assert.throws(()=>completeDriverTrip(tripId,context,db),/unfinished/);arrive(db,stops[1]);const root=fs.mkdtempSync(path.join(os.tmpdir(),'kcs-ng-'));recordNoGoods(stops[1],{reason:'No stock',photo:{dataUrl:png}},context,db,{uploadsRoot:root});assert.equal(completeDriverTrip(tripId,context,db).status,'completed');assert.equal(completeDriverTrip(tripId,context,db).idempotent,true);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');fs.rmSync(root,{recursive:true,force:true})})
test('wrong driver, later stop and cross-outcome attempts are rejected',()=>{const{db,stops}=fixture();assert.throws(()=>arriveAtStop(stops[0],{latitude:3.1,longitude:101.6,accuracy:10,captured_at:'2026-08-03T00:59:30Z'},{...context,employeeId:2},db),/active driver/);assert.throws(()=>completeDriverStop(stops[1],context,db),/handled first/);arrive(db,stops[0]);const root=fs.mkdtempSync(path.join(os.tmpdir(),'kcs-ng-'));recordNoGoods(stops[0],{reason:'None',photo:{dataUrl:png}},context,db,{uploadsRoot:root});assert.throws(()=>completeDriverStop(stops[0],context,db),/No Goods/);fs.rmSync(root,{recursive:true,force:true})})
