import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV27Migration} from '../server/migrationV27.mjs'
import {approveDay,driverToday,generateWeek,reopenDay,saveDraftAdjustments} from '../server/dispatchService.mjs'
import {ARRIVAL_RADIUS_METERS,arriveAtStop,isArrivalTestMode,startDriverTrip} from '../server/driverExecutionService.mjs'

const date='2026-08-03',now=new Date('2026-08-03T01:00:00.000Z'),captured_at='2026-08-03T00:59:30.000Z'
function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.prepare("INSERT OR IGNORE INTO schema_meta(version) VALUES(27)").run();db.prepare("INSERT INTO areas(jodoo_area_id,name) VALUES('A1','North')").run();db.prepare("INSERT INTO customers(jodoo_customer_id,name) VALUES('C1','Alpha')").run();db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,area_id,branch_name,address,latitude,longitude) VALUES('B1',1,1,'One','One',3.1,101.6),('B2',1,1,'Two','Two',NULL,NULL)").run();db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S1',1,'B1','Weekly','Monday'),('S2',2,'B2','Weekly','Monday')").run();db.prepare("INSERT INTO vehicles(vehicle_code,status,operational_status) VALUES('V1','available','active'),('V2','available','active')").run();db.prepare("INSERT INTO employees(employee_code,name,job_role,employment_status,is_active) VALUES('D1','Driver One','Driver','active',1),('D2','Driver Two','Driver','active',1),('O1','Office','Office','active',1)").run();generateWeek({startDate:date},db);const stops=db.prepare('SELECT id FROM dispatch_stops WHERE service_date=? ORDER BY id').all(date);saveDraftAdjustments({adjustments:[{stopId:stops[0].id,vehicleId:1,tripNumber:1},{stopId:stops[1].id,vehicleId:1,tripNumber:2}],reason:'Assign',changedBy:'Planner'},db);db.prepare('UPDATE dispatches SET driver_id=1 WHERE vehicle_id=1').run();approveDay(date,{approvedBy:'Supervisor',reason:'Ready'},db);return db}
const trip=(db,n)=>db.prepare('SELECT id FROM dispatch_trips WHERE trip_number=? AND EXISTS(SELECT 1 FROM dispatch_stops WHERE dispatch_trip_id=dispatch_trips.id)').get(n).id
const stop=(db,n)=>db.prepare('SELECT ds.id FROM dispatch_stops ds JOIN dispatch_trips dt ON dt.id=ds.dispatch_trip_id WHERE dt.trip_number=?').get(n).id
const context={employeeId:1,role:'driver',today:date,now}
const gps=(overrides={})=>({latitude:3.1001,longitude:101.6001,accuracy:10,captured_at,...overrides})

test('v26 to v27 migration is additive and idempotent',()=>{const db=new DatabaseSync(':memory:');db.exec(schemaSql);db.exec('DROP INDEX IF EXISTS dispatch_trips_execution_idx');for(const column of ['started_by_employee_id','started_at','execution_status'])db.exec(`ALTER TABLE dispatch_trips DROP COLUMN ${column}`);for(const column of ['arrived_by_employee_id','arrival_captured_at','arrival_distance_m','arrival_accuracy_m','arrival_longitude','arrival_latitude'])db.exec(`ALTER TABLE dispatch_stops DROP COLUMN ${column}`);db.exec('DELETE FROM schema_meta;INSERT INTO schema_meta(version) VALUES(26)');const first=applyV27Migration(db),second=applyV27Migration(db);assert.equal(first.schemaVersion,27);assert.equal(second.schemaVersion,27);assert.equal(db.prepare("SELECT COUNT(*) n FROM pragma_table_info('dispatch_stops') WHERE name='arrival_distance_m'").get().n,1)})
test('correct driver starts own approved Trip and repeat is idempotent',()=>{const db=fixture(),id=trip(db,1),first=startDriverTrip(id,context,db),second=startDriverTrip(id,context,db);assert.equal(first.status,'in_progress');assert.equal(second.idempotent,true);assert.equal(db.prepare("SELECT COUNT(*) n FROM dispatch_change_logs WHERE change_type='driver_trip_started'").get().n,1);assert.equal(db.prepare('SELECT started_by_employee_id id FROM dispatch_trips WHERE id=?').get(id).id,1)})
test('Draft, wrong date, other driver and inactive vehicle cannot Start',()=>{for(const mode of ['draft','date','driver','vehicle']){const db=fixture(),id=trip(db,1);if(mode==='draft')db.prepare("UPDATE dispatch_days SET status='draft'").run();if(mode==='vehicle')db.prepare("UPDATE vehicles SET operational_status='maintenance',status='maintenance' WHERE id=1").run();const input=mode==='date'?{...context,today:'2026-08-04'}:mode==='driver'?{...context,employeeId:2}:context;assert.throws(()=>startDriverTrip(id,input,db))}})
test('Trip order and one In Progress Trip per vehicle are enforced while empty earlier Trips are ignored',()=>{const db=fixture();assert.throws(()=>startDriverTrip(trip(db,2),context,db),/Trip 1/);startDriverTrip(trip(db,1),context,db);assert.throws(()=>startDriverTrip(trip(db,2),context,db),/already In Progress|must be completed/)})
test('valid nearby GPS arrives only the current Stop and persists evidence',()=>{const db=fixture(),tripId=trip(db,1),stopId=stop(db,1);startDriverTrip(tripId,context,db);const result=arriveAtStop(stopId,gps(),context,db),row=db.prepare('SELECT * FROM dispatch_stops WHERE id=?').get(stopId);assert.equal(result.status,'arrived');assert.ok(result.distanceMeters<ARRIVAL_RADIUS_METERS);assert.equal(row.arrived_by_employee_id,1);assert.equal(row.arrival_accuracy_m,10);assert.equal(row.status,'active');assert.ok(row.arrived_at);assert.equal(db.prepare("SELECT COUNT(*) n FROM dispatch_change_logs WHERE change_type='driver_stop_arrived'").get().n,1)})
test('repeat Arrive is idempotent without duplicate Audit',()=>{const db=fixture(),tripId=trip(db,1),stopId=stop(db,1);startDriverTrip(tripId,context,db);arriveAtStop(stopId,gps(),context,db);assert.equal(arriveAtStop(stopId,gps(),context,db).idempotent,true);assert.equal(db.prepare("SELECT COUNT(*) n FROM dispatch_change_logs WHERE change_type='driver_stop_arrived'").get().n,1)})
test('later sequence, other vehicle and forged identity are rejected',()=>{const db=fixture();startDriverTrip(trip(db,1),context,db);assert.throws(()=>arriveAtStop(stop(db,2),gps(),context,db));assert.throws(()=>arriveAtStop(stop(db,1),gps(),{...context,employeeId:2},db),/another driver/)})
test('out of range, poor accuracy, invalid coordinate and stale capture are rejected',()=>{for(const payload of [gps({latitude:4}),gps({accuracy:80}),gps({latitude:100}),gps({captured_at:'2026-08-01T00:00:00Z'})]){const db=fixture();startDriverTrip(trip(db,1),context,db);assert.throws(()=>arriveAtStop(stop(db,1),payload,context,db))}})
test('explicit remote-arrival test mode bypasses only accuracy and distance checks and audits the bypass',()=>{const db=fixture(),tripId=trip(db,1),stopId=stop(db,1);startDriverTrip(tripId,context,db);const result=arriveAtStop(stopId,gps({latitude:4,accuracy:83}),{...context,remoteArrivalTestMode:true},db),audit=JSON.parse(db.prepare("SELECT after_json value FROM dispatch_change_logs WHERE change_type='driver_stop_arrived'").get().value);assert.equal(result.remoteArrivalTestMode,true);assert.ok(result.distanceMeters>ARRIVAL_RADIUS_METERS);assert.equal(audit.remoteArrivalTestMode,true);assert.equal(isArrivalTestMode({KCS_REMOTE_ARRIVAL_TEST_MODE:'true'}),true);assert.equal(isArrivalTestMode({}),false)})
test('Branch without GPS remains visible but cannot Arrive',()=>{const db=fixture();db.prepare("UPDATE dispatch_trips SET execution_status='completed' WHERE id=?").run(trip(db,1));startDriverTrip(trip(db,2),context,db);assert.throws(()=>arriveAtStop(stop(db,2),gps(),context,db),/Customer GPS not set/);const route=driverToday({employeeId:1,role:'driver',today:date},db);assert.equal(route.trips.find(item=>item.tripNumber===2).stops[0].gpsAvailable,false)})
test('Trip start protects withdrawal and Draft adjustment',()=>{const db=fixture(),id=trip(db,1),stopId=stop(db,1);startDriverTrip(id,context,db);assert.throws(()=>reopenDay(date,{reason:'Try'},db),/Approved|in_progress/);assert.throws(()=>saveDraftAdjustments({adjustments:[{stopId,unassigned:true}],reason:'Try'},db),/protected/)})
test('Audit failure rolls back Start and Arrive transactions',()=>{const startDb=fixture(),tripId=trip(startDb,1);startDb.exec("CREATE TRIGGER fail_start BEFORE INSERT ON dispatch_change_logs WHEN NEW.change_type='driver_trip_started' BEGIN SELECT RAISE(ABORT,'start audit failed'); END");assert.throws(()=>startDriverTrip(tripId,context,startDb),/start audit failed/);assert.equal(startDb.prepare('SELECT execution_status s FROM dispatch_trips WHERE id=?').get(tripId).s,'not_started');assert.equal(startDb.prepare('SELECT status FROM dispatch_days').get().status,'approved');const arriveDb=fixture(),arriveTrip=trip(arriveDb,1),stopId=stop(arriveDb,1);startDriverTrip(arriveTrip,context,arriveDb);arriveDb.exec("CREATE TRIGGER fail_arrive BEFORE INSERT ON dispatch_change_logs WHEN NEW.change_type='driver_stop_arrived' BEGIN SELECT RAISE(ABORT,'arrival audit failed'); END");assert.throws(()=>arriveAtStop(stopId,gps(),context,arriveDb),/arrival audit failed/);assert.equal(arriveDb.prepare('SELECT arrived_at value FROM dispatch_stops WHERE id=?').get(stopId).value,null)})
test('Completed history remains unchanged and database integrity is ok',()=>{const db=fixture();const completed=stop(db,2);db.prepare("UPDATE dispatch_stops SET status='completed',completed_at='2026-01-01T00:00:00Z' WHERE id=?").run(completed);startDriverTrip(trip(db,1),context,db);assert.equal(db.prepare('SELECT completed_at value FROM dispatch_stops WHERE id=?').get(completed).value,'2026-01-01T00:00:00Z');assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})
test('mobile Trip action overrides the generic transparent card-button style',()=>{const css=readFileSync(new URL('../src/App.css',import.meta.url),'utf8');assert.match(css,/\.driver-trip>\.primary-mobile\{[^}]*color:#fff[^}]*background:var\(--green\)[^}]*text-align:center/)})
