import test,{after} from 'node:test'
import assert from 'node:assert/strict'
import React,{act} from 'react'
import {createServer} from 'vite'
import {JSDOM} from 'jsdom'
const dom=new JSDOM('<html><body><div id="root"></div></body></html>',{url:'https://localhost/'})
for(const k of ['window','document','Node','NodeFilter','HTMLElement','MutationObserver','Event','MouseEvent','localStorage','sessionStorage'])globalThis[k]=dom.window[k]
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true
globalThis.ResizeObserver=class{observe(){}disconnect(){}};globalThis.requestAnimationFrame=fn=>setTimeout(fn,0);globalThis.cancelAnimationFrame=clearTimeout
const{createRoot}=await import('react-dom/client'),vite=await createServer({logLevel:'silent',server:{middlewareMode:true},appType:'custom'});after(()=>vite.close())
const{I18nProvider}=await vite.ssrLoadModule('/src/i18n.jsx'),{default:Page}=await vite.ssrLoadModule('/src/EmployeeEarnings.jsx'),{earningsWords:words}=await vite.ssrLoadModule('/shared/earningsWords.js')
const periodFor=url=>{const date=new URL(url,'https://localhost').searchParams.get('date');return {start:date.slice(0,7)+(Number(date.slice(8))<=15?'-01':'-16'),end:date.slice(0,7)+(Number(date.slice(8))<=15?'-15':'-30'),due:'2026-09-20'}}
const report={period:{start:'2026-09-01',end:'2026-09-15',due:'2026-09-20'},companyKg:28000,pendingCompanyKg:0,unlinkedCount:0,rules:{version:0},items:[{employeeId:2,name:'Crew B',driverKg:0,crewKg:28000,pendingKg:0,pendingCount:0,rate:.03,crewRate:.03,amount:840,paidAt:null,details:[{recordId:1,collectionDate:'2026-09-15',deliveryDate:'2026-09-17',role:'crew',plate:'AAA',batch:'H001',ticket:'TN-1',weight:28010,settledKg:28000,matched:true}]}]}
test('personal reports use scoped API and mobile cards; daily details available in all languages',async()=>{for(const language of ['zh','en','ms']){const calls=[],root=createRoot(document.getElementById('root'));globalThis.fetch=async url=>{calls.push(url);return{ok:true,json:async()=>({...report,period:periodFor(url)})}};try{await act(async()=>root.render(React.createElement(I18nProvider,{language},React.createElement(Page,{personal:true}))));assert.equal(calls.length,2);assert.ok(calls.every(u=>u.startsWith('/api/mobile/earnings?')));assert.match(document.body.textContent,/RM 840.00/);assert.equal(document.querySelectorAll('table').length,0);assert.ok(![...document.querySelectorAll('button')].some(b=>b.textContent===words[language].settings));await act(async()=>[...document.querySelectorAll('button')].find(b=>b.textContent===words[language].details).click());assert.match(document.body.textContent,/TN-1/);assert.ok(document.body.textContent.includes(words[language].matched))}finally{await act(async()=>root.unmount())}}})
test('management report renders employees and opens rate settings with effective date and tiers',async()=>{const root=createRoot(document.getElementById('root'));globalThis.fetch=async url=>({ok:true,json:async()=>url.endsWith('/settings')?{revision:0,versions:[],defaults:{driver:[{from:0,rate:.03},{from:25000,rate:.04}],crewRate:.03}}:{...report,period:periodFor(url)}});try{await act(async()=>root.render(React.createElement(I18nProvider,{language:'zh'},React.createElement(Page))));assert.equal(document.querySelectorAll('table').length,2);await act(async()=>[...document.querySelectorAll('button')].find(b=>b.textContent===words.zh.settings).click());assert.equal(document.querySelectorAll('.earnings-tier').length,2);assert.ok(document.body.textContent.includes(words.zh.effective));assert.ok(document.body.textContent.includes(words.zh.crewRate))}finally{await act(async()=>root.unmount())}})
