import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {earningsSchema,applyV72Migration} from '../server/migrationV72.mjs'
import {earningsPeriod,earningsAmount,earningsReport,saveEarningsSettings,recordEarningsPayment,defaultEarningsRules} from '../server/earningsService.mjs'
const owner={employeeId:1,role:'owner_admin',today:'2026-09-20'}
function fixture(){const db=new DatabaseSync(':memory:');db.exec(`
CREATE TABLE employees(id INTEGER PRIMARY KEY,name,job_role,is_active,employment_status);
CREATE TABLE employee_job_roles(employee_id,role);
CREATE TABLE sales_settlements(id INTEGER PRIMARY KEY,vehicle_id,lines_json,revision);
CREATE TABLE cargo_batches(id INTEGER PRIMARY KEY,code,collection_date,vehicle_id,plate_snapshot);
CREATE TABLE cargo_batch_members(batch_id,employee_id,name_snapshot,role);
CREATE TABLE cargo_batch_unloads(record_id,batch_id,ticket_number);
CREATE TABLE unloading_weight_records(id INTEGER PRIMARY KEY,vehicle_id,service_date,confirmed_weight_kg,status);
CREATE TABLE schema_meta(version);
INSERT INTO schema_meta VALUES(71);
INSERT INTO employees VALUES(1,'Driver A','driver',1,'active'),(2,'Crew B','crew',1,'active'),(3,'Crew C','crew',1,'active'),(4,'Delivery driver','driver',1,'active');
INSERT INTO cargo_batches VALUES(1,'H001','2026-09-15',10,'AAA');
INSERT INTO cargo_batch_members VALUES(1,1,'Driver A','driver'),(1,2,'Crew B','crew'),(1,3,'Crew C','crew');
INSERT INTO cargo_batch_unloads VALUES(1,1,'TN-1');
INSERT INTO unloading_weight_records VALUES(1,10,'2026-09-17',28010,'confirmed');
`+earningsSchema);db.prepare('INSERT INTO sales_settlements VALUES(1,10,?,1)').run(JSON.stringify([{slipNumber:'TN-1',deliveryDate:'2026-09-17',weightKg:28000}]));return db}
test('half-month dates, leap year, year rollover and invalid dates',()=>{assert.deepEqual(earningsPeriod('2026-09-15'),{start:'2026-09-01',end:'2026-09-15',due:'2026-09-20'});assert.deepEqual(earningsPeriod('2026-12-16'),{start:'2026-12-16',end:'2026-12-31',due:'2027-01-05'});assert.equal(earningsPeriod('2028-02-29').end,'2028-02-29');assert.throws(()=>earningsPeriod('2026-02-30'),{code:'EARN_DATE'})})
test('whole-weight tiers and decimal boundaries; crew remains 3 sen',()=>{for(const [k,r] of [[0,.03],[24999.999,.03],[25000,.04],[27500,.04],[27500.01,.043],[29999.999,.043],[30000,.045],[34500,.045],[34500.01,.047],[39999.999,.047],[40000,.05]])assert.equal(earningsAmount(k,0).rate,r);assert.equal(earningsAmount(28000,0).amount,1204);assert.equal(earningsAmount(0,28000).amount,840)})
test('original collection period and members; every attendant gets full weight; company deduplicates',()=>{const db=fixture();try{const r=earningsReport(db,owner,'2026-09-15');assert.equal(r.companyKg,28000);assert.equal(r.items.find(e=>e.employeeId===1).amount,1204);for(const id of [2,3])assert.equal(r.items.find(e=>e.employeeId===id).amount,840);assert.equal(r.items.find(e=>e.employeeId===4).amount,0);assert.equal(earningsReport(db,owner,'2026-09-17').companyKg,0);const own=earningsReport(db,{employeeId:2,role:'crew'},'2026-09-15',{personal:true});assert.deepEqual(own.items.map(e=>e.employeeId),[2]);assert.equal(own.companyKg,undefined);assert.throws(()=>earningsReport(db,{employeeId:2,role:'crew'},'2026-09-15'),{code:'EARN_ACCESS'})}finally{db.close()}})
test('duplicate sales, duplicate unloading, wrong date and changed vehicle never produce guessed pay',()=>{for(const mutate of [db=>db.exec('INSERT INTO sales_settlements SELECT 2,vehicle_id,lines_json,revision FROM sales_settlements'),db=>db.exec("INSERT INTO unloading_weight_records VALUES(2,10,'2026-09-17',28000,'confirmed');INSERT INTO cargo_batch_unloads VALUES(2,1,'TN-1')"),db=>db.exec("UPDATE unloading_weight_records SET service_date='2026-09-18'"),db=>db.exec('UPDATE unloading_weight_records SET vehicle_id=20')]){const db=fixture();try{mutate(db);const r=earningsReport(db,owner,'2026-09-15');assert.equal(r.companyKg,0);assert.ok(r.items[0].pendingCount);assert.equal(r.items[0].amount,0);assert.throws(()=>recordEarningsPayment(db,owner,{periodStart:r.period.start,employeeId:1,revision:r.items.find(e=>e.employeeId===1).revision}),{code:'EARN_PENDING'})}finally{db.close()}}})
test('effective rate versions, stale writes, paid immutable snapshot and source changes',()=>{const db=fixture();try{const rules=structuredClone(defaultEarningsRules);rules.crewRate=.04;saveEarningsSettings(db,owner,{effectiveStart:'2026-09-16',rules,revision:0});assert.equal(earningsReport(db,owner,'2026-09-15').rules.crewRate,.03);assert.equal(earningsReport(db,owner,'2026-09-16').rules.crewRate,.04);assert.throws(()=>saveEarningsSettings(db,owner,{effectiveStart:'2026-09-16',rules,revision:0}),{code:'EARN_STALE'});let r=earningsReport(db,owner,'2026-09-15'),e=r.items.find(x=>x.employeeId===1);assert.throws(()=>recordEarningsPayment(db,owner,{periodStart:r.period.start,employeeId:1,revision:'old'}),{code:'EARN_STALE'});recordEarningsPayment(db,owner,{periodStart:r.period.start,employeeId:1,revision:e.revision});recordEarningsPayment(db,owner,{periodStart:r.period.start,employeeId:1,revision:e.revision});assert.equal(db.prepare('SELECT COUNT(*) n FROM earnings_payments').get().n,1);db.prepare('UPDATE sales_settlements SET lines_json=?,revision=2').run(JSON.stringify([{slipNumber:'TN-1',deliveryDate:'2026-09-17',weightKg:40000}]));e=earningsReport(db,owner,'2026-09-15').items.find(x=>x.employeeId===1);assert.equal(e.amount,1204);assert.equal(e.changed,true);assert.throws(()=>db.exec("UPDATE earnings_payments SET snapshot_json='{}'"));assert.throws(()=>saveEarningsSettings(db,{...owner,today:'2026-09-01'},{effectiveStart:'2026-09-01',rules,revision:1}),{code:'EARN_LOCKED'})}finally{db.close()}})
test('migration is idempotent; invalid rates and unpaid incomplete periods rejected',()=>{const db=fixture();try{applyV72Migration(db);applyV72Migration(db);assert.equal(db.prepare('SELECT MAX(version) v FROM schema_meta').get().v,72);assert.throws(()=>saveEarningsSettings(db,owner,{effectiveStart:'2026-09-16',revision:0,rules:{driver:[{from:0,rate:.03},{from:0,rate:.04}],crewRate:.03}}),{code:'EARN_RULE'});assert.throws(()=>recordEarningsPayment(db,{...owner,today:'2026-09-15'},{periodStart:'2026-09-01',employeeId:1}),{code:'EARN_OPEN'})}finally{db.close()}})
test('unlinked legacy tickets prevent payment and excess precision cannot change rules',()=>{const db=fixture();try{db.exec("INSERT INTO unloading_weight_records VALUES(2,10,'2026-09-14',100,'confirmed')");const r=earningsReport(db,owner,'2026-09-15'),e=r.items.find(x=>x.employeeId===1);assert.equal(r.unlinkedCount,1);assert.throws(()=>recordEarningsPayment(db,owner,{periodStart:r.period.start,employeeId:1,revision:e.revision}),{code:'EARN_PENDING'});assert.throws(()=>saveEarningsSettings(db,owner,{effectiveStart:'2026-09-16',revision:0,rules:{driver:[{from:0,rate:.0300001}],crewRate:.03}}),{code:'EARN_RULE'});assert.equal(db.prepare('SELECT COUNT(*) n FROM earnings_rules').get().n,0)}finally{db.close()}})
