import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {assertEmployeePayloadId,createEmployee,endEmployeeEmployment,getNextEmployeeCode,listResources,rehireEmployee,updateEmployee} from '../server/resourceService.mjs'
import {accountCan,createAccount} from '../server/authService.mjs'
import {employeeDetail,revealEmployeeField} from '../server/employeeSensitiveService.mjs'
import {commitMasterImport,masterExport,previewMasterImport} from '../server/masterTransferService.mjs'

function database(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);return db}

test('Employee Code自动递增且Employee改名保留旧值、新值、原因与固定ID',()=>{const db=database(),first=createEmployee({name:'Old Name',jobRole:'Driver',changedBy:'Admin'},db),second=createEmployee({name:'Second',jobRole:'Office',changedBy:'Admin'},db);assert.equal(first.employeeCode,'EMP-0001');assert.equal(second.employeeCode,'EMP-0002');assert.equal(getNextEmployeeCode(db).employeeCode,'EMP-0003');db.prepare("INSERT INTO vehicles(vehicle_code) VALUES('V1')").run();db.prepare("INSERT INTO dispatches(dispatch_date,vehicle_id,driver_id) VALUES('2026-07-22',1,?)").run(first.id);const updated=updateEmployee(first.id,{name:'New Name',reason:'Legal name correction',changedBy:'Admin'},db),history=db.prepare("SELECT * FROM employee_change_history WHERE employee_id=? AND field_name='name' ORDER BY id DESC").get(first.id);assert.equal(updated.id,first.id);assert.equal(db.prepare('SELECT driver_id FROM dispatches').get().driver_id,first.id);assert.equal(history.old_value,'Old Name');assert.equal(history.new_value,'New Name');assert.equal(history.reason,'Legal name correction');assert.equal(history.changed_by,'Admin')})

test('Job Role与Employment Type分开且System Role不会随岗位自动改变',()=>{const db=database(),employee=createEmployee({name:'Contract Driver',jobRole:'Driver',employmentType:'Contractor'},db),account=createAccount({employeeId:employee.id,username:'contractdriver',password:'Password123!',role:'driver'},{username:'Admin'}, {},db);updateEmployee(employee.id,{jobRole:'Attendant / Crew',reason:'Temporary reassignment',changedBy:'Supervisor'},db);assert.equal(db.prepare('SELECT employment_type FROM employees WHERE id=?').get(employee.id).employment_type,'Contractor');assert.equal(db.prepare('SELECT role FROM auth_accounts WHERE id=?').get(account.id).role,'driver')})

test('IC、EPF、SOCSO仅在有值时检查唯一，普通资料默认遮罩',()=>{const db=database(),one=createEmployee({name:'One',jobRole:'Driver',nationalIdNumber:'900101-13-1234',bankAccountNumber:'1234567890'},db);createEmployee({name:'No Statutory Numbers',jobRole:'Office',employmentType:'Part-time',epfNumber:'',socsoNumber:''},db);createEmployee({name:'Also Blank',jobRole:'Other',employmentType:'Temporary'},db);assert.throws(()=>createEmployee({name:'Duplicate',jobRole:'Driver',nationalIdNumber:'900101-13-1234'},db),/IC Number already belongs/);const listed=listResources(db).employees.find(item=>item.id===one.id);assert.equal(listed.nationalIdNumber,undefined);assert.equal(listed.nationalIdMasked,'900101-13-****');assert.match(listed.bankAccountMasked,/7890$/)})

test('敏感资料查看需要原因并写入审计',()=>{const db=database(),employee=createEmployee({name:'Sensitive',jobRole:'Office',epfNumber:'EPF123456'},db),session={id:null,username:'admin'};assert.throws(()=>revealEmployeeField(employee.id,'epfNumber','',session,{},db),/必须填写原因/);assert.equal(revealEmployeeField(employee.id,'epfNumber','Payroll verification',session,{},db).value,'EPF123456');assert.equal(db.prepare("SELECT COUNT(*) count FROM employee_sensitive_access_logs WHERE action='view'").get().count,1)})

test('离职结束当前Period并停用账号，重新入职沿用Employee ID并新增Period',()=>{const db=database(),employee=createEmployee({name:'Returning Worker',jobRole:'Driver',employmentType:'Permanent',employmentStartDate:'2024-01-10'},db);createAccount({employeeId:employee.id,username:'returning',password:'Password123!',role:'driver'},{username:'Admin'}, {},db);updateEmployee(employee.id,{employmentStatus:'resigned',employmentEndDate:'2024-08-31',lastWorkingDay:'2024-08-30',resignationTerminationReason:'Personal',reason:'Resignation accepted',changedBy:'HR'},db);assert.equal(db.prepare('SELECT is_active FROM auth_accounts WHERE employee_id=?').get(employee.id).is_active,0);assert.ok(!listResources(db).employees.find(item=>item.id===employee.id).isActive);const rehired=rehireEmployee(employee.id,{employmentStartDate:'2025-02-15',jobRole:'Driver',employmentType:'Contractor',reason:'Returning worker approved',changedBy:'Admin'},db);assert.equal(rehired.id,employee.id);assert.equal(rehired.employmentPeriods.length,2);assert.equal(rehired.employmentPeriods[0].endDate,'2024-08-31');assert.equal(rehired.employmentPeriods[1].rehireFlag,1)})

test('Employee导入先预览且幂等，普通导出不包含完整敏感号码',()=>{const db=database(),rows=[{'Employee Code':'EMP-0100','Employee Name':'Imported Driver','Primary Job Role':'Driver','Employment Type':'Contractor','Employment Status':'active','IC Number':'880101-13-9999','EPF Number':'','SOCSO Number':''}],preview=previewMasterImport({module:'employee',fileName:'employee.xlsx',rows},db);assert.equal(preview.summary.new,1);commitMasterImport(preview.batchId,{changedBy:'Admin'},db);const repeat=previewMasterImport({module:'employee',fileName:'employee.xlsx',rows},db);assert.equal(repeat.summary.unchanged,1);const exported=masterExport('employee',{},db).rows[0];assert.equal(exported['IC Number'],'880101-13-****');assert.notEqual(exported['IC Number'],'880101-13-9999')})

test('敏感权限与System Role分开授权',()=>{const db=database(),employee=createEmployee({name:'HR Supervisor',jobRole:'Supervisor'},db),account=createAccount({employeeId:employee.id,username:'hrsup',password:'Password123!',role:'supervisor'},{username:'Admin'}, {},db);assert.equal(accountCan(account,'employee_identity_sensitive',db),false);db.prepare("INSERT INTO auth_account_permissions(account_id,permission,granted_by) VALUES(?,'employee_identity_sensitive','Admin')").run(account.id);assert.equal(accountCan(account,'employee_identity_sensitive',db),true);assert.equal(employeeDetail(employee.id,{canViewSensitive:false},db).documents.length,0)})

test('Default Base仅接受Company Yard或Employee Base且Usual Areas只是多选建议',()=>{const db=database();db.prepare("INSERT INTO operational_locations(name,location_type,operational_type) VALUES('Yard','depot','Company Yard'),('Workshop','other','Workshop')").run();db.prepare("INSERT INTO areas(jodoo_area_id,name) VALUES('A1','Area One'),('A2','Area Two')").run();assert.throws(()=>createEmployee({name:'Wrong Base',jobRole:'Driver',defaultBaseLocationId:2},db),/Company Yard or Employee Base/);const employee=createEmployee({name:'Flexible Driver',jobRole:'Driver',defaultBaseLocationId:1,usualAreaIds:[1,2]},db);assert.deepEqual(employee.usualAreaIds,[1,2])})

test('Employee ID不匹配时拒绝保存并且不会更新任何员工',()=>{const db=database(),first=createEmployee({name:'Employee A'},db),second=createEmployee({name:'Employee B'},db);assert.throws(()=>assertEmployeePayloadId(second.id,{employeeId:first.id}),/Employee ID mismatch/);assert.equal(db.prepare('SELECT name FROM employees WHERE id=?').get(second.id).name,'Employee B')})

test('切换后保存只更新当前Employee且IC EPF SOCSO留空仍可保存',()=>{const db=database(),first=createEmployee({name:'Employee A',jobRole:'Driver',epfNumber:'',socsoNumber:''},db),second=createEmployee({name:'Employee B',jobRole:'Office',nationalIdNumber:''},db);assertEmployeePayloadId(second.id,{employeeId:second.id});updateEmployee(second.id,{employeeId:second.id,name:'Employee B Updated',nationalIdNumber:'',epfNumber:'',socsoNumber:'',reason:'Correct current employee',changedBy:'Admin'},db);assert.equal(db.prepare('SELECT name FROM employees WHERE id=?').get(first.id).name,'Employee A');assert.equal(db.prepare('SELECT name FROM employees WHERE id=?').get(second.id).name,'Employee B Updated')})

test('办理离职关闭Period 1且重新入职建立Period 2而不覆盖旧Period',()=>{const db=database(),employee=createEmployee({name:'Period Worker',jobRole:'Driver',employmentStartDate:'2024-01-10'},db);endEmployeeEmployment(employee.id,{employmentStatus:'contract_end',lastWorkingDay:'2024-12-30',employmentEndDate:'2024-12-31',resignationTerminationReason:'Contract completed',changedBy:'Admin'},db);const closed={...db.prepare('SELECT * FROM employee_employment_history WHERE employee_id=?').get(employee.id)};rehireEmployee(employee.id,{employmentStartDate:'2025-02-01',jobRole:'Attendant / Crew',employmentType:'Contractor',additionalRoles:['Driver'],reason:'Return approved',changedBy:'Admin'},db);const periods=db.prepare('SELECT * FROM employee_employment_history WHERE employee_id=? ORDER BY id').all(employee.id);assert.equal(periods.length,2);assert.deepEqual({...periods[0]},closed);assert.equal(periods[1].start_date,'2025-02-01');assert.equal(periods[1].rehire_flag,1)})
