import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {previewAccount,previewEmployees,previewReadUrl} from '../server/employeePreviewService.mjs'
import {driverToday,generateWeek,saveDraftAdjustments,approveDay} from '../server/dispatchService.mjs'
import {employeeNotices,publishNotice} from '../server/noticeBoardService.mjs'
import {driverGuideStatus} from '../server/driverGuideService.mjs'
const actor={employeeId:1,role:'supervisor'}
function fixture(t){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.exec("INSERT INTO employees(id,employee_code,name,job_role,employment_status,is_active) VALUES(1,'S1','Supervisor','Supervisor','active',1),(2,'D1','Driver One','Driver','active',1),(3,'D2','Driver Two','Driver','active',1),(4,'C1','Crew One','Crew','active',1),(5,'D3','Former','Driver','inactive',0)");for(const [id,role]of [[1,'supervisor'],[2,'driver'],[3,'driver'],[4,'crew'],[5,'driver']])db.prepare('INSERT INTO auth_accounts(id,employee_id,username,password_hash,role,system_role,preferred_language,must_change_password) VALUES(?,?,?,?,?,?,?,0)').run(id,id,'user'+id,'unused',role,role,id===2?'ms':'zh');t.after(()=>db.close());return db}
test('preview is management-only, uses real account role/language and excludes inactive accounts',t=>{const db=fixture(t);assert.deepEqual(previewEmployees(actor,db).map(e=>e.employeeId).sort(),[2,3,4]);const a=previewAccount(2,actor,db);assert.equal(a.role,'driver');assert.equal(a.preferredLanguage,'ms');assert.equal(a.employeeName,'Driver One');assert(!('password_hash'in a));for(const role of ['driver','crew','office'])assert.throws(()=>previewAccount(2,{...actor,role},db),{code:'PREVIEW_ACCESS'});assert.throws(()=>previewAccount(5,actor,db),{code:'PREVIEW_EMPLOYEE'});db.exec('UPDATE auth_accounts SET is_active=0 WHERE id=2');assert.throws(()=>previewAccount(2,actor,db),{code:'PREVIEW_EMPLOYEE'})})
test('preview rejects all mutations, nonallowlisted GET routes and path escapes',()=>{for(const method of ['POST','PATCH','PUT','DELETE'])assert.throws(()=>previewReadUrl(method,'/api/mobile/today'),{code:'PREVIEW_READ_ONLY'});for(const path of ['/api/mobile/guide/read','/api/mobile/trips/1/start','/api/auth/logout','/api/auth/accounts','/api/notices','/api/company-menu','//evil.example/api/mobile/today','/api/mobile/../../auth/accounts'])assert.throws(()=>previewReadUrl('GET',path),{code:'PREVIEW_READ_ONLY'});assert.equal(previewReadUrl('GET','/api/mobile/customer-pickup-search?search=Leader').searchParams.get('search'),'Leader')})
test('same mobile route data and action gates, employee isolation; reading changes no dispatch or receipts',t=>{const db=fixture(t),date='2026-09-14';db.exec("INSERT INTO areas(id,jodoo_area_id,name) VALUES(1,'A1','Area');INSERT INTO customers(id,jodoo_customer_id,name) VALUES(1,'C1','Leader');INSERT INTO branches(id,jodoo_branch_id,customer_id,area_id,branch_name) VALUES(1,'B1',1,1,'Leader Depot');INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S1',1,'B1','Weekly','Monday');INSERT INTO vehicles(id,vehicle_code,status,operational_status) VALUES(1,'V1','available','active')");generateWeek({startDate:date},db);const stop=db.prepare('SELECT id FROM dispatch_stops WHERE service_date=?').get(date);saveDraftAdjustments({adjustments:[{stopId:stop.id,vehicleId:1,tripNumber:1}],reason:'Assign',changedBy:'Supervisor'},db);db.exec('UPDATE dispatches SET driver_id=2 WHERE vehicle_id=1');approveDay(date,{approvedBy:'Supervisor',reason:'Ready'},db);publishNotice({title:'Private Driver One',body:'Bring documents',audience:'selected',employeeIds:[2],priority:'normal',requestKey:'preview-notice-test-123'},actor,db);const target=previewAccount(2,actor,db),before=db.prepare('SELECT total_changes() n').get().n;db.exec('PRAGMA query_only=ON');assert.deepEqual(driverToday({...target,today:date},db),driverToday({employeeId:2,role:'driver',today:date},db));assert.equal(driverToday({...previewAccount(3,actor,db),today:date},db).totalStops,0);assert.equal(employeeNotices(target,db)[0].readAt,null);assert.equal(employeeNotices(previewAccount(3,actor,db),db).length,0);assert.equal(driverGuideStatus({...target,now:date},db).readAt,null);assert.equal(db.prepare('SELECT total_changes() n').get().n,before)})

test('finish-work preview allows only the scoped read and never a submission',()=>{
 const path='/api/mobile/trips/123/work-close'
 assert.equal(previewReadUrl('GET',path).pathname,path)
 for(const method of ['POST','PATCH','DELETE'])assert.throws(()=>previewReadUrl(method,path),{code:'PREVIEW_READ_ONLY'})
 assert.throws(()=>previewReadUrl('GET','/api/dispatch/work-close'),{code:'PREVIEW_READ_ONLY'})
})
