import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV26Migration} from '../server/migrationV26.mjs'
import {configureScheduleRecurrence} from '../server/scheduleRecurrenceService.mjs'
import {generateDay,createScheduleException} from '../server/dispatchService.mjs'
import {isSundayCustomerAllowed,monthlyWeekdayDate,nextCollectionDate,scheduleMatchesDate,validateRecurrenceConfig} from '../shared/scheduleRecurrence.js'

const interval=(weeks,anchor,weekday='Monday')=>({frequency:`Every ${weeks} Weeks`,recurrence_type:'interval_weeks',interval_weeks:weeks,anchor_date:anchor,effective_date:anchor,fixed_weekday:weekday,days_of_week:weekday})

test('14-day recurrence stays anchored across months',()=>{const s=interval(2,'2026-01-26');assert.equal(scheduleMatchesDate(s,'2026-02-09'),true);assert.equal(scheduleMatchesDate(s,'2026-02-16'),false);assert.equal(nextCollectionDate(s,'2026-02-01'),'2026-02-09')})
test('21-day recurrence crosses year without becoming weekly',()=>{const s=interval(3,'2026-12-14');assert.equal(scheduleMatchesDate(s,'2027-01-04'),true);assert.equal(scheduleMatchesDate(s,'2026-12-21'),false)})
test('interval requires a matching anchor weekday',()=>{assert.throws(()=>validateRecurrenceConfig(interval(2,'2026-01-27')),/Anchor Date/);assert.equal(scheduleMatchesDate({...interval(2,null),anchor_date:null},'2026-02-02'),false)})
test('monthly first through fourth and last weekday are deterministic',()=>{assert.equal(monthlyWeekdayDate(2026,1,'Monday',1),'2026-02-02');assert.equal(monthlyWeekdayDate(2026,1,'Monday',2),'2026-02-09');assert.equal(monthlyWeekdayDate(2026,1,'Monday',3),'2026-02-16');assert.equal(monthlyWeekdayDate(2026,1,'Monday',4),'2026-02-23');assert.equal(monthlyWeekdayDate(2026,1,'Saturday','Last'),'2026-02-28')})
test('monthly handles leap year and rejects fifth occurrence',()=>{assert.equal(monthlyWeekdayDate(2028,1,'Tuesday','Last'),'2028-02-29');assert.throws(()=>monthlyWeekdayDate(2026,1,'Monday',5),/Monthly occurrence/)})
test('effective date can defer an anchored cycle',()=>{const s={...interval(2,'2026-01-05'),effective_date:'2026-01-20'};assert.equal(scheduleMatchesDate(s,'2026-01-19'),false);assert.equal(scheduleMatchesDate(s,'2026-02-02'),true)})
test('On Call and Paused never generate fixed occurrences',()=>{for(const frequency of ['On Call','Paused'])assert.equal(scheduleMatchesDate({frequency,days_of_week:'Monday'},'2026-01-05'),false)})
test('legacy weekly and daily frequencies remain compatible',()=>{assert.equal(scheduleMatchesDate({frequency:'Weekly',days_of_week:'Monday'},'2026-01-05'),true);assert.equal(scheduleMatchesDate({frequency:'Daily',days_of_week:'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday'},'2026-01-06'),true)})
test('Sunday whitelist is exact and does not admit ordinary customers',()=>{assert.equal(isSundayCustomerAllowed({customerName:'Everrise'}),true);assert.equal(isSundayCustomerAllowed({customerName:'Farley',branchName:'Farley Mall'}),true);assert.equal(isSundayCustomerAllowed({customerName:'Ordinary Shop'}),false)})

function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.exec("INSERT INTO customers(jodoo_customer_id,name) VALUES('C1','Customer'); INSERT INTO branches(jodoo_branch_id,customer_id,branch_name,status,is_active,assigned_weekdays) VALUES('B1',1,'Branch','active',1,'[\"Monday\"]'); INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week,is_active) VALUES('S1',1,'B1','Weekly','Monday',1)");return db}

test('v25 to v26 migration is additive and second run is a no-op',()=>{const db=fixture();db.exec('DELETE FROM schema_meta; INSERT INTO schema_meta(version) VALUES(25)');const before=db.prepare('SELECT COUNT(*) n FROM branch_schedules').get().n,first=applyV26Migration(db),second=applyV26Migration(db);assert.equal(first.schemaVersion,26);assert.equal(second.schemaVersion,26);assert.equal(db.prepare('SELECT COUNT(*) n FROM branch_schedules').get().n,before);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})
test('recurrence configuration preserves existing weekday and writes audit',()=>{const db=fixture();const after=configureScheduleRecurrence(1,{frequency:'Every 2 Weeks',recurrenceType:'interval_weeks',intervalWeeks:2,anchorDate:'2026-08-03',effectiveDate:'2026-08-03',fixedWeekday:'Monday',reason:'Approved cycle',changedBy:'Supervisor'},db);assert.equal(after.days_of_week,'Monday');assert.equal(after.next_collection_date,'2026-08-03');assert.equal(db.prepare("SELECT COUNT(*) n FROM master_change_history WHERE change_type='recurrence_configured'").get().n,1);assert.throws(()=>configureScheduleRecurrence(1,{...after,frequency:'Every 2 Weeks',recurrenceType:'interval_weeks',intervalWeeks:2,anchorDate:'2026-08-04',fixedWeekday:'Tuesday',reason:'Change'},db),/Existing Weekday/)})
test('ordinary customer cannot receive a new Sunday recurrence',()=>{const db=fixture();db.prepare("UPDATE branch_schedules SET days_of_week=NULL WHERE id=1").run();assert.throws(()=>configureScheduleRecurrence(1,{frequency:'Monthly',recurrenceType:'monthly',anchorDate:'2026-08-02',effectiveDate:'2026-08-02',monthlyOccurrence:1,fixedWeekday:'Sunday',reason:'Test'},db),/Sunday/)})
test('generator creates interval stops once and database relation changes are durable',()=>{const db=fixture();configureScheduleRecurrence(1,{frequency:'Every 2 Weeks',recurrenceType:'interval_weeks',intervalWeeks:2,anchorDate:'2026-08-03',effectiveDate:'2026-08-03',fixedWeekday:'Monday',reason:'Approved'},db);generateDay({startDate:'2026-08-03'},db);generateDay({startDate:'2026-08-03'},db);generateDay({startDate:'2026-08-10'},db);generateDay({startDate:'2026-08-17'},db);assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_stops').get().n,2);assert.equal(db.prepare('SELECT COUNT(*) n FROM schedule_occurrences').get().n,2)})
test('schedule exception moves one occurrence without changing anchor',()=>{const db=fixture();configureScheduleRecurrence(1,{frequency:'Every 2 Weeks',recurrenceType:'interval_weeks',intervalWeeks:2,anchorDate:'2026-08-03',effectiveDate:'2026-08-03',fixedWeekday:'Monday',reason:'Approved'},db);createScheduleException({scheduleId:'S1',type:'move_date',originalDate:'2026-08-03',targetDate:'2026-08-04',createdBy:'Supervisor'},db);generateDay({startDate:'2026-08-03'},db);generateDay({startDate:'2026-08-04'},db);assert.equal(db.prepare('SELECT anchor_date value FROM branch_schedules WHERE id=1').get().value,'2026-08-03');assert.equal(db.prepare("SELECT COUNT(*) n FROM dispatch_stops WHERE status<>'cancelled'").get().n,1);assert.equal(db.prepare("SELECT status FROM schedule_occurrences WHERE planned_date='2026-08-03'").get().status,'cancelled')})
test('occurrence audit failure rolls back stop generation transaction',()=>{const db=fixture();configureScheduleRecurrence(1,{frequency:'Every 2 Weeks',recurrenceType:'interval_weeks',intervalWeeks:2,anchorDate:'2026-08-03',effectiveDate:'2026-08-03',fixedWeekday:'Monday',reason:'Approved'},db);db.exec("CREATE TRIGGER fail_occurrence BEFORE INSERT ON schedule_occurrences BEGIN SELECT RAISE(ABORT,'occurrence audit failure'); END");assert.throws(()=>generateDay({startDate:'2026-08-03'},db),/occurrence audit failure/);assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_stops').get().n,0);assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_days').get().n,0)})
