import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {areaParentDiagnostics,bulkAcceptHighConfidence,calculateRecommendation,decideRecommendation,listRecommendations,recalculateRecommendations,resetSelectedRecommendations,saveZoneBoundary} from '../server/gpsRecommendationService.mjs'

function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.prepare("INSERT INTO areas(jodoo_area_id,name,zone_group_id,confirmed_zone_group_id,zone_assignment_status) VALUES('BAU','Bau',1,1,'confirmed'),('MAT','Jalan Datuk Salau',2,2,'confirmed')").run();db.prepare("INSERT INTO customers(jodoo_customer_id,name) VALUES('C1','Anonymous Target'),('C2','Nearby Reference'),('C3','Far Centroid')").run();db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,area_id,branch_name,address,latitude,longitude) VALUES('FIX-1',1,1,'Anonymous Bau Shop','Bau 94000',1,1),('FIX-2',2,1,'Reference','Bau road',1.0003,1.0003),('FIX-3',3,2,'Far','Matang',5,5)").run();db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S1',1,'FIX-1','Weekly','Monday')").run();return db}

test('no-polygon BAU fixture keeps current Area despite a competing centroid',()=>{const db=fixture(),item=calculateRecommendation(1,db);assert.equal(item.recommendedAreaId,1);assert.equal(item.recommendedZoneGroupId,1);assert.equal(item.confidence,'low');assert.equal(item.reason.currentAssignmentStable,true);assert.ok(item.reason.addressEvidence.matchedTokens.includes('bau'));assert.ok(item.reason.nearestCustomer.distanceMeters<100)})
test('recommended Zone always comes from recommended Area current parent',()=>{const db=fixture();db.prepare('UPDATE areas SET confirmed_zone_group_id=2 WHERE id=1').run();const item=calculateRecommendation(1,db);assert.equal(item.recommendedZoneGroupId,2);assert.equal(areaParentDiagnostics(db).readOnly,true)})
test('Pending GPS is preview metadata and cannot apply Area',()=>{const db=fixture();db.prepare('UPDATE branches SET latitude=NULL,longitude=NULL WHERE id=1').run();db.prepare("INSERT INTO temporary_locations(branch_id,latitude,longitude,location_source) VALUES(1,1,1,'collector')").run();recalculateRecommendations({branchIds:[1]},db);const item=listRecommendations({changesOnly:false},db).items.find(row=>row.internalBranchId===1);assert.equal(item.reason.gpsSource,'pending');assert.throws(()=>decideRecommendation(item.id,{action:'accept',reason:'review',confirmedBy:'server actor'},db),/Pending GPS/)})
test('manual reason, audit before/after and recalculation decision preservation',()=>{const db=fixture();saveZoneBoundary(1,{polygon:[[0,0],[0,2],[2,2],[2,0]],effectiveDate:'2026-01-01',changedBy:'fixture'},db);const item=listRecommendations({changesOnly:false},db).items.find(row=>row.internalBranchId===1);assert.throws(()=>decideRecommendation(item.id,{action:'keep_original',confirmedBy:'actor'},db),/reason/);decideRecommendation(item.id,{action:'keep_original',reason:'nearby and address agree',confirmedBy:'session actor'},db);recalculateRecommendations({branchIds:[1],changedBy:'session actor'},db);assert.equal(db.prepare('SELECT status FROM gps_zone_recommendations WHERE id=?').get(item.id).status,'kept_original');const audit=JSON.parse(db.prepare("SELECT after_json value FROM audit_logs WHERE action='gps_zone_recommendation_decided'").get().value);assert.equal(audit.confirmedBy,'session actor');assert.equal(audit.reason,'nearby and address agree');assert.equal(audit.algorithmVersion,'gps-area-v2.0.0');assert.ok(db.prepare("SELECT before_json FROM audit_logs WHERE action='gps_zone_recommendation_decided'").get().before_json)})
test('low/conflict cannot bulk and operational records are preserved',()=>{const db=fixture();recalculateRecommendations({},db);const before={branches:db.prepare('SELECT COUNT(*) n FROM branches').get().n,schedules:db.prepare('SELECT COUNT(*) n FROM branch_schedules').get().n,gps:db.prepare('SELECT latitude,longitude FROM branches WHERE id=1').get()};assert.equal(bulkAcceptHighConfidence({reason:'bulk review',confirmedBy:'session actor'},db).acceptedCount,0);assert.deepEqual({branches:db.prepare('SELECT COUNT(*) n FROM branches').get().n,schedules:db.prepare('SELECT COUNT(*) n FROM branch_schedules').get().n,gps:db.prepare('SELECT latitude,longitude FROM branches WHERE id=1').get()},before)})
test('select-other rejects a malicious Zone and derives the effective parent from Area',()=>{const db=fixture();recalculateRecommendations({},db);const item=listRecommendations({changesOnly:false},db).items.find(row=>row.internalBranchId===1);assert.throws(()=>decideRecommendation(item.id,{action:'select_other',areaId:2,zoneGroupId:1,reason:'malicious mismatch',confirmedBy:'session actor'},db),/must not be submitted/);const decided=decideRecommendation(item.id,{action:'select_other',areaId:2,reason:'manual Area review',confirmedBy:'session actor'},db);assert.equal(decided.recommendedZoneGroupId,1);const audit=JSON.parse(db.prepare("SELECT after_json value FROM audit_logs WHERE action='gps_zone_recommendation_decided'").get().value);assert.equal(audit.zoneGroupId,2)})
test('explicit reset changes only selected decisions and audits reason plus Session actor',()=>{const db=fixture();recalculateRecommendations({},db);const items=listRecommendations({changesOnly:false},db).items;decideRecommendation(items[0].id,{action:'keep_original',reason:'first review',confirmedBy:'session actor'},db);decideRecommendation(items[1].id,{action:'keep_original',reason:'second review',confirmedBy:'session actor'},db);assert.throws(()=>resetSelectedRecommendations({recommendationIds:[items[0].id],changedBy:'session actor'},db),/reason/);resetSelectedRecommendations({recommendationIds:[items[0].id],reason:'new evidence',changedBy:'session actor'},db);assert.equal(db.prepare('SELECT status FROM gps_zone_recommendations WHERE id=?').get(items[0].id).status,'pending');assert.equal(db.prepare('SELECT status FROM gps_zone_recommendations WHERE id=?').get(items[1].id).status,'kept_original');const audit=JSON.parse(db.prepare("SELECT after_json value FROM audit_logs WHERE action='gps_zone_recommendation_reset'").get().value);assert.equal(audit.actor,'session actor');assert.equal(audit.reason,'new evidence')})
test('API and UI contracts use Session actor, isolated reasons and Area-only selection',async()=>{const fs=await import('node:fs'),server=fs.readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../src/GpsZoneRecommendationPage.jsx',import.meta.url),'utf8');assert.match(server,/reset-selected'[\s\S]*accountCan\(session,'gps_review'\)/);assert.match(server,/changedBy:session\.employeeName/);assert.match(server,/confirmedBy:session\.employeeName/);const recommendationUi=ui.slice(ui.indexOf('function RecommendationManager'));assert.doesNotMatch(ui,/changedBy|confirmedBy/);assert.doesNotMatch(recommendationUi,/zoneGroupId/);assert.match(ui,/setManualReason\(''\)/);assert.match(ui,/\[bulkReason,setBulkReason\]/);assert.match(ui,/\[resetReason,setResetReason\]/);assert.match(ui,/recommendationIds:resetIds/);assert.doesNotMatch(ui,/>Accept recommendation<|>Bulk confirm High<|>Select another Zone/);for(const language of ['en','ms','zh'])assert.match(fs.readFileSync(new URL('../src/translations.js',import.meta.url),'utf8'),new RegExp(`Object\\.assign\\(messages\\.${language}`))})
test('recommendation workflows have an explicit protected-data mutation allowlist',async()=>{const fs=await import('node:fs'),source=fs.readFileSync(new URL('../server/gpsRecommendationService.mjs',import.meta.url),'utf8');assert.doesNotMatch(source,/DELETE\s+FROM/i);for(const table of ['dispatches','dispatch_stops','branch_schedules','temporary_locations','branch_product_price_assignments','gps_zone_decisions'])assert.doesNotMatch(source,new RegExp(`UPDATE\\s+${table}`,'i'));assert.match(source,/UPDATE branches SET area_id=/);assert.match(source,/UPDATE gps_zone_recommendations SET/)})
