import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
const mobile=readFileSync(new URL('../src/AuthPages.jsx',import.meta.url),'utf8'),master=readFileSync(new URL('../src/MasterDataPage.jsx',import.meta.url),'utf8'),zone=readFileSync(new URL('../src/ZoneGroupManager.jsx',import.meta.url),'utf8'),css=readFileSync(new URL('../src/App.css',import.meta.url),'utf8')
test('mobile GPS collection renders realtime progress and direct clickable Branch list',()=>{for(const token of ['gpsSummary.totalActiveBranches','gpsSummary.officialGps','gpsSummary.pendingApproval','gpsSummary.remainingToCollect','gps-to-collect','setSelected(branch)'])assert.ok(mobile.includes(token));assert.match(css,/\.gps-to-collect button\{cursor:pointer/);assert.match(css,/@media\(max-width:420px\).*\.gps-address-grid\{grid-template-columns:1fr\}/s)})
test('device GPS is read-only and reverse-geocoded fields remain explicit rather than guessed',()=>{assert.match(mobile,/gps-collection\/reverse-geocode/);assert.match(mobile,/Latitude<input value=\{capture\.latitude\} readOnly/);for(const field of ['address','state','city','street','streetNumber','postalCode','gpsRemark'])assert.match(mobile,new RegExp(`capture\\.${field}`));assert.ok(mobile.includes('reverseGeocodeProvider'));assert.match(mobile,/findingAddress/);assert.match(mobile,/catch\(item\)\{setError\(item\.message\)\}/)})
test('approval displays captured address components and remark',()=>{for(const field of ['item.address','item.state','item.city','item.street','item.streetNumber','item.postalCode','item.gpsRemark'])assert.match(master,new RegExp(field.replace('.','\\.')))} )
test('desktop direct-entry collector persists and visibly opens the preselected Branch',()=>{for(const token of ['initialBranchId','parseTypedId(initialBranch','selectCollectionBranch','setBranchInUrl','formatBranchId(branch.branchId)','formRef.current?.scrollIntoView','!branchId&&<div className="gps-to-collect desktop-gps-queue"','className="back-button"'])assert.ok(master.includes(token));assert.match(master,/window\.history\.replaceState/);assert.match(master,/branch\.hasPendingGps\|\|branch\.temporaryGpsStatus==='pending_supervisor'/)})
test('desktop direct-entry collector uses device GPS, explicit fields and authorized withdrawal',()=>{for(const token of ['initialBranch','getCurrentLocation','navigator.geolocation','gps-collection/reverse-geocode','selectedHasPending','gps.withdrawOfficial','/withdraw'])assert.ok(master.includes(token));assert.match(master,/Latitude.*readOnly/s);assert.match(master,/Longitude.*readOnly/s);assert.doesNotMatch(master,/onChange=\{event=>setGps\(\{\.\.\.gps,latitude:/)})
test('missing GPS rows are keyboard and touch navigable only when no Official or Pending GPS exists',()=>{assert.match(zone,/collectable=metric==='missing_gps'&&!item\.hasOfficialGps&&!item\.hasTemporaryGps/);assert.match(zone,/role=\{collectable\?'button'/);assert.match(zone,/event\.key==='Enter'\|\|event\.key===' '/);assert.match(zone,/branch=\$\{encodeURIComponent\(item\.branchId\)\}/)})
