import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV31Migration} from '../server/migrationV31.mjs'
import {captureBranchGps,gpsCollectionDashboard,listGpsCollector,withdrawBranchOfficialGps} from '../server/customerMasterService.mjs'
import {adoptTemporaryLocation,reviewTemporaryLocation} from '../server/specialRequestService.mjs'

function fresh(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);const customer=db.prepare("INSERT INTO customers(jodoo_customer_id,name,status,is_active) VALUES('C1','Customer','active',1)").run();db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,branch_name,address,status,is_active) VALUES('B1',?,'No GPS','Road 1','active',1)").run(customer.lastInsertRowid);db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,branch_name,latitude,longitude,status,is_active) VALUES('B2',?,'Official',1.5,110.3,'active',1)").run(customer.lastInsertRowid);return db}

test('v30 to v31 is additive, transactional and idempotent',()=>{const db=fresh();db.prepare('INSERT INTO schema_meta(version) VALUES(30)').run();for(const column of ['address','state','street','city','street_number','postal_code','reverse_geocode_provider'])db.exec(`ALTER TABLE temporary_locations DROP COLUMN ${column}`);for(const column of ['gps_address','gps_state','gps_street','gps_city','gps_street_number','gps_postal_code','gps_reverse_geocode_provider'])db.exec(`ALTER TABLE branches DROP COLUMN ${column}`);db.exec('DROP TABLE branch_gps_history');const before={branches:db.prepare('SELECT COUNT(*) n FROM branches').get().n,stops:db.prepare('SELECT COUNT(*) n FROM dispatch_stops').get().n},first=applyV31Migration(db),second=applyV31Migration(db);assert.equal(first.schemaVersion,31);assert.equal(second.noOp,true);assert.deepEqual({branches:db.prepare('SELECT COUNT(*) n FROM branches').get().n,stops:db.prepare('SELECT COUNT(*) n FROM dispatch_stops').get().n},before);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})

test('live GPS queue shows Pending only, then Reject hides history and returns Branch to collect',()=>{const db=fresh();assert.deepEqual(gpsCollectionDashboard({},db).summary,{totalActiveBranches:2,officialGps:1,pendingApproval:0,remainingToCollect:1});const gps=captureBranchGps('B1',{latitude:1.55,longitude:110.35,accuracyM:8,address:'Road 1',state:'Sarawak',street:'Road 1',city:'Kuching',streetNumber:'10',postalCode:'93000',gpsRemark:'Loading bay',reverseGeocodeProvider:'OpenStreetMap Nominatim',capturedBy:'Driver'},db);assert.equal(gps.verification_status,'pending_supervisor');assert.equal(gps.city,'Kuching');assert.equal(gps.remark,'Loading bay');assert.equal(listGpsCollector({},db).length,1);assert.equal(gpsCollectionDashboard({},db).summary.pendingApproval,1);assert.equal(gpsCollectionDashboard({},db).items.length,0);assert.throws(()=>captureBranchGps('B1',{latitude:1,longitude:110},db),/already pending/);reviewTemporaryLocation(gps.id,{decision:'reject',reason:'Wrong gate',reviewedBy:'Supervisor'},db);assert.equal(listGpsCollector({},db).length,0);assert.equal(db.prepare('SELECT COUNT(*) n FROM temporary_locations WHERE id=? AND verification_status=?').get(gps.id,'rejected').n,1);assert.equal(db.prepare("SELECT COUNT(*) n FROM audit_logs WHERE action='temporary_gps_reviewed'").get().n,1);assert.equal(gpsCollectionDashboard({},db).summary.remainingToCollect,1)})

test('Official GPS cannot be recaptured; approval preserves address metadata and withdrawal restores collection eligibility',()=>{const db=fresh();assert.throws(()=>captureBranchGps('B2',{latitude:1,longitude:110},db),/Official GPS already exists/);const gps=captureBranchGps('B1',{latitude:1.55,longitude:110.35,address:'Gate 2',state:'Sarawak',city:'Kuching',postalCode:'93000',gpsRemark:'Receiving entrance',capturedBy:'Driver'},db);adoptTemporaryLocation(gps.id,{adoptedBy:'Supervisor',reason:'Verified'},db);const branch=db.prepare("SELECT latitude,gps_address,gps_city,gps_postal_code,gps_remark FROM branches WHERE jodoo_branch_id='B1'").get();assert.equal(branch.gps_address,'Gate 2');assert.equal(branch.gps_city,'Kuching');assert.equal(branch.gps_remark,'Receiving entrance');assert.equal(gpsCollectionDashboard({},db).summary.officialGps,2);withdrawBranchOfficialGps('B1',{changedBy:'Supervisor',reason:'Site relocated'},db);assert.equal(gpsCollectionDashboard({},db).summary.remainingToCollect,1);assert.equal(db.prepare("SELECT COUNT(*) n FROM branch_gps_history WHERE branch_id=1").get().n,2);assert.equal(db.prepare("SELECT COUNT(*) n FROM master_change_history WHERE change_type='official_gps_withdrawn'").get().n,1)})

test('inactive Branch never enters collection queue',()=>{const db=fresh();db.prepare("UPDATE branches SET status='paused',is_active=0 WHERE jodoo_branch_id='B1'").run();assert.equal(gpsCollectionDashboard({},db).summary.totalActiveBranches,1);assert.equal(gpsCollectionDashboard({},db).summary.remainingToCollect,0)})

test('remaining queue returns existing Area and Zone business-order metadata without changing eligibility',()=>{const db=fresh();const zone=db.prepare("INSERT INTO zone_groups(code,name,sort_order) VALUES('GPS-TEST','GPS Test Zone',4)").run(),area=db.prepare("INSERT INTO areas(jodoo_area_id,name,zone_group_id,confirmed_zone_group_id,zone_assignment_status) VALUES('A-GPS','Batu Kawa',?,?,'confirmed')").run(zone.lastInsertRowid,zone.lastInsertRowid);db.prepare("UPDATE branches SET area_id=? WHERE jodoo_branch_id='B1'").run(area.lastInsertRowid);const result=gpsCollectionDashboard({},db);assert.deepEqual(result.summary,{totalActiveBranches:2,officialGps:1,pendingApproval:0,remainingToCollect:1});assert.equal(result.items.length,1);assert.equal(result.items[0].area,'Batu Kawa');assert.equal(result.items[0].areaId,Number(area.lastInsertRowid));assert.equal(result.items[0].zoneGroup,'GPS Test Zone');assert.equal(result.items[0].zoneSortOrder,4)})
