import test from 'node:test'
import assert from 'node:assert/strict'
import { DatabaseSync } from 'node:sqlite'
import { schemaSql } from '../server/schema.mjs'
import { calculateRecommendation, decideRecommendation, listRecommendations, pointInPolygon, recalculateRecommendations, saveZoneBoundary } from '../server/gpsRecommendationService.mjs'
import { generateDay, getDispatchDay } from '../server/dispatchService.mjs'

const square=(south,west,north,east)=>[{lat:south,lng:west},{lat:south,lng:east},{lat:north,lng:east},{lat:north,lng:west}]
function fixture({latitude=1,longitude=1}={}){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.prepare("INSERT INTO areas(jodoo_area_id,name,zone_group_id,confirmed_zone_group_id,zone_assignment_status) VALUES('A1','Area One',1,1,'confirmed'),('A2','Area Two',2,2,'confirmed')").run();db.prepare("INSERT INTO customers(jodoo_customer_id,name) VALUES('C1','Customer One'),('C2','Neighbour')").run();db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,area_id,branch_name,address,latitude,longitude) VALUES('B1',1,1,'Target','Address',?,?),('B2',2,2,'Neighbour Branch','Nearby',5,5)").run(latitude,longitude);db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S1',1,'B1','Weekly','Monday')").run();return db}
const save=(db,zoneId,polygon)=>saveZoneBoundary(zoneId,{polygon,effectiveDate:'2026-01-01',changedBy:'Test'},db)

test('official GPS 在单一 Zone polygon 内产生高置信度建议',()=>{const db=fixture();save(db,1,square(0,0,2,2));const item=listRecommendations({},db).items.find(row=>row.branchId==='B1');assert.equal(item.recommendedZone,'古晋 A区');assert.equal(item.matchType,'inside');assert.equal(item.confidence,'high');assert.equal(item.boundaryConflict,0)})
test('official GPS 在 Zone 边界时标记为需主管检查',()=>{const db=fixture({latitude:1,longitude:0});save(db,1,square(0,0,2,2));const item=calculateRecommendation(1,db);assert.equal(pointInPolygon({lat:1,lng:0},square(0,0,2,2)),'boundary');assert.equal(item.matchType,'boundary');assert.equal(item.confidence,'medium')})
test('official GPS 落在重叠 Zone 时标记 boundary conflict',()=>{const db=fixture();save(db,1,square(0,0,2,2));save(db,2,square(.5,.5,3,3));const item=calculateRecommendation(1,db);assert.equal(item.matchType,'overlap');assert.equal(item.boundaryConflict,1);assert.equal(item.recommendedZoneGroupId,null)})
test('official GPS 不在任何 Zone 时返回最近边界距离',()=>{const db=fixture({latitude:4,longitude:4});save(db,1,square(0,0,2,2));const item=calculateRecommendation(1,db);assert.equal(item.matchType,'outside');assert.equal(item.confidence,'low');assert.ok(item.nearestDistanceM>0)})
test('没有 official GPS 时不产生正式建议',()=>{const db=fixture({latitude:null,longitude:null});const item=calculateRecommendation(1,db);assert.equal(item.matchType,'no_gps');assert.equal(item.confidence,'none')})
test('只有 temporary GPS 时明确忽略临时位置',()=>{const db=fixture({latitude:null,longitude:null});db.prepare("INSERT INTO temporary_locations(branch_id,latitude,longitude,location_source) VALUES(1,1,1,'Driver Captured')").run();const item=calculateRecommendation(1,db);assert.equal(item.status,'no_gps');assert.equal(item.reason.temporaryGpsIgnored,true);assert.equal(item.recommendedZoneGroupId,null)})
test('Zone 边界新版本会重新计算建议但不修改 Branch Area',()=>{const db=fixture();save(db,1,square(0,0,2,2));assert.equal(listRecommendations({},db).items.find(row=>row.branchId==='B1').matchType,'inside');save(db,1,square(10,10,12,12));const item=listRecommendations({},db).items.find(row=>row.branchId==='B1');assert.equal(item.matchType,'outside');assert.equal(db.prepare('SELECT area_id areaId FROM branches WHERE id=1').get().areaId,1);assert.equal(db.prepare('SELECT COUNT(*) count FROM zone_boundaries WHERE zone_group_id=1').get().count,2)})
test('主管拒绝建议会保留原归属及决定记录',()=>{const db=fixture();save(db,2,square(0,0,2,2));const item=listRecommendations({},db).items.find(row=>row.branchId==='B1');decideRecommendation(item.id,{action:'keep_original',confirmedBy:'Supervisor'},db);assert.equal(db.prepare('SELECT area_id areaId FROM branches WHERE id=1').get().areaId,1);assert.equal(db.prepare('SELECT status FROM gps_zone_recommendations WHERE id=?').get(item.id).status,'kept_original');assert.equal(db.prepare('SELECT decision FROM gps_zone_decisions').get().decision,'keep_original')})
test('主管接受建议后旧 Dispatch 快照不变，新路线使用新归属',()=>{const db=fixture();generateDay({startDate:'2026-07-20'},db);assert.equal(getDispatchDay('2026-07-20',db).stops[0].zoneGroup,'古晋 A区');save(db,2,square(0,0,2,2));const item=listRecommendations({},db).items.find(row=>row.branchId==='B1');assert.equal(item.recommendedArea,'Area Two');decideRecommendation(item.id,{action:'accept',confirmedBy:'Supervisor'},db);assert.equal(getDispatchDay('2026-07-20',db).stops[0].zoneGroup,'古晋 A区');generateDay({startDate:'2026-07-27'},db);assert.equal(getDispatchDay('2026-07-27',db).stops[0].zoneGroup,'古晋 B区')})
test('批量重新计算不会使用 temporary GPS 覆盖 official GPS',()=>{const db=fixture();db.prepare("INSERT INTO temporary_locations(branch_id,latitude,longitude,location_source) VALUES(1,40,40,'Driver Captured')").run();save(db,1,square(0,0,2,2));recalculateRecommendations({changedBy:'Test'},db);const item=listRecommendations({},db).items.find(row=>row.branchId==='B1');assert.equal(item.latitude,1);assert.equal(item.recommendedZone,'古晋 A区')})
