import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV53Migration} from '../server/migrationV53.mjs'
import {approveRoute,assignRouteVehicle,generateDay,getDispatchDay,reorderRouteStop,routeApprovalCheck} from '../server/dispatchService.mjs'
import {installWeeklyRoutePlan} from '../server/weeklyRoutePlanService.mjs'

function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.prepare("INSERT INTO customers(jodoo_customer_id,name) VALUES('C','Customer')").run();db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,branch_name,status,collection_frequency,assigned_weekdays,latitude,longitude) VALUES('B1',1,'One','active','Weekly','[\"Monday\"]',1,1),('B2',1,'Two','active','Weekly','[\"Monday\"]',1,1),('B3',1,'Three','active','Weekly','[\"Monday\"]',1,1)").run();db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S1',1,'B1','Weekly','Monday'),('S2',2,'B2','Weekly','Monday'),('S3',3,'B3','Weekly','Monday')").run();db.prepare("INSERT INTO vehicles(vehicle_code,registration_number,status,operational_status) VALUES('Lorry 2','QAA4293N','available','active'),('Lorry 3','QAB1225B','available','active')").run();installWeeklyRoutePlan({name:'Routes',sourceName:'test',entries:[[1,'QAA4293N',1,1,'B1','',''],[1,'QAA4293N',1,2,'B2','',''],[1,'QAB1225B',1,1,'B3','','']]},{},db);generateDay({startDate:'2026-09-07'},db);return db}

test('each Route can be approved without another unassigned Route blocking it',()=>{const db=fixture();assignRouteVehicle('2026-09-07',1,{vehicleId:1},db);assert.equal(routeApprovalCheck('2026-09-07',1,db).ok,true);assert.equal(routeApprovalCheck('2026-09-07',2,db).ok,false);approveRoute('2026-09-07',1,{approvedBy:'Supervisor'},db);let day=getDispatchDay('2026-09-07',db);assert.equal(day.routeBoards[0].approvalStatus,'approved');assert.equal(day.routeBoards[1].approvalStatus,'pending');assert.equal(day.status,'reapproval_required');assignRouteVehicle('2026-09-07',2,{vehicleId:2},db);approveRoute('2026-09-07',2,{approvedBy:'Supervisor'},db);day=getDispatchDay('2026-09-07',db);assert.equal(day.routeBoards[0].approvalStatus,'approved');assert.equal(day.routeBoards[1].approvalStatus,'approved');assert.equal(day.status,'approved')})

test('editing one Route invalidates only that Route approval',()=>{const db=fixture();assignRouteVehicle('2026-09-07',1,{vehicleId:1},db);assignRouteVehicle('2026-09-07',2,{vehicleId:2},db);approveRoute('2026-09-07',1,{},db);let day=getDispatchDay('2026-09-07',db),second=day.routeBoards[0].stops[1];reorderRouteStop('2026-09-07',1,{stopId:second.id,direction:'up'},db);day=getDispatchDay('2026-09-07',db);assert.equal(day.routeBoards[0].approvalStatus,'reapproval_required');assert.equal(day.routeBoards[1].approvalStatus,'pending')})

test('v53 migration is additive and idempotent',()=>{const db=fixture();db.exec('DROP TABLE daily_route_approvals;DELETE FROM schema_meta;INSERT INTO schema_meta(version) VALUES(52)');const first=applyV53Migration(db),second=applyV53Migration(db);assert.equal(first.schemaVersion,53);assert.equal(second.noOp,true);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})
