import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV22Migration} from '../server/migrationV22.mjs'
import {applyV24Migration} from '../server/migrationV24.mjs'
import {applyV25Migration} from '../server/migrationV25.mjs'
import {createCategory,createProduct,createProductPriceGroup,deleteEntity,entityPreview,getCategory,getPriceGroup,getProduct,listCategories,moveProductsCategory,previewMoveProducts} from '../server/materialCatalogService.mjs'

function fixture(){const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;${schemaSql}`);db.prepare('INSERT OR IGNORE INTO schema_meta(version) VALUES(21)').run();db.prepare("INSERT INTO customers(jodoo_customer_id,name) VALUES('C1','Customer')").run();db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,branch_name) VALUES('B1',1,'One')").run();applyV22Migration(db);db.prepare('INSERT OR IGNORE INTO schema_meta(version) VALUES(23)').run();applyV24Migration(db);return db}

test('Product creation auto-generates code and sort order without requiring a reason',()=>{const db=fixture();applyV25Migration(db);const category=listCategories(db).items.find(item=>item.category_name==='Uncategorized'),before=category.product_count,created=createProduct(category.id,{productName:'  Glass Bottle  ',unit:'kg',status:'active',changedBy:'Owner'},db),listed=getCategory(category.id,db).products.find(item=>item.id===created.id);assert.equal(created.full_name,'Glass Bottle');assert.equal(created.product_code,'GLASS_BOTTLE');assert.equal(listed.sort_order,before*10+10);assert.equal(created.category_id,category.id);assert.equal(db.prepare('SELECT COUNT(*) count FROM material_price_levels WHERE product_id=?').get(created.id).count,0);assert.equal(db.prepare('SELECT COUNT(*) count FROM branch_product_price_assignments WHERE product_id=?').get(created.id).count,0);const audit=db.prepare("SELECT reason,after_json FROM material_master_audit WHERE entity_type='product' AND entity_id=? AND action='create'").get(created.id);assert.equal(audit.reason,'New Product / Grade');assert.equal(JSON.parse(audit.after_json).productCode,'GLASS_BOTTLE');const collision=createProduct(category.id,{productName:'Glass-Bottle',unit:'piece'},db);assert.equal(collision.product_code,'GLASS_BOTTLE_2');assert.throws(()=>createProduct(category.id,{productName:'glass bottle',unit:'kg'},db),/name already exists/)})

test('Product Price Group creation works without a user reason and starts unused',()=>{const db=fixture();applyV25Migration(db);const product=db.prepare("SELECT id FROM material_products WHERE product_code='G1'").get(),created=createProductPriceGroup(product.id,{priceAmount:.77,effectiveDate:'2026-08-19',status:'active',changedBy:'Owner'},db);assert.equal(created.price_amount,.77);assert.equal(created.customer_count,0);assert.equal(created.branch_count,0);assert.deepEqual(created.customers,[]);assert.equal(getProduct(product.id,db).priceGroups.some(group=>group.id===created.id),true);const audit=db.prepare("SELECT reason FROM material_master_audit WHERE entity_type='priceGroup' AND entity_id=? AND action='create'").get(created.id);assert.equal(audit.reason,'New Price Group');assert.throws(()=>createProductPriceGroup(product.id,{priceAmount:.77,effectiveDate:'2026-08-19'},db),/already has a Price Group/)})

test('Product Price Groups show Customer-level membership and Customer names',()=>{const db=fixture();applyV25Migration(db);const product=db.prepare("SELECT id FROM material_products WHERE product_code='G1'").get(),level=db.prepare('SELECT id FROM material_price_levels WHERE product_id=? ORDER BY id LIMIT 1').get(product.id);db.prepare("INSERT INTO customer_product_pricing(customer_id,product_id,standard_price_level_id,updated_by) VALUES(1,?,?,'test')").run(product.id,level.id);const listed=getProduct(product.id,db).priceGroups.find(group=>group.id===level.id),detail=getPriceGroup(level.id,db);assert.equal(listed.customer_count,1);assert.equal(listed.branch_count,1);assert.equal(detail.customers.length,1);assert.equal(detail.customers[0].customer_id,'C1');assert.equal(detail.customers[0].customer_name,'Customer');assert.equal(detail.customers[0].price_type,'standard');assert.equal(entityPreview('priceGroup',level.id,db).deleteEligible,false)})

test('v25 creates OCC first, leaves three Paper Products, and reruns as no-op',()=>{const db=fixture(),occBefore=db.prepare("SELECT * FROM material_products WHERE product_code='OCC'").get(),levels=JSON.stringify(db.prepare('SELECT id,price_amount,product_id FROM material_price_levels WHERE product_id=? ORDER BY id').all(occBefore.id)),assignments=JSON.stringify(db.prepare('SELECT * FROM branch_product_price_assignments WHERE product_id=? ORDER BY id').all(occBefore.id)),first=applyV25Migration(db),second=applyV25Migration(db);assert.deepEqual(listCategories(db).items.map(item=>item.category_name),['OCC','Paper','Aluminium','Scrap Iron','Uncategorized']);assert.equal(getCategory(listCategories(db).items.find(item=>item.category_name==='Paper').id,db).products.length,3);assert.equal(first.productsMoved,1);assert.equal(second.productsMoved,0);assert.equal(second.categoriesCreated,0);assert.equal(db.prepare("SELECT id FROM material_products WHERE product_code='OCC'").get().id,occBefore.id);assert.equal(JSON.stringify(db.prepare('SELECT id,price_amount,product_id FROM material_price_levels WHERE product_id=? ORDER BY id').all(occBefore.id)),levels);assert.equal(JSON.stringify(db.prepare('SELECT * FROM branch_product_price_assignments WHERE product_id=? ORDER BY id').all(occBefore.id)),assignments);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})

test('Category create trims names, audits, and rejects case-insensitive duplicates',()=>{const db=fixture();applyV25Migration(db);const row=createCategory({categoryName:'  Glass  ',sortOrder:50,reason:'Approved',changedBy:'Owner'},db);assert.equal(row.category_name,'Glass');assert.equal(row.sort_order,50);assert.equal(db.prepare("SELECT COUNT(*) count FROM material_master_audit WHERE entity_type='category' AND entity_id=? AND action='create'").get(row.id).count,1);assert.throws(()=>createCategory({categoryName:'gLaSs',reason:'Duplicate',changedBy:'Owner'},db),/already exists/)})

test('empty Category deletes through eligibility check while populated and reserved Categories are blocked',()=>{const db=fixture();applyV25Migration(db);const empty=createCategory({categoryName:'Glass',reason:'Approved'},db);assert.equal(entityPreview('category',empty.id,db).deleteEligible,true);assert.equal(deleteEntity('category',empty.id,{reason:'Unused',changedBy:'Owner'},db).deleted,true);const paper=listCategories(db).items.find(item=>item.category_name==='Paper'),reserved=listCategories(db).items.find(item=>item.category_name==='Uncategorized');assert.equal(entityPreview('category',paper.id,db).deleteEligible,false);assert.equal(entityPreview('category',reserved.id,db).deleteEligible,false);assert.throws(()=>deleteEntity('category',paper.id,{reason:'No',changedBy:'Owner'},db),/related data/);assert.throws(()=>deleteEntity('category',reserved.id,{reason:'No',changedBy:'Owner'},db),/related data/)})

test('selected Products move atomically without changing IDs, Price Groups, or assignments',()=>{const db=fixture();applyV25Migration(db);const categories=listCategories(db).items,paper=categories.find(item=>item.category_name==='Paper'),uncategorized=categories.find(item=>item.category_name==='Uncategorized'),product=getCategory(paper.id,db).products[0],before={product:db.prepare('SELECT id,full_name FROM material_products WHERE id=?').get(product.id),levels:JSON.stringify(db.prepare('SELECT * FROM material_price_levels WHERE product_id=? ORDER BY id').all(product.id)),assignments:JSON.stringify(db.prepare('SELECT * FROM branch_product_price_assignments WHERE product_id=? ORDER BY id').all(product.id))};const preview=previewMoveProducts(paper.id,uncategorized.id,[product.id],db);assert.equal(preview.products[0].id,product.id);assert.equal(moveProductsCategory(paper.id,uncategorized.id,[product.id],{reason:'Reclassify',changedBy:'Owner'},db).changedCount,1);assert.deepEqual(db.prepare('SELECT id,full_name FROM material_products WHERE id=?').get(product.id),before.product);assert.equal(JSON.stringify(db.prepare('SELECT * FROM material_price_levels WHERE product_id=? ORDER BY id').all(product.id)),before.levels);assert.equal(JSON.stringify(db.prepare('SELECT * FROM branch_product_price_assignments WHERE product_id=? ORDER BY id').all(product.id)),before.assignments)})

test('Product move rolls back fully when one Product no longer belongs to source',()=>{const db=fixture();applyV25Migration(db);const categories=listCategories(db).items,paper=categories.find(item=>item.category_name==='Paper'),target=categories.find(item=>item.category_name==='Uncategorized'),paperProduct=getCategory(paper.id,db).products[0],wrong=getCategory(categories.find(item=>item.category_name==='Scrap Iron').id,db).products[0];assert.throws(()=>moveProductsCategory(paper.id,target.id,[paperProduct.id,wrong.id],{reason:'Atomic test',changedBy:'Owner'},db),/no longer belong/);assert.equal(db.prepare('SELECT category_id FROM material_products WHERE id=?').get(paperProduct.id).category_id,paper.id);assert.equal(db.prepare("SELECT COUNT(*) count FROM material_product_category_history WHERE reason='Atomic test'").get().count,0)})

test('Materials UI wires automatic Product creation, working Price Group creation, filtering, and Customer details',()=>{const source=fs.readFileSync(new URL('../src/MaterialsPricesPage.jsx',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../src/MasterDataPage.css',import.meta.url),'utf8');assert.match(source,/onClick=\{beginCreate\}>＋ Add Category/);assert.match(source,/onClick=\{beginAddProduct\}>＋ Add Product \/ Grade/);assert.match(source,/Confirm Product':'Preview Product'/);assert.match(source,/Product Code<output className="auto-product-code"/);assert.match(source,/\/api\/material-products\/\$\{product\.id\}\/price-groups/);assert.match(source,/＋ Add Price Group/);assert.match(source,/Show unused price groups/);assert.match(source,/group\.customer_count/);assert.match(source,/data\.customers\.map/);assert.match(source,/<th>Customer<\/th>/);assert.match(source,/categoryAction\.phase==='preview'\?'Confirm Move':'Preview Move'/);assert.match(source,/← Back to Material Categories/);assert.match(source,/← Back to \{category\.category_name\}/);assert.match(source,/Confirm Group Price Change/);assert.match(css,/\.price-change-fields/);assert.match(css,/\.product-price-customer-table/);assert.match(css,/@media\(max-width:600px\).*\.price-change-fields\{grid-template-columns:minmax\(0,1fr\)/s)})

test('Materials owns clear hierarchical back entries and OCC returns directly to Categories',()=>{const app=fs.readFileSync(new URL('../src/App.jsx',import.meta.url),'utf8'),materials=fs.readFileSync(new URL('../src/MaterialsPricesPage.jsx',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../src/MasterDataPage.css',import.meta.url),'utf8');assert.match(app,/page!==['"]dashboard['"]&&page!==['"]materials['"]&&page!==['"]vehicles['"]&&pageTab!==['"]route-template['"]&&<BackButton/);assert.match(materials,/className="material-back-button" onClick=\{onBack\}>← Back to Material Categories<\/button>/);assert.match(materials,/if\(product\?\.usesOccEngine\)return <OccPriceGroups/);assert.match(materials,/onBack=\{\(\)=>\{setProduct\(null\);setCategory\(null\)\}\}/);assert.match(materials,/<BackButton className="material-back-button"/);assert.match(materials,/← Back to \{category\.category_name\}/);assert.match(materials,/← Back to \{product\.full_name\} Price Groups/);assert.match(css,/@media\(max-width:600px\).*\.material-back-button\{width:100%;white-space:normal;text-align:left\}/s)})
