import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {clearBillDraft,loadBillDraft,processPaymentProof,saveBillDraft} from '../src/paymentProofImage.js'
import {translate} from '../src/translations.js'

const fakeFile=(size=12*1024*1024,type='image/jpeg')=>({size,type,name:'camera.jpg'})
const imageDeps=(outputSize=900_000)=>({createBitmap:async()=>({width:5000,height:3500,close(){this.closed=true}}),createCanvas:()=>({width:0,height:0,getContext:()=>({fillRect(){},drawImage(){},set fillStyle(value){this.value=value}}),toBlob(callback){callback(new Blob([new Uint8Array(outputSize)],{type:'image/jpeg'}))}})})
const storage=()=>{const data=new Map();return{getItem:key=>data.get(key)||null,setItem:(key,value)=>data.set(key,value),removeItem:key=>data.delete(key)}}

test('large Android camera image is orientation-aware, resized and compressed before React state/upload',async()=>{let options;const deps=imageDeps();deps.createBitmap=async(file,next)=>{options=next;return{width:5000,height:3500,close(){}}};const proof=await processPaymentProof(fakeFile(),deps);assert.equal(options.imageOrientation,'from-image');assert.equal(proof.width,2200);assert.equal(proof.height,1540);assert.ok(proof.blob.size<3*1024*1024);assert.equal(proof.type,'image/jpeg')})
test('unsupported, oversized and decode failures give actionable errors',async()=>{await assert.rejects(processPaymentProof(fakeFile(100,'application/pdf'),imageDeps()),/Unsupported/);await assert.rejects(processPaymentProof(fakeFile(26*1024*1024),imageDeps()),/25 MB/);await assert.rejects(processPaymentProof(fakeFile(100,'image/heic'),{...imageDeps(),createBitmap:async()=>{throw new Error('decode')},loadImage:async()=>{throw new Error('decode')}}),/cannot decode HEIC/)})
test('older Android browser falls back when createImageBitmap options or decoding fail',async()=>{let attempts=0,usedFallback=false;const deps=imageDeps();deps.createBitmap=async()=>{attempts++;throw new Error('unsupported')};deps.loadImage=async()=>{usedFallback=true;return{width:1200,height:1600,source:{kind:'html-image'},close(){}}};const proof=await processPaymentProof(fakeFile(400000,'image/jpg'),deps);assert.equal(attempts,2);assert.equal(usedFallback,true);assert.equal(proof.type,'image/jpeg')})
test('bill draft survives reload and is cleared after completion',()=>{const store=storage(),draft={items:[{productId:4,quantity:'62.5'}],printChoice:'no_print'};saveBillDraft(91,draft,store);assert.deepEqual(loadBillDraft(91,store),draft);clearBillDraft(91,store);assert.equal(loadBillDraft(91,store),null)})
test('mobile and office Expenses require a processed receipt preview before saving',()=>{const mobile=fs.readFileSync(new URL('../src/AuthPages.jsx',import.meta.url),'utf8'),office=fs.readFileSync(new URL('../src/ExpenseRecordsPage.jsx',import.meta.url),'utf8'),service=fs.readFileSync(new URL('../server/cashFloatService.mjs',import.meta.url),'utf8');assert.match(mobile,/Receipt photo \(required\)/);assert.match(mobile,/disabled=\{busy\|\|!form\.proof\}/);assert.match(mobile,/proof:await proofData\(form\.proof\)/);assert.match(office,/Receipt photo \(required\)/);assert.match(office,/processPaymentProof\(file\)/);assert.match(office,/proof:await proofData\(form\.proof\)/);assert.equal((service.match(/Receipt photo is required\./g)||[]).length,2)})
test('proof source and replacement labels are complete in all three languages',()=>{for(const language of ['en','ms','zh'])for(const key of ['purchase.takePhoto','purchase.chooseGallery','purchase.retakePhoto','purchase.replaceFromGallery','purchase.removePhoto','purchase.confirmUpload'])assert.notEqual(translate(language,key),key)})
test('server retains strict proof validation, driver ownership and explicit 413 handling',()=>{const service=fs.readFileSync(new URL('../server/purchaseBillingService.mjs',import.meta.url),'utf8'),api=fs.readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8');assert.match(service,/Only an active driver/);assert.ok(service.includes('jpeg|png|webp'));assert.match(service,/8\*1024\*1024/);assert.match(service,/Number\(stop\.driverId\)!==Number\(employeeId\)/);assert.match(api,/statusCode:413/);assert.match(api,/PAYLOAD_TOO_LARGE/)})

test('camera JPEG without MIME is recognized by signature; fake extension is rejected',async()=>{
 const camera=new File([new Uint8Array([255,216,255,224,0,1])],'camera.jpg')
 const proof=await processPaymentProof(camera,imageDeps());assert.equal(proof.type,'image/jpeg');assert.equal(proof.name,'camera.jpg')
 await assert.rejects(processPaymentProof(new File(['%PDF-1.7'],'camera.jpg'),imageDeps()),/Unsupported/)
})
