import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql,SCHEMA_VERSION} from '../server/schema.mjs'
import {listMasterAudit,saveBuyer,saveOperationalLocation} from '../server/customerMasterService.mjs'

const database=()=>{const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);return db}

test('Company Yard uses the existing Operational Location schema and remains distinct from Buyer factory',()=>{const db=database(),buyer=saveBuyer({buyerName:'Existing Buyer'},null,db),buyerLocation=saveOperationalLocation({name:'Buyer Factory',locationType:'Buyer',buyerId:buyer.buyerId},null,db),yard=saveOperationalLocation({name:'Lee Sai Ker Enterprise',locationType:'Company Yard',address:'Confirmed address',latitude:1.5,longitude:110.3,notes:'Main gate',canStart:true,status:'active',changedBy:'Owner Admin',reason:'Create company base'},null,db);assert.equal(SCHEMA_VERSION,42);const stored=db.prepare('SELECT location_type,operational_type,buyer_id FROM operational_locations WHERE id=?').get(yard.id);assert.deepEqual({...stored},{location_type:'depot',operational_type:'Company Yard',buyer_id:null});assert.equal(yard.gpsStatus,'Set');assert.equal(yard.canStart,1);assert.equal(db.prepare('SELECT operational_type FROM operational_locations WHERE id=?').get(buyerLocation.id).operational_type,'Buyer');assert.equal(db.prepare('SELECT COUNT(*) n FROM buyers').get().n,1)})

test('Operational Location coordinates validate as a pair and audit failure rolls back the master write',()=>{const db=database();assert.throws(()=>saveOperationalLocation({name:'Bad Yard',locationType:'Company Yard',latitude:1.5},null,db),/set or cleared together/);db.exec("CREATE TRIGGER fail_location_audit BEFORE INSERT ON master_change_history WHEN NEW.entity_type='operational_location' BEGIN SELECT RAISE(ABORT,'audit failed'); END");assert.throws(()=>saveOperationalLocation({name:'Rollback Yard',locationType:'Company Yard',latitude:1.5,longitude:110.3,changedBy:'Owner',reason:'test'},null,db),/audit failed/);assert.equal(db.prepare("SELECT COUNT(*) n FROM operational_locations WHERE name='Rollback Yard'").get().n,0)})

test('Company Yard create and update preserve actor, before/after, reason, GPS and status',()=>{const db=database(),yard=saveOperationalLocation({name:'Yard',locationType:'Company Yard',status:'active',changedBy:'Owner',reason:'Initial base'},null,db);const updated=saveOperationalLocation({address:'Official address',latitude:1.55,longitude:110.35,notes:'Loading entrance',canStart:true,changedBy:'Operations Admin',reason:'GPS confirmed'},yard.id,db),history=listMasterAudit({entityType:'operational_location',entityId:yard.id},db);assert.equal(updated.gpsStatus,'Set');assert.equal(updated.notes,'Loading entrance');assert.equal(history[0].changedBy,'Operations Admin');assert.equal(history[0].reason,'GPS confirmed');assert.match(history[0].beforeJson,/Yard/);assert.match(history[0].afterJson,/Official address/)})

test('Operational Location editor reuses the shared GPS picker; API actor comes from Session',()=>{const ui=fs.readFileSync(new URL('../src/MasterDataPage.jsx',import.meta.url),'utf8'),picker=fs.readFileSync(new URL('../src/SharedGpsInput.jsx',import.meta.url),'utf8'),server=fs.readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8');for(const token of ['OperationalLocationEditor','SharedGpsInput','Company Yard is a KCS-owned base'])assert.match(ui,new RegExp(token));for(const token of ['Get Current GPS','Paste Coordinates','Select on Map','reverse-geocode'])assert.match(picker,new RegExp(token));assert.match(server,/canManageOperationalLocations/);assert.match(server,/Operational Location management permission is required/);assert.match(server,/saveOperationalLocation\(\{\.\.\.payload,changedBy:session\.employeeName\}/)})
