import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV51Migration} from '../server/migrationV51.mjs'
import {assignRouteVehicle,assignStopsToRoute,generateDay,getDispatchDay,updateStop} from '../server/dispatchService.mjs'
import {installWeeklyRoutePlan} from '../server/weeklyRoutePlanService.mjs'

const fixture=()=>{const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.prepare("INSERT INTO customers(jodoo_customer_id,name) VALUES('C1','Customer')").run();db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,branch_name,collection_frequency,assigned_weekdays) VALUES('B1',1,'First','Weekly','[\"Monday\"]'),('B2',1,'Second','Weekly','[\"Monday\"]')").run();db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S1',1,'B1','Weekly','Monday'),('S2',2,'B2','Weekly','Monday')").run();db.prepare("INSERT INTO vehicles(vehicle_code,registration_number,status,operational_status) VALUES('Truck A','AAA1','available','active'),('Truck B','BBB2','available','active')").run();installWeeklyRoutePlan({name:'Five Routes',sourceName:'test',entries:[[1,'AAA1',1,1,'B1','North','Area A'],[1,'AAA1',1,2,'B2','South','Area B']]},{},db);return db}

test('Route customers and order stay fixed while daily vehicle changes',()=>{const db=fixture();generateDay({startDate:'2026-09-07'},db);let day=getDispatchDay('2026-09-07',db);assert.deepEqual(day.routeBoards[0].stops.map(stop=>stop.branchId),['B1','B2']);assert.equal(day.routeBoards[0].vehicleId,null);assignRouteVehicle('2026-09-07',1,{vehicleId:1,changedBy:'Supervisor'},db);day=getDispatchDay('2026-09-07',db);assert.equal(day.routeBoards[0].vehicleId,1);assignRouteVehicle('2026-09-07',1,{vehicleId:2,changedBy:'Supervisor'},db);day=getDispatchDay('2026-09-07',db);assert.equal(day.routeBoards[0].vehicleId,2);assert.deepEqual(day.routeBoards[0].stops.map(stop=>stop.branchId),['B1','B2']);assert.deepEqual(day.routeBoards[0].stops.map(stop=>stop.routeStopSequence),[1,2])})

test('a Route can be assigned while the editable day requires reapproval',()=>{const db=fixture();generateDay({startDate:'2026-09-07'},db);db.prepare("UPDATE dispatch_days SET status='reapproval_required' WHERE dispatch_date='2026-09-07'").run();assignRouteVehicle('2026-09-07',1,{vehicleId:1,changedBy:'Supervisor'},db);assert.equal(getDispatchDay('2026-09-07',db).routeBoards[0].vehicleId,1)})

test('a whole Route cannot be split across vehicles or changed after approval',()=>{const db=fixture();generateDay({startDate:'2026-09-07'},db);assignRouteVehicle('2026-09-07',1,{vehicleId:1},db);const stop=getDispatchDay('2026-09-07',db).routeBoards[0].stops[0];assert.throws(()=>updateStop(stop.id,{vehicleId:2,tripNumber:1},db),/整条 Route/);db.prepare("UPDATE dispatch_days SET status='approved' WHERE dispatch_date='2026-09-07'").run();assert.throws(()=>assignRouteVehicle('2026-09-07',1,{vehicleId:2},db),/protected/)})

test('Zone and Area default vehicle bindings do not assign a Route',()=>{const db=fixture();db.prepare("INSERT INTO zone_groups(code,name,sort_order) VALUES('Z','Zone',1)").run();db.prepare("INSERT INTO areas(jodoo_area_id,name,zone_group_id,default_vehicle_id) VALUES('A','Area',1,1)").run();db.prepare('UPDATE branches SET area_id=1').run();generateDay({startDate:'2026-09-07'},db);const day=getDispatchDay('2026-09-07',db);assert.equal(day.routeBoards[0].vehicleId,null);assert.equal(day.vehicleBoards.find(board=>board.id===1).customerCount,0)})

test('temporary customers are assigned to a Route and follow that Route vehicle',()=>{const db=fixture();db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,branch_name,collection_frequency,assigned_weekdays) VALUES('B3',1,'Temporary','Weekly','[\"Monday\"]')").run();db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S3',3,'B3','Weekly','Monday')").run();generateDay({startDate:'2026-09-07'},db);let day=getDispatchDay('2026-09-07',db),temporary=day.extraUnassignedStops[0];assignRouteVehicle('2026-09-07',1,{vehicleId:2,changedBy:'Supervisor'},db);assignStopsToRoute('2026-09-07',{routeNumber:1,stopIds:[temporary.id],changedBy:'Supervisor'},db);day=getDispatchDay('2026-09-07',db);assert.equal(day.extraUnassignedStops.length,0);assert.equal(day.routeBoards[0].customerCount,3);assert.equal(day.routeBoards[0].stops.at(-1).branchId,'B3');assert.equal(day.routeBoards[0].vehicleId,2);assert.equal(day.routeBoards[0].stops.at(-1).vehicleId,2)})

test('one active Route does not block temporary-customer assignment to another Route',()=>{const db=fixture();db.prepare("INSERT INTO branches(jodoo_branch_id,customer_id,branch_name,collection_frequency,assigned_weekdays) VALUES('B3',1,'Temporary 1','Weekly','[\"Monday\"]'),('B4',1,'Temporary 2','Weekly','[\"Monday\"]')").run();db.prepare("INSERT INTO branch_schedules(jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week) VALUES('S3',3,'B3','Weekly','Monday'),('S4',4,'B4','Weekly','Monday')").run();generateDay({startDate:'2026-09-07'},db);let day=getDispatchDay('2026-09-07',db),temporary=day.extraUnassignedStops;assignRouteVehicle('2026-09-07',1,{vehicleId:1,changedBy:'Supervisor'},db);db.prepare("UPDATE dispatches SET status='in_progress' WHERE vehicle_id=1 AND dispatch_date='2026-09-07'").run();db.prepare("UPDATE dispatch_days SET status='in_progress' WHERE dispatch_date='2026-09-07'").run();assignStopsToRoute('2026-09-07',{routeNumber:2,stopIds:[temporary[0].id],changedBy:'Supervisor'},db);day=getDispatchDay('2026-09-07',db);assert.equal(day.routeBoards[1].customerCount,1);assert.equal(day.extraUnassignedStops.length,1);assert.throws(()=>assignStopsToRoute('2026-09-07',{routeNumber:1,stopIds:[temporary[1].id],changedBy:'Supervisor'},db),/Route 1 已经开始执行/)})

test('v51 migration is additive, idempotent and preserves operational rows',()=>{const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;CREATE TABLE schema_meta(version INTEGER PRIMARY KEY);INSERT INTO schema_meta VALUES(50);CREATE TABLE weekly_route_plan_stops(plan_id INTEGER,weekday INTEGER,branch_id INTEGER,vehicle_registration_number TEXT,trip_number INTEGER,stop_sequence INTEGER);CREATE TABLE dispatch_days(id INTEGER PRIMARY KEY,dispatch_date TEXT);CREATE TABLE vehicles(id INTEGER PRIMARY KEY);CREATE TABLE dispatches(id INTEGER PRIMARY KEY,vehicle_id INTEGER);CREATE TABLE dispatch_trips(id INTEGER PRIMARY KEY,dispatch_day_id INTEGER,dispatch_id INTEGER);CREATE TABLE dispatch_stops(id INTEGER PRIMARY KEY,dispatch_id INTEGER,dispatch_trip_id INTEGER,status TEXT,branch_id INTEGER);CREATE TABLE purchase_bills(id INTEGER);CREATE TABLE unloading_weight_records(id INTEGER);CREATE TABLE cash_float_transactions(id INTEGER);CREATE TABLE admin_expense_records(id INTEGER)`);db.prepare("INSERT INTO weekly_route_plan_stops VALUES(1,1,1,'QTY5028',1,1)").run();const first=applyV51Migration(db),second=applyV51Migration(db);assert.equal(first.schemaVersion,51);assert.equal(second.noOp,true);assert.equal(db.prepare('SELECT route_number n FROM weekly_route_plan_stops').get().n,4);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})
