import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import {schemaSql} from '../server/schema.mjs'
import {saveSales,listSales,salesPhoto,exportSales,salesRecord} from '../server/salesService.mjs'
import {parseSalesOcr} from '../server/salesOcr.mjs'
import {applyV60Migration} from '../server/migrationV60.mjs'
const office={role:'office',employeeName:'Office'},photo={name:'settlement.png',dataUrl:'data:image/png;base64,iVBORw0KGgo='}
const payload=()=>({buyerId:1,vehicleId:1,billNumber:'CP-2026091027',settlementDate:'2026-09-10',total:'15.00',rounding:'0.00',reviewed:true,proof:photo,lines:[{deliveryDate:'2026-09-09',slipNumber:'TN-1',description:'OCC',weightKg:'10',unitPrice:'0.50',amount:'5.00'},{deliveryDate:'2026-09-09',slipNumber:'TN-2',description:'OCC',weightKg:'20',unitPrice:'0.50',amount:'10.00'}]})
function setup(t){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.exec("INSERT INTO buyers(buyer_code,buyer_name) VALUES('F1','Factory One'),('F2','Factory Two');INSERT INTO vehicles(vehicle_code,registration_number,status) VALUES('V1','QTY5028','available');INSERT INTO schema_meta(version) VALUES(59)");const uploadsRoot=fs.mkdtempSync(path.join(os.tmpdir(),'kcs-sales-test-'));t.after(()=>{db.close();fs.rmSync(uploadsRoot,{recursive:true,force:true})});return{db,uploadsRoot}}
test('settlement saves each line price, preserves proof and rejects duplicate factory number',t=>{const{db,uploadsRoot}=setup(t),p=payload();p.lines[1].unitPrice='0.60';p.lines[1].amount='12.00';p.total='17.00';const r=saveSales(p,office,db,{uploadsRoot});assert.equal(r.lines[1].unitPrice,'0.60');assert.equal(r.total,'17.00');assert.ok(fs.existsSync(path.join(uploadsRoot,salesPhoto(r.id,office,db).storage_key)));assert.throws(()=>saveSales({...p,billNumber:' cp-2026091027 '},office,db,{uploadsRoot}),/SALES_DUPLICATE/);assert.equal(saveSales({...p,buyerId:2},office,db,{uploadsRoot}).buyerId,2)})
test('drivers and crew cannot read, save or export settlements',async t=>{const{db,uploadsRoot}=setup(t);for(const role of ['driver','crew']){assert.throws(()=>saveSales(payload(),{role},db,{uploadsRoot}),/SALES_ACCESS/);assert.throws(()=>listSales({from:'2026-09-01',to:'2026-09-30'},{role},db),/SALES_ACCESS/);await assert.rejects(()=>exportSales({}, {role},db,{uploadsRoot}),/SALES_ACCESS/)}})
test('invalid dates, missing review, wrong line amounts and missing proof cannot save',t=>{const{db,uploadsRoot}=setup(t);for(const p of [{...payload(),reviewed:false},{...payload(),total:'12.00'},{...payload(),proof:null},{...payload(),settlementDate:'2026-02-30'},{...payload(),lines:[{...payload().lines[0],amount:'8.00'}],total:'8.00'}])assert.throws(()=>saveSales(p,office,db,{uploadsRoot}));assert.equal(db.prepare('SELECT COUNT(*) n FROM sales_settlements').get().n,0)})
test('edit keeps proof and audit; stale edits cannot overwrite newer changes',t=>{const{db,uploadsRoot}=setup(t),r=saveSales(payload(),office,db,{uploadsRoot});const next=saveSales({...r,reviewed:true,remarks:'Checked'},office,db,{uploadsRoot});assert.equal(next.revision,2);assert.equal(fs.readdirSync(path.join(uploadsRoot,'sales')).length,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM sales_settlement_audit').get().n,2);assert.throws(()=>saveSales({...r,reviewed:true},office,db,{uploadsRoot}),/SALES_STALE/)})
test('database failure rolls back record and removes new photo',t=>{const{db,uploadsRoot}=setup(t);db.exec("CREATE TRIGGER reject_sale BEFORE INSERT ON sales_settlement_audit BEGIN SELECT RAISE(ABORT,'injected');END");assert.throws(()=>saveSales(payload(),office,db,{uploadsRoot}),/injected/);assert.equal(db.prepare('SELECT COUNT(*) n FROM sales_settlements').get().n,0);assert.equal(fs.readdirSync(path.join(uploadsRoot,'sales')).length,0)})
test('multiselect including blanks, natural sort and Excel export use identical rows',async t=>{const{db,uploadsRoot}=setup(t);saveSales(payload(),office,db,{uploadsRoot});const q={from:'2026-09-01',to:'2026-09-30',columns:JSON.stringify({slipNumber:['TN-2'],remarks:['']}),sortKey:'weightKg',sortDirection:'desc'};const result=listSales(q,office,db);assert.equal(result.items.length,1);assert.equal(result.items[0].slipNumber,'TN-2');const bytes=await exportSales(q,office,db,{uploadsRoot});const {default:ExcelJS}=await import('exceljs');const book=new ExcelJS.Workbook();await book.xlsx.load(bytes);assert.equal(book.getWorksheet('Sales').rowCount,2);assert.equal(book.getWorksheet('Settlement Photos').getImages().length,1)})
test('OCR parses multiple TN rows, two prices and matches current master names',()=>{const result=parseSalesOcr('TRIPLE-C RECYCLE SDN BHD\nQTY5028\nNo : CP-2026091027\nDate : 10/09/2026\n1 OLD CORRUGATED BOX 09/09 TN-153296 KG 960.00 0.420 403.200\n2 OLD CORRUGATED BOX 09/09 TN-153340 KG 1,540.00 0.500 770.000\nFinal Total 1,173.20',{buyers:[{id:1,name:'TRIPLE-C RECYCLE SDN BHD'}],vehicles:[{id:1,plate:'QTY5028'}]});assert.equal(result.buyerId,'1');assert.equal(result.vehicleId,'1');assert.equal(result.lines.length,2);assert.equal(result.lines[1].unitPrice,'0.500');assert.equal(result.lines[1].weightKg,'1540.00');assert.equal(result.lines[0].deliveryDate,'2026-09-09');assert.equal(result.total,'1173.20')})
test('unclear OCR never invents missing weight, vehicle or invalid date',()=>{const r=parseSalesOcr('Date: 40/09/2026\n1 OLD CORRUGATED BOX 09/09 TN-153296 KG unreadable 0.420 403.200');assert.equal(r.settlementDate,undefined);assert.equal(r.vehicleId,undefined);assert.equal(r.lines[0].weightKg,'');assert.equal(r.lines[0].deliveryDate,'')})
test('migration is idempotent and preserves master records',t=>{const{db}=setup(t);assert.equal(applyV60Migration(db).schemaVersion,60);assert.equal(applyV60Migration(db).noOp,true);assert.equal(db.prepare('SELECT COUNT(*) n FROM buyers').get().n,2);assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(),[])})
