import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {schemaSql} from '../server/schema.mjs';
import {releaseIdleSundayAssignments as release} from '../server/sundayIdleAssignments.mjs';
const db=new DatabaseSync(':memory:');db.exec(schemaSql);db.exec('PRAGMA foreign_keys=OFF');
db.exec(`CREATE TABLE IF NOT EXISTS sunday_dispatch_setup(dispatch_day_id INTEGER PRIMARY KEY);INSERT INTO sunday_dispatch_setup(dispatch_day_id) VALUES(1);
INSERT INTO dispatch_days(id,weekly_plan_id,dispatch_date) VALUES(1,1,'2026-10-04');
INSERT INTO dispatches(id,dispatch_date,vehicle_id,driver_id,assistant_id) VALUES(1,'2026-10-04',2,9,17);
INSERT INTO dispatch_trips(id,dispatch_day_id,dispatch_id) VALUES(1,1,1);
INSERT INTO dispatch_vehicle_assistants(dispatch_day_id,vehicle_id,employee_id) VALUES(1,2,17);`);
const day={id:1,dispatch_date:'2026-10-04',status:'draft'},opts={today:'2026-10-03'};
assert.deepEqual(release(db,day,{today:'2026-10-05'}),[]);
assert.deepEqual(release(db,day,{...opts,excludeVehicleId:2}),[]);
db.exec("UPDATE dispatch_trips SET started_at='2026-10-04T08:00:00+08:00'");assert.deepEqual(release(db,day,opts),[]);db.exec('UPDATE dispatch_trips SET started_at=NULL');
db.exec("UPDATE dispatches SET status='released'");assert.deepEqual(release(db,day,opts),[]);db.exec("UPDATE dispatches SET status='draft'");
db.exec('INSERT INTO daily_route_assignments(dispatch_day_id,route_number,vehicle_id) VALUES(1,1,2)');assert.deepEqual(release(db,day,opts),[]);db.exec('DELETE FROM daily_route_assignments');
db.exec("CREATE TRIGGER fail_audit BEFORE INSERT ON dispatch_change_logs BEGIN SELECT RAISE(ABORT,'audit unavailable'); END");assert.throws(()=>release(db,day,opts));assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_vehicle_assistants').get().n,1);db.exec('DROP TRIGGER fail_audit');
assert.deepEqual(release(db,day,opts),[2]);assert.equal(db.prepare('SELECT driver_id FROM dispatches').get().driver_id,null);assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_vehicle_assistants').get().n,0);assert.equal(db.prepare('SELECT COUNT(*) n FROM dispatch_change_logs').get().n,1);assert.deepEqual(release(db,day,opts),[]);
db.close();console.log('Sunday cleanup: real schema, historical/target/route/execution protection, audit rollback and idempotence passed');
