import assert from 'node:assert/strict'
import {spawnSync} from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
const root=path.resolve(import.meta.dirname,'..')
const makeFixture=(version=41)=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'kcs-v42-deploy-')),dbPath=path.join(dir,'fixture.sqlite'),snapshot=path.join(dir,'snapshots','before.json'),db=new DatabaseSync(dbPath);db.exec('PRAGMA foreign_keys=ON;'+schemaSql);db.exec(`DELETE FROM schema_meta;INSERT INTO schema_meta(version) VALUES(${version});INSERT INTO customers(id,jodoo_customer_id,name) VALUES(1,'1','Customer');INSERT INTO branches(id,jodoo_branch_id,customer_id,branch_name) VALUES(1,'1',1,'Branch');INSERT INTO employees(id,employee_code,name,job_role,employment_status,is_active) VALUES(1,'EMP1','Owner','Office','active',1);INSERT INTO auth_accounts(id,employee_id,username,password_hash,role,is_active) VALUES(1,1,'owner','hash','admin',1);INSERT INTO vehicles(id,vehicle_code,registration_number) VALUES(1,'V1','ABC1');INSERT INTO zone_groups(id,code,name) VALUES(99,'Z99','Zone');INSERT INTO areas(id,jodoo_area_id,name,zone_group_id) VALUES(99,'A99','Area',99);INSERT INTO branch_schedules(id,jodoo_schedule_id,branch_id,source_branch_id,frequency) VALUES(1,'S1',1,'1','Weekly');INSERT INTO dispatches(id,dispatch_date,status) VALUES(1,'2026-01-01','draft');INSERT INTO dispatch_stops(id,dispatch_id,branch_id,stop_sequence) VALUES(1,1,1,1);INSERT INTO materials(id,material_code,material_name) VALUES(1,'OCC','OCC');INSERT INTO material_price_levels(id,material_id,price_amount,effective_date) VALUES(1,1,.2,'2026-01-01');INSERT INTO customer_material_pricing(id,customer_id,material_id,standard_price_level_id) VALUES(1,1,1,1);`);db.close();return{dir,dbPath,snapshot}}
const run=(fixture,mode='before',env=true)=>spawnSync(process.execPath,['scripts/cloud-preflight.mjs','--mode',mode,'--snapshot',fixture.snapshot],{cwd:root,env:{...process.env,KCS_DB_PATH:env?fixture.dbPath:''},encoding:'utf8'}),migrate=fixture=>spawnSync(process.execPath,['scripts/migrate-v42.mjs'],{cwd:root,env:{...process.env,KCS_DB_PATH:fixture.dbPath,KCS_DATA_DIR:fixture.dir},encoding:'utf8'}),mutate=(fixture,sql)=>{const db=new DatabaseSync(fixture.dbPath);db.exec(sql);db.close()}

test('v41 code-only before/after preserves schema, counts and sentinels without writing the database',()=>{const f=makeFixture(),before=fs.readFileSync(f.dbPath);assert.equal(run(f).status,0);assert.deepEqual(fs.readFileSync(f.dbPath),before);const first=migrate(f);assert.equal(first.status,0,first.stderr);const second=migrate(f);assert.equal(second.status,0,second.stderr);assert.match(second.stdout,/"noOp": true/);const after=run(f,'after');assert.equal(after.status,0,after.stderr);const snap=JSON.parse(fs.readFileSync(f.snapshot));assert.equal(snap.schemaVersion,41);assert.ok(snap.counts.dispatch_stops);assert.match(snap.fingerprints.branches,/^[a-f0-9]{64}$/);assert.equal(snap.accountSentinels[0].passwordHash,undefined)})

test('preflight rejects schema mismatch, missing KCS_DB_PATH and missing snapshot',()=>{const wrong=makeFixture(40);assert.match(run(wrong).stderr,/before mode requires schema v41, found v40/);const f=makeFixture();assert.match(run(f,'before',false).stderr,/KCS_DB_PATH is required/);const predeploy=spawnSync(process.execPath,['scripts/predeploy.mjs'],{cwd:root,env:{...process.env,KCS_DB_PATH:''},encoding:'utf8'});assert.match(predeploy.stderr,/KCS_DB_PATH is required/);assert.equal(run(f).status,0);assert.match(run(f,'after').stderr,/after mode requires schema v42, found v41/);mutate(f,'INSERT INTO schema_meta(version) VALUES(42)');assert.equal(run(f,'after').status,0)})

test('postflight rejects a critical count decrease',()=>{for(const [sql,pattern] of [["INSERT INTO customers(id,jodoo_customer_id,name) VALUES(2,'2','Extra')",/customers count changed/],["UPDATE branches SET branch_name='Changed' WHERE id=1",/branches fingerprint changed/],["UPDATE employees SET name='Changed' WHERE id=1",/employees fingerprint changed|Employee sentinels changed/],["UPDATE auth_accounts SET password_hash='changed' WHERE id=1",/auth_accounts fingerprint changed|Account identity/]]){const f=makeFixture();assert.equal(run(f).status,0);assert.equal(migrate(f).status,0);mutate(f,sql);assert.match(run(f,'after').stderr,pattern)}})

test('documentation and package entry points separate v41 code-only deploy from historical v17 migration',()=>{const script=fs.readFileSync(path.join(root,'scripts/deploy-v42.sh'),'utf8'),doc=fs.readFileSync(path.join(root,'docs/DEPLOY_V42_CUSTOMER_PRICING.md'),'utf8'),pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json')));for(const token of ['KCS_DB_PATH','git diff-index --quiet','systemctl stop','sqlite3 "$KCS_DB_PATH" ".backup','PRAGMA integrity_check','scripts/migrate-v42.mjs','npm ci','npm run build','KCS_INTERNAL_HEALTH','KCS_HTTPS_HEALTH','rollback'])assert.match(script,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(doc,/sudo env KCS_DB_PATH=.*bash \/opt\/kcs-app\/scripts\/deploy-v42\.sh/);assert.equal(pkg.scripts['deploy:v42:check'],'node scripts/cloud-preflight.mjs')})

test('postflight rejects changed employee identity',()=>{const f=makeFixture();assert.equal(run(f).status,0);assert.equal(migrate(f).status,0);mutate(f,"UPDATE employees SET name='Changed' WHERE id=1");assert.match(run(f,'after').stderr,/employees fingerprint changed|Employee sentinels changed/)})
test('postflight rejects changed account identity',()=>{const f=makeFixture();assert.equal(run(f).status,0);assert.equal(migrate(f).status,0);mutate(f,"UPDATE auth_accounts SET username='changed' WHERE id=1");assert.match(run(f,'after').stderr,/auth_accounts fingerprint changed|Account identity/)})
test('postflight rejects changed password fingerprint',()=>{const f=makeFixture();assert.equal(run(f).status,0);assert.equal(migrate(f).status,0);mutate(f,"UPDATE auth_accounts SET password_hash='changed' WHERE id=1");assert.match(run(f,'after').stderr,/auth_accounts fingerprint changed|Account identity/)})
test('postflight rejects malformed or foreign snapshots without writing either database',()=>{for(const mutateSnapshot of [s=>{s.formatVersion=999},s=>{s.databasePath='/missing/foreign.sqlite'},s=>{delete s.counts.customers},s=>{delete s.fingerprints.branches}]){const f=makeFixture();assert.equal(run(f).status,0);assert.equal(migrate(f).status,0);const before=fs.readFileSync(f.dbPath),snapshot=JSON.parse(fs.readFileSync(f.snapshot));mutateSnapshot(snapshot);fs.writeFileSync(f.snapshot,JSON.stringify(snapshot));assert.notEqual(run(f,'after').status,0);assert.deepEqual(fs.readFileSync(f.dbPath),before)}})
test('before rejects an unsafe existing snapshot directory without chmod or database writes',()=>{const f=makeFixture(),unsafe=path.join(f.dir,'shared');fs.mkdirSync(unsafe,{mode:0o755});fs.chmodSync(unsafe,0o755);f.snapshot=path.join(unsafe,'before.json');const bytes=fs.readFileSync(f.dbPath),mode=fs.statSync(unsafe).mode&0o777;assert.match(run(f).stderr,/private/);assert.equal(fs.statSync(unsafe).mode&0o777,mode);assert.deepEqual(fs.readFileSync(f.dbPath),bytes);assert.equal(fs.existsSync(f.snapshot),false)})
test('runbook fixes health port, privilege boundaries and target-checkout ordering',()=>{const script=fs.readFileSync(path.join(root,'scripts/deploy-v42.sh'),'utf8'),doc=fs.readFileSync(path.join(root,'docs/DEPLOY_V42_CUSTOMER_PRICING.md'),'utf8');assert.match(script,/KCS_INTERNAL_HEALTH/);assert.match(script,/KCS_HTTPS_HEALTH/);assert.match(script,/git rev-parse HEAD/);assert.ok(script.indexOf('git rev-parse HEAD')<script.indexOf('cloud-preflight.mjs --mode before'));assert.ok(script.indexOf('systemctl stop')<script.indexOf('migrate-v42.mjs'));assert.match(doc,/Do not split the command across lines/)})
test('historical v17 document retains the baseline operational material',()=>{const historical=fs.readFileSync(path.join(root,'docs/PRELAUNCH_V17.md'),'utf8');assert.ok(historical.split('\n').length>200);for(const heading of ['## 目的与代码变更','## 重要环境区别','## 权限与安全影响','## 数据库变更与兼容','## Ubuntu 完整回滚','## 常见错误'])assert.match(historical,new RegExp(heading));assert.match(historical,/Historical command block/);assert.match(historical,/migrate:v16-to-v17/)})
