import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV29Migration} from '../server/migrationV29.mjs'
import {canViewVehicleDocuments,roleCan} from '../server/authService.mjs'
import {updateVehicle} from '../server/resourceService.mjs'
import {addVehicleDocument,replaceVehicleDocument,vehicleDocumentFile} from '../server/vehicleService.mjs'
import {applyVehicleMasterV29} from '../server/vehicleMasterV29Data.mjs'
import {assertVehicleRegistrationEdit,vehicleRegistrationFieldsInPayload} from '../server/vehicleRegistrationPermissions.mjs'

const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAB'
function legacy(){const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;CREATE TABLE schema_meta(version INTEGER PRIMARY KEY,applied_at TEXT DEFAULT CURRENT_TIMESTAMP);INSERT INTO schema_meta(version) VALUES(28);CREATE TABLE auth_accounts(id INTEGER PRIMARY KEY);CREATE TABLE vehicles(id INTEGER PRIMARY KEY,registration_number TEXT,capacity_kg REAL,operational_status TEXT);CREATE TABLE dispatches(id INTEGER PRIMARY KEY,vehicle_id INTEGER);CREATE TABLE dispatch_stops(id INTEGER PRIMARY KEY,vehicle_id INTEGER);CREATE TABLE vehicle_documents(id INTEGER PRIMARY KEY,vehicle_id INTEGER,document_type TEXT,title TEXT,storage_key TEXT UNIQUE,original_name TEXT,content_type TEXT,size_bytes INTEGER,document_date TEXT,expiry_date TEXT,uploaded_by TEXT,uploaded_at TEXT DEFAULT CURRENT_TIMESTAMP);INSERT INTO vehicles VALUES(1,'QAV3468',3000,'active')`);return db}
function current(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;'+schemaSql+'CREATE TABLE vehicle_document_audit(id INTEGER PRIMARY KEY AUTOINCREMENT,vehicle_id INTEGER NOT NULL REFERENCES vehicles(id),document_id INTEGER NOT NULL REFERENCES vehicle_documents(id),previous_document_id INTEGER REFERENCES vehicle_documents(id),action TEXT NOT NULL,document_type TEXT NOT NULL,sha256 TEXT NOT NULL,actor_account_id INTEGER REFERENCES auth_accounts(id),actor_name TEXT NOT NULL,remark TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE UNIQUE INDEX vehicle_document_current_uq ON vehicle_documents(vehicle_id,document_type) WHERE is_current=1;CREATE UNIQUE INDEX vehicle_document_version_uq ON vehicle_documents(vehicle_id,document_type,version_number)');db.prepare("INSERT INTO vehicles(vehicle_code,registration_number,capacity_kg,operational_status) VALUES('Lorry 1','QAV3468',3000,'active')").run();return db}

test('v28 to v29 is transactional, preserves vehicle/dispatch values and second run is no-op',()=>{const db=legacy(),first=applyV29Migration(db),second=applyV29Migration(db),row=db.prepare('SELECT registration_number,capacity_kg,operational_status FROM vehicles').get();assert.equal(first.schemaVersion,29);assert.equal(second.noOp,true);assert.equal(row.registration_number,'QAV3468');assert.equal(row.capacity_kg,3000);assert.equal(row.operational_status,'active');for(const name of ['registered_owner','fuel_type','engine_capacity_cc','vehicle_origin','vehicle_class'])assert.ok(db.prepare('PRAGMA table_info(vehicles)').all().some(item=>item.name===name));assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})

test('vehicle fields remain independent, protected identity conflicts stop, and before/after audit is recorded',()=>{const db=current();updateVehicle(1,{registeredOwner:'LEE SAI KER ENTERPRISE',fuelType:'Diesel',engineCapacityCc:4009,vehicleOrigin:'PEMASANGAN TEMPATAN',vehicleClass:'BRG-RIGID',grossVehicleWeightKg:5000,unladenWeightKg:2950,reason:'JPJ card',changedBy:'kcadmin'},db);const row=db.prepare('SELECT * FROM vehicles WHERE id=1').get();assert.equal(row.capacity_kg,3000);assert.equal(row.gross_vehicle_weight_kg,5000);assert.equal(row.unladen_weight_kg,2950);const audit=db.prepare("SELECT * FROM master_change_history WHERE entity_type='vehicle'").get();assert.equal(JSON.parse(audit.before_json).registered_owner,null);assert.equal(JSON.parse(audit.after_json).registered_owner,'LEE SAI KER ENTERPRISE');assert.throws(()=>updateVehicle(1,{registeredOwner:'WRONG OWNER'},db),/conflicts/);assert.throws(()=>updateVehicle(1,{registrationNumber:'QM6305'},db),/conflicts/)})

test('QAA4293N owner and QM630S plate cannot be silently overwritten',()=>{const db=current();db.prepare("INSERT INTO vehicles(vehicle_code,registration_number,registered_owner,operational_status) VALUES('Lorry 2','QAA4293N','EAZY GARLIC ENTERPRISE','active'),('Lorry 6','QM630S','LEE SAI KER ENTERPRISE','active')").run();assert.throws(()=>updateVehicle(2,{registeredOwner:'LEE SAI KER ENTERPRISE'},db),/Registered owner conflicts/);assert.throws(()=>updateVehicle(3,{registrationNumber:'QM6305'},db),/Registration plate conflicts/);assert.equal(db.prepare('SELECT registered_owner owner FROM vehicles WHERE id=2').get().owner,'EAZY GARLIC ENTERPRISE');assert.equal(db.prepare('SELECT registration_number plate FROM vehicles WHERE id=3').get().plate,'QM630S')})

test('controlled master write updates six vehicles atomically and preserves codes, plates, capacity and sold history',()=>{const db=current();db.prepare('INSERT INTO schema_meta(version) VALUES(29)').run();db.exec("DELETE FROM vehicles;INSERT INTO vehicles(id,vehicle_code,registration_number,capacity_kg,operational_status) VALUES(1,'Lorry 1','QAV3468',NULL,'available'),(2,'Lorry 2','QAA4293N',NULL,'active'),(3,'Lorry 3','QAB1225B',NULL,'active'),(4,'Lorry 4','QM3028M',3000,'active'),(5,'Lorry 5','QTY5028',3000,'active'),(8,'Lorry 6','QM630S',3000,'active'),(9,'Former Vehicle','QTW2704',NULL,'sold');UPDATE vehicles SET sold_at='2026-07-21 04:31:14' WHERE id=9");const first=applyVehicleMasterV29(db,{actorName:'deployment:v29-authorized'}),second=applyVehicleMasterV29(db,{actorName:'deployment:v29-authorized'});assert.equal(first.vehiclesUpdated,6);assert.equal(first.auditsAdded,6);assert.equal(second.noOp,true);assert.equal(db.prepare('SELECT registered_owner value FROM vehicles WHERE id=2').get().value,'EAZY GARLIC ENTERPRISE');assert.equal(db.prepare('SELECT registration_number value FROM vehicles WHERE id=8').get().value,'QM630S');assert.equal(db.prepare('SELECT capacity_kg value FROM vehicles WHERE id=4').get().value,3000);assert.equal(db.prepare('SELECT operational_status value FROM vehicles WHERE id=9').get().value,'sold')})

test('office roles can view documents, drivers cannot, and view does not grant management',()=>{for(const role of ['owner_admin','operations_admin','supervisor','office'])assert.equal(canViewVehicleDocuments({role}),true);for(const role of ['driver','crew'])assert.equal(canViewVehicleDocuments({role}),false);assert.equal(roleCan('owner_admin','vehicle_manage'),true);assert.equal(roleCan('office','vehicle_manage'),false);assert.equal(roleCan('supervisor','vehicle_manage'),false)})

test('document upload validates content, hashes, versions and preserves exactly one current version',()=>{const db=current(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'kcs-v29-'));try{const first=addVehicleDocument(1,{documentType:'road_tax',file:{name:'road-tax.png',dataUrl:png},remark:'first',uploadedBy:'forged'},{username:'real-admin'},db,dir);assert.equal(first.versionNumber,1);assert.equal(first.uploadedBy,'real-admin');assert.equal(first.sha256.length,64);const file=vehicleDocumentFile(first.id,db,dir);assert.equal(file.contentType,'image/png');const second=replaceVehicleDocument(first.id,{file:{name:'road-tax.png',dataUrl:png},remark:'renewed'},{username:'real-admin'},db,dir);assert.equal(second.versionNumber,2);assert.equal(db.prepare('SELECT COUNT(*) n FROM vehicle_documents WHERE is_current=1').get().n,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM vehicle_document_audit').get().n,2);assert.throws(()=>replaceVehicleDocument(first.id,{file:{name:'again.png',dataUrl:png}},{},db,dir),/not found/);assert.throws(()=>addVehicleDocument(1,{documentType:'other',file:{name:'../bad.png',dataUrl:png}},{},db,dir),/unsafe/);assert.throws(()=>addVehicleDocument(1,{documentType:'other',file:{name:'bad.jpg',dataUrl:png}},{},db,dir),/extension/);assert.throws(()=>addVehicleDocument(1,{documentType:'other',file:{name:'bad.png',dataUrl:'data:image/png;base64,AAAA'}},{},db,dir),/content/);const oversized=`data:image/png;base64,${Buffer.alloc(8*1024*1024+1).toString('base64')}`;assert.throws(()=>addVehicleDocument(1,{documentType:'other',file:{name:'large.png',dataUrl:oversized}},{},db,dir),/8 MB/)}finally{fs.rmSync(dir,{recursive:true,force:true})}})

test('document DB or audit failure rolls back metadata and removes the newly written file',()=>{const db=current(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'kcs-v29-fail-'));try{db.exec('DROP TABLE vehicle_document_audit');assert.throws(()=>addVehicleDocument(1,{documentType:'insurance',file:{name:'insurance.png',dataUrl:png}},{username:'admin'},db,dir));assert.equal(db.prepare('SELECT COUNT(*) n FROM vehicle_documents').get().n,0);const folder=path.join(dir,'vehicles','1');assert.equal(fs.existsSync(folder)?fs.readdirSync(folder).length:0,0)}finally{fs.rmSync(dir,{recursive:true,force:true})}})

test('vehicle document routes enforce office view and vehicle_manage write permissions',()=>{const source=fs.readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../src/VehicleDetailPage.jsx',import.meta.url),'utf8');assert.match(source,/canViewVehicleDocuments\(session\)/);assert.match(source,/vehicle-documents.*preview\|download/);assert.match(source,/accountCan\(session,'vehicle_manage'\)/);assert.match(source,/Content-Disposition/);assert.match(source,/X-Content-Type-Options/);assert.match(ui,/ownership_certificate/);assert.doesNotMatch(ui,/image\/webp,image\/png,application\/pdf/)})

test('only owner_admin may edit registration fields and reason is mandatory',()=>{const payload={registeredOwner:'Owner',reason:'Verified JPJ card'};assert.deepEqual(vehicleRegistrationFieldsInPayload(payload),['registeredOwner']);assert.doesNotThrow(()=>assertVehicleRegistrationEdit({role:'owner_admin'},payload));for(const role of ['operations_admin','supervisor','office','driver','crew']){const db=current(),before=db.prepare('SELECT registered_owner,capacity_kg FROM vehicles WHERE id=1').get();let error;try{assertVehicleRegistrationEdit({role,permissions:['vehicle_manage']},{registeredOwner:'Forbidden',capacityKg:9999,reason:'Attempt'});updateVehicle(1,{registeredOwner:'Forbidden',capacityKg:9999,reason:'Attempt'},db)}catch(item){error=item}assert.equal(error?.statusCode,403);const after=db.prepare('SELECT registered_owner,capacity_kg FROM vehicles WHERE id=1').get();assert.equal(after.registered_owner,before.registered_owner);assert.equal(after.capacity_kg,before.capacity_kg)}let missing;try{assertVehicleRegistrationEdit({role:'owner_admin'},{model:'HINO'})}catch(item){missing=item}assert.equal(missing?.statusCode,400);assert.doesNotThrow(()=>assertVehicleRegistrationEdit({role:'operations_admin',permissions:['vehicle_manage']},{operationalStatus:'maintenance',reason:'Workshop'}))})

test('non-owner registration UI is explicit read-only while operational editing remains separate',()=>{const ui=fs.readFileSync(new URL('../src/VehicleDetailPage.jsx',import.meta.url),'utf8'),apiSource=fs.readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8');assert.equal(ui.includes('readOnly={!isOwnerAdmin}'),true);assert.match(ui,/only the Owner Administrator may change vehicle registration details/);assert.match(ui,/Save Registration Changes/);assert.match(ui,/Save Operational Details/);assert.match(apiSource,/assertVehicleRegistrationEdit\(session,payload\)/)})
