import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {DatabaseSync} from 'node:sqlite'
import {schemaSql} from '../server/schema.mjs'
import {applyV37Migration} from '../server/migrationV37.mjs'
import {listZoneDefaultVehicles,setZoneDefaultVehicles} from '../server/defaultVehicleService.mjs'
import {generateDay,getDispatchDay} from '../server/dispatchService.mjs'

function fixture(){const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;${schemaSql}`);db.prepare('INSERT INTO schema_meta(version) VALUES(37)').run();db.prepare("INSERT INTO vehicles(id,vehicle_code,registration_number,status,operational_status,is_temporary) VALUES(1,'Lorry 1','QAV3468','available','active',0),(2,'Lorry 2','QAA4293N','available','active',0),(3,'Lorry 3','QAB1225B','assigned','available',0),(4,'Sold','QTW2704','inactive','sold',0)").run();db.prepare("INSERT INTO customers(id,jodoo_customer_id,name) VALUES(1,'C1','Alpha')").run();db.prepare("INSERT INTO areas(id,jodoo_area_id,name,zone_group_id,confirmed_zone_group_id,zone_assignment_status) VALUES(20,'A20','BDC',1,1,'confirmed')").run();db.prepare("INSERT INTO branches(id,jodoo_branch_id,customer_id,area_id,branch_name,is_active,collection_frequency) VALUES(30,'B30',1,20,'Alpha BDC',1,'Weekly')").run();db.prepare("INSERT INTO branch_schedules(id,jodoo_schedule_id,branch_id,source_branch_id,frequency,days_of_week,is_active) VALUES(40,'S40',30,'B30','Weekly','Monday',1)").run();return db}

test('v36 single Zone default migrates once into ordered v37 pool without protected count changes',()=>{const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;CREATE TABLE schema_meta(version INTEGER PRIMARY KEY);INSERT INTO schema_meta VALUES(36);CREATE TABLE vehicles(id INTEGER PRIMARY KEY);CREATE TABLE zone_groups(id INTEGER PRIMARY KEY,name TEXT,default_vehicle_id INTEGER);CREATE TABLE areas(id INTEGER PRIMARY KEY);CREATE TABLE dispatches(id INTEGER PRIMARY KEY);CREATE TABLE dispatch_stops(id INTEGER PRIMARY KEY);INSERT INTO vehicles VALUES(7);INSERT INTO zone_groups VALUES(1,'BDC',7);INSERT INTO areas VALUES(1);INSERT INTO dispatches VALUES(1);INSERT INTO dispatch_stops VALUES(1)`);const first=applyV37Migration(db),second=applyV37Migration(db);assert.equal(first.schemaVersion,37);assert.equal(first.migratedDefaults,1);assert.deepEqual(first.before,first.after);assert.equal(second.noOp,true);assert.deepEqual({...db.prepare('SELECT zone_group_id,vehicle_id,position FROM zone_default_vehicles').get()},{zone_group_id:1,vehicle_id:7,position:1});assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok')})

test('Zone pool accepts one, two and three unique active vehicles and blocks a fourth or duplicate',()=>{const db=fixture();for(const ids of [[1],[1,2],[1,2,3]]){const result=setZoneDefaultVehicles(1,{vehicleIds:ids,reason:'Approved pool',changedBy:'Supervisor'},db);assert.deepEqual(result.defaultVehicles.map(item=>item.id),ids)}assert.throws(()=>setZoneDefaultVehicles(1,{vehicleIds:[1,2,3,4],reason:'Too many',changedBy:'Supervisor'},db),/Maximum 3/);assert.throws(()=>setZoneDefaultVehicles(1,{vehicleIds:[1,1],reason:'Duplicate',changedBy:'Supervisor'},db),/same vehicle/);assert.deepEqual(listZoneDefaultVehicles(1,db).map(item=>item.id),[1,2,3])})

test('inactive vehicle cannot be newly assigned but an existing assignment remains visible as unavailable',()=>{const db=fixture();assert.throws(()=>setZoneDefaultVehicles(1,{vehicleIds:[4],reason:'Invalid',changedBy:'Supervisor'},db),/active dispatch vehicle/);setZoneDefaultVehicles(1,{vehicleIds:[1],reason:'Initial',changedBy:'Supervisor'},db);db.prepare("UPDATE vehicles SET operational_status='sold',status='inactive' WHERE id=1").run();const existing=listZoneDefaultVehicles(1,db)[0];assert.equal(existing.isAvailable,0);assert.equal(existing.registrationNumber,'QAV3468');setZoneDefaultVehicles(1,{vehicleIds:[],reason:'Remove unavailable',changedBy:'Supervisor'},db);assert.equal(listZoneDefaultVehicles(1,db).length,0)})

test('one default still assigns a new Draft while multi-default leaves one Branch unassigned and never duplicates it',()=>{const one=fixture();setZoneDefaultVehicles(1,{vehicleIds:[1],reason:'Single',changedBy:'Supervisor'},one);generateDay({startDate:'2026-08-17'},one);assert.equal(getDispatchDay('2026-08-17',one).stops[0].vehicleId,1);const multi=fixture();setZoneDefaultVehicles(1,{vehicleIds:[1,2],reason:'Pool',changedBy:'Supervisor'},multi);generateDay({startDate:'2026-08-17'},multi);const day=getDispatchDay('2026-08-17',multi);assert.equal(day.stops.length,1);assert.equal(day.unassignedStops.length,1);assert.deepEqual(day.unassignedZones[0].defaultVehicleIds,[1,2]);assert.equal(multi.prepare("SELECT COUNT(*) n FROM dispatch_stops WHERE branch_id=30 AND status<>'cancelled'").get().n,1)})

test('pool audit records ordered before/after, additions, removals, actor and reason',()=>{const db=fixture();setZoneDefaultVehicles(1,{vehicleIds:[1,2],reason:'Initial pool',changedBy:'Owner'},db);setZoneDefaultVehicles(1,{vehicleIds:[2,3],reason:'Vehicle rotation',changedBy:'Office Planner'},db);const audit=db.prepare("SELECT * FROM master_change_history WHERE change_type='default_vehicle_pool_changed' ORDER BY id DESC LIMIT 1").get();assert.equal(audit.changed_by,'Office Planner');assert.equal(audit.reason,'Vehicle rotation');assert.deepEqual(JSON.parse(audit.before_json),{vehicleIds:[1,2]});assert.deepEqual(JSON.parse(audit.after_json),{vehicleIds:[2,3],addedVehicleIds:[3],removedVehicleIds:[1]})})

test('Zone Card owns the pool UI and API authorization stays Session-based',()=>{const ui=fs.readFileSync(new URL('../src/ZoneGroupManager.jsx',import.meta.url),'utf8'),api=fs.readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8');for(const token of ['ZoneDefaultVehicles','defaultVehicle.plural','defaultVehicle.add','defaultVehicle.remove','defaultVehicle.unavailable','defaultVehicle.maximum'])assert.ok(ui.includes(token));assert.doesNotMatch(ui,/function DefaultVehicleAssignments/);assert.ok(api.includes("request.method === 'PUT'"));assert.ok(api.includes('default-vehicles'));assert.match(api,/canManageSchedules\(session\)/);assert.match(api,/changedBy:session\.employeeName/)})
