import crypto from 'node:crypto'
import {db as defaultDb} from './database.mjs'
import {calculateRecommendation,distanceMeters} from './gpsRecommendationService.mjs'
import {reverseGeocodeGoogle} from './googleGeocodingService.mjs'
import {formatBranchId,parseTypedId} from '../shared/typedIds.js'

const text=value=>String(value??'').trim()
const validGps=(lat,lon)=>Number.isFinite(Number(lat))&&Number(lat)>=-90&&Number(lat)<=90&&Number.isFinite(Number(lon))&&Number(lon)>=-180&&Number(lon)<=180&&!(Number(lat)===0&&Number(lon)===0)
const tokens=value=>[...new Set(text(value).toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(value=>value.length>=2))]
const postcodes=value=>tokens(value).filter(value=>/^\d{5}$/.test(value))
const processLocalPreviewSecret=crypto.randomBytes(32).toString('base64url')
const previewSecret=()=>process.env.KCS_ADDRESS_PREVIEW_SECRET||process.env.KCS_SESSION_SECRET||processLocalPreviewSecret
const sign=value=>crypto.createHmac('sha256',previewSecret()).update(value).digest('base64url')
const encode=value=>{const body=Buffer.from(JSON.stringify(value)).toString('base64url');return `${body}.${sign(body)}`}
const decode=value=>{const [body,signature]=text(value).split('.');if(!body||!signature||signature.length!==sign(body).length||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(sign(body))))throw new Error('Address preview expired or is invalid; preview again');const data=JSON.parse(Buffer.from(body,'base64url'));if(data.expiresAt<Date.now())throw new Error('Address preview expired; preview again');return data}
const structured=row=>({state:text(row.gps_state),city:text(row.gps_city),street:text(row.gps_street),streetNumber:text(row.gps_street_number),postcode:text(row.gps_postal_code)})
const incomplete=row=>{const address=text(row.address),parts=tokens(address);return Boolean(address)&&(!/[a-z]/i.test(address)||/^\+?[23456789cfghjmpqrvwx]{4,}\+?[23456789cfghjmpqrvwx]{2,}$/i.test(address.replace(/\s/g,''))||parts.length<3||(!structured(row).street&&!postcodes(address).length))}
function matchesLatestAddressAudit(row){if(!row.review_after_json)return false;let after;try{after=JSON.parse(row.review_after_json)}catch{return false}if(!after||typeof after!=='object')return false;return text(row.address)===text(after.address)&&text(row.gps_address)===text(after.gps_address)&&text(row.gps_state)===text(after.gps_state)&&text(row.gps_street)===text(after.gps_street)&&text(row.gps_city)===text(after.gps_city)&&text(row.gps_street_number)===text(after.gps_street_number)&&text(row.gps_postal_code)===text(after.gps_postal_code)}

function nearby(database,row){if(!validGps(row.latitude,row.longitude))return[];return database.prepare(`SELECT b.id,b.jodoo_branch_id branchId,b.branch_name branchName,b.latitude,b.longitude,b.area_id areaId,a.name areaName FROM branches b JOIN areas a ON a.id=b.area_id WHERE b.id<>? AND b.lifecycle_status='ACTIVE' AND b.is_active=1 AND LOWER(COALESCE(b.status,'active'))='active' AND b.area_id IS NOT NULL AND a.is_active=1 AND a.confirmed_zone_group_id IS NOT NULL AND a.zone_assignment_status='confirmed' AND b.latitude BETWEEN -90 AND 90 AND b.longitude BETWEEN -180 AND 180 AND NOT(b.latitude=0 AND b.longitude=0)`).all(row.id).map(item=>({...item,branchId:formatBranchId(item.branchId),distanceMeters:Math.round(distanceMeters({lat:Number(row.latitude),lng:Number(row.longitude)},{lat:Number(item.latitude),lng:Number(item.longitude)}))})).sort((a,b)=>a.distanceMeters-b.distanceMeters).slice(0,3)}

function view(database,row){
  const official=validGps(row.latitude,row.longitude),recommendation=calculateRecommendation(row.id,database),addressTokens=tokens(`${row.address} ${Object.values(structured(row)).join(' ')}`),areaCandidates=database.prepare(`SELECT id,name,confirmed_zone_group_id zoneGroupId FROM areas WHERE is_active=1 AND confirmed_zone_group_id IS NOT NULL AND zone_assignment_status='confirmed'`).all().map(area=>({...area,matchedTokens:tokens(area.name).filter(token=>addressTokens.includes(token))})).filter(area=>area.matchedTokens.length).sort((a,b)=>b.matchedTokens.length-a.matchedTokens.length).slice(0,5),pending=database.prepare("SELECT id,latitude,longitude,verification_status verificationStatus FROM temporary_locations WHERE branch_id=? AND COALESCE(review_decision,'')<>'approved' ORDER BY id DESC LIMIT 1").get(row.id)||null,near=nearby(database,row),conflicts=[...(recommendation.reason?.conflicts||[])],proposedAreaId=recommendation.recommendedAreaId
  if(postcodes(row.address).length&&row.gps_postal_code&&!postcodes(row.address).includes(text(row.gps_postal_code)))conflicts.push('postcode_conflict')
  const strong=[areaCandidates[0]?.id===proposedAreaId?'address_area_tokens':null].filter(Boolean),manual=!official||conflicts.length>0||recommendation.boundaryConflict||recommendation.matchType==='boundary'||strong.length<2,confidence=strong.length?'medium':'low',reviewed=matchesLatestAddressAudit(row)
  let bucket='ready_review';if(!text(row.address))bucket=official?'missing_with_gps':'missing_without_gps';else if(incomplete(row))bucket='incomplete';else if(conflicts.length||proposedAreaId&&proposedAreaId!==row.area_id)bucket='evidence_conflict';else if(reviewed)bucket='reviewed_unchanged'
  return{internalBranchId:row.id,branchId:formatBranchId(row.jodoo_branch_id),branchName:row.branch_name||'',customerId:row.jodoo_customer_id||'',customerName:row.customer_name||'',lifecycle:row.lifecycle_status,currentAreaId:row.area_id,currentArea:row.area_name||'',currentZoneId:row.zone_id,currentZone:row.zone_name||'',address:row.address||'',structuredAddress:structured(row),officialGps:{available:official,latitude:official?row.latitude:null,longitude:official?row.longitude:null,status:row.gps_status||'',source:row.gps_reverse_geocode_provider||'Official Branch GPS'},pendingGps:pending?{...pending,ignored:true,explanation:'Pending GPS is shown separately and is never address or Area proof.'}:null,addressEvidence:{tokens:addressTokens,postcodes:postcodes(`${row.address} ${row.gps_postal_code}`),areaCandidates},nearbyBranches:near,zoneEvidence:{matchType:recommendation.matchType,polygonStatus:recommendation.reason?.polygonStatus||'unavailable',zoneOnly:true,explanation:'A Zone polygon can support Zone membership only; it never proves a child Area.'},proposedAddress:row.gps_address?{address:row.gps_address,...structured(row),source:row.gps_reverse_geocode_provider||'saved official GPS address'}:null,proposedArea:{id:proposedAreaId,name:recommendation.reason?.recommendedAreaName||null,confidence,independentEvidence:strong,conflicts,manualReviewRequired:manual,explanation:recommendation.reason?.summary||'No safe Area recommendation is available.',recommendationId:row.recommendation_id||null},bucket,reviewed}
}

const baseSelect=`SELECT b.*,c.jodoo_customer_id,c.name customer_name,a.name area_name,COALESCE(a.confirmed_zone_group_id,a.zone_group_id) zone_id,z.name zone_name,r.id recommendation_id,r.status recommendation_status,(SELECT h.after_json FROM master_change_history h WHERE h.entity_type='branch' AND h.entity_id=b.jodoo_branch_id AND h.change_type='address_analysis_address_updated' ORDER BY h.id DESC LIMIT 1) review_after_json FROM branches b LEFT JOIN customers c ON c.id=b.customer_id LEFT JOIN areas a ON a.id=b.area_id LEFT JOIN zone_groups z ON z.id=COALESCE(a.confirmed_zone_group_id,a.zone_group_id) LEFT JOIN gps_zone_recommendations r ON r.branch_id=b.id WHERE b.lifecycle_status='ACTIVE' AND b.is_active=1 AND LOWER(COALESCE(b.status,'active'))='active'`
export function listAddressAnalysis(params={},database=defaultDb){let rows=database.prepare(`${baseSelect} ORDER BY b.branch_name,b.id`).all(),items=rows.map(row=>view(database,row));const search=text(params.search);if(search){let raw='';try{raw=parseTypedId(search,'branch')}catch{}const needle=search.toLowerCase();items=items.filter(item=>[item.branchId,raw,item.branchName,item.customerId,item.customerName,item.currentArea,item.address,item.structuredAddress.postcode].some(value=>text(value).toLowerCase().includes(needle))||raw&&item.branchId===formatBranchId(raw))}const counts={missing_with_gps:0,missing_without_gps:0,incomplete:0,evidence_conflict:0,ready_review:0,reviewed_unchanged:0};for(const item of rows.map(row=>view(database,row)))counts[item.bucket]++;if(params.bucket&&counts[params.bucket]!==undefined)items=items.filter(item=>item.bucket===params.bucket);return{readOnly:true,noBulkWrites:true,reviewLaterPersistence:'session-only',counts,total:items.length,items}}
export function getAddressAnalysis(branchId,database=defaultDb){let raw;try{raw=parseTypedId(branchId,'branch')}catch{throw Object.assign(new Error('Invalid Branch ID'),{statusCode:400})}const row=database.prepare(`${baseSelect} AND b.jodoo_branch_id=?`).get(raw);if(!row)throw Object.assign(new Error('Active Branch not found'),{statusCode:404});return view(database,row)}
export async function previewAddress(branchId,{geocoder=reverseGeocodeGoogle,previewTtlMs=15*60_000}={},database=defaultDb){const item=getAddressAnalysis(branchId,database);if(!item.officialGps.available)throw Object.assign(new Error('Official GPS is required for address preview; Pending GPS is ignored'),{statusCode:400});const found=await geocoder(item.officialGps.latitude,item.officialGps.longitude),candidate={address:text(found.address),state:text(found.state),city:text(found.city||found.locality),street:text(found.street||found.road),streetNumber:text(found.streetNumber),postcode:text(found.postalCode),provider:text(found.provider)||'Google Geocoding API'};if(!candidate.address)throw Object.assign(new Error('Reverse geocoding returned no usable address; the Branch remains unchanged'),{statusCode:422});const payload={branchId:item.internalBranchId,latitude:item.officialGps.latitude,longitude:item.officialGps.longitude,candidate,expiresAt:Date.now()+previewTtlMs};return{candidate,previewOnly:true,proof:false,explanation:'Reverse geocoding is a preview candidate, not proof. A supervisor must confirm it with a reason.',previewToken:encode(payload)}}
export function useSuggestedAddress(branchId,{previewToken,reason,changedBy}={},database=defaultDb){const why=text(reason),actor=text(changedBy);if(!why)throw new Error('A supervisor reason is required');if(!actor)throw new Error('Authenticated actor is required');const item=getAddressAnalysis(branchId,database),preview=decode(previewToken);if(preview.branchId!==item.internalBranchId||preview.latitude!==item.officialGps.latitude||preview.longitude!==item.officialGps.longitude)throw new Error('Branch or Official GPS changed after preview; preview again');const candidate=preview.candidate;if(!text(candidate?.address))throw new Error('Suggested address is empty or invalid; preview again');const before=database.prepare('SELECT address,gps_address,gps_state,gps_street,gps_city,gps_street_number,gps_postal_code,gps_reverse_geocode_provider,latitude,longitude,area_id,customer_id FROM branches WHERE id=?').get(item.internalBranchId),after={...before,address:text(candidate.address),gps_address:text(candidate.address),gps_state:text(candidate.state),gps_street:text(candidate.street),gps_city:text(candidate.city),gps_street_number:text(candidate.streetNumber),gps_postal_code:text(candidate.postcode),gps_reverse_geocode_provider:text(candidate.provider)};database.exec('BEGIN IMMEDIATE');try{database.prepare('UPDATE branches SET address=?,gps_address=?,gps_state=?,gps_street=?,gps_city=?,gps_street_number=?,gps_postal_code=?,gps_reverse_geocode_provider=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(after.address,after.gps_address,after.gps_state,after.gps_street,after.gps_city,after.gps_street_number,after.gps_postal_code,after.gps_reverse_geocode_provider,item.internalBranchId);database.prepare(`INSERT INTO master_change_history(entity_type,entity_id,change_type,field_name,before_json,after_json,reason,changed_by) VALUES('branch',?,'address_analysis_address_updated','address',?,?,?,?)`).run(item.branchId.slice(1),JSON.stringify(before),JSON.stringify(after),why,actor);database.exec('COMMIT')}catch(error){database.exec('ROLLBACK');throw error}return getAddressAnalysis(branchId,database)}
