import {db as defaultDb} from './database.mjs'
import {reverseGeocodeGoogle} from './googleGeocodingService.mjs'

const text=value=>String(value??'').trim()
const normalizeName=value=>text(value).toLowerCase().replace(/\bjln\b/g,'jalan').replace(/\blrg\b/g,'lorong').replace(/[^\p{L}\p{N}]+/gu,' ').replace(/\s+/g,' ').trim().replace(/^(jalan|lorong)\s+/,'')
const displayName=value=>text(value).replace(/^jln\b/i,'Jalan').replace(/^lrg\b/i,'Lorong')
const hasGps=row=>Number.isFinite(row.latitude)&&Number.isFinite(row.longitude)&&!(row.latitude===0&&row.longitude===0)
const actor=value=>text(value)||'KCS User'
const round=value=>Math.round(Number(value)*1e7)/1e7
const buildingPattern=/\b(aeon|mall|plaza|wisma|boulevard|podium|city\s*one|viva\s*city|commercial centre|shopping centre|shopping center)\b/i
const broadLocationPattern=/^(?:batu|bt)\s*\d+$/i
const genericLocationPattern=/^(?:kuching|sarawak|malaysia)$/i
const microRoadPattern=/^(?:lorong|lane)\b/i
const knownMajorCorridorPattern=/\bjalan\s+penrissen\b/i

function distanceKm(a,b){const rad=Math.PI/180,dLat=(b.latitude-a.latitude)*rad,dLon=(b.longitude-a.longitude)*rad,lat1=a.latitude*rad,lat2=b.latitude*rad,x=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function candidateName(result,preferLocality=false){const locality=text(result.sublocality||result.neighborhood);if(preferLocality&&locality&&!/^kuching$/i.test(locality))return displayName(locality);return displayName(result.road||result.street||(preferLocality?locality:'')||result.locality||result.city||'')}
function sameArea(a,b){return normalizeName(a)===normalizeName(b)}
export function normalizeBatuContext(value){return text(value)
  .replace(/\b(?:bt|batu)\s*0*(\d+)\b/ig,(_match,number)=>`BATU ${Number(number)}`)
  .replace(/\b0*(\d+)(?:st|nd|rd|th)?\s*mile\b/ig,(_match,number)=>`BATU ${Number(number)}`)
  .replace(/\bmile\s*0*(\d+)\b/ig,(_match,number)=>`BATU ${Number(number)}`)}
export function extractBatuSegments(...values){const found=new Set();for(const value of values){for(const match of normalizeBatuContext(value).matchAll(/\bBATU\s+(\d+)\b/ig))found.add(`BATU ${Number(match[1])}`)}return[...found]}
export function isMajorRoadCorridor(value){return knownMajorCorridorPattern.test(text(value))}
function compact(value){return normalizeName(value).replace(/\s+/g,'')}
function branchAreaHint(branch,existingAreas){const name=normalizeBatuContext(branch.branchName),normalized=compact(name),matches=existingAreas.filter(area=>!broadLocationPattern.test(area.name)&&normalized.includes(compact(area.name))).sort((a,b)=>b.name.length-a.name.length);if(matches[0])return matches[0].name;const building=name.match(/\b(?:AEON(?:\s+MALL)?|PODIUM|CITY\s*ONE|VIVA\s*CITY|(?:[A-Z0-9]+\s+){0,2}WISMA|BOULEVARD|PLAZA(?:\s+[A-Z0-9]+){0,2})\b/i)?.[0];if(!building)return'';if(/^aeon$/i.test(building)&&/aeon/i.test(branch.currentAreaName))return branch.currentAreaName;return displayName(building.toUpperCase())}
function branchBatuSegments(branch){return extractBatuSegments(branch.branchName,branch.address,branch.gpsAddress,branch.geocode.address,branch.geocode.road,branch.geocode.street,branch.geocode.sublocality,branch.geocode.neighborhood)}
function reliableLocation(branch,existingAreas,validatedBuilding='',majorCorridors=new Set()){const hint=validatedBuilding||branchAreaHint(branch,existingAreas),sub=text(branch.geocode.sublocality||branch.geocode.neighborhood),road=displayName(branch.geocode.road||branch.geocode.street),current=text(branch.currentAreaName),segments=branchBatuSegments(branch),roadKey=normalizeName(road),corridor=isMajorRoadCorridor(road)||majorCorridors.has(roadKey);if(segments.length>1)return{name:'',kind:'conflicting_segment',confidence:'needs_review',reason:`Conflicting BATU mile segments were found: ${segments.join(', ')}.`};if(hint)return{name:hint,kind:buildingPattern.test(hint)?'building':'existing',confidence:'high'};if(sub&&!genericLocationPattern.test(sub)&&!microRoadPattern.test(sub))return{name:displayName(sub),kind:buildingPattern.test(sub)?'building':'named_locality',confidence:'high'};if(road&&!microRoadPattern.test(road)&&!corridor)return{name:road,kind:'main_road',confidence:'medium'};if(segments[0])return{name:segments[0],kind:'batu_segment',confidence:'medium'};if(current&&!broadLocationPattern.test(current))return{name:current,kind:'existing_fallback',confidence:'medium'};return{name:'',kind:corridor?'major_corridor':'uncertain',confidence:'needs_review',reason:corridor?'Only a major road corridor is available; a more specific operational location is required.':'No reliable operational location could be identified.'}}

async function concurrentMap(items,limit,mapper){const output=new Array(items.length);let cursor=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(cursor<items.length){const index=cursor++;output[index]=await mapper(items[index],index)}}));return output}

function areaBranchRows(areaId,includeExisting,database){
  const childIds=database.prepare('SELECT child_area_id id FROM area_refinement_children WHERE parent_area_id=?').all(areaId).map(row=>row.id)
  const ids=includeExisting?[areaId,...childIds]:[areaId],marks=ids.map(()=>'?').join(',')
  return database.prepare(`SELECT b.id,b.jodoo_branch_id branchId,b.branch_name branchName,b.address,b.latitude,b.longitude,b.gps_address gpsAddress,b.gps_street savedRoad,b.gps_city savedLocality,b.area_id currentAreaId,a.name currentAreaName,c.jodoo_customer_id customerId,c.name customerName FROM branches b LEFT JOIN areas a ON a.id=b.area_id LEFT JOIN customers c ON c.id=b.customer_id WHERE b.is_active=1 AND b.status='active' AND b.area_id IN (${marks}) ORDER BY COALESCE(b.branch_name,''),b.id`).all(...ids)
}

function confirmedZoneBranchIds(zoneId,database){return new Set(database.prepare(`SELECT DISTINCT s.branch_id id FROM area_refinement_suggestions s JOIN area_refinement_analyses ar ON ar.id=s.analysis_id WHERE ar.scope_type='zone' AND ar.zone_group_id=? AND ar.status='confirmed' AND s.action<>'need_gps'`).all(zoneId).map(row=>row.id))}
function zoneBranchRows(zoneId,includeExisting,database){
  const stable=includeExisting?new Set():confirmedZoneBranchIds(zoneId,database)
  return database.prepare(`SELECT b.id,b.jodoo_branch_id branchId,b.branch_name branchName,b.address,b.latitude,b.longitude,b.gps_address gpsAddress,b.gps_street savedRoad,b.gps_city savedLocality,b.area_id currentAreaId,a.name currentAreaName,c.jodoo_customer_id customerId,c.name customerName FROM branches b JOIN areas a ON a.id=b.area_id LEFT JOIN customers c ON c.id=b.customer_id WHERE b.is_active=1 AND b.status='active' AND a.is_active=1 AND COALESCE(a.confirmed_zone_group_id,a.zone_group_id)=? ORDER BY COALESCE(a.name,''),COALESCE(b.branch_name,''),b.id`).all(zoneId).filter(row=>!stable.has(row.id)||!hasGps(row))
}

function groupAreaItems(items){
  const grouped=new Map()
  for(const item of items.filter(row=>row.action==='move')){const key=normalizeName(item.proposedAreaName);if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(item)}
  const stable=[...grouped.values()].filter(group=>group.length>=2)
  for(const group of grouped.values()){
    if(group.length>=2){const confidence=group.length>=3?'high':'medium',canonical=[...new Set(group.map(item=>item.proposedAreaName))].sort((a,b)=>(/^Jalan\b/i.test(b)?1:0)-(/^Jalan\b/i.test(a)?1:0)||a.localeCompare(b))[0];for(const item of group){item.proposedAreaName=canonical;item.confidence=confidence;item.reason=`${group.length} official GPS records share the normalized road/locality “${canonical}”.`};continue}
    const item=group[0],near=stable.map(candidate=>({candidate,distance:Math.min(...candidate.map(row=>distanceKm(item,row)))})).filter(row=>row.distance<=1.5).sort((a,b)=>a.distance-b.distance)[0]
    if(near){item.proposedAreaName=near.candidate[0].proposedAreaName;item.confidence='medium';item.reason=`Sparse GPS point merged with the nearest stable road/locality group (${near.distance.toFixed(2)} km).`}
    else{item.action='needs_review';item.confidence='needs_review';item.reason='Only one usable GPS point supports this subdivision; manual review is required to avoid over-splitting.'}
  }
  return items
}

function groupZoneItems(items,existingAreas){
  const gps=items.filter(hasGps),grouped=new Map(),roadSegments=new Map(),buildingSeeds=gps.map(item=>({item,hint:branchAreaHint(item,existingAreas),segments:branchBatuSegments(item)})).filter(row=>buildingPattern.test(row.hint))
  for(const item of gps){const road=displayName(item.geocode.road||item.geocode.street),key=normalizeName(road),segments=branchBatuSegments(item);if(!key||!segments.length)continue;if(!roadSegments.has(key))roadSegments.set(key,new Set());for(const segment of segments)roadSegments.get(key).add(segment)}
  const majorCorridors=new Set([...roadSegments].filter(([,segments])=>segments.size>1).map(([road])=>road))
  for(const item of gps){const itemSegments=branchBatuSegments(item),seed=buildingSeeds.filter(row=>row.item.currentAreaId===item.currentAreaId&&distanceKm(row.item,item)<=0.15&&(!row.segments.length||!itemSegments.length||row.segments.some(segment=>itemSegments.includes(segment)))).sort((a,b)=>distanceKm(a.item,item)-distanceKm(b.item,item))[0],location=reliableLocation(item,existingAreas,seed?.hint||'',majorCorridors);item.proposedAreaName=location.name;item.locationKind=location.kind;item.confidence=location.confidence;if(!location.name){item.action='needs_review';item.reason=location.reason||'Only a micro road, broad BATU context, or conflicting location evidence is available; manual review is required.';continue}const key=normalizeName(location.name);if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(item)}
  for(const group of grouped.values()){
    const canonical=[...new Set(group.map(item=>item.proposedAreaName))].sort((a,b)=>a.length-b.length||a.localeCompare(b))[0],existing=existingAreas.find(area=>sameArea(area.name,canonical)),target=existing?.name||canonical,building=group.every(item=>item.locationKind==='building'),named=group.every(item=>['building','named_locality'].includes(item.locationKind)),currentAreas=new Set(group.map(item=>item.currentAreaId)),confidence=building||named?'high':group.some(item=>item.confidence==='medium')?'medium':'high'
    for(const item of group){item.proposedAreaName=target;if(currentAreas.size>1&&!building){item.action='needs_review';item.confidence='needs_review';item.reason=`The named location “${target}” appears across ${currentAreas.size} meaningful Existing Areas. GPS proximity or a shared locality alone cannot merge them.`;continue}item.action=sameArea(item.currentAreaName,target)?'keep':'move';item.confidence=confidence;item.reason=building?`${group.length} Official GPS Branch(es) identify the same building or commercial complex “${target}”.`:`${group.length} Official GPS Branch(es) identify the same explicit operational location “${target}”; no distance-only merge was applied.`}
  }
  return items
}

async function enrich(branches,geocoder,preferLocality=false){return concurrentMap(branches.filter(hasGps),4,async branch=>{try{const found=await geocoder(branch.latitude,branch.longitude),combined={...found,address:found.address||branch.gpsAddress||branch.address,street:found.street||branch.savedRoad,road:found.road||found.street||branch.savedRoad,locality:found.locality||found.city||branch.savedLocality},name=candidateName(combined,preferLocality);return{...branch,geocode:combined,proposedAreaName:name,action:name?'move':'needs_review',confidence:'needs_review',reason:name?'Official GPS address requires operational grouping validation.':'No usable road or locality evidence; manual review is required.'}}catch(error){const fallback={address:branch.gpsAddress||branch.address,street:branch.savedRoad,road:branch.savedRoad,locality:branch.savedLocality},name=candidateName(fallback,preferLocality);return{...branch,geocode:fallback,proposedAreaName:name,action:name?'move':'needs_review',confidence:'needs_review',reason:name?'Google unavailable; grouped from saved Official GPS address components.':`Reverse geocoding unavailable: ${text(error.message)||'unknown error'}`}}})}
function missing(branches){return branches.filter(branch=>!hasGps(branch)).map(branch=>({...branch,geocode:{},proposedAreaName:'',action:'need_gps',confidence:'needs_review',reason:'Official GPS is required; current Zone and Area remain unchanged.'}))}
function insertSuggestions(analysisId,suggestions,database){const insert=database.prepare('INSERT INTO area_refinement_suggestions(analysis_id,branch_id,current_area_id,proposed_area_name,action,confidence,reason,official_latitude,official_longitude,reverse_address,road,locality,sublocality,postal_code) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');database.exec('BEGIN IMMEDIATE');try{for(const item of suggestions)insert.run(analysisId,item.id,item.currentAreaId,item.proposedAreaName||null,item.action,item.confidence,item.reason,hasGps(item)?item.latitude:null,hasGps(item)?item.longitude:null,item.geocode.address||null,item.geocode.road||item.geocode.street||null,item.geocode.locality||item.geocode.city||null,item.geocode.sublocality||item.geocode.neighborhood||null,item.geocode.postalCode||null);database.exec('COMMIT')}catch(error){database.exec('ROLLBACK');throw error}}

export async function analyzeArea(areaId,{includeExisting=false,createdBy,geocoder=reverseGeocodeGoogle}={},database=defaultDb){
  const area=database.prepare('SELECT id,name,zone_group_id zoneGroupId,confirmed_zone_group_id confirmedZoneGroupId FROM areas WHERE id=? AND is_active=1').get(Number(areaId));if(!area)throw Object.assign(new Error('Area not found'),{statusCode:404})
  const branches=areaBranchRows(area.id,Boolean(includeExisting),database),analysis=database.prepare("INSERT INTO area_refinement_analyses(parent_area_id,include_existing,created_by,scope_type,zone_group_id) VALUES(?,?,?,'area',?)").run(area.id,includeExisting?1:0,actor(createdBy),area.confirmedZoneGroupId||area.zoneGroupId),analysisId=Number(analysis.lastInsertRowid)
  try{const suggestions=groupAreaItems([...(await enrich(branches,geocoder)),...missing(branches)]);insertSuggestions(analysisId,suggestions,database);return getAreaRefinement(analysisId,database)}catch(error){database.prepare("UPDATE area_refinement_analyses SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(analysisId);throw error}
}

export async function analyzeZoneAreas(zoneId,{includeExisting=false,createdBy,geocoder=reverseGeocodeGoogle}={},database=defaultDb){
  const zone=database.prepare('SELECT id,name FROM zone_groups WHERE id=? AND is_active=1').get(Number(zoneId));if(!zone)throw Object.assign(new Error('Zone Group not found'),{statusCode:404})
  const areas=database.prepare('SELECT id,name FROM areas WHERE is_active=1 AND COALESCE(confirmed_zone_group_id,zone_group_id)=? ORDER BY name').all(zone.id);if(!areas.length)throw new Error('Zone has no Active Areas to analyze')
  const branches=zoneBranchRows(zone.id,Boolean(includeExisting),database),anchor=areas[0],analysis=database.prepare("INSERT INTO area_refinement_analyses(parent_area_id,include_existing,created_by,scope_type,zone_group_id) VALUES(?,?,?,'zone',?)").run(anchor.id,includeExisting?1:0,actor(createdBy),zone.id),analysisId=Number(analysis.lastInsertRowid)
  try{const suggestions=groupZoneItems([...(await enrich(branches,geocoder,true)),...missing(branches)],areas);insertSuggestions(analysisId,suggestions,database);return getAreaRefinement(analysisId,database)}catch(error){database.prepare("UPDATE area_refinement_analyses SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(analysisId);throw error}
}

export function getAreaRefinement(analysisId,database=defaultDb){
  const analysis=database.prepare(`SELECT ar.id,ar.parent_area_id parentAreaId,a.name parentAreaName,ar.scope_type scopeType,ar.zone_group_id zoneGroupId,ar.status,ar.include_existing includeExisting,ar.created_by createdBy,ar.created_at createdAt,ar.updated_by updatedBy,ar.updated_at updatedAt,ar.confirmed_by confirmedBy,ar.confirmed_at confirmedAt,ar.reason,COALESCE(z.name,pz.name) zoneGroup FROM area_refinement_analyses ar LEFT JOIN areas a ON a.id=ar.parent_area_id LEFT JOIN zone_groups z ON z.id=ar.zone_group_id LEFT JOIN zone_groups pz ON pz.id=COALESCE(a.confirmed_zone_group_id,a.zone_group_id) WHERE ar.id=?`).get(Number(analysisId));if(!analysis)throw Object.assign(new Error('Area refinement analysis not found'),{statusCode:404})
  const items=database.prepare(`SELECT s.id,s.branch_id branchInternalId,b.jodoo_branch_id branchId,b.branch_name branchName,c.jodoo_customer_id customerId,c.name customerName,s.current_area_id currentAreaId,a.name currentAreaName,s.proposed_area_name proposedAreaName,s.action,s.confidence,s.reason,s.official_latitude latitude,s.official_longitude longitude,s.reverse_address reverseAddress,s.road,s.locality,s.sublocality,s.postal_code postalCode,b.address currentAddress FROM area_refinement_suggestions s JOIN branches b ON b.id=s.branch_id LEFT JOIN customers c ON c.id=b.customer_id LEFT JOIN areas a ON a.id=s.current_area_id WHERE s.analysis_id=? ORDER BY CASE s.action WHEN 'move' THEN 1 WHEN 'keep' THEN 2 WHEN 'needs_review' THEN 3 ELSE 4 END,COALESCE(s.proposed_area_name,''),COALESCE(b.branch_name,''),b.id`).all(analysis.id)
  const existingAreas=analysis.scopeType==='zone'?database.prepare('SELECT id,name FROM areas WHERE COALESCE(confirmed_zone_group_id,zone_group_id)=?').all(analysis.zoneGroupId):database.prepare('SELECT a.id,a.name FROM area_refinement_children c JOIN areas a ON a.id=c.child_area_id WHERE c.parent_area_id=?').all(analysis.parentAreaId),existingNames=new Set(existingAreas.map(row=>normalizeName(row.name)))
  for(const item of items)item.suggestionKind=item.action==='need_gps'?'need_gps':item.action==='needs_review'?'needs_review':item.action==='keep'?'keep':existingNames.has(normalizeName(item.proposedAreaName))?'move_existing':'new_area'
  const suggestedNames=new Set(items.filter(item=>item.action==='move'&&text(item.proposedAreaName)).map(item=>normalizeName(item.proposedAreaName))),counts={total:items.length,officialGps:items.filter(item=>Number.isFinite(item.latitude)&&Number.isFinite(item.longitude)).length,needGps:items.filter(item=>item.action==='need_gps').length,move:items.filter(item=>item.action==='move').length,keep:items.filter(item=>item.action==='keep').length,needsReview:items.filter(item=>item.action==='needs_review').length,createAreas:[...suggestedNames].filter(name=>!existingNames.has(name)).length,existingAreas:analysis.scopeType==='zone'?existingAreas.length:1,suggestedAreas:new Set(items.filter(item=>item.action==='move'||item.action==='keep').map(item=>normalizeName(item.proposedAreaName||item.currentAreaName)).filter(Boolean)).size}
  return{...analysis,includeExisting:Boolean(analysis.includeExisting),counts,items}
}

export function updateAreaRefinement(analysisId,{items=[],changedBy}={},database=defaultDb){
  const analysis=database.prepare("SELECT id,status FROM area_refinement_analyses WHERE id=?").get(Number(analysisId));if(!analysis)throw Object.assign(new Error('Area refinement analysis not found'),{statusCode:404});if(analysis.status!=='preview')throw new Error('Only a Preview analysis can be adjusted');if(!Array.isArray(items)||!items.length)throw new Error('At least one Branch adjustment is required')
  const allowed=new Set(['move','keep','needs_review','need_gps']),update=database.prepare('UPDATE area_refinement_suggestions SET proposed_area_name=?,action=?,confidence=?,reason=?,reviewed_by=?,reviewed_at=CURRENT_TIMESTAMP WHERE analysis_id=? AND branch_id=?')
  database.exec('BEGIN IMMEDIATE');try{for(const item of items){const action=text(item.action),name=text(item.proposedAreaName);if(!allowed.has(action))throw new Error('Invalid Area refinement action');if(action==='move'&&!name)throw new Error('Suggested Area name is required when moving a Branch');const result=update.run(name||null,action,'needs_review',text(item.reason)||'Manually adjusted during Preview.',actor(changedBy),analysis.id,Number(item.branchId));if(result.changes!==1)throw new Error('Branch does not belong to this Area refinement analysis')}database.prepare('UPDATE area_refinement_analyses SET updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(actor(changedBy),analysis.id);database.exec('COMMIT');return getAreaRefinement(analysis.id,database)}catch(error){database.exec('ROLLBACK');throw error}
}

export function confirmAreaRefinement(analysisId,{reason,changedBy,failBeforeAudit=false}={},database=defaultDb){
  const preview=getAreaRefinement(analysisId,database),why=text(reason);if(preview.status!=='preview')throw new Error('Only a Preview analysis can be confirmed');if(!why)throw new Error('Confirmation reason is required');if(preview.counts.needsReview)throw new Error('Resolve every Needs Review suggestion before confirmation')
  const who=actor(changedBy),movable=preview.items.filter(item=>item.action==='move'),created=[],moved=[];database.exec('BEGIN IMMEDIATE')
  try{
    const parent=database.prepare('SELECT * FROM areas WHERE id=?').get(preview.parentAreaId),zoneId=preview.scopeType==='zone'?preview.zoneGroupId:(parent.confirmed_zone_group_id??parent.zone_group_id),areaRows=preview.scopeType==='zone'?database.prepare('SELECT id,name FROM areas WHERE COALESCE(confirmed_zone_group_id,zone_group_id)=?').all(zoneId):database.prepare('SELECT c.child_area_id id,a.name FROM area_refinement_children c JOIN areas a ON a.id=c.child_area_id WHERE c.parent_area_id=?').all(parent.id),targets=new Map(areaRows.map(row=>[normalizeName(row.name),row.id])),names=[...new Map(movable.map(item=>[normalizeName(item.proposedAreaName),item.proposedAreaName])).entries()]
    names.forEach(([key,name],index)=>{if(targets.has(key))return;const externalId=`KCS-REF-${preview.id}-${index+1}`,result=database.prepare(`INSERT INTO areas(jodoo_area_id,name,zone_group_id,confirmed_zone_group_id,zone_assignment_status,zone_confirmed_by,zone_confirmed_at,is_active) VALUES(?,?,?,?, 'confirmed',?,CURRENT_TIMESTAMP,1)`).run(externalId,name,zoneId,zoneId,who),newId=Number(result.lastInsertRowid);database.prepare('INSERT INTO area_refinement_children(parent_area_id,child_area_id,analysis_id) VALUES(?,?,?)').run(parent.id,newId,preview.id);targets.set(key,newId);created.push(newId)})
    for(const item of movable){const live=database.prepare(`SELECT b.area_id,b.latitude,b.longitude,COALESCE(a.confirmed_zone_group_id,a.zone_group_id) zone_id FROM branches b JOIN areas a ON a.id=b.area_id WHERE b.id=?`).get(item.branchInternalId);if(live&&live.zone_id!==zoneId)throw new Error(`Branch ${item.branchId} is outside the analyzed Zone`);if(!live||live.area_id!==item.currentAreaId||round(live.latitude)!==round(item.latitude)||round(live.longitude)!==round(item.longitude))throw new Error(`Branch ${item.branchId} changed after Preview; run Analyze again`);const target=targets.get(normalizeName(item.proposedAreaName)),targetZone=database.prepare('SELECT COALESCE(confirmed_zone_group_id,zone_group_id) zone_id FROM areas WHERE id=?').get(target);if(!targetZone||targetZone.zone_id!==zoneId)throw new Error('Area refinement cannot cross the Zone boundary');database.prepare('UPDATE branches SET area_id=?,source_area_id=(SELECT jodoo_area_id FROM areas WHERE id=?),updated_at=CURRENT_TIMESTAMP WHERE id=?').run(target,target,item.branchInternalId);moved.push({branchId:item.branchInternalId,beforeAreaId:item.currentAreaId,afterAreaId:target})}
    if(failBeforeAudit)throw new Error('Simulated Area refinement audit failure')
    for(const change of moved)database.prepare(`INSERT INTO master_change_history(entity_type,entity_id,change_type,field_name,before_json,after_json,reason,changed_by) VALUES('branch',?,'area_refinement_confirmed','area_id',?,?,?,?)`).run(String(change.branchId),JSON.stringify({areaId:change.beforeAreaId,zoneGroupId:zoneId}),JSON.stringify({areaId:change.afterAreaId,zoneGroupId:zoneId}),why,who)
    database.prepare(`INSERT INTO master_change_history(entity_type,entity_id,change_type,field_name,before_json,after_json,reason,changed_by) VALUES('area_refinement',?,'area_refinement_confirmed','status',?,?,?,?)`).run(String(preview.id),JSON.stringify({status:'preview',scopeType:preview.scopeType,zoneGroupId:zoneId}),JSON.stringify({status:'confirmed',scopeType:preview.scopeType,zoneGroupId:zoneId,createdAreaIds:created,branchesMoved:moved,officialGpsUsed:movable.map(item=>({branchId:item.branchInternalId,latitude:item.latitude,longitude:item.longitude}))}),why,who)
    database.prepare("UPDATE area_refinement_analyses SET status='confirmed',confirmed_by=?,confirmed_at=CURRENT_TIMESTAMP,updated_by=?,updated_at=CURRENT_TIMESTAMP,reason=? WHERE id=?").run(who,who,why,preview.id);database.exec('COMMIT');return{...getAreaRefinement(preview.id,database),result:{createdAreaIds:created,movedBranchCount:moved.length}}
  }catch(error){database.exec('ROLLBACK');throw error}
}
