// Explicit public business messages only. Never expose arbitrary exceptions or SQL.
const rules=[
 ["DRIVER_PLAN_FORBIDDEN",403,/^DRIVER_PLAN_FORBIDDEN$/,() => ({"zh": "只有当天分配的司机可以检查或编排自己的明日行程。请刷新并检查人员分配。", "en": "Only the assigned driver can check or arrange their own tomorrow route. Refresh and check the assignment.", "ms": "Hanya pemandu yang ditugaskan boleh menyemak atau menyusun laluan esok sendiri. Muat semula dan semak penugasan."})],
 ["DRIVER_PLAN_DATE",409,/^DRIVER_PLAN_DATE$/,() => ({"zh": "只可提前编排明天的行程。请刷新页面并选择明天。", "en": "Only tomorrow’s route can be planned here. Refresh and select Tomorrow.", "ms": "Hanya laluan esok boleh disusun di sini. Muat semula dan pilih Esok."})],
 ["DRIVER_PLAN_LOCKED",409,/^DRIVER_PLAN_LOCKED$/,() => ({"zh": "行程已批准、已开始或有待处理事项，不能直接更改。请联系主管处理后刷新。", "en": "The trip is approved, started or has pending work. Contact your supervisor, then refresh.", "ms": "Perjalanan telah diluluskan, bermula atau ada urusan tertangguh. Hubungi penyelia, kemudian muat semula."})],
 ["DRIVER_PLAN_STALE",409,/^DRIVER_PLAN_STALE$/,() => ({"zh": "行程安排已改变。请刷新并重新检查当前顺序后提交。", "en": "The plan has changed. Refresh and check the current order before submitting.", "ms": "Rancangan telah berubah. Muat semula dan semak turutan terkini sebelum menghantar."})],

 ["MAP_SEARCH_CONFIGURATION",503,/^Map\ search\ requires\ a\ Google\ Places\ API\ key\.$/,()=>({"en": "Map search requires a Google Places API key.", "zh": "地图搜索尚未配置密钥。请管理员配置 GOOGLE_PLACES_API_KEY 或 GOOGLE_GEOCODING_API_KEY。", "ms": "Carian peta belum dikonfigurasi. Minta pentadbir menetapkan GOOGLE_PLACES_API_KEY atau GOOGLE_GEOCODING_API_KEY."})],
 ["MAP_SEARCH_AUTHORIZATION",503,/^Enable\ Places\ API\ \(New\)\ and\ authorize\ the\ server\ API\ key\ in\ Google\ Cloud\.$/,()=>({"en": "Enable Places API (New) and authorize the server API key in Google Cloud.", "zh": "Google 拒绝地图搜索授权。请管理员在 Google Cloud 启用 Places API (New)，检查服务器密钥限制及结算设置。", "ms": "Google menolak kebenaran carian peta. Minta pentadbir mengaktifkan Places API (New) dan menyemak sekatan kunci pelayan serta pengebilan."})],
 ["MAP_SEARCH_UNAVAILABLE",502,/^Map\ search\ is\ temporarily\ unavailable\.$/,()=>({"en": "Map search is temporarily unavailable.", "zh": "地图搜索暂时无法连接或服务异常。请稍后重试；仍可点击地图选择位置。", "ms": "Carian peta tidak tersedia buat sementara waktu. Cuba lagi; anda masih boleh memilih lokasi dengan mengetik peta."})],
 ["MAP_SEARCH_NO_RESULTS",404,/^No\ matching\ location\ was\ found\.$/,()=>({"en": "No matching location was found.", "zh": "找不到匹配地点。请加上地区或街道名称再搜索，或直接点击地图选择位置。", "ms": "Tiada lokasi sepadan. Tambah kawasan atau nama jalan, atau pilih lokasi pada peta."})],
 ["MAP_SEARCH_QUERY_REQUIRED",400,/^Enter\ a\ customer\ name\ or\ address\ to\ search\.$/,()=>({"en": "Enter a customer name or address to search.", "zh": "请输入客户／分店名称或地址。", "ms": "Masukkan nama pelanggan / cawangan atau alamat."})],
 ['ASSIGNMENT_CONFLICT',409,/^该(?:司机|跟车员)当天已分配给 (.{1,100})，请先解除原分配$/,m=>({zh:`该员工当天已分配给 ${m[1]}。请先在原车辆解除分配，再安排到这辆车。`,en:`This employee is already assigned to ${m[1]} on this date. Remove the original assignment before assigning this vehicle.`,ms:`Pekerja ini sudah ditugaskan kepada ${m[1]} pada tarikh ini. Batalkan penugasan asal sebelum menugaskannya kepada kenderaan ini.`})],
 ['ASSIGNMENT_ROLE_CONFLICT',409,/^(?:同一员工同一天不能同时担任 Driver 与 Attendant|该员工当天已担任 (?:Driver|Attendant)，不能同时担任 (?:Driver|Attendant))$/,()=>({zh:'该员工当天已有司机或跟车员安排，不能同时担任两种角色。请先解除原安排。',en:'This employee already has a driver or attendant assignment for this date. Remove it before changing roles.',ms:'Pekerja ini sudah ditugaskan sebagai pemandu atau kelindan pada tarikh ini. Batalkan penugasan asal sebelum menukar peranan.'})],
 ['EMPLOYEE_UNAVAILABLE',409,/^所选员工不是可用 (Driver|Assistant\/Crew)$/,m=>({zh:`所选员工目前不能担任${m[1]==='Driver'?'司机':'跟车员'}。请检查员工是否启用及其工作职位。`,en:`The selected employee is not available as ${m[1]}. Check employment status and job roles.`,ms:`Pekerja yang dipilih tidak tersedia sebagai ${m[1]}. Semak status pekerja dan jawatannya.`})],
 ['CREW_LIMIT',400,/^每辆车最多只能安排 (\d+) 名 Assistant\/Crew$/,m=>({zh:`每辆车最多安排 ${m[1]} 名跟车员，请减少选择人数。`,en:`Select no more than ${m[1]} attendants per vehicle.`,ms:`Pilih tidak lebih daripada ${m[1]} kelindan bagi setiap kenderaan.`})],
 ['CURRENT_PASSWORD_INCORRECT',400,/^当前密码不正确$/,()=>({zh:'当前密码不正确，请重新输入。若管理员刚重设密码，请使用最新的临时密码。',en:'The current password is incorrect. Enter it again; if an administrator reset it, use the latest temporary password.',ms:'Kata laluan semasa tidak betul. Masukkan semula; jika pentadbir telah menetapkannya semula, gunakan kata laluan sementara terkini.'})],
 ['ROUTE_REAPPROVAL_REQUIRED',409,/^路线必须先按当前版本重新批准$/,()=>({zh:'路线安排已修改，请主管先重新批准当前版本，再继续操作。',en:'The route has changed. Ask a supervisor to approve the current version before continuing.',ms:'Laluan telah berubah. Minta penyelia meluluskan versi terkini sebelum meneruskan.'})],
 ['STOP_ORDER_LOCKED',409,/^此客户顺序已锁定，请先解除锁定$/,()=>({zh:'此客户的顺序已锁定，请先解除锁定，再调整顺序。',en:'This customer order is locked. Unlock it before changing the order.',ms:'Turutan pelanggan ini dikunci. Buka kunci sebelum mengubah turutan.'})],
 ['ROUTE_WITHDRAWAL_BLOCKED',409,/^This route has been released or started and cannot be withdrawn\.$/,()=>({zh:'这条路线已经发布或开始执行，不能撤回批准。请使用当天调配功能处理人员变更。',en:'This route has been released or started and cannot be withdrawn. Use the daily handover function for staff changes.',ms:'Laluan ini telah dikeluarkan atau bermula dan kelulusannya tidak boleh ditarik balik. Gunakan fungsi pertukaran harian untuk perubahan pekerja.'})],
 ['VEHICLE_UNAVAILABLE',409,/^Vehicle is not available for this date$/,()=>({zh:'这辆车在所选日期不可用，请检查车辆状态或选择其他车辆。',en:'This vehicle is unavailable on the selected date. Check its status or choose another vehicle.',ms:'Kenderaan ini tidak tersedia pada tarikh dipilih. Semak statusnya atau pilih kenderaan lain.'})]
]
export function businessError(error){
 const message=String(error?.message||error||'')
 for(const [errorCode,status,pattern,render] of rules){const match=message.match(pattern);if(match)return{errorCode,status,messages:render(match)}}
 return null
}
