import {kuchingDate} from '../shared/kuchingTime.js'
import {activeRouteDriver} from './routeDriverAuthorization.mjs'
const fail=(code,statusCode=409)=>Object.assign(new Error(code),{code,statusCode})
const day=ctx=>ctx.today||kuchingDate()
function employee(db,ctx){const e=db.prepare("SELECT id,name FROM employees WHERE id=? AND is_active=1 AND employment_status='active'").get(Number(ctx.employeeId));if(!e||!['driver','crew','supervisor','operations_admin','owner_admin'].includes(ctx.role))throw fail('CARGO_DENIED',403);return e}
function atomic(db,fn){if(db.isTransaction)return fn();db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}
function audit(db,action,batchId,ctx,details){db.prepare('INSERT INTO audit_logs(action,entity_type,entity_id,after_json) VALUES(?,?,?,?)').run(action,'cargo_batch',String(batchId),JSON.stringify({employeeId:ctx.employeeId,...details}))}
function notify(db,batchId,employeeId){db.prepare('INSERT OR IGNORE INTO cargo_batch_notifications(batch_id,employee_id) VALUES(?,?)').run(batchId,employeeId)}
function prepare(db,vehicleId,ctx){const v=db.prepare('SELECT registration_number,vehicle_code FROM vehicles WHERE id=?').get(vehicleId);const id=Number(db.prepare("INSERT INTO cargo_batches(vehicle_id,plate_snapshot,status,created_by_employee_id) VALUES(?,?,'prepared',?)").run(vehicleId,v.registration_number||v.vehicle_code,ctx.employeeId).lastInsertRowid),code=`H${day(ctx).replaceAll('-','').slice(2)}-${String(id).padStart(6,'0')}`;db.prepare('UPDATE cargo_batches SET code=? WHERE id=?').run(code,id);notify(db,id,ctx.employeeId);audit(db,'cargo_prepared',id,ctx,{code,vehicleId});return db.prepare('SELECT * FROM cargo_batches WHERE id=?').get(id)}
function driverTrip(db,tripId,ctx){employee(db,ctx);if(!activeRouteDriver(db,ctx.employeeId,ctx.role))throw fail('CARGO_DENIED',403);const t=db.prepare(`SELECT t.id,t.dispatch_day_id,d.vehicle_id,d.driver_id,dd.dispatch_date FROM dispatch_trips t JOIN dispatches d ON d.id=t.dispatch_id JOIN dispatch_days dd ON dd.id=t.dispatch_day_id WHERE t.id=? AND d.driver_id=? AND dd.dispatch_date=? AND t.execution_status='in_progress'`).get(Number(tripId),Number(ctx.employeeId),day(ctx));if(!t)throw fail('CARGO_TRIP');return t}
export function startCargoBatch(db,ctx,tripId){return atomic(db,()=>{const t=driverTrip(db,tripId,ctx);let b=db.prepare("SELECT * FROM cargo_batches WHERE vehicle_id=? AND status<>'closed'").get(t.vehicle_id);if(!b)b=prepare(db,t.vehicle_id,ctx);if(b.status==='prepared'){const e=employee(db,ctx),crew=db.prepare('SELECT e.id,e.name FROM dispatch_vehicle_assistants a JOIN employees e ON e.id=a.employee_id WHERE a.dispatch_day_id=? AND a.vehicle_id=? AND e.is_active=1 AND e.employment_status=\'active\'').all(t.dispatch_day_id,t.vehicle_id);db.prepare("UPDATE cargo_batches SET status='active',started_at=CURRENT_TIMESTAMP,collection_date=?,start_trip_id=?,driver_employee_id=?,driver_name_snapshot=?,eligible_crew_json=? WHERE id=?").run(day(ctx),t.id,e.id,e.name,JSON.stringify(crew),b.id);db.prepare("INSERT INTO cargo_batch_members(batch_id,employee_id,name_snapshot,role) VALUES(?,?,?,'driver')").run(b.id,e.id,e.name);notify(db,b.id,e.id);audit(db,'cargo_started',b.id,ctx,{tripId:t.id,crew});}return batchView(db,b.id)})}
function batchView(db,id){const b=db.prepare('SELECT id,code,vehicle_id vehicleId,plate_snapshot plate,status,created_at createdAt,collection_date collectionDate,driver_name_snapshot driverName,closed_at closedAt FROM cargo_batches WHERE id=?').get(id);if(!b)return null;return{...b,members:db.prepare('SELECT employee_id employeeId,name_snapshot name,role,confirmed_at confirmedAt FROM cargo_batch_members WHERE batch_id=? ORDER BY role,employee_id').all(id),unloads:db.prepare('SELECT record_id recordId,ticket_number ticketNumber,mode,created_at createdAt FROM cargo_batch_unloads WHERE batch_id=? ORDER BY record_id').all(id)}}
function visible(db,b,ctx){return Boolean(db.prepare('SELECT 1 FROM cargo_batch_members WHERE batch_id=? AND employee_id=?').get(b.id,ctx.employeeId)||b.created_by_employee_id===Number(ctx.employeeId)||db.prepare(`SELECT 1 FROM dispatches d JOIN dispatch_days dd ON dd.dispatch_date=d.dispatch_date WHERE d.vehicle_id=? AND dd.dispatch_date=? AND (d.driver_id=? OR EXISTS(SELECT 1 FROM dispatch_vehicle_assistants a WHERE a.dispatch_day_id=dd.id AND a.vehicle_id=d.vehicle_id AND a.employee_id=?))`).get(b.vehicle_id,day(ctx),ctx.employeeId,ctx.employeeId))}
export function cargoContext(db,ctx){employee(db,ctx);const trips=db.prepare(`SELECT t.id tripId,t.trip_number tripNumber,d.vehicle_id vehicleId,v.registration_number plate FROM dispatch_trips t JOIN dispatches d ON d.id=t.dispatch_id JOIN dispatch_days dd ON dd.id=t.dispatch_day_id JOIN vehicles v ON v.id=d.vehicle_id WHERE d.driver_id=? AND dd.dispatch_date=? AND t.execution_status='in_progress'`).all(ctx.employeeId,day(ctx));const rows=db.prepare(`SELECT DISTINCT b.* FROM cargo_batches b LEFT JOIN cargo_batch_members m ON m.batch_id=b.id WHERE m.employee_id=? OR b.created_by_employee_id=? OR (b.status<>'closed' AND EXISTS(SELECT 1 FROM dispatches d JOIN dispatch_days dd ON dd.dispatch_date=d.dispatch_date WHERE d.vehicle_id=b.vehicle_id AND dd.dispatch_date=? AND (d.driver_id=? OR EXISTS(SELECT 1 FROM dispatch_vehicle_assistants a WHERE a.dispatch_day_id=dd.id AND a.vehicle_id=d.vehicle_id AND a.employee_id=?)))) ORDER BY b.id DESC LIMIT 100`).all(ctx.employeeId,ctx.employeeId,day(ctx),ctx.employeeId,ctx.employeeId);return{items:rows.map(b=>batchView(db,b.id)),trips,notifications:db.prepare(`SELECT n.batch_id id,b.code,b.plate_snapshot plate FROM cargo_batch_notifications n JOIN cargo_batches b ON b.id=n.batch_id WHERE n.employee_id=? AND n.acknowledged_at IS NULL AND b.status<>'closed' ORDER BY n.batch_id DESC`).all(ctx.employeeId)}}
export function lookupCargoBatch(db,ctx,code){employee(db,ctx);const b=db.prepare('SELECT * FROM cargo_batches WHERE code=?').get(String(code||'').trim().toUpperCase());if(!b||!visible(db,b,ctx))throw fail('CARGO_NOT_FOUND',404);return batchView(db,b.id)}
export function joinCargoBatch(db,ctx,code){return atomic(db,()=>{const e=employee(db,ctx);if(ctx.role!=='crew')throw fail('CARGO_DENIED',403);const b=db.prepare('SELECT * FROM cargo_batches WHERE code=?').get(String(code||'').trim().toUpperCase());if(!b||!visible(db,b,ctx))throw fail('CARGO_NOT_FOUND',404);const prior=db.prepare('SELECT 1 FROM cargo_batch_members WHERE batch_id=? AND employee_id=?').get(b.id,e.id);if(prior)return batchView(db,b.id);if(b.status!=='active'||b.collection_date!==day(ctx)||!JSON.parse(b.eligible_crew_json).some(c=>c.id===e.id))throw fail('CARGO_JOIN');db.prepare("INSERT INTO cargo_batch_members(batch_id,employee_id,name_snapshot,role) VALUES(?,?,?,'crew')").run(b.id,e.id,e.name);audit(db,'cargo_crew_joined',b.id,ctx,{name:e.name});return batchView(db,b.id)})}
export function acknowledgeCargo(db,ctx,id){employee(db,ctx);db.prepare('UPDATE cargo_batch_notifications SET acknowledged_at=CURRENT_TIMESTAMP WHERE batch_id=? AND employee_id=? AND acknowledged_at IS NULL').run(Number(id),ctx.employeeId);return{ok:true}}
// Called inside weight confirmation's transaction; a retry never advances the batch twice.
export function linkCargoUnload(db,ctx,record,payload){
 const e=employee(db,ctx),prior=db.prepare('SELECT * FROM cargo_batch_unloads WHERE record_id=?').get(record.id)
 if(prior)return{batch:batchView(db,prior.batch_id),nextBatch:prior.next_batch_id?batchView(db,prior.next_batch_id):null}
 if(record.driver_employee_id!==e.id)throw fail('CARGO_DENIED',403)
 const b=db.prepare('SELECT * FROM cargo_batches WHERE id=?').get(Number(payload.batchId)),mode=payload.unloadMode,ticket=String(payload.ticketNumber||'').trim()
 if(!b||b.vehicle_id!==record.vehicle_id||!visible(db,b,ctx))throw fail('CARGO_NOT_FOUND',404)
 if(!ticket||ticket.length>100||!['partial','full','supplement'].includes(mode))throw fail('CARGO_TICKET',400)
 if((b.status==='closed'&&mode!=='supplement')||(b.status!=='closed'&&mode==='supplement')||b.status==='prepared')throw fail('CARGO_STATE')
 // Reusing a ticket for this batch is likely a duplicate upload, not another load.
 if(db.prepare('SELECT 1 FROM cargo_batch_unloads WHERE batch_id=? AND UPPER(TRIM(ticket_number))=UPPER(?)').get(b.id,ticket))throw fail('CARGO_DUPLICATE')
 let next=null
 if(mode==='full'){db.prepare("UPDATE cargo_batches SET status='closed',closed_at=CURRENT_TIMESTAMP WHERE id=?").run(b.id);next=prepare(db,b.vehicle_id,ctx)}
 db.prepare('INSERT INTO cargo_batch_unloads(record_id,batch_id,ticket_number,mode,submitted_by_employee_id,next_batch_id) VALUES(?,?,?,?,?,?)').run(record.id,b.id,ticket,mode,e.id,next?.id||null)
 audit(db,'cargo_unloaded',b.id,ctx,{recordId:record.id,ticket,mode,nextBatchId:next?.id||null})
 return{batch:batchView(db,b.id),nextBatch:next?batchView(db,next.id):null}
}
