import {db as defaultDb} from './database.mjs'

const scopeTable={zone:'zone_groups',area:'areas'}
const actor=value=>String(value||'Supervisor').trim()||'Supervisor'

export function usableDefaultVehicle(database,vehicleId){if(!vehicleId)return null;return database.prepare(`SELECT id,vehicle_code vehicleCode,vehicle_name vehicleName,registration_number registrationNumber,operational_status status FROM vehicles WHERE id=? AND is_temporary=0 AND operational_status IN ('available','active') AND status IN ('available','assigned')`).get(Number(vehicleId))||null}

export function listZoneDefaultVehicles(zoneId,database=defaultDb){return database.prepare(`SELECT v.id,v.vehicle_code vehicleCode,v.vehicle_name vehicleName,v.registration_number registrationNumber,v.operational_status status,v.status masterStatus,zdv.position,CASE WHEN v.is_temporary=0 AND v.operational_status IN ('available','active') AND v.status IN ('available','assigned') THEN 1 ELSE 0 END isAvailable FROM zone_default_vehicles zdv JOIN vehicles v ON v.id=zdv.vehicle_id WHERE zdv.zone_group_id=? ORDER BY zdv.position`).all(Number(zoneId))}

export function setZoneDefaultVehicles(zoneId,payload={},database=defaultDb){const zone=database.prepare('SELECT id,name FROM zone_groups WHERE id=?').get(Number(zoneId));if(!zone)throw new Error('Zone not found');if(!Array.isArray(payload.vehicleIds))throw new Error('Default Vehicle list is required');const ids=payload.vehicleIds.map(Number);if(ids.some(id=>!Number.isInteger(id)||id<=0))throw new Error('Invalid Default Vehicle');if(ids.length>3)throw new Error('Maximum 3 Vehicles');if(new Set(ids).size!==ids.length)throw new Error('The same vehicle cannot be assigned twice to one Zone');const reason=String(payload.reason||'').trim();if(!reason)throw new Error('Change Reason is required');const before=listZoneDefaultVehicles(zoneId,database),beforeIds=before.map(item=>item.id);for(const id of ids)if(!beforeIds.includes(id)&&!usableDefaultVehicle(database,id))throw new Error('Default Vehicle must be an active dispatch vehicle');if(JSON.stringify(beforeIds)===JSON.stringify(ids))return{zoneId:Number(zoneId),defaultVehicles:before,unchanged:true};const added=ids.filter(id=>!beforeIds.includes(id)),removed=beforeIds.filter(id=>!ids.includes(id));database.exec('BEGIN IMMEDIATE');try{database.prepare('DELETE FROM zone_default_vehicles WHERE zone_group_id=?').run(Number(zoneId));const insert=database.prepare('INSERT INTO zone_default_vehicles(zone_group_id,vehicle_id,position,created_by) VALUES(?,?,?,?)');ids.forEach((id,index)=>insert.run(Number(zoneId),id,index+1,actor(payload.changedBy)));database.prepare('UPDATE zone_groups SET default_vehicle_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(ids[0]??null,Number(zoneId));const after=listZoneDefaultVehicles(zoneId,database);database.prepare(`INSERT INTO master_change_history(entity_type,entity_id,change_type,field_name,before_json,after_json,reason,changed_by) VALUES('zone_group',?,'default_vehicle_pool_changed','default_vehicle_ids',?,?,?,?)`).run(String(zoneId),JSON.stringify({vehicleIds:beforeIds}),JSON.stringify({vehicleIds:ids,addedVehicleIds:added,removedVehicleIds:removed}),reason,actor(payload.changedBy));database.exec('COMMIT');return{zoneId:Number(zoneId),defaultVehicles:after,addedVehicleIds:added,removedVehicleIds:removed}}catch(error){database.exec('ROLLBACK');throw error}}

export function setDefaultVehicle(scope,id,payload={},database=defaultDb){if(scope==='zone')return setZoneDefaultVehicles(id,{vehicleIds:payload.vehicleId==null||payload.vehicleId===''?[]:[Number(payload.vehicleId)],reason:payload.reason,changedBy:payload.changedBy},database);const table=scopeTable[scope];if(!table)throw new Error('Default Vehicle scope must be Zone or Area');const target=database.prepare(`SELECT id,name,default_vehicle_id defaultVehicleId FROM ${table} WHERE id=?`).get(Number(id));if(!target)throw new Error('Area not found');const nextId=payload.vehicleId==null||payload.vehicleId===''?null:Number(payload.vehicleId);if(nextId&&!usableDefaultVehicle(database,nextId))throw new Error('Default Vehicle must be an active dispatch vehicle');const reason=String(payload.reason||'').trim();if(!reason)throw new Error('Change Reason is required');if(Number(target.defaultVehicleId||0)===Number(nextId||0))return{...target,defaultVehicleId:nextId,unchanged:true};database.exec('BEGIN IMMEDIATE');try{database.prepare(`UPDATE ${table} SET default_vehicle_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(nextId,Number(id));const after=database.prepare(`SELECT id,name,default_vehicle_id defaultVehicleId FROM ${table} WHERE id=?`).get(Number(id));database.prepare(`INSERT INTO master_change_history(entity_type,entity_id,change_type,field_name,before_json,after_json,reason,changed_by) VALUES('area',?,'default_vehicle_changed','default_vehicle_id',?,?,?,?)`).run(String(id),JSON.stringify({defaultVehicleId:target.defaultVehicleId??null}),JSON.stringify({defaultVehicleId:after.defaultVehicleId??null}),reason,actor(payload.changedBy));database.exec('COMMIT');return after}catch(error){database.exec('ROLLBACK');throw error}}
