const clean=value=>String(value??'').trim()
const validCoordinates=row=>row.latitude!=null&&row.longitude!=null&&Number.isFinite(Number(row.latitude))&&Number.isFinite(Number(row.longitude))&&Number(row.latitude)>=-90&&Number(row.latitude)<=90&&Number(row.longitude)>=-180&&Number(row.longitude)<=180

export function commercialOptions(database){
  const buyers=database.prepare("SELECT id,buyer_code buyerCode,buyer_name buyerName FROM buyers WHERE status='active' ORDER BY buyer_name,id").all()
  const endLocations=database.prepare(`SELECT l.id,l.location_code locationCode,l.name locationName,l.address,l.latitude,l.longitude,l.operational_type locationType,l.buyer_id buyerReferenceId,b.buyer_code buyerCode,b.buyer_name parentName FROM operational_locations l LEFT JOIN buyers b ON b.id=l.buyer_id WHERE l.is_active=1 AND COALESCE(l.status,'active')='active' AND (l.can_end=1 OR l.operational_type='Company Yard') AND l.latitude IS NOT NULL AND l.longitude IS NOT NULL ORDER BY CASE WHEN l.operational_type='Company Yard' THEN 1 ELSE 0 END,COALESCE(b.buyer_name,l.name),l.name`).all().filter(validCoordinates)
  return{buyers,endLocations}
}

export function resolveBuyerPayer(selection,database){if(selection==null)return null;const id=Number(selection.referenceId??selection.buyerId??selection);if(!id)throw new Error('Select an active Buyer / Payer');const row=database.prepare("SELECT id,buyer_code buyerCode,buyer_name buyerName FROM buyers WHERE id=? AND status='active'").get(id);if(!row)throw new Error('Buyer / Payer is not active');return{buyerReferenceId:row.id,buyerCode:row.buyerCode,buyerName:row.buyerName}}

export function resolvePrimaryEndLocation(selection,database){if(selection==null)return null;const id=Number(selection.referenceId??selection.locationId??selection);if(!id)throw new Error('Select a Primary End Location');const row=database.prepare(`SELECT l.id,l.name locationName,l.address,l.latitude,l.longitude,l.operational_type locationType,b.buyer_name parentName FROM operational_locations l LEFT JOIN buyers b ON b.id=l.buyer_id WHERE l.id=? AND l.is_active=1 AND COALESCE(l.status,'active')='active' AND (l.can_end=1 OR l.operational_type='Company Yard') AND l.latitude IS NOT NULL AND l.longitude IS NOT NULL`).get(id);if(!row||!validCoordinates(row))throw new Error('Primary End Location must be active, approved for delivery and have valid GPS');return{endLocationId:row.id,endLocationReferenceType:'operational_location',endLocationReferenceId:row.id,endLocationName:row.locationName,endLocationParentName:row.parentName||null,endAddress:clean(row.address)||null,endLatitude:Number(row.latitude),endLongitude:Number(row.longitude)}}

export function writeCommercialSnapshot(database,dispatchId,{buyer,endLocation}){database.prepare(`UPDATE dispatches SET buyer_reference_id=?,buyer_code=?,buyer_name=?,end_location_id=?,end_location_reference_type=?,end_location_reference_id=?,end_location_name=?,end_location_parent_name=?,end_address=?,end_latitude=?,end_longitude=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(buyer?.buyerReferenceId??null,buyer?.buyerCode??null,buyer?.buyerName??null,endLocation?.endLocationId??null,endLocation?.endLocationReferenceType??null,endLocation?.endLocationReferenceId??null,endLocation?.endLocationName??null,endLocation?.endLocationParentName??null,endLocation?.endAddress??null,endLocation?.endLatitude??null,endLocation?.endLongitude??null,dispatchId)}
