import {db as defaultDb} from './database.mjs'
import {kuchingDate} from '../shared/kuchingTime.js'
import {withImmediateTransaction} from './branchServiceDateGuard.mjs'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'

export const ARRIVAL_RADIUS_METERS=Number(process.env.KCS_ARRIVAL_RADIUS_METERS||150)
export const MAX_ARRIVAL_ACCURACY_METERS=Number(process.env.KCS_MAX_ARRIVAL_ACCURACY_METERS||50)
export const isArrivalTestMode=(env=process.env)=>/^(1|true|yes|on)$/i.test(String(env.KCS_REMOTE_ARRIVAL_TEST_MODE||'').trim())
const fail=(message,code='INVALID_STATUS',statusCode=409,details={})=>{const error=new Error(message);error.code=code;error.statusCode=statusCode;error.publicDetails=details;return error}
const nowKuching=(input=new Date())=>{const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuching',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(input)).map(part=>[part.type,part.value]));return`${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}:${parts.second}+08:00`}
const distanceMeters=(aLat,aLon,bLat,bLon)=>{const rad=value=>value*Math.PI/180,R=6371000,dLat=rad(bLat-aLat),dLon=rad(bLon-aLon),x=Math.sin(dLat/2)**2+Math.cos(rad(aLat))*Math.cos(rad(bLat))*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function activeDriver(database,employeeId,role){if(String(role).toLowerCase()!=='driver')throw fail('Only an active driver can perform this action.','PERMISSION_DENIED',403);const employee=database.prepare(`SELECT e.id FROM employees e WHERE e.id=? AND e.is_active=1 AND e.employment_status='active' AND (lower(e.job_role)='driver' OR EXISTS(SELECT 1 FROM employee_job_roles r WHERE r.employee_id=e.id AND r.role='Driver' AND r.is_active=1))`).get(Number(employeeId));if(!employee)throw fail('Only an active driver can perform this action.','PERMISSION_DENIED',403);return employee}
const tripContext=(database,tripId)=>database.prepare(`SELECT dt.*,dd.dispatch_date,dd.status day_status,d.vehicle_id,d.driver_id,d.status dispatch_status,v.operational_status,v.status vehicle_status
  FROM dispatch_trips dt JOIN dispatch_days dd ON dd.id=dt.dispatch_day_id JOIN dispatches d ON d.id=dt.dispatch_id JOIN vehicles v ON v.id=d.vehicle_id WHERE dt.id=?`).get(Number(tripId))
const assertOwnedToday=(database,tripId,employeeId,today)=>{const trip=tripContext(database,tripId);if(!trip)throw fail('Trip not found.','NOT_FOUND',404);if(trip.dispatch_date!==today)throw fail('Only today’s route can be operated.','PERMISSION_DENIED',403);if(Number(trip.driver_id)!==Number(employeeId))throw fail('This Trip is assigned to another driver.','PERMISSION_DENIED',403);if(!['available','active'].includes(trip.operational_status)||!['available','assigned'].includes(trip.vehicle_status))throw fail('The assigned vehicle is inactive.');return trip}
const stopContext=(database,stopId)=>database.prepare(`SELECT ds.*,dt.execution_status,dt.completed_at trip_completed_at,dt.id trip_id,dd.id day_id,dd.dispatch_date,dd.status day_status,d.vehicle_id,d.driver_id,d.id dispatch_id FROM dispatch_stops ds JOIN dispatch_trips dt ON dt.id=ds.dispatch_trip_id JOIN dispatch_days dd ON dd.id=dt.dispatch_day_id JOIN dispatches d ON d.id=dt.dispatch_id WHERE ds.id=?`).get(Number(stopId))
const currentStop=(database,tripId)=>database.prepare("SELECT id,stop_sequence FROM dispatch_stops WHERE dispatch_trip_id=? AND status NOT IN ('cancelled','completed') ORDER BY stop_sequence,id LIMIT 1").get(tripId)
function assertCurrentArrived(database,stopId,employeeId,today){const stop=stopContext(database,stopId);if(!stop)throw fail('Stop not found.','NOT_FOUND',404);assertOwnedToday(database,stop.trip_id,employeeId,today);if(stop.execution_status!=='in_progress'||stop.trip_completed_at)throw fail('The Trip is not In Progress.');const current=currentStop(database,stop.trip_id);if(!current||Number(current.id)!==Number(stop.id))throw fail(`Stop ${current?.id||'unknown'} must be handled first.`,'STOP_SEQUENCE_REQUIRED',409,{currentStopId:current?.id||null});if(!stop.arrived_at||stop.status!=='active')throw fail('The current Stop must be Arrived before it can be completed.');return stop}
const log=(database,stop,type,actorId,before,after)=>database.prepare(`INSERT INTO dispatch_change_logs(dispatch_day_id,actor,change_type,entity_type,entity_id,before_json,after_json,requires_reapproval) VALUES(?,?,?,?,?,?,?,0)`).run(stop.day_id,String(actorId),type,'dispatch_stop',String(stop.id),JSON.stringify(before),JSON.stringify(after))

export function startDriverTrip(tripId,{employeeId,role,today=kuchingDate(),now=new Date()}={},database=defaultDb){
  activeDriver(database,employeeId,role);const serviceDate=kuchingDate(`${today}T00:00:00+08:00`)
  return withImmediateTransaction(database,()=>{const trip=assertOwnedToday(database,tripId,employeeId,serviceDate);if(trip.execution_status==='in_progress')return{tripId:Number(trip.id),status:'in_progress',startedAt:trip.started_at,idempotent:true};if(trip.execution_status==='completed')throw fail('This Trip is already completed.');if(!['approved','in_progress'].includes(trip.day_status))throw fail(`Only an Approved route can start; current status is ${trip.day_status}.`)
    const stopCount=database.prepare("SELECT COUNT(*) n FROM dispatch_stops WHERE dispatch_trip_id=? AND status<>'cancelled'").get(trip.id).n;if(!stopCount)throw fail('This Trip has no active Stops.')
    const running=database.prepare("SELECT dt.id FROM dispatch_trips dt JOIN dispatches d ON d.id=dt.dispatch_id WHERE dt.dispatch_day_id=? AND d.vehicle_id=? AND dt.execution_status='in_progress' AND dt.id<>? LIMIT 1").get(trip.dispatch_day_id,trip.vehicle_id,trip.id);if(running)throw fail(`Trip ${running.id} is already In Progress for this vehicle.`)
    const earlier=database.prepare(`SELECT dt.id,dt.trip_number FROM dispatch_trips dt JOIN dispatches d ON d.id=dt.dispatch_id WHERE dt.dispatch_day_id=? AND d.vehicle_id=? AND dt.trip_number<? AND dt.execution_status<>'completed' AND EXISTS(SELECT 1 FROM dispatch_stops ds WHERE ds.dispatch_trip_id=dt.id AND ds.status<>'cancelled') ORDER BY dt.trip_number LIMIT 1`).get(trip.dispatch_day_id,trip.vehicle_id,trip.trip_number);if(earlier)throw fail(`Trip ${earlier.trip_number} must be completed before starting Trip ${trip.trip_number}.`)
    const startedAt=nowKuching(now),before={status:trip.execution_status,startedAt:trip.started_at};database.prepare("UPDATE dispatch_trips SET execution_status='in_progress',started_at=?,started_by_employee_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND execution_status='not_started'").run(startedAt,employeeId,trip.id);database.prepare("UPDATE dispatches SET status='in_progress',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(trip.dispatch_id);database.prepare("UPDATE dispatch_days SET status='in_progress',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(trip.dispatch_day_id);database.prepare(`INSERT INTO dispatch_change_logs(dispatch_day_id,actor,change_type,entity_type,entity_id,before_json,after_json,requires_reapproval) VALUES(?,?,'driver_trip_started','dispatch_trip',?,?,?,0)`).run(trip.dispatch_day_id,String(employeeId),String(trip.id),JSON.stringify(before),JSON.stringify({status:'in_progress',startedAt,driverId:Number(employeeId),vehicleId:trip.vehicle_id}));return{tripId:Number(trip.id),status:'in_progress',startedAt,idempotent:false}
  })
}

export function arriveAtStop(stopId,payload={},context={},database=defaultDb){
  const{employeeId,role,today=kuchingDate(),now=new Date()}=context,testMode=context.remoteArrivalTestMode??isArrivalTestMode();activeDriver(database,employeeId,role);const latitude=Number(payload.latitude),longitude=Number(payload.longitude),accuracy=Number(payload.accuracy),capturedAt=new Date(payload.captured_at)
  if(!Number.isFinite(latitude)||latitude < -90||latitude > 90||!Number.isFinite(longitude)||longitude < -180||longitude > 180)throw fail('Invalid GPS coordinates.','INVALID_GPS',400)
  if(!Number.isFinite(accuracy)||accuracy<=0)throw fail('Invalid GPS accuracy.','INVALID_GPS',400)
  if(!testMode&&accuracy>MAX_ARRIVAL_ACCURACY_METERS)throw fail(`GPS accuracy ${Math.round(accuracy)}m is insufficient; required accuracy is ${MAX_ARRIVAL_ACCURACY_METERS}m or better.`,'GPS_ACCURACY_POOR',400,{accuracyMeters:Math.round(accuracy),maximumAccuracyMeters:MAX_ARRIVAL_ACCURACY_METERS})
  if(Number.isNaN(capturedAt.getTime())||Math.abs(new Date(now).getTime()-capturedAt.getTime())>15*60*1000)throw fail('GPS capture time is invalid or stale.','GPS_CAPTURE_STALE',400)
  return withImmediateTransaction(database,()=>{const stop=database.prepare(`SELECT ds.*,dt.execution_status,dt.id trip_id,dd.id day_id,dd.dispatch_date,dd.status day_status,d.vehicle_id,d.driver_id,b.latitude branch_latitude,b.longitude branch_longitude
      FROM dispatch_stops ds JOIN dispatch_trips dt ON dt.id=ds.dispatch_trip_id JOIN dispatch_days dd ON dd.id=dt.dispatch_day_id JOIN dispatches d ON d.id=dt.dispatch_id JOIN branches b ON b.id=ds.branch_id WHERE ds.id=?`).get(Number(stopId));if(!stop)throw fail('Stop not found.','NOT_FOUND',404);assertOwnedToday(database,stop.trip_id,employeeId,kuchingDate(`${today}T00:00:00+08:00`));if(stop.arrived_at)return{stopId:Number(stop.id),status:'arrived',arrivedAt:stop.arrived_at,distanceMeters:stop.arrival_distance_m,idempotent:true};if(stop.execution_status!=='in_progress'||stop.day_status!=='in_progress')throw fail('The Trip is not In Progress.');const current=database.prepare("SELECT id,stop_sequence FROM dispatch_stops WHERE dispatch_trip_id=? AND status NOT IN ('cancelled','completed') ORDER BY stop_sequence,id LIMIT 1").get(stop.trip_id);if(!current||Number(current.id)!==Number(stop.id))throw fail(`Stop ${current?.id||'unknown'} must be handled first.`,'STOP_SEQUENCE_REQUIRED',409,{currentStopId:current?.id||null});if(stop.branch_latitude==null||stop.branch_longitude==null)throw fail('Customer GPS not set, please contact the supervisor.','CUSTOMER_GPS_NOT_SET',409)
    const distance=Math.round(distanceMeters(latitude,longitude,Number(stop.branch_latitude),Number(stop.branch_longitude)));if(!testMode&&distance>ARRIVAL_RADIUS_METERS)throw fail(`You are ${distance}m from the Customer; allowed arrival radius is ${ARRIVAL_RADIUS_METERS}m (GPS accuracy ${Math.round(accuracy)}m).`,'ARRIVAL_OUT_OF_RANGE',409,{distanceMeters:distance,allowedRadiusMeters:ARRIVAL_RADIUS_METERS,accuracyMeters:accuracy});const arrivedAt=nowKuching(now),before={status:stop.status,arrivedAt:null};database.prepare("UPDATE dispatch_stops SET status='active',arrived_at=?,arrival_latitude=?,arrival_longitude=?,arrival_accuracy_m=?,arrival_distance_m=?,arrival_captured_at=?,arrived_by_employee_id=? WHERE id=? AND arrived_at IS NULL").run(arrivedAt,latitude,longitude,accuracy,distance,capturedAt.toISOString(),employeeId,stop.id);database.prepare(`INSERT INTO dispatch_change_logs(dispatch_day_id,actor,change_type,entity_type,entity_id,before_json,after_json,requires_reapproval) VALUES(?,?,'driver_stop_arrived','dispatch_stop',?,?,?,0)`).run(stop.day_id,String(employeeId),String(stop.id),JSON.stringify(before),JSON.stringify({status:'arrived',arrivedAt,latitude,longitude,accuracy,distanceMeters:distance,driverId:Number(employeeId),remoteArrivalTestMode:Boolean(testMode)}));return{stopId:Number(stop.id),status:'arrived',arrivedAt,distanceMeters:distance,accuracyMeters:accuracy,remoteArrivalTestMode:Boolean(testMode),idempotent:false}
  })
}

export function deferDriverStop(stopId,payload={},context={},database=defaultDb){
  const{employeeId,role,today=kuchingDate()}=context,reason=String(payload.reason||'').trim(),allowed=new Set(['customer_requested_return','no_space_available','other'])
  activeDriver(database,employeeId,role)
  if(!allowed.has(reason))throw fail('Select a valid reason for coming back later.','DEFER_REASON_REQUIRED',400)
  return withImmediateTransaction(database,()=>{
    const stop=assertCurrentArrived(database,stopId,employeeId,kuchingDate(`${today}T00:00:00+08:00`))
    if(database.prepare("SELECT 1 FROM purchase_bills WHERE dispatch_stop_id=? AND status='issued'").get(stop.id))throw fail('This Stop already has an electronic Bill and cannot be moved.','BILL_ALREADY_CREATED',409)
    const later=database.prepare("SELECT id,stop_sequence stopSequence FROM dispatch_stops WHERE dispatch_trip_id=? AND status NOT IN ('cancelled','completed') AND stop_sequence>? ORDER BY stop_sequence,id").all(stop.trip_id,stop.stop_sequence)
    if(!later.length)throw fail('There is no later customer in this Trip to open.','NO_NEXT_STOP',409)
    const positions=[Number(stop.stop_sequence),...later.map(item=>Number(item.stopSequence))],maximum=Number(database.prepare('SELECT COALESCE(MAX(stop_sequence),0) value FROM dispatch_stops WHERE dispatch_id=?').get(stop.dispatch_id).value),offset=maximum+1000000
    database.prepare('UPDATE dispatch_stops SET stop_sequence=? WHERE id=?').run(offset+maximum+1,stop.id)
    for(const item of later)database.prepare('UPDATE dispatch_stops SET stop_sequence=? WHERE id=?').run(offset+Number(item.stopSequence),item.id)
    for(let index=0;index<later.length;index+=1)database.prepare('UPDATE dispatch_stops SET stop_sequence=? WHERE id=?').run(positions[index],later[index].id)
    const movedSequence=positions.at(-1)
    database.prepare('UPDATE dispatch_stops SET stop_sequence=?,arrived_at=NULL,arrival_latitude=NULL,arrival_longitude=NULL,arrival_accuracy_m=NULL,arrival_distance_m=NULL,arrival_captured_at=NULL,arrived_by_employee_id=NULL WHERE id=?').run(movedSequence,stop.id)
    log(database,stop,'driver_stop_deferred',employeeId,{status:'arrived',stopSequence:Number(stop.stop_sequence),arrivedAt:stop.arrived_at,latitude:stop.arrival_latitude,longitude:stop.arrival_longitude,accuracy:stop.arrival_accuracy_m,distanceMeters:stop.arrival_distance_m},{status:'pending',stopSequence:movedSequence,reason,nextStopId:Number(later[0].id),movedToTripEnd:true})
    return{stopId:Number(stop.id),status:'deferred',reason,stopSequence:movedSequence,nextStopId:Number(later[0].id)}
  })
}

export function completeDriverStop(stopId,context={},database=defaultDb){const{employeeId,role,today=kuchingDate(),now=new Date()}=context;activeDriver(database,employeeId,role);return withImmediateTransaction(database,()=>{const ended=stopContext(database,stopId);if(ended?.status==='completed'){if(ended.completion_outcome==='completed')return{stopId:Number(ended.id),status:'completed',completedAt:ended.completed_at,idempotent:true};throw fail('This Stop already ended as No Goods.','STOP_ALREADY_ENDED')};const stop=assertCurrentArrived(database,stopId,employeeId,kuchingDate(`${today}T00:00:00+08:00`));const bill=database.prepare(`SELECT pb.id,pb.bill_number,pb.payment_method,EXISTS(SELECT 1 FROM purchase_payment_proofs pp WHERE pp.purchase_bill_id=pb.id) payment_proof_uploaded FROM purchase_bills pb WHERE pb.dispatch_stop_id=? AND pb.status='issued'`).get(stop.id);if(!bill)throw fail('Create the electronic Purchase Bill before completing this Stop.','BILL_REQUIRED',409);if(bill.payment_method==='Cash'&&!bill.payment_proof_uploaded)throw fail('Upload the Cash payment proof before completing this Stop.','PAYMENT_PROOF_REQUIRED',409);const completedAt=nowKuching(now);database.prepare("UPDATE dispatch_stops SET status='completed',completion_outcome='completed',completed_at=?,completed_by_employee_id=?,payment_status=? WHERE id=? AND status='active'").run(completedAt,employeeId,bill.payment_method==='Cash'?'verified_for_route':'credit',stop.id);log(database,stop,'driver_stop_completed',employeeId,{status:'arrived'},{status:'completed',outcome:'completed',completedAt,billNumber:bill.bill_number,paymentMethod:bill.payment_method,paymentProofUploaded:Boolean(bill.payment_proof_uploaded)});return{stopId:Number(stop.id),status:'completed',completedAt,nextStopId:currentStop(database,stop.trip_id)?.id||null,idempotent:false}})}

const image=(photo,max=8*1024*1024)=>{const match=/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/.exec(String(photo?.dataUrl||''));if(!match)throw fail('A valid JPEG, PNG or WebP photo is required.','INVALID_PHOTO',400);const bytes=Buffer.from(match[2],'base64');if(!bytes.length||bytes.length>max)throw fail(`Photo must be no larger than ${Math.round(max/1024/1024)} MB.`,'INVALID_PHOTO',400);const type=match[1],valid=type==='image/jpeg'&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff||type==='image/png'&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))||type==='image/webp'&&bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP';if(!valid)throw fail('Photo content does not match its declared file type.','INVALID_PHOTO',400);return{bytes,type,extension:type.split('/')[1].replace('jpeg','jpg')}}
export function recordNoGoods(stopId,payload={},context={},database=defaultDb,{uploadsRoot}={}){const{employeeId,role,today=kuchingDate(),now=new Date()}=context;activeDriver(database,employeeId,role);const reason=String(payload.reason||'').trim();if(!reason)throw fail('No Goods reason is required.','REASON_REQUIRED',400);if(!uploadsRoot)throw fail('Secure upload storage is unavailable.','UPLOAD_UNAVAILABLE',500);const file=image(payload.photo),folder=path.resolve(uploadsRoot,'no-goods'),name=`${crypto.randomUUID()}.${file.extension}`,absolute=path.resolve(folder,name);if(!absolute.startsWith(folder+path.sep))throw fail('Invalid upload path.','INVALID_PHOTO',400);fs.mkdirSync(folder,{recursive:true});fs.writeFileSync(absolute,file.bytes,{flag:'wx'});try{return withImmediateTransaction(database,()=>{const ended=stopContext(database,stopId);if(ended?.status==='completed'){const proof=database.prepare('SELECT id,created_at FROM driver_no_goods_proofs WHERE dispatch_stop_id=?').get(ended.id);if(ended.completion_outcome==='no_goods'&&proof){fs.unlinkSync(absolute);return{stopId:Number(ended.id),status:'no_goods',proofId:Number(proof.id),completedAt:proof.created_at,idempotent:true}}throw fail('This Stop already ended as Completed.','STOP_ALREADY_ENDED')};const stop=assertCurrentArrived(database,stopId,employeeId,kuchingDate(`${today}T00:00:00+08:00`)),completedAt=nowKuching(now),storageKey=`no-goods/${name}`;const result=database.prepare('INSERT INTO driver_no_goods_proofs(dispatch_stop_id,dispatch_trip_id,driver_employee_id,vehicle_id,reason,storage_key,original_name,content_type,size_bytes,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(stop.id,stop.trip_id,employeeId,stop.vehicle_id,reason,storageKey,String(payload.photo?.name||`no-goods.${file.extension}`),file.type,file.bytes.length,completedAt);database.prepare("UPDATE dispatch_stops SET status='completed',completion_outcome='no_goods',completed_at=?,completed_by_employee_id=? WHERE id=? AND status='active'").run(completedAt,employeeId,stop.id);log(database,stop,'driver_stop_no_goods',employeeId,{status:'arrived'},{status:'completed',outcome:'no_goods',completedAt,proofId:Number(result.lastInsertRowid),reason});return{stopId:Number(stop.id),status:'no_goods',proofId:Number(result.lastInsertRowid),completedAt,nextStopId:currentStop(database,stop.trip_id)?.id||null,idempotent:false}})}catch(error){if(fs.existsSync(absolute))fs.unlinkSync(absolute);throw error}}

export function completeDriverTrip(tripId,context={},database=defaultDb){const{employeeId,role,today=kuchingDate(),now=new Date()}=context;activeDriver(database,employeeId,role);return withImmediateTransaction(database,()=>{const trip=assertOwnedToday(database,tripId,employeeId,kuchingDate(`${today}T00:00:00+08:00`));if(trip.execution_status==='completed')return{tripId:Number(trip.id),status:'completed',completedAt:trip.completed_at,idempotent:true};if(trip.execution_status!=='in_progress')throw fail('Only an In Progress Trip can be completed.');const open=database.prepare("SELECT id,status FROM dispatch_stops WHERE dispatch_trip_id=? AND status NOT IN ('cancelled','completed') ORDER BY stop_sequence").all(trip.id);if(open.length)throw fail(`Trip has ${open.length} unfinished Stop(s).`,'UNFINISHED_STOPS',409,{stopIds:open.map(x=>x.id)});const completedAt=nowKuching(now);database.prepare("UPDATE dispatch_trips SET execution_status='completed',completed_at=?,completed_by_employee_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND execution_status='in_progress'").run(completedAt,employeeId,trip.id);database.prepare("UPDATE dispatches SET status='completed',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(trip.dispatch_id);const remaining=database.prepare("SELECT COUNT(*) n FROM dispatch_trips WHERE dispatch_day_id=? AND execution_status<>'completed' AND EXISTS(SELECT 1 FROM dispatch_stops WHERE dispatch_trip_id=dispatch_trips.id AND status<>'cancelled')").get(trip.dispatch_day_id).n;if(!remaining)database.prepare("UPDATE dispatch_days SET status='completed',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(trip.dispatch_day_id);database.prepare(`INSERT INTO dispatch_change_logs(dispatch_day_id,actor,change_type,entity_type,entity_id,before_json,after_json,requires_reapproval) VALUES(?,?,'driver_trip_completed','dispatch_trip',?,?,?,0)`).run(trip.dispatch_day_id,String(employeeId),String(trip.id),JSON.stringify({status:'in_progress'}),JSON.stringify({status:'completed',completedAt,driverId:Number(employeeId),vehicleId:trip.vehicle_id}));return{tripId:Number(trip.id),status:'completed',completedAt,idempotent:false}})}
