import {db as defaultDb} from './database.mjs'
import {kuchingDate} from '../shared/kuchingTime.js'
import {withImmediateTransaction} from './branchServiceDateGuard.mjs'

export const ARRIVAL_RADIUS_METERS=Number(process.env.KCS_ARRIVAL_RADIUS_METERS||150)
export const MAX_ARRIVAL_ACCURACY_METERS=Number(process.env.KCS_MAX_ARRIVAL_ACCURACY_METERS||50)
const fail=(message,code='INVALID_STATUS',statusCode=409,details={})=>{const error=new Error(message);error.code=code;error.statusCode=statusCode;error.publicDetails=details;return error}
const nowKuching=(input=new Date())=>{const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuching',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(input)).map(part=>[part.type,part.value]));return`${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}:${parts.second}+08:00`}
const distanceMeters=(aLat,aLon,bLat,bLon)=>{const rad=value=>value*Math.PI/180,R=6371000,dLat=rad(bLat-aLat),dLon=rad(bLon-aLon),x=Math.sin(dLat/2)**2+Math.cos(rad(aLat))*Math.cos(rad(bLat))*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function activeDriver(database,employeeId,role){if(String(role).toLowerCase()!=='driver')throw fail('Only an active driver can perform this action.','PERMISSION_DENIED',403);const employee=database.prepare(`SELECT e.id FROM employees e WHERE e.id=? AND e.is_active=1 AND e.employment_status='active' AND (lower(e.job_role)='driver' OR EXISTS(SELECT 1 FROM employee_job_roles r WHERE r.employee_id=e.id AND r.role='Driver' AND r.is_active=1))`).get(Number(employeeId));if(!employee)throw fail('Only an active driver can perform this action.','PERMISSION_DENIED',403);return employee}
const tripContext=(database,tripId)=>database.prepare(`SELECT dt.*,dd.dispatch_date,dd.status day_status,d.vehicle_id,d.driver_id,d.status dispatch_status,v.operational_status,v.status vehicle_status
  FROM dispatch_trips dt JOIN dispatch_days dd ON dd.id=dt.dispatch_day_id JOIN dispatches d ON d.id=dt.dispatch_id JOIN vehicles v ON v.id=d.vehicle_id WHERE dt.id=?`).get(Number(tripId))
const assertOwnedToday=(database,tripId,employeeId,today)=>{const trip=tripContext(database,tripId);if(!trip)throw fail('Trip not found.','NOT_FOUND',404);if(trip.dispatch_date!==today)throw fail('Only today’s route can be operated.','PERMISSION_DENIED',403);if(Number(trip.driver_id)!==Number(employeeId))throw fail('This Trip is assigned to another driver.','PERMISSION_DENIED',403);if(!['available','active'].includes(trip.operational_status)||!['available','assigned'].includes(trip.vehicle_status))throw fail('The assigned vehicle is inactive.');return trip}

export function startDriverTrip(tripId,{employeeId,role,today=kuchingDate(),now=new Date()}={},database=defaultDb){
  activeDriver(database,employeeId,role);const serviceDate=kuchingDate(`${today}T00:00:00+08:00`)
  return withImmediateTransaction(database,()=>{const trip=assertOwnedToday(database,tripId,employeeId,serviceDate);if(trip.execution_status==='in_progress')return{tripId:Number(trip.id),status:'in_progress',startedAt:trip.started_at,idempotent:true};if(trip.execution_status==='completed')throw fail('This Trip is already completed.');if(!['approved','in_progress'].includes(trip.day_status))throw fail(`Only an Approved route can start; current status is ${trip.day_status}.`)
    const stopCount=database.prepare("SELECT COUNT(*) n FROM dispatch_stops WHERE dispatch_trip_id=? AND status<>'cancelled'").get(trip.id).n;if(!stopCount)throw fail('This Trip has no active Stops.')
    const running=database.prepare("SELECT dt.id FROM dispatch_trips dt JOIN dispatches d ON d.id=dt.dispatch_id WHERE dt.dispatch_day_id=? AND d.vehicle_id=? AND dt.execution_status='in_progress' AND dt.id<>? LIMIT 1").get(trip.dispatch_day_id,trip.vehicle_id,trip.id);if(running)throw fail(`Trip ${running.id} is already In Progress for this vehicle.`)
    const earlier=database.prepare(`SELECT dt.id,dt.trip_number FROM dispatch_trips dt JOIN dispatches d ON d.id=dt.dispatch_id WHERE dt.dispatch_day_id=? AND d.vehicle_id=? AND dt.trip_number<? AND dt.execution_status<>'completed' AND EXISTS(SELECT 1 FROM dispatch_stops ds WHERE ds.dispatch_trip_id=dt.id AND ds.status<>'cancelled') ORDER BY dt.trip_number LIMIT 1`).get(trip.dispatch_day_id,trip.vehicle_id,trip.trip_number);if(earlier)throw fail(`Trip ${earlier.trip_number} must be completed before starting Trip ${trip.trip_number}.`)
    const startedAt=nowKuching(now),before={status:trip.execution_status,startedAt:trip.started_at};database.prepare("UPDATE dispatch_trips SET execution_status='in_progress',started_at=?,started_by_employee_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND execution_status='not_started'").run(startedAt,employeeId,trip.id);database.prepare("UPDATE dispatches SET status='in_progress',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(trip.dispatch_id);database.prepare("UPDATE dispatch_days SET status='in_progress',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(trip.dispatch_day_id);database.prepare(`INSERT INTO dispatch_change_logs(dispatch_day_id,actor,change_type,entity_type,entity_id,before_json,after_json,requires_reapproval) VALUES(?,?,'driver_trip_started','dispatch_trip',?,?,?,0)`).run(trip.dispatch_day_id,String(employeeId),String(trip.id),JSON.stringify(before),JSON.stringify({status:'in_progress',startedAt,driverId:Number(employeeId),vehicleId:trip.vehicle_id}));return{tripId:Number(trip.id),status:'in_progress',startedAt,idempotent:false}
  })
}

export function arriveAtStop(stopId,payload={},context={},database=defaultDb){
  const{employeeId,role,today=kuchingDate(),now=new Date()}=context;activeDriver(database,employeeId,role);const latitude=Number(payload.latitude),longitude=Number(payload.longitude),accuracy=Number(payload.accuracy),capturedAt=new Date(payload.captured_at)
  if(!Number.isFinite(latitude)||latitude < -90||latitude > 90||!Number.isFinite(longitude)||longitude < -180||longitude > 180)throw fail('Invalid GPS coordinates.','INVALID_GPS',400)
  if(!Number.isFinite(accuracy)||accuracy<=0||accuracy>MAX_ARRIVAL_ACCURACY_METERS)throw fail(`GPS accuracy ${Number.isFinite(accuracy)?Math.round(accuracy):'unknown'}m is insufficient; required accuracy is ${MAX_ARRIVAL_ACCURACY_METERS}m or better.`,'GPS_ACCURACY_POOR',400,{accuracyMeters:Number.isFinite(accuracy)?Math.round(accuracy):'unknown',maximumAccuracyMeters:MAX_ARRIVAL_ACCURACY_METERS})
  if(Number.isNaN(capturedAt.getTime())||Math.abs(new Date(now).getTime()-capturedAt.getTime())>15*60*1000)throw fail('GPS capture time is invalid or stale.','GPS_CAPTURE_STALE',400)
  return withImmediateTransaction(database,()=>{const stop=database.prepare(`SELECT ds.*,dt.execution_status,dt.id trip_id,dd.id day_id,dd.dispatch_date,dd.status day_status,d.vehicle_id,d.driver_id,b.latitude branch_latitude,b.longitude branch_longitude
      FROM dispatch_stops ds JOIN dispatch_trips dt ON dt.id=ds.dispatch_trip_id JOIN dispatch_days dd ON dd.id=dt.dispatch_day_id JOIN dispatches d ON d.id=dt.dispatch_id JOIN branches b ON b.id=ds.branch_id WHERE ds.id=?`).get(Number(stopId));if(!stop)throw fail('Stop not found.','NOT_FOUND',404);assertOwnedToday(database,stop.trip_id,employeeId,kuchingDate(`${today}T00:00:00+08:00`));if(stop.arrived_at)return{stopId:Number(stop.id),status:'arrived',arrivedAt:stop.arrived_at,distanceMeters:stop.arrival_distance_m,idempotent:true};if(stop.execution_status!=='in_progress'||stop.day_status!=='in_progress')throw fail('The Trip is not In Progress.');const current=database.prepare("SELECT id,stop_sequence FROM dispatch_stops WHERE dispatch_trip_id=? AND status NOT IN ('cancelled','completed') ORDER BY stop_sequence,id LIMIT 1").get(stop.trip_id);if(!current||Number(current.id)!==Number(stop.id))throw fail(`Stop ${current?.id||'unknown'} must be handled first.`,'STOP_SEQUENCE_REQUIRED',409,{currentStopId:current?.id||null});if(stop.branch_latitude==null||stop.branch_longitude==null)throw fail('Customer GPS not set, please contact the supervisor.','CUSTOMER_GPS_NOT_SET',409)
    const distance=Math.round(distanceMeters(latitude,longitude,Number(stop.branch_latitude),Number(stop.branch_longitude)));if(distance>ARRIVAL_RADIUS_METERS)throw fail(`You are ${distance}m from the Customer; allowed arrival radius is ${ARRIVAL_RADIUS_METERS}m (GPS accuracy ${Math.round(accuracy)}m).`,'ARRIVAL_OUT_OF_RANGE',409,{distanceMeters:distance,allowedRadiusMeters:ARRIVAL_RADIUS_METERS,accuracyMeters:accuracy});const arrivedAt=nowKuching(now),before={status:stop.status,arrivedAt:null};database.prepare("UPDATE dispatch_stops SET status='active',arrived_at=?,arrival_latitude=?,arrival_longitude=?,arrival_accuracy_m=?,arrival_distance_m=?,arrival_captured_at=?,arrived_by_employee_id=? WHERE id=? AND arrived_at IS NULL").run(arrivedAt,latitude,longitude,accuracy,distance,capturedAt.toISOString(),employeeId,stop.id);database.prepare(`INSERT INTO dispatch_change_logs(dispatch_day_id,actor,change_type,entity_type,entity_id,before_json,after_json,requires_reapproval) VALUES(?,?,'driver_stop_arrived','dispatch_stop',?,?,?,0)`).run(stop.day_id,String(employeeId),String(stop.id),JSON.stringify(before),JSON.stringify({status:'arrived',arrivedAt,latitude,longitude,accuracy,distanceMeters:distance,driverId:Number(employeeId)}));return{stopId:Number(stop.id),status:'arrived',arrivedAt,distanceMeters:distance,accuracyMeters:accuracy,idempotent:false}
  })
}
