import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import {db as defaultDb,uploadsDir} from './database.mjs'
import {getEmployeeMaster} from './resourceService.mjs'

const text=value=>String(value??'').trim()
const sensitiveColumns={nationalIdNumber:'national_id_number',bankAccountNumber:'bank_account_number',epfNumber:'epf_number',socsoNumber:'socso_number'}
const sensitiveHistory=new Set(Object.values(sensitiveColumns))
const mask=value=>text(value)?`${'*'.repeat(Math.max(4,text(value).length-4))}${text(value).slice(-4)}`:null
const audit=(database,employeeId,session,action,field,reason,meta={})=>database.prepare(`INSERT INTO employee_sensitive_access_logs(employee_id,account_id,action,field_name,reason,actor,ip_address) VALUES(?,?,?,?,?,?,?)`).run(employeeId,session.id,action,field,text(reason)||null,session.username||session.employeeName,meta.ipAddress||null)

export function employeeDetail(id,{canViewSensitive=false}={},database=defaultDb){const item=getEmployeeMaster(id,database);if(!item)return null;const history=database.prepare('SELECT id,field_name fieldName,old_value oldValue,new_value newValue,reason,changed_by changedBy,changed_at changedAt FROM employee_change_history WHERE employee_id=? ORDER BY id DESC LIMIT 200').all(id).map(row=>sensitiveHistory.has(row.fieldName)&&!canViewSensitive?{...row,oldValue:mask(row.oldValue),newValue:mask(row.newValue)}:row);const documents=canViewSensitive?database.prepare(`SELECT id,document_type documentType,original_name originalName,content_type contentType,uploaded_by uploadedBy,uploaded_at uploadedAt FROM employee_documents WHERE employee_id=? AND is_active=1 ORDER BY document_type,uploaded_at DESC`).all(id):[];return{...item,history,documents,canViewSensitive}}

export function revealEmployeeField(id,field,reason,session,meta={},database=defaultDb){const column=sensitiveColumns[field];if(!column)throw new Error('Unsupported sensitive field');if(!text(reason))throw new Error('查看敏感资料必须填写原因');const row=database.prepare(`SELECT ${column} value FROM employees WHERE id=?`).get(id);if(!row)throw new Error('Employee not found');audit(database,id,session,'view',field,reason,meta);return{field,value:row.value||null}}

export function addEmployeeDocument(id,payload,session,meta={},database=defaultDb){if(!['ic_front','ic_back'].includes(payload.documentType))throw new Error('Invalid employee document type');const match=String(payload.file?.dataUrl||'').match(/^data:([^;,]+);base64,(.+)$/);if(!match)throw new Error('IC image is required');const buffer=Buffer.from(match[2],'base64');if(!buffer.length||buffer.length>8_000_000)throw new Error('IC image must be between 1 byte and 8 MB');const ext=({'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp'})[match[1]];if(!ext)throw new Error('Only JPG, PNG or WEBP images are allowed');const employee=database.prepare('SELECT id FROM employees WHERE id=?').get(id);if(!employee)throw new Error('Employee not found');const folder=path.join(uploadsDir,'employee-documents'),storageKey=path.join('employee-documents',`${crypto.randomUUID()}${ext}`);fs.mkdirSync(folder,{recursive:true});fs.writeFileSync(path.join(uploadsDir,storageKey),buffer,{flag:'wx'});database.exec('BEGIN IMMEDIATE');try{database.prepare('UPDATE employee_documents SET is_active=0,replaced_at=CURRENT_TIMESTAMP WHERE employee_id=? AND document_type=? AND is_active=1').run(id,payload.documentType);const result=database.prepare(`INSERT INTO employee_documents(employee_id,document_type,storage_key,original_name,content_type,uploaded_by) VALUES(?,?,?,?,?,?)`).run(id,payload.documentType,storageKey,text(payload.file.name)||'identity-document',match[1],session.username||session.employeeName);audit(database,id,session,'replace',payload.documentType,payload.reason,meta);database.exec('COMMIT');return{id:Number(result.lastInsertRowid),documentType:payload.documentType}}catch(error){database.exec('ROLLBACK');try{fs.unlinkSync(path.join(uploadsDir,storageKey))}catch{}throw error}}

export function employeeDocumentFile(documentId,session,reason,meta={},database=defaultDb){const row=database.prepare('SELECT * FROM employee_documents WHERE id=? AND is_active=1').get(documentId);if(!row)throw new Error('Employee document not found');if(!text(reason))throw new Error('下载证件必须填写原因');const absolute=path.resolve(uploadsDir,row.storage_key),root=path.resolve(uploadsDir)+path.sep;if(!absolute.startsWith(root)||!fs.existsSync(absolute))throw new Error('Employee document file not found');audit(database,row.employee_id,session,'download',row.document_type,reason,meta);return{absolute,contentType:row.content_type||'application/octet-stream',fileName:`employee-document-${row.id}${path.extname(absolute)}`}}

export function sensitiveAccessLogs(employeeId,database=defaultDb){return database.prepare(`SELECT id,action,field_name fieldName,reason,actor,ip_address ipAddress,created_at createdAt FROM employee_sensitive_access_logs WHERE employee_id=? ORDER BY id DESC LIMIT 200`).all(employeeId)}

export function sensitiveEmployeeExport(reason,session,meta={},database=defaultDb){if(!text(reason))throw new Error('敏感资料导出必须填写用途');const rows=database.prepare(`SELECT employee_code 'Employee Code',name 'Employee Name',national_id_number 'IC Number',bank_name 'Bank Name',bank_account_number 'Bank Account Number',bank_account_holder_name 'Bank Account Holder Name',epf_number 'EPF Number',socso_number 'SOCSO Number' FROM employees ORDER BY name`).all();for(const employee of database.prepare('SELECT id FROM employees').all())audit(database,employee.id,session,'export','sensitive_employee_export',reason,meta);return{module:'employee_sensitive',label:'Employee Sensitive Payroll Export',columns:['Employee Code','Employee Name','IC Number','Bank Name','Bank Account Number','Bank Account Holder Name','EPF Number','SOCSO Number'],rows,fileName:`KCS_Employee_Sensitive_${new Date().toISOString().replace(/[-:]/g,'').slice(0,15)}`}}
