import crypto from 'node:crypto'
import { db as defaultDb } from './database.mjs'
import {invalidateDispatchDay} from './dispatchService.mjs'
import {recalculateRecommendations} from './gpsRecommendationService.mjs'

const text=value=>String(value??'').trim()
const value=(row,names)=>{for(const name of names){const key=Object.keys(row||{}).find(item=>item.trim().toLowerCase()===name.toLowerCase());if(key!=null&&text(row[key]))return row[key]}return null}
const validGps=(lat,lng)=>Number.isFinite(lat)&&Number.isFinite(lng)&&lat>=-90&&lat<=90&&lng>=-180&&lng<=180&&!(lat===0&&lng===0)
const sameGps=(a,b,c,d)=>[a,b,c,d].every(Number.isFinite)&&Math.abs(a-c)<0.000001&&Math.abs(b-d)<0.000001
const summary=rows=>Object.fromEntries(['new','unchanged','conflict','branch_not_found','invalid_gps','duplicate_source'].map(type=>[type,rows.filter(row=>row.classification===type).length]))
const rowView=row=>({...row,raw:row.raw_json?JSON.parse(row.raw_json):null})
function applyOfficialGps(database,branch,row,actor,reason){const before={latitude:branch.latitude,longitude:branch.longitude},after={latitude:row.latitude,longitude:row.longitude};database.prepare(`UPDATE branches SET latitude=?,longitude=?,gps_status='Supervisor Confirmed Migration',gps_verified_at=CURRENT_TIMESTAMP,gps_remark=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(row.latitude,row.longitude,reason||'Imported from legacy Jodoo GPS migration',branch.id);database.prepare(`INSERT INTO master_change_history(entity_type,entity_id,change_type,before_json,after_json,reason,changed_by) VALUES('branch',?,'official_gps_migrated',?,?,?,?)`).run(row.branch_id_text,JSON.stringify(before),JSON.stringify(after),reason||null,actor);const dates=database.prepare(`SELECT DISTINCT dd.dispatch_date FROM dispatch_days dd JOIN dispatch_trips dt ON dt.dispatch_day_id=dd.id JOIN dispatch_stops ds ON ds.dispatch_trip_id=dt.id WHERE ds.branch_id=? AND dd.dispatch_date>=date('now','localtime')`).all(branch.id);for(const item of dates)invalidateDispatchDay(database,item.dispatch_date,'official_gps_migrated','branch',branch.id,before,after,actor)}

export function previewGpsMigration(payload,actor='Supervisor',database=defaultDb){
  const rows=Array.isArray(payload.rows)?payload.rows:[];if(!rows.length)throw new Error('GPS migration file has no rows')
  const canonical=JSON.stringify(rows),hash=text(payload.fileHash)||crypto.createHash('sha256').update(canonical).digest('hex'),existing=database.prepare('SELECT * FROM gps_migration_batches WHERE file_hash=?').get(hash)
  if(existing)return getGpsMigrationBatch(existing.id,database)
  const seen=new Map(),prepared=rows.map((source,index)=>{const branchId=text(value(source,['BranchID','Branch ID','Branch Id','branch_id'])),customerId=text(value(source,['CustomerID','Customer ID'])),latitude=Number(value(source,['Latitude','Lat','GPS Latitude'])),longitude=Number(value(source,['Longitude','Lng','Long','GPS Longitude']));const branch=branchId?database.prepare('SELECT id,latitude,longitude FROM branches WHERE jodoo_branch_id=?').get(branchId):null;let classification=!validGps(latitude,longitude)?'invalid_gps':!branch?'branch_not_found':validGps(Number(branch.latitude),Number(branch.longitude))?(sameGps(latitude,longitude,Number(branch.latitude),Number(branch.longitude))?'unchanged':'conflict'):'new';const key=branchId;if(key&&seen.has(key)&&!sameGps(latitude,longitude,seen.get(key).latitude,seen.get(key).longitude))classification='duplicate_source';else if(key)seen.set(key,{latitude,longitude});return{rowNumber:index+2,branchId,customerId,customerName:text(value(source,['Customer Name','CustomerName'])),branchName:text(value(source,['Branch Name','BranchName'])),latitude,longitude,oldLatitude:branch?.latitude??null,oldLongitude:branch?.longitude??null,classification,raw:source}})
  const counts=summary(prepared);database.exec('BEGIN IMMEDIATE');try{const batch=database.prepare(`INSERT INTO gps_migration_batches(file_name,file_hash,status,summary_json,created_by) VALUES(?,?,'previewed',?,?)`).run(text(payload.fileName)||'GPS Migration',hash,JSON.stringify(counts),actor);const insert=database.prepare(`INSERT INTO gps_migration_rows(batch_id,row_number,branch_id_text,customer_id_text,customer_name,branch_name,latitude,longitude,old_latitude,old_longitude,classification,raw_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`);for(const row of prepared)insert.run(batch.lastInsertRowid,row.rowNumber,row.branchId||null,row.customerId||null,row.customerName||null,row.branchName||null,Number.isFinite(row.latitude)?row.latitude:null,Number.isFinite(row.longitude)?row.longitude:null,row.oldLatitude,row.oldLongitude,row.classification,JSON.stringify(row.raw));database.exec('COMMIT');return getGpsMigrationBatch(Number(batch.lastInsertRowid),database)}catch(error){database.exec('ROLLBACK');throw error}
}

export function getGpsMigrationBatch(id,database=defaultDb){const batch=database.prepare('SELECT * FROM gps_migration_batches WHERE id=?').get(id);if(!batch)throw new Error('GPS migration batch not found');return{...batch,summary:JSON.parse(batch.summary_json),rows:database.prepare('SELECT * FROM gps_migration_rows WHERE batch_id=? ORDER BY row_number').all(id).map(rowView)}}
export function listGpsMigrationBatches(database=defaultDb){return database.prepare('SELECT id,file_name fileName,file_hash fileHash,status,summary_json summary,created_by createdBy,created_at createdAt,committed_at committedAt FROM gps_migration_batches ORDER BY id DESC').all().map(row=>({...row,summary:JSON.parse(row.summary)}))}

export function commitGpsMigration(id,actor='Supervisor',database=defaultDb){const batch=getGpsMigrationBatch(id,database);if(batch.status==='committed')return batch;const changed=[];database.exec('BEGIN IMMEDIATE');try{for(const row of batch.rows){if(row.classification!=='new')continue;const branch=database.prepare('SELECT id,latitude,longitude FROM branches WHERE jodoo_branch_id=?').get(row.branch_id_text);if(!branch||validGps(Number(branch.latitude),Number(branch.longitude)))continue;applyOfficialGps(database,branch,row,actor,'Branch had no official GPS; approved legacy migration');changed.push(branch.id);database.prepare(`UPDATE gps_migration_rows SET decision='import_new',decision_reason='Branch had no official GPS',decided_by=?,decided_at=CURRENT_TIMESTAMP WHERE id=?`).run(actor,row.id)}database.prepare(`UPDATE gps_migration_batches SET status='committed',committed_at=CURRENT_TIMESTAMP WHERE id=?`).run(id);database.exec('COMMIT')}catch(error){database.exec('ROLLBACK');throw error}if(changed.length)recalculateRecommendations({branchIds:changed,changedBy:actor},database);return getGpsMigrationBatch(id,database)}

export function resolveGpsMigrationRow(rowId,payload,actor='Supervisor',database=defaultDb){const row=database.prepare('SELECT * FROM gps_migration_rows WHERE id=?').get(rowId);if(!row)throw new Error('GPS migration row not found');const decision=text(payload.decision);if(!['keep_official','use_imported','reject'].includes(decision))throw new Error('Invalid migration decision');let changedBranch=null;if(decision==='use_imported'){if(!validGps(Number(row.latitude),Number(row.longitude)))throw new Error('Invalid GPS');const branch=database.prepare('SELECT id,latitude,longitude FROM branches WHERE jodoo_branch_id=?').get(row.branch_id_text);if(!branch)throw new Error('Branch not found');applyOfficialGps(database,branch,row,actor,text(payload.reason)||'Supervisor approved legacy GPS');changedBranch=branch.id}database.prepare(`UPDATE gps_migration_rows SET decision=?,decision_reason=?,decided_by=?,decided_at=CURRENT_TIMESTAMP WHERE id=?`).run(decision,text(payload.reason)||null,actor,rowId);if(changedBranch)recalculateRecommendations({branchIds:[changedBranch],changedBy:actor},database);return rowView(database.prepare('SELECT * FROM gps_migration_rows WHERE id=?').get(rowId))}

export function gpsMigrationTemplate(){return{columns:['BranchID','CustomerID','Customer Name','Branch Name','Latitude','Longitude'],rows:[]}}
