import { db as defaultDb } from './database.mjs'

const validCoordinate=(latitude,longitude)=>Number.isFinite(Number(latitude))&&Number.isFinite(Number(longitude))&&Number(latitude)>=-90&&Number(latitude)<=90&&Number(longitude)>=-180&&Number(longitude)<=180
const validGps=(latitude,longitude)=>validCoordinate(latitude,longitude)&&!(Number(latitude)===0&&Number(longitude)===0)
const radians=value=>value*Math.PI/180
export function distanceMeters(a,b){const earth=6371000,dLat=radians(b.lat-a.lat),dLng=radians(b.lng-a.lng),value=Math.sin(dLat/2)**2+Math.cos(radians(a.lat))*Math.cos(radians(b.lat))*Math.sin(dLng/2)**2;return 2*earth*Math.asin(Math.sqrt(value))}

function normalizePoint(point){const lat=Number(Array.isArray(point)?point[0]:point.lat),lng=Number(Array.isArray(point)?point[1]:point.lng);if(!validCoordinate(lat,lng))throw new Error('Polygon contains invalid latitude or longitude');return{lat,lng}}
export function normalizePolygon(polygon){if(!Array.isArray(polygon)||polygon.length<3)throw new Error('Zone polygon requires at least three points');const points=polygon.map(normalizePoint);if(points.length>3&&points[0].lat===points.at(-1).lat&&points[0].lng===points.at(-1).lng)points.pop();if(points.length<3)throw new Error('Zone polygon requires at least three different points');return points}
function onSegment(point,a,b){const cross=(point.lng-a.lng)*(b.lat-a.lat)-(point.lat-a.lat)*(b.lng-a.lng);if(Math.abs(cross)>1e-9)return false;return point.lng>=Math.min(a.lng,b.lng)-1e-9&&point.lng<=Math.max(a.lng,b.lng)+1e-9&&point.lat>=Math.min(a.lat,b.lat)-1e-9&&point.lat<=Math.max(a.lat,b.lat)+1e-9}
export function pointInPolygon(point,polygon){for(let index=0;index<polygon.length;index++)if(onSegment(point,polygon[index],polygon[(index+1)%polygon.length]))return'boundary';let inside=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j],crosses=(a.lat>point.lat)!==(b.lat>point.lat)&&point.lng<(b.lng-a.lng)*(point.lat-a.lat)/(b.lat-a.lat)+a.lng;if(crosses)inside=!inside}return inside?'inside':'outside'}
function segmentDistanceMeters(point,a,b){const mean=radians((point.lat+a.lat+b.lat)/3),scaleX=111320*Math.cos(mean),scaleY=110540,px=0,py=0,ax=(a.lng-point.lng)*scaleX,ay=(a.lat-point.lat)*scaleY,bx=(b.lng-point.lng)*scaleX,by=(b.lat-point.lat)*scaleY,dx=bx-ax,dy=by-ay,length=dx*dx+dy*dy,t=length?Math.max(0,Math.min(1,-(ax*dx+ay*dy)/length)):0,x=ax+t*dx,y=ay+t*dy;return Math.hypot(x-px,y-py)}
export function distanceToPolygonMeters(point,polygon){return Math.min(...polygon.map((a,index)=>segmentDistanceMeters(point,a,polygon[(index+1)%polygon.length])))}
function orientation(a,b,c){const value=(b.lng-a.lng)*(c.lat-a.lat)-(b.lat-a.lat)*(c.lng-a.lng);return Math.abs(value)<1e-9?0:value>0?1:-1}
function segmentsCross(a,b,c,d){const o1=orientation(a,b,c),o2=orientation(a,b,d),o3=orientation(c,d,a),o4=orientation(c,d,b);return o1!==0&&o2!==0&&o3!==0&&o4!==0&&o1!==o2&&o3!==o4}
export function polygonsOverlap(first,second){for(let i=0;i<first.length;i++)for(let j=0;j<second.length;j++)if(segmentsCross(first[i],first[(i+1)%first.length],second[j],second[(j+1)%second.length]))return true;if(first.some(point=>pointInPolygon(point,second)==='inside')||second.some(point=>pointInPolygon(point,first)==='inside'))return true;return pointInPolygon(polygonCenter(first),second)==='inside'&&pointInPolygon(polygonCenter(second),first)==='inside'}

const boundarySelect=`SELECT zb.id,zb.zone_group_id zoneGroupId,z.name zoneGroup,zb.boundary_version boundaryVersion,zb.polygon_json polygonJson,zb.center_latitude centerLatitude,zb.center_longitude centerLongitude,zb.effective_date effectiveDate,zb.is_active isActive,zb.created_by createdBy,zb.created_at createdAt FROM zone_boundaries zb JOIN zone_groups z ON z.id=zb.zone_group_id`
const boundaryView=row=>({...row,polygon:row.polygonJson?JSON.parse(row.polygonJson):null,polygonJson:undefined})
export function listZoneBoundaries({includeHistory=false}={},database=defaultDb){const rows=database.prepare(`${boundarySelect}${includeHistory?'':' WHERE zb.is_active=1'} ORDER BY z.sort_order,zb.boundary_version DESC`).all().map(boundaryView);const active=rows.filter(row=>row.isActive&&row.effectiveDate<=new Date().toISOString().slice(0,10)&&row.polygon?.length>=3);const overlaps=[];for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++)if(polygonsOverlap(active[i].polygon,active[j].polygon))overlaps.push({firstBoundaryId:active[i].id,firstZone:active[i].zoneGroup,secondBoundaryId:active[j].id,secondZone:active[j].zoneGroup});const official=database.prepare(`SELECT id,jodoo_branch_id branchId,branch_name branchName,latitude,longitude FROM branches WHERE latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180 AND NOT(latitude=0 AND longitude=0)`).all(),uncovered=official.filter(branch=>!active.some(boundary=>pointInPolygon({lat:branch.latitude,lng:branch.longitude},boundary.polygon)!=='outside')).map(({id,branchId,branchName,latitude,longitude})=>({id,branchId,branchName,latitude,longitude}));return{items:rows,overlaps,uncoveredBranchCount:uncovered.length,uncoveredBranches:uncovered.slice(0,100)}}

function polygonCenter(points){return{lat:points.reduce((sum,item)=>sum+item.lat,0)/points.length,lng:points.reduce((sum,item)=>sum+item.lng,0)/points.length}}
export function saveZoneBoundary(zoneGroupId,payload,database=defaultDb){const zone=database.prepare('SELECT * FROM zone_groups WHERE id=?').get(zoneGroupId);if(!zone)throw new Error('Zone Group not found');const polygon=payload.polygon?.length?normalizePolygon(payload.polygon):null,providedCenter=validCoordinate(payload.centerLatitude,payload.centerLongitude)?{lat:Number(payload.centerLatitude),lng:Number(payload.centerLongitude)}:null,center=providedCenter||(polygon?polygonCenter(polygon):null);if(!polygon&&!center)throw new Error('Provide a polygon or a valid Zone center');const version=database.prepare('SELECT COALESCE(MAX(boundary_version),0)+1 value FROM zone_boundaries WHERE zone_group_id=?').get(zoneGroupId).value,effectiveDate=payload.effectiveDate||new Date().toISOString().slice(0,10),actor=String(payload.changedBy||'Supervisor');database.exec('BEGIN IMMEDIATE');try{database.prepare('UPDATE zone_boundaries SET is_active=0 WHERE zone_group_id=? AND is_active=1').run(zoneGroupId);const result=database.prepare(`INSERT INTO zone_boundaries(zone_group_id,boundary_version,polygon_json,center_latitude,center_longitude,effective_date,is_active,created_by) VALUES(?,?,?,?,?,?,?,?)`).run(zoneGroupId,version,polygon?JSON.stringify(polygon):null,center.lat,center.lng,effectiveDate,payload.isActive===false?0:1,actor);database.prepare(`INSERT INTO audit_logs(action,entity_type,entity_id,after_json) VALUES('zone_boundary_version_saved','zone_boundary',?,?)`).run(String(result.lastInsertRowid),JSON.stringify({zoneGroupId,version,polygon,center,effectiveDate,changedBy:actor}));database.exec('COMMIT');recalculateRecommendations({},database);return boundaryView(database.prepare(`${boundarySelect} WHERE zb.id=?`).get(result.lastInsertRowid))}catch(error){database.exec('ROLLBACK');throw error}}

function activeBoundaries(database){const today=new Date().toISOString().slice(0,10),rows=database.prepare(`${boundarySelect} WHERE zb.is_active=1 AND zb.effective_date<=? AND zb.polygon_json IS NOT NULL ORDER BY zb.boundary_version DESC`).all(today).map(boundaryView),seen=new Set();return rows.filter(row=>!seen.has(row.zoneGroupId)&&seen.add(row.zoneGroupId))}
function branchZoneId(database,areaId){return database.prepare('SELECT COALESCE(confirmed_zone_group_id,zone_group_id) zoneId FROM areas WHERE id=?').get(areaId)?.zoneId??null}
function nearestOfficialBranch(database,point,{zoneGroupId,excludeBranchId}={}){const where=[`b.id<>?`,`b.latitude BETWEEN -90 AND 90`,`b.longitude BETWEEN -180 AND 180`,`NOT(b.latitude=0 AND b.longitude=0)`],args=[excludeBranchId||0];if(zoneGroupId){where.push('COALESCE(a.confirmed_zone_group_id,a.zone_group_id)=?');args.push(zoneGroupId)}const rows=database.prepare(`SELECT b.id,b.jodoo_branch_id branchId,b.branch_name branchName,b.latitude,b.longitude,b.area_id areaId,a.name areaName,COALESCE(a.confirmed_zone_group_id,a.zone_group_id) zoneGroupId,z.name zoneGroup FROM branches b LEFT JOIN areas a ON a.id=b.area_id LEFT JOIN zone_groups z ON z.id=COALESCE(a.confirmed_zone_group_id,a.zone_group_id) WHERE ${where.join(' AND ')}`).all(...args);return rows.map(row=>({...row,distanceMeters:distanceMeters(point,{lat:row.latitude,lng:row.longitude})})).sort((a,b)=>a.distanceMeters-b.distanceMeters)[0]||null}
function nearestArea(database,point,zoneGroupId){const where=zoneGroupId?'AND COALESCE(a.confirmed_zone_group_id,a.zone_group_id)=?':'',args=zoneGroupId?[zoneGroupId]:[],rows=database.prepare(`SELECT a.id,a.name,COALESCE(a.confirmed_zone_group_id,a.zone_group_id) zoneGroupId,z.name zoneGroup,AVG(b.latitude) latitude,AVG(b.longitude) longitude,COUNT(*) pointCount FROM areas a JOIN branches b ON b.area_id=a.id LEFT JOIN zone_groups z ON z.id=COALESCE(a.confirmed_zone_group_id,a.zone_group_id) WHERE b.latitude BETWEEN -90 AND 90 AND b.longitude BETWEEN -180 AND 180 AND NOT(b.latitude=0 AND b.longitude=0) ${where} GROUP BY a.id`).all(...args);return rows.map(row=>({...row,distanceMeters:distanceMeters(point,{lat:row.latitude,lng:row.longitude})})).sort((a,b)=>a.distanceMeters-b.distanceMeters)[0]||null}

export function calculateRecommendation(branchId,database=defaultDb){const branch=database.prepare(`SELECT b.*,a.name areaName,COALESCE(a.confirmed_zone_group_id,a.zone_group_id) currentZoneGroupId,z.name currentZoneGroup FROM branches b LEFT JOIN areas a ON a.id=b.area_id LEFT JOIN zone_groups z ON z.id=COALESCE(a.confirmed_zone_group_id,a.zone_group_id) WHERE b.id=?`).get(branchId);if(!branch)throw new Error('Branch not found');if(!validGps(branch.latitude,branch.longitude)){const temporary=database.prepare('SELECT COUNT(*) count FROM temporary_locations WHERE branch_id=?').get(branchId).count;return{branchId,officialLatitude:null,officialLongitude:null,currentAreaId:branch.area_id,currentZoneGroupId:branch.currentZoneGroupId,recommendedAreaId:null,recommendedZoneGroupId:null,boundaryId:null,matchType:'no_gps',confidence:'none',boundaryConflict:0,nearestDistanceM:null,status:'no_gps',reason:{summary:'没有正式 GPS，无法产生 Zone 建议。',temporaryGpsIgnored:temporary>0,signals:temporary?[`发现 ${temporary} 条 temporary GPS，但未用于计算。`]:[]}}}
  const point={lat:branch.latitude,lng:branch.longitude},boundaries=activeBoundaries(database),matches=boundaries.map(boundary=>({...boundary,relation:pointInPolygon(point,boundary.polygon)})).filter(item=>item.relation!=='outside'),nearestCustomer=nearestOfficialBranch(database,point,{excludeBranchId:branchId});let recommendedZoneGroupId=null,recommendedAreaId=null,boundaryId=null,matchType='no_polygon',confidence='low',boundaryConflict=0,nearestDistanceM=nearestCustomer?.distanceMeters??null,summary='',signals=[]
  if(matches.length>1){boundaryConflict=1;matchType='overlap';confidence='medium';summary=`GPS 同时落在 ${matches.length} 个重叠 Zone，必须主管确认。`;signals=matches.map(item=>`${item.zoneGroup} (${item.relation})`)}
  else if(matches.length===1){const match=matches[0];recommendedZoneGroupId=match.zoneGroupId;boundaryId=match.id;matchType=match.relation;confidence=match.relation==='inside'?'high':'medium';summary=match.relation==='inside'?`正式 GPS 位于 ${match.zoneGroup} 边界内部。`:`正式 GPS 位于 ${match.zoneGroup} 边界线上，需主管检查。`;const area=nearestArea(database,point,recommendedZoneGroupId);recommendedAreaId=area?.id??null;nearestDistanceM=area?.distanceMeters??nearestDistanceM;signals=[`Polygon v${match.boundaryVersion}`,area?`同 Zone 最近 Area：${area.name}，约 ${Math.round(area.distanceMeters)}m`:'该 Zone 暂无足够 Area GPS']}
  else if(boundaries.length){const nearest=boundaries.map(boundary=>({...boundary,distanceMeters:distanceToPolygonMeters(point,boundary.polygon)})).sort((a,b)=>a.distanceMeters-b.distanceMeters)[0];recommendedZoneGroupId=nearest.zoneGroupId;boundaryId=nearest.id;matchType='outside';confidence='low';nearestDistanceM=nearest.distanceMeters;summary=`正式 GPS 不在任何 Zone 内；最近边界为 ${nearest.zoneGroup}，约 ${Math.round(nearest.distanceMeters)}m。`;const area=nearestArea(database,point,recommendedZoneGroupId);recommendedAreaId=area?.id??null;signals=[area?`最近候选 Area：${area.name}`:'候选 Zone 内没有足够 Area GPS','建议主管检查边界或客户 GPS']}
  else{const area=nearestArea(database,point),centers=database.prepare(`SELECT z.id,z.name,zb.center_latitude latitude,zb.center_longitude longitude FROM zone_groups z JOIN zone_boundaries zb ON zb.zone_group_id=z.id WHERE zb.is_active=1 AND zb.center_latitude IS NOT NULL AND zb.center_longitude IS NOT NULL`).all().map(row=>({...row,distanceMeters:distanceMeters(point,{lat:row.latitude,lng:row.longitude})})).sort((a,b)=>a.distanceMeters-b.distanceMeters),center=centers[0];recommendedAreaId=area?.id??nearestCustomer?.areaId??null;recommendedZoneGroupId=area?.zoneGroupId??nearestCustomer?.zoneGroupId??center?.id??null;nearestDistanceM=area?.distanceMeters??nearestCustomer?.distanceMeters??center?.distanceMeters??null;confidence=area&&nearestCustomer&&area.id===nearestCustomer.areaId?'medium':'low';summary='当前没有可用 Zone polygon，仅提供多项辅助信号，不能自动确认。';signals=[nearestCustomer?`最近正式 GPS 客户：${nearestCustomer.branchName}，约 ${Math.round(nearestCustomer.distanceMeters)}m`:'没有附近正式 GPS 客户',area?`最近 Area GPS 中心：${area.name}，约 ${Math.round(area.distanceMeters)}m`:'没有 Area GPS 中心',center?`最近 Zone 中心：${center.name}，约 ${Math.round(center.distanceMeters)}m`:'没有 Zone 中心','没有道路距离矩阵；距离为直线近似并结合客户、Area、Zone 多项信号']}
  const recommendedZoneName=recommendedZoneGroupId?database.prepare('SELECT name FROM zone_groups WHERE id=?').get(recommendedZoneGroupId)?.name:null,recommendedAreaName=recommendedAreaId?database.prepare('SELECT name FROM areas WHERE id=?').get(recommendedAreaId)?.name:null
  return{branchId,officialLatitude:branch.latitude,officialLongitude:branch.longitude,currentAreaId:branch.area_id,currentZoneGroupId:branch.currentZoneGroupId,recommendedAreaId,recommendedZoneGroupId,boundaryId,matchType,confidence,boundaryConflict,nearestDistanceM,status:'pending',reason:{summary,signals,recommendationOnly:true,nearestCustomer:nearestCustomer?{branchId:nearestCustomer.branchId,branchName:nearestCustomer.branchName,distanceMeters:Math.round(nearestCustomer.distanceMeters)}:null,recommendedZoneName,recommendedAreaName}}
}

function saveRecommendation(item,database){const reason=JSON.stringify(item.reason);database.prepare(`INSERT INTO gps_zone_recommendations(branch_id,official_latitude,official_longitude,current_area_id,current_zone_group_id,recommended_area_id,recommended_zone_group_id,boundary_id,match_type,confidence,boundary_conflict,nearest_distance_m,reason_json,status,calculated_at)
  VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(branch_id) DO UPDATE SET official_latitude=excluded.official_latitude,official_longitude=excluded.official_longitude,current_area_id=excluded.current_area_id,current_zone_group_id=excluded.current_zone_group_id,recommended_area_id=excluded.recommended_area_id,recommended_zone_group_id=excluded.recommended_zone_group_id,boundary_id=excluded.boundary_id,match_type=excluded.match_type,confidence=excluded.confidence,boundary_conflict=excluded.boundary_conflict,nearest_distance_m=excluded.nearest_distance_m,reason_json=excluded.reason_json,status=CASE WHEN gps_zone_recommendations.official_latitude IS excluded.official_latitude AND gps_zone_recommendations.official_longitude IS excluded.official_longitude AND gps_zone_recommendations.status IN ('accepted','kept_original','selected_other') THEN gps_zone_recommendations.status ELSE excluded.status END,decided_by=CASE WHEN gps_zone_recommendations.official_latitude IS excluded.official_latitude AND gps_zone_recommendations.official_longitude IS excluded.official_longitude THEN gps_zone_recommendations.decided_by ELSE NULL END,decided_at=CASE WHEN gps_zone_recommendations.official_latitude IS excluded.official_latitude AND gps_zone_recommendations.official_longitude IS excluded.official_longitude THEN gps_zone_recommendations.decided_at ELSE NULL END,calculated_at=CURRENT_TIMESTAMP`).run(item.branchId,item.officialLatitude,item.officialLongitude,item.currentAreaId,item.currentZoneGroupId,item.recommendedAreaId,item.recommendedZoneGroupId,item.boundaryId,item.matchType,item.confidence,item.boundaryConflict,item.nearestDistanceM,reason,item.status)}
export function recalculateRecommendations(payload={},database=defaultDb){const branchIds=payload.branchIds?.length?payload.branchIds.map(Number):database.prepare('SELECT id FROM branches').all().map(item=>item.id);database.exec('BEGIN IMMEDIATE');try{for(const branchId of branchIds)saveRecommendation(calculateRecommendation(branchId,database),database);database.prepare(`INSERT INTO audit_logs(action,entity_type,entity_id,after_json) VALUES('gps_zone_recommendations_recalculated','gps_recommendation','batch',?)`).run(JSON.stringify({branchCount:branchIds.length,changedBy:payload.changedBy||'System'}));database.exec('COMMIT')}catch(error){database.exec('ROLLBACK');throw error}return recommendationSummary(database)}
export function ensureRecommendations(database=defaultDb){const ids=database.prepare(`SELECT b.id FROM branches b LEFT JOIN gps_zone_recommendations r ON r.branch_id=b.id WHERE r.id IS NULL OR NOT(r.official_latitude IS b.latitude AND r.official_longitude IS b.longitude)`).all().map(item=>item.id);return ids.length?recalculateRecommendations({branchIds:ids,changedBy:'System Startup'},database):recommendationSummary(database)}

const recommendationSelect=`SELECT r.id,r.branch_id internalBranchId,b.jodoo_branch_id branchId,b.branch_name branchName,b.address,b.latitude,b.longitude,a.name currentArea,z.name currentZone,ra.name recommendedArea,rz.name recommendedZone,r.recommended_area_id recommendedAreaId,r.recommended_zone_group_id recommendedZoneGroupId,r.match_type matchType,r.confidence,r.boundary_conflict boundaryConflict,r.nearest_distance_m nearestDistanceM,r.reason_json reasonJson,r.status,r.calculated_at calculatedAt,r.decided_by decidedBy,r.decided_at decidedAt FROM gps_zone_recommendations r JOIN branches b ON b.id=r.branch_id LEFT JOIN areas a ON a.id=r.current_area_id LEFT JOIN zone_groups z ON z.id=r.current_zone_group_id LEFT JOIN areas ra ON ra.id=r.recommended_area_id LEFT JOIN zone_groups rz ON rz.id=r.recommended_zone_group_id`
const recommendationView=row=>({...row,reason:JSON.parse(row.reasonJson),reasonJson:undefined})
export function recommendationSummary(database=defaultDb){return database.prepare(`SELECT COUNT(*) total,SUM(status='pending') pending,SUM(confidence='high' AND boundary_conflict=0 AND status='pending') highConfidencePending,SUM(boundary_conflict=1) conflicts,SUM(match_type='outside') outside,SUM(status='no_gps') noGps FROM gps_zone_recommendations`).get()}
export function listRecommendations(params={},database=defaultDb){const where=[],args=[];if(params.status){where.push('r.status=?');args.push(params.status)}if(params.confidence){where.push('r.confidence=?');args.push(params.confidence)}if(params.conflict==='true')where.push('r.boundary_conflict=1');if(params.search){where.push('(b.branch_name LIKE ? OR b.jodoo_branch_id LIKE ? OR b.address LIKE ?)');args.push(...Array(3).fill(`%${params.search}%`))}const items=database.prepare(`${recommendationSelect}${where.length?' WHERE '+where.join(' AND '):''} ORDER BY r.boundary_conflict DESC,r.confidence='high' DESC,b.branch_name`).all(...args).map(recommendationView);return{summary:recommendationSummary(database),items}}

function effectiveZone(database,areaId){return areaId?branchZoneId(database,areaId):null}
export function decideRecommendation(id,payload,database=defaultDb){const before=database.prepare('SELECT * FROM gps_zone_recommendations WHERE id=?').get(id);if(!before)throw new Error('Recommendation not found');const action=payload.action;if(!['accept','keep_original','select_other','later'].includes(action))throw new Error('Invalid recommendation decision');const branch=database.prepare('SELECT * FROM branches WHERE id=?').get(before.branch_id),oldAreaId=branch.area_id,oldZoneId=effectiveZone(database,oldAreaId);let newAreaId=oldAreaId,status='kept_original';if(action==='accept'){if(!before.recommended_area_id)throw new Error('Recommendation has no Area; choose another Area manually');newAreaId=before.recommended_area_id;status='accepted'}if(action==='select_other'){newAreaId=Number(payload.areaId);if(!database.prepare('SELECT id FROM areas WHERE id=?').get(newAreaId))throw new Error('Selected Area not found');if(payload.zoneGroupId&&effectiveZone(database,newAreaId)!==Number(payload.zoneGroupId))throw new Error('Selected Area does not belong to the selected confirmed Zone');status='selected_other'}if(action==='later')status='later';const newZoneId=effectiveZone(database,newAreaId),actor=String(payload.confirmedBy||payload.changedBy||'Supervisor'),reason=before.reason_json;database.exec('BEGIN IMMEDIATE');try{if(['accept','select_other'].includes(action))database.prepare('UPDATE branches SET area_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(newAreaId,branch.id);database.prepare('UPDATE gps_zone_recommendations SET status=?,decided_by=?,decided_at=CURRENT_TIMESTAMP WHERE id=?').run(status,actor,id);database.prepare(`INSERT INTO gps_zone_decisions(recommendation_id,branch_id,decision,old_area_id,new_area_id,old_zone_group_id,new_zone_group_id,official_latitude,official_longitude,recommendation_reason_json,confirmed_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(id,branch.id,action,oldAreaId,newAreaId,oldZoneId,newZoneId,before.official_latitude,before.official_longitude,reason,actor);database.prepare(`INSERT INTO audit_logs(action,entity_type,entity_id,before_json,after_json) VALUES('gps_zone_recommendation_decided','branch',?,?,?)`).run(String(branch.id),JSON.stringify({areaId:oldAreaId,zoneGroupId:oldZoneId}),JSON.stringify({areaId:newAreaId,zoneGroupId:newZoneId,gps:{latitude:before.official_latitude,longitude:before.official_longitude},recommendationReason:JSON.parse(reason),decision:action,confirmedBy:actor}));database.exec('COMMIT')}catch(error){database.exec('ROLLBACK');throw error}return recommendationView(database.prepare(`${recommendationSelect} WHERE r.id=?`).get(id))}
export function bulkAcceptHighConfidence(payload={},database=defaultDb){const ids=database.prepare(`SELECT id FROM gps_zone_recommendations WHERE status='pending' AND confidence='high' AND boundary_conflict=0 AND recommended_area_id IS NOT NULL`).all().map(item=>item.id),items=[];for(const id of ids)items.push(decideRecommendation(id,{action:'accept',confirmedBy:payload.confirmedBy||payload.changedBy},database));return{acceptedCount:items.length,items}}
