import { createHash } from 'node:crypto'
import { db as defaultDb } from './database.mjs'
import { createCustomer, updateCustomer, createBranch, updateBranch, saveBuyer, saveOperationalLocation, captureBranchGps } from './customerMasterService.mjs'
import { invalidateDispatchDay } from './dispatchService.mjs'

const text=value=>String(value??'').trim()
const lower=value=>text(value).toLowerCase().replace(/[\s_./-]+/g,'')
const value=(row,...names)=>{const entries=Object.entries(row||{}),wanted=names.map(lower);const found=entries.find(([key])=>wanted.includes(lower(key)));return found?found[1]:undefined}
const nullable=value=>text(value)||null
const number=value=>value===''||value==null?null:Number(value)
const bool=value=>['yes','true','1','y','是','confirmed','active'].includes(text(value).toLowerCase())
const nowStamp=()=>new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'')

export const transferModules={
  customer:{label:'Customer',key:'customerId',headers:['Customer ID','Customer Name','Legal Name','Registration Number','Billing Address','Contact Person','Phone','WhatsApp','Email','Default Payment Type','Credit Terms','Status','Notes'],normalize:row=>({customerId:text(value(row,'Customer ID','CustomerID')),customerName:text(value(row,'Customer Name','CustomerName')),legalName:nullable(value(row,'Legal Name')),registrationNumber:nullable(value(row,'Registration Number')),billingAddress:nullable(value(row,'Billing Address')),contactPerson:nullable(value(row,'Contact Person')),phone:nullable(value(row,'Phone')),whatsapp:nullable(value(row,'WhatsApp')),email:nullable(value(row,'Email')),defaultPaymentType:nullable(value(row,'Default Payment Type','Payment Type')),creditTerms:nullable(value(row,'Credit Terms')),status:text(value(row,'Status')||'active').toLowerCase(),notes:nullable(value(row,'Notes'))}),required:['customerId','customerName']},
  branch:{label:'Customer Branch',key:'branchId',headers:['Branch ID','Customer ID','Branch Name','Address','Area ID','Contact Person','Phone','Collection Frequency','Assigned Weekdays','Collection Time Constraint','OCC Price','Payment Type','Proof Requirements','Vehicle Restriction','Status','Notes'],normalize:row=>({branchId:text(value(row,'Branch ID','BranchID')),customerId:text(value(row,'Customer ID','CustomerID')),branchName:text(value(row,'Branch Name')),address:nullable(value(row,'Address')),areaId:nullable(value(row,'Area ID','AreaID')),contactPerson:nullable(value(row,'Contact Person')),phone:nullable(value(row,'Phone')),collectionFrequency:nullable(value(row,'Collection Frequency')),assignedWeekdays:nullable(value(row,'Assigned Weekdays')),collectionTimeConstraint:nullable(value(row,'Collection Time Constraint')),occPrice:number(value(row,'OCC Price')),paymentType:nullable(value(row,'Payment Type')),proofRequirements:nullable(value(row,'Proof Requirements')),vehicleRestriction:nullable(value(row,'Vehicle Restriction')),status:text(value(row,'Status')||'active').toLowerCase(),notes:nullable(value(row,'Notes'))}),required:['branchId','customerId','branchName']},
  zone:{label:'Zone',key:'code',headers:['Zone Code','Zone Name','Sort Order','Status'],normalize:row=>({code:text(value(row,'Zone Code','Code')),name:text(value(row,'Zone Name','Name')),sortOrder:number(value(row,'Sort Order'))??0,status:text(value(row,'Status')||'active').toLowerCase()}),required:['code','name']},
  area:{label:'Area',key:'areaId',headers:['Area ID','Area Name','Zone Code','Confirmed','Status'],normalize:row=>({areaId:text(value(row,'Area ID','AreaID')),name:text(value(row,'Area Name','Name')),zoneCode:text(value(row,'Zone Code')),confirmed:bool(value(row,'Confirmed')),status:text(value(row,'Status')||'active').toLowerCase()}),required:['areaId','name','zoneCode']},
  gps:{label:'GPS',key:'branchId',headers:['Branch ID','Latitude','Longitude','GPS Type','Location Source','Location Link','Reason'],normalize:row=>({branchId:text(value(row,'Branch ID','BranchID')),latitude:number(value(row,'Latitude')),longitude:number(value(row,'Longitude')),gpsType:text(value(row,'GPS Type')||'Temporary'),locationSource:text(value(row,'Location Source')||'Manual Entry'),locationLink:nullable(value(row,'Location Link')),reason:nullable(value(row,'Reason'))}),required:['branchId','latitude','longitude']},
  buyer:{label:'Buyer',key:'buyerId',headers:['Buyer ID','Buyer Name','Location Name','Address','Official Latitude','Official Longitude','Contact Person','Phone','Material Accepted','Operating Hours','Unloading Restrictions','Pricing Notes','Status','Notes'],normalize:row=>({buyerId:text(value(row,'Buyer ID','BuyerID')),buyerName:text(value(row,'Buyer Name')),locationName:nullable(value(row,'Location Name')),address:nullable(value(row,'Address')),officialLatitude:number(value(row,'Official Latitude','Latitude')),officialLongitude:number(value(row,'Official Longitude','Longitude')),contactPerson:nullable(value(row,'Contact Person')),phone:nullable(value(row,'Phone')),materialAccepted:nullable(value(row,'Material Accepted')),operatingHours:nullable(value(row,'Operating Hours')),unloadingRestrictions:nullable(value(row,'Unloading Restrictions')),pricingNotes:nullable(value(row,'Pricing Notes')),status:text(value(row,'Status')||'active').toLowerCase(),notes:nullable(value(row,'Notes'))}),required:['buyerId','buyerName']},
  operational_location:{label:'Operational Location',key:'locationId',headers:['Location ID','Location Name','Location Type','Address','Latitude','Longitude','Operating Hours','Contact Person','Phone','Buyer ID','Can Start','Can End','Status','Notes'],normalize:row=>({locationId:text(value(row,'Location ID')),name:text(value(row,'Location Name','Name')),locationType:text(value(row,'Location Type')||'Other'),address:nullable(value(row,'Address')),latitude:number(value(row,'Latitude')),longitude:number(value(row,'Longitude')),operatingHours:nullable(value(row,'Operating Hours')),contactPerson:nullable(value(row,'Contact Person')),phone:nullable(value(row,'Phone')),buyerId:nullable(value(row,'Buyer ID')),canStart:bool(value(row,'Can Start')),canEnd:bool(value(row,'Can End')),status:text(value(row,'Status')||'active').toLowerCase(),notes:nullable(value(row,'Notes'))}),required:['locationId','name','locationType']},
}

function currentFor(module,key,database){if(module==='area')return database.prepare(`SELECT a.*,z.code zone_code FROM areas a LEFT JOIN zone_groups z ON z.id=COALESCE(a.confirmed_zone_group_id,a.zone_group_id) WHERE a.jodoo_area_id=?`).get(key);if(module==='operational_location')return database.prepare(`SELECT l.*,b.buyer_code buyer_code FROM operational_locations l LEFT JOIN buyers b ON b.id=l.buyer_id WHERE l.location_code=?`).get(key);const queries={customer:'SELECT * FROM customers WHERE jodoo_customer_id=?',branch:'SELECT * FROM branches WHERE jodoo_branch_id=?',zone:'SELECT * FROM zone_groups WHERE code=?',gps:'SELECT * FROM branches WHERE jodoo_branch_id=?',buyer:'SELECT * FROM buyers WHERE buyer_code=?'};return database.prepare(queries[module]).get(key)}
function comparable(module,item){if(!item)return null;const maps={customer:{customerId:item.jodoo_customer_id,customerName:item.name,legalName:item.legal_name,registrationNumber:item.registration_number,billingAddress:item.billing_address,contactPerson:item.contact_person,phone:item.phone,whatsapp:item.whatsapp,email:item.email,defaultPaymentType:item.default_payment_type??item.payment_type,creditTerms:item.credit_terms,status:item.status,notes:item.notes},branch:{branchId:item.jodoo_branch_id,customerId:item.source_customer_id,branchName:item.branch_name,address:item.address,areaId:item.source_area_id,contactPerson:item.contact_person,phone:item.phone,collectionFrequency:item.collection_frequency,assignedWeekdays:item.assigned_weekdays,collectionTimeConstraint:item.time_restriction,occPrice:item.occ_price,paymentType:item.payment_type,proofRequirements:item.proof_requirements,vehicleRestriction:item.vehicle_restriction,status:item.status,notes:item.notes},zone:{code:item.code,name:item.name,sortOrder:item.sort_order,status:item.is_active?'active':'inactive'},area:{areaId:item.jodoo_area_id,name:item.name,zoneCode:item.zone_code,confirmed:item.zone_assignment_status==='confirmed'&&item.confirmed_zone_group_id!=null,status:item.is_active?'active':'inactive'},gps:{branchId:item.jodoo_branch_id,latitude:item.latitude,longitude:item.longitude},buyer:{buyerId:item.buyer_code,buyerName:item.buyer_name,locationName:item.location_name,address:item.address,officialLatitude:item.latitude,officialLongitude:item.longitude,contactPerson:item.contact_person,phone:item.phone,materialAccepted:item.material_accepted,operatingHours:item.operating_hours,unloadingRestrictions:item.unloading_restrictions,pricingNotes:item.pricing_notes,status:item.status,notes:item.notes},operational_location:{locationId:item.location_code,name:item.name,locationType:item.operational_type,address:item.address,latitude:item.latitude,longitude:item.longitude,operatingHours:item.operating_hours,contactPerson:item.contact_person,phone:item.phone,buyerId:item.buyer_code,canStart:Boolean(item.can_start),canEnd:Boolean(item.can_end),status:item.status,notes:item.notes}};return maps[module]}
const same=(module,normalized,current)=>{if(!current)return false;const left=comparable(module,current);return Object.entries(normalized).every(([key,val])=>key==='reason'||key==='locationSource'||key==='locationLink'||key==='gpsType'||val==null||String(left?.[key]??'')===String(val??''))}

export function previewMasterImport(payload,database=defaultDb){
  const module=text(payload.module),definition=transferModules[module];if(!definition)throw new Error('Unsupported import module');if(!Array.isArray(payload.rows)||!payload.rows.length)throw new Error('The import file has no data rows')
  const fileName=text(payload.fileName)||`${module}.${payload.fileFormat||'csv'}`,hash=createHash('sha256').update(JSON.stringify(payload.rows)).digest('hex'),manifest={module,fileName,fileFormat:payload.fileFormat||'csv',contentHash:hash,rowCount:payload.rows.length}
  const batch=database.prepare(`INSERT INTO import_batches(source,status,file_manifest_json) VALUES(?,'preview',?)`).run(`kcs_master_${module}`,JSON.stringify([manifest])),batchId=Number(batch.lastInsertRowid)
  const file=database.prepare(`INSERT INTO import_files(import_batch_id,file_name,sheet_name,file_type,content_hash,row_count,headers_json) VALUES(?,?,?,?,?,?,?)`).run(batchId,fileName,payload.sheetName||definition.label,module,hash,payload.rows.length,JSON.stringify(Object.keys(payload.rows[0]||{}))),fileId=Number(file.lastInsertRowid)
  const summary={total:payload.rows.length,new:0,update:0,unchanged:0,error:0},errors=[]
  payload.rows.forEach((row,index)=>{let normalized={},action='error',message='';try{normalized=definition.normalize(row);const missing=definition.required.filter(key=>normalized[key]==null||normalized[key]==='');if(missing.length)throw new Error(`Missing required field: ${missing.join(', ')}`);if(module==='gps'&&(!(normalized.latitude>=-90&&normalized.latitude<=90)||!(normalized.longitude>=-180&&normalized.longitude<=180)))throw new Error('Invalid latitude or longitude');const current=currentFor(module,normalized[definition.key],database);action=current?(same(module,normalized,current)?'unchanged':'update'):'new';if(module==='branch'&&!database.prepare('SELECT id FROM customers WHERE jodoo_customer_id=?').get(normalized.customerId))throw new Error(`Customer ID not found: ${normalized.customerId}`);if(module==='gps'&&!current)throw new Error(`Branch ID not found: ${normalized.branchId}`);if(module==='gps'&&normalized.gpsType.toLowerCase()!=='official'){const latest=database.prepare('SELECT latitude,longitude FROM temporary_locations WHERE branch_id=? ORDER BY id DESC LIMIT 1').get(current.id);action=latest&&Number(latest.latitude)===normalized.latitude&&Number(latest.longitude)===normalized.longitude?'unchanged':'update'}if(module==='area'&&!database.prepare('SELECT id FROM zone_groups WHERE code=?').get(normalized.zoneCode))throw new Error(`Zone Code not found: ${normalized.zoneCode}`)}catch(error){action='error';message=error.message;errors.push({rowNumber:index+2,message,source:row});database.prepare(`INSERT INTO import_errors(import_batch_id,import_file_id,row_number,entity_type,external_id,severity,error_code,message,source_json) VALUES(?,?,?,?,?,'error','VALIDATION',?,?)`).run(batchId,fileId,index+2,module,normalized[definition.key]||null,message,JSON.stringify(row))}
    summary[action]+=1;database.prepare(`INSERT INTO import_staged_rows(import_batch_id,import_file_id,file_type,row_number,external_id,action,normalized_json,source_json) VALUES(?,?,?,?,?,?,?,?)`).run(batchId,fileId,module,index+2,normalized[definition.key]||null,action,JSON.stringify(normalized),JSON.stringify(row))})
  database.prepare('UPDATE import_batches SET summary_json=? WHERE id=?').run(JSON.stringify(summary),batchId);return{batchId,module,fileName,summary,errors,rows:database.prepare('SELECT row_number rowNumber,external_id externalId,action,normalized_json normalizedJson FROM import_staged_rows WHERE import_batch_id=? ORDER BY row_number LIMIT 100').all(batchId).map(item=>({...item,normalized:JSON.parse(item.normalizedJson),normalizedJson:undefined}))}
}

function audit(database,module,key,type,before,after,actor,reason='Master import'){database.prepare(`INSERT INTO master_change_history(entity_type,entity_id,change_type,before_json,after_json,reason,changed_by) VALUES(?,?,?,?,?,?,?)`).run(module,String(key),type,JSON.stringify(before),JSON.stringify(after),reason,actor)}
function commitOne(module,item,actor,database){
  const current=currentFor(module,item[transferModules[module].key],database)
  if(module==='customer')return current?updateCustomer(item.customerId,{...item,changedBy:actor,reason:'Master import'},database):createCustomer({...item,changedBy:actor,reason:'Master import'},database)
  if(module==='branch')return current?updateBranch(item.branchId,{...item,changedBy:actor,reason:'Master import'},database):createBranch({...item,changedBy:actor,reason:'Master import'},database)
  if(module==='buyer')return saveBuyer({...item,changedBy:actor,reason:'Master import'},current?.id||null,database)
  if(module==='operational_location')return saveOperationalLocation({...item,changedBy:actor,reason:'Master import'},current?.id||null,database)
  if(module==='gps'){
    if(item.gpsType.toLowerCase()==='official'){const before={latitude:current.latitude,longitude:current.longitude};database.prepare(`UPDATE branches SET latitude=?,longitude=?,gps_status='Supervisor Confirmed',gps_verified_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(item.latitude,item.longitude,current.id);const after={latitude:item.latitude,longitude:item.longitude};audit(database,'branch',item.branchId,'official_gps_imported',before,after,actor,item.reason);return after}
    return captureBranchGps(item.branchId,{...item,capturedBy:actor},database)
  }
  if(module==='zone'){if(current)database.prepare('UPDATE zone_groups SET name=?,sort_order=?,is_active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(item.name,item.sortOrder,item.status==='active'?1:0,current.id);else database.prepare('INSERT INTO zone_groups(code,name,sort_order,is_active) VALUES(?,?,?,?)').run(item.code,item.name,item.sortOrder,item.status==='active'?1:0);const after=currentFor(module,item.code,database);audit(database,module,item.code,current?'import_updated':'import_created',current,after,actor);return after}
  if(module==='area'){const zone=database.prepare('SELECT id FROM zone_groups WHERE code=?').get(item.zoneCode);if(current)database.prepare(`UPDATE areas SET name=?,zone_group_id=?,confirmed_zone_group_id=CASE WHEN ? THEN ? ELSE confirmed_zone_group_id END,zone_assignment_status=CASE WHEN ? THEN 'confirmed' ELSE 'pending_confirmation' END,zone_confirmed_by=CASE WHEN ? THEN ? ELSE NULL END,zone_confirmed_at=CASE WHEN ? THEN CURRENT_TIMESTAMP ELSE NULL END,is_active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(item.name,zone.id,item.confirmed?1:0,zone.id,item.confirmed?1:0,item.confirmed?1:0,actor,item.confirmed?1:0,item.status==='active'?1:0,current.id);else database.prepare(`INSERT INTO areas(jodoo_area_id,name,zone_group_id,confirmed_zone_group_id,zone_assignment_status,zone_confirmed_by,zone_confirmed_at,is_active) VALUES(?,?,?,?,?,?,CASE WHEN ? THEN CURRENT_TIMESTAMP ELSE NULL END,?)`).run(item.areaId,item.name,zone.id,item.confirmed?zone.id:null,item.confirmed?'confirmed':'pending_confirmation',item.confirmed?actor:null,item.confirmed?1:0,item.status==='active'?1:0);const after=currentFor(module,item.areaId,database);audit(database,module,item.areaId,current?'import_updated':'import_created',current,after,actor);return after}
}

export function commitMasterImport(batchId,payload={},database=defaultDb){const batch=database.prepare("SELECT * FROM import_batches WHERE id=? AND source LIKE 'kcs_master_%'").get(batchId);if(!batch)throw new Error('Master import preview batch not found');if(batch.status==='completed')return{batchId,status:'completed',summary:JSON.parse(batch.summary_json||'{}'),idempotent:true};const rows=database.prepare("SELECT * FROM import_staged_rows WHERE import_batch_id=? AND action IN ('new','update') ORDER BY row_number").all(batchId),actor=text(payload.changedBy)||'Supervisor',summary=JSON.parse(batch.summary_json||'{}'),affected=[]
  if(summary.error>0)throw new Error('Import contains errors. Export the error list, correct the file and preview again before commit.')
  database.exec('BEGIN IMMEDIATE');try{database.prepare("UPDATE import_batches SET status='importing' WHERE id=?").run(batchId);for(const row of rows){const item=JSON.parse(row.normalized_json),before=currentFor(row.file_type,row.external_id,database);commitOne(row.file_type,item,actor,database);if(row.file_type==='gps'&&item.gpsType.toLowerCase()==='official')affected.push({branchId:before.id,module:row.file_type,before});if(row.file_type==='area'&&before){const after=currentFor('area',row.external_id,database),oldZone=before.zone_assignment_status==='confirmed'?before.confirmed_zone_group_id:null,newZone=after.zone_assignment_status==='confirmed'?after.confirmed_zone_group_id:null;if(oldZone!==newZone)for(const branch of database.prepare('SELECT id FROM branches WHERE area_id=?').all(before.id))affected.push({branchId:branch.id,module:'area',before})}}database.prepare("UPDATE import_batches SET status='completed',completed_at=CURRENT_TIMESTAMP WHERE id=?").run(batchId);database.prepare(`INSERT INTO data_transfer_logs(operation_type,module,file_name,file_format,summary_json,performed_by) VALUES('import',?,?,?,?,?)`).run(rows[0]?.file_type||batch.source,JSON.parse(batch.file_manifest_json||'[]')[0]?.fileName||null,JSON.parse(batch.file_manifest_json||'[]')[0]?.fileFormat||null,JSON.stringify(summary),actor);database.exec('COMMIT')}
  catch(error){database.exec('ROLLBACK');database.prepare("UPDATE import_batches SET status='failed',summary_json=? WHERE id=?").run(JSON.stringify({...summary,fatalError:error.message}),batchId);throw error}
  for(const change of affected){if(!change.branchId)continue;const dates=database.prepare(`SELECT DISTINCT dd.dispatch_date FROM dispatch_days dd JOIN dispatch_trips dt ON dt.dispatch_day_id=dd.id JOIN dispatch_stops ds ON ds.dispatch_trip_id=dt.id WHERE ds.branch_id=? AND dd.dispatch_date>=date('now','localtime')`).all(change.branchId);for(const day of dates)invalidateDispatchDay(database,day.dispatch_date,'master_import_changed',change.module,change.branchId,change.before,null,actor)}return{batchId,status:'completed',summary}}

export function masterTemplate(module){const definition=transferModules[module];if(!definition)throw new Error('Unsupported transfer module');return{module,label:definition.label,columns:definition.headers,rows:[],fileName:`KCS_${definition.label.replace(/\s/g,'_')}_Template_${nowStamp()}`}}

export function masterExport(module,params={},database=defaultDb){const definition=transferModules[module];if(!definition)throw new Error('Unsupported export module');let rows=[]
  if(module==='customer')rows=database.prepare(`SELECT jodoo_customer_id 'Customer ID',name 'Customer Name',legal_name 'Legal Name',registration_number 'Registration Number',billing_address 'Billing Address',contact_person 'Contact Person',phone Phone,whatsapp WhatsApp,email Email,COALESCE(default_payment_type,payment_type) 'Default Payment Type',credit_terms 'Credit Terms',status Status,notes Notes FROM customers ORDER BY name`).all()
  if(module==='branch')rows=database.prepare(`SELECT b.jodoo_branch_id 'Branch ID',c.jodoo_customer_id 'Customer ID',b.branch_name 'Branch Name',b.address Address,a.jodoo_area_id 'Area ID',b.contact_person 'Contact Person',b.phone Phone,b.collection_frequency 'Collection Frequency',b.assigned_weekdays 'Assigned Weekdays',b.time_restriction 'Collection Time Constraint',COALESCE(b.occ_price,c.occ_price) 'OCC Price',COALESCE(b.payment_type,c.default_payment_type,c.payment_type) 'Payment Type',b.proof_requirements 'Proof Requirements',b.vehicle_restriction 'Vehicle Restriction',b.status Status,b.notes Notes FROM branches b LEFT JOIN customers c ON c.id=b.customer_id LEFT JOIN areas a ON a.id=b.area_id ORDER BY c.name,b.branch_name`).all()
  if(module==='zone')rows=database.prepare(`SELECT code 'Zone Code',name 'Zone Name',sort_order 'Sort Order',CASE is_active WHEN 1 THEN 'active' ELSE 'inactive' END Status FROM zone_groups ORDER BY sort_order,id`).all()
  if(module==='area')rows=database.prepare(`SELECT a.jodoo_area_id 'Area ID',a.name 'Area Name',z.code 'Zone Code',CASE WHEN a.zone_assignment_status='confirmed' AND a.confirmed_zone_group_id IS NOT NULL THEN 'Yes' ELSE 'No' END Confirmed,CASE a.is_active WHEN 1 THEN 'active' ELSE 'inactive' END Status,a.zone_confirmed_by 'Confirmed By',a.zone_confirmed_at 'Confirmed At' FROM areas a LEFT JOIN zone_groups z ON z.id=COALESCE(a.confirmed_zone_group_id,a.zone_group_id) ORDER BY z.sort_order,a.name`).all()
  if(module==='gps')rows=database.prepare(`SELECT b.jodoo_branch_id 'Branch ID',b.latitude Latitude,b.longitude Longitude,'Official' 'GPS Type',b.gps_status 'Verification Status',b.gps_verified_at 'Verified At' FROM branches b ORDER BY b.jodoo_branch_id`).all()
  if(module==='buyer')rows=database.prepare(`SELECT buyer_code 'Buyer ID',buyer_name 'Buyer Name',location_name 'Location Name',address Address,latitude 'Official Latitude',longitude 'Official Longitude',contact_person 'Contact Person',phone Phone,material_accepted 'Material Accepted',operating_hours 'Operating Hours',unloading_restrictions 'Unloading Restrictions',pricing_notes 'Pricing Notes',status Status,notes Notes FROM buyers ORDER BY buyer_name`).all()
  if(module==='operational_location')rows=database.prepare(`SELECT location_code 'Location ID',name 'Location Name',operational_type 'Location Type',address Address,latitude Latitude,longitude Longitude,operating_hours 'Operating Hours',contact_person 'Contact Person',phone Phone,status Status,notes Notes,CASE can_start WHEN 1 THEN 'Yes' ELSE 'No' END 'Can Start',CASE can_end WHEN 1 THEN 'Yes' ELSE 'No' END 'Can End' FROM operational_locations ORDER BY name`).all()
  if(params.search){const q=text(params.search).toLowerCase();rows=rows.filter(row=>Object.values(row).some(item=>text(item).toLowerCase().includes(q)))}
  const actor=text(params.changedBy)||'Supervisor',fileName=`KCS_${definition.label.replace(/\s/g,'_')}_${nowStamp()}`;database.prepare(`INSERT INTO data_transfer_logs(operation_type,module,file_name,file_format,scope_json,summary_json,performed_by) VALUES('export',?,?,?,?,?,?)`).run(module,fileName,params.format||'xlsx',JSON.stringify(params),JSON.stringify({rowCount:rows.length}),actor);return{module,label:definition.label,columns:rows.length?Object.keys(rows[0]):definition.headers,rows,fileName}}

export function listTransferLogs(database=defaultDb){return database.prepare(`SELECT id,operation_type operationType,module,file_name fileName,file_format fileFormat,summary_json summaryJson,performed_by performedBy,performed_at performedAt FROM data_transfer_logs ORDER BY id DESC LIMIT 200`).all().map(item=>({...item,summary:JSON.parse(item.summaryJson||'{}'),summaryJson:undefined}))}
