import {db as defaultDb} from './database.mjs'

const clean=value=>String(value??'').trim()
const fail=(code,message,statusCode=400)=>{const error=new Error(message);error.code=code;error.statusCode=statusCode;throw error}
const actor=payload=>clean(payload.changedBy)||'Owner Admin'
const reason=payload=>{const value=clean(payload.reason);if(!value)fail('MATERIAL_REASON_REQUIRED','A reason is required.');return value}
const categoryRow=(database,id)=>database.prepare(`SELECT c.*,COUNT(DISTINCT p.id) product_count FROM material_categories c LEFT JOIN material_products p ON p.category_id=c.id AND p.visibility_status<>'hidden' WHERE c.id=? GROUP BY c.id`).get(id)
const productRow=(database,id)=>database.prepare(`SELECT p.*,c.category_name,c.category_code,m.material_name legacy_material_name FROM material_products p JOIN material_categories c ON c.id=p.category_id LEFT JOIN materials m ON m.id=p.material_id WHERE p.id=?`).get(id)
const levelRow=(database,id)=>database.prepare(`SELECT l.*,p.full_name product_name,p.short_form,p.unit,p.category_id,c.category_name,COUNT(a.branch_id) branch_count FROM material_price_levels l JOIN material_products p ON p.id=l.product_id JOIN material_categories c ON c.id=p.category_id LEFT JOIN branch_product_price_assignments a ON a.price_level_id=l.id WHERE l.id=? GROUP BY l.id`).get(id)

export function listCategories(database=defaultDb){
  const items=database.prepare(`SELECT c.*,COUNT(DISTINCT p.id) product_count,COUNT(DISTINCT l.id) price_group_count,COUNT(DISTINCT a.branch_id) branch_count FROM material_categories c LEFT JOIN material_products p ON p.category_id=c.id AND p.visibility_status<>'hidden' LEFT JOIN material_price_levels l ON l.product_id=p.id AND l.visibility_status<>'hidden' LEFT JOIN branch_product_price_assignments a ON a.price_level_id=l.id WHERE c.is_hidden=0 GROUP BY c.id ORDER BY c.sort_order,c.category_name`).all()
  return{items}
}
export function getCategory(id,database=defaultDb){
  const category=categoryRow(database,id);if(!category)fail('MATERIAL_CATEGORY_NOT_FOUND','Material Category was not found.',404)
  category.products=database.prepare(`SELECT p.*,COALESCE((SELECT CAST(json_extract(ma.after_json,'$.sortOrder') AS INTEGER) FROM material_master_audit ma WHERE ma.entity_type='product' AND ma.entity_id=p.id AND ma.action='create' ORDER BY ma.id DESC LIMIT 1),100) sort_order,COUNT(DISTINCT l.id) price_group_count,COUNT(DISTINCT a.branch_id) branch_count FROM material_products p LEFT JOIN material_price_levels l ON l.product_id=p.id AND l.visibility_status<>'hidden' LEFT JOIN branch_product_price_assignments a ON a.price_level_id=l.id WHERE p.category_id=? AND p.visibility_status<>'hidden' GROUP BY p.id ORDER BY sort_order,p.full_name`).all(id)
  return category
}
export function createProduct(categoryId,payload={},database=defaultDb){
  const category=categoryRow(database,Number(categoryId)),name=clean(payload.productName),code=clean(payload.productCode).toUpperCase(),unit=clean(payload.unit)||'kg',status=clean(payload.status)||'active',sort=Number(payload.sortOrder),why=reason(payload),who=actor(payload)
  if(!category)fail('MATERIAL_CATEGORY_NOT_FOUND','Material Category was not found.',404)
  if(!name)fail('MATERIAL_PRODUCT_NAME_REQUIRED','Product Name is required.')
  if(!code)fail('MATERIAL_PRODUCT_CODE_REQUIRED','Product Code is required.')
  if(!['kg','piece'].includes(unit))fail('MATERIAL_PRODUCT_UNIT_INVALID','Unit must be kg or piece.')
  if(!['active','inactive'].includes(status))fail('MATERIAL_PRODUCT_STATUS_INVALID','Status must be Active or Inactive.')
  if(!Number.isInteger(sort))fail('MATERIAL_PRODUCT_SORT_INVALID','Sort Order must be a whole number.')
  if(database.prepare('SELECT id FROM material_products WHERE LOWER(TRIM(full_name))=LOWER(?)').get(name))fail('MATERIAL_PRODUCT_NAME_DUPLICATE','A Product with this name already exists.',409)
  if(database.prepare('SELECT id FROM material_products WHERE LOWER(TRIM(product_code))=LOWER(?)').get(code))fail('MATERIAL_PRODUCT_CODE_DUPLICATE','A Product with this code already exists.',409)
  database.exec('BEGIN IMMEDIATE')
  try{
    const materialCode=`PRODUCT_${code}`,materialName=`Product: ${name}`
    if(database.prepare('SELECT id FROM materials WHERE LOWER(material_code)=LOWER(?) OR LOWER(material_name)=LOWER(?)').get(materialCode,materialName))fail('MATERIAL_PRODUCT_LEGACY_DUPLICATE','A compatibility Material already exists for this Product.',409)
    const materialId=Number(database.prepare('INSERT INTO materials(material_code,material_name,unit,status,created_by) VALUES(?,?,?,?,?)').run(materialCode,materialName,unit,status,who).lastInsertRowid)
    const id=Number(database.prepare('INSERT INTO material_products(material_id,product_code,full_name,short_form,unit,status,created_by,category_id) VALUES(?,?,?,?,?,?,?,?)').run(materialId,code,name,code,unit,status,who,category.id).lastInsertRowid)
    database.prepare('INSERT INTO material_master_audit(entity_type,entity_id,action,after_json,reason,changed_by) VALUES(?,?,?,?,?,?)').run('product',id,'create',JSON.stringify({categoryId:category.id,productName:name,productCode:code,unit,status,sortOrder:sort,materialId}),why,who)
    database.exec('COMMIT')
    return productRow(database,id)
  }catch(error){database.exec('ROLLBACK');if(String(error.message).includes('UNIQUE'))fail('MATERIAL_PRODUCT_DUPLICATE','A Product with this name or code already exists.',409);throw error}
}
export function getProduct(id,database=defaultDb){
  const product=productRow(database,id);if(!product)fail('MATERIAL_PRODUCT_NOT_FOUND','Product was not found.',404)
  product.priceGroups=database.prepare(`SELECT l.*,COUNT(a.branch_id) branch_count FROM material_price_levels l LEFT JOIN branch_product_price_assignments a ON a.price_level_id=l.id WHERE l.product_id=? AND l.visibility_status<>'hidden' GROUP BY l.id ORDER BY l.price_cents,l.id`).all(id)
  product.usesOccEngine=product.product_code==='OCC'
  return product
}
export function getPriceGroup(id,database=defaultDb){
  const group=levelRow(database,id);if(!group)fail('MATERIAL_PRICE_GROUP_NOT_FOUND','Price Group was not found.',404)
  group.branches=database.prepare(`SELECT b.id branch_internal_id,b.jodoo_branch_id branch_id,b.branch_name,c.jodoo_customer_id customer_id,c.name customer_name,ar.name area_name FROM branch_product_price_assignments a JOIN branches b ON b.id=a.branch_id LEFT JOIN customers c ON c.id=b.customer_id LEFT JOIN areas ar ON ar.id=b.area_id WHERE a.price_level_id=? ORDER BY c.name,b.branch_name`).all(id)
  group.candidates=database.prepare(`SELECT b.id branch_internal_id,b.jodoo_branch_id branch_id,b.branch_name,c.name customer_name,a.price_level_id current_price_level_id,l.price_amount current_price FROM branches b JOIN branch_product_availability v ON v.branch_id=b.id AND v.product_id=? AND v.is_selectable=1 LEFT JOIN customers c ON c.id=b.customer_id LEFT JOIN branch_product_price_assignments a ON a.branch_id=b.id AND a.product_id=? LEFT JOIN material_price_levels l ON l.id=a.price_level_id ORDER BY c.name,b.branch_name`).all(group.product_id,group.product_id)
  return group
}
export function moveProductBranches(sourceId,targetId,branchIds,payload={},database=defaultDb){
  const source=levelRow(database,Number(sourceId)),target=levelRow(database,Number(targetId)),ids=[...new Set((branchIds||[]).map(Number).filter(Boolean))],why=reason(payload),who=actor(payload)
  if(!source||!target)fail('MATERIAL_PRICE_GROUP_NOT_FOUND','Source or target Price Group was not found.',404)
  if(source.id===target.id)fail('MATERIAL_SAME_PRICE_GROUP','Source and target Price Groups cannot be the same.')
  if(source.product_id!==target.product_id)fail('MATERIAL_PRODUCT_MISMATCH','Price Groups must belong to the same Product.')
  if(!ids.length)fail('MATERIAL_NO_BRANCHES_SELECTED','No Branches were selected.')
  database.exec('BEGIN IMMEDIATE')
  try{
    for(const branchId of ids){
      const current=database.prepare('SELECT price_level_id FROM branch_product_price_assignments WHERE branch_id=? AND product_id=?').get(branchId,source.product_id)
      if(Number(current?.price_level_id)!==source.id)fail('MATERIAL_BRANCH_SOURCE_CHANGED','One or more Branches no longer belong to the source Price Group. Refresh and try again.',409)
      database.prepare('UPDATE branch_product_price_assignments SET price_level_id=?,assigned_by=?,updated_at=CURRENT_TIMESTAMP WHERE branch_id=? AND product_id=?').run(target.id,who,branchId,source.product_id)
      database.prepare(`INSERT INTO branch_product_price_assignment_history(branch_id,product_id,old_price_level_id,new_price_level_id,reason,changed_by,action) VALUES(?,?,?,?,?,?,'move')`).run(branchId,source.product_id,source.id,target.id,why,who)
    }
    database.exec('COMMIT');return{changedCount:ids.length,source:getPriceGroup(source.id,database),target:getPriceGroup(target.id,database)}
  }catch(error){database.exec('ROLLBACK');throw error}
}
export function assignProductBranches(targetId,branchIds,payload={},database=defaultDb){
  const target=levelRow(database,Number(targetId)),ids=[...new Set((branchIds||[]).map(Number).filter(Boolean))],why=reason(payload),who=actor(payload)
  if(!target)fail('MATERIAL_PRICE_GROUP_NOT_FOUND','Target Price Group was not found.',404);if(!ids.length)fail('MATERIAL_NO_BRANCHES_SELECTED','No Branches were selected.')
  database.exec('BEGIN IMMEDIATE')
  try{let changed=0;for(const branchId of ids){const available=database.prepare('SELECT 1 FROM branch_product_availability WHERE branch_id=? AND product_id=? AND is_selectable=1').get(branchId,target.product_id);if(!available)fail('MATERIAL_PRODUCT_NOT_AVAILABLE','One or more Branches cannot select this Product.',409);const old=database.prepare('SELECT price_level_id FROM branch_product_price_assignments WHERE branch_id=? AND product_id=?').get(branchId,target.product_id);if(Number(old?.price_level_id)===target.id)continue;database.prepare(`INSERT INTO branch_product_price_assignments(branch_id,product_id,price_level_id,assigned_by) VALUES(?,?,?,?) ON CONFLICT(branch_id,product_id) DO UPDATE SET price_level_id=excluded.price_level_id,assigned_by=excluded.assigned_by,updated_at=CURRENT_TIMESTAMP`).run(branchId,target.product_id,target.id,who);database.prepare(`INSERT INTO branch_product_price_assignment_history(branch_id,product_id,old_price_level_id,new_price_level_id,reason,changed_by,action) VALUES(?,?,?,?,?,?,'assign')`).run(branchId,target.product_id,old?.price_level_id||null,target.id,why,who);changed++}database.exec('COMMIT');return{changedCount:changed,target:getPriceGroup(target.id,database)}}catch(error){database.exec('ROLLBACK');throw error}
}
export function changeProductGroupPrice(id,payload={},database=defaultDb){
  const group=levelRow(database,Number(id));if(!group)fail('MATERIAL_PRICE_GROUP_NOT_FOUND','Price Group was not found.',404)
  const amount=Number(payload.newPrice),cents=Math.round(amount*100),date=clean(payload.effectiveDate),why=reason(payload),who=actor(payload)
  if(!Number.isFinite(amount)||amount<0||Math.abs(amount*100-cents)>.00001)fail('MATERIAL_INVALID_PRICE','Price must be a non-negative amount with at most two decimal places.')
  if(!/^\d{4}-\d{2}-\d{2}$/.test(date))fail('MATERIAL_EFFECTIVE_DATE_REQUIRED','A valid Effective Date is required.')
  const collision=database.prepare('SELECT id FROM material_price_levels WHERE product_id=? AND price_cents=? AND id<>?').get(group.product_id,cents,group.id);if(collision)fail('MATERIAL_PRICE_GROUP_DUPLICATE','This Product already has a Price Group with that price.',409)
  database.exec('BEGIN IMMEDIATE');try{database.prepare(`INSERT INTO product_price_group_history(price_level_id,product_id,old_price_amount,new_price_amount,old_effective_date,new_effective_date,affected_branch_count,reason,changed_by) VALUES(?,?,?,?,?,?,?,?,?)`).run(group.id,group.product_id,group.price_amount,amount,group.effective_date,date,group.branch_count,why,who);database.prepare('UPDATE material_price_levels SET previous_price_amount=price_amount,price_amount=?,price_cents=?,effective_date=?,reason=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(amount,cents,date,why,group.id);database.exec('COMMIT');return getPriceGroup(group.id,database)}catch(error){database.exec('ROLLBACK');throw error}
}
export function moveProductsCategory(sourceId,targetId,productIds,payload={},database=defaultDb){const source=categoryRow(database,Number(sourceId)),target=categoryRow(database,Number(targetId)),ids=[...new Set((productIds||[]).map(Number).filter(Boolean))],why=reason(payload),who=actor(payload);if(!source||!target)fail('MATERIAL_ENTITY_NOT_FOUND','Source or target Category was not found.',404);if(source.id===target.id)fail('MATERIAL_CATEGORY_SAME','Source and target Categories cannot be the same.');if(!ids.length)fail('MATERIAL_NO_PRODUCTS_SELECTED','No Products were selected.');database.exec('BEGIN IMMEDIATE');try{const products=[];for(const id of ids){const product=database.prepare(`SELECT p.*,COUNT(DISTINCT l.id) price_group_count,COUNT(DISTINCT a.branch_id) branch_count FROM material_products p LEFT JOIN material_price_levels l ON l.product_id=p.id LEFT JOIN branch_product_price_assignments a ON a.product_id=p.id WHERE p.id=? GROUP BY p.id`).get(id);if(!product||Number(product.category_id)!==source.id)fail('MATERIAL_PRODUCT_SOURCE_CHANGED','One or more Products no longer belong to the source Category. Refresh and try again.',409);products.push(product)}for(const product of products){database.prepare('UPDATE material_products SET category_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(target.id,product.id);database.prepare('INSERT INTO material_product_category_history(product_id,old_category_id,new_category_id,reason,changed_by) VALUES(?,?,?,?,?)').run(product.id,source.id,target.id,why,who);database.prepare('INSERT INTO material_master_audit(entity_type,entity_id,action,before_json,after_json,reason,changed_by) VALUES(?,?,?,?,?,?,?)').run('product',product.id,'category_move',JSON.stringify({categoryId:source.id}),JSON.stringify({categoryId:target.id}),why,who)}database.exec('COMMIT');return{changedCount:products.length,source:getCategory(source.id,database),target:getCategory(target.id,database)}}catch(error){database.exec('ROLLBACK');throw error}}
export function moveProductCategory(productId,categoryId,payload={},database=defaultDb){const product=productRow(database,Number(productId));if(!product)fail('MATERIAL_PRODUCT_NOT_FOUND','Product was not found.',404);return moveProductsCategory(product.category_id,categoryId,[product.id],payload,database).target.products.find(item=>Number(item.id)===product.id)}
export function previewMoveProducts(sourceId,targetId,productIds,database=defaultDb){const source=getCategory(Number(sourceId),database),target=categoryRow(database,Number(targetId)),ids=[...new Set((productIds||[]).map(Number).filter(Boolean))];if(!target)fail('MATERIAL_CATEGORY_NOT_FOUND','Target Category was not found.',404);if(source.id===target.id)fail('MATERIAL_CATEGORY_SAME','Source and target Categories cannot be the same.');const selected=source.products.filter(item=>ids.includes(Number(item.id)));if(selected.length!==ids.length||!ids.length)fail('MATERIAL_NO_PRODUCTS_SELECTED','Select valid Products from the source Category.');return{source:{id:source.id,name:source.category_name},target:{id:target.id,name:target.category_name},products:selected.map(item=>({id:item.id,name:item.full_name,priceGroupCount:item.price_group_count,branchAssignmentCount:item.branch_count}))}}
export function entityPreview(type,id,database=defaultDb){
  if(type==='category'){const row=categoryRow(database,id);if(!row)fail('MATERIAL_ENTITY_NOT_FOUND','Category was not found.',404);const refs={products:row.product_count,systemReserved:row.system_reserved};return{entity:row,references:refs,deleteEligible:!refs.products&&!refs.systemReserved}}
  if(type==='product'){const row=productRow(database,id);if(!row)fail('MATERIAL_ENTITY_NOT_FOUND','Product was not found.',404);const refs={priceGroups:database.prepare('SELECT COUNT(*) count FROM material_price_levels WHERE product_id=?').get(id).count,branchRelations:database.prepare('SELECT COUNT(*) count FROM branch_product_availability WHERE product_id=?').get(id).count,assignments:database.prepare('SELECT COUNT(*) count FROM branch_product_price_assignments WHERE product_id=?').get(id).count};return{entity:row,references:refs,deleteEligible:Object.values(refs).every(value=>value===0)}}
  const row=levelRow(database,id);if(!row)fail('MATERIAL_ENTITY_NOT_FOUND','Price Group was not found.',404);const refs={assignments:row.branch_count,history:database.prepare('SELECT COUNT(*) count FROM product_price_group_history WHERE price_level_id=?').get(id).count};return{entity:row,references:refs,deleteEligible:Object.values(refs).every(value=>value===0)}
}
export function setEntityVisibility(type,id,action,payload={},database=defaultDb){const why=reason(payload),who=actor(payload),preview=entityPreview(type,id,database);if(type==='category'&&preview.entity.system_reserved)fail('MATERIAL_RESERVED_CATEGORY','Uncategorized cannot be archived or hidden.');if(action==='hide'&&((preview.references.assignments||0)>0))fail('MATERIAL_ENTITY_IN_USE','An in-use record cannot be hidden.',409);const table=type==='category'?'material_categories':type==='product'?'material_products':'material_price_levels',column=type==='category'?'is_hidden':'visibility_status',value=type==='category'?1:(action==='archive'?'archived':'hidden');database.exec('BEGIN IMMEDIATE');try{database.prepare(`UPDATE ${table} SET ${column}=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(value,id);database.prepare('INSERT INTO material_master_audit(entity_type,entity_id,action,before_json,after_json,reason,changed_by) VALUES(?,?,?,?,?,?,?)').run(type,id,action,JSON.stringify(preview.entity),JSON.stringify({[column]:value}),why,who);database.exec('COMMIT');return{ok:true}}catch(error){database.exec('ROLLBACK');throw error}}

export function createCategory(payload={},database=defaultDb){const name=clean(payload.categoryName),code=clean(payload.categoryCode)||name.toUpperCase().replace(/[^A-Z0-9]+/g,'_'),why=reason(payload),who=actor(payload),sort=Number.isInteger(Number(payload.sortOrder))?Number(payload.sortOrder):100;if(!name)fail('MATERIAL_CATEGORY_NAME_REQUIRED','Category name is required.');if(database.prepare('SELECT id FROM material_categories WHERE LOWER(TRIM(category_name))=LOWER(?)').get(name))fail('MATERIAL_CATEGORY_DUPLICATE','A Category with this name already exists.',409);database.exec('BEGIN IMMEDIATE');try{const result=database.prepare(`INSERT INTO material_categories(category_code,category_name,sort_order,created_by) VALUES(?,?,?,?)`).run(code,name,sort,who),id=Number(result.lastInsertRowid);database.prepare('INSERT INTO material_master_audit(entity_type,entity_id,action,after_json,reason,changed_by) VALUES(?,?,?,?,?,?)').run('category',id,'create',JSON.stringify({code,name,sortOrder:sort}),why,who);database.exec('COMMIT');return categoryRow(database,id)}catch(error){database.exec('ROLLBACK');if(String(error.message).includes('UNIQUE'))fail('MATERIAL_CATEGORY_DUPLICATE','A Category with this name already exists.',409);throw error}}
export function updateCategory(id,payload={},database=defaultDb){const current=categoryRow(database,Number(id));if(!current)fail('MATERIAL_CATEGORY_NOT_FOUND','Material Category was not found.',404);const name=clean(payload.categoryName),sort=Number(payload.sortOrder),why=reason(payload),who=actor(payload);if(!name)fail('MATERIAL_CATEGORY_NAME_REQUIRED','Category name is required.');if(!Number.isInteger(sort))fail('MATERIAL_CATEGORY_SORT_INVALID','Sort Order must be a whole number.');if(database.prepare('SELECT id FROM material_categories WHERE LOWER(TRIM(category_name))=LOWER(?) AND id<>?').get(name,current.id))fail('MATERIAL_CATEGORY_DUPLICATE','A Category with this name already exists.',409);database.exec('BEGIN IMMEDIATE');try{database.prepare('UPDATE material_categories SET category_name=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(name,sort,current.id);database.prepare('INSERT INTO material_master_audit(entity_type,entity_id,action,before_json,after_json,reason,changed_by) VALUES(?,?,?,?,?,?,?)').run('category',current.id,'edit',JSON.stringify({name:current.category_name,sortOrder:current.sort_order}),JSON.stringify({name,sortOrder:sort}),why,who);database.exec('COMMIT');return categoryRow(database,current.id)}catch(error){database.exec('ROLLBACK');throw error}}
export function deleteEntity(type,id,payload={},database=defaultDb){const preview=entityPreview(type,id,database),why=reason(payload),who=actor(payload);if(!preview.deleteEligible)fail('MATERIAL_DELETE_BLOCKED','This record has related data and cannot be deleted.',409);const table=type==='category'?'material_categories':type==='product'?'material_products':'material_price_levels';database.exec('BEGIN IMMEDIATE');try{database.prepare('INSERT INTO material_master_audit(entity_type,entity_id,action,before_json,reason,changed_by) VALUES(?,?,?,?,?,?)').run(type,id,'delete',JSON.stringify(preview.entity),why,who);database.prepare(`DELETE FROM ${table} WHERE id=?`).run(id);database.exec('COMMIT');return{deleted:true}}catch(error){database.exec('ROLLBACK');throw error}}
export function mergeEntities(type,sourceId,targetId,payload={},database=defaultDb){if(sourceId===targetId)fail('MATERIAL_MERGE_SAME','Source and target cannot be the same.');const source=entityPreview(type,sourceId,database).entity,target=entityPreview(type,targetId,database).entity,why=reason(payload),who=actor(payload);if(type==='product'&&(source.category_id!==target.category_id||source.unit!==target.unit))fail('MATERIAL_MERGE_INCOMPATIBLE','Products must have the same Category and Unit.');if(type==='priceGroup'&&source.product_id!==target.product_id)fail('MATERIAL_MERGE_INCOMPATIBLE','Price Groups must belong to the same Product.');database.exec('BEGIN IMMEDIATE');try{if(type==='category')database.prepare('UPDATE material_products SET category_id=? WHERE category_id=?').run(targetId,sourceId);else if(type==='product'){database.prepare('UPDATE material_price_levels SET product_id=? WHERE product_id=?').run(targetId,sourceId);database.prepare('UPDATE branch_product_availability SET product_id=? WHERE product_id=?').run(targetId,sourceId)}else{database.prepare('UPDATE branch_product_price_assignments SET price_level_id=? WHERE price_level_id=?').run(targetId,sourceId)}const table=type==='category'?'material_categories':type==='product'?'material_products':'material_price_levels',mergedColumn=type==='category'?'merged_into_category_id':type==='product'?'merged_into_product_id':'merged_into_price_level_id',visibility=type==='category'?'is_hidden=1':"visibility_status='archived'";database.prepare(`UPDATE ${table} SET ${mergedColumn}=?,${visibility},updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(targetId,sourceId);database.prepare('INSERT INTO material_master_merge_links(entity_type,source_id,target_id,reason,changed_by) VALUES(?,?,?,?,?)').run(type,sourceId,targetId,why,who);database.prepare('INSERT INTO material_master_audit(entity_type,entity_id,action,before_json,after_json,reason,changed_by) VALUES(?,?,?,?,?,?,?)').run(type,sourceId,'merge',JSON.stringify(source),JSON.stringify({targetId}),why,who);database.exec('COMMIT');return{merged:true,sourceId,targetId}}catch(error){database.exec('ROLLBACK');throw error}}
