export const V42_VERSION=42
const exists=(db,table)=>Boolean(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(table))
const columns=(db,table)=>new Set(db.prepare(`PRAGMA table_info(${table})`).all().map(row=>row.name))
const count=(db,table)=>exists(db,table)?Number(db.prepare(`SELECT COUNT(*) n FROM ${table}`).get().n):0
const protectedCounts=db=>Object.fromEntries(['customers','branches','customer_material_pricing','customer_material_pricing_history','branch_material_price_selections','branch_material_price_selection_history','branch_material_prices','branch_material_price_history','branch_occ_price_assignments','branch_occ_price_assignment_history','branch_schedules','dispatches','dispatch_stops','temporary_locations','areas','zone_groups','master_change_history'].map(table=>[table,count(db,table)]))
export function ensureV42Schema(db){
  if(!columns(db,'customer_material_pricing').has('price_type'))db.exec("ALTER TABLE customer_material_pricing ADD COLUMN price_type TEXT NOT NULL DEFAULT 'standard' CHECK(price_type IN ('standard','outstation'))")
  if(!columns(db,'customer_material_pricing').has('resolution_state'))db.exec("ALTER TABLE customer_material_pricing ADD COLUMN resolution_state TEXT NOT NULL DEFAULT 'review_required' CHECK(resolution_state IN ('ready','review_required'))")
  db.exec("UPDATE customer_material_pricing SET price_type='standard',resolution_state='ready' WHERE outstation_enabled=0;UPDATE customer_material_pricing SET price_type='outstation',resolution_state='ready' WHERE outstation_enabled=1 AND (SELECT COUNT(DISTINCT s.price_type) FROM branch_material_price_selections s JOIN branches b ON b.id=s.branch_id WHERE b.customer_id=customer_material_pricing.customer_id AND s.material_id=customer_material_pricing.material_id)=1 AND (SELECT MIN(s.price_type) FROM branch_material_price_selections s JOIN branches b ON b.id=s.branch_id WHERE b.customer_id=customer_material_pricing.customer_id AND s.material_id=customer_material_pricing.material_id)='outstation';UPDATE customer_material_pricing SET price_type='standard',resolution_state='ready' WHERE outstation_enabled=1 AND (SELECT COUNT(DISTINCT s.price_type) FROM branch_material_price_selections s JOIN branches b ON b.id=s.branch_id WHERE b.customer_id=customer_material_pricing.customer_id AND s.material_id=customer_material_pricing.material_id)=1 AND (SELECT MIN(s.price_type) FROM branch_material_price_selections s JOIN branches b ON b.id=s.branch_id WHERE b.customer_id=customer_material_pricing.customer_id AND s.material_id=customer_material_pricing.material_id)='standard'")
}
const assertV42Contract=db=>{const cols=columns(db,'customer_material_pricing');for(const name of ['price_type','resolution_state'])if(!cols.has(name))throw new Error(`Schema v42 contract is incomplete: missing customer_material_pricing.${name}`);const sql=String(db.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name='customer_material_pricing'").get()?.sql||'');for(const token of ["price_type IN ('standard','outstation')","resolution_state IN ('ready','review_required')"])if(!sql.replaceAll(' ','').includes(token.replaceAll(' ','')))throw new Error(`Schema v42 constraint is missing: ${token}`);if(db.prepare('PRAGMA foreign_key_check').get())throw new Error('Foreign-key validation failed for v42 schema');if(db.prepare('PRAGMA integrity_check').get().integrity_check!=='ok')throw new Error('Database integrity check failed for v42 schema')}
export function applyV42Migration(db,{afterSchema}={}){
  const version=Number(db.prepare('SELECT COALESCE(MAX(version),0) version FROM schema_meta').get().version)
  if(version>=V42_VERSION){assertV42Contract(db);return{schemaVersion:version,noOp:true,before:protectedCounts(db),after:protectedCounts(db)}}
  if(version!==41)throw new Error(`Schema v41 is required before v42; current schema is v${version}`)
  if(db.prepare('PRAGMA integrity_check').get().integrity_check!=='ok')throw new Error('Database integrity check failed before v42 migration')
  const before=protectedCounts(db)
  db.exec('BEGIN IMMEDIATE')
  try{ensureV42Schema(db);afterSchema?.(db);db.prepare('INSERT INTO schema_meta(version) VALUES(?)').run(V42_VERSION);const after=protectedCounts(db);if(JSON.stringify(before)!==JSON.stringify(after))throw new Error('Protected business or history counts changed during v42 migration');assertV42Contract(db);db.exec('COMMIT');return{schemaVersion:V42_VERSION,noOp:false,before,after}}
  catch(error){db.exec('ROLLBACK');throw error}
}
