export const V28_VERSION=28
const columns=(db,table)=>new Set(db.prepare(`PRAGMA table_info("${table}")`).all().map(row=>row.name))
const add=(db,table,name,definition)=>{if(!columns(db,table).has(name))db.exec(`ALTER TABLE "${table}" ADD COLUMN "${name}" ${definition}`)}
export function ensureV28Schema(db){
  add(db,'dispatch_trips','completed_at','TEXT');add(db,'dispatch_trips','completed_by_employee_id','INTEGER REFERENCES employees(id)')
  add(db,'dispatch_stops','completion_outcome','TEXT');add(db,'dispatch_stops','completed_by_employee_id','INTEGER REFERENCES employees(id)')
  db.exec(`CREATE TABLE IF NOT EXISTS driver_no_goods_proofs(id INTEGER PRIMARY KEY AUTOINCREMENT,dispatch_stop_id INTEGER NOT NULL UNIQUE REFERENCES dispatch_stops(id),dispatch_trip_id INTEGER NOT NULL REFERENCES dispatch_trips(id),driver_employee_id INTEGER NOT NULL REFERENCES employees(id),vehicle_id INTEGER NOT NULL REFERENCES vehicles(id),reason TEXT NOT NULL,storage_key TEXT NOT NULL UNIQUE,original_name TEXT NOT NULL,content_type TEXT NOT NULL,size_bytes INTEGER NOT NULL,created_at TEXT NOT NULL)`)
}
export function applyV28Migration(db){const version=Number(db.prepare('SELECT COALESCE(MAX(version),0) version FROM schema_meta').get().version);if(version!==0&&version<27)throw new Error(`Schema v27 is required before v28; current schema is v${version}`);if(db.prepare('PRAGMA integrity_check').get().integrity_check!=='ok')throw new Error('Database integrity check failed before v28 migration');const count=()=>({trips:db.prepare('SELECT COUNT(*) n FROM dispatch_trips').get().n,stops:db.prepare('SELECT COUNT(*) n FROM dispatch_stops').get().n,completed:db.prepare("SELECT COUNT(*) n FROM dispatch_stops WHERE status='completed'").get().n}),before=count();db.exec('BEGIN IMMEDIATE');try{ensureV28Schema(db);db.prepare('INSERT OR IGNORE INTO schema_meta(version) VALUES(?)').run(V28_VERSION);const after=count();if(JSON.stringify(before)!==JSON.stringify(after))throw new Error('Protected dispatch counts changed during v28 migration');db.exec('COMMIT');return{schemaVersion:V28_VERSION,before,after}}catch(error){db.exec('ROLLBACK');throw error}}
