import {createHash} from 'node:crypto'
import {canCorrectExpense,canApproveExpense} from './expenseCorrectionService.mjs'
import {withImmediateTransaction} from './branchServiceDateGuard.mjs'
import {unloadingCode} from './routeUnloadingService.mjs'
const fail=(code,statusCode=409)=>Object.assign(Error(code),{code,statusCode})
function access(db,a,approve=false){if(!(approve?canApproveExpense(db,a):canCorrectExpense(db,a)))throw fail('PERMISSION_DENIED',403)}
const name=a=>a.employeeName||a.username||String(a.id)
export const unloadingEditable={weighedAt:'weighed_at',tripNumber:'trip_number',vehicleCode:'vehicle_code_snapshot',registrationNumber:'registration_number_snapshot',driverName:'driver_name_snapshot',crew:'crew_names_snapshot',locationName:'unloading_location_name_snapshot',address:'unloading_address_snapshot',estimatedWeightKg:'estimated_weight_kg',grossWeightKg:'gross_weight_kg',tareWeightKg:'tare_weight_kg',confirmedWeightKg:'confirmed_weight_kg'}
const fields=r=>Object.fromEntries(Object.entries(unloadingEditable).map(([k,col])=>[k,r[col]??null]))
function current(db,id){const r=db.prepare('SELECT * FROM unloading_weight_records WHERE id=?').get(Number(id));if(!r)throw fail('NOT_FOUND',404);const h=db.prepare('SELECT * FROM unloading_corrections WHERE record_id=? ORDER BY id DESC').all(r.id);return{row:r,values:fields(r),revision:createHash('sha256').update(JSON.stringify(r)+'|'+(h[0]?.id||0)).digest('hex'),history:h}}
function reason(p){const r=String(p.reason||'').trim();if(!r||r.length>500)throw fail('REQUIRED_FIELD',400);return r}
const text=(v,max=250)=>{const s=String(v??'').trim();if(s.length>max)throw fail('REQUIRED_FIELD',400);return s||null}
function normalize(db,values,old){
 if(!values||Object.keys(values).some(k=>!Object.hasOwn(unloadingEditable,k)))throw fail('REQUIRED_FIELD',400)
 const v={...old,...values}
 if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?\+08:00$/.test(v.weighedAt||''))throw fail('REQUIRED_FIELD',400)
 const timestamp=Date.parse(v.weighedAt);if(!Number.isFinite(timestamp)||new Date(timestamp+8*3600000).toISOString().slice(0,16)!==v.weighedAt.slice(0,16)||timestamp>Date.now()+60000)throw fail('REQUIRED_FIELD',400)
 v.tripNumber=Number(v.tripNumber);if(!Number.isInteger(v.tripNumber)||v.tripNumber<1||v.tripNumber>3)throw fail('REQUIRED_FIELD',400)
 for(const k of ['estimatedWeightKg','grossWeightKg','tareWeightKg','confirmedWeightKg']){v[k]=v[k]==null||v[k]===''?null:Number(v[k]);if(v[k]!=null&&(!Number.isFinite(v[k])||v[k]<0||v[k]>100000||Math.abs(v[k]*100-Math.round(v[k]*100))>0.000001))throw fail('REQUIRED_FIELD',400)}
 if(!(v.confirmedWeightKg>0))throw fail('REQUIRED_FIELD',400)
 if(v.grossWeightKg!=null&&v.tareWeightKg!=null&&v.grossWeightKg<v.tareWeightKg)throw fail('REQUIRED_FIELD',400)
 for(const k of ['vehicleCode','registrationNumber','driverName','crew','locationName','address'])v[k]=text(v[k],k==='address'?500:250)
 if(!v.vehicleCode||!v.driverName||!v.locationName)throw fail('REQUIRED_FIELD',400)
 if(/[\u3400-\u9fff]/.test((v.locationName||'')+(v.address||'')))throw fail('INVALID_LOCATION_TEXT',400)
 // Names on an unchanged historical record remain valid, even after a master is deactivated.
 if(v.vehicleCode!==old.vehicleCode||v.registrationNumber!==old.registrationNumber){if(!db.prepare("SELECT 1 FROM vehicles WHERE vehicle_code=? AND COALESCE(registration_number,'')=? AND status IN ('available','assigned') AND operational_status IN ('active','available')").get(v.vehicleCode,v.registrationNumber||''))throw fail('CONFLICT')}
 if(v.driverName!==old.driverName&&!db.prepare("SELECT 1 FROM employees e WHERE name=? AND is_active=1 AND employment_status='active' AND (lower(job_role) IN ('driver','supervisor') OR EXISTS(SELECT 1 FROM employee_job_roles r WHERE r.employee_id=e.id AND r.role='Driver' AND r.is_active=1))").get(v.driverName))throw fail('CONFLICT')
 return Object.fromEntries(Object.keys(unloadingEditable).map(k=>[k,v[k]]))
}
export function unloadingCorrectionDetail(db,a,id){access(db,a);const c=current(db,id);return{id:c.row.id,code:unloadingCode({id:c.row.id,serviceDate:c.row.service_date}),values:c.values,revision:c.revision,history:c.history,status:c.row.status,photoUrl:`/api/unloading-weights/${c.row.id}/photo`}}
export function unloadingCorrectionCenter(db,a,q=''){access(db,a);q=String(q).trim().toUpperCase();if(q.length>70)throw fail('REQUIRED_FIELD',400);const m=/^UL-\d{8}-(\d+)$/.exec(q);let item=null;if(m){try{const x=unloadingCorrectionDetail(db,a,Number(m[1]));if(x.code===q)item=x}catch(e){if(e.code!=='NOT_FOUND')throw e}}
 return{item,canApprove:canApproveExpense(db,a),requests:db.prepare("SELECT r.*,w.service_date FROM unloading_correction_requests r JOIN unloading_weight_records w ON w.id=r.record_id ORDER BY CASE r.status WHEN 'pending' THEN 0 ELSE 1 END,r.id DESC LIMIT 100").all().map(r=>({...r,code:unloadingCode({id:r.record_id,serviceDate:r.service_date})})),vehicles:db.prepare("SELECT vehicle_code vehicleCode,registration_number registrationNumber FROM vehicles WHERE status IN ('available','assigned') AND operational_status IN ('active','available') ORDER BY vehicle_code").all(),employees:db.prepare("SELECT e.name,e.job_role jobRole,(lower(e.job_role) IN ('driver','supervisor') OR EXISTS(SELECT 1 FROM employee_job_roles r WHERE r.employee_id=e.id AND r.role='Driver' AND r.is_active=1)) isDriver FROM employees e WHERE is_active=1 AND employment_status='active' ORDER BY name").all(),locations:db.prepare("SELECT name,address FROM operational_locations WHERE COALESCE(status,'active')='active' ORDER BY name").all()}
}
export function requestUnloadingCorrection(db,a,id,p){access(db,a);const why=reason(p);return withImmediateTransaction(db,()=>{const c=current(db,id);if(p.revision!==c.revision)throw fail('CONFLICT');const after=normalize(db,p.values,c.values);if(JSON.stringify(after)===JSON.stringify(c.values))throw fail('CONFLICT');if(db.prepare("SELECT 1 FROM unloading_correction_requests WHERE record_id=? AND status='pending'").get(id))throw fail('CONFLICT');const r=db.prepare('INSERT INTO unloading_correction_requests(record_id,before_json,after_json,expected_revision,reason,requester_account_id,requester_name,created_at) VALUES(?,?,?,?,?,?,?,?)').run(id,JSON.stringify({...c.values,status:c.row.status}),JSON.stringify(after),c.revision,why,a.id,name(a),new Date().toISOString());return{status:'pending',requestId:Number(r.lastInsertRowid)}})}
export function decideUnloadingCorrection(db,a,id,decision,p){access(db,a,true);const why=reason(p);if(!['approve','reject'].includes(decision))throw fail('REQUIRED_FIELD',400);return withImmediateTransaction(db,()=>{const r=db.prepare('SELECT * FROM unloading_correction_requests WHERE id=?').get(Number(id));if(!r||r.status!=='pending')throw fail('CONFLICT');const now=new Date().toISOString();if(decision==='approve'){const c=current(db,r.record_id);if(c.revision!==r.expected_revision)throw fail('CONFLICT');const after=normalize(db,JSON.parse(r.after_json),c.values);db.prepare(`UPDATE unloading_weight_records SET ${Object.values(unloadingEditable).map(k=>k+'=?').join(',')},status='confirmed',confirmed_at=COALESCE(confirmed_at,?),updated_at=? WHERE id=?`).run(...Object.values(after),now,now,r.record_id);db.prepare('INSERT INTO unloading_corrections(request_id,record_id,before_json,after_json,reason,review_reason,actor_account_id,actor_name,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(r.id,r.record_id,r.before_json,JSON.stringify(after),r.reason,why,a.id,name(a),now)}db.prepare('UPDATE unloading_correction_requests SET status=?,reviewer_account_id=?,reviewer_name=?,review_reason=?,reviewed_at=? WHERE id=?').run(decision==='approve'?'approved':'rejected',a.id,name(a),why,now,r.id);return{status:decision==='approve'?'approved':'rejected'}})}
