const targets=[
  {id:1,plate:'QAV3468',registered_owner:'LEE SAI KER ENTERPRISE',brand:'HINO',model:'WU410R-HKMMS3',chassis_number:'JHFUF13H206007753',engine_number:'W04DJ39258',engine_capacity_cc:4009,fuel_type:'Diesel',vehicle_origin:'PEMASANGAN TEMPATAN',vehicle_class:'BRG-RIGID DECON 950-7500KG',vehicle_type:'LORI RIGID - KARGO AM',manufacture_year:2010,registration_date:'2010-12-16',gross_vehicle_weight_kg:5000,unladen_weight_kg:2950},
  {id:2,plate:'QAA4293N',registered_owner:'EAZY GARLIC ENTERPRISE',brand:'HINO',model:'WU710R-HKMQL3',chassis_number:'JHHUJL1H806001153',engine_number:'W04DTN35989',engine_capacity_cc:4009,fuel_type:'Diesel',vehicle_type:'LORI RIGID - KARGO AM',manufacture_year:2015,registration_date:'2015-08-25',gross_vehicle_weight_kg:5000,unladen_weight_kg:3220},
  {id:3,plate:'QAB1225B',registered_owner:'LEE SAI KER ENTERPRISE',brand:'TATA',model:'ULTRA 512',chassis_number:'MAT752262G8R25803',engine_number:'497TC92KTY84156',engine_capacity_cc:3783,fuel_type:'Diesel',vehicle_class:'BRG-RIGID DECON 950-7500KG',vehicle_type:'LORI RIGID - KARGO AM',manufacture_year:2016,registration_date:'2020-12-04',gross_vehicle_weight_kg:7500,unladen_weight_kg:3430},
  {id:4,plate:'QM3028M',registered_owner:'LEE SAI KER ENTERPRISE',brand:'HINO',model:'XZU720 (RB/NEK N01)',chassis_number:'XZU720-0006873',engine_number:'N04CUP37792',engine_capacity_cc:4009,fuel_type:'Diesel',vehicle_origin:'KENDERAAN PEMBINAAN SEMULA - REBUILD',vehicle_class:'BRG-RIGID DECON 950-7500KG',vehicle_type:'LORI RIGID - ROLL ON ROLL OFF',manufacture_year:2023,registration_date:'2023-04-20',gross_vehicle_weight_kg:7500,unladen_weight_kg:3630},
  {id:5,plate:'QTY5028',registered_owner:'LEE SAI KER ENTERPRISE',brand:'HINO',model:'XZU710 (RB/NEK N02)',chassis_number:'XZU710-0019064',engine_number:'N04CU019365',engine_capacity_cc:4009,fuel_type:'Diesel',vehicle_origin:'KENDERAAN PEMBINAAN SEMULA - REBUILD',vehicle_class:'BRG-RIGID DECON 950-7500KG',vehicle_type:'LORI RIGID - ROLL ON ROLL OFF',manufacture_year:2023,registration_date:'2023-06-07',gross_vehicle_weight_kg:7500,unladen_weight_kg:3770},
  {id:8,plate:'QM630S',registered_owner:'LEE SAI KER ENTERPRISE',brand:'FOTON',model:'BJ1088VEJEA-RF',chassis_number:'PNEV4JBB9PY407439',engine_number:'1SF38S315477289504',engine_capacity_cc:3760,fuel_type:'Diesel',vehicle_origin:'PEMASANGAN TEMPATAN',vehicle_class:'BRG-RIGID DECON 950-7500KG',vehicle_type:'LORI RIGID - ROLL ON ROLL OFF',manufacture_year:2024,registration_date:'2025-07-15',gross_vehicle_weight_kg:7500,unladen_weight_kg:3780}
]
const protectedColumns=['registration_number','registered_owner','chassis_number','engine_number']
const normalized=value=>String(value??'').trim()
export function vehicleMasterV29Targets(){return structuredClone(targets)}
export function applyVehicleMasterV29(db,{actorName,reason='JPJ Vehicle Ownership Certificate verified master update'}={}){
  if(!normalized(actorName))throw new Error('A trusted system actor name is required')
  const version=Number(db.prepare('SELECT COALESCE(MAX(version),0) version FROM schema_meta').get().version);if(version!==29)throw new Error(`Schema v29 is required; current schema is v${version}`)
  if(db.prepare('PRAGMA integrity_check').get().integrity_check!=='ok')throw new Error('Database integrity check failed')
  const sold=db.prepare('SELECT * FROM vehicles WHERE id=9').get();if(!sold||sold.registration_number!=='QTW2704'||sold.operational_status!=='sold'||!sold.sold_at)throw new Error('QTW2704 sold-history protection assertion failed')
  const planned=[]
  for(const target of targets){const before=db.prepare('SELECT * FROM vehicles WHERE id=?').get(target.id);if(!before)throw new Error(`Vehicle ID ${target.id} was not found`);if(before.registration_number!==target.plate)throw new Error(`Vehicle ID ${target.id} plate conflict: expected ${target.plate}, found ${before.registration_number}`);const values={...target};delete values.id;delete values.plate;for(const column of protectedColumns){const proposed=column==='registration_number'?target.plate:values[column];if(normalized(before[column])&&normalized(before[column])!==normalized(proposed))throw new Error(`Vehicle ID ${target.id} ${column} conflict`)}const changed=Object.keys(values).filter(column=>before[column]!==values[column]&&!(before[column]==null&&values[column]===undefined));planned.push({target,values,before,changed})}
  const baseline=planned.map(({before})=>({id:before.id,vehicle_code:before.vehicle_code,registration_number:before.registration_number,capacity_kg:before.capacity_kg,operational_status:before.operational_status,sold_at:before.sold_at}))
  db.exec('BEGIN IMMEDIATE');try{let updated=0,audits=0;for(const item of planned){if(!item.changed.length)continue;const columns=Object.keys(item.values).filter(key=>item.values[key]!==undefined),sql=columns.map(column=>`${column}=?`).join(',');db.prepare(`UPDATE vehicles SET ${sql},updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(...columns.map(column=>item.values[column]),item.target.id);const after=db.prepare('SELECT * FROM vehicles WHERE id=?').get(item.target.id);db.prepare(`INSERT INTO master_change_history(entity_type,entity_id,change_type,field_name,before_json,after_json,reason,changed_by) VALUES('vehicle',?,'update',?,?,?,?,?)`).run(String(item.target.id),item.changed.join(','),JSON.stringify(item.before),JSON.stringify(after),reason,actorName);updated++;audits++}
    const afterBaseline=planned.map(({target})=>{const row=db.prepare('SELECT id,vehicle_code,registration_number,capacity_kg,operational_status,sold_at FROM vehicles WHERE id=?').get(target.id);return row});if(JSON.stringify(baseline)!==JSON.stringify(afterBaseline))throw new Error('Protected vehicle identity, capacity or status changed');db.exec('COMMIT');return{vehiclesMatched:planned.length,vehiclesUpdated:updated,auditsAdded:audits,noOp:updated===0}}
  catch(error){db.exec('ROLLBACK');throw error}
}
