import {useEffect,useState} from 'react'
import {createPortal} from 'react-dom'
import {useI18n} from './i18n.jsx'
import {apiRequest} from './apiClient.js'
import DateInput from './DateInput.jsx'
import {kuchingDate} from '../shared/kuchingTime.js'
import {accountStatementBuffer} from './accountStatement.js'
import './ExportDateDialog.css'
const copy={zh:{title:'Account Statement',from:'开始日期',to:'结束日期',method:'付款方式',customer:'客户',branch:'分店',all:'全部',download:'导出 Excel',close:'关闭',loading:'读取中…',empty:'所选范围没有有效采购单。'},en:{title:'Account Statement',from:'Start date',to:'End date',method:'Payment method',customer:'Customer',branch:'Branch',all:'All',download:'Export Excel',close:'Close',loading:'Loading…',empty:'No issued purchase bills match this selection.'},ms:{title:'Penyata Akaun',from:'Tarikh mula',to:'Tarikh akhir',method:'Kaedah bayaran',customer:'Pelanggan',branch:'Cawangan',all:'Semua',download:'Eksport Excel',close:'Tutup',loading:'Memuatkan…',empty:'Tiada bil belian sah bagi pilihan ini.'}}
export default function AccountStatement(){
 const{language}=useI18n(),m=copy[language]||copy.en,[open,setOpen]=useState(false),[from,setFrom]=useState(kuchingDate().slice(0,7)+'-01'),[to,setTo]=useState(kuchingDate()),[method,setMethod]=useState('Credit'),[customer,setCustomer]=useState(''),[branch,setBranch]=useState(''),[items,setItems]=useState([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(!open||!from||!to||from>to)return;let active=true;setLoading(true);setError('');setItems([]);apiRequest('/api/purchase-bills?'+new URLSearchParams({from,to,paymentMethod:method,exportRange:'1'})).then(d=>{if(active)setItems(d.items.filter(b=>b.status==='issued').map(b=>({...b,customerName:b.statementCustomerName||b.customerName,branchName:b.statementBranchName||b.branchName})))}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[open,from,to,method])
 const customers=[...new Set(items.map(b=>b.customerName))].sort(),branches=[...new Set(items.filter(b=>!customer||b.customerName===customer).map(b=>b.branchName))].sort()
 const download=async e=>{e.preventDefault();if(busy||loading)return;setBusy(true);setError('');try{const data=await accountStatementBuffer(items.filter(b=>(!customer||b.customerName===customer)&&(!branch||b.branchName===branch)),{from,to,paymentMethod:method});const url=URL.createObjectURL(new Blob([data],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=url;a.download=`Account_Statement_${method}_${from}_${to}.xlsx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setOpen(false)}catch(e){setError(e.message==='EMPTY_STATEMENT'?m.empty:e.message)}finally{setBusy(false)}}
 return <><button type="button" onClick={()=>setOpen(true)}>{m.title}</button>{open&&createPortal(<div className="kcs-export-overlay" onClick={e=>{if(e.target===e.currentTarget&&!busy)setOpen(false)}}><form className="kcs-export-dialog" role="dialog" aria-modal="true" aria-label={m.title} onSubmit={download}><header><h2>{m.title}</h2><button type="button" disabled={busy} aria-label={m.close} onClick={()=>setOpen(false)}>×</button></header><fieldset disabled={busy} style={{border:0,padding:0}}><label>{m.from}<DateInput required type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>{m.to}<DateInput required type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><label>{m.method}<select value={method} onChange={e=>{setMethod(e.target.value);setCustomer('');setBranch('')}}><option>Credit</option><option>Cash</option></select></label><label>{m.customer}<select value={customer} onChange={e=>{setCustomer(e.target.value);setBranch('')}}><option value="">{m.all}</option>{customers.map(v=><option key={v} data-i18n-raw>{v}</option>)}</select></label><label>{m.branch}<select value={branch} onChange={e=>setBranch(e.target.value)}><option value="">{m.all}</option>{branches.map(v=><option key={v} data-i18n-raw>{v}</option>)}</select></label></fieldset>{loading&&<p role="status">{m.loading}</p>}{error&&<p role="alert">{error}</p>}<footer><button type="submit" disabled={busy||loading||!from||!to||from>to}>{m.download}</button></footer></form></div>,document.body)}</>
}
