import {useEffect,useState} from 'react'
import {apiRequest as api} from './apiClient.js'
import {useI18n} from './i18n.jsx'
import {DriverGuide} from './DriverGuide.jsx'
import './EmployeePreview.css'

export default function ActingCollectorPage({onEnterMobile}){
 const{t}=useI18n(),[data,setData]=useState(null),[employees,setEmployees]=useState([]),[employeeId,setEmployeeId]=useState(''),[revision,setRevision]=useState(0),[guide,setGuide]=useState(false),[busy,setBusy]=useState(null),[error,setError]=useState('')
 const load=async()=>{try{const [d,e]=await Promise.all([api('/api/acting-collector/today'),api('/api/acting-collector/preview-employees')]);setData(d);setEmployees(e.items);setEmployeeId(id=>e.items.some(e=>String(e.employeeId)===id)?id:'');setError('')}catch(e){setError(e.message)}}
 useEffect(()=>{void load()},[])
 const claim=async vehicle=>{if(!window.confirm(t('acting.confirm',{plate:vehicle.registrationNumber||vehicle.vehicleCode})))return;setBusy(vehicle.vehicleId);setError('');try{await api(`/api/acting-collector/vehicle/${vehicle.vehicleId}`,{method:'POST',body:'{}'});onEnterMobile()}catch(item){setError(item.message)}finally{setBusy(null)}}
 return <div className="page acting-collector-page"><div className="heading"><div><p>{t('preview.help')}</p></div><button className="secondary" onClick={()=>setGuide(!guide)}>{t('guide.title')}</button></div>{guide&&<DriverGuide/>}{error&&<p role="alert">{error}</p>}<div className="employee-preview-controls"><label>{t('preview.employee')}<select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">{t('preview.select')}</option>{employees.map(e=><option key={e.employeeId} value={e.employeeId} data-i18n-raw>{e.employeeName} · {e.employeeCode}</option>)}</select></label><button onClick={()=>{void load();setRevision(r=>r+1)}}>{t('notice.refresh')}</button>{employeeId&&<button onClick={()=>setEmployeeId('')}>{t('preview.close')}</button>}</div>{employeeId?<section className="employee-preview-section"><p>{t('preview.snapshot')}</p><iframe key={employeeId+'-'+revision} className="employee-preview-frame" title={t('preview.title')} src={`/?employeePreview=${employeeId}&revision=${revision}`} sandbox="allow-scripts allow-same-origin allow-popups" allow="camera 'none'; microphone 'none'; geolocation 'none'"/></section>:!data?<p>{t('common.loadingData')}</p>:<section className="acting-vehicle-list">{data.vehicles.map(vehicle=><article key={vehicle.vehicleId+'-'+vehicle.driverId}><header><div><strong data-i18n-raw>{vehicle.registrationNumber||vehicle.vehicleCode}</strong><span>{vehicle.totalStops} {t('mobile.stops')}</span></div><small>{t('acting.currentDriver')}: <span data-i18n-raw>{vehicle.driverName||'—'}</span></small></header><div className="acting-actions"><button className="secondary" disabled={!employees.some(e=>e.employeeId===vehicle.driverId)} onClick={()=>setEmployeeId(String(vehicle.driverId))}>{t('preview.open')}</button><button disabled={busy!==null||vehicle.assignedToMe||!vehicle.approved} onClick={()=>claim(vehicle)}>{!vehicle.approved?t('acting.approveFirst'):vehicle.assignedToMe?t('acting.assignedToMe'):busy===vehicle.vehicleId?t('common.saving'):t('acting.takeOver')}</button></div></article>)}</section>}</div>
}
