import {useCallback,useEffect,useState} from 'react'
import {apiRequest} from './apiClient.js'
import {useI18n} from './i18n.jsx'
import './AddressAnalysisPage.css'

const bucketIds=['missing_with_gps','missing_without_gps','incomplete','evidence_conflict','ready_review','reviewed_unchanged']
const Copy=({value,label,t})=><button className="address-copy" title={t('addressAnalysis.copyTitle',{label})} aria-label={t('addressAnalysis.copyTitle',{label})} onClick={event=>{event.stopPropagation();navigator.clipboard?.writeText(String(value||''))}}>⧉</button>

export default function AddressAnalysisPage({onOpenRecommendations}){
  const{t}=useI18n(),[data,setData]=useState(null),[search,setSearch]=useState(''),[bucket,setBucket]=useState(''),[selected,setSelected]=useState(null),[preview,setPreview]=useState(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[later,setLater]=useState(new Set()),[kept,setKept]=useState(new Set())
  const load=useCallback(async()=>{try{setError('');const query=new URLSearchParams({...(search?{search}:{}),...(bucket?{bucket}:{})});setData(await apiRequest(`/api/address-analysis?${query}`))}catch(err){setError(err.message)}},[search,bucket])
  useEffect(()=>{const timer=setTimeout(load,200);return()=>clearTimeout(timer)},[load])
  const reverse=async item=>{try{setError('');setPreview(await apiRequest(`/api/address-analysis/${encodeURIComponent(item.branchId)}/reverse-geocode-preview`,{method:'POST',body:'{}'}))}catch(err){setError(err.message)}}
  const useAddress=async()=>{if(!reason.trim())return setError(t('addressAnalysis.reasonRequired'));try{const item=await apiRequest(`/api/address-analysis/${encodeURIComponent(selected.branchId)}/use-suggested-address`,{method:'POST',body:JSON.stringify({previewToken:preview.previewToken,reason})});setSelected(item);setPreview(null);setReason('');await load()}catch(err){setError(err.message)}}
  const reviewLater=id=>setLater(previous=>new Set(previous).add(id))
  const keepCurrent=id=>setKept(previous=>new Set(previous).add(id))
  const open=item=>{setSelected(item);setPreview(null);setReason('')}
  const keyOpen=(event,item)=>{if(['Enter',' '].includes(event.key)){event.preventDefault();open(item)}}
  const none=value=>value||t('common.notSet')
  return <section className="address-analysis">
    <header><div><em>{t('addressAnalysis.eyebrow')}</em><h2>{t('addressAnalysis.title')}</h2><p>{t('addressAnalysis.safety')}</p></div><span>{t('addressAnalysis.noBulk')}</span></header>
    {error&&<div className="address-error" role="alert">{error}</div>}
    <div className="address-counts">{bucketIds.map(id=><button key={id} className={bucket===id?'active':''} onClick={()=>setBucket(bucket===id?'':id)}><strong>{data?.counts?.[id]??'—'}</strong><small>{t(`addressAnalysis.bucket.${id}`)}</small></button>)}</div>
    <div className="address-filters"><input aria-label={t('addressAnalysis.searchLabel')} placeholder={t('addressAnalysis.searchPlaceholder')} value={search} onChange={event=>setSearch(event.target.value)}/><select aria-label={t('addressAnalysis.bucketLabel')} value={bucket} onChange={event=>setBucket(event.target.value)}><option value="">{t('addressAnalysis.allActive')}</option>{bucketIds.map(id=><option key={id} value={id}>{t(`addressAnalysis.bucket.${id}`)}</option>)}</select></div>
    <div className="address-list">{data?.items?.map(item=><article key={item.internalBranchId} className="interactive-card" role="button" tabIndex="0" onClick={()=>open(item)} onKeyDown={event=>keyOpen(event,item)}><div><span><b>{item.branchId}</b><Copy value={item.branchId} label={t('addressAnalysis.branchId')} t={t}/></span><strong>{item.branchName}</strong><small>{item.customerName} · {item.lifecycle}</small></div><div><b>{none(item.currentArea)}</b><small>{t('addressAnalysis.zone')}: {none(item.currentZone)}</small><p>{item.address||t('addressAnalysis.addressMissing')}</p></div><div><span className={item.officialGps.available?'ok':'manual'}>{t(item.officialGps.available?'addressAnalysis.officialGps':'addressAnalysis.noOfficialGps')}</span>{item.pendingGps&&<span className="pending">{t('addressAnalysis.pendingIgnored')}</span>}<small>{t(`addressAnalysis.confidence.${item.proposedArea.confidence}`)} · {t(item.proposedArea.manualReviewRequired?'addressAnalysis.manualReview':'addressAnalysis.reviewReady')}</small></div></article>)}{data&&!data.items.length&&<p className="address-empty">{t('addressAnalysis.empty')}</p>}</div>
    {selected&&<div className="address-backdrop" onClick={()=>setSelected(null)}><aside className="address-detail" onClick={event=>event.stopPropagation()}><header><div><h2>{selected.branchId} · {selected.branchName}</h2><p>{selected.customerName} · {selected.lifecycle}</p></div><button aria-label={t('common.close')} onClick={()=>setSelected(null)}>×</button></header>
      <section><h3>{t('addressAnalysis.currentAddress')}</h3><p>{selected.address||t('addressAnalysis.addressMissing')} <Copy value={selected.address} label={t('common.address')} t={t}/></p><dl><dt>{t('addressAnalysis.state')}</dt><dd>{none(selected.structuredAddress.state)}</dd><dt>{t('addressAnalysis.city')}</dt><dd>{none(selected.structuredAddress.city)}</dd><dt>{t('addressAnalysis.streetNumber')}</dt><dd>{none(`${selected.structuredAddress.street} ${selected.structuredAddress.streetNumber}`.trim())}</dd><dt>{t('addressAnalysis.postcode')}</dt><dd>{none(selected.structuredAddress.postcode)}</dd></dl></section>
      <section><h3>{t('addressAnalysis.gpsEvidence')}</h3><p><b>{t(selected.officialGps.available?'addressAnalysis.officialGps':'addressAnalysis.officialGpsMissing')}</b>{selected.officialGps.available&&<>: {selected.officialGps.latitude}, {selected.officialGps.longitude} <Copy value={`${selected.officialGps.latitude}, ${selected.officialGps.longitude}`} label={t('addressAnalysis.coordinates')} t={t}/></>}</p>{selected.pendingGps&&<p className="warning"><b>{t('addressAnalysis.pendingIgnored')}:</b> {selected.pendingGps.latitude}, {selected.pendingGps.longitude}. {t('addressAnalysis.notProof')}</p>}</section>
      <section><h3>{t('addressAnalysis.parsedEvidence')}</h3><p>{t('addressAnalysis.tokens')}: {selected.addressEvidence.tokens.join(', ')||t('common.none')} · {t('addressAnalysis.postcodes')}: {selected.addressEvidence.postcodes.join(', ')||t('common.none')}</p><p>{t('addressAnalysis.areaCandidates')}: {selected.addressEvidence.areaCandidates.map(area=>`${area.name} (${area.matchedTokens.join(', ')})`).join('; ')||t('common.none')}</p><p><b>{t('addressAnalysis.zonePolygon')}:</b> {t(`addressAnalysis.polygon.${selected.zoneEvidence.polygonStatus}`)}. {t('addressAnalysis.zoneOnly')}</p><h4>{t('addressAnalysis.nearby')}</h4>{selected.nearbyBranches.map(branch=><p key={branch.id}>{branch.branchId} {branch.branchName} · {branch.areaName} · {branch.distanceMeters}m</p>)}{!selected.nearbyBranches.length&&<p>{t('common.none')}</p>}</section>
      <section><h3>{t('addressAnalysis.areaRecommendation')}</h3><p><b>{none(selected.currentArea)} → {selected.proposedArea.name||t('addressAnalysis.noSafeSuggestion')}</b></p><p>{t(selected.proposedArea.manualReviewRequired?'addressAnalysis.manualExplanation':'addressAnalysis.reviewExplanation')}</p><p>{t('addressAnalysis.confidenceLabel')}: <b>{t(`addressAnalysis.confidence.${selected.proposedArea.confidence}`)}</b> · {t('addressAnalysis.strongEvidence')}: {selected.proposedArea.independentEvidence.map(value=>t(`addressAnalysis.signal.${value}`)).join(', ')||t('common.none')} · {t('addressAnalysis.conflictsCount',{count:selected.proposedArea.conflicts.length})}</p><button disabled={!selected.proposedArea.recommendationId} onClick={onOpenRecommendations}>{t('addressAnalysis.changeArea')}</button></section>
      <section><h3>{t('addressAnalysis.decisions')}</h3><p>{t('addressAnalysis.sessionLimitation')}</p><div className="address-actions"><button onClick={()=>keepCurrent(selected.internalBranchId)}>{t(kept.has(selected.internalBranchId)?'addressAnalysis.keepCurrentSession':'addressAnalysis.keepCurrent')}</button><button onClick={()=>reviewLater(selected.internalBranchId)}>{t(later.has(selected.internalBranchId)?'addressAnalysis.reviewLaterSession':'addressAnalysis.reviewLater')}</button><button disabled={!selected.officialGps.available} onClick={()=>reverse(selected)}>{t('addressAnalysis.previewGoogle')}</button></div>{kept.has(selected.internalBranchId)&&<p className="address-session-feedback" role="status">{t('addressAnalysis.keepFeedback')}</p>}{preview&&<div className="address-preview"><b>{t('addressAnalysis.previewNotProof')}</b><p>{preview.candidate.address} <Copy value={preview.candidate.address} label={t('addressAnalysis.suggestedAddress')} t={t}/></p><small>{t('addressAnalysis.previewExplanation')}</small><label>{t('addressAnalysis.mandatoryReason')}<textarea value={reason} onChange={event=>setReason(event.target.value)}/></label><button className="confirm" onClick={useAddress}>{t('addressAnalysis.useSuggested')}</button></div>}</section>
    </aside></div>}
  </section>
}
