import { useEffect, useState } from 'react'
import './App.css'
import ImportPage from './ImportPage.jsx'
import WeeklyDispatchPage from './WeeklyDispatchPage.jsx'
import SpecialRequestsPage from './SpecialRequestsPage.jsx'
import ResourcePage from './ResourcePage.jsx'
import { CustomerBranchesPage, DataQualityPage, SchedulesPage } from './DataPages.jsx'

const navigation=[['dashboard','⌂','总览'],['dispatch','↗','一周派车'],['special','＋','临时收货请求'],['customers','◎','客户与分店'],['schedule','▷','收货排程'],['data','⌖','GPS 与资料'],['resources','◇','员工、车辆与地点'],['sync','↻','Jodoo 资料同步']]
const modules=[['dispatch','↗','一周派车','按日期、车辆和趟次安排路线，每天独立批准并发布。','打开周计划','green'],['special','＋','临时收货请求','登记老客户临时加收或潜在新客户，并保护客户承诺。','建立请求','rose'],['customers','◎','客户与分店','查询真实客户、分店、付款方式、价格、GPS 与排程。','查看客户资料','blue'],['schedule','▷','收货排程','按星期、Frequency、BranchID 和 Area 查询所有排程。','管理排程','orange'],['data','⌖','GPS 与资料完整度','分组追踪缺少 GPS、排程或关联主档的资料。','检查资料','violet'],['resources','◇','员工、车辆与地点','管理员工、车辆以及出发与结束地点。','管理资源','cyan'],['sync','↻','Jodoo 资料同步','预览并正式导入最新五类 Jodoo Excel。','准备导入','rose']]
const todayLabel=()=>{const now=new Date();const days=['星期日','星期一','星期二','星期三','星期四','星期五','星期六'];return `${now.getFullYear()}年${now.getMonth()+1}月${now.getDate()}日 · ${days[now.getDay()]}`}

export default function App(){const[page,setPage]=useState('dashboard'),[menuOpen,setMenuOpen]=useState(false),[systemStatus,setSystemStatus]=useState({connected:false,label:'后台连接中…'});useEffect(()=>{let active=true;fetch('/api/system/status').then(r=>{if(!r.ok)throw new Error();return r.json()}).then(s=>active&&setSystemStatus({connected:s.database==='connected',label:`数据库 v${s.schemaVersion} · Jodoo ${s.integrations?.jodoo?.configured?'已配置':'等待配置'}`})).catch(()=>active&&setSystemStatus({connected:false,label:'后台未连接，请重新启动系统'}));return()=>{active=false}},[]);const go=id=>{setPage(id);setMenuOpen(false)};const title=navigation.find(x=>x[0]===page)?.[2];return <div className="shell"><aside className={menuOpen?'sidebar open':'sidebar'}><div className="brand"><b>K</b><div><strong>KCS Dispatch</strong><span>LEE SAI KER ENTERPRISE</span></div></div><nav><small>工作台</small>{navigation.map(x=><button key={x[0]} className={page===x[0]?'active':''} onClick={()=>go(x[0])}><i>{x[1]}</i>{x[2]}</button>)}</nav><footer><div><i className={systemStatus.connected?'':'offline'}/><span><strong>{systemStatus.connected?'系统运行中':'系统等待后台'}</strong><small>{systemStatus.label}</small></span></div><p>诚信守时 · 服务至上</p></footer></aside>{menuOpen&&<button className="shade" aria-label="关闭菜单" onClick={()=>setMenuOpen(false)}/>}<main><header className="topbar"><button className="menu" aria-label="打开菜单" onClick={()=>setMenuOpen(true)}>☰</button><div><small>KCS DISPATCH SYSTEM</small><strong>{title}</strong></div><span>{todayLabel()}</span><b>LSK</b></header>{page==='dashboard'?<Dashboard go={go}/>:page==='sync'?<ImportPage onBack={()=>go('dashboard')}/>:page==='dispatch'?<WeeklyDispatchPage onOpenSpecial={()=>go('special')}/>:page==='special'?<SpecialRequestsPage onOpenPlanner={()=>go('dispatch')}/>:page==='customers'?<CustomerBranchesPage/>:page==='schedule'?<SchedulesPage/>:page==='data'?<DataQualityPage/>:page==='resources'?<ResourcePage/>:<Placeholder page={page} go={go}/>}</main></div>}

function Dashboard({go}){const[summary,setSummary]=useState(null),[error,setError]=useState('');useEffect(()=>{let active=true;fetch('/api/dashboard/summary').then(r=>r.json().then(x=>{if(!r.ok)throw new Error(x.error||'无法读取 Dashboard');return x})).then(x=>active&&setSummary(x)).catch(e=>active&&setError(e.message));return()=>{active=false}},[]);const stats=summary?[[summary.branchCount,'客户分店','目前分店主档总数','blue'],[summary.scheduledBranchCount,'已有排程','至少一条有效排程','green'],[summary.gpsBranchCount,'已有 GPS','有效经纬度','violet'],[summary.routeReadyCount,'Route Ready','排程与 GPS 齐全','orange']]:[];const issues=summary?[[summary.scheduledMissingGpsCount,'已有排程，但缺少 GPS','需跟进'],[summary.noScheduleCount,'尚未安排收货排程','待安排'],[summary.unmatchedScheduleCount,'排程 BranchID 无法匹配','需核对']]:[];return <div className="page"><section className="welcome"><div><em>运营总览</em><h1>早安，今天从这里开始。</h1><p>所有数字来自 SQLite 实时资料，不再使用示范数字。</p></div><button onClick={()=>go('dispatch')}>＋ 建立今日派车</button></section>{error?<div className="data-error">后台无法连接：{error}</div>:!summary?<div className="data-loading">Dashboard 资料载入中…</div>:<><section className="stats">{stats.map(s=><article className={s[3]} key={s[1]}><span>{s[1]}</span><strong>{s[0]}</strong><small>{s[2]}</small></article>)}</section><section className="layout"><div><Heading label="主要功能" title="系统模块"/><div className="cards">{modules.map(m=><button className="card" key={m[0]} onClick={()=>go(m[0])}><i className={m[5]}>{m[1]}</i><span><strong>{m[2]}</strong><small>{m[3]}</small><b>{m[4]} →</b></span></button>)}</div></div><aside className="data"><Heading label="资料状态" title="需要处理" action={()=>go('data')}/><div className="progress"><span><b>Route Ready</b><strong>{summary.routeReadyCount} / {summary.branchCount}</strong></span><div><i style={{width:`${summary.branchCount?summary.routeReadyCount/summary.branchCount*100:0}%`}}/></div><small>有排程、有效 GPS，且状态可使用</small></div><div className="issues">{issues.map(x=><button key={x[1]} onClick={()=>go('data')}><strong>{x[0]}</strong><span>{x[1]}<small>{x[2]}</small></span><b>›</b></button>)}</div></aside></section></>}</div>}
function Heading({label,title,action}){return <div className="heading"><div><em>{label}</em><h2>{title}</h2></div>{action&&<button onClick={action}>查看全部</button>}</div>}
function Placeholder({page,go}){const m=modules.find(x=>x[0]===page);return <div className="page placeholder"><button onClick={()=>go('dashboard')}>← 返回总览</button><section><i className={m[5]}>{m[1]}</i><h1>{m[2]}</h1><p>{m[3]}</p><small>此模块不在本阶段真实资料导入范围内</small></section></div>}
