import {useEffect,useRef,useState} from 'react'
import {apiRequest,isEmployeePreview} from './apiClient.js'
import {useI18n} from './i18n.jsx'
import {kuchingDate} from '../shared/kuchingTime.js'
import './Attendance.css'
export const attendanceWords={
 zh:{title:'上班打卡',home:'在家打卡',company:'公司打卡',method:'上班打卡方式',select:'请选择',place:'公司地点',radius:'允许范围（米）',save:'保存打卡设置',saved:'已保存',loading:'加载中…',retry:'重新加载',logout:'退出登录',busy:'正在定位及打卡…',help:'按下按钮时获取一次 GPS，记录上班时间，不持续追踪。',companyHelp:'必须在公司允许范围内才能打卡。',setup:'设置后，该员工每天首次进入系统需要打卡。未设置的员工暂不启用。',history:'最近31次打卡',daily:'员工打卡记录',date:'日期',time:'打卡时间',missing:'未打卡',empty:'暂无记录',gps:'GPS',refresh:'刷新',ATTENDANCE_GPS:'定位不够准确或已过期，请开启精确定位后重试。',ATTENDANCE_OUTSIDE:'你不在公司允许的打卡范围内，请到公司后重试。',ATTENDANCE_LOCATION:'公司地点未设置有效 GPS 或已停用，请联系管理员。',ATTENDANCE_SETUP:'请管理员先设置你的打卡方式。',ATTENDANCE_STALE:'设置已被更改，请重新加载后再保存。',ATTENDANCE_INVALID:'请检查打卡方式和范围（20–5000 米）。',ATTENDANCE_DENIED:'没有查看或修改权限。',failed:'操作未完成，请重试。'},
 en:{title:'Clock in',home:'Home clock-in',company:'Company clock-in',method:'Clock-in method',select:'Select',place:'Company location',radius:'Allowed radius (m)',save:'Save clock-in settings',saved:'Saved',loading:'Loading…',retry:'Reload',logout:'Sign out',busy:'Getting location and clocking in…',help:'GPS is captured once when you press the button to record your start time. No continuous tracking.',companyHelp:'You must be within the company clock-in area.',setup:'Once configured, this employee clocks in before entering each day. Employees without settings are not enabled yet.',history:'Last 31 clock-ins',daily:'Employee clock-in records',date:'Date',time:'Clock-in time',missing:'Not clocked in',empty:'No records',gps:'GPS',refresh:'Refresh',ATTENDANCE_GPS:'Location is inaccurate or expired. Enable precise location and retry.',ATTENDANCE_OUTSIDE:'Outside the company clock-in area. Retry at the company.',ATTENDANCE_LOCATION:'Company GPS is missing or the location is inactive. Contact the administrator.',ATTENDANCE_SETUP:'Ask the administrator to configure your clock-in method.',ATTENDANCE_STALE:'Settings changed. Reload before saving.',ATTENDANCE_INVALID:'Check the method and radius (20–5000 m).',ATTENDANCE_DENIED:'No permission to view or change this.',failed:'Could not complete. Please retry.'},
 ms:{title:'Daftar masuk kerja',home:'Daftar dari rumah',company:'Daftar di syarikat',method:'Kaedah daftar masuk',select:'Pilih',place:'Lokasi syarikat',radius:'Jejari dibenarkan (m)',save:'Simpan tetapan daftar masuk',saved:'Disimpan',loading:'Memuatkan…',retry:'Muat semula',logout:'Log keluar',busy:'Mendapatkan lokasi dan mendaftar…',help:'GPS diambil sekali apabila butang ditekan untuk merekod masa mula kerja. Tiada penjejakan berterusan.',companyHelp:'Anda mesti berada dalam kawasan daftar masuk syarikat.',setup:'Selepas ditetapkan, pekerja perlu daftar masuk sebelum masuk setiap hari. Pekerja tanpa tetapan belum diaktifkan.',history:'31 rekod terakhir',daily:'Rekod daftar masuk pekerja',date:'Tarikh',time:'Masa daftar masuk',missing:'Belum daftar masuk',empty:'Tiada rekod',gps:'GPS',refresh:'Muat semula',ATTENDANCE_GPS:'Lokasi kurang tepat atau luput. Aktifkan lokasi tepat dan cuba lagi.',ATTENDANCE_OUTSIDE:'Di luar kawasan daftar masuk syarikat. Cuba lagi di syarikat.',ATTENDANCE_LOCATION:'GPS syarikat belum ditetapkan atau lokasi tidak aktif. Hubungi pentadbir.',ATTENDANCE_SETUP:'Minta pentadbir menetapkan kaedah daftar masuk.',ATTENDANCE_STALE:'Tetapan telah berubah. Muat semula sebelum menyimpan.',ATTENDANCE_INVALID:'Semak kaedah dan jejari (20–5000 m).',ATTENDANCE_DENIED:'Tiada kebenaran melihat atau mengubah.',failed:'Tidak berjaya. Sila cuba lagi.'}
}
const localTime=value=>value?new Date(value).toLocaleString('en-GB',{timeZone:'Asia/Kuching',hour12:false}):'—'
const gpsOnce=()=>new Promise((resolve,reject)=>{
 if(!navigator.geolocation)return reject({code:'ATTENDANCE_GPS'})
 navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracyM:p.coords.accuracy,deviceCapturedAt:new Date(p.timestamp).toISOString()}),()=>reject({code:'ATTENDANCE_GPS'}),{enableHighAccuracy:true,timeout:20000,maximumAge:0})
})
export function AttendanceGate({account,onLogout,children}){
 const{language}=useI18n(),w=attendanceWords[language]||attendanceWords.en
 const[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const enabled=['driver','crew'].includes(account.role)&&!isEmployeePreview()
 useEffect(()=>{if(!enabled)return;let alive=true;const load=()=>apiRequest('/api/mobile/attendance').then(d=>{if(alive){setData(d);setError('')}}).catch(e=>{if(alive){setData(null);setError(e.code||'failed')}})
 load();const timer=setInterval(load,30000),focus=()=>{if(document.visibilityState==='visible')load()};document.addEventListener('visibilitychange',focus);window.addEventListener('focus',load)
 return()=>{alive=false;clearInterval(timer);document.removeEventListener('visibilitychange',focus);window.removeEventListener('focus',load)}
 },[account.employeeId,enabled])
 if(!enabled||data?.configured===false)return children
 if(data?.record)return <><div className="attendance-receipt" role="status">{w.title}: {localTime(data.record.clocked_at)}</div>{children}</>
 const clock=async()=>{setBusy(true);setError('');try{const gps=await gpsOnce();setData(await apiRequest('/api/mobile/attendance',{method:'POST',body:JSON.stringify(gps)}))}catch(e){setError(e.code||'failed')}finally{setBusy(false)}}
 return <main className="attendance-gate"><section className="attendance-panel"><small>KCS</small><h1>{w.title}</h1><p data-i18n-raw>{account.employeeName}</p>{data?<><p>{data.date}</p><p>{w.help}</p>{data.mode==='company'&&<p>{w.companyHelp}</p>}<button className="attendance-clock" disabled={busy} onClick={clock}>{busy?w.busy:w.title}</button></>:!error?<p>{w.loading}</p>:null}{error&&<p role="alert">{w[error]||w.failed}</p>}{!data&&error&&<button onClick={async()=>{setError('');try{setData(await apiRequest('/api/mobile/attendance'))}catch(e){setError(e.code||'failed')}}}>{w.retry}</button>}<button disabled={busy} onClick={onLogout}>{w.logout}</button></section></main>
}
export function AttendanceSettings({employeeId,blocked=false}){
 const{language}=useI18n(),w=attendanceWords[language]||attendanceWords.en,[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false)
 const load=()=>apiRequest(`/api/attendance/employees/${employeeId}`).then(d=>{setData(d);setError('')}).catch(e=>setError(e.code||'failed'))
 useEffect(()=>{setData(null);load()},[employeeId])
 const change=p=>{setData(d=>({...d,...p}));setSaved(false)}
 const save=async()=>{setBusy(true);setError('');setSaved(false);try{setData(await apiRequest(`/api/attendance/employees/${employeeId}`,{method:'PATCH',body:JSON.stringify({mode:data.mode,locationId:data.locationId,radiusM:Number(data.radiusM),revision:data.revision})}));setSaved(true)}catch(e){setError(e.code||'failed')}finally{setBusy(false)}}
 return <details className="attendance-panel" open><summary>{w.method}</summary><p>{w.setup}</p>{data&&<><fieldset disabled={busy||blocked}><label>{w.method}<select value={data.mode} onChange={e=>change({mode:e.target.value})}><option value="" disabled>{w.select}</option><option value="home">{w.home}</option><option value="company">{w.company}</option></select></label>{data.mode==='company'&&<><label>{w.place}<select value={data.locationId||''} onChange={e=>change({locationId:Number(e.target.value)})}><option value="">{w.select}</option>{data.locations.map(l=><option key={l.id} value={l.id} data-i18n-raw>{l.name}</option>)}</select></label><label>{w.radius}<input type="number" min="20" max="5000" step="1" value={data.radiusM} onChange={e=>change({radiusM:e.target.value})}/></label></>}<button type="button" disabled={!data.mode} onClick={save}>{w.save}</button></fieldset><details><summary>{w.history}</summary>{data.records.length?data.records.map(r=><article key={r.id}><b>{localTime(r.clocked_at)}</b> · {w[r.mode]}<p>{w.gps}: <span data-i18n-raw>{r.latitude}, {r.longitude} (±{r.accuracy_m} m)</span></p></article>):<p>{w.empty}</p>}</details></>}{saved&&<p role="status">{w.saved}</p>}{error&&<><p role="alert">{w[error]||w.failed}</p><button type="button" onClick={load}>{w.retry}</button></>}</details>
}
export function AttendanceDaily(){
 const{language}=useI18n(),w=attendanceWords[language]||attendanceWords.en,[open,setOpen]=useState(false),[date,setDate]=useState(kuchingDate()),[data,setData]=useState(null),[error,setError]=useState(''),requestVersion=useRef(0)
 const load=()=>{const version=++requestVersion.current;setData(null);setError('');return apiRequest('/api/attendance?'+new URLSearchParams({date})).then(d=>{if(version===requestVersion.current)setData(d)}).catch(e=>{if(version===requestVersion.current)setError(e.code||'failed')})}
 useEffect(()=>{if(open)load()},[open,date])
 return <details className="attendance-panel" onToggle={e=>setOpen(e.currentTarget.open)}><summary>{w.daily}</summary>{open&&<><label>{w.date}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button onClick={load}>{w.refresh}</button>{error&&<p role="alert">{w[error]||w.failed}</p>}<div className="attendance-records">{data?.items.map(r=><article key={r.employeeId}><b data-i18n-raw>{r.name}</b><p>{w[r.mode]} · {r.clocked_at?localTime(r.clocked_at):w.missing}</p>{r.clocked_at&&<p>{w.gps}: <span data-i18n-raw>{r.latitude}, {r.longitude} (±{r.accuracy_m} m)</span></p>}</article>)}</div>{data&&!data.items.length&&<p>{w.empty}</p>}</>}</details>
}
