import {createPortal} from 'react-dom'
import {FilterHeader} from './ExpenseRecordsPage.jsx'
import TableBottomScroll from './TableBottomScroll.jsx'
import DataExportButton from './DataExportButton.jsx'
import {formatDateDisplay} from './dateDisplay.js'
import DateInput from './DateInput.jsx'
import CenteredNotice from './CenteredNotice.jsx'
import {useEffect,useRef,useState} from 'react'
import {apiRequest,isEmployeePreview} from './apiClient.js'
import {useI18n} from './i18n.jsx'
import {kuchingDate} from '../shared/kuchingTime.js'
import './Attendance.css'
export const attendanceWords={
 zh:{title:'拿车时间',home:'在家打卡',company:'公司打卡',method:'上班打卡方式',select:'请选择',place:'公司地点',radius:'允许范围（米）',save:'保存打卡设置',saved:'已保存',loading:'加载中…',retry:'重新加载',logout:'退出登录',busy:'正在定位及打卡…',help:'按下按钮时获取一次 GPS，记录上班时间，不持续追踪。',companyHelp:'必须在公司允许范围内才能打卡。',setup:'默认在公司打卡，范围200米；需要在家打卡的员工请另外设置。',history:'最近31次打卡',daily:'员工打卡记录',date:'日期',time:'打卡时间',missing:'未打卡',empty:'暂无记录',gps:'GPS',refresh:'刷新',ATTENDANCE_GPS:'定位不够准确或已过期，请开启精确定位后重试。',ATTENDANCE_OUTSIDE:'你不在公司允许的打卡范围内，请到公司后重试。',ATTENDANCE_LOCATION:'公司地点未设置有效 GPS 或已停用，请联系管理员。',ATTENDANCE_SETUP:'请管理员先设置你的打卡方式。',ATTENDANCE_STALE:'设置已被更改，请重新加载后再保存。',ATTENDANCE_INVALID:'请检查打卡方式和范围（20–5000 米）。',ATTENDANCE_DENIED:'没有查看或修改权限。',failed:'操作未完成，请重试。'},
 en:{title:'Vehicle pickup time',home:'Home clock-in',company:'Company clock-in',method:'Clock-in method',select:'Select',place:'Company location',radius:'Allowed radius (m)',save:'Save clock-in settings',saved:'Saved',loading:'Loading…',retry:'Reload',logout:'Sign out',busy:'Getting location and clocking in…',help:'GPS is captured once when you press the button to record your start time. No continuous tracking.',companyHelp:'You must be within the company clock-in area.',setup:'Company clock-in within 200 m is the default. Set Home separately for employees who need it.',history:'Last 31 clock-ins',daily:'Employee clock-in records',date:'Date',time:'Clock-in time',missing:'Not clocked in',empty:'No records',gps:'GPS',refresh:'Refresh',ATTENDANCE_GPS:'Location is inaccurate or expired. Enable precise location and retry.',ATTENDANCE_OUTSIDE:'Outside the company clock-in area. Retry at the company.',ATTENDANCE_LOCATION:'Company GPS is missing or the location is inactive. Contact the administrator.',ATTENDANCE_SETUP:'Ask the administrator to configure your clock-in method.',ATTENDANCE_STALE:'Settings changed. Reload before saving.',ATTENDANCE_INVALID:'Check the method and radius (20–5000 m).',ATTENDANCE_DENIED:'No permission to view or change this.',failed:'Could not complete. Please retry.'},
 ms:{title:'Masa ambil lori',home:'Daftar dari rumah',company:'Daftar di syarikat',method:'Kaedah daftar masuk',select:'Pilih',place:'Lokasi syarikat',radius:'Jejari dibenarkan (m)',save:'Simpan tetapan daftar masuk',saved:'Disimpan',loading:'Memuatkan…',retry:'Muat semula',logout:'Log keluar',busy:'Mendapatkan lokasi dan mendaftar…',help:'GPS diambil sekali apabila butang ditekan untuk merekod masa mula kerja. Tiada penjejakan berterusan.',companyHelp:'Anda mesti berada dalam kawasan daftar masuk syarikat.',setup:'Daftar di syarikat dalam 200 m ialah tetapan lalai. Tetapkan Rumah untuk pekerja yang memerlukannya.',history:'31 rekod terakhir',daily:'Rekod daftar masuk pekerja',date:'Tarikh',time:'Masa daftar masuk',missing:'Belum daftar masuk',empty:'Tiada rekod',gps:'GPS',refresh:'Muat semula',ATTENDANCE_GPS:'Lokasi kurang tepat atau luput. Aktifkan lokasi tepat dan cuba lagi.',ATTENDANCE_OUTSIDE:'Di luar kawasan daftar masuk syarikat. Cuba lagi di syarikat.',ATTENDANCE_LOCATION:'GPS syarikat belum ditetapkan atau lokasi tidak aktif. Hubungi pentadbir.',ATTENDANCE_SETUP:'Minta pentadbir menetapkan kaedah daftar masuk.',ATTENDANCE_STALE:'Tetapan telah berubah. Muat semula sebelum menyimpan.',ATTENDANCE_INVALID:'Semak kaedah dan jejari (20–5000 m).',ATTENDANCE_DENIED:'Tiada kebenaran melihat atau mengubah.',failed:'Tidak berjaya. Sila cuba lagi.'}
}
const approvalWords={
 zh:{request:'申请主管批准',reason:'申请原因',submit:'提交',pending:'等待主管批准',rejected:'申请已被拒绝，请联系主管。',approved:'主管批准补登记',heading:'拿车时间待批准',approve:'批准',reject:'拒绝',hint:'批准后以提交申请的时间记录拿车时间。',ATTENDANCE_REASON:'请填写申请原因（最多1000字）。'},
 en:{request:'Request supervisor approval',reason:'Reason',submit:'Submit',pending:'Awaiting supervisor approval',rejected:'Request rejected. Contact your supervisor.',approved:'Supervisor-approved registration',heading:'Vehicle pickup approval requests',approve:'Approve',reject:'Reject',hint:'After approval, the request submission time is recorded as the vehicle pickup time.',ATTENDANCE_REASON:'Enter a reason (up to 1000 characters).'},
 ms:{request:'Mohon kelulusan penyelia',reason:'Sebab',submit:'Hantar',pending:'Menunggu kelulusan penyelia',rejected:'Permohonan ditolak. Hubungi penyelia.',approved:'Pendaftaran diluluskan penyelia',heading:'Permohonan masa ambil lori',approve:'Luluskan',reject:'Tolak',hint:'Selepas diluluskan, masa permohonan dihantar direkod sebagai masa ambil lori.',ATTENDANCE_REASON:'Masukkan sebab (maksimum 1000 aksara).'}
}
for(const lang of Object.keys(attendanceWords))Object.assign(attendanceWords[lang],approvalWords[lang])
const localTime=value=>value?new Date(value).toLocaleString('en-GB',{timeZone:'Asia/Kuching',hour12:false}):'—'
const gpsOnce=()=>new Promise((resolve,reject)=>{
 if(!navigator.geolocation)return reject({code:'ATTENDANCE_GPS'})
 navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracyM:p.coords.accuracy,deviceCapturedAt:new Date(p.timestamp).toISOString()}),()=>reject({code:'ATTENDANCE_GPS'}),{enableHighAccuracy:true,timeout:20000,maximumAge:0})
})
export function AttendanceGate({account,onLogout,children}){
 const{language}=useI18n(),w=attendanceWords[language]||attendanceWords.en
 const[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[requesting,setRequesting]=useState(false),[reason,setReason]=useState('')
 const enabled=['driver','crew'].includes(account.role)&&!isEmployeePreview()
 useEffect(()=>{if(!enabled)return;let alive=true;const load=()=>apiRequest('/api/mobile/attendance').then(d=>{if(alive){setData(d);setError('')}}).catch(e=>{if(alive){setData(null);setError(e.code||'failed')}})
 load();const timer=setInterval(load,30000),focus=()=>{if(document.visibilityState==='visible')load()};document.addEventListener('visibilitychange',focus);window.addEventListener('focus',load)
 return()=>{alive=false;clearInterval(timer);document.removeEventListener('visibilitychange',focus);window.removeEventListener('focus',load)}
 },[account.employeeId,enabled])
 if(!enabled||data?.configured===false)return children
 if(data?.record)return <><div className="attendance-receipt" role="status">{w.title}: {localTime(data.record.clocked_at)}{data.record.mode==='approved'&&` · ${w.approved}`}</div>{children}</>
 const clock=async()=>{setBusy(true);setError('');try{const gps=await gpsOnce();setData(await apiRequest('/api/mobile/attendance',{method:'POST',body:JSON.stringify(gps)}))}catch(e){setError(e.code||'failed')}finally{setBusy(false)}}
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const gps=await gpsOnce();setData(await apiRequest('/api/mobile/attendance/request',{method:'POST',body:JSON.stringify({...gps,reason})}));setRequesting(false)}catch(e){setError(e.code||'failed')}finally{setBusy(false)}}
 return <main className="attendance-gate"><section className="attendance-panel"><small>KCS</small><h1>{w.title}</h1><p data-i18n-raw>{account.employeeName}</p>{data?<><p>{formatDateDisplay(data.date)}</p><p>{w.help}</p>{data.mode==='company'&&<p>{w.companyHelp}</p>}<button className="attendance-clock" disabled={busy} onClick={clock}>{busy?w.busy:w.title}</button>{data.request?<p role="status">{data.request.status==='pending'?w.pending:data.request.status==='rejected'?w.rejected:w.approved} · {localTime(data.request.requested_at)}</p>:<><button disabled={busy} onClick={()=>setRequesting(v=>!v)}>{w.request}</button>{requesting&&<form onSubmit={submit}><p>{w.hint}</p><label>{w.reason}<textarea required maxLength={1000} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()}>{busy?w.busy:w.submit}</button></form>}</>}</>:!error?<p>{w.loading}</p>:null}{error&&<CenteredNotice>{w[error]||w.failed}</CenteredNotice>}{!data&&error&&<button onClick={async()=>{setError('');try{setData(await apiRequest('/api/mobile/attendance'))}catch(e){setError(e.code||'failed')}}}>{w.retry}</button>}<button disabled={busy} onClick={onLogout}>{w.logout}</button></section></main>
}
export function AttendanceSettings({employeeId,blocked=false,stage}){
 const{language}=useI18n(),w=attendanceWords[language]||attendanceWords.en,[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false)
 const load=()=>apiRequest(`/api/attendance/employees/${employeeId}`).then(d=>{setData(d);setError('')}).catch(e=>setError(e.code||'failed'))
 useEffect(()=>{setData(null);load()},[employeeId])
 const change=p=>{const next={...data,...p};setData(next);setSaved(false);if(stage)stage(async()=>{const result=await apiRequest(`/api/attendance/employees/${employeeId}`,{method:'PATCH',body:JSON.stringify({mode:next.mode,locationId:next.locations.length===1?next.locations[0].id:next.locationId,radiusM:Number(next.radiusM),revision:next.revision})});setData(result);setSaved(true)})}
 const save=async()=>{setBusy(true);setError('');setSaved(false);try{setData(await apiRequest(`/api/attendance/employees/${employeeId}`,{method:'PATCH',body:JSON.stringify({mode:data.mode,locationId:data.locations.length===1?data.locations[0].id:data.locationId,radiusM:Number(data.radiusM),revision:data.revision})}));setSaved(true)}catch(e){setError(e.code||'failed')}finally{setBusy(false)}}
 return <details className="attendance-panel" open><summary>{w.method}</summary><p>{w.setup}</p>{data&&<><fieldset disabled={busy||blocked}><label>{w.method}<select value={data.mode} onChange={e=>change({mode:e.target.value})}><option value="" disabled>{w.select}</option><option value="home">{w.home}</option><option value="company">{w.company}</option></select></label>{data.mode==='company'&&<><label>{w.place}{data.locations.length===1?<span data-i18n-raw>{data.locations[0].name}</span>:<select value={data.locationId||''} onChange={e=>change({locationId:Number(e.target.value)})}><option value="">{w.select}</option>{data.locations.map(l=><option key={l.id} value={l.id} data-i18n-raw>{l.name}</option>)}</select>}</label><label>{w.radius}<input type="number" min="20" max="5000" step="1" value={data.radiusM} onChange={e=>change({radiusM:e.target.value})}/></label></>}{!stage&&<button type="button" disabled={!data.mode} onClick={save}>{w.save}</button>}</fieldset><details><summary>{w.history}</summary>{data.records.length?data.records.map(r=><article key={r.id}><b>{localTime(r.clocked_at)}</b> · {w[r.mode]}<p>{w.gps}: <span data-i18n-raw>{r.latitude}, {r.longitude} (±{r.accuracy_m} m)</span></p></article>):<p>{w.empty}</p>}</details></>}{saved&&<p role="status">{w.saved}</p>}{error&&<><CenteredNotice>{w[error]||w.failed}</CenteredNotice><button type="button" onClick={load}>{w.retry}</button></>}</details>
}
export function AttendanceDaily(){
 const{language}=useI18n(),w=attendanceWords[language]||attendanceWords.en,[data,setData]=useState(null),[error,setError]=useState(''),requestVersion=useRef(0)
 const scrollRef=useRef(null),labels=({zh:{name:'员工',accuracy:'定位误差（米）'},en:{name:'Employee',accuracy:'Accuracy (m)'},ms:{name:'Pekerja',accuracy:'Ketepatan (m)'}})[language]||{name:'Employee',accuracy:'Accuracy (m)'}
 const [filters,setFilters]=useState(()=>({work_date:[kuchingDate()]})),[sort,setSort]=useState({}),[menu,setMenu]=useState(null)
 const [target,setTarget]=useState(null)
 useEffect(()=>setTarget(document.getElementById('page-data-exports')),[])
 const clock=value=>value?new Date(value).toLocaleTimeString('en-GB',{timeZone:'Asia/Kuching',hour12:false}):w.missing
 const columns=[['work_date',w.date],['name',labels.name],['mode',w.method],['clocked_at',w.time],['gps',w.gps],['accuracy_m',labels.accuracy]]
 const value=(r,k)=>k==='work_date'?r.work_date:k==='mode'?w[r.mode]||'—':k==='clocked_at'?clock(r.clocked_at):k==='gps'?r.clocked_at?r.latitude+', '+r.longitude:'—':k==='accuracy_m'?r.clocked_at&&r.accuracy_m!=null?Number(r.accuracy_m).toFixed(2):'—':String(r[k]??'')
 const items=data?.items||[],visible=items.filter(r=>Object.entries(filters).every(([k,v])=>v==null||v.includes(value(r,k))))
 if(sort.key)visible.sort((a,b)=>{const k=sort.key,n=k==='clocked_at'?clock(a.clocked_at).localeCompare(clock(b.clocked_at)):k==='accuracy_m'?(a.clocked_at?Number(a.accuracy_m)||0:-1)-(b.clocked_at?Number(b.accuracy_m)||0:-1):value(a,k).localeCompare(value(b,k),undefined,{numeric:true});return n*(sort.direction==='desc'?-1:1)})
 const load=()=>{const version=++requestVersion.current;setData(null);setError('');return apiRequest('/api/attendance?date=all').then(d=>{if(version===requestVersion.current)setData(d)}).catch(e=>{if(version===requestVersion.current)setError(e.code||'failed')})}
 useEffect(()=>{load();return()=>{requestVersion.current++}},[])
 return <section className="page attendance-archive">{target&&createPortal(<button className="attendance-refresh" onClick={load} title={w.refresh} aria-label={w.refresh}>↻</button>,target)}{error&&<CenteredNotice onClose={()=>setError('')}>{w[error]||w.failed}</CenteredNotice>}<DataExportButton name={w.daily} rows={visible} columns={columns.map(([key,label])=>({key,label,value:r=>key==='work_date'?formatDateDisplay(r.work_date):key==='accuracy_m'&&r.clocked_at&&r.accuracy_m!=null?Number(r.accuracy_m):value(r,key)}))}/><div className="attendance-table-scroll" ref={scrollRef}><table className="attendance-table"><thead><tr>{columns.map(([key,label])=><FilterHeader key={key} label={label} numeric={key==='accuracy_m'} value={filters[key]??null} options={[...new Set(items.map(r=>value(r,key)))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map(v=>({value:v,label:key==='work_date'?formatDateDisplay(v):v||'—'}))} onChange={v=>setFilters(f=>({...f,[key]:v}))} open={menu===key} onOpen={()=>setMenu(key)} onClose={()=>setMenu(null)} sortDirection={sort.key===key?sort.direction:null} onSort={direction=>setSort(direction?{key,direction}:{})}/>)}</tr></thead><tbody>{visible.map(r=><tr key={r.employeeId+'-'+r.work_date}><td>{formatDateDisplay(r.work_date)}</td><td data-i18n-raw>{r.name}</td><td>{w[r.mode]||'—'}</td><td className={r.clocked_at&&clock(r.clocked_at)>'08:00:00'?'attendance-late':undefined}>{clock(r.clocked_at)}</td><td data-i18n-raw>{r.clocked_at?r.latitude+', '+r.longitude:'—'}</td><td data-numeric>{r.clocked_at&&r.accuracy_m!=null?Number(r.accuracy_m).toFixed(2):'—'}</td></tr>)}</tbody></table></div><TableBottomScroll scrollRef={scrollRef}/>{data&&!visible.length&&<p>{w.empty}</p>}</section>
}

export function AttendanceApprovals({account}){
 const{language}=useI18n(),w=attendanceWords[language]||attendanceWords.en,[items,setItems]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const allowed=['owner_admin','operations_admin','supervisor'].includes(account?.role)
 useEffect(()=>{if(!allowed)return;let alive=true;const load=()=>apiRequest('/api/attendance/requests').then(r=>{if(alive)setItems(r.items)}).catch(e=>{if(alive)setError(e.code||'failed')});load();const timer=setInterval(load,30000);return()=>{alive=false;clearInterval(timer)}},[allowed,account?.id])
 const decide=async(id,decision)=>{setBusy(true);setError('');try{await apiRequest(`/api/attendance/requests/${id}`,{method:'POST',body:JSON.stringify({decision})});setItems((await apiRequest('/api/attendance/requests')).items)}catch(e){setError(e.code||'failed')}finally{setBusy(false)}}
 if(!allowed||(!items.length&&!error))return null
 return <section className="attendance-panel"><h2>{w.heading}</h2>{items.map(r=>{const gps=JSON.parse(r.gps_json),self=r.account_id===account.id||r.employee_id===account.employeeId;return <article key={r.id}><b data-i18n-raw>{r.name}</b><p>{w.title}: {localTime(r.requested_at)}</p><p data-i18n-raw>{r.reason}</p><p>{w.gps}: {gps.latitude}, {gps.longitude} (±{gps.accuracyM} m)</p><button disabled={busy||self} onClick={()=>decide(r.id,'approved')}>{w.approve}</button><button disabled={busy||self} onClick={()=>decide(r.id,'rejected')}>{w.reject}</button></article>})}{error&&<CenteredNotice onClose={()=>setError('')}>{w[error]||w.failed}</CenteredNotice>}</section>
}
