import {useCallback,useEffect,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest as api} from './apiClient.js'
import ProofPhotoPicker from './ProofPhotoPicker.jsx'
import {proofData} from './paymentProofImage.js'
import './BillVoidPage.css'

const money=n=>`RM ${(Number(n)/100).toFixed(2)}`
export default function BillVoidPage({mobile=false,onBack}){
 const {t}=useI18n(),[data,setData]=useState(null),[search,setSearch]=useState(''),[filter,setFilter]=useState(mobile?'all':'pending'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(()=>api(`/api/bill-voids${mobile?'?scope=own':''}`).then(setData),[mobile])
 useEffect(()=>{load().catch(e=>setError(e.message))},[load])
 const run=async(fn)=>{setBusy(true);setError('');setNotice('');try{await fn();await load();setNotice(t('void.saved'))}catch(e){setError(e.message)}finally{setBusy(false)}}
 const items=(data?.items||[]).filter(b=>(filter==='all'||b.requests.some(r=>r.status===filter))&&[b.bill_number,b.customer_name_snapshot,b.branch_name_snapshot,b.branch_code_snapshot,b.driver_name_snapshot].some(s=>String(s||'').toLowerCase().includes(search.toLowerCase())))
 return <section className="bill-void-page"><div className="bill-void-toolbar">{onBack&&<button onClick={onBack}>←</button>}<h1>{t('void.title')}</h1><button disabled={busy} onClick={()=>run(async()=>{})}>{t('void.refresh')}</button></div><p>{t('void.help')}</p><label>{t('void.search')}<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>{t('void.filter')}<select value={filter} onChange={e=>setFilter(e.target.value)}>{['all','pending','approved','rejected'].map(s=><option key={s} value={s}>{t('void.'+s)}</option>)}</select></label>{error&&<p role="alert" className="auth-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{!data&&<p>{t('void.loading')}</p>}{data&&!items.length&&<p>{t('void.empty')}</p>}{items.map(b=><BillCard key={b.id} bill={b} canReview={data.canReview&&!mobile} run={run} busy={busy}/>)}</section>
}
function BillCard({bill:b,canReview,run,busy}){
 const {t}=useI18n(),[reason,setReason]=useState(''),[note,setNote]=useState(''),[reissue,setReissue]=useState(false)
 const latest=b.requests[0]
 return <article className="bill-void-card"><h2 data-i18n-raw>{b.bill_number}</h2><p data-i18n-raw>{b.service_date} · {b.customer_name_snapshot} · {b.branch_code_snapshot} — {b.branch_name_snapshot}</p><p data-i18n-raw>{b.driver_name_snapshot} · {b.registration_number_snapshot||b.vehicle_code_snapshot}</p><strong>{money(b.total_cents)} · {t('void.'+b.payment_method)} · {t('void.'+b.status)}</strong><details><summary>{t('void.items')}</summary>{b.items.map((i,n)=><p key={n} data-i18n-raw>{i.product_name_snapshot} · {i.quantity} {i.unit_snapshot} · {money(i.line_total_cents)}</p>)}</details>{b.proofId&&<a href={`/api/purchase-payment-proofs/${b.proofId}/photo`} target="_blank" rel="noreferrer">{t('void.proof')}</a>}
 {b.requests.map(r=><div className="bill-void-history" key={r.id}><b>{t('void.'+r.status)}</b><p data-i18n-raw>{r.requested_name} · {r.requested_at}</p><p>{r.reason}</p>{r.reviewed_at&&<p data-i18n-raw>{r.reviewed_name} · {r.reviewed_at}</p>}{r.review_note&&<p>{r.review_note}</p>}{r.status==='approved'&&<p>{t(r.reversal_transaction_id?'void.reversed':'void.noDeduction')}</p>}{r.replacement_bill_id&&<p>{t('void.replacementLinked',{id:r.replacement_bill_id})}</p>}</div>)}
 {b.canRequest&&<form onSubmit={e=>{e.preventDefault();run(async()=>{await api(`/api/bill-voids/${b.id}/request`,{method:'POST',body:JSON.stringify({reason})});setReason('')})}}><label>{t('void.reason')}<textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()}>{t('void.request')}</button></form>}
 {canReview&&latest?.status==='pending'&&<div><label>{t('void.reviewNote')}<textarea maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="bill-void-toolbar"><button disabled={busy} onClick={()=>{if(window.confirm(t('void.confirm',{number:b.bill_number,amount:money(b.total_cents)})))run(()=>api(`/api/bill-voids/${latest.id}/approve`,{method:'POST',body:JSON.stringify({note})}))}}>{t('void.approve')}</button><button disabled={busy||!note.trim()} onClick={()=>run(()=>api(`/api/bill-voids/${latest.id}/reject`,{method:'POST',body:JSON.stringify({note})}))}>{t('void.reject')}</button></div></div>}
 {(b.canReissue||reissue||b.canViewReplacement)&&<><button disabled={busy} onClick={()=>setReissue(!reissue)}>{t('void.reissue')}</button>{reissue&&<ReplacementForm billId={b.id} onDone={()=>run(async()=>{})}/>}</>}
 </article>
}
function ReplacementForm({billId,onDone}){
 const {t}=useI18n(),[data,setData]=useState(null),[items,setItems]=useState([{productId:'',quantity:''}]),[weightMethod,setWeight]=useState('on_site'),[printChoice,setPrint]=useState('no_print'),[photo,setPhoto]=useState(null),[processing,setProcessing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{api(`/api/bill-voids/${billId}/replacement`).then(setData).catch(e=>setError(e.message))},[billId])
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const bill=data.bill||await api(`/api/bill-voids/${billId}/replacement`,{method:'POST',body:JSON.stringify({items,weightMethod,printChoice})});setData(d=>({...d,bill}));if(bill.paymentMethod==='Cash'&&!bill.paymentProofUploaded){await api(`/api/bill-voids/${billId}/replacement-proof`,{method:'POST',body:JSON.stringify({photo:await proofData(photo)})});setData(d=>({...d,bill:{...bill,paymentProofUploaded:true}}));setPhoto(null)}await onDone()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const needsProof=data&&(data.bill?data.bill.paymentMethod==='Cash'&&!data.bill.paymentProofUploaded:data.stop.paymentMethod==='Cash')
 return <form onSubmit={submit}>{error&&<p role="alert" className="auth-error">{error}</p>}{data&&<><p>{t('void.reissueHelp')}</p>{data.bill?<><div className="purchase-receipt"><h2>LEE SAI KER ENTERPRISE</h2><p data-i18n-raw>{data.bill.billNumber} · {data.bill.serviceDate}</p><p data-i18n-raw>{data.bill.branchName} · {data.bill.registrationNumber||data.bill.vehicleCode}</p>{data.bill.items.map((i,n)=><p key={n} data-i18n-raw>{i.quantity} {i.unit} · {i.shortForm||i.productName} · {money(i.lineTotalCents)}</p>)}<b>{t('void.total')}: {money(data.bill.totalCents)}</b><p>{t('void.'+data.bill.paymentMethod)}</p></div><button type="button" onClick={e=>{document.querySelectorAll('.purchase-receipt').forEach(n=>n.classList.toggle('void-print-selected',n===e.currentTarget.previousElementSibling));document.body.classList.add('void-printing');try{window.print()}finally{document.body.classList.remove('void-printing')}}}>{t('void.print')}</button></>:<><label>{t('void.weight')}<select value={weightMethod} onChange={e=>setWeight(e.target.value)}>{['on_site','factory','estimated'].map(s=><option key={s} value={s}>{t('void.'+s)}</option>)}</select></label><label>{t('void.print')}<select value={printChoice} onChange={e=>setPrint(e.target.value)}>{['print','no_print'].map(s=><option key={s} value={s}>{t('void.'+s)}</option>)}</select></label>{items.map((item,index)=><div className="bill-void-item" key={index}><label>{t('void.product')}<select required value={item.productId} onChange={e=>setItems(a=>a.map((x,n)=>n===index?{...x,productId:e.target.value}:x))}><option value="">{t('void.select')}</option>{data.products.map(p=><option key={p.productId} value={p.productId}>{p.fullName} · RM {Number(p.currentPrice).toFixed(2)} / {p.unit}</option>)}</select></label><label>{t('void.quantity')}<input required type="number" min="0.001" max="1000000" step="any" value={item.quantity} onChange={e=>setItems(a=>a.map((x,n)=>n===index?{...x,quantity:e.target.value}:x))}/></label>{items.length>1&&<button type="button" onClick={()=>setItems(a=>a.filter((_,n)=>n!==index))}>{t('void.remove')}</button>}</div>)}<button type="button" disabled={items.length>=20} onClick={()=>setItems(a=>[...a,{productId:'',quantity:''}])}>{t('void.addItem')}</button><p>{t('void.total')}: {money(items.reduce((sum,i)=>sum+Math.round(Number(i.quantity||0)*Math.round(Number(data.products.find(p=>String(p.productId)===String(i.productId))?.currentPrice||0)*100)),0))}</p></>}{needsProof&&<><p>{t('void.newProof')}</p><ProofPhotoPicker value={photo} onChange={setPhoto} onBusyChange={setProcessing} disabled={busy}/></>}{(!data.bill||needsProof)&&<button disabled={busy||processing||needsProof&&!photo}>{t(data.bill?'void.saveProof':'void.createNew')}</button>}{data.bill&&!needsProof&&<p>{t('void.saved')}</p>}</>}</form>
}
