import {useCallback,useEffect,useMemo,useState} from 'react'
import {apiRequest as api} from './apiClient.js'
import {formatBranchId,formatCustomerId} from '../shared/typedIds.js'
import {useI18n} from './i18n.jsx'
import CompactDataTable,{CopyValue} from './CompactDataTable.jsx'
import './MasterDataPage.css'

const statuses=['TEMPORARILY_PAUSED','CLOSED','DUPLICATE_REPLACED','NOT_COLLECTING','TEST_INVALID']

export default function BranchLifecycleReviewPage({initialBranchId='',onOpenBranch,currentUser={}}){
  const{t}=useI18n(),[search,setSearch]=useState(initialBranchId?formatBranchId(initialBranchId):''),[status,setStatus]=useState(''),[replacement,setReplacement]=useState(''),[data,setData]=useState({items:[],counts:{}}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false)
  const load=useCallback(async()=>{setLoading(true);setError('');try{const query=new URLSearchParams({search,status,replacement});setData(await api(`/api/branch-lifecycle-review?${query}`))}catch(item){setError(item.message)}finally{setLoading(false)}},[search,status,replacement])
  useEffect(()=>{const timer=setTimeout(()=>void load(),180);return()=>clearTimeout(timer)},[load])
  const restore=async()=>{setBusy(true);setError('');try{await api(`/api/branches/${editing.branchId}/lifecycle`,{method:'PATCH',body:JSON.stringify({lifecycleStatus:'ACTIVE',reason})});setEditing(null);setReason('');await load()}catch(item){setError(item.message)}finally{setBusy(false)}}
  const labels=useMemo(()=>({selected:t('list.selected'),selectAll:t('list.selectAll'),selectRow:t('list.selectRow'),sortAsc:t('list.sortAsc'),sortDesc:t('list.sortDesc'),clearSort:t('list.clearSort'),clearFilter:t('list.clearFilter'),actions:t('list.actions'),details:t('list.details'),expand:t('list.expand'),collapse:t('list.collapse'),columns:t('list.columns'),closeColumns:t('list.closeColumns'),resetColumns:t('list.resetColumns')}),[t])
  const columns=useMemo(()=>[
    {key:'branchId',label:t('list.branchId'),value:item=>formatBranchId(item.branchId)},
    {key:'branchName',label:t('list.branchName'),required:true,render:item=><button type="button" className="entity-name-link" onClick={event=>{event.stopPropagation();onOpenBranch?.(item.branchId)}} data-i18n-raw>{item.branchName}</button>},
    {key:'customerName',label:t('list.customer'),render:item=><span className="compact-related-id" data-i18n-raw>{formatCustomerId(item.customerId)} — {item.customerName}</span>},
    {key:'area',label:t('list.area'),filterable:true,secondary:true},
    {key:'lifecycleStatus',label:t('list.lifecycleStatus'),filterable:true,render:item=><span className={`lifecycle-badge ${item.lifecycleStatus.toLowerCase()}`}>{t(`branchLifecycle.status.${item.lifecycleStatus}`)}</span>},
    {key:'statusReason',label:t('branchLifecycle.reason'),secondary:true},
    {key:'statusChangedAt',label:t('branchLifecycle.changedAt'),secondary:true},
    {key:'statusChangedBy',label:t('branchLifecycle.changedBy'),secondary:true},
    {key:'lastCollectionDate',label:t('branchLifecycle.lastCollection'),secondary:true},
  ],[t,onOpenBranch])
  const details=item=><dl className="compact-detail-grid"><div><dt>{t('list.branchId')}</dt><dd><CopyValue value={formatBranchId(item.branchId)} label={t('list.copy')} copiedLabel={t('list.copied')}/></dd></div><div><dt>{t('list.customerId')}</dt><dd><CopyValue value={formatCustomerId(item.customerId)} label={t('list.copy')} copiedLabel={t('list.copied')}/></dd></div><div><dt>{t('list.address')}</dt><dd data-i18n-raw>{item.address||t('master.notSetAddress')}</dd></div><div><dt>{t('branchLifecycle.reason')}</dt><dd data-i18n-raw>{item.statusReason||'—'}</dd></div><div><dt>{t('branchLifecycle.changedAt')}</dt><dd>{item.statusChangedAt||'—'}</dd></div><div><dt>{t('branchLifecycle.changedBy')}</dt><dd data-i18n-raw>{item.statusChangedBy||'—'}</dd></div><div><dt>{t('branchLifecycle.lastCollection')}</dt><dd>{item.lastCollectionDate||t('branchLifecycle.noCollection')}</dd></div>{item.replacedByBranchId&&<div><dt>{t('branchLifecycle.replacedBy')}</dt><dd data-i18n-raw>{formatBranchId(item.replacedByBranchId)} — {item.replacedByBranchName}</dd></div>}</dl>
  return <section className="master-workspace branch-review"><header><div><h2>{t('branchLifecycle.reviewTitle')}</h2><p>{t('branchLifecycle.reviewHelp')}</p></div></header>{error&&<div className="data-error" role="alert">{error}</div>}<div className="lifecycle-summary">{statuses.map(item=><button key={item} className={status===item?'active':''} onClick={()=>setStatus(status===item?'':item)}><b>{data.counts[item]||0}</b><span>{t(`branchLifecycle.status.${item}`)}</span></button>)}</div><div className="master-filters"><input aria-label={t('common.search')} placeholder={t('branchLifecycle.search')} value={search} onChange={event=>setSearch(event.target.value)}/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">{t('branchLifecycle.allInactive')}</option>{statuses.map(item=><option key={item} value={item}>{t(`branchLifecycle.status.${item}`)}</option>)}</select><select value={replacement} onChange={event=>setReplacement(event.target.value)}><option value="">{t('common.all')}</option><option value="with">{t('branchLifecycle.withReplacement')}</option><option value="without">{t('branchLifecycle.withoutReplacement')}</option></select></div>{loading?<div className="data-loading">{t('common.loadingData')}</div>:<CompactDataTable items={data.items} rowKey={item=>item.internalId} columns={columns} labels={labels} preferenceKey={`${currentUser.preferenceId||currentUser.name||'anonymous'}.branch-review`} emptyLabel={t('branchLifecycle.empty')} renderDetails={details} renderActions={item=><button type="button" onClick={()=>{setEditing(item);setReason('')}}>{t('branchLifecycle.restoreActive')}</button>}/>} {editing&&<div className="master-modal"><section className="restore-dialog" role="dialog" aria-modal="true"><h3>{t('branchLifecycle.restoreActive')}</h3><p data-i18n-raw>{formatBranchId(editing.branchId)} — {editing.branchName}</p><label>{t('branchLifecycle.restoreReason')}<textarea value={reason} onChange={event=>setReason(event.target.value)}/></label><footer><button onClick={()=>setEditing(null)}>{t('common.cancel')}</button><button className="primary" disabled={busy||!reason.trim()} onClick={restore}>{busy?t('common.saving'):t('common.confirm')}</button></footer></section></div>}</section>
}
