import {useCallback,useEffect,useMemo,useState} from 'react'
import {apiRequest as api} from './apiClient.js'
import {formatBranchId,formatCustomerId} from '../shared/typedIds.js'
import {useI18n} from './i18n.jsx'
import CompactDataTable,{CopyValue} from './CompactDataTable.jsx'
import './MasterDataPage.css'
import FormActionBar from './FormActionBar.jsx'

const statuses=['TEMPORARILY_PAUSED','CLOSED','DUPLICATE_REPLACED','NOT_COLLECTING','TEST_INVALID']
const emptyChange={status:'',reason:'',replacementId:'',replacementSearch:'',replacementItems:[]}

export default function BranchLifecycleReviewPage({initialBranchId='',onOpenBranch,currentUser={}}){
  const{t}=useI18n(),[search,setSearch]=useState(initialBranchId?formatBranchId(initialBranchId):''),[status,setStatus]=useState(''),[replacement,setReplacement]=useState(''),[data,setData]=useState({items:[],counts:{}}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[restoring,setRestoring]=useState(null),[changing,setChanging]=useState(null),[reason,setReason]=useState(''),[change,setChange]=useState(emptyChange),[busy,setBusy]=useState(false)
  const load=useCallback(async()=>{setLoading(true);setError('');try{const query=new URLSearchParams({search,status,replacement});setData(await api(`/api/branch-lifecycle-review?${query}`))}catch(item){setError(item.message)}finally{setLoading(false)}},[search,status,replacement])
  useEffect(()=>{const timer=setTimeout(()=>void load(),180);return()=>clearTimeout(timer)},[load])
  const patchLifecycle=async(branch,payload)=>api(`/api/master/branches/${encodeURIComponent(branch.branchId)}/lifecycle`,{method:'PATCH',body:JSON.stringify(payload)})
  const restore=async()=>{setBusy(true);setError('');try{await patchLifecycle(restoring,{lifecycleStatus:'ACTIVE',reason});setRestoring(null);setReason('');await load()}catch(item){setError(item.message)}finally{setBusy(false)}}
  const openChange=item=>{setChanging(item);setChange({...emptyChange,status:statuses.find(value=>value!==item.lifecycleStatus)||''})}
  const searchReplacements=async value=>{setChange(current=>({...current,replacementSearch:value}));if(value.trim().length<2){setChange(current=>({...current,replacementItems:[]}));return}try{const result=await api(`/api/branch-lifecycle-replacements?search=${encodeURIComponent(value)}`);setChange(current=>({...current,replacementItems:(result.items||[]).filter(item=>item.internalId!==changing.internalId)}))}catch(item){setError(item.message)}}
  const submitChange=async()=>{setBusy(true);setError('');try{await patchLifecycle(changing,{lifecycleStatus:change.status,reason:change.reason,replacedByBranchId:change.replacementId});setChanging(null);setChange(emptyChange);await load()}catch(item){setError(item.message)}finally{setBusy(false)}}
  const labels=useMemo(()=>({selected:t('list.selected'),selectAll:t('list.selectAll'),selectRow:t('list.selectRow'),sortAsc:t('list.sortAsc'),sortDesc:t('list.sortDesc'),clearSort:t('list.clearSort'),clearFilter:t('list.clearFilter'),actions:t('list.actions'),details:t('list.details'),expand:t('list.expand'),collapse:t('list.collapse'),columns:t('list.columns'),closeColumns:t('list.closeColumns'),resetColumns:t('list.resetColumns')}),[t])
  const columns=useMemo(()=>[
    {key:'branchId',label:t('list.branchId'),value:item=>formatBranchId(item.branchId)},
    {key:'branchName',label:t('list.branchName'),required:true,render:item=><button type="button" className="entity-name-link" onClick={event=>{event.stopPropagation();onOpenBranch?.(item.branchId)}} data-i18n-raw>{item.branchName}</button>},
    {key:'customerName',label:t('list.customer'),render:item=><span className="compact-related-id" data-i18n-raw>{formatCustomerId(item.customerId)} — {item.customerName}</span>},
    {key:'area',label:t('list.area'),filterable:true,secondary:true},
    {key:'lifecycleStatus',label:t('list.lifecycleStatus'),filterable:true,render:item=><span className={`lifecycle-badge ${item.lifecycleStatus.toLowerCase()}`}>{t(`branchLifecycle.status.${item.lifecycleStatus}`)}</span>},
    {key:'statusReason',label:t('branchLifecycle.reason'),secondary:true},{key:'statusChangedAt',label:t('branchLifecycle.changedAt'),secondary:true},{key:'statusChangedBy',label:t('branchLifecycle.changedBy'),secondary:true},{key:'lastCollectionDate',label:t('branchLifecycle.lastCollection'),secondary:true},
  ],[t,onOpenBranch])
  const details=item=><dl className="compact-detail-grid"><div><dt>{t('list.branchId')}</dt><dd><CopyValue value={formatBranchId(item.branchId)} label={t('list.copy')} copiedLabel={t('list.copied')}/></dd></div><div><dt>{t('list.customerId')}</dt><dd><CopyValue value={formatCustomerId(item.customerId)} label={t('list.copy')} copiedLabel={t('list.copied')}/></dd></div><div><dt>{t('list.address')}</dt><dd data-i18n-raw>{item.address||t('master.notSetAddress')}</dd></div><div><dt>{t('branchLifecycle.reason')}</dt><dd data-i18n-raw>{item.statusReason||'—'}</dd></div><div><dt>{t('branchLifecycle.changedAt')}</dt><dd>{item.statusChangedAt||'—'}</dd></div><div><dt>{t('branchLifecycle.changedBy')}</dt><dd data-i18n-raw>{item.statusChangedBy||'—'}</dd></div><div><dt>{t('branchLifecycle.lastCollection')}</dt><dd>{item.lastCollectionDate||t('branchLifecycle.noCollection')}</dd></div>{item.replacedByBranchId&&<div><dt>{t('branchLifecycle.replacedBy')}</dt><dd data-i18n-raw>{formatBranchId(item.replacedByBranchId)} — {item.replacedByBranchName}</dd></div>}</dl>
  const actionButtons=item=><div className="lifecycle-row-actions"><button type="button" onClick={()=>openChange(item)}>{t('branchLifecycle.changeStatus')}</button><button type="button" onClick={()=>{setRestoring(item);setReason('')}}>{t('branchLifecycle.restoreActive')}</button></div>
  const changeValid=change.status&&change.status!==changing?.lifecycleStatus&&change.reason.trim()&&(change.status!=='DUPLICATE_REPLACED'||change.replacementId)
  return <section className="master-workspace branch-review"><header><div><h2>{t('branchLifecycle.reviewTitle')}</h2><p>{t('branchLifecycle.reviewHelp')}</p></div></header>{error&&<div className="data-error" role="alert">{error}</div>}<div className="lifecycle-summary">{statuses.map(item=><button key={item} className={status===item?'active':''} onClick={()=>setStatus(status===item?'':item)}><b>{data.counts[item]||0}</b><span>{t(`branchLifecycle.status.${item}`)}</span></button>)}</div><div className="master-filters"><input aria-label={t('common.search')} placeholder={t('branchLifecycle.search')} value={search} onChange={event=>setSearch(event.target.value)}/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">{t('branchLifecycle.allInactive')}</option>{statuses.map(item=><option key={item} value={item}>{t(`branchLifecycle.status.${item}`)}</option>)}</select><select value={replacement} onChange={event=>setReplacement(event.target.value)}><option value="">{t('common.all')}</option><option value="with">{t('branchLifecycle.withReplacement')}</option><option value="without">{t('branchLifecycle.withoutReplacement')}</option></select></div>{loading?<div className="data-loading">{t('common.loadingData')}</div>:<CompactDataTable items={data.items} rowKey={item=>item.internalId} columns={columns} labels={labels} preferenceKey={`${currentUser.preferenceId||currentUser.name||'anonymous'}.branch-review`} emptyLabel={t('branchLifecycle.empty')} renderDetails={details} renderActions={actionButtons}/>}
  {restoring&&<div className="master-modal"><section className="restore-dialog" role="dialog" aria-modal="true"><h3>{t('branchLifecycle.restoreActive')}</h3><p data-i18n-raw>{formatBranchId(restoring.branchId)} — {restoring.branchName}</p><label>{t('branchLifecycle.restoreReason')}<textarea required value={reason} onChange={event=>setReason(event.target.value)}/></label><FormActionBar><button onClick={()=>setRestoring(null)}>{t('common.cancel')}</button><button className="primary" disabled={busy||!reason.trim()} onClick={restore}>{busy?t('common.saving'):t('common.confirm')}</button></FormActionBar></section></div>}
  {changing&&<div className="master-modal"><section className="lifecycle-change-dialog" role="dialog" aria-modal="true" aria-labelledby="change-lifecycle-title"><h3 id="change-lifecycle-title">{t('branchLifecycle.changeStatus')}</h3><dl><div><dt>{t('list.branchId')}</dt><dd>{formatBranchId(changing.branchId)}</dd></div><div><dt>{t('list.branchName')}</dt><dd data-i18n-raw>{changing.branchName}</dd></div><div><dt>{t('branchLifecycle.currentStatus')}</dt><dd>{t(`branchLifecycle.status.${changing.lifecycleStatus}`)}</dd></div></dl><label>{t('branchLifecycle.newStatus')}<select value={change.status} onChange={event=>setChange(current=>({...current,status:event.target.value,replacementId:''}))}>{statuses.filter(value=>value!==changing.lifecycleStatus).map(value=><option key={value} value={value}>{t(`branchLifecycle.status.${value}`)}</option>)}</select></label>{change.status==='DUPLICATE_REPLACED'&&<><label>{t('branchLifecycle.replacementSearch')}<input value={change.replacementSearch} onChange={event=>void searchReplacements(event.target.value)}/></label><label>{t('branchLifecycle.replacedBy')}<select required value={change.replacementId} onChange={event=>setChange(current=>({...current,replacementId:event.target.value}))}><option value="">{t('common.select')}</option>{change.replacementItems.map(item=><option key={item.internalId} value={item.internalId}>{formatBranchId(item.branchId)} — {item.branchName}</option>)}</select></label></>}<label>{t('branchLifecycle.reason')}<textarea required value={change.reason} onChange={event=>setChange(current=>({...current,reason:event.target.value}))}/></label>{changing.futureStops>0&&<div className="lifecycle-impact-warning" role="alert"><b>{t('common.warning')}</b><span>{t('branchLifecycle.stopWarning',{stops:changing.futureStops,dispatches:changing.futureDispatches})}</span></div>}<p className="lifecycle-preservation-note">{t('branchLifecycle.preserveHistory')}</p><FormActionBar><button onClick={()=>setChanging(null)}>{t('common.cancel')}</button><button className="primary" disabled={busy||!changeValid} onClick={submitChange}>{busy?t('common.saving'):t('common.confirm')}</button></FormActionBar></section></div>}</section>
}
