import {useEffect,useState} from 'react'
import {apiRequest,isEmployeePreview} from './apiClient.js'
import {useI18n} from './i18n.jsx'
import './CargoBatches.css'
export const cargoWords={
 zh:{title:'货物批次',help:'司机把批次号交给本批收货的 attendant，双方保留同号记录。',new:'新的货物批次号',share:'请把号码交给下一批收货的 attendant。开始收货后，attendant 再输入号码确认参与。',read:'知道了',start:'开始本批收货',code:'输入批次号',lookup:'核对号码',join:'确认参与本批收货',refresh:'刷新',empty:'暂无货物批次记录。',prepared:'待开始',active:'收货中／待卸货',closed:'已卸完',driver:'司机',crew:'Attendant',members:'已确认人员',history:'我的批次记录',date:'收货日期',ticket:'工厂下货单号码',batch:'本张下货单所属批次',mode:'卸货情况',full:'全部卸完，生成下一批号码',partial:'只卸一部分，沿用原号',supplement:'补交已卸完批次的单据',select:'请选择',saved:'已保存',loading:'加载中…',failed:'操作未完成，请刷新后重试。',CARGO_JOIN:'只可加入今天开始且派车名单有你的收货批次。请主管先核对人员安排。',CARGO_NOT_FOUND:'找不到你可查看的批次，请检查号码及派车安排。',CARGO_STATE:'批次状态已改变，请刷新并重新选择。',CARGO_TRIP:'请先开始当天分配给你的趟次。',CARGO_DUPLICATE:'该批次已有这个下货单号码，请勿重复提交。',CARGO_TICKET:'请选择卸货情况并填写下货单号码。',CARGO_DENIED:'你没有执行此操作的权限。'},
 en:{title:'Cargo batches',help:'Share the batch code with the attendant collecting this load. Both retain the same code.',new:'New cargo batch code',share:'Share this code with the attendant for the next load. Start collection before the attendant confirms participation.',read:'Got it',start:'Start this load',code:'Enter batch code',lookup:'Check code',join:'Confirm participation in this load',refresh:'Refresh',empty:'No cargo batches yet.',prepared:'Ready to start',active:'Collecting / awaiting unloading',closed:'Fully unloaded',driver:'Driver',crew:'Attendant',members:'Confirmed participants',history:'My batch records',date:'Collection date',ticket:'Factory unloading ticket number',batch:'Batch for this unloading ticket',mode:'Unloading status',full:'Fully unloaded — prepare next code',partial:'Partly unloaded — retain code',supplement:'Submit another ticket for a closed batch',select:'Select',saved:'Saved',loading:'Loading…',failed:'Could not complete. Refresh and retry.',CARGO_JOIN:'Join only a batch started today with you on its crew assignment. Ask the supervisor to check the assignment.',CARGO_NOT_FOUND:'No accessible batch found. Check the code and assignment.',CARGO_STATE:'The batch changed. Refresh and select again.',CARGO_TRIP:'Start your assigned trip for today first.',CARGO_DUPLICATE:'This batch already has that ticket number.',CARGO_TICKET:'Select unloading status and enter the ticket number.',CARGO_DENIED:'You cannot perform this action.'},
 ms:{title:'Batch muatan',help:'Kongsi kod batch dengan attendant yang mengutip muatan ini. Kedua-duanya menyimpan kod yang sama.',new:'Kod batch muatan baharu',share:'Berikan kod kepada attendant muatan seterusnya. Mulakan kutipan sebelum attendant mengesahkan penyertaan.',read:'Faham',start:'Mula muatan ini',code:'Masukkan kod batch',lookup:'Semak kod',join:'Sahkan penyertaan muatan ini',refresh:'Muat semula',empty:'Belum ada rekod batch.',prepared:'Sedia untuk mula',active:'Mengutip / menunggu pemunggahan',closed:'Selesai dipunggah',driver:'Pemandu',crew:'Attendant',members:'Peserta disahkan',history:'Rekod batch saya',date:'Tarikh kutipan',ticket:'Nombor tiket pemunggahan kilang',batch:'Batch untuk tiket ini',mode:'Status pemunggahan',full:'Semua dipunggah — sediakan kod baharu',partial:'Sebahagian dipunggah — kekalkan kod',supplement:'Tambah tiket bagi batch selesai',select:'Pilih',saved:'Disimpan',loading:'Memuatkan…',failed:'Gagal. Muat semula dan cuba lagi.',CARGO_JOIN:'Hanya sertai batch bermula hari ini dengan nama anda dalam tugasan kru. Minta penyelia semak tugasan.',CARGO_NOT_FOUND:'Batch tidak ditemui. Semak kod dan tugasan.',CARGO_STATE:'Status batch berubah. Muat semula dan pilih lagi.',CARGO_TRIP:'Mulakan perjalanan ditugaskan hari ini dahulu.',CARGO_DUPLICATE:'Batch ini sudah mempunyai nombor tiket tersebut.',CARGO_TICKET:'Pilih status dan isi nombor tiket.',CARGO_DENIED:'Anda tidak dibenarkan melakukan tindakan ini.'}
}
export const cargoError=(w,e)=>w[e.code]||w.failed
function BatchCard({b,w}){return <article className="cargo-card"><b data-i18n-raw>{b.code} · {b.plate}</b><p>{w[b.status]} · {w.date}: {b.collectionDate||'—'}</p><p>{w.driver}: <span data-i18n-raw>{b.driverName||'—'}</span></p><p>{w.members}: {b.members.map(m=><span data-i18n-raw key={m.employeeId}>{m.name} ({w[m.role]}) </span>)}</p>{b.unloads.map(u=><p key={u.recordId}>{w.ticket}: <span data-i18n-raw>{u.ticketNumber}</span></p>)}</article>}
export function CargoNotification(){const{language}=useI18n(),w=cargoWords[language]||cargoWords.en,[items,setItems]=useState([])
 useEffect(()=>{let alive=true;const load=()=>apiRequest('/api/mobile/cargo-batches').then(d=>alive&&setItems(d.notifications)).catch(()=>{});load();const timer=setInterval(load,10000);window.addEventListener('cargo-changed',load);return()=>{alive=false;clearInterval(timer);window.removeEventListener('cargo-changed',load)}},[])
 if(!items.length)return null
 return <section className="cargo-notification" role="status"><b>{w.new}</b>{items.map(n=><div key={n.id}><strong data-i18n-raw>{n.code} · {n.plate}</strong><button disabled={isEmployeePreview()} onClick={async()=>{try{await apiRequest('/api/mobile/cargo-batches/read',{method:'POST',body:JSON.stringify({id:n.id})});setItems(v=>v.filter(i=>i.id!==n.id))}catch{}}}>{w.read}</button></div>)}<p>{w.share}</p></section>
}
export default function CargoBatches({account}){const{language}=useI18n(),w=cargoWords[language]||cargoWords.en,[data,setData]=useState(null),[code,setCode]=useState(''),[found,setFound]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=()=>apiRequest('/api/mobile/cargo-batches').then(setData)
 useEffect(()=>{let alive=true;const refresh=()=>apiRequest('/api/mobile/cargo-batches').then(d=>alive&&setData(d)).catch(e=>alive&&setError(cargoError(w,e)));refresh();const timer=setInterval(refresh,10000);return()=>{alive=false;clearInterval(timer)}},[])
 const action=async(fn)=>{setBusy(true);setError('');try{await fn();await load();window.dispatchEvent(new Event('cargo-changed'))}catch(e){setError(cargoError(w,e))}finally{setBusy(false)}}
 return <section className="cargo-page"><h1>{w.title}</h1><p>{w.help}</p>{error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={()=>action(load)}>{w.refresh}</button>{account.role==='crew'&&<form onSubmit={e=>{e.preventDefault();action(async()=>setFound(await apiRequest('/api/mobile/cargo-batches/lookup?'+new URLSearchParams({code}))))}}><label>{w.code}<input value={code} onChange={e=>{setCode(e.target.value);setFound(null)}} required autoCapitalize="characters"/></label><button disabled={busy||!code.trim()}>{w.lookup}</button></form>}{found&&<><BatchCard b={found} w={w}/>{found.status==='active'&&!found.members.some(m=>m.employeeId===account.employeeId)&&<button disabled={busy||isEmployeePreview()} onClick={()=>action(async()=>setFound(await apiRequest('/api/mobile/cargo-batches/join',{method:'POST',body:JSON.stringify({code:found.code})})))}>{w.join}</button>}</>}{data?.trips.map(t=>{const b=data.items.find(i=>i.vehicleId===t.vehicleId&&i.status!=='closed');return !b||b.status==='prepared'?<button key={t.tripId} disabled={busy||isEmployeePreview()} onClick={()=>action(()=>apiRequest('/api/mobile/cargo-batches/start',{method:'POST',body:JSON.stringify({tripId:t.tripId})}))}>{w.start} · <span data-i18n-raw>{t.plate}</span></button>:null})}<h2>{w.history}</h2>{!data?<p>{w.loading}</p>:!data.items.length?<p>{w.empty}</p>:data.items.map(b=><BatchCard key={b.id} b={b} w={w}/>)}</section>
}
export function CargoUnloadFields({items,vehicleId,value,onChange,disabled}){const{language}=useI18n(),w=cargoWords[language]||cargoWords.en
 return <fieldset className="cargo-unload-fields" disabled={disabled}><label>{w.batch}<select required value={value.batchId} onChange={e=>{const b=items.find(i=>String(i.id)===e.target.value);onChange({...value,batchId:e.target.value,unloadMode:b?.status==='closed'?'supplement':''})}}><option value="">{w.select}</option>{items.filter(i=>i.vehicleId===vehicleId&&i.status!=='prepared').map(i=><option key={i.id} value={i.id}>{i.code} · {i.collectionDate} · {i.driverName} · {w[i.status]}</option>)}</select></label><label>{w.ticket}<input required maxLength={100} value={value.ticketNumber} onChange={e=>onChange({...value,ticketNumber:e.target.value})}/></label><label>{w.mode}<select required value={value.unloadMode} onChange={e=>onChange({...value,unloadMode:e.target.value})}><option value="">{w.select}</option>{(items.find(i=>String(i.id)===value.batchId)?.status==='closed'?['supplement']:['partial','full']).map(k=><option key={k} value={k}>{w[k]}</option>)}</select></label></fieldset>
}
