import {useCallback,useEffect,useMemo,useState} from 'react'
import {apiRequest as api} from './apiClient.js'
import './CashFloatPage.css'

const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuching',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const firstOfMonth=()=>`${today().slice(0,7)}-01`
const money=cents=>`RM ${(Number(cents||0)/100).toFixed(2)}`
const displayDate=value=>{const match=/^(\d{4})-(\d{2})-(\d{2})/.exec(String(value||''));return match?`${match[3]}-${match[2]}-${match[1].slice(-2)}`:String(value||'')}
const fileData=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,dataUrl:reader.result});reader.onerror=reject;reader.readAsDataURL(file)})
const labels={opening_balance:'Opening Balance',top_up:'Top Up',cash_purchase:'Cash Purchase',expense:'Expense',reversal:'Reversal',adjustment:'Adjustment'}

export default function CashFloatPage(){
  const[filters,setFilters]=useState({from:firstOfMonth(),to:today(),employeeId:''}),[accounts,setAccounts]=useState([]),[transactions,setTransactions]=useState([]),[alerts,setAlerts]=useState([]),[action,setAction]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  const query=useMemo(()=>new URLSearchParams(Object.entries(filters).filter(([,value])=>value)).toString(),[filters])
  const load=useCallback(async()=>{try{const[a,t,n]=await Promise.all([api(`/api/cash-floats?date=${filters.to}`),api(`/api/cash-floats/transactions?${query}`),api('/api/cash-floats/alerts')]);setAccounts(a.items);setTransactions(t.items);setAlerts(n.items);setError('')}catch(item){setError(item.message)}},[query,filters.to])
  useEffect(()=>{load()},[load])
  const complete=async(fn)=>{setBusy(true);setError('');setMessage('');try{await fn();setAction(null);setMessage('Cash Float saved.');await load()}catch(item){setError(item.message)}finally{setBusy(false)}}
  const enableAlerts=async()=>{if(!('Notification'in window))return setError('This browser does not support notifications.');const permission=await Notification.requestPermission();if(permission==='granted')setMessage('Browser alerts enabled. Keep KCS open in the browser to receive low-balance notifications.');else setError('Browser notification permission was not granted.')}
  return <div className="page cash-float-page">
    <div className="cash-heading"><div><small>EMPLOYEE ROLLING FUND</small><h1>Cash Float</h1><p>Cash stays with each employee. Top up at any time; Cash Purchases and Expenses reduce the balance automatically.</p></div><div className="cash-actions"><button className="secondary" onClick={enableAlerts}>Enable Browser Alerts</button><button onClick={()=>{window.location.href=`/api/cash-floats/export.xlsx?${query}`}}>Download Excel</button></div></div>
    {alerts.length>0&&<section className="cash-alerts"><b>Low Balance — Action Required</b>{alerts.map(item=><button key={item.id} onClick={()=>setAction({type:'topup',item:accounts.find(x=>x.employeeId===item.employeeId)||item})}><span>{item.employeeName}: {money(item.balanceCents)}</span><strong>Suggested Top Up {money(item.suggestedTopUpCents)} →</strong></button>)}</section>}
    {message&&<div className="data-success">{message}</div>}{error&&<div className="data-error">{error}</div>}
    <section className="cash-account-grid">{accounts.map(item=><article className={`${item.configured&&item.lowBalance?'low':''}`} key={item.employeeId}><header><div><small>{item.employeeCode||'EMPLOYEE'}</small><h2>{item.employeeName}</h2></div><span className={item.configured?(item.lowBalance?'danger':'ok'):'inactive'}>{item.configured?(item.lowBalance?'LOW':'ACTIVE'):'SET UP'}</span></header>{item.configured?<><div className="cash-balance"><span>Current Balance</span><b>{money(item.balanceCents)}</b></div><dl><div><dt>Target Float</dt><dd>{money(item.targetFloatCents)}</dd></div><div><dt>Low Balance Alert</dt><dd>{money(item.lowBalanceThresholdCents)}</dd></div><div><dt>Suggested Top Up</dt><dd>{money(item.suggestedTopUpCents)}</dd></div></dl><div className="cash-card-actions"><button onClick={()=>setAction({type:'topup',item})}>Top Up</button><button className="secondary" onClick={()=>setAction({type:'expense',item})}>Add Expense</button><button className="text" onClick={()=>setAction({type:'setup',item})}>Settings</button></div></>:<><p>Enter the employee’s real current balance to start without changing old Purchase Bills.</p><button onClick={()=>setAction({type:'setup',item})}>Set Up Cash Float</button></>}</article>)}</section>
    <section className="cash-ledger"><div className="cash-ledger-filters"><h2>Cash Float Ledger</h2><label>From<input type="date" value={filters.from} max={filters.to} onChange={event=>setFilters({...filters,from:event.target.value})}/></label><label>To<input type="date" value={filters.to} min={filters.from} onChange={event=>setFilters({...filters,to:event.target.value})}/></label><label>Employee<select value={filters.employeeId} onChange={event=>setFilters({...filters,employeeId:event.target.value})}><option value="">All employees</option>{accounts.map(item=><option key={item.employeeId} value={item.employeeId}>{item.employeeName}</option>)}</select></label></div><div className="cash-ledger-table"><table><thead><tr><th>Date</th><th>Employee</th><th>Type</th><th>Amount</th><th>Channel</th><th>Reference / PO</th><th>Description</th><th>Entered By</th><th>Proof</th></tr></thead><tbody>{transactions.map(item=><tr key={item.id}><td>{displayDate(item.serviceDate)}</td><td>{item.employeeName}</td><td>{labels[item.transactionType]||item.transactionType}</td><td className={item.amountCents<0?'negative':'positive'}>{item.amountCents<0?'-':'+'}{money(Math.abs(item.amountCents))}</td><td>{item.paymentChannel||'—'}</td><td>{item.billNumber||item.referenceNumber||'—'}</td><td>{item.description||'—'}</td><td>{item.createdBy}</td><td>{item.hasProof?<a href={`/api/cash-floats/proofs/${item.id}`} target="_blank" rel="noreferrer">View proof</a>:'—'}</td></tr>)}</tbody></table>{!transactions.length&&<div className="archive-empty">No Cash Float transactions found.</div>}</div></section>
    {action&&<CashAction action={action} busy={busy} close={()=>setAction(null)} save={payload=>complete(async()=>{const id=action.item.employeeId;if(action.type==='setup')return api(`/api/cash-floats/${id}`,{method:'PATCH',body:JSON.stringify(payload)});const proof=payload.proof?await fileData(payload.proof):undefined;return api(`/api/cash-floats/${id}/${action.type==='topup'?'top-ups':'expenses'}`,{method:'POST',body:JSON.stringify({...payload,proof})})})}/>}
  </div>
}

function CashAction({action,busy,close,save}){const configured=Boolean(action.item.configured),[form,setForm]=useState(action.type==='setup'?{targetFloat:configured?action.item.targetFloatCents/100:500,lowBalanceThreshold:configured?action.item.lowBalanceThresholdCents/100:200,currentBalance:''}:action.type==='topup'?{amount:(action.item.suggestedTopUpCents||0)/100,paymentChannel:'TNG',referenceNumber:'',description:'',proof:null}:{amount:'',description:'',referenceNumber:'',proof:null});const update=(key,value)=>setForm({...form,[key]:value});return <div className="cash-modal" role="dialog" aria-modal="true"><form onSubmit={event=>{event.preventDefault();save(form)}}><header><div><small>{action.item.employeeName}</small><h2>{action.type==='setup'?'Cash Float Settings':action.type==='topup'?'Top Up':'Add Expense'}</h2></div><button type="button" className="close" onClick={close}>×</button></header>{action.type==='setup'?<><label>Target Float (RM)<input required min="0.01" step="0.01" type="number" value={form.targetFloat} onChange={event=>update('targetFloat',event.target.value)}/></label><label>Low Balance Alert (RM)<input required min="0" step="0.01" type="number" value={form.lowBalanceThreshold} onChange={event=>update('lowBalanceThreshold',event.target.value)}/></label>{!configured&&<label>Current Balance (RM)<input required min="0" step="0.01" type="number" value={form.currentBalance} onChange={event=>update('currentBalance',event.target.value)}/><small>Enter the actual money currently held by this employee.</small></label>}</>:<><label>{action.type==='topup'?'Top Up Amount (RM)':'Expense Amount (RM)'}<input required min="0.01" step="0.01" type="number" value={form.amount} onChange={event=>update('amount',event.target.value)}/></label>{action.type==='topup'&&<label>Payment Channel<select value={form.paymentChannel} onChange={event=>update('paymentChannel',event.target.value)}><option>TNG</option><option>Bank Transfer</option><option>Cash</option></select></label>}<label>{action.type==='topup'?'Remark':'Expense Description'}<input required={action.type==='expense'} value={form.description} onChange={event=>update('description',event.target.value)}/></label><label>Reference Number<input value={form.referenceNumber} onChange={event=>update('referenceNumber',event.target.value)}/></label><label>Payment / Receipt Proof (optional)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>update('proof',event.target.files[0]||null)}/></label></>}<footer><button type="button" className="secondary" onClick={close}>Cancel</button><button disabled={busy}>{busy?'Saving…':'Save'}</button></footer></form></div>}

export function CashFloatAlertWatcher({go}){const[alerts,setAlerts]=useState([]);useEffect(()=>{let active=true;const load=()=>api('/api/cash-floats/alerts').then(data=>{if(!active)return;setAlerts(data.items);if('Notification'in window&&Notification.permission==='granted'){const seen=new Set(JSON.parse(localStorage.getItem('kcs_cash_alerts_seen')||'[]'));for(const item of data.items)if(!seen.has(item.id)){new Notification('KCS Low Cash Balance',{body:`${item.employeeName}: ${money(item.balanceCents)}. Top up ${money(item.suggestedTopUpCents)}.`});seen.add(item.id)}localStorage.setItem('kcs_cash_alerts_seen',JSON.stringify([...seen].slice(-100)))}}).catch(()=>{});load();const timer=setInterval(load,15000);return()=>{active=false;clearInterval(timer)}},[]);if(!alerts.length)return null;return <button className="global-cash-alert" onClick={()=>go('cash-float')}><b>{alerts.length}</b><span>Low Cash Balance</span></button>}
