import {useEffect,useRef,useState} from 'react'
import {apiRequest as api} from './apiClient.js'
import {useI18n,useUi} from './i18n.jsx'
import {collectionHistoryWord} from '../shared/collectionHistoryWords.js'
import {formatBranchId} from '../shared/typedIds.js'
import {FilterHeader} from './ExpenseRecordsPage.jsx'
import ExpenseColumnOrder,{expenseColumnWords,normalizeExpenseOrder} from './ExpenseColumnOrder.jsx'
import TableBottomScroll from './TableBottomScroll.jsx'
import './CollectionHistoryPage.css'
const localTime=v=>{if(!v)return '';const d=new Date(/[Z+]|T.*-\d\d:\d\d$/.test(v)?v:v.replace(' ','T')+'Z');return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Kuching',dateStyle:'short',timeStyle:'medium'}).format(d)}
export default function CollectionHistoryPage(){
 const {language}=useI18n(),ui=useUi(),w=k=>collectionHistoryWord(language,k),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[results,setResults]=useState([]),[resultPage,setResultPage]=useState(1),[pages,setPages]=useState(1),[branch,setBranch]=useState(''),[data,setData]=useState(null),[from,setFrom]=useState(''),[to,setTo]=useState(''),[reload,setReload]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(false)
 useEffect(()=>{if(!query)return;let live=true;setBusy(true);setError(false);setResults([]);api(`/api/master/branches?search=${encodeURIComponent(query)}&page=${resultPage}&pageSize=100`).then(r=>{if(live){setResults(r.items);setPages(r.pagination.pages)}}).catch(()=>{if(live)setError(true)}).finally(()=>{if(live)setBusy(false)});return()=>{live=false}},[query,resultPage,reload])
 useEffect(()=>{if(!branch)return;let live=true;setData(null);setBusy(true);setError(false);api(`/api/collection-history?branchId=${encodeURIComponent(branch)}&from=${from}&to=${to}`).then(r=>{if(live)setData(r)}).catch(()=>{if(live)setError(true)}).finally(()=>{if(live)setBusy(false)});return()=>{live=false}},[branch,from,to,reload])
 const val=v=>v==null||v===''?w('unknown'):Array.isArray(v)?v.map(x=>ui(String(x))).join(', '):ui(w(String(v)))
 const snapshot=o=>Object.entries(o||{}).map(([k,v])=>`${w(k)}: ${val(v)}`).join(' · ')||w('unknown')
 const history=(data?.history||[]).map(r=>({...r,time:localTime(r.time),type:w(r.type),status:val(r.status),scope:val(r.scope),before:snapshot(r.before),after:snapshot(r.after),requestedAt:localTime(r.requestedAt),reviewedAt:localTime(r.reviewedAt)}))
 return <section className="collection-history"><h2>{w('title')}</h2><form className="expense-toolbar" onSubmit={e=>{e.preventDefault();setBranch('');setData(null);setFrom('');setTo('');setResultPage(1);setQuery(search.trim());setReload(n=>n+1)}}><input aria-label={w('search')} placeholder={w('search')} value={search} onChange={e=>setSearch(e.target.value)}/><button disabled={!search.trim()}>{w('find')}</button>{branch&&<button type="button" onClick={()=>{setBranch('');setData(null)}}>{w('back')}</button>}<button type="button" onClick={()=>setReload(n=>n+1)}>{w('refresh')}</button></form>
 {error&&<p role="alert">{w('error')}</p>}{busy&&<p role="status">{w('loading')}</p>}
 {!branch&&<><p>{w('choose')}</p><HistoryTable key={`results-${query}-${resultPage}`} id="results" rows={results.map(r=>({...r,id:r.branchId,branchId:formatBranchId(r.branchId),status:val(r.status)}))} columns={['branchId','customerName','branchName','status']} w={w} language={language} onSelect={r=>setBranch(r.id)}/>{pages>1&&<div className="expense-toolbar"><button disabled={resultPage<=1} onClick={()=>setResultPage(n=>n-1)}>{w('previous')}</button><span>{resultPage} / {pages}</span><button disabled={resultPage>=pages} onClick={()=>setResultPage(n=>n+1)}>{w('next')}</button></div>}</>}
 {branch&&<><div className="expense-toolbar"><label>{w('from')}<input type="date" value={from} max={to||undefined} onChange={e=>setFrom(e.target.value)}/></label><label>{w('to')}<input type="date" value={to} min={from||undefined} onChange={e=>setTo(e.target.value)}/></label><button onClick={()=>{setFrom('');setTo('')}}>{w('clear')}</button></div>{data&&<><h3 data-i18n-raw>{formatBranchId(data.branch.branchId)} · {data.branch.customerName} · {data.branch.branchName}</h3><h3>{w('current')}</h3>{!data.branch.enabled&&<p>{w('inactive')}</p>}<p>{w('timeConstraint')}: <span data-i18n-raw>{data.branch.timeConstraint||w('unknown')}</span></p>{data.current.length?<HistoryTable id="current" rows={data.current.map(r=>({...r,id:r.scheduleId,frequency:val(r.frequency),weekdays:val(r.weekdays)}))} columns={['scheduleId','frequency','weekdays','effectiveDate','nextFixedDate']} w={w} language={language}/>:<p>{w('noSchedule')}</p>}<p>{w('nextHint')}</p><p>{w('routes')}: {data.routes.map(r=>`${ui(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][r.weekday])}: ${r.name}`).join(' · ')||w('unknown')}</p><p>{w('upcoming')}: {data.upcoming.map(r=>`${r.date} (${w('routeNumber')} ${r.routeNumber??'—'})`).join(' · ')||w('empty')}</p><h3>{w('history')} ({history.length})</h3><p>{w('coverage')}</p><HistoryTable key={`history-${branch}`} id="history" rows={history} columns={['time','type','before','after','actor','reason','reviewer','reviewReason','scope','status','requestedAt','reviewedAt']} w={w} language={language}/></>}</>}
 </section>
}
function HistoryTable({id,rows,columns,w,language,onSelect}){
 const storage=`kcs.collection-history.${id}`,[order,setOrder]=useState(()=>{try{return normalizeExpenseOrder(JSON.parse(localStorage.getItem(storage)),columns)}catch{return columns}}),[arrange,setArrange]=useState(false),[menu,setMenu]=useState(null),[filters,setFilters]=useState({}),[sort,setSort]=useState({}),[page,setPage]=useState(0),ref=useRef(null)
 const value=(r,k)=>String(r[k]??''),visible=rows.filter(r=>columns.every(k=>filters[k]==null||filters[k].includes(value(r,k))))
 if(sort.key)visible.sort((a,b)=>value(a,sort.key).localeCompare(value(b,sort.key),undefined,{numeric:true})*(sort.direction==='desc'?-1:1))
 const pages=Math.max(1,Math.ceil(visible.length/50)),current=Math.min(page,pages-1)
 return <><div className="expense-toolbar"><button type="button" onClick={()=>setArrange(true)}>{expenseColumnWords[language]?.title||expenseColumnWords.en.title}</button><small>{w('local')}</small></div>{arrange&&<ExpenseColumnOrder order={order} columns={columns.map(k=>[k,w(k)])} w={expenseColumnWords[language]||expenseColumnWords.en} storageKey={storage} onSave={setOrder} onClose={()=>setArrange(false)}/>}<div className="archive-table" ref={ref}><table><thead><tr>{order.map(k=><FilterHeader key={k} label={w(k)} open={menu===k} onOpen={()=>setMenu(k)} onClose={()=>setMenu(null)} value={filters[k]??null} options={[...new Set(rows.map(r=>value(r,k)))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map(v=>({value:v,label:v||'—'}))} onChange={v=>{setPage(0);setFilters(f=>({...f,[k]:v}))}} sortDirection={sort.key===k?sort.direction:null} onSort={direction=>{setPage(0);setSort(direction?{key:k,direction}:{})}}/>)}</tr></thead><tbody>{visible.slice(current*50,current*50+50).map(r=><tr key={r.id}>{order.map(k=><td key={k} className={['before','after','reason','reviewReason'].includes(k)?'history-wrap':''} data-i18n-raw>{onSelect&&k==='branchName'?<button className="history-link" onClick={()=>onSelect(r)}>{value(r,k)||r.branchId}</button>:value(r,k)||'—'}</td>)}</tr>)}</tbody></table>{!visible.length&&<p className="archive-empty">{w('empty')}</p>}</div><TableBottomScroll scrollRef={ref}/>{pages>1&&<div className="expense-toolbar"><button disabled={!current} onClick={()=>setPage(current-1)}>{w('previous')}</button><span>{current+1} / {pages}</span><button disabled={current>=pages-1} onClick={()=>setPage(current+1)}>{w('next')}</button></div>}</>
}
