import {useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest} from './apiClient.js'
import './CombineDayRoutes.css'
const copy={
 en:{title:'Combine areas',help:'For this date only: add the selected routes’ customers to the receiving vehicle’s route. Fixed schedules stay unchanged. Approve the receiving route again before departure.',target:'Receiving route / vehicle',choose:'Select a route with an assigned vehicle',source:'Also collect these routes / areas',reason:'Reason',save:'Save combined collection',close:'Close',saving:'Saving…',saved:'Saved. Check the receiving route, then approve departure.',MULTI_PERMISSION:'Dispatch management permission is required.',MULTI_SELECTION:'Select a receiving route, at least one other route and enter a reason.',MULTI_STALE:'The plan changed. Refresh and select again.',MULTI_PROTECTED:'Withdraw approval first. Started work, records and pending work cannot be combined. For running vehicles, use supervisor dispatch in open areas.',MULTI_PENDING:'Resolve the pending customer requests before combining.',MULTI_VEHICLE:'Assign an available vehicle to the receiving route first.',customers:'customers'},
 ms:{title:'Gabung kawasan',help:'Untuk tarikh ini sahaja: masukkan pelanggan laluan dipilih ke laluan kenderaan penerima. Jadual tetap tidak berubah. Luluskan semula laluan penerima sebelum berlepas.',target:'Laluan / kenderaan penerima',choose:'Pilih laluan dengan kenderaan ditugaskan',source:'Kutip juga laluan / kawasan ini',reason:'Sebab',save:'Simpan kutipan gabungan',close:'Tutup',saving:'Menyimpan…',saved:'Disimpan. Semak laluan penerima dan luluskan pelepasan.',MULTI_PERMISSION:'Kebenaran pengurusan penghantaran diperlukan.',MULTI_SELECTION:'Pilih laluan penerima, sekurang-kurangnya satu laluan lain dan masukkan sebab.',MULTI_STALE:'Pelan berubah. Muat semula dan pilih lagi.',MULTI_PROTECTED:'Tarik balik kelulusan dahulu. Kerja bermula atau berrekod tidak boleh digabungkan. Untuk kenderaan berjalan, gunakan penghantaran penyelia di kawasan terbuka.',MULTI_PENDING:'Selesaikan permintaan pelanggan tertunda dahulu.',MULTI_VEHICLE:'Tugaskan kenderaan tersedia ke laluan penerima dahulu.',customers:'pelanggan'},
 zh:{title:'区域合拼',help:'仅限所选日期：把勾选路线的客户加入接手车辆的行程，固定排程不变。保存后请检查并重新批准接手路线。',target:'接手路线／车辆',choose:'选择已分配车辆的路线',source:'同时负责这些路线／区域',reason:'调整原因',save:'保存合并收货',close:'关闭',saving:'保存中…',saved:'已保存。请检查接手路线并批准出车。',MULTI_PERMISSION:'需要派车管理权限。',MULTI_SELECTION:'请选择接手路线、至少一条其他路线，并填写原因。',MULTI_STALE:'安排已经改变，请刷新后重新选择。',MULTI_PROTECTED:'请先撤回批准；已经出车或有执行、单据的记录不能合并。已出车请使用开放区域的主管推送功能。',MULTI_PENDING:'请先处理客户的待审批申请，再合并。',MULTI_VEHICLE:'请先为接手路线分配当天可用车辆。',customers:'家客户'}
}
export default function CombineDayRoutes({day,onSaved}){
 const{language}=useI18n(),m=copy[language]||copy.en
 const[open,setOpen]=useState(false),[target,setTarget]=useState(''),[sources,setSources]=useState([]),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const routes=(day.routeBoards||[]).filter(r=>r.customerCount>0)
 const save=async()=>{setBusy(true);setError('');try{await apiRequest(`/api/dispatch/day/${day.dispatch_date}/combine-routes`,{method:'POST',body:JSON.stringify({expectedRevision:day.revision,targetRouteNumber:Number(target),sourceRouteNumbers:sources,reason})});setOpen(false);setSources([]);setReason('');setMessage(m.saved);await onSaved()}catch(e){setError(m[e.code]||m[e.message]||e.message)}finally{setBusy(false)}}
 const label=r=>`${r.name} · ${r.registrationNumber||r.vehicle||'—'} · ${r.customerCount} ${m.customers}`
 return <section className="combine-day-routes"><button type="button" disabled={busy} aria-expanded={open} onClick={()=>{setOpen(!open);setError('');setMessage('')}}>{m.title}</button>{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}{open&&<div className="combine-day-editor"><p>{day.dispatch_date} · {m.help}</p>{!['draft','reapproval_required'].includes(day.status)&&<p>{m.MULTI_PROTECTED}</p>}<label>{m.target}<select value={target} disabled={busy} onChange={e=>{setTarget(e.target.value);setSources(s=>s.filter(n=>n!==Number(e.target.value)))}}><option value="">{m.choose}</option>{routes.filter(r=>r.vehicleId).map(r=><option key={r.routeNumber} value={r.routeNumber} data-i18n-raw>{label(r)}</option>)}</select></label><fieldset disabled={busy}><legend>{m.source}</legend>{routes.filter(r=>r.routeNumber!==Number(target)).map(r=><label className="combine-route-option" key={r.routeNumber}><input type="checkbox" checked={sources.includes(r.routeNumber)} onChange={e=>setSources(s=>e.target.checked?[...s,r.routeNumber]:s.filter(n=>n!==r.routeNumber))}/><span><strong data-i18n-raw>{label(r)}</strong><small data-i18n-raw>{[...new Set((r.stops||[]).map(s=>s.zoneGroup||s.area).filter(Boolean))].join(' · ')}</small></span></label>)}</fieldset><label>{m.reason}<input value={reason} disabled={busy} maxLength={500} onChange={e=>setReason(e.target.value)}/></label><div className="combine-route-actions"><button type="button" disabled={busy||!target||!sources.length||!reason.trim()||!['draft','reapproval_required'].includes(day.status)} onClick={save}>{busy?m.saving:m.save}</button><button type="button" disabled={busy} onClick={()=>setOpen(false)}>{m.close}</button></div></div>}</section>
}
