import {useEffect,useRef,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest as api} from './apiClient.js'
import {defaultMenuLayout,billMenuIds} from '../shared/menuLayout.js'
import './CompanyMenu.css'
export default function CompanyMenu({items,page,go}){
 const {t}=useI18n(),[config,setConfig]=useState({layout:defaultMenuLayout(),canEdit:false,revision:0}),[draft,setDraft]=useState(null),[open,setOpen]=useState(billMenuIds.includes(page)),[busy,setBusy]=useState(false),[error,setError]=useState(''),drag=useRef(null)
 useEffect(()=>{let active=true;const load=()=>api('/api/company-menu').then(r=>{if(active)setConfig(r)}).catch(()=>{});load();const timer=setInterval(load,30000);window.addEventListener('focus',load);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',load)}},[])
 useEffect(()=>{if(billMenuIds.includes(page))setOpen(true)},[page])
 const label=id=>id==='documents'?t('menu.documents'):t(items.find(x=>x[0]===id)?.[2]||'menu.unavailable')
 const move=(group,from,to)=>{if(to<0||to>=draft.layout[group].length)return;setDraft(d=>{const list=[...d.layout[group]];list.splice(to,0,list.splice(from,1)[0]);return{...d,layout:{...d.layout,[group]:list}}})}
 const save=async()=>{setBusy(true);setError('');try{const result=await api('/api/company-menu',{method:'PUT',body:JSON.stringify(draft)});setConfig(result);setDraft(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const entry=id=>{const x=items.find(item=>item[0]===id);return x?<button key={id} className={page===id?'active':''} onClick={()=>go(id)}><i>{x[1]}</i>{t(x[2])}</button>:null}
 return <><nav><small>{t('nav.workspace')}</small>{config.layout.top.map(id=>id==='documents'?(config.layout.documents.some(child=>items.some(x=>x[0]===child))&&<div key={id}><button aria-expanded={open} onClick={()=>setOpen(!open)}><i>▱</i>{t('menu.documents')} {open?'▾':'▸'}</button>{open&&<div className="company-menu-children">{config.layout.documents.map(entry)}</div>}</div>):entry(id))}{config.canEdit&&<button onClick={()=>{setDraft({layout:structuredClone(config.layout),revision:config.revision});setError('')}}>{t('menu.edit')}</button>}</nav>{draft&&<div className="company-menu-overlay"><section className="company-menu-editor" role="dialog" aria-modal="true" aria-label={t('menu.edit')}><h2>{t('menu.edit')}</h2><p>{t('menu.shared')}</p>{['top','documents'].map(group=><div key={group}><h3>{t(group==='top'?'menu.main':'menu.documents')}</h3>{draft.layout[group].map((id,i)=><div className="company-menu-row" key={id} draggable={!busy} onDragStart={()=>{drag.current={group,i}}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy&&drag.current?.group===group)move(group,drag.current.i,i);drag.current=null}}><span>{label(id)}</span><button type="button" disabled={busy||i===0} aria-label={t('menu.up')+' '+label(id)} onClick={()=>move(group,i,i-1)}>↑</button><button type="button" disabled={busy||i===draft.layout[group].length-1} aria-label={t('menu.down')+' '+label(id)} onClick={()=>move(group,i,i+1)}>↓</button></div>)}</div>)}{error&&<p role="alert">{error}</p>}<div className="company-menu-actions"><button disabled={busy} onClick={()=>setDraft(d=>({...d,layout:defaultMenuLayout()}))}>{t('menu.reset')}</button><button disabled={busy} onClick={()=>setDraft(null)}>{t('sales.cancel')}</button><button disabled={busy} onClick={save}>{t('sales.save')}</button></div></section></div>}</>
}
