export const customerWorkspaceWords={
 zh:{title:'客户、GPS与收货安排',save:'保存客户及收货安排',branch:'分店资料',name:'分店名称',contact:'联系人',phone:'电话',payment:'付款方式',schedule:'收货安排',route:'所属路线',first:'首次收货日期／生效日期',reason:'新增或修改原因',gps:'GPS定位',capture:'采集当前位置',pending:'GPS等待主管审核',official:'正式GPS已锁定；需要更改时先撤销',later:'暂未采集GPS，可稍后在本页补充',saved:'已保存客户及收货安排',review:'以下日期需要主管核对',confirm:'确认补入此客户',done:'完成',settings:'区域与GPS管理',reload:'资料已改变，请关闭后重新打开再修改。',unsaved:'资料尚未保存，确定离开？',loading:'正在加载',clearGps:'移除本次定位',defer:'稍后安排收货',plan:'保存后同步未来七天；更远日期按排程自动生成。',next:'下次收货日期',failed:'保存失败，请检查资料后重试。'},
 en:{title:'Customer, GPS & collection',save:'Save customer and collection setup',branch:'Branch details',name:'Branch name',contact:'Contact',phone:'Phone',payment:'Payment method',schedule:'Collection setup',route:'Route',first:'First collection / effective date',reason:'Reason for creation or change',gps:'GPS location',capture:'Get current GPS',pending:'GPS awaiting supervisor review',official:'Official GPS is locked; withdraw it before changing',later:'GPS not captured; add it here later',saved:'Customer and collection setup saved',review:'Supervisor review needed for these dates',confirm:'Confirm adding this customer',done:'Done',settings:'Area & GPS management',reload:'Data changed. Close and reopen before editing.',unsaved:'Unsaved changes. Leave?',loading:'Loading',clearGps:'Remove draft GPS',defer:'Arrange collection later',plan:'Sync the next seven days on save; later dates follow the schedule.',next:'Next collection date',failed:'Save failed. Check the details and retry.'},
 ms:{title:'Pelanggan, GPS & kutipan',save:'Simpan pelanggan dan aturan kutipan',branch:'Maklumat cawangan',name:'Nama cawangan',contact:'Orang dihubungi',phone:'Telefon',payment:'Kaedah bayaran',schedule:'Aturan kutipan',route:'Laluan',first:'Tarikh kutipan pertama / berkuat kuasa',reason:'Sebab penambahan atau perubahan',gps:'Lokasi GPS',capture:'Dapatkan GPS semasa',pending:'GPS menunggu semakan penyelia',official:'GPS rasmi dikunci; tarik balik sebelum mengubah',later:'GPS belum direkod; tambah di sini kemudian',saved:'Pelanggan dan aturan kutipan disimpan',review:'Semakan penyelia diperlukan bagi tarikh ini',confirm:'Sahkan penambahan pelanggan ini',done:'Selesai',settings:'Pengurusan kawasan & GPS',reload:'Data telah berubah. Tutup dan buka semula sebelum mengedit.',unsaved:'Perubahan belum disimpan. Keluar?',loading:'Memuatkan',clearGps:'Buang GPS draf',defer:'Atur kutipan kemudian',plan:'Segerakkan tujuh hari akan datang; tarikh seterusnya mengikut jadual.',next:'Tarikh kutipan seterusnya',failed:'Gagal menyimpan. Semak maklumat dan cuba semula.'}
}
export const customerWorkspaceReviewWords={
 zh:{missing:'已批准的安排需要主管确认补入。',completed:'所属路线已完成，请主管安排其他日期。',route:'需要确认所属路线。',route_change:'现有派车路线与新排程不同，请主管核对。',sunday_review:'星期日安排已有批准或人工调整，请主管核对。',outdated:'现有站点受保护，请主管核对新的收货日期。',occurrence:'站点与收货记录的关联需要核对。'},
 en:{missing:'Approved arrangements require supervisor confirmation to add this customer.',completed:'The route is complete. Ask the supervisor to arrange another date.',route:'Confirm the assigned route.',route_change:'The existing dispatch route differs from the new schedule. Supervisor review required.',sunday_review:'Sunday arrangements were approved or manually changed. Supervisor review required.',outdated:'The existing stop is protected. Ask the supervisor to review the new date.',occurrence:'The stop and collection record linkage needs review.'},
 ms:{missing:'Aturan yang diluluskan memerlukan pengesahan penyelia untuk menambah pelanggan ini.',completed:'Laluan telah selesai. Minta penyelia mengatur tarikh lain.',route:'Sahkan laluan yang ditetapkan.',route_change:'Laluan sedia ada berbeza daripada jadual baharu. Semakan penyelia diperlukan.',sunday_review:'Aturan Ahad telah diluluskan atau diubah secara manual. Semakan penyelia diperlukan.',outdated:'Hentian sedia ada dilindungi. Minta penyelia menyemak tarikh baharu.',occurrence:'Pautan hentian dan rekod kutipan memerlukan semakan.'}
}
