import CustomerLocationCheck,{locationWords} from './CustomerLocationCheck.jsx'
import {useEffect,useRef,useState} from 'react'
import {CustomerEditor} from './MasterDataPage.jsx'
import {apiRequest as api} from './apiClient.js'
import {useI18n,useUi} from './i18n.jsx'
import SharedGpsInput from './SharedGpsInput.jsx'
import GoogleMapPreview from './GoogleMapPreview.jsx'
import {collectHighAccuracyPosition} from './highAccuracyGps.js'
import {COLLECTION_FREQUENCIES,COLLECTION_WEEKDAYS,toggleCollectionWeekday,isCollectionWeekdayDisabled} from '../shared/collectionSettings.js'
import {nextCollectionDate} from '../shared/scheduleRecurrence.js'
import {kuchingDate} from '../shared/kuchingTime.js'
import {customerWorkspaceWords,customerWorkspaceReviewWords} from './customerWorkspaceWords.js'
import './CustomerWorkspaceEditor.css'
export default function CustomerWorkspaceEditor(props){
 return <CustomerWorkspaceSession key={JSON.stringify([props.customerId??null,props.branchId??null])} {...props}/>
}
function CustomerWorkspaceSession({branchId,customerId,onClose,onSaved}){
 const {language,t}=useI18n(),ui=useUi(),w=customerWorkspaceWords[language]||customerWorkspaceWords.en
 const [data,setData]=useState(null),[branch,setBranch]=useState({}),[schedule,setSchedule]=useState(null),[gps,setGps]=useState(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[gpsBusy,setGpsBusy]=useState(false),[result,setResult]=useState(null)
 const [locationCheck,setLocationCheck]=useState(null),[changingGps,setChangingGps]=useState(false)
 const lw=locationWords[language]||locationWords.en
 const request=useRef({id:crypto.randomUUID()}),dirty=useRef(false)

 useEffect(()=>{let active=true;api('/api/customer-workspace?'+new URLSearchParams({...branchId?{branchId}:{},...customerId?{customerId}:{}})).then(d=>{if(active){setData(d);setBranch(d.branch||{branchName:'',address:'',paymentType:d.customer?.defaultPaymentType||'Cash'});setSchedule(d.schedule?.frequency?{...d.schedule,routeNumber:d.schedule.homeRouteNumber||''}:null)}}).catch(e=>active&&setError(e.message));return()=>{active=false}},[branchId,customerId])
 const close=()=>{if(busy||gpsBusy)return;if(!result&&dirty.current&&!window.confirm(w.unsaved))return;onClose()}
 const change=(key,value)=>{dirty.current=true;setBranch(b=>({...b,[key]:value}))}
 const ss=(key,value)=>{dirty.current=true;setSchedule(s=>({...s,[key]:value,...(key==='frequency'&&['On Call','Paused'].includes(value)?{weekdays:[]}:{} )}))}
 const capture=async()=>{setGpsBusy(true);setError('');try{const r=await collectHighAccuracyPosition(navigator.geolocation);dirty.current=true;setGps({...r,capturedLatitude:r.latitude,capturedLongitude:r.longitude,capturedAccuracyM:r.accuracyM,locationSource:'device'});try{const a=await api(`/api/gps-collection/reverse-geocode?latitude=${r.latitude}&longitude=${r.longitude}`);setGps(g=>({...g,...a,reverseGeocodeProvider:a.provider}));if(!branch.address&&a.address)change('address',a.address)}catch(e){setError(e.message)}}catch(e){setError(e.message)}finally{setGpsBusy(false)}}
 const adjust=change=>{dirty.current=true;setGps(g=>({...g,...change,locationSource:change.gpsSource||'map_selection',manuallyAdjusted:Boolean(g?.capturedLatitude),...(change.addressComponents||{}),reverseGeocodeProvider:change.addressComponents?.provider||g?.reverseGeocodeProvider}))}
 const save=async customer=>{
  if(!branch.branchName?.trim()||!reason.trim()){setError(t('common.operationFailed'));return}
  setBusy(true);setError('')
  try{const body={requestId:request.current.id,branchId,customerId,revision:data.revision,customer,branch,schedule:['paused','closed'].includes(customer.status)||(branch.lifecycleStatus||'ACTIVE')!=='ACTIVE'?null:schedule,gps,reason,locationCheck};const saved=await api('/api/customer-workspace',{method:'POST',body:JSON.stringify(body)});setResult(saved);dirty.current=false;onSaved?.(saved);if(!saved.review?.length&&!saved.pending?.length&&!saved.locationReviews?.length)onClose()}catch(e){setError(e.status===409?w.reload:e.message||w.failed)}finally{setBusy(false)}
 }
 const confirmSchedule=async r=>{const note=window.prompt(w.reason);if(!note?.trim())return;setBusy(true);setError('');try{const response=await api('/api/customer-workspace/confirm-schedule',{method:'POST',body:JSON.stringify({branchId:result.branch.branchId,date:r.date,expectedRevision:r.expectedRevision,reason:note})});setResult(current=>({...current,review:[...current.review.filter(x=>x.date!==r.date),...response.review]}))}catch(e){setError(e.message)}finally{setBusy(false)}}
 const reviewLocation=async(id,decision)=>{const note=window.prompt(lw.reason);if(!note?.trim())return;setBusy(true);setError('');try{const d=await api('/api/customer-workspace/review-location',{method:'POST',body:JSON.stringify({branchId:data.branch.branchId,id,decision,reason:note})});setData(d);setBranch(b=>({...b,address:d.branch.address,areaId:d.branch.areaId}))}catch{setError(lw.failed)}finally{setBusy(false)}}

 const reviewGps=async(id,decision)=>{const note=window.prompt(t('gps.reviewReason'));if(!note?.trim())return;setBusy(true);try{await api(`/api/gps-collector/${id}/${decision==='adopt'?'adopt':'review'}`,{method:'POST',body:JSON.stringify({reason:note,decision})});const d=await api('/api/customer-workspace?'+new URLSearchParams({branchId:data.branch.branchId}));setData(d)}catch(e){setError(e.message)}finally{setBusy(false)}}
 let next='';try{if(schedule&&(branch.lifecycleStatus||'ACTIVE')==='ACTIVE')next=nextCollectionDate({...schedule,daysOfWeek:schedule.weekdays},kuchingDate())||''}catch{}
 if(result)return <div className="customer-workspace-saved" role="status"><section className="customer-workspace-result"><h2>{w.saved}</h2><p>{result.customer.customerName} · {result.branch.branchName} · {result.branch.branchId}</p>{gps&&<p>{result.pending.length?lw.changePending:lw.initialSaved}</p>}{result.locationReviews?.length>0&&<p>{lw.pending}</p>}{result.schedule&&<p>{w.next}: {result.schedule.nextCollectionDate||'—'}</p>}{result.review?.length>0&&<><h3>{w.review}</h3>{result.review.map((r,i)=><p key={i}>{r.date} · {r.branchName||result.branch.branchName} · {(customerWorkspaceReviewWords[language]||customerWorkspaceReviewWords.en)[r.kind]||w.review} {r.kind==='missing'&&result.canConfirmSchedule&&<button disabled={busy} onClick={()=>confirmSchedule(r)}>{w.confirm}</button>}</p>)}</>}{error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={close}>{w.done}</button></section></div>
 if(!data)return <div className="master-modal" onClick={e=>{if(e.target===e.currentTarget)close()}}><section className="customer-workspace-result"><p role={error?'alert':undefined}>{error||w.loading}</p><button onClick={onClose}>{t('common.close')}</button></section></div>
 const extra=customer=><div className="customer-workspace-fields" onChange={()=>{dirty.current=true}}>
 <section className="customer-workspace-card customer-branch-card"><h3>{w.branch}</h3><div className="editor-fields"><label>{t('list.lifecycleStatus')}<select aria-label={t('list.lifecycleStatus')} value={branch.lifecycleStatus||'ACTIVE'} onChange={e=>change('lifecycleStatus',e.target.value)}>{['ACTIVE','TEMPORARILY_PAUSED','CLOSED'].map(status=><option key={status} value={status}>{t(`branchLifecycle.status.${status}`)}</option>)}</select></label>{[['branchName',w.name],['contactPerson',w.contact],['phone',w.phone],['collectionTimeConstraint',t('master.collectionTime')],['proofRequirements',t('master.proofRequirements')],['vehicleRestriction',t('master.vehicleRestriction')],['notes',t('list.notes')]].map(([k,label])=><label key={k}>{label}<input required={k==='branchName'} value={branch[k]||''} onChange={e=>change(k,e.target.value)}/></label>)}<label>{w.payment}<select value={branch.paymentType||''} onChange={e=>change('paymentType',e.target.value)}><option value="">—</option>{['Cash','Credit'].map(v=><option key={v} value={v}>{ui(v)}</option>)}</select></label></div></section>
 <CustomerLocationCheck payload={{branchId,customerId,revision:data.revision,branch,gps}} data={data} value={locationCheck} onBranchChange={change} onChange={value=>{setLocationCheck(value);if(value)dirty.current=true}} busy={busy||gpsBusy} onReview={reviewLocation}/>
 <section className="customer-workspace-card customer-schedule-card"><fieldset disabled={['paused','closed'].includes(customer.status)||(branch.lifecycleStatus||'ACTIVE')!=='ACTIVE'} style={{border:0,padding:0,margin:0,minWidth:0}}><h3>{w.schedule}</h3><label><input type="checkbox" checked={Boolean(schedule)} disabled={Boolean(data.schedule?.frequency)} onChange={e=>setSchedule(e.target.checked?{frequency:'Once a week',weekdays:[],effectiveDate:kuchingDate(),anchorDate:kuchingDate(),routeNumber:''}:null)}/>{w.schedule}</label>{!schedule&&<p>{w.defer}</p>}{schedule&&<><div className="editor-fields"><label>{w.route}<select required={schedule.weekdays?.length>0} value={schedule.routeNumber||''} onChange={e=>ss('routeNumber',e.target.value)}><option value="">—</option>{data.routeOptions.map(r=><option key={r.routeNumber} value={r.routeNumber}>{r.name}</option>)}</select></label><label>{ui('Frequency')}<select value={schedule.frequency} onChange={e=>ss('frequency',e.target.value)}>{COLLECTION_FREQUENCIES.map(f=><option key={f} value={f}>{ui(f)}</option>)}</select></label><label>{w.first}<input required={!['Paused','On Call'].includes(schedule.frequency)} disabled={['Paused','On Call'].includes(schedule.frequency)} type="date" value={schedule.effectiveDate||''} onChange={e=>{ss('effectiveDate',e.target.value);if(!data.schedule?.scheduleId)ss('anchorDate',e.target.value)}}/></label>{['Every 2 Weeks','Every 3 Weeks','Monthly'].includes(schedule.frequency)&&<label>{ui('周期起算日期')}<input required type="date" value={schedule.anchorDate||''} onChange={e=>ss('anchorDate',e.target.value)}/></label>}{schedule.frequency==='Monthly'&&<label>{t('schedule.monthlyOccurrence')}<select required value={schedule.monthlyOccurrence||''} onChange={e=>ss('monthlyOccurrence',Number(e.target.value))}><option value="">—</option>{[1,2,3,4,-1].map(n=><option key={n} value={n}>{n===-1?ui('Last'):n}</option>)}</select></label>}</div><div className="weekday-picker">{COLLECTION_WEEKDAYS.map(day=><label key={day}><input type="checkbox" checked={schedule.weekdays?.includes(day)||false} disabled={isCollectionWeekdayDisabled(schedule.frequency,schedule.weekdays||[],day)} onChange={()=>ss('weekdays',toggleCollectionWeekday(schedule.frequency,schedule.weekdays||[],day))}/>{ui(day)}</label>)}</div>{schedule.weekdays?.includes('Sunday')&&<label>{ui('星期日执行路线')}<select value={schedule.sundayRouteNumber||''} onChange={e=>ss('sundayRouteNumber',e.target.value)}><option value="">{ui('跟随固定所属路线')}</option>{data.routeOptions.map(r=><option key={r.routeNumber} value={r.routeNumber}>{r.name}</option>)}</select></label>}<p>{w.next}: {next||'—'} · {w.plan}</p></>}
 </fieldset></section><section className="customer-workspace-card customer-gps-card"><h3>{w.gps}</h3><p>{lw.gps}</p>{data.branch?.officialLatitude!=null&&!changingGps?<><p>{w.official}</p>{data.canCaptureGps&&!data.pending.length&&<button type="button" disabled={busy} onClick={()=>setChangingGps(true)}>{lw.request}</button>}<GoogleMapPreview latitude={data.branch.officialLatitude} longitude={data.branch.officialLongitude}/>{data.pending.map(g=><div key={g.id}><p>{lw.changePending}</p><GoogleMapPreview latitude={g.temporaryLatitude} longitude={g.temporaryLongitude}/>{data.canReviewGps&&<><button type="button" disabled={busy} onClick={()=>reviewGps(g.id,'adopt')}>{t('gps.adoptOfficial')}</button><button type="button" disabled={busy} onClick={()=>reviewGps(g.id,'recapture')}>{t('gps.recapture')}</button></>}</div>)}</>:data.pending.length?<><p>{w.pending}</p>{data.pending.map(g=><div key={g.id}><GoogleMapPreview latitude={g.temporaryLatitude} longitude={g.temporaryLongitude}/>{data.canReviewGps&&<><button type="button" disabled={busy} onClick={()=>reviewGps(g.id,'adopt')}>{t('gps.adoptOfficial')}</button><button type="button" disabled={busy} onClick={()=>reviewGps(g.id,'recapture')}>{t('gps.recapture')}</button></>}</div>)}</>:data.canCaptureGps?<><button type="button" disabled={gpsBusy} onClick={capture}>{w.capture}</button>{gps&&<button type="button" onClick={()=>setGps(null)}>{w.clearGps}</button>}<SharedGpsInput allowDevice={false} latitude={gps?.latitude??''} longitude={gps?.longitude??''} address={branch.address||''} onChange={adjust}/>{gps&&<GoogleMapPreview latitude={gps.latitude} longitude={gps.longitude} onPositionAdjusted={adjust}/>} {Number(gps?.capturedAccuracyM)>20&&<p className="data-error">{t('gpsCollection.lowAccuracy',{accuracy:gps.capturedAccuracyM})}</p>}{!gps&&<p>{w.later}</p>}</>:<p>{w.later}</p>}</section>
 {error&&<p className="data-error" role="alert">{error}</p>}
 </div>
 return <div onClick={e=>{if(e.target.classList.contains('master-modal'))close()}} onChangeCapture={()=>{dirty.current=true}}><CustomerEditor workspaceCards readOnlyCustomer={Boolean(data.customer)} initial={data.customer||{status:'active'}} lockId={Boolean(data.customer)} onClose={close} onSave={save} fail={setError} canManagePricing={data.canManagePricing} saving={busy||gpsBusy} extraFields={extra} saveLabel={w.save} title={w.title} changeReason={reason} hideCancel actionFields={<label className="customer-save-reason">{w.reason}<textarea required rows={2} disabled={busy||gpsBusy} value={reason} onChange={e=>setReason(e.target.value)}/></label>} onDirty={()=>{dirty.current=true}}/></div>
}
