import {useEffect,useMemo,useRef,useState} from 'react'
import {apiRequest} from './apiClient.js'
import {useI18n} from './i18n.jsx'
import {kuchingDate} from '../shared/kuchingTime.js'
import {reportWord} from '../shared/dailyReportWords.js'
import {FilterHeader} from './ExpenseRecordsPage.jsx'
import ExpenseColumnOrder,{expenseColumnWords,normalizeExpenseOrder} from './ExpenseColumnOrder.jsx'
import TableBottomScroll from './TableBottomScroll.jsx'
import './ExpenseRecordsPage.css'
import './DailyReport.css'
const keys=['name','kind','status','quantity','amountCents','actor','time']
export function reportTime(value){if(!value)return '—';const d=new Date(/[zZ]|[+-]\d\d:\d\d$/.test(value)?value:String(value).replace(' ','T')+'Z');return Number.isNaN(+d)?String(value):new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Kuching',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(d)}
export default function DailyReport({account}){
 const {language}=useI18n(),w=k=>reportWord(language,k),[open,setOpen]=useState(false),[date,setDate]=useState(kuchingDate),[data,setData]=useState(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[section,setSection]=useState('vehicles'),[target,setTarget]=useState(2000)
 useEffect(()=>{if(!open)return;let active=true;setData(null);setError('');apiRequest('/api/daily-report?date='+encodeURIComponent(date)).then(r=>{if(active)setData(r)}).catch(()=>{if(active)setError(w('failed'))});return()=>{active=false}},[open,date,refresh,language])
 return <section className="daily-report"><header><h2>{w('title')}</h2><button onClick={()=>setOpen(v=>!v)} aria-expanded={open}>{w(open?'close':'open')}</button></header>{open&&<><div className="daily-report-controls"><label>{w('date')}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button onClick={()=>setRefresh(v=>v+1)}>{w('refresh')}</button><label>{w('target')}<input type="number" min="1" step="100" value={target} onChange={e=>setTarget(e.target.value)}/></label></div><p>{w('targetHint')}</p><p>{w('hint')}</p>{error?<p role="alert">{error}</p>:!data||data.date!==date?<p role="status">{w('loading')}</p>:<><p>{w(data.access.full?'full':data.access.finance?'finance':'operations')} · {w('saved')}: {reportTime(data.generatedAt)}</p><div className="daily-report-summary">{Object.entries(data.summary).map(([k,v])=><button key={k} onClick={()=>setSection(({weightKg:'goods',trips:'vehicles',plannedBranches:'stops',collectedBranches:'stops',noGoodsBranches:'stops',pendingBranches:'stops',cancelledBranches:'stops',cashCents:'bills',creditCents:'bills',purchaseCents:'bills',voidCents:'bills',expenseCents:'expenses',topupCents:'topups',salesCents:'sales',deliveredKg:'deliveries',pendingApprovals:'approvals',changedBranches:'changes',rescheduledBranches:'reschedules'})[k]||k)}><strong>{k.endsWith('Cents')?'RM '+(v/100).toFixed(2):Number(v).toLocaleString(undefined,{maximumFractionDigits:3})}</strong><span>{w(k)}</span></button>)}</div><p>{w('pendingHint')}</p>{data.access.finance&&<p>{w('salesHint')}</p>}<nav className="daily-report-tabs">{Object.keys(data.sections).map(k=><button key={k} aria-pressed={section===k} onClick={()=>setSection(k)}>{w(k)} ({data.sections[k].length})</button>)}</nav><h3>{w(section)}</h3><ReportTable key={`${date}-${section}`} rows={data.sections[section]||[]} section={section} finance={data.access.finance} w={w} language={language} target={Number(target)} account={account}/><p>{w('coverage')}</p>{data.missingSources.length>0&&<p role="status">{w('missing')}: {data.missingSources.join(', ')}</p>}</>}</>}</section>
}
function Detail({value,w,field}){if(value==null||value==='')return <span>—</span>;if(typeof value==='boolean')return <span>{w(value?'yes':'no')}</span>;if(typeof value!=='object')return <span data-i18n-raw>{/(At|_at)$/.test(field||'')?reportTime(value):['status','payment','paymentStatus','scope','kind','source','change_type','entity_type'].includes(field)||value==='protected'?w(String(value)):String(value)}</span>;return <dl className="daily-report-detail">{Object.entries(value).filter(([,v])=>v!=null&&v!=='').map(([k,v])=><div key={k}><dt>{w(k)}</dt><dd><Detail value={v} w={w} field={k}/></dd></div>)}</dl>}
function ReportTable({rows,section,finance,w,language,target,account}){
 const available=finance?keys:keys.filter(k=>k!=='amountCents'),storage=`kcs.daily-report.columns.${account?.id}.${section}`,[order,setOrder]=useState(()=>{try{return normalizeExpenseOrder(JSON.parse(localStorage.getItem(storage)),available)}catch{return available}}),[arrange,setArrange]=useState(false),[filters,setFilters]=useState({}),[sort,setSort]=useState({}),[menu,setMenu]=useState(null),[expanded,setExpanded]=useState(null),ref=useRef(null)
 const value=(row,k)=>k==='time'?reportTime(row[k]):k==='amountCents'?row[k]==null?'':(row[k]/100).toFixed(2):k==='quantity'?row[k]==null?'':String(Math.round(row[k]*1000)/1000):['kind','status'].includes(k)?w(String(row[k]??'')):String(row[k]??'')
 const visible=useMemo(()=>{const result=rows.filter(r=>available.every(k=>filters[k]==null||filters[k].includes(value(r,k))));if(sort.key)result.sort((a,b)=>{const k=sort.key;return (['quantity','amountCents'].includes(k)?Number(a[k])-Number(b[k]):value(a,k).localeCompare(value(b,k),undefined,{numeric:true}))*(sort.direction==='desc'?-1:1)});return result},[rows,filters,sort,language])
 return <><button onClick={()=>setArrange(true)}>{expenseColumnWords[language]?.title||expenseColumnWords.en.title}</button><small> {w('local')}</small>{arrange&&<ExpenseColumnOrder order={order} columns={available.map(k=>[k,w(k)])} w={expenseColumnWords[language]||expenseColumnWords.en} storageKey={storage} onSave={setOrder} onClose={()=>setArrange(false)}/>}<div className="archive-table" ref={ref}><table><thead><tr>{order.map(k=><FilterHeader key={k} label={w(k)} open={menu===k} onOpen={()=>setMenu(k)} onClose={()=>setMenu(null)} value={filters[k]??null} options={[...new Set(rows.map(r=>value(r,k)))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map(v=>({value:v,label:v||'—'}))} onChange={v=>setFilters(f=>({...f,[k]:v}))} sortDirection={sort.key===k?sort.direction:null} onSort={direction=>setSort(direction?{key:k,direction}:{})}/>)}</tr></thead><tbody>{visible.map(r=><ReportRows key={r.id} row={r} order={order} value={value} expanded={expanded===r.id} toggle={()=>setExpanded(expanded===r.id?null:r.id)} w={w} section={section} target={target}/>)}</tbody></table>{!visible.length&&<p>{w('empty')}</p>}</div><TableBottomScroll scrollRef={ref}/></>
}
function ReportRows({row,order,value,expanded,toggle,w,section,target}){return <><tr>{order.map(k=><td key={k}>{k==='name'?<button className="daily-report-name" onClick={toggle} aria-expanded={expanded}>{value(row,k)||'—'} {expanded?'▴':'▾'}</button>:value(row,k)||'—'}</td>)}</tr>{expanded&&<tr><td colSpan={order.length}>{section==='vehicles'&&target>0&&<p>{w('achievement')}: {(row.quantity/target*100).toFixed(1)}% · {w(row.quantity>=target?'met':'notMet')} ({target} kg)</p>}<Detail value={row.detail} w={w}/></td></tr>}</>}
