import {useEffect,useState} from 'react'
import {apiRequest} from './apiClient.js'
import {useI18n} from './i18n.jsx'
const words={
 zh:{title:'最近 24 小时已处理／修改',history:'临时客户已审核记录',close:'关闭已审核记录',changes:'修改记录',error:'最近处理记录加载失败',defer:'返回收货审批',intake:'临时客户审核',transfer:'顾客转车审批',arrangement:'司机安排审批',date:'员工改期审批',gps:'GPS 审批',data:'资料修改',approved:'已批准',rejected:'已拒绝',cancelled:'已取消',formal:'正式客户',one_time:'一次性客户',linked:'已关联客户',adopted:'已采用',changed:'已修改',branch:'分店',customer:'客户',branch_schedule:'收货排程'},
 en:{title:'Processed / changed in the last 24 hours',history:'Reviewed temporary customers',close:'Close reviewed records',changes:'Change records',error:'Recent activity could not be loaded',defer:'Return-later review',intake:'Temporary customer review',transfer:'Customer transfer review',arrangement:'Driver arrangement review',date:'Date request review',gps:'GPS review',data:'Data change',approved:'Approved',rejected:'Rejected',cancelled:'Cancelled',formal:'Formal customer',one_time:'One-time customer',linked:'Linked customer',adopted:'Adopted',changed:'Changed',branch:'Branch',customer:'Customer',branch_schedule:'Collection schedule'},
 ms:{title:'Diproses / diubah dalam 24 jam terakhir',history:'Pelanggan sementara telah disemak',close:'Tutup rekod semakan',changes:'Rekod perubahan',error:'Aktiviti terkini gagal dimuatkan',defer:'Semakan kembali kutip',intake:'Semakan pelanggan sementara',transfer:'Semakan pindah pelanggan',arrangement:'Semakan aturan pemandu',date:'Semakan pertukaran tarikh',gps:'Semakan GPS',data:'Perubahan maklumat',approved:'Diluluskan',rejected:'Ditolak',cancelled:'Dibatalkan',formal:'Pelanggan tetap',one_time:'Pelanggan sekali sahaja',linked:'Pelanggan dipautkan',adopted:'Digunakan',changed:'Diubah',branch:'Cawangan',customer:'Pelanggan',branch_schedule:'Jadual kutipan'}
}
export const activityTime=value=>Date.parse(value.replace(' ','T')+(/Z|[+-]\d\d:\d\d$/.test(value)?'':'Z'))
export default function DashboardActivityRecords(){
 const{language}=useI18n(),w=words[language]||words.en,[items,setItems]=useState([]),[error,setError]=useState(false),[now,setNow]=useState(Date.now)
 useEffect(()=>{let alive=true;const load=async()=>{try{const r=await apiRequest('/api/dashboard/recent-activity');if(alive){setItems(r.items);setError(false)}}catch{if(alive)setError(true)}finally{if(alive)setNow(Date.now())}};void load();const timer=setInterval(load,10000);return()=>{alive=false;clearInterval(timer)}},[])
 const recent=items.filter(i=>activityTime(i.time)>now-86400000&&activityTime(i.time)<=now)
 if(!error&&!recent.length)return null
 return <section className="dashboard-activity-records">{error&&<p role="alert">{w.error}</p>}{recent.length>0&&<section className="dashboard-data-tasks"><h2>{w.title} ({recent.length})</h2>{recent.map(i=><article key={i.id}><div><b>{w[i.kind]} · <span data-i18n-raw>{i.name||`${w[i.entityType]||''} ${i.branchId||''}`}</span></b><p>{w[i.status]||i.status} · <time>{new Intl.DateTimeFormat(language==='zh'?'zh-MY':language==='ms'?'ms-MY':'en-MY',{timeZone:'Asia/Kuching',dateStyle:'short',timeStyle:'medium'}).format(activityTime(i.time))}</time> · <span data-i18n-raw>{i.actor}</span></p>{i.reason&&<p data-i18n-raw>{i.reason}</p>}</div></article>)}</section>}</section>
}
