import {useCallback,useEffect,useRef,useState} from 'react'
import {apiRequest as api} from './apiClient.js'
import {useI18n} from './i18n.jsx'

export default function DashboardApprovals({enabled}){
  const{t}=useI18n(),[items,setItems]=useState([]),[busy,setBusy]=useState(null),[error,setError]=useState(''),[soundEnabled,setSoundEnabled]=useState(false)
  const knownIds=useRef(new Set()),initialized=useRef(false),audioContext=useRef(null)
  const ring=useCallback(async()=>{const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return false;const context=audioContext.current||new AudioContext();audioContext.current=context;await context.resume();const start=context.currentTime;[[0,880],[.2,1175]].forEach(([delay,frequency])=>{const oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,start+delay);gain.gain.exponentialRampToValueAtTime(.22,start+delay+.02);gain.gain.exponentialRampToValueAtTime(.0001,start+delay+.16);oscillator.connect(gain).connect(context.destination);oscillator.start(start+delay);oscillator.stop(start+delay+.18)});return true},[])
  const load=useCallback(async()=>{if(!enabled)return;try{const next=(await api('/api/dispatch/defer-requests/pending')).items||[],hasNew=initialized.current&&next.some(item=>!knownIds.current.has(item.id));knownIds.current=new Set(next.map(item=>item.id));initialized.current=true;setItems(next);setError('');if(hasNew&&soundEnabled)void ring()}catch(item){setError(item.message)}},[enabled,ring,soundEnabled])
  useEffect(()=>{if(!enabled)return undefined;void load();const timer=setInterval(()=>void load(),5000);return()=>clearInterval(timer)},[enabled,load])
  useEffect(()=>{const original=document.title;document.title=items.length?`🔔 (${items.length}) KCS Dispatch`:original;return()=>{document.title=original}},[items.length])
  useEffect(()=>()=>{void audioContext.current?.close()},[])
  const enableSound=async()=>{try{if(await ring())setSoundEnabled(true);else setError(t('dashboard.soundUnsupported'))}catch{setError(t('dashboard.soundBlocked'))}}
  const decide=async(item,decision)=>{const reason=window.prompt(t(decision==='approve'?'deferApproval.approveReason':'deferApproval.rejectReason'));if(!reason?.trim())return;setBusy(item.id);try{await api(`/api/dispatch/defer-requests/${item.id}/${decision}`,{method:'POST',body:JSON.stringify({reason:reason.trim()})});await load()}catch(value){setError(value.message)}finally{setBusy(null)}}
  if(!enabled)return null
  return <div className={`dashboard-approvals ${items.length?'has-pending':''}`} role="region" aria-live="polite"><header><strong>{t('dashboard.employeeApprovals')}</strong><div><button type="button" className={soundEnabled?'sound-on':''} disabled={soundEnabled} onClick={enableSound}>{soundEnabled?t('dashboard.soundOn'):t('dashboard.enableSound')}</button><span>{items.length}</span></div></header>{error&&<div className="data-error" role="alert">{error}</div>}{!items.length?<p>{t('dashboard.noEmployeeApprovals')}</p>:items.map(item=><article key={item.id}><div><b>{item.driverName} · {item.registrationNumber||item.vehicleName}</b><strong>{item.branchId} — {item.customerName||item.branchName}</strong><small>{t('mobile.expectedReturnTime')}：{item.expectedReturnTime} · {String(item.reason||'other').replaceAll('_',' ')}</small></div><button disabled={busy!==null} onClick={()=>decide(item,'approve')}>{t('deferApproval.approve')}</button><button disabled={busy!==null} onClick={()=>decide(item,'reject')}>{t('deferApproval.reject')}</button></article>)}</div>
}
