import {useCallback,useEffect,useRef,useState} from 'react'
import {apiRequest as api} from './apiClient.js'
import {useI18n} from './i18n.jsx'

export default function DashboardApprovals({enabled,onOpenBillVoids}){
  const{t}=useI18n(),[items,setItems]=useState([]),[voidRequests,setVoidRequests]=useState([]),[intakeCount,setIntakeCount]=useState(0),[transferCount,setTransferCount]=useState(0),[arrangementCount,setArrangementCount]=useState(0),[busy,setBusy]=useState(null),[error,setError]=useState(''),[soundEnabled,setSoundEnabled]=useState(false)
  const knownIds=useRef(new Set()),initialized=useRef(false),audioContext=useRef(null)
  const ring=useCallback(async()=>{const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return false;const context=audioContext.current||new AudioContext();audioContext.current=context;await context.resume();const start=context.currentTime;[[0,880],[.2,1175]].forEach(([delay,frequency])=>{const oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,start+delay);gain.gain.exponentialRampToValueAtTime(.22,start+delay+.02);gain.gain.exponentialRampToValueAtTime(.0001,start+delay+.16);oscillator.connect(gain).connect(context.destination);oscillator.start(start+delay);oscillator.stop(start+delay+.18)});return true},[])
  const load=useCallback(async()=>{if(!enabled)return;try{const [deferred,intakes,transfers,arrangements,voids]=await Promise.all([api('/api/dispatch/defer-requests/pending'),api('/api/customer-intakes'),api('/api/customer-transfers'),api('/api/driver-arrangements'),api('/api/bill-voids?status=pending')]),next=deferred.items||[],pendingVoids=voids.canReview?(voids.items||[]).flatMap(b=>b.requests.filter(r=>r.status==='pending').map(r=>({...r,billNumber:b.bill_number,employeeName:r.requested_name,customerName:b.branch_name_snapshot||b.customer_name_snapshot,totalCents:b.total_cents}))):[],ids=[...pendingVoids.map(r=>'void-'+r.id),...next.map(i=>'defer-'+i.id),...(intakes.items||[]).map(i=>'intake-'+i.id),...(transfers.items||[]).map(i=>'transfer-'+i.id),...(arrangements.items||[]).map(i=>'arrangement-'+i.id)],hasNew=initialized.current&&ids.some(id=>!knownIds.current.has(id));knownIds.current=new Set(ids);setIntakeCount((intakes.items||[]).length);setTransferCount((transfers.items||[]).length);setArrangementCount((arrangements.items||[]).length);initialized.current=true;setVoidRequests(pendingVoids);setItems(next);setError('');if(hasNew&&soundEnabled)void ring()}catch(item){setError(item.message)}},[enabled,ring,soundEnabled])
  useEffect(()=>{if(!enabled)return undefined;void load();const timer=setInterval(()=>void load(),5000);return()=>clearInterval(timer)},[enabled,load])
  useEffect(()=>{const original=document.title;document.title=items.length+intakeCount+transferCount+arrangementCount+voidRequests.length?`🔔 (${items.length+intakeCount+transferCount+arrangementCount+voidRequests.length}) KCS Dispatch`:original;return()=>{document.title=original}},[items.length,intakeCount,transferCount,arrangementCount,voidRequests.length])
  useEffect(()=>()=>{void audioContext.current?.close()},[])
  const enableSound=async()=>{try{if(await ring())setSoundEnabled(true);else setError(t('dashboard.soundUnsupported'))}catch{setError(t('dashboard.soundBlocked'))}}
  const decide=async(item,decision)=>{const reason=window.prompt(t(decision==='approve'?'deferApproval.approveReason':'deferApproval.rejectReason'));if(!reason?.trim())return;setBusy(item.id);try{await api(`/api/dispatch/defer-requests/${item.id}/${decision}`,{method:'POST',body:JSON.stringify({reason:reason.trim()})});await load()}catch(value){setError(value.message)}finally{setBusy(null)}}
  const decideVoid=async(item,decision)=>{if(busy!==null)return;let note='';if(decision==='approve'){if(!window.confirm(t('void.confirm',{number:item.billNumber,amount:`RM ${(Number(item.totalCents)/100).toFixed(2)}`})))return}else{note=window.prompt(t('void.reviewNote'));if(!note?.trim())return}setBusy('void-'+item.id);setError('');try{await api(`/api/bill-voids/${item.id}/${decision}`,{method:'POST',body:JSON.stringify({note:note.trim()})});await load()}catch(e){setError(e.message)}finally{setBusy(null)}}
  if(!enabled||(!error&&!items.length&&!intakeCount&&!transferCount&&!arrangementCount&&!voidRequests.length))return null
  return <div className={`dashboard-approvals ${items.length+intakeCount+transferCount+arrangementCount+voidRequests.length?'has-pending':''}`} role="region" aria-live="polite"><header><strong>{t('dashboard.employeeApprovals')}</strong><div><button type="button" className={soundEnabled?'sound-on':''} disabled={soundEnabled} onClick={enableSound}>{soundEnabled?t('dashboard.soundOn'):t('dashboard.enableSound')}</button><span>{items.length+intakeCount+transferCount+arrangementCount+voidRequests.length}</span></div></header>{error&&<div className="data-error" role="alert">{error}</div>}{!items.length&&!intakeCount&&!transferCount&&!arrangementCount&&!voidRequests.length?<p>{t('dashboard.noEmployeeApprovals')}</p>:items.map(item=><article key={item.id}><div><b>{item.driverName} · {item.registrationNumber||item.vehicleName}</b><strong>{item.branchId} — {item.customerName||item.branchName}</strong><small>{t('mobile.expectedReturnTime')}：{item.expectedReturnTime} · {String(item.reason||'other').replaceAll('_',' ')}</small></div><button disabled={busy!==null} onClick={()=>decide(item,'approve')}>{t('deferApproval.approve')}</button><button disabled={busy!==null} onClick={()=>decide(item,'reject')}>{t('deferApproval.reject')}</button></article>)}{voidRequests.map(item=><article key={'void-'+item.id}><div><b>{t('void.title')} · {t('void.pending')}</b><strong data-i18n-raw>{item.billNumber} · {item.employeeName}</strong><span data-i18n-raw>{item.customerName} · RM {(Number(item.totalCents)/100).toFixed(2)}</span><small data-i18n-raw>{item.reason}</small></div><button type="button" disabled={busy!==null} onClick={()=>decideVoid(item,'approve')}>{t('void.approve')}</button><button type="button" disabled={busy!==null} onClick={()=>decideVoid(item,'reject')}>{t('void.reject')}</button></article>)}</div>
}
