import { useEffect, useState } from 'react'
import {apiRequest} from './apiClient.js'
import {useI18n} from './i18n.jsx'

function useApi(url){const[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{let active=true;setData(null);setError('');apiRequest(url).then(x=>active&&setData(x)).catch(e=>active&&setError(e.message));return()=>{active=false}},[url]);return{data,error}}
const Raw=({children})=><span data-i18n-raw>{children}</span>
function Loading({error}){const{t}=useI18n();return <div className={error?'data-error':'data-loading'}>{error||t('common.loadingData')}</div>}

export function CustomerBranchesPage(){
  const{t}=useI18n()
  const[search,setSearch]=useState(''),[gps,setGps]=useState(''),[schedule,setSchedule]=useState(''),[page,setPage]=useState(1),[detail,setDetail]=useState(null)
  const q=new URLSearchParams({search,gps,schedule,page:String(page),pageSize:'25'});const{data,error}=useApi(`/api/customer-branches?${q}`)
  const open=async id=>setDetail(await apiRequest(`/api/customer-branches/${encodeURIComponent(id)}`))
  const columns=['BranchID','Customer Name','Branch Name','Zone Group','Area','Payment Type','OCC Price',t('branch.gpsStatus'),t('branch.scheduleStatus'),t('branch.weekday'),'Frequency','']
  return <DataShell eyebrow="CUSTOMER MASTER" title={t('branch.title')} subtitle={t('customer.description')}><div className="filters"><input placeholder={t('branch.search')} value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><select value={gps} onChange={e=>setGps(e.target.value)}><option value="">{t('common.all')} GPS</option><option value="complete">{t('schedule.gpsComplete')}</option><option value="missing">{t('schedule.gpsMissing')}</option></select><select value={schedule} onChange={e=>setSchedule(e.target.value)}><option value="">{t('schedule.allSchedules')}</option><option value="scheduled">{t('schedule.scheduled')}</option><option value="none">{t('schedule.noSchedule')}</option></select></div>{!data?<Loading error={error}/>:<><div className="table-wrap"><table><thead><tr>{columns.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.items.map(x=><tr key={x.branchId}><td><b><Raw>{x.branchId}</Raw></b></td><td><Raw>{x.customerName||'—'}</Raw></td><td><Raw>{x.branchName||'—'}</Raw></td><td><Raw>{x.zoneGroup||'—'}</Raw></td><td><Raw>{x.area||'—'}</Raw></td><td><Raw>{x.paymentType||'—'}</Raw></td><td>{x.occPrice??'—'}</td><td><Status ok={x.latitude!=null&&x.longitude!=null} text={x.gpsStatus||t('branch.notCompleted')}/></td><td><Status ok={x.scheduleCount>0} text={x.scheduleCount?t('branch.scheduleCount',{count:x.scheduleCount}):t('common.none')}/></td><td><Raw>{x.daysOfWeek||'—'}</Raw></td><td><Raw>{x.frequency||'—'}</Raw></td><td><button className="link-button" onClick={()=>open(x.branchId)}>{t('branch.details')}</button></td></tr>)}</tbody></table></div><div className="pager"><span>{t('branch.totalCount',{count:data.pagination.total})}</span><button disabled={page<=1} onClick={()=>setPage(page-1)}>{t('common.previous')}</button><b>{page}/{data.pagination.pages||1}</b><button disabled={page>=data.pagination.pages} onClick={()=>setPage(page+1)}>{t('common.next')}</button></div></>}{detail&&<div className="detail-panel"><button onClick={()=>setDetail(null)}>{t('common.close')}</button><h2 data-i18n-raw>{detail.customerName} · {detail.branchName}</h2><div className="detail-grid">{[['BranchID',detail.branchId],['CustomerID',detail.customerId],['Zone Group',detail.zoneGroup],['Area',detail.area],['Payment Type',detail.paymentType],['OCC Price',detail.occPrice],['GPS',`${detail.latitude??'—'}, ${detail.longitude??'—'}`],['Parking Note',detail.parkingNote],['Truck Access',detail.truckAccess]].map(([k,v])=><div key={k}><small>{k}</small><strong data-i18n-raw>{v||'—'}</strong></div>)}</div><h3>{t('customer.allSchedules')}</h3>{detail.schedules?.map(s=><p key={s.scheduleId} data-i18n-raw>{s.scheduleId} · {s.frequency} · {s.dayOfWeek}</p>)}{detail.warnings?.map(w=><p className="warning-line" key={w}>⚠ <Raw>{w}</Raw></p>)}</div>}</DataShell>
}

export function SchedulesPage(){
  const{t}=useI18n()
  const[day,setDay]=useState(''),[frequency,setFrequency]=useState(''),[search,setSearch]=useState(''),[unmatched,setUnmatched]=useState(false)
  const q=new URLSearchParams({day,frequency,search,unmatched:String(unmatched)}),{data,error}=useApi(`/api/schedules?${q}`)
  const columns=['ScheduleID','BranchID','Branch','Zone Group','Area','Frequency','Day Of Week','Take Date','Next Take Date',t('schedule.flag')]
  return <DataShell eyebrow="COLLECTION PLAN" title={t('schedule.title')} subtitle={t('schedule.description')}><div className="filters"><input placeholder={t('branch.search')} value={search} onChange={e=>setSearch(e.target.value)}/><select value={day} onChange={e=>setDay(e.target.value)}><option value="">{t('schedule.allDays')}</option>{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(x=><option key={x}>{x}</option>)}</select><select value={frequency} onChange={e=>setFrequency(e.target.value)}><option value="">{t('schedule.allFrequency')}</option><option>Weekly</option><option>2 Weeks</option><option>Call</option></select><label><input type="checkbox" checked={unmatched} onChange={e=>setUnmatched(e.target.checked)}/> {t('schedule.unmatchedOnly')}</label></div>{!data?<Loading error={error}/>:<div className="table-wrap"><table><thead><tr>{columns.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.map(x=><tr className={x.unmatched?'row-warning':''} key={x.scheduleId}><td><b><Raw>{x.scheduleId}</Raw></b></td><td><Raw>{x.branchId}</Raw></td><td><Raw>{x.branch||'—'}</Raw></td><td><Raw>{x.zoneGroup||'—'}</Raw></td><td><Raw>{x.area||'—'}</Raw></td><td><Raw>{x.frequency}</Raw></td><td><Raw>{x.dayOfWeek||'—'}</Raw></td><td><Raw>{x.takeDate||'—'}</Raw></td><td><Raw>{x.nextTakeDate||'—'}</Raw></td><td>{x.unmatched?<Status text={t('schedule.notFound')}/>:x.multipleSchedules?<Status ok text={t('schedule.multiple')}/>:'—'}</td></tr>)}</tbody></table></div>}</DataShell>
}

const groupKeys={scheduledWithGps:'schedule.qualityScheduledGps',scheduledMissingGps:'schedule.qualityScheduledMissingGps',gpsWithoutSchedule:'schedule.qualityGpsWithoutSchedule',missingGpsAndSchedule:'schedule.qualityMissingBoth',invalidGps:'schedule.qualityInvalidGps',unmatchedSchedules:'schedule.qualityUnmatchedBranch',missingArea:'schedule.qualityMissingArea'}
export function DataQualityPage(){const{t}=useI18n(),{data,error}=useApi('/api/data-quality/summary');return <DataShell eyebrow="DATA QUALITY" title={t('schedule.dataQuality')} subtitle={t('schedule.dataQualityHelp')}>{!data?<Loading error={error}/>:<div className="quality-grid">{Object.entries(groupKeys).map(([key,labelKey])=><section key={key}><div><h2>{t(labelKey)}</h2><strong>{data[key]?.length??0}</strong></div><div>{(data[key]??[]).slice(0,50).map((x,i)=><p key={x.branchId||x.scheduleId||i}><b data-i18n-raw>{x.branchId||'—'}</b><span data-i18n-raw>{x.customerName||x.branchName||x.dayOfWeek||t('common.waitingReview')}</span></p>)}</div></section>)}</div>}</DataShell>}

function DataShell({eyebrow,title,subtitle,children}){return <div className="page data-page"><div className="data-title"><em>{eyebrow}</em><h1>{title}</h1><p>{subtitle}</p></div>{children}</div>}
function Status({ok=false,text}){return <span className={ok?'status-pill ok':'status-pill'}>{text}</span>}
