import { useEffect, useState } from 'react'

function useApi(url){const[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{let active=true;setData(null);setError('');fetch(url).then(r=>r.json().then(x=>{if(!r.ok)throw new Error(x.error||'载入失败');return x})).then(x=>active&&setData(x)).catch(e=>active&&setError(e.message));return()=>{active=false}},[url]);return{data,error}}
const Loading=({error})=><div className={error?'data-error':'data-loading'}>{error||'资料载入中…'}</div>

export function CustomerBranchesPage(){
  const[search,setSearch]=useState(''),[gps,setGps]=useState(''),[schedule,setSchedule]=useState(''),[page,setPage]=useState(1),[detail,setDetail]=useState(null)
  const q=new URLSearchParams({search,gps,schedule,page:String(page),pageSize:'25'});const{data,error}=useApi(`/api/customer-branches?${q}`)
  const open=async(id)=>{const r=await fetch(`/api/customer-branches/${encodeURIComponent(id)}`);setDetail(await r.json())}
  return <DataShell eyebrow="CUSTOMER MASTER" title="客户与分店" subtitle="资料直接来自 SQLite；Zone Group 可由主管管理，Area 是详细路线区域。"><div className="filters"><input placeholder="搜索 Customer Name、Branch Name 或 BranchID" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><select value={gps} onChange={e=>setGps(e.target.value)}><option value="">全部 GPS</option><option value="complete">已有 GPS</option><option value="missing">缺 GPS</option></select><select value={schedule} onChange={e=>setSchedule(e.target.value)}><option value="">全部排程</option><option value="scheduled">已有排程</option><option value="none">没有排程</option></select></div>{!data?<Loading error={error}/>:<><div className="table-wrap"><table><thead><tr>{['BranchID','Customer Name','Branch Name','Zone Group','Area','Payment Type','OCC Price','GPS 状态','排程状态','星期','Frequency',''].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.items.map(x=><tr key={x.branchId}><td><b>{x.branchId}</b></td><td>{x.customerName||'—'}</td><td>{x.branchName||'—'}</td><td>{x.zoneGroup||'—'}</td><td>{x.area||'—'}</td><td>{x.paymentType||'—'}</td><td>{x.occPrice??'—'}</td><td><Status ok={x.latitude!=null&&x.longitude!=null} text={x.gpsStatus||'未完成'}/></td><td><Status ok={x.scheduleCount>0} text={x.scheduleCount?`${x.scheduleCount} 条`:'无'}/></td><td>{x.daysOfWeek||'—'}</td><td>{x.frequency||'—'}</td><td><button className="link-button" onClick={()=>open(x.branchId)}>查看详情</button></td></tr>)}</tbody></table></div><div className="pager"><span>共 {data.pagination.total} 间分店</span><button disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</button><b>{page}/{data.pagination.pages||1}</b><button disabled={page>=data.pagination.pages} onClick={()=>setPage(page+1)}>下一页</button></div></>}{detail&&<div className="detail-panel"><button onClick={()=>setDetail(null)}>关闭</button><h2>{detail.customerName} · {detail.branchName}</h2><div className="detail-grid">{[['BranchID',detail.branchId],['CustomerID',detail.customerId],['Zone Group',detail.zoneGroup],['Area',detail.area],['Payment Type',detail.paymentType],['OCC Price',detail.occPrice],['GPS',`${detail.latitude??'—'}, ${detail.longitude??'—'}`],['Parking Note',detail.parkingNote],['Truck Access',detail.truckAccess]].map(([k,v])=><div key={k}><small>{k}</small><strong>{v||'—'}</strong></div>)}</div><h3>所有排程</h3>{detail.schedules?.map(s=><p key={s.scheduleId}>{s.scheduleId} · {s.frequency} · {s.dayOfWeek}</p>)}{detail.warnings?.map(w=><p className="warning-line" key={w}>⚠ {w}</p>)}</div>}</DataShell>
}

export function SchedulesPage(){const[day,setDay]=useState(''),[frequency,setFrequency]=useState(''),[search,setSearch]=useState(''),[unmatched,setUnmatched]=useState(false);const q=new URLSearchParams({day,frequency,search,unmatched:String(unmatched)});const{data,error}=useApi(`/api/schedules?${q}`);return <DataShell eyebrow="COLLECTION PLAN" title="收货排程" subtitle="ScheduleID 为唯一编号；Zone Group 与详细 Area 分层显示。"><div className="filters"><input placeholder="搜索 BranchID 或 Branch" value={search} onChange={e=>setSearch(e.target.value)}/><select value={day} onChange={e=>setDay(e.target.value)}><option value="">全部星期</option>{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(x=><option key={x}>{x}</option>)}</select><select value={frequency} onChange={e=>setFrequency(e.target.value)}><option value="">全部 Frequency</option><option>Weekly</option><option>2 Weeks</option><option>Call</option></select><label><input type="checkbox" checked={unmatched} onChange={e=>setUnmatched(e.target.checked)}/> 只看无法匹配 Branch</label></div>{!data?<Loading error={error}/>:<div className="table-wrap"><table><thead><tr>{['ScheduleID','BranchID','Branch','Zone Group','Area','Frequency','Day Of Week','Take Date','Next Take Date','标识'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.map(x=><tr className={x.unmatched?'row-warning':''} key={x.scheduleId}><td><b>{x.scheduleId}</b></td><td>{x.branchId}</td><td>{x.branch||'—'}</td><td>{x.zoneGroup||'—'}</td><td>{x.area||'—'}</td><td>{x.frequency}</td><td>{x.dayOfWeek||'—'}</td><td>{x.takeDate||'—'}</td><td>{x.nextTakeDate||'—'}</td><td>{x.unmatched?<Status text="Branch 找不到"/>:x.multipleSchedules?<Status ok text="多排程"/>:'—'}</td></tr>)}</tbody></table></div>}</DataShell>}

const groupLabels={scheduledWithGps:'已有排程且已有 GPS',scheduledMissingGps:'已有排程但缺 GPS',gpsWithoutSchedule:'有 GPS 但没有排程',missingGpsAndSchedule:'没有 GPS 也没有排程',invalidGps:'GPS 格式异常',unmatchedSchedules:'Schedule BranchID 找不到',missingArea:'AreaID 找不到'}
export function DataQualityPage(){const{data,error}=useApi('/api/data-quality/summary');return <DataShell eyebrow="DATA QUALITY" title="GPS 与资料完整度" subtitle="缺 GPS 或没有排程不是导入错误；系统将其分组列出供后续补齐。">{!data?<Loading error={error}/>:<div className="quality-grid">{Object.entries(groupLabels).map(([key,label])=><section key={key}><div><h2>{label}</h2><strong>{data[key]?.length??0}</strong></div><div>{(data[key]??[]).slice(0,50).map((x,i)=><p key={x.branchId||x.scheduleId||i}><b>{x.branchId||'—'}</b><span>{x.customerName||x.branchName||x.dayOfWeek||'等待核对'}</span></p>)}</div></section>)}</div>}</DataShell>}

function DataShell({eyebrow,title,subtitle,children}){return <div className="page data-page"><div className="data-title"><em>{eyebrow}</em><h1>{title}</h1><p>{subtitle}</p></div>{children}</div>}
function Status({ok=false,text}){return <span className={ok?'status-pill ok':'status-pill'}>{text}</span>}
