export const dateSystemWords={
 zh:{question:'是否同时修改系统资料？',yes:'需要修改',no:'不需要，只处理本次申请',cancel:'返回审核',draft:'保存修改并提交审批',dual:'第一位主管批准后员工可继续下一位客户；分店状态须第二位主管批准才修改。',waiting:'等待第二位主管批准',first:'第一位主管',proposal:'待批准的修改',approve:'批准同一份修改',unchanged:'不修改系统资料',planner:'调整当天车辆与路线',plannerDone:'已保存，返回审核',stale:'资料或排程已变化，请重新载入并核对。',different:'请由另一位主管审核；同一个人不能批准两次。',supervisor:'这项申请需要有员工身份的主管审核。',required:'请完成证明核对、修改选择和审核原因。',failed:'未能完成审核，申请仍待处理。'},
 en:{question:'Also update system records?',yes:'Update records',no:'No, handle this request only',cancel:'Back to review',draft:'Save changes and submit for approval',dual:'The first supervisor may release the employee to the next customer. Branch status changes only after a second supervisor approves.',waiting:'Waiting for a second supervisor',first:'First supervisor',proposal:'Proposed changes',approve:'Approve these same changes',unchanged:'No system record changes',planner:'Edit today’s vehicle and route',plannerDone:'Saved; return to review',stale:'Records or plans changed. Reload and review again.',different:'A different supervisor must review. One person cannot approve twice.',supervisor:'A supervisor with an employee identity must review this request.',required:'Check the evidence, select the update option and enter a review reason.',failed:'Review could not be completed. The request remains pending.'},
 ms:{question:'Ubah rekod sistem juga?',yes:'Ya, ubah rekod',no:'Tidak, urus permintaan ini sahaja',cancel:'Kembali ke semakan',draft:'Simpan perubahan dan hantar untuk kelulusan',dual:'Kelulusan pertama membolehkan pekerja ke pelanggan seterusnya. Status cawangan hanya berubah selepas penyelia kedua meluluskan.',waiting:'Menunggu penyelia kedua',first:'Penyelia pertama',proposal:'Cadangan perubahan',approve:'Luluskan perubahan yang sama',unchanged:'Tiada perubahan rekod sistem',planner:'Ubah lori dan laluan hari ini',plannerDone:'Sudah simpan; kembali semak',stale:'Rekod atau jadual telah berubah. Muat semula dan semak.',different:'Penyelia lain mesti menyemak. Orang yang sama tidak boleh lulus dua kali.',supervisor:'Permintaan ini perlu disemak penyelia dengan identiti pekerja.',required:'Semak bukti, pilih perubahan dan isi sebab semakan.',failed:'Semakan gagal. Permintaan masih belum diluluskan.'}
}

Object.assign(dateSystemWords.zh,{released:'第一位主管已批准继续下一位客户；本店不计为已收货。',systemRejected:'分店状态修改已退回；原资料不变，收货由主管另行安排，员工无需返回上一站。',noActive:'目前没有其他可执行的行程。',legacyRelease:'这笔旧申请尚未放行；第一位主管可再次确认，让员工继续下一位。'})
Object.assign(dateSystemWords.en,{released:'The first supervisor approved moving to the next customer. This stop is not counted as collected.',systemRejected:'Branch status change rejected. Records stay unchanged; the supervisor will review collection arrangements. Do not return automatically.',noActive:'There are no other active trips at present.',legacyRelease:'This earlier request has not released the employee. The first supervisor can confirm again to release it.'})
Object.assign(dateSystemWords.ms,{released:'Penyelia pertama benarkan ke pelanggan seterusnya. Kedai ini tidak dikira sudah dikutip.',systemRejected:'Perubahan status ditolak. Rekod kekal; penyelia akan semak semula kutipan. Pekerja tidak perlu kembali secara automatik.',noActive:'Tiada perjalanan aktif lain buat masa ini.',legacyRelease:'Permintaan lama ini belum dilepaskan. Penyelia pertama boleh sahkan sekali lagi supaya pekerja boleh teruskan.'})
