import {useI18n} from './i18n.jsx'
const words={
 zh:{title:'行程尚未完成',go:'前往处理',supervisor:'请联系主管处理',retry:'处理后请再次按“结束行程”。',arrival:'尚未确认到店，请处理到店；无货或改期按申请流程处理。',bill:'已到店，尚未开有效单据，请检查开单或无货流程。',proof:'尚未上传现金付款凭证，请补传。',finish_stop:'已有单据，请确认完成本站。',approval:'有申请等待审批。',closed_unused:'客户已关闭，站点尚未执行。',closed_protected:'客户已关闭，但已有执行或凭证记录，需要核对。',inactive:'客户目前不是启用状态，需要核对。',order:'请先处理排在前面的客户。'},
 en:{title:'Trip is not complete',go:'Go to stop',supervisor:'Contact your supervisor',retry:'After resolving these items, tap Complete Trip again.',arrival:'Arrival has not been recorded. Handle arrival or follow the No Goods / rescheduling process.',bill:'Arrived without an issued bill. Check billing or the No Goods process.',proof:'Cash payment proof is missing. Upload the proof.',finish_stop:'Bill recorded. Confirm completion of this stop.',approval:'A request is awaiting approval.',closed_unused:'The branch is closed and this stop is untouched.',closed_protected:'The branch is closed but has execution or evidence records to review.',inactive:'The branch is not active and needs review.',order:'Handle the earlier customer first.'},
 ms:{title:'Perjalanan belum selesai',go:'Pergi ke hentian',supervisor:'Hubungi penyelia',retry:'Selepas selesai, tekan Selesaikan perjalanan sekali lagi.',arrival:'Ketibaan belum direkodkan. Uruskan ketibaan atau ikut proses Tiada Barang / perubahan tarikh.',bill:'Sudah tiba tetapi belum ada bil sah. Semak bil atau proses Tiada Barang.',proof:'Bukti bayaran tunai belum dimuat naik. Sila muat naik bukti.',finish_stop:'Bil telah direkodkan. Sahkan selesai hentian ini.',approval:'Permohonan sedang menunggu kelulusan.',closed_unused:'Cawangan telah ditutup dan hentian belum dilaksanakan.',closed_protected:'Cawangan ditutup tetapi mempunyai rekod pelaksanaan atau bukti untuk disemak.',inactive:'Cawangan tidak aktif dan perlu disemak.',order:'Uruskan pelanggan yang lebih awal dahulu.'}}
export default function DriverTripBlockers({items,onGo,busy}){
 const{language}=useI18n(),w=words[language]||words.en
 return <div className="auth-error" role="alert"><b>{w.title}</b>{items.map(s=><div key={s.stopId} style={{padding:'10px 0',borderBottom:'1px solid #e8cccc'}}><strong data-i18n-raw>{s.stopSequence}. {s.branchName}</strong><p>{w[s.issue]||w.supervisor}</p>{s.contactSupervisor&&<b>{w.supervisor}</b>}{s.canGo&&<button type="button" className="secondary-mobile" disabled={busy} onClick={()=>onGo(s.stopId)}>{w.go}</button>}</div>)}<p>{w.retry}</p></div>
}
