import {Fragment,useRef,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {formatDateDisplay} from './dateDisplay.js'
import {FilterHeader} from './ExpenseRecordsPage.jsx'
import ExpenseColumnOrder,{expenseColumnWords,normalizeExpenseOrder} from './ExpenseColumnOrder.jsx'
import TableBottomScroll from './TableBottomScroll.jsx'
import RouteBranchEditor from './RouteBranchEditor.jsx'

export const dueWords={
 zh:{title:'到期未到店客户',total:'到期未到店客户总数',branchName:'分店',route:'路线',dueDate:'应收日期／时间',no_collection:'未有收货记录',schedule_unknown:'收货频率未完整设置',on_call:'等通知／无固定到期日',bill:'最近有效购货单',overdueMinutes:'逾期时长',lastCollectionDate:'上次实际收货',newDate:'现安排日期',driverName:'司机',overdueStatus:'状态',today:'今日待到店',overdue:'已逾期／没有到达记录',timed_out:'已超时／没有到达记录',empty:'没有符合条件的客户',note:'按最近有效购货单的收货日期及当前固定收货频率计算；作废单不计，改期、到达或无货不会重置。没有单据或频率不完整时不计算逾期。时间按马来西亚时间；无法识别的时间限制按日期判断。',asOf:'核对时间',restriction:'客户时间限制',history:'改期记录',visits:'到达／收货记录',date:'日期',from:'原定日期',to:'改到日期',reason:'原因',approver:'批准人',at:'到达时间',completed:'完成时间',status:'状态',close:'收起',none:'没有记录',collected:'已完成收货',arrived:'已有到达记录',arrived_no_goods:'已到店／无货',bill_record:'已有有效单据',completed_unverified:'有完成记录／没有到达或有效单据',reported_no_goods:'已报告无货／没有到达记录',blocked:'当天任务已有执行记录或不符合支援分配条件。',minutes:'分钟',days:'天',hours:'小时',local:'栏目顺序保存在当前浏览器。'},
 en:{title:'Customers due without arrival',total:'Total customers due without arrival',branchName:'Branch',route:'Route',dueDate:'Collection due date / time',no_collection:'No collection record',schedule_unknown:'Collection schedule incomplete',on_call:'On call / no fixed due date',bill:'Latest valid purchase bill',overdueMinutes:'Overdue duration',lastCollectionDate:'Last actual collection',newDate:'Current scheduled date',driverName:'Driver',overdueStatus:'Status',today:'Due today',overdue:'Overdue / no arrival record',timed_out:'Past deadline / no arrival record',empty:'No matching customers',note:'Calculated from the latest issued purchase bill service date and current recurring collection schedule. Voided bills are excluded; rescheduling, arrival and no goods do not reset the clock. No overdue duration is guessed without a bill or a complete schedule. Malaysia time applies; unrecognized time limits use date only.',asOf:'Checked at',restriction:'Customer time restriction',history:'Date changes',visits:'Arrival / collection records',date:'Date',from:'Original date',to:'New date',reason:'Reason',approver:'Approved by',at:'Arrival time',completed:'Completed at',status:'Status',close:'Collapse',none:'No records',collected:'Collection completed',arrived:'Arrival recorded',arrived_no_goods:'Arrived / no goods',bill_record:'Valid bill recorded',completed_unverified:'Completion recorded / no arrival or valid bill',reported_no_goods:'No goods reported / no arrival record',blocked:'Work has started or this customer is not eligible for support assignment.',minutes:'min',days:'d',hours:'h',local:'Column order is saved in this browser.'},
 ms:{title:'Pelanggan sampai tarikh tanpa rekod ketibaan',total:'Jumlah pelanggan sampai tarikh tanpa rekod ketibaan',branchName:'Cawangan',route:'Laluan',dueDate:'Tarikh / masa kutipan sepatutnya',no_collection:'Belum ada rekod kutipan',schedule_unknown:'Jadual kutipan tidak lengkap',on_call:'Tunggu panggilan / tiada tarikh tetap',bill:'Bil belian sah terakhir',overdueMinutes:'Tempoh lewat',lastCollectionDate:'Kutipan sebenar terakhir',newDate:'Tarikh jadual semasa',driverName:'Pemandu',overdueStatus:'Status',today:'Perlu hadir hari ini',overdue:'Lewat / tiada rekod ketibaan',timed_out:'Melepasi masa / tiada rekod ketibaan',empty:'Tiada pelanggan sepadan',note:'Dikira daripada tarikh kutipan bil belian sah terakhir dan jadual kutipan tetap semasa. Bil batal dikecualikan; pertukaran tarikh, ketibaan dan tiada barang tidak menetapkan semula kiraan. Tempoh lewat tidak dianggarkan tanpa bil atau jadual lengkap. Mengikut masa Malaysia; had masa tidak dikenali dinilai mengikut tarikh sahaja.',asOf:'Disemak pada',restriction:'Had masa pelanggan',history:'Pertukaran tarikh',visits:'Rekod ketibaan / kutipan',date:'Tarikh',from:'Tarikh asal',to:'Tarikh baharu',reason:'Sebab',approver:'Diluluskan oleh',at:'Masa ketibaan',completed:'Masa selesai',status:'Status',close:'Tutup',none:'Tiada rekod',collected:'Kutipan selesai',arrived:'Ketibaan direkodkan',arrived_no_goods:'Sudah hadir / tiada barang',bill_record:'Bil sah direkodkan',completed_unverified:'Selesai direkodkan / tiada ketibaan atau bil sah',reported_no_goods:'Tiada barang dilaporkan / tiada rekod ketibaan',blocked:'Tugasan telah bermula atau pelanggan tidak layak untuk bantuan.',minutes:'min',days:'hari',hours:'jam',local:'Susunan lajur disimpan dalam pelayar ini.'}
}
const keys=['branchName','route','dueDate','overdueMinutes','lastCollectionDate','newDate','driverName','overdueStatus'],orderKey='kcs.due-customers.columns.v1'
const natural=new Intl.Collator(undefined,{numeric:true,sensitivity:'base'})
export function recordTime(value){
 if(!value)return '—'
 const raw=String(value),time=new Date(/[zZ]$|[+-]\d{2}:?\d{2}$/.test(raw)?raw:raw.replace(' ','T')+'Z')
 if(!Number.isFinite(+time))return '—'
 const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kuching',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(time).map(p=>[p.type,p.value]))
 return formatDateDisplay(`${p.year}-${p.month}-${p.day}`)+' '+p.hour+':'+p.minute
}
export default function DueCustomers({data,selection,disabled,onRefresh}){
 const{language}=useI18n(),w=dueWords[language]||dueWords.en,cw=expenseColumnWords[language]||expenseColumnWords.en,scrollRef=useRef(null)
 const[expanded,setExpanded]=useState(null),[editing,setEditing]=useState(null),[filters,setFilters]=useState({}),[sort,setSort]=useState({key:'overdueMinutes',direction:'desc'}),[open,setOpen]=useState(null),[showColumns,setShowColumns]=useState(false)
 const[order,setOrder]=useState(()=>{try{return normalizeExpenseOrder(JSON.parse(localStorage.getItem(orderKey)),keys)}catch{return keys}})
 const rows=(data.due||[]).map(b=>({...b,route:b.routeNumbers.map(n=>selection?.routes.find(r=>r.routeNumber===n)?.name||data.routes.find(r=>r.routeNumber===n)?.name||String(n)).join(' / ')}))
 const compare=(key,a,b)=>key==='overdueMinutes'?(a==null?-1:Number(a))-(b==null?-1:Number(b)):natural.compare(a??'',b??'')
 const shown=rows.filter(b=>Object.entries(filters).every(([key,values])=>values==null||values.includes(String(b[key]??'')))).sort((a,b)=>sort.key?compare(sort.key,a[sort.key],b[sort.key])*(sort.direction==='desc'?-1:1)||natural.compare(a.branchName,b.branchName):0)
 const display=(key,value,b={})=>key==='overdueStatus'?w[value]||value:key==='overdueMinutes'?(value>0?`${Math.floor(value/1440)} ${w.days} ${Math.floor(value%1440/60)} ${w.hours} ${value%60} ${w.minutes}`:'—'):['dueDate','lastCollectionDate','newDate'].includes(key)?(value?formatDateDisplay(value)+(key==='dueDate'&&b.deadlineTime?' '+b.deadlineTime:''):'—'):value||'—'
 const choice=b=>{const stop=selection?.routes.flatMap(r=>r.stops).find(s=>s.id===b.stopId),extra=data.items.find(s=>s.id===b.id);return{extra,allowed:b.stopId?Boolean(stop&&['locked','available'].includes(stop.status)&&!stop.hasBill&&!stop.arrivedAt&&!stop.completedAt):Boolean(extra)}}
 const toggle=(b,checked)=>{if(b.stopId)selection.setStops(ids=>checked?[...new Set([...ids,b.stopId])]:ids.filter(id=>id!==b.stopId));else selection.setOtherCustomers(items=>checked?items.some(s=>s.id===b.id)?items:[...items,choice(b).extra]:items.filter(s=>s.id!==b.id))}
 return <div className="due-customers" data-i18n-raw>
  <header><strong>{w.total}: {shown.length}</strong><button type="button" onClick={()=>setShowColumns(true)}>{cw.title}</button></header>
  <p>{w.note}</p><small>{w.asOf}: {recordTime(data.asOf)} · {w.local}</small>
  {showColumns&&<ExpenseColumnOrder order={order} columns={keys.map(k=>[k,w[k]])} w={cw} storageKey={orderKey} onSave={setOrder} onClose={()=>setShowColumns(false)}/>}
  {editing&&<RouteBranchEditor branchId={editing} onClose={()=>{setEditing(null);onRefresh()}}/>}
  <div className="archive-table" ref={scrollRef}><table><thead><tr>{order.map(key=><FilterHeader key={key} label={w[key]} numeric={key==='overdueMinutes'} value={filters[key]??null} options={['',...new Set(rows.map(b=>String(b[key]??'')).filter(Boolean))].sort((a,b)=>compare(key,a,b)).map(value=>({value,label:value?display(key,value):''}))} onChange={value=>setFilters(v=>({...v,[key]:value}))} sortDirection={sort.key===key?sort.direction:null} onSort={direction=>setSort(direction?{key,direction}:{})} open={open===key} onOpen={()=>setOpen(key)} onClose={()=>setOpen(null)}/>)}</tr></thead>
   <tbody>{shown.map(b=><Fragment key={b.id}><tr className="reschedule-summary-row due-summary-row" tabIndex={0} aria-label={b.branchName} aria-expanded={expanded===b.id} onClick={()=>setExpanded(expanded===b.id?null:b.id)} onKeyDown={e=>{if(e.target===e.currentTarget&&['Enter',' '].includes(e.key)){e.preventDefault();setExpanded(expanded===b.id?null:b.id)}}}>{order.map(key=><td key={key}>{key==='branchName'&&selection?<div className="support-option" title={choice(b).allowed?'':w.blocked}><input type="checkbox" aria-label={b.branchName||b.branchCode} onClick={e=>e.stopPropagation()} disabled={disabled||!choice(b).allowed} checked={b.stopId?selection.stops.includes(b.stopId):selection.otherCustomers.some(s=>s.id===b.id)} onChange={e=>toggle(b,e.target.checked)}/><span>{b.branchName||b.branchCode}</span></div>:display(key,b[key],b)}</td>)}</tr>
    {expanded===b.id&&<tr className="reschedule-detail-row"><td colSpan={order.length}><section><header><strong>{b.branchCode?<button type="button" className="reschedule-branch-link" onClick={()=>setEditing(b.branchCode)}>{b.branchName||b.branchCode}</button>:b.branchName}</strong><button type="button" onClick={()=>setExpanded(null)}>{w.close}</button></header><p>{w.bill}: {b.lastBillNumber||'—'} · {formatDateDisplay(b.lastCollectionDate)}</p><p>{w.restriction}: {b.timeRestriction||'—'}</p>
     <strong>{w.history}</strong><div className="reschedule-detail-scroll"><table><thead><tr>{['from','to','reason','approver'].map(k=><th key={k}>{w[k]}</th>)}</tr></thead><tbody>{(b.history||[]).map(h=><tr key={h.id}><td>{formatDateDisplay(h.sourceDate)}</td><td>{formatDateDisplay(h.targetDate)}</td><td>{h.reason||'—'}</td><td>{h.approvedBy||'—'} · {recordTime(h.approvedAt)}</td></tr>)}</tbody></table>{!b.history?.length&&<p>{w.none}</p>}</div>
     <strong>{w.visits}</strong><div className="reschedule-detail-scroll"><table><thead><tr>{['date','at','completed','driverName','status'].map(k=><th key={k}>{w[k]}</th>)}</tr></thead><tbody>{(b.visits||[]).map(v=><tr key={v.id}><td>{formatDateDisplay(v.date)}</td><td>{recordTime(v.arrivedAt)}</td><td>{recordTime(v.completedAt)}</td><td>{v.driverName||'—'}</td><td>{w[v.status]||v.status}</td></tr>)}</tbody></table>{!b.visits?.length&&<p>{w.none}</p>}</div>
    </section></td></tr>}
   </Fragment>)}</tbody></table>{!shown.length&&<p>{w.empty}</p>}</div><TableBottomScroll scrollRef={scrollRef}/>
 </div>
}
