import {useEffect,useId,useRef,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest as api} from './apiClient.js'
import {earningsWords} from '../shared/earningsWords.js'
import {kuchingDate} from '../shared/kuchingTime.js'
import {FilterHeader} from './ExpenseRecordsPage.jsx'
import TableBottomScroll from './TableBottomScroll.jsx'
import ExpenseColumnOrder,{expenseColumnWords,normalizeExpenseOrder} from './ExpenseColumnOrder.jsx'
import RecordActionIcon from './RecordActionIcon.jsx'
import BackButton from './BackButton.jsx'
import './EmployeeEarnings.css'
const columns=['name','weightKg','pendingKg','unitRate','amount','paidAt']
const displayEmployee=e=>{
 const rates=[...new Set([...(e.driverKg>0?[e.rate]:[]),...(e.crewKg>0?[e.crewRate]:[])])]
 return {...e,weightKg:Math.round((e.driverKg+e.crewKg)*1000)/1000,unitRate:rates.length?rates.join(' / '):'—'}
}
const savedColumns=()=>{
 const saved=JSON.parse(localStorage.getItem('earnings-columns'))
 const aliases={driverKg:'weightKg',crewKg:'weightKg',rate:'unitRate',crewRate:'unitRate'}
 return normalizeExpenseOrder(Array.isArray(saved)?saved.map(k=>aliases[k]||k):saved,columns)
}
const previous=date=>{const d=Number(date.slice(8));return d>15?date.slice(0,7)+'-01':new Date(Date.UTC(Number(date.slice(0,4)),Number(date.slice(5,7))-1,0)).toISOString().slice(0,10)}
export default function EmployeeEarnings({personal=false,onBack,view,onViewChange}){
 const{language}=useI18n(),w=earningsWords[language]||earningsWords.en,[date,setDate]=useState(kuchingDate()),[reports,setReports]=useState(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[localSettings,setLocalSettings]=useState(false),[showPrevious,setShowPrevious]=useState(false)
 useEffect(()=>setShowPrevious(false),[date,personal,view,localSettings])
 const settings=!personal&&(view===undefined?localSettings:view==='settings'),setSettings=value=>{setLocalSettings(value);onViewChange?.(value?'settings':'')}
 useEffect(()=>{let last=kuchingDate();const roll=()=>{const today=kuchingDate();if(today!==last){const prior=last;last=today;setDate(d=>d===prior?today:d)}};const timer=setInterval(roll,30000);window.addEventListener('focus',roll);return()=>{clearInterval(timer);window.removeEventListener('focus',roll)}},[])
 useEffect(()=>{if(settings)return;let alive=true;setReports(null);const load=()=>Promise.all([date,previous(date)].map(d=>api((personal?'/api/mobile/earnings':'/api/earnings')+'?'+new URLSearchParams({date:d})))).then(r=>{if(alive){setReports(r);setError('')}}).catch(e=>alive&&setError(w[e.code]||w.failed));load();const timer=setInterval(load,30000);return()=>{alive=false;clearInterval(timer)}},[date,personal,refresh,language,settings])
 if(settings)return <section className="page earnings-page earnings-settings-page"><Settings w={w} date={date} onClose={()=>setSettings(false)} onSaved={()=>{setSettings(false);setRefresh(n=>n+1)}}/></section>
 return <section className="page earnings-page">{personal?<h1>{w.mine}</h1>:<div className="earnings-navigation"><BackButton className="earnings-back" fallback={onBack} iconOnly/><button onClick={()=>setSettings(true)}>{w.settings}</button></div>}<div className="earnings-toolbar"><label>{w.period}<input type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/></label><button className="earnings-icon" title={w.refresh} aria-label={w.refresh} onClick={()=>setRefresh(n=>n+1)}><RecordActionIcon kind="refresh"/></button>{reports?.[1]&&<button className="earnings-previous-button" type="button" aria-haspopup="dialog" onClick={()=>setShowPrevious(true)}>{w.previous}</button>}</div>{error&&<p role="alert">{error}</p>}{!reports&&!error&&<p>{w.loading}</p>}{reports?.[0]&&<Period key={reports[0].period.start} r={reports[0]} personal={personal} w={w} language={language} title={w.current} onChange={()=>setRefresh(n=>n+1)}/>} {showPrevious&&reports?.[1]&&<PreviousPeriod key={reports[1].period.start} r={reports[1]} personal={personal} w={w} language={language} onChange={()=>setRefresh(n=>n+1)} onClose={()=>setShowPrevious(false)}/> }</section>
}
function PreviousPeriod({r,personal,w,language,onChange,onClose}){
 const ref=useRef(null),closeRef=useRef(null)
 useEffect(()=>{const dialog=ref.current,previous=document.activeElement;if(dialog.showModal)dialog.showModal();else dialog.setAttribute('open','');closeRef.current?.focus({preventScroll:true});return()=>{if(dialog.close)dialog.close();previous?.focus?.({preventScroll:true})}},[])
 return <dialog ref={ref} className="earnings-detail-dialog earnings-previous-dialog" aria-label={w.previous} onCancel={e=>{e.preventDefault();e.stopPropagation();onClose()}} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="earnings-previous-content"><header><button ref={closeRef} type="button" onClick={onClose}>{w.close}</button></header><Period r={r} personal={personal} w={w} language={language} title={w.previous} onChange={onChange} inPopup/></div></dialog>
}
function Period({r,personal,w,language,title,onChange,inPopup=false}){
 const dockRef=useRef(null),ref=useRef(null),[selected,setSelected]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filters,setFilters]=useState({}),[sort,setSort]=useState({}),[open,setOpen]=useState(null),[editOrder,setEditOrder]=useState(false),[order,setOrder]=useState(()=>{try{return savedColumns()}catch{return columns}})
 const items=r.items.map(displayEmployee)
 const compare=new Intl.Collator('en',{numeric:true,sensitivity:'base'}).compare,rows=items.filter(e=>columns.every(k=>!Array.isArray(filters[k])||filters[k].includes(String(e[k]??'')))).sort((a,b)=>sort.key?(sort.direction==='desc'?-1:1)*(typeof a[sort.key]==='number'?a[sort.key]-b[sort.key]:compare(String(a[sort.key]||''),String(b[sort.key]||''))):0)
 const paid=async e=>{if(!window.confirm(w.confirm))return;setBusy(true);setError('');try{await api('/api/earnings/paid',{method:'POST',body:JSON.stringify({periodStart:r.period.start,employeeId:e.employeeId,revision:e.revision})});onChange()}catch(err){setError(w[err.code]||w.failed)}finally{setBusy(false)}}
 const employee=r.items.find(e=>e.employeeId===selected)
 return <article className="earnings-period"><h2>{title} · {r.period.start} ～ {r.period.end}</h2><p>{w.due}: {r.period.due}</p>{error&&<p role="alert">{error}</p>}
 {!personal&&<button className="earnings-icon" aria-label={expenseColumnWords[language]?.title||w.settings} title={expenseColumnWords[language]?.title||w.settings} onClick={()=>setEditOrder(true)}><RecordActionIcon kind="columns"/></button>}{editOrder&&<ExpenseColumnOrder storageKey="earnings-columns" order={order} columns={columns.map(k=>[k,w[k]])} w={expenseColumnWords[language]||expenseColumnWords.en} onSave={setOrder} onClose={()=>setEditOrder(false)}/>}
 {personal?<div className="earnings-personal">{rows.map(e=><article key={e.employeeId}><h3><button className="earnings-name" aria-haspopup="dialog" data-i18n-raw onClick={()=>setSelected(e.employeeId)}>{e.name}</button></h3>{columns.filter(k=>k!=='name').map(k=><p key={k}><span>{w[k]}</span><b>{k==='amount'?'RM '+e.amount.toFixed(2):e[k]??'—'}</b></p>)}{e.changed&&<p role="alert">{w.changed}</p>}<button onClick={()=>setSelected(e.employeeId)}>{w.details}</button></article>)}</div>:<><div className="earnings-scroll" ref={ref}><table><thead><tr>{order.map(k=><FilterHeader key={k} label={w[k]} open={open===k} onOpen={()=>setOpen(k)} onClose={()=>setOpen(null)} value={filters[k]??null} options={[...new Set(['',...items.map(e=>String(e[k]??''))])].sort(compare).map(v=>({value:v,label:v||'—'}))} onChange={v=>setFilters({...filters,[k]:v})} sortDirection={sort.key===k?sort.direction:null} onSort={direction=>setSort(direction?{key:k,direction}:{})}/>)}</tr></thead><tbody>{rows.map(e=><tr key={e.employeeId}>{order.map(k=><td key={k}>{k==='name'?<button className="earnings-name" aria-haspopup="dialog" data-i18n-raw onClick={()=>setSelected(e.employeeId)}>{e.name}</button>:k==='paidAt'?e.paidAt||(!personal&&r.period.end<kuchingDate()?<button disabled={busy||e.pendingCount>0||r.unlinkedCount>0||e.amount<=0} onClick={()=>paid(e)}>{w.paid}</button>:'—'):k==='amount'?e.amount.toFixed(2):e[k]}</td>)}</tr>)}</tbody></table></div><TableBottomScroll scrollRef={ref} dockRef={inPopup?dockRef:undefined}/>{inPopup&&<div className="earnings-previous-scroll-dock" ref={dockRef}/>}</>}{!rows.length&&<p>{w.empty}</p>}
 {employee&&<EarningsDetail personal={personal} employee={employee} period={r.period} w={w} onClose={()=>setSelected(null)}/>}</article>
}
function EarningsDetail({employee,period,w,onClose,personal=false}){
 const ref=useRef(null),heading=useRef(null),id=useId()
 useEffect(()=>{const dialog=ref.current,previous=document.activeElement;if(dialog.showModal)dialog.showModal();else dialog.setAttribute('open','');heading.current?.focus({preventScroll:true});return()=>{if(dialog.close)dialog.close();previous?.focus?.({preventScroll:true})}},[])
 return <dialog ref={ref} className="earnings-detail-dialog" aria-labelledby={id} onCancel={e=>{e.preventDefault();e.stopPropagation();onClose()}} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="earnings-detail-content"><header><div><h2 ref={heading} tabIndex={-1} id={id} data-i18n-raw>{employee.name}</h2><p>{period.start} ～ {period.end}</p></div><button type="button" onClick={onClose}>{w.close}</button></header>{employee.changed&&<p role="alert">{w.changed}</p>}<h3>{w.details}</h3>{!employee.details.length&&<p>{w.empty}</p>}{employee.details.map(d=><article key={d.recordId}><b>{w.date}: {d.collectionDate}{!personal&&<> · {w[d.role]}</>}</b><p>{w.delivery}: {d.deliveryDate}</p><p data-i18n-raw>{d.plate} · {d.batch} · {d.ticket}</p><p>{w.weight}: {d.weight} · {w.settled}: {d.settledKg??'—'} · {d.matched?w.matched:w.pending}</p></article>)}</div></dialog>
}

function Settings({w,date,onClose,onSaved}){
 const [data,setData]=useState(null),[rules,setRules]=useState(null),[effective,setEffective]=useState(date.slice(0,7)+(Number(date.slice(8))<=15?'-01':'-16')),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let alive=true;api('/api/earnings/settings').then(d=>{if(alive){setData(d);const applicable=d.versions.find(v=>v.effectiveStart<=effective);setRules(structuredClone(applicable?.rules||d.defaults))}}).catch(e=>alive&&setError(w[e.code]||w.failed));return()=>{alive=false}},[])
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/api/earnings/settings',{method:'POST',body:JSON.stringify({effectiveStart:effective,rules,revision:data.revision})});onSaved()}catch(e){setError(w[e.code]||w.failed)}finally{setBusy(false)}}
 return <form className="earnings-settings" onSubmit={save}><header className="earnings-navigation"><button type="button" className="earnings-back" aria-label={w.close} title={w.close} disabled={busy} onClick={onClose}>←</button><h2>{w.settings}</h2></header><p>{w.rulesHelp}</p>{error&&<p role="alert">{error}</p>}{rules&&<fieldset disabled={busy}><label>{w.effective}<input required type="date" value={effective} onChange={e=>setEffective(e.target.value)}/></label>{rules.driver.map((r,i)=><div className="earnings-tier" key={i}><label>{w.from}<input required type="number" step="0.001" min="0" disabled={i===0} value={r.from} onChange={e=>setRules({...rules,driver:rules.driver.map((x,j)=>j===i?{...x,from:e.target.value===''?'':Number(e.target.value)}:x)})}/></label><label>{w.unit}<input required type="number" step="0.000001" min="0" max="10" value={r.rate} onChange={e=>setRules({...rules,driver:rules.driver.map((x,j)=>j===i?{...x,rate:e.target.value===''?'':Number(e.target.value)}:x)})}/></label>{i>0&&<button type="button" onClick={()=>setRules({...rules,driver:rules.driver.filter((_,j)=>j!==i)})}>{w.remove}</button>}</div>)}<button type="button" onClick={()=>setRules({...rules,driver:[...rules.driver,{from:rules.driver.at(-1).from+1000,rate:rules.driver.at(-1).rate}]})}>{w.add}</button><label>{w.crewRate}<input required type="number" step="0.000001" min="0" max="10" value={rules.crewRate} onChange={e=>setRules({...rules,crewRate:e.target.value===''?'':Number(e.target.value)})}/></label><button className="earnings-save">{w.save}</button><details><summary>{w.history}</summary>{data.versions.map(v=><p key={v.id}>{w.version} {v.id} · {v.effectiveStart} · {v.rules.driver.map(r=>`${r.from}kg: RM${r.rate}`).join(' / ')} · {w.crewRate}: {v.rules.crewRate}</p>)}</details></fieldset>}</form>
}
