import {useState} from 'react'
export const expenseColumnWords={zh:{title:'调整栏目',save:'保存',close:'关闭',reset:'恢复默认',hint:'拖动栏目或用上下箭头调整顺序。保存后，本浏览器会记住排列。',up:'上移',down:'下移',history:'更正记录',corrected:'已更正',unchanged:'未更正',number:'费用编号',failed:'无法保存排列，请检查浏览器储存设置。'},en:{title:'Arrange columns',save:'Save',close:'Close',reset:'Restore default',hint:'Drag columns or use the arrows. This browser remembers your saved order.',up:'Move up',down:'Move down',history:'Correction history',corrected:'Corrected',unchanged:'Unchanged',number:'Expense No.',failed:'Unable to save order. Check browser storage settings.'},ms:{title:'Susun lajur',save:'Simpan',close:'Tutup',reset:'Susunan asal',hint:'Seret lajur atau gunakan anak panah. Susunan disimpan dalam pelayar ini.',up:'Naik',down:'Turun',history:'Sejarah pembetulan',corrected:'Dibetulkan',unchanged:'Tidak dibetulkan',number:'No. belanja',failed:'Gagal menyimpan susunan. Semak tetapan storan pelayar.'}}
export const expenseOrderKey='kcs.expense-column-order.v1'
export function normalizeExpenseOrder(saved,keys){return [...new Set([...(Array.isArray(saved)?saved.filter(k=>keys.includes(k)):[]),...keys])]}
export function readExpenseOrder(keys){try{return normalizeExpenseOrder(JSON.parse(localStorage.getItem(expenseOrderKey)),keys)}catch{return keys}}
export default function ExpenseColumnOrder({order,columns,w,onSave,onClose}){
 const[draft,setDraft]=useState(order),[drag,setDrag]=useState(null),[error,setError]=useState('')
 const move=(key,target)=>setDraft(current=>{const next=current.filter(k=>k!==key);next.splice(target,0,key);return next})
 const save=()=>{try{localStorage.setItem(expenseOrderKey,JSON.stringify(draft));onSave(draft);onClose()}catch{setError(w.failed)}}
 return <div className="cash-modal expense-column-modal" role="dialog" aria-modal="true" aria-label={w.title} onClick={e=>{if(e.target===e.currentTarget)onClose()}} onKeyDown={e=>{if(e.key==='Escape')onClose()}}><form onSubmit={e=>{e.preventDefault();save()}}><header><h2>{w.title}</h2><button type="button" onClick={onClose} aria-label={w.close}>×</button></header><p>{w.hint}</p>{draft.map((key,i)=><div className="expense-column-row" key={key} draggable onDragStart={e=>{setDrag(key);e.dataTransfer.setData('text/plain',key)}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag&&draft.includes(drag))move(drag,i);setDrag(null)}} onDragEnd={()=>setDrag(null)}><span>{columns.find(c=>c[0]===key)?.[1]}</span><button type="button" disabled={!i} aria-label={w.up+': '+columns.find(c=>c[0]===key)?.[1]} onClick={()=>move(key,i-1)}>↑</button><button type="button" disabled={i===draft.length-1} aria-label={w.down+': '+columns.find(c=>c[0]===key)?.[1]} onClick={()=>move(key,i+1)}>↓</button></div>)}{error&&<p role="alert">{error}</p>}<footer><button type="button" onClick={()=>setDraft(columns.map(c=>c[0]))}>{w.reset}</button><button>{w.save}</button></footer></form></div>
}
