import {useEffect,useRef,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest} from './apiClient.js'
import {proofData} from './paymentProofImage.js'
export const emptyExpenseDetails={vehicleId:'',odometerKm:'',companyName:'',tinNumber:'',remarks:'',referenceNumber:''}
export default function ExpenseDetailFields({form,setForm,vehicles=[],category,proof,busy=false,onReadingChange=()=>{}}){
 const{t}=useI18n(),[reading,setReading]=useState(false),[notice,setNotice]=useState(''),latest=useRef(proof),mounted=useRef(true)
 latest.current=proof
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;onReadingChange(false)}},[onReadingChange])
 useEffect(()=>setNotice(''),[proof])
 const required=Boolean(category&&category!=='Other'),change=(key,value)=>setForm(current=>({...current,[key]:value}))
 const recognize=async()=>{const selected=proof;setReading(true);onReadingChange(true);setNotice('');try{const result=await apiRequest('/api/expenses/recognize',{method:'POST',body:JSON.stringify({proof:await proofData(selected)})});if(!mounted.current||latest.current!==selected)return;setForm(current=>{const next={...current};for(const key of ['amount','referenceNumber','companyName','tinNumber','vehicleId','odometerKm'])if((next[key]==null||String(next[key]).trim()==='')&&result.fields?.[key]!=null)next[key]=result.fields[key];return next});setNotice(result.status==='review'?'review':result.status==='unavailable'?'unavailable':result.status==='busy'?'busy':'unreadable')}catch{if(mounted.current)setNotice('unreadable')}finally{if(mounted.current){setReading(false);onReadingChange(false)}}}
 return <fieldset className="expense-detail-fields" disabled={busy||reading}><legend>{t('expenseDetail.title')}</legend><p>{t(required?'expenseDetail.required':'expenseDetail.optional')}</p>{proof&&<button type="button" onClick={recognize}>{t(reading?'expenseDetail.reading':'expenseDetail.read')}</button>}{notice&&<p role="status">{t('expenseDetail.'+notice)}</p>}<label>{t('expenseDetail.vehicle')}{required?' *':''}<select required={required} value={form.vehicleId||''} onChange={e=>change('vehicleId',e.target.value)}><option value="">{t('expenseDetail.selectVehicle')}</option>{vehicles.map(v=><option key={v.id} value={v.id} data-i18n-raw>{v.registrationNumber||v.vehicleCode}</option>)}</select></label><label>{t('expenseDetail.meter')}{required?' *':''}<input type="number" min="0" max="10000000" step="0.1" inputMode="decimal" required={required} value={form.odometerKm??''} onChange={e=>change('odometerKm',e.target.value)}/></label><label>{t('expenseDetail.invoice')}{required?' *':''}<input required={required} maxLength={150} value={form.referenceNumber||''} onChange={e=>change('referenceNumber',e.target.value)}/></label><label>{t('expenseDetail.company')}{required?' *':''}<input required={required} maxLength={250} value={form.companyName||''} onChange={e=>change('companyName',e.target.value)}/></label><label>{t('expenseDetail.tin')}<input maxLength={100} value={form.tinNumber||''} onChange={e=>change('tinNumber',e.target.value)}/></label><label>{t('expenseDetail.remarks')}<textarea maxLength={2000} value={form.remarks||''} onChange={e=>change('remarks',e.target.value)}/></label></fieldset>
}
