import {useCallback,useEffect,useMemo,useState} from 'react'
import {apiRequest as api} from './apiClient.js'
import './ExpenseRecordsPage.css'

const categories=['Fuel','Services','Repair','Spare Parts','Road Tax','Puspakom','Insurance','Other']
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuching',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const firstOfMonth=()=>`${today().slice(0,7)}-01`
const money=cents=>`RM ${(Number(cents||0)/100).toFixed(2)}`
const displayDate=value=>{const match=/^(\d{4})-(\d{2})-(\d{2})/.exec(String(value||''));return match?`${match[3]}-${match[2]}-${match[1].slice(-2)}`:String(value||'')}
const displayDateTime=value=>{const date=displayDate(value),time=String(value||'').match(/T(\d{2}:\d{2})/)?.[1];return time?`${date} ${time}`:date}
const fileData=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,dataUrl:reader.result});reader.onerror=reject;reader.readAsDataURL(file)})
const columns=[['serviceDateLabel','Date'],['expenseTypeLabel','Type'],['employeeName','Employee / Admin'],['category','Category'],['description','Description'],['amountLabel','Amount'],['paymentMethod','Payment Method'],['referenceNumber','Reference'],['createdBy','Entered By'],['createdAtLabel','Entered Time'],['receiptLabel','Receipt']]

export default function ExpenseRecordsPage(){
  const[filters,setFilters]=useState({from:firstOfMonth(),to:today(),search:'',expenseType:'',category:'',employeeId:''}),[columnFilters,setColumnFilters]=useState({}),[data,setData]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false)
  const query=useMemo(()=>new URLSearchParams(Object.entries(filters).filter(([,value])=>value)).toString(),[filters])
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await api(`/api/expenses?${query}`))}catch(item){setError(item.message)}finally{setLoading(false)}},[query])
  useEffect(()=>{load()},[load])
  const rows=useMemo(()=>(data?.items||[]).map(item=>({...item,serviceDateLabel:displayDate(item.serviceDate),expenseTypeLabel:item.expenseType==='admin'?'Admin Expense':'Employee Expense',amountLabel:money(item.amountCents),createdAtLabel:displayDateTime(item.createdAt),receiptLabel:item.hasProof?'Uploaded':'Missing'})),[data])
  const displayed=useMemo(()=>rows.filter(row=>Object.entries(columnFilters).every(([key,value])=>!value||String(row[key]??'')===value)),[rows,columnFilters])
  const save=async form=>{setBusy(true);setError('');setMessage('');try{const proof=form.proof?await fileData(form.proof):undefined,description=form.category==='Other'?form.otherDescription.trim():form.category;await api('/api/expenses',{method:'POST',body:JSON.stringify({...form,description,proof})});setShowForm(false);setMessage('Expense saved and Cash Float balance updated.');await load()}catch(item){setError(item.message)}finally{setBusy(false)}}
  return <div className="page purchase-archive expense-records">
    <div className="archive-heading"><div><small>ACCOUNT SUPPORTING DOCUMENTS</small><h1>Expense Records</h1><p>Employee and office expenses, receipt photos and Cash Float deductions in one place.</p></div><div className="archive-actions"><button className="secondary" onClick={()=>setShowForm(true)}>＋ Record Expense</button><button onClick={()=>{window.location.href=`/api/expenses/export.xlsx?${query}`}}>Download Excel with Receipts</button></div></div>
    <section className="archive-filters expense-filters">
      <label>From Date<div className="compact-date"><span>{displayDate(filters.from)}</span><i aria-hidden="true">▣</i><input aria-label="From Date" type="date" value={filters.from} max={filters.to} onChange={event=>setFilters({...filters,from:event.target.value})}/></div></label>
      <label>To Date<div className="compact-date"><span>{displayDate(filters.to)}</span><i aria-hidden="true">▣</i><input aria-label="To Date" type="date" value={filters.to} min={filters.from} onChange={event=>setFilters({...filters,to:event.target.value})}/></div></label>
      <label>Search<input placeholder="Employee, description or reference" value={filters.search} onChange={event=>setFilters({...filters,search:event.target.value})}/></label>
      <label>Type<select value={filters.expenseType} onChange={event=>setFilters({...filters,expenseType:event.target.value,employeeId:event.target.value==='admin'?'':filters.employeeId})}><option value="">All types</option><option value="employee">Employee Expense</option><option value="admin">Admin Expense</option></select></label>
      <label>Category<select value={filters.category} onChange={event=>setFilters({...filters,category:event.target.value})}><option value="">All categories</option>{categories.map(item=><option key={item}>{item}</option>)}</select></label>
      <label>Employee<select disabled={filters.expenseType==='admin'} value={filters.employeeId} onChange={event=>setFilters({...filters,employeeId:event.target.value})}><option value="">All employees</option>{(data?.employees||[]).map(item=><option value={item.employeeId} key={item.employeeId}>{item.employeeName}{item.configured?'':' — Not Set Up'}</option>)}</select></label>
    </section>
    {message&&<div className="data-success">{message}</div>}{error&&<div className="data-error">{error}</div>}{loading&&!data&&<div className="data-loading">Loading Expense Records…</div>}
    <div className="archive-table"><table className="expense-table"><thead><tr>{columns.map(([key,label])=><FilterHeader key={key} label={label} value={columnFilters[key]||''} values={[...new Set(rows.map(row=>String(row[key]??'')).filter(Boolean))]} onChange={value=>setColumnFilters(current=>({...current,[key]:value}))}/>)}</tr></thead><tbody>{displayed.map(item=><tr key={item.recordKey}><td>{item.serviceDateLabel}</td><td><span className={`expense-type ${item.expenseType}`}>{item.expenseTypeLabel}</span></td><td><b>{item.employeeName}</b><small>{item.employeeCode||''}</small></td><td><span className="expense-category">{item.category}</span></td><td>{item.description||'—'}</td><td><b>{item.amountLabel}</b></td><td>{item.paymentMethod||'—'}</td><td>{item.referenceNumber||'—'}</td><td>{item.createdBy||'—'}</td><td>{item.createdAtLabel}</td><td>{item.hasProof?<a href={`/api/expenses/${item.recordKey}/receipt`} target="_blank" rel="noreferrer">View receipt</a>:'Missing'}</td></tr>)}</tbody></table>{!loading&&data&&!displayed.length&&<div className="archive-empty">No Expense Records found for this selection.</div>}</div>
    {showForm&&<ExpenseForm employees={data?.employees||[]} busy={busy} close={()=>setShowForm(false)} save={save}/>}
  </div>
}

function FilterHeader({label,value,values,onChange}){return <th><label className={value?'compact-filter active':'compact-filter'}><span>{label}</span><i aria-hidden="true">▼</i><select aria-label={`Filter ${label}`} value={value} onChange={event=>onChange(event.target.value)}><option value="">All</option>{values.sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map(item=><option key={item} value={item}>{item}</option>)}</select></label></th>}

function ExpenseForm({employees,busy,close,save}){const configured=employees.filter(item=>item.configured),[form,setForm]=useState({expenseType:'employee',employeeId:configured[0]?.employeeId||'',serviceDate:today(),amount:'',category:'',otherDescription:'',paymentMethod:'Cash',referenceNumber:'',proof:null}),update=(key,value)=>setForm({...form,[key]:value}),employeeExpense=form.expenseType==='employee',canSave=!employeeExpense||Boolean(configured.length);return <div className="cash-modal" role="dialog" aria-modal="true"><form onSubmit={event=>{event.preventDefault();save(form)}}><header><div><small>EXPENSE RECORD</small><h2>Record Expense</h2></div><button type="button" className="close" onClick={close}>×</button></header><label>Expense Type<select value={form.expenseType} onChange={event=>update('expenseType',event.target.value)}><option value="employee">Employee Expense</option><option value="admin">Admin Expense</option></select></label>{employeeExpense&&<label>Employee<select required value={form.employeeId} onChange={event=>update('employeeId',event.target.value)}>{employees.map(item=><option disabled={!item.configured} key={item.employeeId} value={item.employeeId}>{item.employeeName}{item.configured?'':' — Not Set Up'}</option>)}</select></label>}{employeeExpense&&!configured.length&&<div className="expense-no-account">No employee has completed Cash Float setup. Set up an employee in Cash Float first.</div>} {!employeeExpense&&<label>Payment Method<select value={form.paymentMethod} onChange={event=>update('paymentMethod',event.target.value)}><option>Cash</option><option>Bank Transfer</option><option>TNG</option><option>Card</option></select></label>}<label>Date<input required type="date" max={today()} value={form.serviceDate} onChange={event=>update('serviceDate',event.target.value)}/></label><label>Amount (RM)<input required min="0.01" step="0.01" type="number" inputMode="decimal" value={form.amount} onChange={event=>update('amount',event.target.value)}/></label><label>Description<select required value={form.category} onChange={event=>update('category',event.target.value)}><option value="">Select description</option>{categories.map(item=><option key={item}>{item}</option>)}</select></label>{form.category==='Other'&&<label>Other description<input required value={form.otherDescription} onChange={event=>update('otherDescription',event.target.value)}/></label>}<label>Invoice / Reference Number<input value={form.referenceNumber} onChange={event=>update('referenceNumber',event.target.value)}/></label><label>Receipt photo (optional)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>update('proof',event.target.files[0]||null)}/></label><footer><button type="button" className="secondary" onClick={close}>Cancel</button><button disabled={busy||!canSave}>{busy?'Saving…':'Save Expense'}</button></footer></form></div>}
