import {useEffect,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest} from './apiClient.js'
const words={zh:{open:'更正金额',title:'更正金额 / 更正记录',amount:'正确金额 (RM)',reason:'更正原因',save:'提交主管批准',close:'关闭',history:'更正记录',current:'当前金额',impact:'批准后备用金余额调整',admin:'公司费用：不影响员工备用金。',help:'提交后等待主管及以上批准，批准后才更新费用及备用金。',empty:'暂无更正记录。',loading:'读取中…',saved:'已提交，等待主管批准。',error:'无法完成，请重试。'},en:{open:'Correct amount',title:'Correct amount / History',amount:'Correct amount (RM)',reason:'Reason for correction',save:'Submit for approval',close:'Close',history:'Correction history',current:'Current amount',impact:'Cash float adjustment after approval',admin:'Company expense: employee cash float is unaffected.',help:'Amounts and cash float change only after supervisor approval.',empty:'No corrections yet.',loading:'Loading…',saved:'Submitted for supervisor approval.',error:'Unable to complete. Please retry.'},ms:{open:'Betulkan amaun',title:'Betulkan amaun / Sejarah',amount:'Amaun betul (RM)',reason:'Sebab pembetulan',save:'Hantar untuk kelulusan',close:'Tutup',history:'Sejarah pembetulan',current:'Amaun semasa',impact:'Pelarasan baki selepas kelulusan',admin:'Belanja syarikat: baki wang tunai pekerja tidak terjejas.',help:'Amaun dan baki hanya berubah selepas kelulusan penyelia.',empty:'Belum ada pembetulan.',loading:'Memuatkan…',saved:'Dihantar untuk kelulusan penyelia.',error:'Tidak dapat diselesaikan. Sila cuba lagi.'}}
const rm=c=>'RM '+(c/100).toFixed(2)
export default function ExpenseCorrection({item,onClose,onSaved,readOnly=false}){
 const {language}=useI18n(),w=words[language]||words.en,[data,setData]=useState(null),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false)
 const endpoint='/api/expenses/'+item.recordKey+'/corrections'
 useEffect(()=>{let alive=true;apiRequest(endpoint).then(d=>{if(alive){setData(d);setAmount((d.amountCents/100).toFixed(2))}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[endpoint])
 const valid=/^\d+(\.\d{1,2})?$/.test(amount)&&Number(amount)>0&&Number(amount)<=1000000&&reason.trim()&&Math.round(Number(amount)*100)!==data?.amountCents
 const save=async e=>{e.preventDefault();if(readOnly||busy||success||!valid)return;setBusy(true);setError('');setSuccess(false);try{const d=await apiRequest(endpoint,{method:'POST',body:JSON.stringify({amount,reason,expectedAmountCents:data.amountCents,revision:data.revision})});setData(d);setReason('');setSuccess(true);onSaved()}catch(e){setError(e.message||w.error)}finally{setBusy(false)}}
 return <div className="cash-modal" role="dialog" aria-modal="true" aria-label={w.title}><form onSubmit={save}><header><h2>{readOnly?w.history:w.title}</h2><button type="button" disabled={busy} onClick={onClose}>{w.close}</button></header><p data-i18n-raw>{item.serviceDate} · {item.employeeName} · {item.description} · {item.documentNumber||item.recordKey}</p>{!readOnly&&<p>{w.help}</p>}{error&&<p role="alert">{error}</p>}{success&&<p role="status">{w.saved}</p>}{!data&&!error&&<p>{w.loading}</p>}{data&&<><p>{w.current}: <b>{rm(data.amountCents)}</b></p>{!readOnly&&<><label>{w.amount}<input autoFocus required type="number" min="0.01" max="1000000" step="0.01" inputMode="decimal" value={amount} disabled={busy} onChange={e=>setAmount(e.target.value)}/></label><label>{w.reason}<textarea required maxLength={500} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><p>{data.employee?`${w.impact}: ${Number.isFinite(Number(amount))?rm(data.amountCents-Math.round(Number(amount)*100)):'—'}`:w.admin}</p><button type="submit" disabled={busy||success||!valid}>{w.save}</button></>}<h3>{w.history}</h3>{!data.history.length&&<p>{w.empty}</p>}{data.history.map(h=><article key={h.id}><p>{rm(h.oldAmountCents)} → {rm(h.newAmountCents)}</p><p data-i18n-raw>{h.reason}</p><small data-i18n-raw>{h.actorName} · {new Date(h.createdAt).toLocaleString(language==='zh'?'zh-MY':language==='ms'?'ms-MY':'en-MY',{timeZone:'Asia/Kuching'})}</small></article>)}</>}</form></div>
}
export function ExpenseCorrectionButton({onClick}){const{language}=useI18n();return <button type="button" onClick={onClick}>{(words[language]||words.en).open}</button>}
