import {useEffect,useState} from 'react'
import {apiRequest as api} from './apiClient.js'
import {useI18n} from './i18n.jsx'
import './FlexibleCollectionPanel.css'
export default function FlexibleCollectionPanel(){
 const {t}=useI18n(),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[zone,setZone]=useState(''),[options,setOptions]=useState({branches:[],trips:[]}),[branch,setBranch]=useState(''),[trip,setTrip]=useState(''),[search,setSearch]=useState(''),[success,setSuccess]=useState(false)
 const load=()=>api('/api/collection-access').then(setData)
 useEffect(()=>{let active=true;const refresh=()=>api('/api/collection-access').then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});refresh();const timer=setInterval(refresh,15000);return()=>{active=false;clearInterval(timer)}},[])
 useEffect(()=>{let active=true;setOptions({branches:[],trips:[]});setBranch('');setTrip('');setSuccess(false);if(zone)api(`/api/collection-access/${zone}/dispatch`).then(d=>{if(active)setOptions(d)}).catch(e=>active&&setError(e.message));return()=>{active=false}},[zone])
 const run=async work=>{setBusy(true);setError('');setSuccess(false);try{await work();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const dispatch=e=>{e.preventDefault();run(async()=>{await api('/api/collection-access/dispatch',{method:'POST',body:JSON.stringify({zoneId:Number(zone),branchId:Number(branch),tripId:Number(trip)})});setSuccess(true);setBranch('')})}
 return <section className="flexible-collection"><h3>{t('flex.title')}</h3><p>{t('flex.help')}</p>{error&&<p role="alert">{error}</p>}{data&&<><div className="flexible-zone-list">{data.items.map(z=><div key={z.id}><strong data-i18n-raw>{z.name}</strong><span>{t(z.isOpen&&z.active?'flex.open':'flex.closed')}</span>{data.canEdit&&<button type="button" role="switch" aria-checked={Boolean(z.isOpen&&z.active)} aria-label={`${t('flex.title')} ${z.name}`} disabled={busy||!z.active} onClick={()=>run(()=>api(`/api/collection-access/${z.id}`,{method:'PATCH',body:JSON.stringify({isOpen:!z.isOpen,revision:z.revision})}))}>{t(z.isOpen?'flex.close':'flex.enable')}</button>}</div>)}</div><details><summary>{t('flex.dispatch')}</summary><form onSubmit={dispatch}><label>{t('flex.zone')}<select required value={zone} onChange={e=>setZone(e.target.value)}><option value="">—</option>{data.items.filter(z=>z.isOpen&&z.active).map(z=><option key={z.id} value={z.id} data-i18n-raw>{z.name}</option>)}</select></label><label>{t('flex.search')}<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>{t('flex.customer')}<select required value={branch} onChange={e=>setBranch(e.target.value)}><option value="">—</option>{options.branches.filter(b=>`${b.company} ${b.name}`.toLowerCase().includes(search.toLowerCase())).map(b=><option key={b.id} value={b.id} data-i18n-raw>{b.company} · {b.name}</option>)}</select></label><label>{t('flex.vehicle')}<select required value={trip} onChange={e=>setTrip(e.target.value)}><option value="">—</option>{options.trips.map(r=><option key={r.id} value={r.id} data-i18n-raw>{r.plate} · {r.driverName} · {r.tripNumber}</option>)}</select></label>{zone&&!options.trips.length&&<p>{t('flex.noTrip')}</p>}<button disabled={busy||!branch||!trip||!data.items.some(z=>String(z.id)===zone&&z.isOpen&&z.active)}>{t('flex.send')}</button>{success&&<p role="status">{t('flex.sent')}</p>}</form></details></>}</section>
}
