import {useEffect,useState} from 'react'
import {downloadSpreadsheet,readSpreadsheet} from './spreadsheetFiles.js'
import {apiRequest as api} from './apiClient.js'
import {useI18n} from './i18n.jsx'

const labels={new:'New',unchanged:'Unchanged',conflict:'Conflict',branch_not_found:'Branch Not Found',invalid_gps:'Invalid GPS',duplicate_source:'Duplicate Source'}

export default function GpsMigrationPage(){
  const{t}=useI18n()
  const[batch,setBatch]=useState(null),[batches,setBatches]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
  const load=()=>api('/api/gps-migration/batches').then(x=>setBatches(x.items)).catch(e=>setError(e.message))
  useEffect(()=>{load()},[])
  const preview=async event=>{const file=event.target.files[0];if(!file)return;setBusy(true);setError('');try{const sheet=await readSpreadsheet(file);setBatch(await api('/api/gps-migration/preview',{method:'POST',body:JSON.stringify({fileName:file.name,rows:sheet.rows})}))}catch(e){setError(e.message)}finally{setBusy(false)}}
  const commit=async()=>{if(!confirm(t('gpsMigration.commitConfirm')))return;setBusy(true);try{setBatch(await api(`/api/gps-migration/batches/${batch.id}/commit`,{method:'POST',body:'{}'}));setMessage(t('gpsMigration.committed'));load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const resolve=async(row,decision)=>{const reason=prompt(t('gpsMigration.resolveReason'));if(reason==null)return;await api(`/api/gps-migration/rows/${row.id}/resolve`,{method:'POST',body:JSON.stringify({decision,reason})});setBatch(await api(`/api/gps-migration/batches/${batch.id}`))}
  const template=format=>downloadSpreadsheet({columns:['BranchID','CustomerID','Customer Name','Branch Name','Latitude','Longitude'],rows:[],fileName:'KCS_GPS_Migration_Template',label:'GPS Migration'},format)
  const exportReport=()=>downloadSpreadsheet({columns:['Row','BranchID','CustomerID','Customer Name','Branch Name','Old Latitude','Old Longitude','Imported Latitude','Imported Longitude','Classification','Decision','Decision Reason','Decided By','Decided At'],rows:batch.rows.map(row=>({'Row':row.row_number,'BranchID':row.branch_id_text,'CustomerID':row.customer_id_text,'Customer Name':row.customer_name,'Branch Name':row.branch_name,'Old Latitude':row.old_latitude,'Old Longitude':row.old_longitude,'Imported Latitude':row.latitude,'Imported Longitude':row.longitude,'Classification':labels[row.classification],'Decision':row.decision,'Decision Reason':row.decision_reason,'Decided By':row.decided_by,'Decided At':row.decided_at})),fileName:`KCS_GPS_Migration_Report_${batch.id}_${new Date().toISOString().replaceAll(':','-').slice(0,19)}`,label:'GPS Migration Report'},'xlsx')
  return <div className="page"><section className="welcome"><div><em>GPS MIGRATION</em><h1>{t('gpsMigration.title')}</h1><p>{t('gpsMigration.help')}</p></div><button onClick={template}>{t('gpsMigration.downloadTemplate')}</button></section>{error&&<div className="data-error">{error}</div>}{message&&<div className="data-loading">{message}</div>}<section className="master-toolbar"><label className="import-file">{t('gpsMigration.selectFile')}<input type="file" accept=".xlsx,.csv" onChange={preview}/></label><span>{busy?t('common.processing'):t('gpsMigration.previewOnly')}</span></section>{batch&&<><section className="stats gps-migration-stats">{Object.entries(labels).map(([key,label])=><article key={key}><span>{label}</span><strong>{batch.summary[key]||0}</strong></article>)}</section><div className="master-toolbar"><b data-i18n-raw>{batch.file_name} · {batch.status}</b><button onClick={exportReport}>{t('common.export')}</button>{batch.status!=='committed'&&<button onClick={commit} disabled={busy}>{t('common.confirm')}</button>}</div><div className="master-table"><table><thead><tr><th>Row</th><th>BranchID</th><th>Customer / Branch</th><th>{t('gps.official')}</th><th>{t('gps.temporary')}</th><th>{t('gps.category')}</th><th>{t('gps.decision')}</th></tr></thead><tbody>{batch.rows.map(row=><tr key={row.id} data-i18n-raw><td>{row.row_number}</td><td>{row.branch_id_text}</td><td>{row.customer_name}<small>{row.branch_name}</small></td><td>{row.old_latitude??'-'}, {row.old_longitude??'-'}</td><td>{row.latitude??'-'}, {row.longitude??'-'}</td><td><b>{labels[row.classification]}</b></td><td>{row.decision||(['conflict','duplicate_source'].includes(row.classification)?<><button onClick={()=>resolve(row,'keep_official')}>{t('gps.keepOfficial')}</button><button onClick={()=>resolve(row,'use_imported')}>{t('gps.adopt')}</button><button onClick={()=>resolve(row,'reject')}>{t('gps.reject')}</button></>:'—')}</td></tr>)}</tbody></table></div></>}{!batch&&<section className="panel"><h2>{t('gpsMigration.history')}</h2>{batches.map(item=><button className="history-row" key={item.id} data-i18n-raw onClick={()=>api(`/api/gps-migration/batches/${item.id}`).then(setBatch)}>{item.fileName}<span>{item.status} · {item.createdAt}</span></button>)}</section>}</div>
}
