import {useEffect,useState} from 'react'
import {downloadSpreadsheet,readSpreadsheet} from './spreadsheetFiles.js'

const labels={new:'New',unchanged:'Unchanged',conflict:'Conflict',branch_not_found:'Branch Not Found',invalid_gps:'Invalid GPS',duplicate_source:'Duplicate Source'}
const api=async(path,options={})=>{const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options}),data=await response.json();if(!response.ok)throw new Error(data.error||'操作失败');return data}

export default function GpsMigrationPage(){
  const[batch,setBatch]=useState(null),[batches,setBatches]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
  const load=()=>api('/api/gps-migration/batches').then(x=>setBatches(x.items)).catch(e=>setError(e.message))
  useEffect(load,[])
  const preview=async event=>{const file=event.target.files[0];if(!file)return;setBusy(true);setError('');try{const sheet=await readSpreadsheet(file);setBatch(await api('/api/gps-migration/preview',{method:'POST',body:JSON.stringify({fileName:file.name,rows:sheet.rows})}))}catch(e){setError(e.message)}finally{setBusy(false)}}
  const commit=async()=>{if(!confirm('只会写入没有 official GPS 的 New 记录。Conflict 不会自动覆盖，是否继续？'))return;setBusy(true);try{setBatch(await api(`/api/gps-migration/batches/${batch.id}/commit`,{method:'POST',body:'{}'}));setMessage('迁移已提交；Conflict 仍等待主管逐笔决定。');load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const resolve=async(row,decision)=>{const reason=prompt('请输入处理原因');if(reason==null)return;await api(`/api/gps-migration/rows/${row.id}/resolve`,{method:'POST',body:JSON.stringify({decision,reason})});setBatch(await api(`/api/gps-migration/batches/${batch.id}`))}
  const template=format=>downloadSpreadsheet({columns:['BranchID','CustomerID','Customer Name','Branch Name','Latitude','Longitude'],rows:[],fileName:'KCS_GPS_Migration_Template',label:'GPS Migration'},format)
  const exportReport=()=>downloadSpreadsheet({columns:['Row','BranchID','CustomerID','Customer Name','Branch Name','Old Latitude','Old Longitude','Imported Latitude','Imported Longitude','Classification','Decision','Decision Reason','Decided By','Decided At'],rows:batch.rows.map(row=>({'Row':row.row_number,'BranchID':row.branch_id_text,'CustomerID':row.customer_id_text,'Customer Name':row.customer_name,'Branch Name':row.branch_name,'Old Latitude':row.old_latitude,'Old Longitude':row.old_longitude,'Imported Latitude':row.latitude,'Imported Longitude':row.longitude,'Classification':labels[row.classification],'Decision':row.decision,'Decision Reason':row.decision_reason,'Decided By':row.decided_by,'Decided At':row.decided_at})),fileName:`KCS_GPS_Migration_Report_${batch.id}_${new Date().toISOString().replaceAll(':','-').slice(0,19)}`,label:'GPS Migration Report'},'xlsx')
  return <div className="page"><section className="welcome"><div><em>GPS MIGRATION</em><h1>Jodoo 旧 GPS 迁移</h1><p>按 BranchID 预览；冲突绝不自动覆盖正式 GPS。</p></div><button onClick={template}>下载模板</button></section>{error&&<div className="data-error">{error}</div>}{message&&<div className="data-loading">{message}</div>}<section className="master-toolbar"><label className="import-file">选择 XLSX / CSV<input type="file" accept=".xlsx,.csv" onChange={preview}/></label><span>{busy?'处理中…':'先预览，确认后才写入 SQLite'}</span></section>{batch&&<><section className="stats gps-migration-stats">{Object.entries(labels).map(([key,label])=><article key={key}><span>{label}</span><strong>{batch.summary[key]||0}</strong></article>)}</section><div className="master-toolbar"><b>{batch.file_name} · {batch.status}</b><button onClick={exportReport}>导出查核报告</button>{batch.status!=='committed'&&<button onClick={commit} disabled={busy}>确认迁移 New 记录</button>}</div><div className="master-table"><table><thead><tr><th>Row</th><th>BranchID</th><th>Customer / Branch</th><th>旧 GPS</th><th>导入 GPS</th><th>分类</th><th>决定</th></tr></thead><tbody>{batch.rows.map(row=><tr key={row.id}><td>{row.row_number}</td><td>{row.branch_id_text}</td><td>{row.customer_name}<small>{row.branch_name}</small></td><td>{row.old_latitude??'-'}, {row.old_longitude??'-'}</td><td>{row.latitude??'-'}, {row.longitude??'-'}</td><td><b>{labels[row.classification]}</b></td><td>{row.decision||(['conflict','duplicate_source'].includes(row.classification)?<><button onClick={()=>resolve(row,'keep_official')}>保留正式</button><button onClick={()=>resolve(row,'use_imported')}>采用导入</button><button onClick={()=>resolve(row,'reject')}>拒绝</button></>:'—')}</td></tr>)}</tbody></table></div></>}{!batch&&<section className="panel"><h2>历史批次</h2>{batches.map(item=><button className="history-row" key={item.id} onClick={()=>api(`/api/gps-migration/batches/${item.id}`).then(setBatch)}>{item.fileName}<span>{item.status} · {item.createdAt}</span></button>)}</section>}</div>
}
