import { useCallback, useEffect, useState } from 'react'
import { downloadSpreadsheet, readSpreadsheet } from './spreadsheetFiles.js'
import './MasterDataPage.css'

const api=async(url,options={})=>{const response=await fetch(url,{headers:{'Content-Type':'application/json'},...options}),data=await response.json();if(!response.ok)throw new Error(data.error||'操作失败');return data}
const actor={changedBy:'LSK',actorRole:'supervisor'}
const modules=[['customer','Customer'],['branch','Customer Branch'],['zone','Zone'],['area','Area'],['gps','GPS'],['buyer','Buyer'],['operational_location','Operational Location']]
const customerFields=[['customerId','Customer ID','text',true],['customerName','Customer Name','text',true],['legalName','Legal Name'],['registrationNumber','Registration Number'],['billingAddress','Billing Address','textarea'],['contactPerson','Contact Person'],['phone','Phone'],['whatsapp','WhatsApp'],['email','Email','email'],['defaultPaymentType','Default Payment Type','select',['','Cash','Credit']],['creditTerms','Credit Terms'],['status','Status','select',['active','paused','closed']],['notes','Notes','textarea']]
const branchFields=[['branchId','Branch ID','text',true],['customerId','Customer ID','text',true],['branchName','Branch Name','text',true],['address','Address','textarea'],['zoneGroup','Zone Group（由 Area 决定）','readonly'],['areaId','Area ID'],['officialLatitude','Official Latitude','readonly'],['officialLongitude','Official Longitude','readonly'],['temporaryLatitude','Latest Temporary Latitude','readonly'],['temporaryLongitude','Latest Temporary Longitude','readonly'],['gpsVerificationStatus','GPS Verification Status','readonly'],['contactPerson','Contact Person'],['phone','Phone'],['collectionFrequency','Collection Frequency'],['assignedWeekdays','Assigned Weekdays'],['collectionTimeConstraint','Collection Time Constraint'],['occPrice','OCC Price','number'],['paymentType','Payment Type','select',['','Cash','Credit']],['proofRequirements','Proof Requirements','textarea'],['vehicleRestriction','Vehicle Restriction'],['status','Status','select',['active','paused','closed']],['notes','Notes','textarea']]
const buyerFields=[['buyerId','Buyer ID','text',true],['buyerName','Buyer Name','text',true],['locationName','Location Name'],['address','Address','textarea'],['officialLatitude','Official Latitude','number'],['officialLongitude','Official Longitude','number'],['contactPerson','Contact Person'],['phone','Phone'],['materialAccepted','Material Accepted'],['operatingHours','Operating Hours'],['unloadingRestrictions','Unloading Restrictions','textarea'],['pricingNotes','Pricing Notes','textarea'],['status','Status','select',['active','paused','closed']],['notes','Notes','textarea']]
const locationFields=[['locationId','Location ID','text',true],['name','Location Name','text',true],['locationType','Location Type','select',['Company Yard','Buyer','Employee Base','Workshop','Fuel Station','Other']],['address','Address','textarea'],['latitude','Latitude','number'],['longitude','Longitude','number'],['operatingHours','Operating Hours'],['contactPerson','Contact Person'],['phone','Phone'],['buyerId','Buyer ID'],['status','Status','select',['active','paused','closed']],['notes','Notes','textarea']]

export default function MasterDataPage(){
  const[tab,setTab]=useState('customers'),[closeout,setCloseout]=useState(null),[reload,setReload]=useState(0),[message,setMessage]=useState(''),[error,setError]=useState('')
  const refresh=()=>setReload(value=>value+1);useEffect(()=>{api('/api/master/area-closeout').then(setCloseout).catch(item=>setError(item.message))},[reload])
  return <div className="page master-data-page"><div className="data-title"><em>KCS MASTER DATA</em><h1>Customer Master & Operational Locations</h1><p>KCS 是客户与营运地点主档；Jodoo 暂时只继续用于开单。所有关键修改保留审计，并保护已批准路线。</p></div>
    {closeout&&<section className="area-closeout"><div><strong>{closeout.confirmedAreas}</strong><span>已确认 Area</span></div><div className={closeout.pendingAreas?'warning':''}><strong>{closeout.pendingAreas}</strong><span>待确认 Area</span></div><div><strong>{closeout.totalAreas}</strong><span>Area 总数</span></div><aside>{closeout.zones.map(zone=><span key={zone.id}>{zone.name} <b>{zone.areaCount}</b></span>)}</aside><ExportButton module="area" label="导出 Area-Zone Mapping"/></section>}
    {message&&<div className="planner-message">✓ {message}</div>}{error&&<div className="data-error">{error}</div>}
    <nav className="master-nav">{[['customers','Customer'],['branches','Branch'],['gps','GPS Collector'],['buyers','Buyer'],['locations','Operational Location'],['transfer','Import / Export']].map(item=><button key={item[0]} className={tab===item[0]?'active':''} onClick={()=>{setTab(item[0]);setError('');setMessage('')}}>{item[1]}</button>)}</nav>
    {tab==='customers'?<EntityManager key={`c${reload}`} type="customer" endpoint="/api/customers" fields={customerFields} reload={refresh} notify={setMessage} fail={setError}/>:tab==='branches'?<EntityManager key={`b${reload}`} type="branch" endpoint="/api/master/branches" fields={branchFields} reload={refresh} notify={setMessage} fail={setError}/>:tab==='gps'?<GpsCollector reload={reload} refresh={refresh} notify={setMessage} fail={setError}/>:tab==='buyers'?<EntityManager key={`y${reload}`} type="buyer" endpoint="/api/buyers" fields={buyerFields} reload={refresh} notify={setMessage} fail={setError}/>:tab==='locations'?<EntityManager key={`l${reload}`} type="operational_location" endpoint="/api/operational-locations" fields={locationFields} reload={refresh} notify={setMessage} fail={setError}/>:<TransferPanel notify={setMessage} fail={setError}/>}</div>
}

function EntityManager({type,endpoint,fields,reload,notify,fail}){
  const[items,setItems]=useState([]),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[editing,setEditingState]=useState(null),[loading,setLoading]=useState(true)
  const load=useCallback(()=>{setLoading(true);const q=new URLSearchParams({search,status,pageSize:'200'});api(`${endpoint}?${q}`).then(data=>setItems(data.items||[])).catch(item=>fail(item.message)).finally(()=>setLoading(false))},[endpoint,search,status,fail]);useEffect(()=>{const timer=setTimeout(load,200);return()=>clearTimeout(timer)},[load,reload])
  const idKey=type==='customer'?'customerId':type==='branch'?'branchId':type==='buyer'?'buyerId':'id',setEditing=item=>{if(!item||!item[idKey]||(type!=='customer'&&type!=='branch'))return setEditingState(item);api(`${endpoint}/${encodeURIComponent(item[idKey])}`).then(setEditingState).catch(error=>fail(error.message))},save=async form=>{const isEdit=Boolean(editing),routeId=type==='buyer'?editing?.id:editing?.[idKey],url=isEdit?`${endpoint}/${encodeURIComponent(routeId)}`:endpoint,method=isEdit?'PATCH':'POST';try{await api(url,{method,body:JSON.stringify({...form,...actor,reason:'Customer Master supervisor update'})});setEditing(null);notify(`${type} 已保存；关键资料变化会要求相关路线重新批准。`);load()}catch(item){fail(item.message)}}
  return <section className="master-workspace"><header><div><h2>{type==='customer'?'Customer Master':type==='branch'?'Customer Branch Master':type==='buyer'?'Buyer Master':'Operational Location Master'}</h2><p>不物理删除历史资料；使用 Pause、Resume 或 Close 管理状态。</p></div><button className="primary" onClick={()=>setEditing({status:'active',locationType:type==='operational_location'?'Other':undefined})}>＋ 新增</button></header><div className="master-filters"><input placeholder="搜索编号、名称、电话或地址" value={search} onChange={event=>setSearch(event.target.value)}/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">全部状态</option><option value="active">Active</option><option value="paused">Paused</option><option value="closed">Closed</option></select><ExportButton module={type} search={search}/></div>{loading?<div className="data-loading">主档载入中…</div>:<div className="master-record-grid">{items.map(item=><article key={item[idKey]||item.id}><div><span className={`master-status ${item.status}`}>{item.status}</span><h3>{type==='customer'?item.customerName:type==='branch'?item.branchName:type==='buyer'?item.buyerName:item.name}</h3><b>{item[idKey]||item.locationId}</b></div><p>{type==='customer'?`${item.branchCount} Branch · ${item.phone||'无电话'} · ${item.defaultPaymentType||'未设付款方式'}`:type==='branch'?`${item.customerName||item.customerId} · ${item.area||'未设 Area'} · ${item.paymentType||'未设付款方式'} · ${item.occPrice??'未设价格'}`:type==='buyer'?`${item.locationName||'未设地点'} · ${item.materialAccepted||'未设物料'}`:`${item.locationType} · ${item.address||'未设地址'}`}</p><small>{item.notes||'无备注'}</small><footer><button onClick={()=>setEditing(item)}>查看 / 编辑</button>{item.status!=='active'&&<button onClick={()=>save({...item,status:'active'})}>恢复</button>}{item.status==='active'&&<button onClick={()=>save({...item,status:'paused'})}>暂停</button>}{item.status!=='closed'&&<button className="danger-text" onClick={()=>save({...item,status:'closed'})}>关闭</button>}</footer></article>)}</div>}{editing&&<Editor title={`${editing[idKey]||editing.id?'编辑':'新增'} ${type}`} fields={fields} initial={editing} lockId={Boolean(editing[idKey]||editing.id)} onClose={()=>setEditing(null)} onSave={save}/>}</section>
}

function Editor({title,fields,initial,lockId,onClose,onSave}){const[form,setForm]=useState(initial);return <div className="master-modal"><form onSubmit={event=>{event.preventDefault();onSave(form)}}><header><h2>{title}</h2><button type="button" onClick={onClose}>×</button></header><div className="editor-fields">{fields.map(([key,label,type='text',options])=><label key={key}>{label}{type==='textarea'?<textarea value={form[key]??''} onChange={event=>setForm({...form,[key]:event.target.value})}/>:type==='select'?<select value={form[key]??''} onChange={event=>setForm({...form,[key]:event.target.value})}>{options.map(option=><option key={option} value={option}>{option||'—'}</option>)}</select>:<input required={options===true} disabled={type==='readonly'||(lockId&&(key.endsWith('Id')||key==='locationId'))} type={type==='readonly'?'text':type} step={type==='number'?'any':undefined} value={form[key]??''} onChange={event=>setForm({...form,[key]:type==='number'&&event.target.value!==''?Number(event.target.value):event.target.value})}/>}</label>)}</div>{initial.audit?.length>0&&<section className="audit-timeline"><h3>审计记录</h3>{initial.audit.slice(0,20).map(item=><p key={item.id}><b>{item.changeType}</b><span>{item.changedBy} · {item.changedAt}</span><small>{item.reason||'未填写原因'}</small></p>)}</section>}<footer><button type="button" onClick={onClose}>取消</button><button className="primary">保存</button></footer></form></div>}

function GpsCollector({reload,refresh,notify,fail}){const[search,setSearch]=useState(''),[branches,setBranches]=useState([]),[branchId,setBranchId]=useState(''),[gps,setGps]=useState({latitude:'',longitude:'',locationSource:'Driver Captured',reason:''}),[items,setItems]=useState([])
  useEffect(()=>{if(search.length<2)return setBranches([]);const timer=setTimeout(()=>api(`/api/master/branches?search=${encodeURIComponent(search)}&pageSize=20`).then(data=>setBranches(data.items)).catch(item=>fail(item.message)),250);return()=>clearTimeout(timer)},[search,fail]);useEffect(()=>{api('/api/gps-collector').then(data=>setItems(data.items)).catch(item=>fail(item.message))},[reload,fail])
  const capture=async event=>{event.preventDefault();try{await api(`/api/gps-collector/branch/${encodeURIComponent(branchId)}`,{method:'POST',body:JSON.stringify({...gps,latitude:Number(gps.latitude),longitude:Number(gps.longitude),capturedBy:'LSK'})});notify('GPS 已保存为 temporary GPS，不会覆盖 official GPS。');refresh()}catch(item){fail(item.message)}}
  const adopt=async item=>{const reason=prompt('采用为 official GPS 的理由','主管现场资料确认');if(!reason)return;try{const result=await api(`/api/gps-collector/${item.id}/adopt`,{method:'POST',body:JSON.stringify({adoptedBy:'LSK',reason})});notify(result.distanceWarning?'已采用为 official GPS；与旧位置距离较大，请再次核对。':'已采用为 official GPS，并保存旧 GPS、新 GPS 与审批记录。');refresh()}catch(error){fail(error.message)}}
  return <section className="master-workspace gps-collector"><header><div><h2>GPS Collector</h2><p>员工先选择 Branch；采集结果一律先进入 temporary GPS，主管审批后才写入 official GPS。</p></div></header><form onSubmit={capture}><label>搜索 Customer Branch<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Customer、Branch、BranchID、电话或地址"/></label><label>选择 Branch<select required value={branchId} onChange={event=>setBranchId(event.target.value)}><option value="">请选择</option>{branches.map(item=><option key={item.branchId} value={item.branchId}>{item.branchId} — {item.customerName} / {item.branchName}</option>)}</select></label><label>Latitude<input required type="number" step="any" value={gps.latitude} onChange={event=>setGps({...gps,latitude:event.target.value})}/></label><label>Longitude<input required type="number" step="any" value={gps.longitude} onChange={event=>setGps({...gps,longitude:event.target.value})}/></label><label>来源<select value={gps.locationSource} onChange={event=>setGps({...gps,locationSource:event.target.value})}>{['Driver Captured','Customer WhatsApp','Customer Phone','Manual Entry','Supervisor Confirmed'].map(item=><option key={item}>{item}</option>)}</select></label><button className="primary">保存 temporary GPS</button></form><div className="gps-queue">{items.map(item=><article key={item.id}><div><b>{item.branchId} · {item.branchName}</b><span>{item.customerName}</span></div><p>Temporary: {item.temporaryLatitude}, {item.temporaryLongitude}<br/>Official: {item.officialLatitude??'—'}, {item.officialLongitude??'—'}</p><small>{item.locationSource} · {item.verificationStatus} · {item.capturedBy}</small>{!item.adoptedAt&&<button onClick={()=>adopt(item)}>采用为 official GPS</button>}</article>)}</div></section>}

function ExportButton({module,label='导出资料',search=''}){const[busy,setBusy]=useState(false);const run=async format=>{setBusy(true);try{const data=await api(`/api/master-transfer/${module}/export?format=${format}&search=${encodeURIComponent(search)}&changedBy=LSK`);await downloadSpreadsheet(data,format)}finally{setBusy(false)}};return <span className="export-buttons"><button disabled={busy} onClick={()=>run('xlsx')}>{label} XLSX</button><button disabled={busy} onClick={()=>run('csv')}>CSV</button></span>}

function TransferPanel({notify,fail}){const[module,setModule]=useState('customer'),[file,setFile]=useState(null),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[logs,setLogs]=useState([]);const label=modules.find(item=>item[0]===module)?.[1]
  const loadLogs=useCallback(()=>api('/api/master-transfer/logs').then(data=>setLogs(data.items)).catch(item=>fail(item.message)),[fail]);useEffect(()=>{loadLogs()},[loadLogs])
  const template=async format=>{const data=await api(`/api/master-transfer/${module}/template`);await downloadSpreadsheet(data,format)}
  const previewFile=async()=>{if(!file)return;setBusy(true);try{const parsed=await readSpreadsheet(file),data=await api('/api/master-transfer/preview',{method:'POST',body:JSON.stringify({module,fileName:file.name,fileFormat:parsed.format,sheetName:parsed.sheetName,rows:parsed.rows,changedBy:'LSK'})});setPreview(data);notify('预览完成。只有按“确认导入”后才会写入 SQLite。')}catch(item){fail(item.message)}finally{setBusy(false)}}
  const commit=async()=>{setBusy(true);try{await api('/api/master-transfer/commit',{method:'POST',body:JSON.stringify({batchId:preview.batchId,changedBy:'LSK'})});notify('导入事务已完成；重复导入不会产生重复记录。');setPreview(null);setFile(null);loadLogs()}catch(item){fail(item.message)}finally{setBusy(false)}}
  const exportErrors=async()=>{const data=await api(`/api/import-batches/${preview.batchId}/errors`);await downloadSpreadsheet({columns:['rowNumber','entityType','externalId','severity','code','message'],rows:data.items,fileName:`KCS_Import_Errors_${preview.batchId}`,label:'Import Errors'},'xlsx')}
  return <section className="master-workspace transfer-panel"><header><div><h2>Excel / CSV Import & Export</h2><p>下载模板 → 填写 → 预览 → 确认导入。任何错误都会阻止写入，确保原资料不受破坏。</p></div></header><div className="transfer-tools"><label>模块<select value={module} onChange={event=>{setModule(event.target.value);setPreview(null)}}>{modules.map(item=><option key={item[0]} value={item[0]}>{item[1]}</option>)}</select></label><button onClick={()=>template('xlsx')}>下载 {label} XLSX 空白模板</button><button onClick={()=>template('csv')}>下载 CSV 模板</button><ExportButton module={module} label="导出全部"/></div><div className="file-drop"><input type="file" accept=".xlsx,.csv" onChange={event=>{setFile(event.target.files[0]);setPreview(null)}}/><b>{file?.name||'请选择 .xlsx 或 .csv'}</b><button className="primary" disabled={!file||busy} onClick={previewFile}>导入前预览</button></div>{preview&&<><div className="preview-stats">{Object.entries(preview.summary).map(([key,value])=><div key={key} className={key==='error'&&value?'bad':''}><strong>{value}</strong><span>{key}</span></div>)}</div>{preview.errors.length>0&&<div className="transfer-errors"><b>发现 {preview.errors.length} 个错误，必须修正后重新预览。</b><button onClick={exportErrors}>导出错误 XLSX</button>{preview.errors.slice(0,8).map(item=><p key={item.rowNumber}>Row {item.rowNumber}: {item.message}</p>)}</div>}<div className="table-wrap"><table><thead><tr><th>Row</th><th>ID</th><th>Action</th><th>Preview</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.externalId}</td><td><span className={`import-action ${row.action}`}>{row.action}</span></td><td>{JSON.stringify(row.normalized)}</td></tr>)}</tbody></table></div><button className="primary commit-import" disabled={busy||preview.summary.error>0} onClick={commit}>确认导入 SQLite</button></>}<h3>最近导入 / 导出记录</h3><div className="transfer-log">{logs.map(item=><p key={item.id}><b>{item.operationType}</b> {item.module} · {item.fileName||'—'} · {item.performedBy} · {item.performedAt}</p>)}</div></section>}
