import {useCallback,useEffect,useState} from 'react'
import {apiRequest as api} from './apiClient.js'

const money=value=>`RM${Number(value).toFixed(2)}/kg`

export default function MaterialsPricesPage({currentUser,notify,fail}){
  const[materials,setMaterials]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true)
  const canManage=['owner_admin','operations_admin'].includes(currentUser.systemRole)||currentUser.permissions?.includes('price_manage')
  const load=useCallback(async()=>{setLoading(true);try{const data=await api('/api/materials?includeInactive=true');setMaterials(data.items)}catch(error){fail(error.message)}finally{setLoading(false)}},[fail])
  useEffect(()=>{void load()},[load])
  const open=async material=>{try{setSelected(await api(`/api/materials/${material.id}`))}catch(error){fail(error.message)}}
  const addMaterial=async()=>{const materialName=prompt('Material Name');if(!materialName)return;const materialCode=prompt('Material Code',materialName.toUpperCase().replace(/[^A-Z0-9]+/g,'_'));if(!materialCode)return;try{await api('/api/materials',{method:'POST',body:JSON.stringify({materialName,materialCode,unit:'kg'})});notify('Material 已建立。');await load()}catch(error){fail(error.message)}}
  const addLevel=async()=>{const priceAmount=prompt('New price (RM/kg)');if(priceAmount===null)return;const effectiveDate=prompt('Effective Date (YYYY-MM-DD)',new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kuching'}));const reason=prompt('Modification reason');if(!effectiveDate||!reason)return;try{await api(`/api/materials/${selected.id}/price-levels`,{method:'POST',body:JSON.stringify({priceAmount:Number(priceAmount),effectiveDate,reason})});notify('Price Level 已建立。');await open(selected)}catch(error){fail(error.message)}}
  const bulk=async level=>{const newPrice=prompt(`将 ${money(level.priceAmount)} 调整为（RM/kg）`);if(newPrice===null)return;const effectiveDate=prompt('New Effective Date (YYYY-MM-DD)',new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kuching'}));const reason=prompt('必须填写修改原因');if(!effectiveDate||!reason)return;if(!confirm(`二次确认：${level.affectedBranchCount} 个分店将从 ${money(level.priceAmount)} 调整为 ${money(newPrice)}。继续？`))return;try{const result=await api(`/api/price-levels/${level.id}/bulk-update`,{method:'POST',body:JSON.stringify({newPrice:Number(newPrice),effectiveDate,reason,confirmed:true})});notify(`批量调价完成，影响 ${result.affectedBranchCount} 个分店。`);await open(selected)}catch(error){fail(error.message)}}
  const toggle=async level=>{const status=level.status==='active'?'inactive':'active',reason=prompt(`请输入${status==='inactive'?'停用':'重新启用'}原因`);if(!reason)return;try{await api(`/api/price-levels/${level.id}/status`,{method:'PATCH',body:JSON.stringify({status,reason})});notify('Price Level 状态已更新。');await open(selected)}catch(error){fail(error.message)}}
  if(selected)return <section className="master-workspace material-prices"><header><div><button className="link-button" onClick={()=>setSelected(null)}>← Materials</button><h2>{selected.materialName}</h2><p>{selected.materialCode} · Unit: {selected.unit} · {selected.branches.length} Branches</p></div>{canManage&&<button className="primary" onClick={addLevel}>＋ 新增 Price Level</button>}</header><div className="price-level-grid">{selected.priceLevels.map(level=><article key={level.id} className={level.status}><strong>{money(level.priceAmount)}</strong><span>{level.status} · Effective {level.effectiveDate}</span><small>{level.affectedBranchCount} affected Branches · {level.reason||'No reason'}</small>{canManage&&<footer><button onClick={()=>bulk(level)}>批量调价</button><button onClick={()=>toggle(level)}>{level.status==='active'?'停用':'启用'}</button></footer>}</article>)}</div><h3>受影响分店名单</h3><div className="table-wrap"><table><thead><tr><th>BranchID</th><th>Customer / Branch</th><th>Current Price</th><th>Source</th></tr></thead><tbody>{selected.branches.map(item=><tr key={item.branchId}><td>{item.branchId}</td><td>{item.customerName} / {item.branchName}</td><td>{money(item.currentPrice)}</td><td>{item.specialPrice!=null?'Special Price':'Price Level'}</td></tr>)}</tbody></table></div></section>
  return <section className="master-workspace material-prices"><header><div><h2>Materials & Prices</h2><p>第一层只显示 Material。选择 Material 后才管理该货物的 Price Levels。</p></div>{canManage&&<button className="primary" onClick={addMaterial}>＋ 新增 Material</button>}</header>{loading?<div className="data-loading">载入中…</div>:<div className="material-grid">{materials.map(material=><button key={material.id} onClick={()=>open(material)}><strong>{material.materialName}</strong><span>{material.priceLevelCount} Price Levels</span><small>{material.branchCount} Branches · {material.status}</small></button>)}</div>}{!canManage&&<p className="permission-note">当前账号只可查看货物与价格。价格管理需要 Administrator 或获授权 Supervisor。</p>}</section>
}
