import {useEffect,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest} from './apiClient.js'
import CustomerReceipt from './CustomerReceipt.jsx'
import ProofViewer from './ProofViewer.jsx'
const words={en:{title:'My bills',help:'View only bills you issued. No changes can be made here.',today:'Today',yesterday:'Yesterday',all:'All dates',search:'Bill number / Customer',previous:'Previous',next:'Next',empty:'No bills found.'},ms:{title:'Bil saya',help:'Lihat bil yang anda keluarkan sahaja. Tiada perubahan boleh dibuat di sini.',today:'Hari ini',yesterday:'Semalam',all:'Semua tarikh',search:'Nombor bil / Pelanggan',previous:'Sebelumnya',next:'Seterusnya',empty:'Tiada bil ditemui.'},zh:{title:'我的单据',help:'只查看自己开出的单据，这里不能修改。',today:'今天',yesterday:'昨天',all:'全部日期',search:'单号 / 客户名称',previous:'上一页',next:'下一页',empty:'没有找到单据。'}}
export const myBillsWords=words
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuching',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
export default function MyBillsPage({onBack}){
 const {language,t}=useI18n(),l=words[language]||words.en,[range,setRange]=useState({from:today(),to:today()}),[search,setSearch]=useState(''),[page,setPage]=useState(0),[data,setData]=useState(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0)
 const query=new URLSearchParams({...range,search,page}).toString()
 useEffect(()=>{let active=true;setData(null);setError('');apiRequest('/api/mobile/my-bills?'+query).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[query,refresh])
 const choose=day=>{setPage(0);setRange({from:day,to:day})}
 return <section className="bill-void-page"><div className="bill-void-toolbar"><button type="button" data-preview-safe title={t('common.back')} aria-label={t('common.back')} onClick={onBack}>←</button><h1>{l.title}</h1><button data-preview-safe onClick={()=>setRefresh(n=>n+1)}>{t('void.refresh')}</button></div><p>{l.help}</p><div className="bill-void-toolbar"><button data-preview-safe onClick={()=>choose(today())}>{l.today}</button><button data-preview-safe onClick={()=>choose(new Date(Date.parse(today()+'T00:00:00Z')-86400000).toISOString().slice(0,10))}>{l.yesterday}</button><button data-preview-safe onClick={()=>choose('')}>{l.all}</button></div>{['from','to'].map(k=><label key={k}>{t('sales.'+k)}<input type="date" value={range[k]} min={k==='to'?range.from:undefined} max={k==='from'?range.to:undefined} onChange={e=>{setPage(0);setRange({...range,[k]:e.target.value})}}/></label>)}<label>{l.search}<input value={search} onChange={e=>{setPage(0);setSearch(e.target.value)}}/></label>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p>{t('void.loading')}</p>}{data&&!data.items.length&&<p>{l.empty}</p>}{data?.items.map(b=><article className="bill-void-card" key={b.id}><h2 data-i18n-raw>{b.billNumber}</h2><p data-i18n-raw>{b.serviceDate} · {b.customerName} · {b.branchName}</p><p data-i18n-raw>{b.registrationNumber||b.vehicleCode} · RM {(b.totalCents/100).toFixed(2)}</p><p>{t('void.'+b.status)} · {t('void.'+b.paymentMethod)}</p><div className="bill-void-toolbar"><CustomerReceipt bill={b}/>{b.hasProof?<ProofViewer url={'/api/mobile/my-bills/'+b.id+'/proof'}>{t('void.proof')}</ProofViewer>:null}</div></article>)}<div className="bill-void-toolbar"><button data-preview-safe disabled={!page} onClick={()=>setPage(p=>p-1)}>{l.previous}</button><button data-preview-safe disabled={!data?.hasMore} onClick={()=>setPage(p=>p+1)}>{l.next}</button></div></section>
}
