export const newPricingWords={
 zh:{title:'新客户收购商品及价格',help:'单一有效价格已自动选择；OCC 和多个价格的商品请分别选择。',choose:'请选择价格',missing:'未设置有效价格：暂不能用于开单',automatic:'自动带入',required:'必须选择',unavailable:'没有可用商品，请先设置商品及价格。',loading:'正在读取商品价格…',denied:'需要有价格管理权限的人员完成价格选择。'},
 en:{title:'New customer products and prices',help:'Single valid prices are selected automatically. Choose a price for OCC and products with multiple prices.',choose:'Select a price',missing:'No valid price: unavailable for billing',automatic:'Selected automatically',required:'Selection required',unavailable:'No available products. Configure products and prices first.',loading:'Loading product prices…',denied:'A user with pricing permission must complete price selection.'},
 ms:{title:'Produk dan harga pelanggan baharu',help:'Harga sah tunggal dipilih secara automatik. Pilih harga OCC dan produk yang mempunyai beberapa harga.',choose:'Pilih harga',missing:'Tiada harga sah: belum boleh digunakan dalam bil',automatic:'Dipilih secara automatik',required:'Wajib pilih',unavailable:'Tiada produk tersedia. Tetapkan produk dan harga dahulu.',loading:'Memuatkan harga produk…',denied:'Pengguna dengan kebenaran harga perlu melengkapkan pilihan harga.'}
}
export default function NewCustomerPricing({catalog,values,onChange,language,disabled,canManagePricing}){
 const w=newPricingWords[language]||newPricingWords.en
 return <section className="branch-materials customer-pricing customer-workspace-card"><h3>{w.title}</h3><p>{w.help}</p>{!catalog?<p>{w.loading}</p>:!catalog.length?<p>{w.unavailable}</p>:catalog.map(p=><article key={p.productId}><label><b data-i18n-raw>{p.name} ({p.unit})</b>{p.prices.length?<><select data-i18n-raw required aria-label={p.name} disabled={disabled||!canManagePricing} value={values.find(v=>v.productId===p.productId)?.standardPriceLevelId||''} onChange={e=>onChange(p.productId,Number(e.target.value))}><option value="">{w.choose}</option>{p.prices.map(l=><option key={l.id} value={l.id}>RM {Number(l.price).toFixed(3)}</option>)}</select><small>{p.requiresChoice?w.required:w.automatic}</small></>:<p role="status">{w.missing}</p>}</label></article>)}{!canManagePricing&&<p>{w.denied}</p>}</section>
}
