import {DriverGuidePopup} from './DriverGuide.jsx'
import NoticeArchive from './NoticeArchive.jsx'
import {createContext,useCallback,useContext,useEffect,useRef,useState} from 'react'
import {apiRequest as api} from './apiClient.js'
import {useI18n} from './i18n.jsx'
import './NoticeBoard.css'
const NoticeContext=createContext(null)
const dateLabel=value=>new Date(value).toLocaleString('en-GB',{timeZone:'Asia/Kuching'})
function NoticeText({item}){const{t}=useI18n();return <><span className={'notice-priority '+item.priority}>{t('notice.'+item.priority)}</span><h3 data-i18n-raw>{item.title}</h3><p className="notice-body" data-i18n-raw>{item.body}</p><small><span data-i18n-raw>{item.publisherName}</span> · {dateLabel(item.createdAt)}</small></>}
function UnreadPopup({item,remaining,onRead}){
 const{t}=useI18n(),ref=useRef(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{const d=ref.current,previous=document.activeElement;if(d.showModal)d.showModal();else d.setAttribute('open','');return()=>{if(d.close)d.close();previous?.focus?.()}},[])
 const read=async()=>{setBusy(true);setError('');try{await onRead(item.id)}catch(e){setError(e.message);setBusy(false)}}
 return <dialog ref={ref} className="notice-popup" aria-labelledby="notice-popup-title" onCancel={e=>e.preventDefault()}><h2 id="notice-popup-title">{t('notice.new')} ({remaining})</h2><NoticeText item={item}/>{error&&<p role="alert">{error}</p>}<button autoFocus className="notice-primary" disabled={busy} onClick={read}>{t(busy?'common.processing':'notice.acknowledge')}</button></dialog>
}
export function NoticeMobileProvider({children}){
 const{t}=useI18n(),[items,setItems]=useState([]),[guide,setGuide]=useState(null),guideRead=useRef(new Map()),[error,setError]=useState(''),acknowledged=useRef(new Map()),generation=useRef(0)
 const load=useCallback(async()=>{const g=++generation.current;const [r,nextGuide]=await Promise.all([api('/api/mobile/notices'),api('/api/mobile/guide')]);if(g!==generation.current)return;setGuide({...nextGuide,readAt:nextGuide.readAt||guideRead.current.get(nextGuide.version)||null});setItems(r.items.map(i=>({...i,readAt:i.readAt||acknowledged.current.get(i.id)||null})));setError('')},[])
 useEffect(()=>{let alive=true;const refresh=()=>{if(document.visibilityState==='hidden')return;load().catch(e=>{if(alive)setError(e.message)})};void refresh();const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);window.addEventListener('online',refresh);document.addEventListener('visibilitychange',refresh);return()=>{alive=false;generation.current++;clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('online',refresh);document.removeEventListener('visibilitychange',refresh)}},[load])
 const read=async id=>{const r=await api(`/api/mobile/notices/${id}/read`,{method:'POST',body:'{}'});acknowledged.current.set(id,r.readAt);setItems(current=>current.map(i=>i.id===id?{...i,readAt:r.readAt}:i))}
 const readGuide=async()=>{const r=await api('/api/mobile/guide/read',{method:'POST',body:JSON.stringify({version:guide.version})});guideRead.current.set(r.version,r.readAt);setGuide(r)}
 const showGuide=guide?.active&&!guide.readAt
 const unread=items.filter(i=>!i.readAt).sort((a,b)=>Number(b.priority==='urgent')-Number(a.priority==='urgent')||a.id-b.id)
 return <NoticeContext.Provider value={{items,error,load}}>{children}{error&&<div className="notice-load-error" role="alert">{t('notice.loadFailed')} <button onClick={()=>load().catch(e=>setError(e.message))}>{t('notice.refresh')}</button></div>}{showGuide?<DriverGuidePopup key={guide.version} onRead={readGuide}/>:unread[0]&&<UnreadPopup key={unread[0].id} item={unread[0]} remaining={unread.length} onRead={read}/>}</NoticeContext.Provider>
}
export function NoticeHistory(){
 const{t}=useI18n(),{items,error,load}=useContext(NoticeContext),[search,setSearch]=useState(''),[refreshError,setRefreshError]=useState('')
 return <section className="notice-board"><header><h1>{t('notice.title')}</h1><button onClick={()=>load().then(()=>setRefreshError('')).catch(e=>setRefreshError(e.message))}>{t('notice.refresh')}</button></header><label>{t('notice.search')}<input value={search} onChange={e=>setSearch(e.target.value)}/></label>{(error||refreshError)&&<p role="alert">{error||refreshError}</p>}{!items.length&&<p>{t('notice.empty')}</p>}{items.filter(i=>(i.title+' '+i.body).toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(i=><article key={i.id}><NoticeText item={i}/><p>{t(i.readAt?'notice.read':'notice.unread')}{i.readAt&&<> · {dateLabel(i.readAt)}</>}</p></article>)}</section>
}
function PublishedNotice({item,initiallyOpen=false}){
 const{t}=useI18n(),[open,setOpen]=useState(initiallyOpen),[receipts,setReceipts]=useState([]),[error,setError]=useState('')
 useEffect(()=>{if(!open)return;let alive=true;const refresh=async()=>{try{const r=await api(`/api/notices/${item.id}/receipts`);if(alive){setReceipts(r.items);setError('')}}catch(e){if(alive)setError(e.message)}};void refresh();const timer=setInterval(refresh,15000);return()=>{alive=false;clearInterval(timer)}},[open,item.id])
 return <article><NoticeText item={item}/><p>{t('notice.read')}: {item.readCount} / {item.recipientCount}</p><button aria-expanded={open} onClick={()=>setOpen(!open)}>{t(open?'notice.hideReceipts':'notice.receipts')}</button>{open&&<><p>{t('notice.readMeaning')}</p>{error&&<p role="alert">{error}</p>}<ul className="notice-receipts">{receipts.map(r=><li key={r.employeeId}><b data-i18n-raw>{r.employeeName}</b><span>{t(r.readAt?'notice.read':'notice.unread')}{r.readAt&&<> · {dateLabel(r.readAt)}</>}</span></li>)}</ul></>}</article>
}
const emptyDraft=()=>({title:'',body:'',priority:'normal',audience:'all',employeeIds:[],requestKey:crypto.randomUUID()})
export function NoticeManagement(){
 const{t}=useI18n(),[items,setItems]=useState([]),[employees,setEmployees]=useState([]),[draft,setDraft]=useState(emptyDraft),[search,setSearch]=useState(''),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=useCallback(async()=>{const [n,e]=await Promise.all([api('/api/notices'),api('/api/notices/recipients')]);setItems(n.items);setEmployees(e.items)},[])
 useEffect(()=>{let alive=true;const refresh=()=>load().catch(e=>{if(alive)setError(e.message)});void refresh();const timer=setInterval(refresh,15000);return()=>{alive=false;clearInterval(timer)}},[load])
 const selected=employees.filter(e=>draft.audience==='all'||draft.employeeIds.includes(e.id))
 const change=values=>{setDraft(d=>({...d,...values,requestKey:crypto.randomUUID()}));setMessage('')}
 const publish=async()=>{if(busy)return;setBusy(true);setError('');setMessage('');try{await api('/api/notices',{method:'POST',body:JSON.stringify(draft)});setDraft(emptyDraft());setPreview(false);setMessage(t('notice.published'));await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="notice-board notice-management"><h2>{t('notice.manage')}</h2><p>{t('notice.help')}</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<form onSubmit={e=>{e.preventDefault();setPreview(true);setError('')}}><fieldset disabled={busy||preview}><label>{t('notice.heading')}<input required maxLength={120} value={draft.title} onChange={e=>change({title:e.target.value})}/></label><label>{t('notice.content')}<textarea required maxLength={5000} rows={5} value={draft.body} onChange={e=>change({body:e.target.value})}/></label><label>{t('notice.priority')}<select value={draft.priority} onChange={e=>change({priority:e.target.value})}><option value="normal">{t('notice.normal')}</option><option value="urgent">{t('notice.urgent')}</option></select></label><label>{t('notice.audience')}<select value={draft.audience} onChange={e=>change({audience:e.target.value})}><option value="all">{t('notice.all')}</option><option value="selected">{t('notice.selected')}</option></select></label>{draft.audience==='selected'&&<><label>{t('notice.findEmployee')}<input value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="notice-employee-options">{employees.filter(e=>(e.name+' '+e.employeeCode).toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(e=><label key={e.id}><input type="checkbox" checked={draft.employeeIds.includes(e.id)} onChange={event=>change({employeeIds:event.target.checked?[...draft.employeeIds,e.id]:draft.employeeIds.filter(id=>id!==e.id)})}/><span data-i18n-raw>{e.name} · {e.employeeCode}</span></label>)}</div></>}<p>{t('notice.recipientCount')}: {selected.length}</p><button type="submit" disabled={!draft.title.trim()||!draft.body.trim()||!selected.length}>{t('notice.preview')}</button></fieldset></form>{preview&&<article className="notice-preview"><h3>{t('notice.preview')}</h3><NoticeText item={{...draft,createdAt:new Date().toISOString(),publisherName:''}}/><p>{t('notice.audience')}: {draft.audience==='all'?t('notice.all'):t('notice.selected')} ({selected.length})</p><p data-i18n-raw>{selected.map(e=>e.name).join(', ')}</p><p>{t('notice.publishHelp')}</p><button type="button" disabled={busy} onClick={()=>setPreview(false)}>{t('notice.editDraft')}</button><button type="button" className="notice-primary" disabled={busy||!selected.length} onClick={publish}>{t(busy?'common.processing':'notice.publish')}</button></article>}<h3>{t('notice.history')}</h3>{!items.length&&<p>{t('notice.empty')}</p>}<NoticeArchive items={items} renderDetail={item=><PublishedNotice item={item} initiallyOpen/>}/></section>
}
