const labels={
 zh:{source:'原文语言',prepare:'生成三语并预览',translating:'正在翻译…',retry:'重新翻译',help:'请检查三种语言后发布。空白字段会显示原文；已发布的内容会固定保存。',retryHelp:'重新翻译会替换成功生成的译文，请先确认手动修改是否需要保留。',notConfigured:'自动翻译尚未配置。你可以手填译文，或直接发布原文。',failed:'部分语言未能翻译，已有内容已保留。缺少的译文将显示原文，也可以重新翻译。',busy:'另一个翻译正在处理中。稍后重试，或直接发布已有内容。',fallback:'未填写的字段将显示原文。',original:'原文',versions:'三语预览与修改'},
 ms:{source:'Bahasa asal',prepare:'Terjemah & pratonton tiga bahasa',translating:'Sedang menterjemah…',retry:'Terjemah semula',help:'Semak ketiga-tiga bahasa sebelum terbitkan. Ruangan kosong menggunakan teks asal. Kandungan yang diterbitkan disimpan tetap.',retryHelp:'Terjemahan baharu yang berjaya akan menggantikan suntingan terjemahan anda.',notConfigured:'Terjemahan automatik belum dikonfigurasi. Isi terjemahan sendiri atau terbitkan teks asal.',failed:'Sebahagian terjemahan gagal. Kandungan sedia ada dikekalkan. Terjemahan yang tiada menggunakan teks asal; anda boleh cuba lagi.',busy:'Terjemahan lain sedang diproses. Cuba lagi kemudian atau terbitkan kandungan sedia ada.',fallback:'Ruangan kosong akan menggunakan teks asal.',original:'Teks asal',versions:'Pratonton & sunting tiga bahasa'},
 en:{source:'Source language',prepare:'Translate & preview three languages',translating:'Translating…',retry:'Re-translate',help:'Review all three languages before publishing. Blank fields use the original text. Published content is saved permanently.',retryHelp:'Successful re-translations replace your edited translations.',notConfigured:'Automatic translation is not configured. Enter translations manually or publish the original text.',failed:'Some translations failed. Existing text is preserved. Missing translations use the original; you can retry.',busy:'Another translation is running. Retry later or publish the existing content.',fallback:'Blank fields will use the original text.',original:'Original text',versions:'Review & edit three languages'}
}
const failureLabels={"invalidKey": ["翻译密钥无效。请重新完整复制 OpenAI API 密钥到服务器并重启 kcs-api。", "Kunci API terjemahan tidak sah. Salin semula kunci penuh ke pelayan dan mulakan semula kcs-api.", "Invalid translation API key. Copy the complete key to the server and restart kcs-api."], "quotaExceeded": ["API 额度不足。请检查 OpenAI Platform 的 Billing 余额及额度；之后重新翻译。", "Kuota API tidak mencukupi. Semak baki dan kuota Billing OpenAI Platform, kemudian cuba lagi.", "API quota exceeded. Check OpenAI Platform Billing balance and quota, then retry."], "permissionDenied": ["翻译密钥没有调用权限。请检查密钥的 Responses 写入权限及项目模型权限。", "Kunci API tiada kebenaran. Semak kebenaran tulis Responses dan akses model projek.", "API permission denied. Check Responses write permission and project model access."], "rateLimited": ["翻译请求过于频繁，请稍后重新翻译。", "Terlalu banyak permintaan. Cuba terjemah semula sebentar lagi.", "Too many translation requests. Please retry shortly."], "modelUnavailable": ["翻译模型不可用。请检查服务器的翻译模型设置及项目访问权限。", "Model terjemahan tidak tersedia. Semak tetapan model pelayan dan akses projek.", "Translation model unavailable. Check server model settings and project access."], "providerUnavailable": ["翻译服务暂时出错，请稍后重试。原文和已有译文已保留。", "Perkhidmatan terjemahan bermasalah. Cuba lagi kemudian. Teks sedia ada dikekalkan.", "Translation service error. Retry later. Existing text is preserved."], "connectionFailed": ["服务器无法连接翻译服务，请检查网络后重试。已有内容已保留。", "Pelayan tidak dapat menghubungi perkhidmatan terjemahan. Semak rangkaian dan cuba lagi.", "Server could not connect to translation service. Check the network and retry."], "translationTimeout": ["翻译等待超时，请重新翻译。已有内容已保留。", "Terjemahan tamat masa. Cuba lagi. Teks sedia ada dikekalkan.", "Translation timed out. Retry; existing text is preserved."], "invalidTranslation": ["译文未通过完整性检查，请重新翻译，或手动填写。已有内容已保留。", "Terjemahan tidak lengkap atau gagal semakan. Cuba lagi atau isi sendiri. Teks sedia ada dikekalkan.", "Translation failed completeness checks. Retry or enter manually. Existing text is preserved."]}
for(const [key,values] of Object.entries(failureLabels))for(const [index,lang] of ["zh","ms","en"].entries())labels[lang][key]=values[index]
export const noticeLanguageNames={zh:'中文',ms:'Bahasa Melayu',en:'English'}
export const noticeTranslationLabel=(language,key)=>(labels[language]||labels.en)[key]||key
