import OccGroupName from './OccGroupName.jsx'
import {navigateWithinApp} from './navigation.js'
import OccPriceGrouping from './OccPriceGrouping.jsx'
import {FilterHeader} from './ExpenseRecordsPage.jsx'
import {useEffect,useState} from 'react'
import {createPortal} from 'react-dom'
import {apiRequest as api} from './apiClient.js'
import {useI18n} from './i18n.jsx'
import BackButton from './BackButton.jsx'
import DateInput from './DateInput.jsx'
import {formatDateDisplay} from './dateDisplay.js'
import {kuchingDate} from '../shared/kuchingTime.js'
import {formatCustomerId} from '../shared/typedIds.js'
import './OccCurrentPrices.css'

const words={
 zh:{title:'OCC 价格组',help:'与客户主档及开单使用相同的现行价格。',unused:'显示未使用的价格组',companies:'公司',branches:'分店',edit:'修改整组价格',current:'当前价格',next:'新价格（RM/kg）',date:'生效日期',reason:'修改原因',preview:'预览修改',confirm:'确认保存',cancel:'取消',saved:'已保存',pending:'待生效',standard:'标准价格',outstation:'外埠价格',all:'全选',move:'更换价格组',target:'目标价格组',select:'请选择',search:'搜索公司／分店',customer:'公司',type:'价格类型',special:'待归组价格记录',unpriced:'未设置 OCC 价格的公司',open:'打开客户主档',warning:'以下公司保留在原组，新单在生效日起使用新价格，历史单据保持原价。同价的其他组不会合并。',scope:'修改公司价格会影响该公司使用此价格类型的所有分店。',moving:'确认更换价格组',moveWarning:'仅更换所选公司的对应价格类型。请核对目标组价格及待生效价格。',empty:'没有符合条件的公司',loading:'正在读取…',inactive:'已停用',unsaved:'放弃尚未保存的修改？',specialHelp:'这些价格尚未连接到价格组。按原价归组后，将跟随对应组调价。',refresh:'刷新',error:'操作未完成，请刷新核对后重试。'},
 ms:{title:'Kumpulan Harga OCC',help:'Harga semasa yang sama dengan rekod pelanggan dan bil.',unused:'Tunjuk kumpulan belum digunakan',companies:'Syarikat',branches:'Cawangan',edit:'Ubah harga seluruh kumpulan',current:'Harga semasa',next:'Harga baharu (RM/kg)',date:'Tarikh kuat kuasa',reason:'Sebab perubahan',preview:'Pratonton perubahan',confirm:'Sahkan simpan',cancel:'Batal',saved:'Disimpan',pending:'Akan berkuat kuasa',standard:'Harga standard',outstation:'Harga luar kawasan',all:'Pilih semua',move:'Tukar kumpulan harga',target:'Kumpulan sasaran',select:'Sila pilih',search:'Cari syarikat / cawangan',customer:'Syarikat',type:'Jenis harga',special:'Rekod harga belum dikumpulkan',unpriced:'Syarikat tanpa harga OCC',open:'Buka rekod pelanggan',warning:'Syarikat kekal dalam kumpulan ini. Bil baharu menggunakan harga baharu mulai tarikh kuat kuasa. Bil lama tidak berubah. Kumpulan lain dengan harga sama tidak digabungkan.',scope:'Perubahan harga syarikat melibatkan semua cawangan yang menggunakan jenis harga ini.',moving:'Sahkan pertukaran kumpulan',moveWarning:'Hanya jenis harga syarikat yang dipilih akan ditukar. Semak harga sasaran dan harga akan datang.',empty:'Tiada syarikat sepadan',loading:'Memuatkan…',inactive:'Tidak aktif',unsaved:'Buang perubahan yang belum disimpan?',specialHelp:'Harga ini belum dipautkan ke kumpulan. Selepas dikumpulkan pada harga asal, ia mengikuti perubahan harga kumpulan.',refresh:'Muat semula',error:'Tindakan tidak selesai. Muat semula dan semak sebelum mencuba lagi.'},
 en:{title:'OCC Price Groups',help:'Current prices shared with Customer records and billing.',unused:'Show unused price groups',companies:'Companies',branches:'Branches',edit:'Change whole group price',current:'Current price',next:'New price (RM/kg)',date:'Effective date',reason:'Reason',preview:'Preview change',confirm:'Confirm save',cancel:'Cancel',saved:'Saved',pending:'Scheduled',standard:'Standard',outstation:'Outstation',all:'Select all',move:'Change price group',target:'Target price group',select:'Select',search:'Search company / branch',customer:'Company',type:'Price type',special:'Ungrouped price records',unpriced:'Companies without OCC pricing',open:'Open customer record',warning:'Companies remain in this group. New bills use the new price from the effective date. Existing bills retain their original prices. Other groups with the same price remain separate.',scope:'A company price change affects all its branches using that price type.',moving:'Confirm price group change',moveWarning:'Only the selected company price types change. Review the target price and any scheduled price.',empty:'No matching companies',loading:'Loading…',inactive:'Inactive',unsaved:'Discard unsaved changes?',specialHelp:'These prices are not linked to a group yet. Group them at current prices to follow future group price changes.',refresh:'Refresh',error:'Action not completed. Refresh and review before trying again.'}
}
const errors={
 'Price or customers changed. Refresh and review again.':['价格或公司资料已改变，请刷新后重新核对。','Harga atau pelanggan telah berubah. Muat semula dan semak.'],
 'This group already has a scheduled price change.':['这组已有待生效改价，请待生效后再修改。','Kumpulan ini sudah mempunyai perubahan harga berjadual.'],
 'Enter a price greater than zero with at most 3 decimals.':['请输入大于零、最多三位小数的价格。','Masukkan harga melebihi sifar, maksimum 3 tempat perpuluhan.'],
 'Choose today or a future effective date.':['请选择今天或以后的有效日期。','Pilih tarikh sah hari ini atau akan datang.'],
 'Enter a reason.':['请填写修改原因。','Sila isi sebab.'],
 'Enter a different price.':['请输入不同的新价格。','Masukkan harga baharu yang berbeza.'],
 'Customer assignment changed. Refresh and review again.':['公司所属组已改变，请刷新后重新核对。','Kumpulan pelanggan telah berubah. Muat semula dan semak.']
}
const money=n=>`RM${Number(n).toFixed(3)}/kg`
const link=m=>`?page=customers&customer=${encodeURIComponent(formatCustomerId(m.customerCode))}`
export default function OccCurrentPrices({canManage,onBack,notify,fail}){
 const {language,t}=useI18n(),w=words[language]||words.en
 const [data,setData]=useState(null),[id,setId]=useState(null),[unused,setUnused]=useState(false),[search,setSearch]=useState(''),[keys,setKeys]=useState([]),[dialog,setDialog]=useState(null),[busy,setBusy]=useState(false),[draft,setDraft]=useState({price:'',effectiveDate:'',reason:'',targetId:''}),[preview,setPreview]=useState(false),[error,setError]=useState('')
 const [filters,setFilters]=useState({}),[sort,setSort]=useState({}),[openFilter,setOpenFilter]=useState(null)
 const group=data?.groups.find(g=>g.id===id),target=data?.groups.find(g=>g.id===Number(draft.targetId))
 const report=e=>setError(language==='en'?e.message:(errors[e.message]?.[language==='zh'?0:1]||w.error))
 const load=async()=>{try{setData(await api('/api/occ-current-groups'));setError('')}catch(e){report(e)}}
 useEffect(()=>{load()},[])
 const close=()=>{if(busy)return;if((draft.reason||draft.price||draft.targetId)&&!window.confirm(w.unsaved))return;setDialog(null);setError('')}
 useEffect(()=>{if(!dialog)return;const handle=e=>{if(e.key==='Escape'){e.stopPropagation();close()}};document.addEventListener('keydown',handle);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handle);document.body.style.overflow=old}},[dialog,busy,draft,language])
 const back=<BackButton onClick={()=>{if(group){setId(null);setKeys([]);setSearch('');setFilters({});setSort({});setOpenFilter(null)}else onBack()}}/>,headerTarget=document.getElementById('materials-header-back')
 const start=kind=>{setDialog(kind);setDraft({price:'',effectiveDate:kuchingDate(),reason:'',targetId:''});setPreview(false);setError('')}
 const save=async()=>{if(busy)return;setBusy(true);try{if(dialog==='price')await api(`/api/occ-current-groups/${group.id}/price`,{method:'PATCH',body:JSON.stringify({price:draft.price,effectiveDate:draft.effectiveDate,reason:draft.reason,version:group.version})});else await api('/api/occ-current-groups/move',{method:'POST',body:JSON.stringify({sourceId:group.id,targetId:target.id,keys,reason:draft.reason,sourceVersion:group.version,targetVersion:target.version})});setDialog(null);setKeys([]);notify(w.saved);await load()}catch(e){report(e)}finally{setBusy(false)}}
 const customer=m=><a className="entity-name-link" data-i18n-raw href={link(m)} onClick={event=>{event.preventDefault();navigateWithinApp(link(m),t('common.unsaved'))}}>{formatCustomerId(m.customerCode)} · {m.customerName}</a>
 if(!data)return <div>{w.loading}{error&&<p role="alert">{error}</p>}</div>
 const memberValue=(m,key)=>key==='customer'?m.customerName:key==='type'?w[m.priceType]:m.branches.map(b=>b.branchName).join(' / ')
 const members=(group?.members.filter(m=>`${m.customerCode} ${m.customerName} ${m.branches.map(b=>b.branchName).join(' ')}`.toLowerCase().includes(search.toLowerCase())&&Object.entries(filters).every(([key,values])=>values==null||values.includes(memberValue(m,key))))||[]).sort((a,b)=>sort.direction?memberValue(a,sort.key).localeCompare(memberValue(b,sort.key),undefined,{numeric:true})*(sort.direction==='desc'?-1:1):a.customerName.localeCompare(b.customerName,undefined,{numeric:true}))
 const all=members.length>0&&members.every(m=>keys.includes(m.key))
 return <div className="material-page-level occ-current-prices">{headerTarget?createPortal(back,headerTarget):back}<section className="occ-price-groups">
 <header><div><h3>{w.title}{group?` · ${group.code}`:''}</h3><p>{w.help}</p></div><button onClick={load}>{w.refresh}</button></header>
 {!dialog&&error&&<p role="alert">{error}</p>}
 {group?<><h3>{money(group.price)} · {group.customerCount} {w.companies} · {group.branchCount} {w.branches}</h3><p>{w.scope}</p>{group.pending&&<p>{w.pending}: {money(group.pending.price)} · {formatDateDisplay(group.pending.date)}</p>}
 {canManage&&<div className="occ-current-actions"><button disabled={Boolean(group.pending)||group.status!=='active'||group.visibility!=='active'} onClick={()=>start('price')}>{w.edit}</button><OccGroupName group={group} onSaved={load} notify={notify}/><button disabled={!keys.length} onClick={()=>start('move')}>{w.move} ({keys.length})</button></div>}
 <input aria-label={w.search} placeholder={w.search} value={search} onChange={e=>setSearch(e.target.value)}/>
 <div className="table-wrap"><table><thead><tr>{canManage&&<th><label><input type="checkbox" checked={all} onChange={()=>setKeys(all?keys.filter(k=>!members.some(m=>m.key===k)):[...new Set([...keys,...members.map(m=>m.key)])])}/>{w.all}</label></th>}{['customer','type','branches'].map(key=><FilterHeader key={key} label={w[key]} options={[...new Set(group.members.map(m=>memberValue(m,key)))].map(value=>({value,label:value||'—'}))} value={filters[key]??null} onChange={value=>setFilters({...filters,[key]:value})} sortDirection={sort.key===key?sort.direction:null} onSort={direction=>setSort({key,direction})} open={openFilter===key} onOpen={()=>setOpenFilter(key)} onClose={()=>setOpenFilter(null)}/>)}</tr></thead><tbody>{members.map(m=><tr key={m.key}>{canManage&&<td><input type="checkbox" aria-label={m.customerName+' '+w[m.priceType]} checked={keys.includes(m.key)} onChange={()=>setKeys(keys.includes(m.key)?keys.filter(k=>k!==m.key):[...keys,m.key])}/></td>}<td>{customer(m)}</td><td>{w[m.priceType]}</td><td>{m.branches.map(b=><div key={b.id} data-i18n-raw>{b.branchName}</div>)}</td></tr>)}</tbody></table>{!members.length&&<p>{w.empty}</p>}</div></>:<>
 <label><input type="checkbox" checked={unused} onChange={e=>setUnused(e.target.checked)}/>{w.unused}</label>
 <div className="price-level-grid">{data.groups.filter(g=>g.members.length||unused).map(g=><article key={g.id} role="button" tabIndex={0} onClick={()=>setId(g.id)} onKeyDown={e=>e.key==='Enter'&&setId(g.id)}><strong>{money(g.price)}</strong><span>{g.code} · {g.customerCount} {w.companies}</span><small>{g.branchCount} {w.branches}</small>{g.status!=='active'&&<small>{w.inactive}</small>}{g.pending&&<small>{w.pending}: {money(g.pending.price)} · {formatDateDisplay(g.pending.date)}</small>}</article>)}</div>
 {canManage&&data.special.length>0&&<div className="occ-current-actions"><OccPriceGrouping onSaved={load} notify={notify}/></div>}
 {data.special.length>0&&<details><summary>{w.special} ({data.special.length})</summary><p>{w.specialHelp}</p>{data.special.map(m=><p key={m.key}>{customer(m)} · {w[m.priceType]} · {money(m.specialPrice)}</p>)}</details>}
 {data.unpriced.length>0&&<details><summary>{w.unpriced} ({data.unpriced.length})</summary>{data.unpriced.map(m=><p key={m.customerId}>{customer(m)}</p>)}</details>}
 </>}
 </section>{dialog&&group&&createPortal(<div className="master-modal occ-current-modal" onClick={e=>e.target===e.currentTarget&&close()}><form role="dialog" aria-modal="true" aria-label={dialog==='price'?w.edit:w.moving} onSubmit={e=>{e.preventDefault();if(preview)save();else setPreview(true)}}><h3>{dialog==='price'?w.edit:w.moving}</h3><p>{group.code} · {w.current}: {money(group.price)}</p><p>{dialog==='price'?w.warning:w.moveWarning}</p>{preview?<><p>{dialog==='price'?`${money(draft.price)} · ${formatDateDisplay(draft.effectiveDate)}`:`${target.code} · ${money(target.price)}`}</p>{target?.pending&&dialog==='move'&&<p>{w.pending}: {money(target.pending.price)} · {formatDateDisplay(target.pending.date)}</p>}<p>{w.reason}: {draft.reason}</p><div className="occ-preview-members">{group.members.filter(m=>dialog==='price'||keys.includes(m.key)).map(m=><p key={m.key}><span data-i18n-raw>{m.customerName}</span> · {w[m.priceType]} · {m.branches.length} {w.branches}</p>)}</div></>:<>{dialog==='price'?<><label>{w.next}<input autoFocus required type="number" min="0.001" step="0.001" value={draft.price} onChange={e=>setDraft({...draft,price:e.target.value})}/></label><label>{w.date}<DateInput required type="date" min={kuchingDate()} value={draft.effectiveDate} onChange={e=>setDraft({...draft,effectiveDate:e.target.value})}/></label></>:<label>{w.target}<select required value={draft.targetId} onChange={e=>setDraft({...draft,targetId:e.target.value})}><option value="">{w.select}</option>{data.groups.filter(g=>g.id!==group.id&&g.status==='active'&&g.visibility==='active').map(g=><option key={g.id} value={g.id}>{g.code} · {money(g.price)}{g.pending?` · ${w.pending} ${money(g.pending.price)} ${formatDateDisplay(g.pending.date)}`:''}</option>)}</select></label>}<label>{w.reason}<textarea required value={draft.reason} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label></>}{error&&<p role="alert">{error}</p>}<footer><button type="button" disabled={busy} onClick={close}>{w.cancel}</button>{preview&&<button type="button" disabled={busy} onClick={()=>setPreview(false)}>{w.edit}</button>}<button disabled={busy||!draft.reason.trim()||(dialog==='price'?(!draft.price||!draft.effectiveDate):!target)}>{preview?w.confirm:w.preview}</button></footer></form></div>,document.body)}</div>
}
