import {useState} from 'react'
import {createPortal} from 'react-dom'
import {useI18n} from './i18n.jsx'
import {apiRequest as api} from './apiClient.js'
const words={zh:{edit:'修改价格组名称',name:'价格组名称',save:'保存名称',cancel:'取消',saved:'价格组名称已保存',help:'价格及组内客户保持不变。',duplicate:'这个名称已被其他价格组使用。',invalid:'请输入 1 至 80 个字的名称。',failed:'保存失败，请刷新价格组后重试。'},ms:{edit:'Ubah nama kumpulan harga',name:'Nama kumpulan harga',save:'Simpan nama',cancel:'Batal',saved:'Nama kumpulan harga disimpan',help:'Harga dan pelanggan dalam kumpulan tidak berubah.',duplicate:'Nama ini sudah digunakan oleh kumpulan lain.',invalid:'Masukkan nama 1 hingga 80 aksara.',failed:'Gagal menyimpan. Muat semula kumpulan dan cuba lagi.'},en:{edit:'Rename price group',name:'Price group name',save:'Save name',cancel:'Cancel',saved:'Price group name saved',help:'Prices and group customers stay unchanged.',duplicate:'This name is already used by another group.',invalid:'Enter a name of 1 to 80 characters.',failed:'Save failed. Refresh the group and try again.'}}
export default function OccGroupName({group,label=group.code,onSaved,notify}){
 const{language,t}=useI18n(),w=words[language]||words.en
 const[open,setOpen]=useState(false),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const close=()=>{if(busy)return;if(name.trim()!==group.code&&!window.confirm(t('common.unsaved')))return;setOpen(false)}
 const save=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await api(`/api/occ-current-groups/${group.id}/name`,{method:'PATCH',body:JSON.stringify({name:name.trim(),version:group.version})});setOpen(false);notify(w.saved);await onSaved()}catch(e){setError(e.message==='This group name is already used.'?w.duplicate:e.message==='Enter a group name of 1 to 80 characters.'?w.invalid:w.failed)}finally{setBusy(false)}}
 return <><button type="button" className="entity-name-link" style={{font:'inherit',padding:0}} title={w.edit} aria-label={`${w.edit}: ${group.code}`} onClick={()=>{setName(group.code);setError('');setOpen(true)}}><span data-i18n-raw>{label}</span></button>{open&&createPortal(<div className="master-modal occ-current-modal" onClick={e=>e.target===e.currentTarget&&close()} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();close()}}}><form role="dialog" aria-modal="true" aria-label={w.edit} onSubmit={save}><h3>{w.edit}</h3><p>{w.help}</p><label>{w.name}<input autoFocus required maxLength={80} value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<footer><button type="button" disabled={busy} onClick={close}>{w.cancel}</button><button disabled={busy||!name.trim()||name.trim()===group.code}>{w.save}</button></footer></form></div>,document.body)}</>
}
