import {useEffect,useState} from 'react'
import {createPortal} from 'react-dom'
import {apiRequest as api} from './apiClient.js'
import {useI18n} from './i18n.jsx'
const labels={
 zh:{open:'按原价归组',title:'核对同价归组',help:'当前价格保持不变。归组后，这些公司会跟随所属价格组一起调价。',records:'价格记录',companies:'公司',newGroup:'建立同价新组',choose:'有多个同价组，请选择',group:'目标价格组',confirm:'确认归组',cancel:'取消',busy:'处理中…',blocked:'以下记录的价格无效，需要在客户主档核对后再归组',none:'没有需要归组的价格记录',error:'资料可能已改变，请关闭并重新预览后再试。',success:'已按原价归组',standard:'标准价格',outstation:'外埠价格',pending:'有待生效改价的组不会自动选用。'},
 ms:{open:'Kumpulkan pada harga asal',title:'Semak pengumpulan harga sama',help:'Harga semasa tidak berubah. Selepas dikumpulkan, syarikat ini akan mengikuti perubahan harga kumpulan.',records:'Rekod harga',companies:'Syarikat',newGroup:'Cipta kumpulan baharu pada harga sama',choose:'Beberapa kumpulan sama harga: sila pilih',group:'Kumpulan sasaran',confirm:'Sahkan pengumpulan',cancel:'Batal',busy:'Memproses…',blocked:'Harga berikut tidak sah. Semak rekod pelanggan dahulu',none:'Tiada rekod harga perlu dikumpulkan',error:'Data mungkin telah berubah. Tutup dan buka semula pratonton.',success:'Dikumpulkan pada harga asal',standard:'Standard',outstation:'Luar kawasan',pending:'Kumpulan dengan perubahan harga berjadual tidak dipilih secara automatik.'},
 en:{open:'Group at current prices',title:'Review same-price grouping',help:'Current prices stay unchanged. After grouping, these companies follow future changes to their group price.',records:'Price records',companies:'Companies',newGroup:'Create a new group at the same price',choose:'Multiple same-price groups: choose one',group:'Target group',confirm:'Confirm grouping',cancel:'Cancel',busy:'Processing…',blocked:'These prices need correction in Customer Master before grouping',none:'No price records need grouping',error:'Data may have changed. Close and reopen the preview.',success:'Grouped at unchanged prices',standard:'Standard',outstation:'Outstation',pending:'Groups with scheduled price changes are not selected automatically.'}
}
const price=value=>`RM${Number(value).toFixed(3)}/kg`
export default function OccPriceGrouping({onSaved,notify}){
 const{language}=useI18n(),w=labels[language]||labels.en
 const[plan,setPlan]=useState(null),[choices,setChoices]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const open=async()=>{setBusy(true);setError('');try{const data=await api('/api/occ-current-groups/group-special');setPlan(data);setChoices(Object.fromEntries(data.items.map(g=>[g.key,g.defaultTarget])))}catch{setError(w.error)}finally{setBusy(false)}}
 const close=()=>{if(!busy){setPlan(null);setError('')}}
 useEffect(()=>{if(!plan)return;const old=document.body.style.overflow,active=document.activeElement;document.body.style.overflow='hidden';const panel=document.querySelector('.occ-grouping-dialog');panel?.querySelector('select,footer button')?.focus();const handle=e=>{if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab'){const nodes=[...panel.querySelectorAll('button:not(:disabled),select:not(:disabled),summary')];if(!nodes.length){e.preventDefault();return}const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',handle);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',handle);active?.focus?.()}},[plan,busy])
 const save=async()=>{if(busy)return;setBusy(true);setError('');try{const result=await api('/api/occ-current-groups/group-special',{method:'POST',body:JSON.stringify({version:plan.version,choices})});setPlan(null);notify(`${w.success}: ${result.changedCount} ${w.records} · ${result.customerCount} ${w.companies}`);await onSaved()}catch{setError(w.error)}finally{setBusy(false)}}
 return <><button type="button" disabled={busy} onClick={open}>{busy?w.busy:w.open}</button>{error&&!plan&&<p role="alert">{error}</p>}{plan&&createPortal(<div className="master-modal occ-current-modal" onClick={e=>e.target===e.currentTarget&&close()}><form className="occ-grouping-dialog" role="dialog" aria-modal="true" aria-label={w.title} onSubmit={e=>{e.preventDefault();save()}}><h3>{w.title}</h3><p>{w.help}</p><p>{plan.recordCount} {w.records} · {plan.customerCount} {w.companies}</p><p>{w.pending}</p>{plan.items.map(bucket=><section key={bucket.key}><h4>{price(bucket.price)} · {bucket.members.length} {w.records}</h4>{bucket.options.length===0?<p>{w.newGroup}</p>:bucket.options.length===1?<p>{w.group}: {bucket.options[0].code}</p>:<label>{w.choose}<select aria-label={`${w.group} ${price(bucket.price)}`} required disabled={busy} value={choices[bucket.key]} onChange={e=>setChoices({...choices,[bucket.key]:e.target.value})}><option value="">{w.choose}</option>{bucket.options.map(g=><option value={g.id} key={g.id}>{g.code} · {g.customerCount} {w.companies}</option>)}</select></label>}<details><summary>{w.companies}</summary>{bucket.members.map(m=><p key={m.key}><span data-i18n-raw>{m.customerCode} · {m.customerName}</span> · {w[m.priceType]} · {price(m.specialPrice)}</p>)}</details></section>)}{plan.blocked.length>0&&<p>{w.blocked}: {plan.blocked.map(m=>m.customerName).join(', ')}</p>}{!plan.recordCount&&<p>{w.none}</p>}{error&&<p role="alert">{error}</p>}<footer><button type="button" disabled={busy} onClick={close}>{w.cancel}</button><button disabled={busy||!plan.recordCount||plan.items.some(g=>!choices[g.key])}>{busy?w.busy:w.confirm}</button></footer></form></div>,document.body)}</>
}
