import BackButton from './BackButton.jsx'
import TableBottomScroll from './TableBottomScroll.jsx'
import {FilterHeader} from './ExpenseRecordsPage.jsx'
import {useUi} from './i18n.jsx'
import './ExpenseRecordsPage.css'
import {useEffect,useMemo,useRef,useState} from 'react'
import {apiRequest} from './apiClient.js'
import './PurchaseBillsPage.css'
import './WeightRecords.css'

const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuching',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const firstOfMonth=()=>`${today().slice(0,7)}-01`
const money=cents=>`RM ${(Number(cents||0)/100).toFixed(2)}`
const displayDate=value=>{const match=/^(\d{4})-(\d{2})-(\d{2})/.exec(String(value||''));return match?`${match[3]}-${match[2]}-${match[1].slice(-2)}`:String(value||'')}
const displayDateTime=value=>{const date=displayDate(value),time=String(value||'').match(/T(\d{2}:\d{2})/)?.[1];return time?`${date} ${time}`:date}
const columns=[['serviceDateLabel','Date'],['billNumber','PO No.'],['paymentMethod','Payment Method'],['customerName','Customer Name'],['branchName','Branch'],['issuedBy','Issued By'],['crew','Crew'],['car','Car'],['totalLabel','Total'],['proofLabel','Payment Proof'],['statusLabel','Status']]

export default function PurchaseBillsPage({onBack}){
  const ui=useUi(),tableRef=useRef(null),[openFilter,setOpenFilter]=useState(null)
  const[filters,setFilters]=useState({from:firstOfMonth(),to:today(),search:'',paymentMethod:'',employeeId:''}),[columnFilters,setColumnFilters]=useState({}),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[open,setOpen]=useState(null),[showWeights,setShowWeights]=useState(false)
  const query=useMemo(()=>new URLSearchParams(Object.entries(filters).filter(([,value])=>value)).toString(),[filters])
  useEffect(()=>{let active=true;setLoading(true);setError('');setColumnFilters({});apiRequest(`/api/purchase-bills?${query}`).then(result=>active&&setData(result)).catch(item=>active&&setError(item.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[query])
  const rows=useMemo(()=>(data?.items||[]).map(bill=>({...bill,serviceDateLabel:displayDate(bill.serviceDate),car:bill.registrationNumber||bill.vehicleCode||'',totalLabel:money(bill.totalCents),proofLabel:bill.proofId?'Uploaded':bill.paymentMethod==='Credit'?'Not required':'Missing',statusLabel:bill.status==='voided'?'Voided':'Issued'})),[data])
  const displayed=useMemo(()=>rows.filter(row=>Object.entries(columnFilters).every(([key,value])=>!value||String(row[key]??'')===value)),[rows,columnFilters])
  const setColumn=(key,value)=>setColumnFilters(current=>({...current,[key]:value}))
  if(showWeights)return <WeightRecordsPage from={filters.from} to={filters.to} onBack={()=>setShowWeights(false)}/>
  return <div className="page purchase-archive expense-records">
    <div className="expense-toolbar"><BackButton fallback={onBack} iconOnly className="secondary"/><button type="button" onClick={()=>{setOpenFilter(null);setShowWeights(true)}}>{ui('Unloading Weight Records')}</button>
      <label>{ui('From Date')}<input aria-label={ui('From Date')} type="date" value={filters.from} max={filters.to} onChange={event=>setFilters({...filters,from:event.target.value})}/></label>
      <label>{ui('To Date')}<input aria-label={ui('To Date')} type="date" value={filters.to} min={filters.from} onChange={event=>setFilters({...filters,to:event.target.value})}/></label>
      <button type="button" onClick={()=>{window.location.href=`/api/purchase-bills/export.xlsx?${query}`}}>{ui('Download Excel with Payment Proofs')}</button></div>
    {error&&<div className="data-error">{error}</div>}{loading&&!data&&<div className="data-loading">{ui('Loading Purchase Bills…')}</div>}
    <div className="archive-table" ref={tableRef}><table><thead><tr>{columns.map(([key,label])=>{
 const serverKey={paymentMethod:'paymentMethod',issuedBy:'employeeId'}[key]
 const options=key==='paymentMethod'?['Cash','Credit'].map(value=>({value,label:ui(value)})):key==='issuedBy'?(data?.employees||[]).map(e=>({value:String(e.id),label:e.name})):[...new Set(rows.map(row=>String(row[key]??'')).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map(value=>({value,label:['proofLabel','statusLabel'].includes(key)?ui(value):value}))
 return <FilterHeader key={key} label={ui(label)} value={serverKey?filters[serverKey]:columnFilters[key]||''} options={options} open={openFilter===key} onOpen={()=>setOpenFilter(key)} onClose={()=>setOpenFilter(null)} search={['billNumber','customerName','branchName'].includes(key)?filters.search:undefined} onSearch={['billNumber','customerName','branchName'].includes(key)?value=>setFilters(current=>({...current,search:value})):undefined} searchLabel="Search purchase bills" searchPlaceholder="PO No., Customer, Branch or Branch ID" onChange={value=>serverKey?setFilters(current=>({...current,[serverKey]:value})):setColumn(key,value)}/>
 })}</tr></thead><tbody>{displayed.map(bill=><BillRow key={bill.id} bill={bill} expanded={open===bill.id} toggle={()=>setOpen(open===bill.id?null:bill.id)}/>)}</tbody></table>{!loading&&data&&!displayed.length&&<div className="archive-empty">{ui('No Purchase Bills found for this selection.')}</div>}</div>
    <TableBottomScroll scrollRef={tableRef}/>
  </div>
}

function WeightRecordsPage({from:initialFrom,to:initialTo,onBack}){const[from,setFrom]=useState(initialFrom),[to,setTo]=useState(initialTo),[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{let active=true;apiRequest(`/api/unloading-weights?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`).then(result=>active&&setData(result)).catch(item=>active&&setError(item.message));return()=>{active=false}},[from,to]);return <div className="page purchase-archive"><div className="archive-heading"><div><small>VEHICLE UNLOADING</small><h1>Unloading Weight Records</h1><p>Confirmed weighbridge photos, actual weights, estimated loads, vehicles, employees, GPS and times.</p></div><div className="archive-actions"><button className="secondary" onClick={onBack}>← Purchase Bills</button></div></div><section className="archive-filters weight-record-filters"><label>From Date<div className="compact-date"><span>{displayDate(from)}</span><i>▣</i><input type="date" value={from} max={to} onChange={event=>setFrom(event.target.value)}/></div></label><label>To Date<div className="compact-date"><span>{displayDate(to)}</span><i>▣</i><input type="date" value={to} min={from} onChange={event=>setTo(event.target.value)}/></div></label></section>{error&&<div className="data-error">{error}</div>}<div className="archive-table"><table className="weight-record-table"><thead><tr><th>Date</th><th>Vehicle</th><th>Driver</th><th>Crew</th><th>Trip</th><th>Unload Location</th><th>Estimated</th><th>Actual</th><th>GPS</th><th>Time</th><th>Photo</th></tr></thead><tbody>{(data?.items||[]).map(item=><tr key={item.id}><td>{displayDate(item.serviceDate)}</td><td>{item.vehicleCode} · {item.registrationNumber||'—'}</td><td>{item.driverName}</td><td>{item.crew||'—'}</td><td>{item.tripNumber}</td><td>{item.locationName||'—'}</td><td>{item.estimatedWeightKg??'—'} kg</td><td><b>{item.confirmedWeightKg} kg</b></td><td>{item.latitude!=null?<a href={`https://www.google.com/maps?q=${item.latitude},${item.longitude}`} target="_blank" rel="noreferrer">Open map</a>:'—'}</td><td>{displayDateTime(item.weighedAt)}</td><td><a href={`/api/unloading-weights/${item.id}/photo`} target="_blank" rel="noreferrer">View ticket</a></td></tr>)}</tbody></table>{data&&!data.items.length&&<div className="archive-empty">No unloading weight records found for this selection.</div>}</div></div>}

function BillRow({bill,expanded,toggle}){const ui=useUi();return <><tr className="bill-row" onClick={toggle}><td>{bill.serviceDateLabel}</td><td><button className="bill-number" onClick={event=>{event.stopPropagation();toggle()}}>{bill.billNumber}</button></td><td><span className={`payment ${bill.paymentMethod.toLowerCase()}`}>{ui(bill.paymentMethod)}</span></td><td data-i18n-raw>{bill.customerName}</td><td data-i18n-raw>{bill.branchName}</td><td data-i18n-raw>{bill.issuedBy}</td><td>{bill.crew||'—'}</td><td data-i18n-raw>{bill.car}</td><td>{bill.totalLabel}</td><td>{bill.proofId?<a href={`/api/purchase-bills/proofs/${bill.proofId}`} target="_blank" rel="noreferrer" onClick={event=>event.stopPropagation()}>{ui('View proof')}</a>:bill.paymentMethod==='Credit'?'—' :ui('Missing')}</td><td>{bill.status==='voided'?<span className="voided">{ui('Voided')}</span>:<span className="issued">{ui('Issued')}</span>}</td></tr>{expanded&&<tr className="bill-detail"><td colSpan="11"><div><b>{ui('Bill Items')}</b><table><thead><tr><th>{ui('Item')}</th><th>{ui('Quantity')}</th><th>{ui('Unit')}</th><th>{ui('Price')}</th><th>{ui('Item Total')}</th></tr></thead><tbody>{bill.items.map((item,index)=><tr key={index}><td>{item.shortForm||item.item}</td><td>{item.quantity}</td><td>{item.unit||'—'}</td><td>{money(item.unitPriceCents)}</td><td>{money(item.itemTotalCents)}</td></tr>)}</tbody></table><small>{ui('Issued at')} {displayDateTime(bill.issuedAt)} · {ui('Electronic records cannot be deleted.')}</small></div></td></tr>}</>}
