import {useEffect,useMemo,useState} from 'react'
import {apiRequest} from './apiClient.js'
import './PurchaseBillsPage.css'
import './WeightRecords.css'

const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuching',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const firstOfMonth=()=>`${today().slice(0,7)}-01`
const money=cents=>`RM ${(Number(cents||0)/100).toFixed(2)}`
const displayDate=value=>{const match=/^(\d{4})-(\d{2})-(\d{2})/.exec(String(value||''));return match?`${match[3]}-${match[2]}-${match[1].slice(-2)}`:String(value||'')}
const displayDateTime=value=>{const date=displayDate(value),time=String(value||'').match(/T(\d{2}:\d{2})/)?.[1];return time?`${date} ${time}`:date}
const columns=[['serviceDateLabel','Date'],['billNumber','PO No.'],['paymentMethod','Payment Method'],['customerName','Customer Name'],['branchName','Branch'],['issuedBy','Issued By'],['crew','Crew'],['car','Car'],['totalLabel','Total'],['proofLabel','Payment Proof'],['statusLabel','Status']]

export default function PurchaseBillsPage(){
  const[filters,setFilters]=useState({from:firstOfMonth(),to:today(),search:'',paymentMethod:'',employeeId:''}),[columnFilters,setColumnFilters]=useState({}),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[open,setOpen]=useState(null),[showWeights,setShowWeights]=useState(false)
  const query=useMemo(()=>new URLSearchParams(Object.entries(filters).filter(([,value])=>value)).toString(),[filters])
  useEffect(()=>{let active=true;setLoading(true);setError('');setColumnFilters({});apiRequest(`/api/purchase-bills?${query}`).then(result=>active&&setData(result)).catch(item=>active&&setError(item.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[query])
  const rows=useMemo(()=>(data?.items||[]).map(bill=>({...bill,serviceDateLabel:displayDate(bill.serviceDate),car:bill.registrationNumber||bill.vehicleCode||'',totalLabel:money(bill.totalCents),proofLabel:bill.proofId?'Uploaded':bill.paymentMethod==='Credit'?'Not required':'Missing',statusLabel:bill.status==='voided'?'Voided':'Issued'})),[data])
  const displayed=useMemo(()=>rows.filter(row=>Object.entries(columnFilters).every(([key,value])=>!value||String(row[key]??'')===value)),[rows,columnFilters])
  const setColumn=(key,value)=>setColumnFilters(current=>({...current,[key]:value}))
  if(showWeights)return <WeightRecordsPage from={filters.from} to={filters.to} onBack={()=>setShowWeights(false)}/>
  return <div className="page purchase-archive">
    <div className="archive-heading"><div><small>ACCOUNT SUPPORTING DOCUMENTS</small><h1>Purchase Bill Records</h1><p>Select any payroll or accounting period. Payment Proof images are included inside the Excel file.</p></div><div className="archive-actions"><button className="secondary" onClick={()=>setShowWeights(true)}>Unloading Weight Records</button><button onClick={()=>{window.location.href=`/api/purchase-bills/export.xlsx?${query}`}}>Download Excel with Payment Proofs</button></div></div>
    <section className="archive-filters">
      <label>From Date<div className="compact-date"><span>{displayDate(filters.from)}</span><i aria-hidden="true">▣</i><input aria-label="From Date" type="date" value={filters.from} max={filters.to} onChange={event=>setFilters({...filters,from:event.target.value})}/></div></label>
      <label>To Date<div className="compact-date"><span>{displayDate(filters.to)}</span><i aria-hidden="true">▣</i><input aria-label="To Date" type="date" value={filters.to} min={filters.from} onChange={event=>setFilters({...filters,to:event.target.value})}/></div></label>
      <label>Search<input placeholder="PO No., Customer, Branch or Branch ID" value={filters.search} onChange={event=>setFilters({...filters,search:event.target.value})}/></label>
      <label>Payment Method<select value={filters.paymentMethod} onChange={event=>setFilters({...filters,paymentMethod:event.target.value})}><option value="">All</option><option>Cash</option><option>Credit</option></select></label>
      <label>Issued By<select value={filters.employeeId} onChange={event=>setFilters({...filters,employeeId:event.target.value})}><option value="">All employees</option>{(data?.employees||[]).map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>
    </section>
    {error&&<div className="data-error">{error}</div>}{loading&&!data&&<div className="data-loading">Loading Purchase Bills…</div>}
    <div className="archive-table"><table><thead><tr>{columns.map(([key,label])=><FilterHeader key={key} label={label} value={columnFilters[key]||''} values={[...new Set(rows.map(row=>String(row[key]??'')).filter(Boolean))]} onChange={value=>setColumn(key,value)}/>)}</tr></thead><tbody>{displayed.map(bill=><BillRow key={bill.id} bill={bill} expanded={open===bill.id} toggle={()=>setOpen(open===bill.id?null:bill.id)}/>)}</tbody></table>{!loading&&data&&!displayed.length&&<div className="archive-empty">No Purchase Bills found for this selection.</div>}</div>
  </div>
}

function FilterHeader({label,value,values,onChange}){return <th><label className={value?'compact-filter active':'compact-filter'}><span>{label}</span><i aria-hidden="true">▼</i><select aria-label={`Filter ${label}`} value={value} onChange={event=>onChange(event.target.value)}><option value="">All</option>{values.sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map(item=><option key={item} value={item}>{item}</option>)}</select></label></th>}

function WeightRecordsPage({from:initialFrom,to:initialTo,onBack}){const[from,setFrom]=useState(initialFrom),[to,setTo]=useState(initialTo),[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{let active=true;apiRequest(`/api/unloading-weights?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`).then(result=>active&&setData(result)).catch(item=>active&&setError(item.message));return()=>{active=false}},[from,to]);return <div className="page purchase-archive"><div className="archive-heading"><div><small>VEHICLE UNLOADING</small><h1>Unloading Weight Records</h1><p>Confirmed weighbridge photos, actual weights, estimated loads, vehicles, employees, GPS and times.</p></div><div className="archive-actions"><button className="secondary" onClick={onBack}>← Purchase Bills</button></div></div><section className="archive-filters weight-record-filters"><label>From Date<div className="compact-date"><span>{displayDate(from)}</span><i>▣</i><input type="date" value={from} max={to} onChange={event=>setFrom(event.target.value)}/></div></label><label>To Date<div className="compact-date"><span>{displayDate(to)}</span><i>▣</i><input type="date" value={to} min={from} onChange={event=>setTo(event.target.value)}/></div></label></section>{error&&<div className="data-error">{error}</div>}<div className="archive-table"><table className="weight-record-table"><thead><tr><th>Date</th><th>Vehicle</th><th>Driver</th><th>Crew</th><th>Trip</th><th>Unload Location</th><th>Estimated</th><th>Actual</th><th>GPS</th><th>Time</th><th>Photo</th></tr></thead><tbody>{(data?.items||[]).map(item=><tr key={item.id}><td>{displayDate(item.serviceDate)}</td><td>{item.vehicleCode} · {item.registrationNumber||'—'}</td><td>{item.driverName}</td><td>{item.crew||'—'}</td><td>{item.tripNumber}</td><td>{item.locationName||'—'}</td><td>{item.estimatedWeightKg??'—'} kg</td><td><b>{item.confirmedWeightKg} kg</b></td><td>{item.latitude!=null?<a href={`https://www.google.com/maps?q=${item.latitude},${item.longitude}`} target="_blank" rel="noreferrer">Open map</a>:'—'}</td><td>{displayDateTime(item.weighedAt)}</td><td><a href={`/api/unloading-weights/${item.id}/photo`} target="_blank" rel="noreferrer">View ticket</a></td></tr>)}</tbody></table>{data&&!data.items.length&&<div className="archive-empty">No unloading weight records found for this selection.</div>}</div></div>}

function BillRow({bill,expanded,toggle}){return <><tr className="bill-row" onClick={toggle}><td>{bill.serviceDateLabel}</td><td><button className="bill-number" onClick={event=>{event.stopPropagation();toggle()}}>{bill.billNumber}</button></td><td><span className={`payment ${bill.paymentMethod.toLowerCase()}`}>{bill.paymentMethod}</span></td><td>{bill.customerName}</td><td>{bill.branchName}</td><td>{bill.issuedBy}</td><td>{bill.crew||'—'}</td><td>{bill.car}</td><td>{bill.totalLabel}</td><td>{bill.proofId?<a href={`/api/purchase-bills/proofs/${bill.proofId}`} target="_blank" rel="noreferrer" onClick={event=>event.stopPropagation()}>View proof</a>:bill.paymentMethod==='Credit'?'—':'Missing'}</td><td>{bill.status==='voided'?<span className="voided">Voided</span>:<span className="issued">Issued</span>}</td></tr>{expanded&&<tr className="bill-detail"><td colSpan="11"><div><b>Bill Items</b><table><thead><tr><th>Item</th><th>Quantity</th><th>Unit</th><th>Price</th><th>Item Total</th></tr></thead><tbody>{bill.items.map((item,index)=><tr key={index}><td>{item.shortForm||item.item}</td><td>{item.quantity}</td><td>{item.unit||'—'}</td><td>{money(item.unitPriceCents)}</td><td>{money(item.itemTotalCents)}</td></tr>)}</tbody></table><small>Issued at {displayDateTime(bill.issuedAt)} · Electronic records cannot be deleted.</small></div></td></tr>}</>}
