import {formatDateDisplay} from './dateDisplay.js'
import {Fragment,useEffect,useRef,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest} from './apiClient.js'
import {FilterHeader} from './ExpenseRecordsPage.jsx'
import TableBottomScroll from './TableBottomScroll.jsx'
import CenteredNotice from './CenteredNotice.jsx'
import './RescheduledCustomers.css'
const copy={
 zh:{title:'曾改期客户',total:'曾改期客户总数',branchName:'分店',route:'路线',count:'改期次数',empty:'没有符合条件的曾改期客户',loading:'正在读取客户…',retry:'刷新',blocked:'此客户当天已有任务，当前不能转给支援车。'},
 en:{title:'Rescheduled customers',total:'Total rescheduled customers',branchName:'Branch',route:'Route',count:'Date changes',empty:'No matching rescheduled customers',loading:'Loading customers…',retry:'Refresh',blocked:'This customer already has work on this date and cannot currently be transferred.'},
 ms:{title:'Pelanggan pernah tukar tarikh',total:'Jumlah pelanggan pernah tukar tarikh',branchName:'Cawangan',route:'Laluan',count:'Bilangan tukar tarikh',empty:'Tiada pelanggan sepadan yang pernah tukar tarikh',loading:'Memuatkan pelanggan…',retry:'Muat semula',blocked:'Pelanggan ini sudah mempunyai tugasan pada tarikh ini dan belum boleh dipindahkan.'}
}
const detailCopy={
 zh:{title:'改期明细',note:'以下为上次完成收货后已批准的改期记录，不代表每次都未到店。',from:'原定日期',to:'改到日期',reason:'申请原因',employee:'申请员工',approver:'批准人',at:'批准时间',review:'批准备注',empty:'没有可显示的明细，请刷新重试。',close:'收起'},
 ms:{title:'Butiran tukar tarikh',note:'Rekod pertukaran tarikh yang diluluskan sejak kutipan terakhir selesai; bukan bukti setiap kali tidak hadir.',from:'Tarikh asal',to:'Tarikh baharu',reason:'Sebab permohonan',employee:'Pemohon',approver:'Diluluskan oleh',at:'Masa kelulusan',review:'Catatan kelulusan',empty:'Tiada butiran dipaparkan. Muat semula.',close:'Tutup'},
 en:{title:'Reschedule details',note:'Approved date changes since the last completed collection; these do not prove non-attendance on each occasion.',from:'Original date',to:'New date',reason:'Request reason',employee:'Requested by',approver:'Approved by',at:'Approval time',review:'Approval note',empty:'No details available. Please refresh.',close:'Collapse'}
}
function approvalTime(value){
 if(!value)return '—'
 const raw=String(value),normalized=/[zZ]$|[+-]\d{2}:?\d{2}$/.test(raw)?raw:raw.replace(' ','T')+'Z',date=new Date(normalized)
 if(!Number.isFinite(+date))return '—'
 const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kuching',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date).map(p=>[p.type,p.value]))
 return formatDateDisplay(parts.year+'-'+parts.month+'-'+parts.day)+' '+parts.hour+':'+parts.minute
}
const keys=['branchName','route','count'],natural=new Intl.Collator(undefined,{numeric:true,sensitivity:'base'})
export default function RescheduledCustomers({date,selection,disabled=false}){
 const{language}=useI18n(),m=copy[language]||copy.en,d=detailCopy[language]||detailCopy.en,[expanded,setExpanded]=useState(null),scrollRef=useRef(null)
 const[data,setData]=useState({priority:[],items:[],routes:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[reload,setReload]=useState(0),[filters,setFilters]=useState({}),[sort,setSort]=useState({key:'count',direction:'desc'}),[open,setOpen]=useState(null)
 useEffect(()=>{setExpanded(null);let active=true;setLoading(true);setError('');apiRequest(`/api/dispatch/day/${date}/support-customers`).then(r=>{if(active)setData(r)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[date,reload])
 const rows=(data.priority||[]).map(b=>({...b,route:b.routeNumbers.map(n=>selection?.routes.find(r=>r.routeNumber===n)?.name||data.routes.find(r=>r.routeNumber===n)?.name||String(n)).join(' / ')}))
 const compare=(key,a,b)=>key==='count'?Number(a)-Number(b):natural.compare(a,b)
 const shown=rows.filter(b=>Object.entries(filters).every(([key,values])=>values==null||values.includes(String(b[key]??'')))).sort((a,b)=>sort.key?compare(sort.key,a[sort.key],b[sort.key])*(sort.direction==='desc'?-1:1)||natural.compare(a.branchName,b.branchName):0)
 const choice=b=>{const stop=selection?.routes.flatMap(r=>r.stops).find(s=>s.id===b.stopId),extra=data.items.find(s=>s.id===b.id);return{stop,extra,allowed:b.stopId?Boolean(stop&&['locked','available'].includes(stop.status)&&!stop.hasBill&&!stop.arrivedAt&&!stop.completedAt):Boolean(extra)}}
 const toggle=(b,checked)=>{const{extra}=choice(b);if(b.stopId)selection.setStops(ids=>checked?[...new Set([...ids,b.stopId])]:ids.filter(id=>id!==b.stopId));else selection.setOtherCustomers(items=>checked?items.some(s=>s.id===b.id)?items:[...items,extra]:items.filter(s=>s.id!==b.id))}
 return <section className="rescheduled-customers"><header><strong>{m.total}{language==='zh'?'：':': '}{loading?'…':shown.length.toLocaleString('en-MY')}</strong><button type="button" disabled={loading||disabled} onClick={()=>setReload(n=>n+1)}>{m.retry}</button></header>{error&&<CenteredNotice>{error}</CenteredNotice>}{loading?<p role="status">{m.loading}</p>:<><div className="archive-table" ref={scrollRef}><table><thead><tr>{keys.map(key=><FilterHeader key={key} label={m[key]} numeric={key==='count'} value={filters[key]??null} options={['',...new Set(rows.map(b=>String(b[key]??'')).filter(Boolean))].sort((a,b)=>compare(key,a,b)).map(value=>({value,label:value}))} onChange={value=>setFilters(v=>({...v,[key]:value}))} sortDirection={sort.key===key?sort.direction:null} onSort={direction=>setSort(direction?{key,direction}:{})} open={open===key} onOpen={()=>setOpen(key)} onClose={()=>setOpen(null)}/>)}</tr></thead><tbody>{shown.map(b=><Fragment key={b.id}><tr><td>{selection?<label className="support-option" title={choice(b).allowed?'':m.blocked}><input type="checkbox" disabled={disabled||!choice(b).allowed} checked={b.stopId?selection.stops.includes(b.stopId):selection.otherCustomers.some(s=>s.id===b.id)} onChange={e=>toggle(b,e.target.checked)}/><span data-i18n-raw>{b.branchName||b.branchCode}</span></label>:<span data-i18n-raw>{b.branchName||b.branchCode}</span>}</td><td data-i18n-raw>{b.route||'—'}</td><td data-numeric><button type="button" className="reschedule-count" aria-label={d.title+' · '+(b.branchName||b.branchCode)+' · '+b.count} aria-expanded={expanded===b.id} onClick={()=>setExpanded(current=>current===b.id?null:b.id)}>{b.count} <span aria-hidden="true">{expanded===b.id?'▴':'▾'}</span></button></td></tr>{expanded===b.id&&<tr className="reschedule-detail-row"><td colSpan="3"><section data-i18n-raw><header><strong>{b.branchName||b.branchCode} · {d.title} ({b.count})</strong><button type="button" onClick={()=>setExpanded(null)}>{d.close}</button></header><p>{d.note}</p><div className="reschedule-detail-scroll"><table><thead><tr>{['from','to','reason','employee','approver','at','review'].map(key=><th key={key}>{d[key]}</th>)}</tr></thead><tbody>{(b.history||[]).map(item=><tr key={item.id}><td>{formatDateDisplay(item.sourceDate)}</td><td>{formatDateDisplay(item.targetDate)}</td><td>{item.reason||'—'}</td><td>{item.employeeName||'—'}</td><td>{item.approvedBy||'—'}</td><td>{approvalTime(item.approvedAt)}</td><td>{item.reviewReason||'—'}</td></tr>)}</tbody></table></div>{!b.history?.length&&<p>{d.empty}</p>}</section></td></tr>}</Fragment>)}</tbody></table>{!shown.length&&<p>{m.empty}</p>}</div><TableBottomScroll scrollRef={scrollRef}/></>}</section>
}
