import {useI18n} from './i18n.jsx'
import {formatDateDisplay} from './dateDisplay.js'
import './RescheduleReminder.css'
export const repeatWords={
 zh:{pending:'上次改期后尚未完成收货',count:n=>`连续${n}次改期，请优先处理`,review:n=>`本次为连续第${n}次批准改期`,last:'上次实际收货',unknown:'没有可确认的收货记录',days:n=>`已过去${n}天`,change:'上次改期',reason:'原因',onsite:'已到店，确认无货',unverified:'无货报告（未验证到店）',history:'查看改期与批准记录',confirm:'这是连续第2次批准改期，期间尚未完成收货，确定批准吗？',proof:'连续第3次及以后：请先与商家沟通，填写沟通结果并上传证明，才能批准。',name:'商家联系人',at:'沟通时间',result:'沟通结果及收货安排',photo:'沟通证明（必填）',proceed:'确定批准',cancel:'取消确认',stale:'改期次数已变化，请刷新后重新核对并确认。',required:'请填写商家联系人、有效沟通时间、沟通结果，并上传证明。',view:'查看沟通证明'},
 en:{pending:'Collection not completed since the last reschedule',count:n=>`${n} consecutive reschedules — prioritize collection`,review:n=>`Consecutive reschedule approval #${n}`,last:'Last completed collection',unknown:'No confirmed collection record',days:n=>`${n} days ago`,change:'Last reschedule',reason:'Reason',onsite:'Visited; no goods confirmed',unverified:'No-goods report (arrival not GPS-verified)',history:'Reschedule and approval history',confirm:'This is the second consecutive reschedule approval without a completed collection. Approve again?',proof:'Third and subsequent approvals require contacting the customer, recording the outcome and uploading proof.',name:'Customer contact',at:'Contact time',result:'Contact outcome and collection arrangement',photo:'Contact proof (required)',proceed:'Confirm approval',cancel:'Cancel confirmation',stale:'Reschedule count changed. Refresh, review and confirm again.',required:'Enter the customer contact, valid contact time and outcome, and upload proof.',view:'View contact proof'},
 ms:{pending:'Kutipan belum selesai sejak penjadualan semula terakhir',count:n=>`${n} kali berturut-turut dijadualkan semula — utamakan kutipan`,review:n=>`Kelulusan penjadualan semula kali ke-${n} berturut-turut`,last:'Kutipan terakhir selesai',unknown:'Tiada rekod kutipan yang disahkan',days:n=>`${n} hari lalu`,change:'Penjadualan semula terakhir',reason:'Sebab',onsite:'Sudah datang; disahkan tiada barang',unverified:'Laporan tiada barang (ketibaan belum disahkan GPS)',history:'Sejarah penjadualan dan kelulusan',confirm:'Ini kelulusan kali kedua berturut-turut tanpa kutipan selesai. Pasti mahu luluskan lagi?',proof:'Kelulusan kali ketiga dan seterusnya memerlukan penyelia menghubungi pelanggan, merekodkan hasil dan memuat naik bukti.',name:'Nama wakil pelanggan',at:'Masa dihubungi',result:'Hasil perbualan dan aturan kutipan',photo:'Bukti komunikasi (wajib)',proceed:'Sahkan kelulusan',cancel:'Batal pengesahan',stale:'Bilangan penjadualan semula telah berubah. Muat semula, semak dan sahkan lagi.',required:'Isi nama wakil pelanggan, masa yang sah, hasil perbualan dan muat naik bukti.',view:'Lihat bukti komunikasi'}
}
export default function RescheduleReminder({value,review=false}){
 const{language}=useI18n(),w=repeatWords[language]||repeatWords.en
 if(!value?.count)return null
 const n=value.count+(review?1:0),last=value.lastChange
 return <aside className={'reschedule-reminder '+(n>=2?'repeated':'first')}><strong>{review?w.review(n):n>=2?w.count(n):w.pending}</strong>{review&&<p>{w.pending}</p>}<p>{w.last}: {value.lastCollectionDate?formatDateDisplay(value.lastCollectionDate):w.unknown}{value.daysSinceCollection!=null?` · ${w.days(value.daysSinceCollection)}`:''}</p>{last&&<><p>{w.change}: {formatDateDisplay(last.sourceDate)} → {formatDateDisplay(last.targetDate)}</p><p>{w.reason}: <span data-i18n-raw>{last.reason}</span></p></>}{value.noGoods&&<p>{value.noGoods.verified?w.onsite:w.unverified} · {formatDateDisplay(value.noGoods.date)}</p>}{review&&<details><summary>{w.history}</summary>{value.history.map(r=><div key={r.id}><p>{formatDateDisplay(r.sourceDate)} → {formatDateDisplay(r.targetDate)}</p><p data-i18n-raw>{r.reason} · {r.approvedBy} · {r.reviewReason}</p>{r.contactName&&<p data-i18n-raw>{r.contactName} · {r.contactResult}</p>}{r.hasProof===1&&<a href={`/api/dispatch/date-requests/${r.id}/repeat-proof`} target="_blank" rel="noreferrer">{w.view}</a>}</div>)}</details>}</aside>
}
