import { useCallback, useEffect, useState } from 'react'
import './ResourcePage.css'

const api=async(url,options={})=>{const response=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const data=await response.json();if(!response.ok)throw new Error(data.error||'操作失败');return data}

export default function ResourcePage(){
  const[data,setData]=useState(null),[tab,setTab]=useState('vehicles'),[error,setError]=useState(''),[message,setMessage]=useState(''),[vehicle,setVehicle]=useState({vehicleCode:'',registrationNumber:'',capacityKg:''}),[employee,setEmployee]=useState({name:'',employeeCode:'',phone:'',jobRole:'driver'}),[location,setLocation]=useState({name:'',locationType:'depot',address:'',canStart:true,canEnd:true})
  const load=useCallback(()=>api('/api/resources').then(setData).catch(item=>setError(item.message)),[]);useEffect(()=>{load()},[load])
  const save=async(url,method,body)=>{setError('');setMessage('');try{await api(url,{method,body:JSON.stringify({...body,changedBy:'Supervisor'})});setMessage('主档已保存。相关已批准路线如受影响，会要求重新批准。');await load()}catch(item){setError(item.message)}}
  const addVehicle=async(event)=>{event.preventDefault();await save('/api/vehicles','POST',{...vehicle,capacityKg:vehicle.capacityKg?Number(vehicle.capacityKg):null});setVehicle({vehicleCode:'',registrationNumber:'',capacityKg:''})}
  const addEmployee=async(event)=>{event.preventDefault();await save('/api/employees','POST',employee);setEmployee({name:'',employeeCode:'',phone:'',jobRole:'driver'})}
  const addLocation=async(event)=>{event.preventDefault();await save('/api/locations','POST',location);setLocation({name:'',locationType:'depot',address:'',canStart:true,canEnd:true})}
  const editVehicle=(item)=>{const vehicleCode=prompt('Vehicle Code',item.vehicleCode);if(vehicleCode!=null)save(`/api/vehicles/${item.id}`,'PATCH',{vehicleCode})}
  const editEmployee=(item)=>{const name=prompt('Employee Name',item.name);if(name!=null)save(`/api/employees/${item.id}`,'PATCH',{name})}
  const editLocation=(item)=>{const name=prompt('Location Name',item.name);if(name!=null)save(`/api/locations/${item.id}`,'PATCH',{name})}
  return <div className="page resource-page"><div className="data-title"><em>MASTER DATA</em><h1>员工、车辆与地点</h1><p>派车页面只读取这里启用的主档；维修或停用车辆不会出现在当天车辆栏。</p></div>{message&&<div className="planner-message">✓ {message}</div>}{error&&<div className="data-error">{error}</div>}<div className="resource-tabs"><button className={tab==='vehicles'?'active':''} onClick={()=>setTab('vehicles')}>Vehicle Master</button><button className={tab==='employees'?'active':''} onClick={()=>setTab('employees')}>Employee Master</button><button className={tab==='locations'?'active':''} onClick={()=>setTab('locations')}>Location Master</button></div>{!data?<div className="data-loading">主档载入中…</div>:tab==='vehicles'?<VehicleMaster items={data.vehicles} form={vehicle} setForm={setVehicle} add={addVehicle} save={save} edit={editVehicle}/>:tab==='employees'?<EmployeeMaster items={data.employees} form={employee} setForm={setEmployee} add={addEmployee} save={save} edit={editEmployee}/>:<LocationMaster items={data.locations} form={location} setForm={setLocation} add={addLocation} save={save} edit={editLocation}/>}</div>
}

function VehicleMaster({items,form,setForm,add,save,edit}){return <MasterSection title="Vehicle Master" note="系统首次发现车辆主档为空时建立 Lorry 1–5；请补上实际车牌和载重。"><form onSubmit={add}><input required placeholder="Vehicle Code，例如 Lorry 6" value={form.vehicleCode} onChange={event=>setForm({...form,vehicleCode:event.target.value})}/><input placeholder="Registration Number" value={form.registrationNumber} onChange={event=>setForm({...form,registrationNumber:event.target.value})}/><input type="number" placeholder="Capacity kg" value={form.capacityKg} onChange={event=>setForm({...form,capacityKg:event.target.value})}/><button>新增车辆</button></form><div className="master-list master-vehicles">{items.map(item=><article key={item.id}><div><strong>{item.vehicleCode}</strong><small>{item.registrationNumber||'未填写车牌'} · {item.capacityKg?`${item.capacityKg} kg`:'未填写载重'}{item.isTemporary?' · 临时车辆':''}</small></div><select value={item.status} onChange={event=>save(`/api/vehicles/${item.id}`,'PATCH',{status:event.target.value})}><option value="available">启用／可用</option><option value="assigned">已分配</option><option value="maintenance">维修</option><option value="inactive">停用</option></select><button onClick={()=>edit(item)}>改名称</button></article>)}</div></MasterSection>}
function EmployeeMaster({items,form,setForm,add,save,edit}){return <MasterSection title="Employee Master" note="Driver 和 Assistant 都从启用员工中选择，不会按客户或 Area 自动产生。"><form onSubmit={add}><input required placeholder="Employee Name" value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/><input placeholder="Employee Code" value={form.employeeCode} onChange={event=>setForm({...form,employeeCode:event.target.value})}/><input placeholder="Phone" value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})}/><select value={form.jobRole} onChange={event=>setForm({...form,jobRole:event.target.value})}><option value="driver">Driver</option><option value="assistant">Assistant</option><option value="supervisor">Supervisor</option><option value="office">Office</option></select><button>新增员工</button></form><div className="master-list">{items.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.employeeCode||'无员工编号'} · {item.jobRole||'未设置职位'} · {item.phone||'无电话'}</small></div><button className={item.isActive?'state-on':'state-off'} onClick={()=>save(`/api/employees/${item.id}`,'PATCH',{isActive:!item.isActive})}>{item.isActive?'启用中':'已停用'}</button><button onClick={()=>edit(item)}>改名称</button></article>)}</div></MasterSection>}
function LocationMaster({items,form,setForm,add,save,edit}){return <MasterSection title="Location Master" note="用于车辆出发地点和结束地点，可分别启用 Start / End。"><form onSubmit={add}><input required placeholder="Location Name" value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/><select value={form.locationType} onChange={event=>setForm({...form,locationType:event.target.value})}>{['depot','parking','employee_home','factory','temporary','other'].map(item=><option key={item}>{item}</option>)}</select><input placeholder="Address" value={form.address} onChange={event=>setForm({...form,address:event.target.value})}/><label><input type="checkbox" checked={form.canStart} onChange={event=>setForm({...form,canStart:event.target.checked})}/> Start</label><label><input type="checkbox" checked={form.canEnd} onChange={event=>setForm({...form,canEnd:event.target.checked})}/> End</label><button>新增地点</button></form><div className="master-list">{items.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.locationType} · {item.address||'无地址'} · Start {item.canStart?'Yes':'No'} / End {item.canEnd?'Yes':'No'}</small></div><button className={item.isActive?'state-on':'state-off'} onClick={()=>save(`/api/locations/${item.id}`,'PATCH',{isActive:!item.isActive})}>{item.isActive?'启用中':'已停用'}</button><button onClick={()=>edit(item)}>改名称</button></article>)}</div></MasterSection>}
function MasterSection({title,note,children}){return <section className="master-section"><header><h2>{title}</h2><p>{note}</p></header>{children}</section>}
