import ExportDateDialog,{downloadArchive} from './ExportDateDialog.jsx'
import {formatDateDisplay} from './dateDisplay.js'
import DateInput from './DateInput.jsx'
import CenteredNotice from './CenteredNotice.jsx'
import {salesSafetyText} from './salesSafetyText.js'
import {createPortal} from 'react-dom'
import {isNumericColumn} from './numericColumns.js'
import {useCallback,useEffect,useRef,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest as api} from './apiClient.js'
import TableBottomScroll from './TableBottomScroll.jsx'
import {FilterHeader} from './ExpenseRecordsPage.jsx'
import ProofPhotoPicker from './ProofPhotoPicker.jsx'
import {proofData} from './paymentProofImage.js'
import {salesColumns,salesLineCents,mergeSalesRecognition,billKey,validSalesDate,canonicalSaleMaterial,salesDateNeedsConfirmation} from '../shared/sales.js'
import {formatWeight,formatUnitPrice,validWeight,validUnitPrice} from '../shared/measurePrecision.js'
import './SalesPage.css'
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuching',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const displayDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v))?v.slice(8)+'/'+v.slice(5,7)+'/'+v.slice(0,4):v
const emptyLine=()=>({deliveryDate:'',slipNumber:'',description:'OCC',weightKg:'',unitPrice:'',amount:''})
function findLineIssue(lines,settlementDate,t){
 const seen=new Map()
 for(let index=0;index<lines.length;index++){
  const line=lines[index],row=index+1,slip=String(line.slipNumber||'').trim(),description=String(line.description||'').trim()
  const problem=field=>({index,message:t('sales.fixLine',{row,field:t('sales.'+field)})})
  if(!validSalesDate(line.deliveryDate)||line.deliveryDate>settlementDate)return problem('deliveryDate')
  if(!slip||slip.length>100)return problem('slipNumber')
  const key=billKey(slip)
  if(seen.has(key))return{index,message:t('sales.duplicateSlip',{row,other:seen.get(key)})}
  seen.set(key,row)
  if(!description||description.length>300)return problem('description')
  for(const[field,pattern]of [['weightKg',/^\d{1,7}(\.\d{1,2})?$/],['unitPrice',/^\d{1,5}(\.\d{1,3})?$/],['amount',/^\d{1,10}(\.\d{1,2})?$/]]){
   const value=String(line[field]??'').trim()
   if(!pattern.test(value)||field!=='amount'&&Number(value)<=0)return problem(field)
  }
 }
 return null
}
export default function SalesPage({onBack}){
 const [showExport,setShowExport]=useState(false),[exportTarget,setExportTarget]=useState(null)
 useEffect(()=>{setExportTarget(document.getElementById('sales-header-export'))},[])
 const{t,language}=useI18n(),numberLabel=({zh:'卖货单号',en:'Sales No.',ms:'No. jualan'})[language]||'Sales No.',ref=useRef(null),request=useRef(0),[range]=useState(()=>({from:'',to:''})),[filters,setFilters]=useState({}),[sort,setSort]=useState({}),[open,setOpen]=useState(null),[data,setData]=useState(null),[form,setForm]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const safety=salesSafetyText[language]||salesSafetyText.en
 const [duplicate,setDuplicate]=useState(null)
 const historyKeys=['documentNumber','billNumber','settlementDate','deliveryDate','slipNumber']
 const query=new URLSearchParams({...range,columns:JSON.stringify(filters),sortKey:sort.key||'',sortDirection:sort.direction||''}).toString()
 const load=useCallback(async()=>{const id=++request.current;try{const d=await api('/api/sales?'+query);if(id===request.current)setData(d)}catch(e){if(id===request.current)setError(e.message)}},[query])
 useEffect(()=>{load();return()=>{request.current++}},[load])
 const edit=async id=>{setError('');setDuplicate(null);try{setForm(await api('/api/sales/'+id))}catch(e){setError(e.message)}}
 const save=async values=>{setBusy(true);setError('');setDuplicate(null);try{await api('/api/sales',{method:'POST',body:JSON.stringify({...values,proof:values.id?undefined:await proofData(values.proof)})});setForm(null);await load()}catch(e){setError(e.message);if(e.code==='SALES_DUPLICATE')setDuplicate(e.details?.duplicate||null);if(e.code==='SALES_DATE_CONFIRM')setError(safety.confirm(values.settlementDate))}finally{setBusy(false)}}
 return <div className="page purchase-archive expense-records sales-page"><div className="expense-toolbar">{exportTarget&&createPortal(<button className="record-icon-button" title={t('sales.export')} aria-label={t('sales.export')} onClick={()=>{setOpen(null);setShowExport(true)}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M12 15V3m-5 5 5-5 5 5M4 15v6h16v-6"/></svg></button>,exportTarget)}<button className={'sales-action-icon'+(form?' active':'')} title={t('sales.add')} aria-label={t('sales.add')} onClick={()=>{setError('');setForm({})}}>{t('sales.add').replace(/^[+＋]\s*/, '')}</button></div>
 {showExport&&<ExportDateDialog title={t('sales.export')} initialFrom={range.from} initialTo={range.to} onDownload={dates=>downloadArchive('/api/sales/export.xlsx?'+query,dates)} onClose={()=>setShowExport(false)}/>}<div className="archive-table" ref={ref}><table className="expense-table"><thead><tr>{salesColumns.map(k=><FilterHeader numeric={isNumericColumn(k)} key={k} matchOptionValue={historyKeys.includes(k)} optionSearchLabel={historyKeys.includes(k)?({zh:'搜索选项（全部日期）',en:'Find an option (all dates)',ms:'Cari pilihan (semua tarikh)'})[language]:'Find an option'} label={k==='documentNumber'?numberLabel:t('sales.'+k)} open={open===k} onOpen={()=>setOpen(k)} onClose={()=>setOpen(null)} value={filters[k]??null} options={(data?.filterOptions?.[k]||['']).map(v=>({value:v,label:v===''?t('sales.blank'):['settlementDate','deliveryDate'].includes(k)?displayDate(v):k==='weightKg'&&v?formatWeight(v):k==='unitPrice'&&v?formatUnitPrice(v):v}))} onChange={v=>setFilters({...filters,[k]:v})} sortDirection={sort.key===k?sort.direction:null} onSort={d=>setSort(d?{key:k,direction:d}:{})}/>) }<th>{t('sales.photo')}</th></tr></thead><tbody>{data?.items.map(row=><tr key={row.rowKey}>{salesColumns.map(k=><td data-numeric={isNumericColumn(k) || undefined} key={k} data-i18n-raw>{['billNumber','documentNumber'].includes(k)&&row[k]?<button className="sales-link" onClick={()=>edit(row.id)}>{row[k]}</button>:['settlementDate','deliveryDate'].includes(k)?displayDate(row[k]):k==='weightKg'&&row[k]?formatWeight(row[k]):k==='unitPrice'&&row[k]?formatUnitPrice(row[k]):row[k]||'—'}</td>)}<td><a href={'/api/sales/'+row.id+'/photo'} target="_blank" rel="noreferrer">{t('sales.view')}</a></td></tr>)}</tbody></table>{data&&!data.items.length&&<p>{t('sales.empty')}</p>}</div><TableBottomScroll scrollRef={ref}/>{form&&<SalesForm key={form.id||'new'} initial={form} masters={data||{}} busy={busy} onClose={()=>{if(!busy)setForm(null)}} onSave={save}/>} {error&&<SalesErrorDialog onClose={()=>{setError('');setDuplicate(null)}}>{error}{duplicate&&<div><p data-i18n-raw>{duplicate.documentNumber} · {duplicate.billNumber} · {formatDateDisplay(duplicate.settlementDate)}</p><button type="button" disabled={busy} onClick={()=>{if(window.confirm(safety.discard))edit(duplicate.id)}}>{safety.view}</button></div>}</SalesErrorDialog>}</div>
}
export function SalesForm({initial={},masters={},busy,onClose,onSave,error}){
 const{t,language}=useI18n(),lastAuto=useRef(initial.id?{}:{settlementDate:today(),lines:[emptyLine()]}),linesRef=useRef(null),[lineIssue,setLineIssue]=useState(null),[recognizedPreview,setRecognizedPreview]=useState(''),[recognition,setRecognition]=useState(null),[form,setForm]=useState({buyerId:'',vehicleId:'',billNumber:'',settlementDate:today(),total:'',rounding:'0.00',remarks:'',lines:[emptyLine()],...initial,reviewed:false}),[proof,setProof]=useState(null),[processing,setProcessing]=useState(false),[reading,setReading]=useState(false),[status,setStatus]=useState(''),[ocrError,setOcrError]=useState(''),[retry,setRetry]=useState(0),[preview,setPreview]=useState('')
 const update=(key,value)=>{delete lastAuto.current[key];setLineIssue(null);setForm(f=>({...f,[key]:value,reviewed:false}))}
 useEffect(()=>{if(!proof){setPreview('');return}const url=URL.createObjectURL(proof.blob);setPreview(url);return()=>URL.revokeObjectURL(url)},[proof])
 useEffect(()=>{let active=true;if(!proof){setRecognizedPreview('');setRecognition(null);return}setRecognizedPreview('');setRecognition(null);setReading(true);setStatus('reading');setOcrError('');setForm(f=>({...f,reviewed:false}));proofData(proof).then(p=>api('/api/sales/recognize',{method:'POST',body:JSON.stringify({proof:p})})).then(result=>{if(!active)return;setStatus(result.status);setRecognition(result);setRecognizedPreview(result.previewDataUrl||'');const previous=lastAuto.current;setForm(f=>mergeSalesRecognition(f,result.fields,previous));lastAuto.current=result.fields||{}}).catch(e=>{if(active){setOcrError(e.message);setStatus('unreadable')}}).finally(()=>{if(active)setReading(false)});return()=>{active=false}},[proof,retry])
 const salePrices=(masters.salePrices||[]).filter(item=>item.buyerId==null||String(item.buyerId)===String(form.buyerId))
 const productChoices=[...new Set(['OCC',...(masters.productNames||[]),...salePrices.map(item=>item.description),...form.lines.map(line=>line.description)].map(canonicalSaleMaterial).filter(Boolean))]
 const pricesFor=description=>[...new Set([...salePrices.filter(item=>canonicalSaleMaterial(item.description).toLowerCase()===canonicalSaleMaterial(description).toLowerCase()).map(item=>item.unitPrice),...form.lines.filter(line=>canonicalSaleMaterial(line.description).toLowerCase()===canonicalSaleMaterial(description).toLowerCase()).map(line=>line.unitPrice)].filter(Boolean).map(formatUnitPrice))]
 const changeLine=(index,k,value)=>{delete lastAuto.current.lines;setLineIssue(null);const options=k==='description'?pricesFor(value):[],suggestedPrice=options.length===1?options[0]:null;setForm(f=>({...f,reviewed:false,lines:f.lines.map((l,i)=>{if(i!==index)return l;const next={...l,[k]:value};if(k==='description')next.unitPrice=suggestedPrice||'';if((['weightKg','unitPrice'].includes(k)||k==='description')&&next.weightKg)next.amount=next.unitPrice?(salesLineCents(next.weightKg,next.unitPrice)/100).toFixed(2):'';return next})}))}
 const submit=e=>{e.preventDefault();if(locked||!matches||!form.reviewed||!initial.id&&!proof)return;const issue=findLineIssue(form.lines,form.settlementDate,t);if(issue){setLineIssue(issue);linesRef.current?.querySelectorAll('fieldset')[issue.index]?.scrollIntoView({block:'center',behavior:'smooth'});return}setLineIssue(null);if(salesDateNeedsConfirmation(form.settlementDate,today())&&!window.confirm((salesSafetyText[language]||salesSafetyText.en).confirm(form.settlementDate)))return;onSave({...form,proof,confirmedSettlementDate:form.settlementDate})}
 const sum=form.lines.reduce((n,l)=>n+Math.round(Number(l.amount||0)*100),0)+Math.round(Number(form.rounding||0)*100),matches=Math.round(Number(form.total)*100)===sum&&sum>0
 const locked=busy||processing||reading
 const photoUrl=initial.id?'/api/sales/'+initial.id+'/photo':recognizedPreview||preview
 return <div className="cash-modal sales-modal" role="dialog" aria-modal="true" aria-label={t('sales.title')}><form onSubmit={submit}><header><h2>{t('sales.title')}</h2><button type="button" disabled={locked} onClick={onClose}>×</button></header><div className="sales-review-grid"><div>{!initial.id&&<><ProofPhotoPicker preserveJpeg value={proof} onChange={setProof} onBusyChange={setProcessing} disabled={busy||reading}/>{status&&<p role="status">{t('sales.ocr.'+status)}</p>}{recognition?.rotation>0&&<p>{t('sales.rotated')}</p>}{recognition&&!form.buyerId&&<p role="status">{t('sales.factory.'+(recognition.factoryMatch||'unreadable'))}{recognition.fields?.factoryText&&<span data-i18n-raw> · {recognition.fields.factoryText}</span>}</p>}{proof&&!reading&&<button type="button" disabled={busy} onClick={()=>setRetry(x=>x+1)}>{t('sales.retry')}</button>}</>}{photoUrl&&<a href={photoUrl} target="_blank" rel="noreferrer"><img className="sales-proof" src={photoUrl} alt={t('sales.photo')}/></a>}{ocrError&&<CenteredNotice>{ocrError}</CenteredNotice>}<p>{t('sales.reviewHelp')}</p></div><div className="sales-fields">
 {['buyerId','vehicleId'].map(k=><label key={k}>{t(k==='buyerId'?'sales.buyerName':'sales.vehiclePlate')}<select required disabled={locked} value={form[k]} onChange={e=>update(k,e.target.value)}><option value="">{t('sales.select')}</option>{initial.id&&!(k==='buyerId'?masters.buyers||[]:masters.vehicles||[]).some(x=>String(x.id)===String(initial[k]))&&<option value={initial[k]}>{k==='buyerId'?initial.buyerName:initial.vehiclePlate}</option>}{(k==='buyerId'?masters.buyers||[]:masters.vehicles||[]).map(x=><option key={x.id} value={x.id}>{x.name||x.plate||x.code}</option>)}</select></label>)}
 {form.documentNumber&&<p data-i18n-raw><b>{form.documentNumber}</b></p>}{['billNumber','settlementDate','total','rounding','remarks'].map(k=><label key={k}>{t('sales.'+k)}<DateInput disabled={locked} required={k!=='remarks'} type={k==='settlementDate'?'date':['total','rounding'].includes(k)?'number':'text'} step={['total','rounding'].includes(k)?'.01':undefined} value={form[k]} onChange={e=>update(k,e.target.value)}/></label>)}
 </div></div><div className="sales-lines" ref={linesRef}>{form.lines.map((line,i)=><fieldset key={i}><legend>{t('sales.line')} {i+1}</legend>{['deliveryDate','slipNumber','description','weightKg','unitPrice','amount'].map(k=><label key={k}>{t('sales.'+k)}
  {k==='unitPrice'&&<datalist id={`sales-prices-${i}`}>{pricesFor(line.description).map(price=><option key={price} value={price} label={`RM ${formatUnitPrice(price)}/kg`}/>)}</datalist>}
 {k==='description'?<select required disabled={locked} value={line.description} onChange={e=>changeLine(i,'description',e.target.value)}><option value="">{t('sales.chooseProduct')}</option>{productChoices.map(name=><option key={name} value={name}>{name}</option>)}</select>:<DateInput required disabled={locked} type={k==='deliveryDate'?'date':['weightKg','amount'].includes(k)?'number':'text'} inputMode={k==='unitPrice'?'decimal':undefined} list={k==='description'?`sales-products-${i}`:k==='unitPrice'?`sales-prices-${i}`:undefined} placeholder={k==='description'?t('sales.chooseProduct'):k==='unitPrice'&&!line.unitPrice?t('sales.choosePrice'):undefined} step={k==='weightKg'?'.01':k==='amount'?'.01':undefined} value={line[k]} onChange={e=>changeLine(i,k,e.target.value)} onBlur={e=>{if(k==='description'){const normalized=canonicalSaleMaterial(e.target.value);if(normalized!==e.target.value)changeLine(i,k,normalized)}else if(k==='weightKg'&&validWeight(e.target.value))changeLine(i,k,formatWeight(e.target.value));else if(k==='unitPrice'&&validUnitPrice(e.target.value))changeLine(i,k,formatUnitPrice(e.target.value))}}/>}</label>)}{lineIssue?.index===i&&<CenteredNotice>{lineIssue.message}</CenteredNotice>}<button type="button" disabled={locked||form.lines.length===1} onClick={()=>update('lines',form.lines.filter((_,j)=>j!==i))}>{t('sales.remove')}</button></fieldset>)}</div><button type="button" disabled={locked||form.lines.length>=100} onClick={()=>update('lines',[...form.lines,emptyLine()])}>{t('sales.addLine')}</button><p>{t('sales.calculated')}: RM {(sum/100).toFixed(2)} {!matches&&t('sales.mismatch')}</p><label className="sales-confirm"><input type="checkbox" disabled={locked} checked={form.reviewed} onChange={e=>setForm({...form,reviewed:e.target.checked})}/>{t('sales.confirm')}</label>{error&&<CenteredNotice>{error}</CenteredNotice>}<footer><button type="button" disabled={locked} onClick={onClose}>{t('sales.cancel')}</button><button disabled={locked||!matches||!form.reviewed||!initial.id&&!proof}>{t('sales.save')}</button></footer></form></div>
}

export function SalesErrorDialog({children,onClose}){
 const {language}=useI18n(),panel=useRef(null),start=useRef(null)
 const close=({zh:'关闭',en:'Close',ms:'Tutup'})[language]||'Close',title=({zh:'提示',en:'Notice',ms:'Makluman'})[language]||'Notice'
 useEffect(()=>{const previous=document.activeElement;panel.current?.querySelector('button')?.focus();return()=>previous?.isConnected&&previous.focus()},[])
 return createPortal(<div className="sales-error-overlay" onPointerDown={e=>{start.current=e.target===e.currentTarget?{x:e.clientX,y:e.clientY}:null}} onClick={e=>{if(e.target===e.currentTarget&&start.current&&Math.hypot(e.clientX-start.current.x,e.clientY-start.current.y)<5)onClose();start.current=null}}><section ref={panel} className="sales-error-dialog" role="alertdialog" aria-modal="true" aria-labelledby="sales-error-title" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();onClose()}if(e.key==='Tab'){const buttons=[...panel.current.querySelectorAll('button:not(:disabled)')],first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><header><h2 id="sales-error-title">{title}</h2><button type="button" aria-label={close} onClick={onClose}>×</button></header><div className="sales-error-message">{children}</div><footer><button type="button" onClick={onClose}>{close}</button></footer></section></div>,document.body)
}
