import {useCallback,useEffect,useRef,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest as api} from './apiClient.js'
import BackButton from './BackButton.jsx'
import TableBottomScroll from './TableBottomScroll.jsx'
import {FilterHeader} from './ExpenseRecordsPage.jsx'
import ProofPhotoPicker from './ProofPhotoPicker.jsx'
import {proofData} from './paymentProofImage.js'
import {salesColumns,salesLineCents} from '../shared/sales.js'
import './SalesPage.css'
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuching',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const displayDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v))?v.slice(8)+'-'+v.slice(5,7)+'-'+v.slice(2,4):v
const emptyLine=()=>({deliveryDate:'',slipNumber:'',description:'',weightKg:'',unitPrice:'',amount:''})
export default function SalesPage({onBack}){
 const{t}=useI18n(),ref=useRef(null),request=useRef(0),[range,setRange]=useState({from:today().slice(0,7)+'-01',to:today()}),[filters,setFilters]=useState({}),[sort,setSort]=useState({}),[open,setOpen]=useState(null),[data,setData]=useState(null),[form,setForm]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const query=new URLSearchParams({...range,columns:JSON.stringify(filters),sortKey:sort.key||'',sortDirection:sort.direction||''}).toString()
 const load=useCallback(async()=>{const id=++request.current;try{const d=await api('/api/sales?'+query);if(id===request.current)setData(d)}catch(e){if(id===request.current)setError(e.message)}},[query])
 useEffect(()=>{load();return()=>{request.current++}},[load])
 const edit=async id=>{setError('');try{setForm(await api('/api/sales/'+id))}catch(e){setError(e.message)}}
 const save=async values=>{setBusy(true);setError('');try{await api('/api/sales',{method:'POST',body:JSON.stringify({...values,proof:values.id?undefined:await proofData(values.proof)})});setForm(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="page purchase-archive expense-records sales-page"><div className="expense-toolbar"><BackButton iconOnly fallback={onBack}/><button className={form?'active':''} onClick={()=>{setError('');setForm({})}}>{t('sales.add')}</button>{['from','to'].map(k=><label key={k}>{t('sales.'+k)}<input type="date" value={range[k]} onChange={e=>setRange({...range,[k]:e.target.value})}/></label>)}<button onClick={()=>window.location.href='/api/sales/export.xlsx?'+query}>{t('sales.export')}</button></div>{error&&!form&&<p role="alert" className="data-error">{error}</p>}
 <div className="archive-table" ref={ref}><table className="expense-table"><thead><tr>{salesColumns.map(k=><FilterHeader key={k} label={t('sales.'+k)} open={open===k} onOpen={()=>setOpen(k)} onClose={()=>setOpen(null)} value={filters[k]??null} options={(data?.filterOptions?.[k]||['']).map(v=>({value:v,label:v===''?t('sales.blank'):['settlementDate','deliveryDate'].includes(k)?displayDate(v):v}))} onChange={v=>setFilters({...filters,[k]:v})} sortDirection={sort.key===k?sort.direction:null} onSort={d=>setSort(d?{key:k,direction:d}:{})}/>) }<th>{t('sales.photo')}</th></tr></thead><tbody>{data?.items.map(row=><tr key={row.rowKey}>{salesColumns.map(k=><td key={k} data-i18n-raw>{k==='billNumber'?<button className="sales-link" onClick={()=>edit(row.id)}>{row[k]}</button>:['settlementDate','deliveryDate'].includes(k)?displayDate(row[k]):row[k]||'—'}</td>)}<td><a href={'/api/sales/'+row.id+'/photo'} target="_blank" rel="noreferrer">{t('sales.view')}</a></td></tr>)}</tbody></table>{data&&!data.items.length&&<p>{t('sales.empty')}</p>}</div><TableBottomScroll scrollRef={ref}/>{form&&<SalesForm key={form.id||'new'} initial={form} masters={data||{}} busy={busy} error={error} onClose={()=>{if(!busy)setForm(null)}} onSave={save}/>}</div>
}
export function SalesForm({initial={},masters={},busy,onClose,onSave,error}){
 const{t}=useI18n(),[form,setForm]=useState({buyerId:'',vehicleId:'',billNumber:'',settlementDate:'',total:'',rounding:'0.00',remarks:'',lines:[emptyLine()],...initial,reviewed:false}),[proof,setProof]=useState(null),[processing,setProcessing]=useState(false),[reading,setReading]=useState(false),[status,setStatus]=useState(''),[ocrError,setOcrError]=useState(''),[retry,setRetry]=useState(0),[preview,setPreview]=useState('')
 const update=(key,value)=>setForm(f=>({...f,[key]:value,reviewed:false}))
 useEffect(()=>{if(!proof){setPreview('');return}const url=URL.createObjectURL(proof.blob);setPreview(url);return()=>URL.revokeObjectURL(url)},[proof])
 useEffect(()=>{let active=true;if(!proof)return;setReading(true);setStatus('reading');setOcrError('');setForm(f=>({...f,reviewed:false}));proofData(proof).then(p=>api('/api/sales/recognize',{method:'POST',body:JSON.stringify({proof:p})})).then(result=>{if(!active)return;setStatus(result.status);setForm(f=>{const next={...f,reviewed:false};for(const k of ['buyerId','vehicleId','billNumber','settlementDate','total'])if(!next[k]&&result.fields?.[k])next[k]=result.fields[k];if(f.lines.length===1&&Object.values(f.lines[0]).every(v=>!v)&&result.fields?.lines?.length)next.lines=result.fields.lines;return next})}).catch(e=>{if(active){setOcrError(e.message);setStatus('unreadable')}}).finally(()=>{if(active)setReading(false)});return()=>{active=false}},[proof,retry])
 const changeLine=(index,k,value)=>setForm(f=>({...f,reviewed:false,lines:f.lines.map((l,i)=>{if(i!==index)return l;const next={...l,[k]:value};if(['weightKg','unitPrice'].includes(k)&&next.weightKg&&next.unitPrice)next.amount=(salesLineCents(next.weightKg,next.unitPrice)/100).toFixed(2);return next})}))
 const sum=form.lines.reduce((n,l)=>n+Math.round(Number(l.amount||0)*100),0)+Math.round(Number(form.rounding||0)*100),matches=Math.round(Number(form.total)*100)===sum&&sum>0
 const locked=busy||processing||reading
 const photoUrl=initial.id?'/api/sales/'+initial.id+'/photo':preview
 return <div className="cash-modal sales-modal" role="dialog" aria-modal="true" aria-label={t('sales.title')}><form onSubmit={e=>{e.preventDefault();if(!locked&&matches&&form.reviewed&&(initial.id||proof))onSave({...form,proof})}}><header><h2>{t('sales.title')}</h2><button type="button" disabled={locked} onClick={onClose}>×</button></header><div className="sales-review-grid"><div>{!initial.id&&<><ProofPhotoPicker value={proof} onChange={setProof} onBusyChange={setProcessing} disabled={busy||reading}/>{status&&<p role="status">{t('sales.ocr.'+status)}</p>}{proof&&!reading&&<button type="button" disabled={busy} onClick={()=>setRetry(x=>x+1)}>{t('sales.retry')}</button>}</>}{photoUrl&&<a href={photoUrl} target="_blank" rel="noreferrer"><img className="sales-proof" src={photoUrl} alt={t('sales.photo')}/></a>}{ocrError&&<p role="alert">{ocrError}</p>}<p>{t('sales.reviewHelp')}</p></div><div className="sales-fields">
 {['buyerId','vehicleId'].map(k=><label key={k}>{t(k==='buyerId'?'sales.buyerName':'sales.vehiclePlate')}<select required disabled={locked} value={form[k]} onChange={e=>update(k,e.target.value)}><option value="">{t('sales.select')}</option>{initial.id&&!(k==='buyerId'?masters.buyers||[]:masters.vehicles||[]).some(x=>String(x.id)===String(initial[k]))&&<option value={initial[k]}>{k==='buyerId'?initial.buyerName:initial.vehiclePlate}</option>}{(k==='buyerId'?masters.buyers||[]:masters.vehicles||[]).map(x=><option key={x.id} value={x.id}>{x.name||x.plate||x.code}</option>)}</select></label>)}
 {['billNumber','settlementDate','total','rounding','remarks'].map(k=><label key={k}>{t('sales.'+k)}<input disabled={locked} required={k!=='remarks'} type={k==='settlementDate'?'date':['total','rounding'].includes(k)?'number':'text'} step={['total','rounding'].includes(k)?'.01':undefined} value={form[k]} onChange={e=>update(k,e.target.value)}/></label>)}
 </div></div><div className="sales-lines">{form.lines.map((line,i)=><fieldset key={i}><legend>{t('sales.line')} {i+1}</legend>{['deliveryDate','slipNumber','description','weightKg','unitPrice','amount'].map(k=><label key={k}>{t('sales.'+k)}<input required disabled={locked} type={k==='deliveryDate'?'date':['weightKg','unitPrice','amount'].includes(k)?'number':'text'} step={k==='weightKg'?'.001':k==='unitPrice'?'.000001':k==='amount'?'.01':undefined} value={line[k]} onChange={e=>changeLine(i,k,e.target.value)}/></label>)}<button type="button" disabled={locked||form.lines.length===1} onClick={()=>update('lines',form.lines.filter((_,j)=>j!==i))}>{t('sales.remove')}</button></fieldset>)}</div><button type="button" disabled={locked||form.lines.length>=100} onClick={()=>update('lines',[...form.lines,emptyLine()])}>{t('sales.addLine')}</button><p>{t('sales.calculated')}: RM {(sum/100).toFixed(2)} {!matches&&t('sales.mismatch')}</p><label className="sales-confirm"><input type="checkbox" disabled={locked} checked={form.reviewed} onChange={e=>setForm({...form,reviewed:e.target.checked})}/>{t('sales.confirm')}</label>{error&&<p role="alert" className="data-error">{error}</p>}<footer><button type="button" disabled={locked} onClick={onClose}>{t('sales.cancel')}</button><button disabled={locked||!matches||!form.reviewed||!initial.id&&!proof}>{t('sales.save')}</button></footer></form></div>
}
