import RecordDownloadIcon from './RecordDownloadIcon.jsx'
import {useCallback,useEffect,useRef,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest as api} from './apiClient.js'
import BackButton from './BackButton.jsx'
import TableBottomScroll from './TableBottomScroll.jsx'
import {FilterHeader} from './ExpenseRecordsPage.jsx'
import ProofPhotoPicker from './ProofPhotoPicker.jsx'
import {proofData} from './paymentProofImage.js'
import {salesColumns,salesLineCents,mergeSalesRecognition,billKey,validSalesDate} from '../shared/sales.js'
import './SalesPage.css'
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuching',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const displayDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v))?v.slice(8)+'-'+v.slice(5,7)+'-'+v.slice(2,4):v
const emptyLine=()=>({deliveryDate:'',slipNumber:'',description:'',weightKg:'',unitPrice:'',amount:''})
function findLineIssue(lines,settlementDate,t){
 const seen=new Map()
 for(let index=0;index<lines.length;index++){
  const line=lines[index],row=index+1,slip=String(line.slipNumber||'').trim(),description=String(line.description||'').trim()
  const problem=field=>({index,message:t('sales.fixLine',{row,field:t('sales.'+field)})})
  if(!validSalesDate(line.deliveryDate)||line.deliveryDate>settlementDate)return problem('deliveryDate')
  if(!slip||slip.length>100)return problem('slipNumber')
  const key=billKey(slip)
  if(seen.has(key))return{index,message:t('sales.duplicateSlip',{row,other:seen.get(key)})}
  seen.set(key,row)
  if(!description||description.length>300)return problem('description')
  for(const[field,pattern]of [['weightKg',/^\d{1,7}(\.\d{1,3})?$/],['unitPrice',/^\d{1,5}(\.\d{1,6})?$/],['amount',/^\d{1,10}(\.\d{1,2})?$/]]){
   const value=String(line[field]??'').trim()
   if(!pattern.test(value)||field!=='amount'&&Number(value)<=0)return problem(field)
  }
 }
 return null
}
export default function SalesPage({onBack}){
 const{t,language}=useI18n(),numberLabel=({zh:'卖货单号',en:'Sales No.',ms:'No. jualan'})[language]||'Sales No.',ref=useRef(null),request=useRef(0),[range,setRange]=useState({from:today().slice(0,7)+'-01',to:today()}),[filters,setFilters]=useState({}),[sort,setSort]=useState({}),[open,setOpen]=useState(null),[data,setData]=useState(null),[form,setForm]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const query=new URLSearchParams({...range,columns:JSON.stringify(filters),sortKey:sort.key||'',sortDirection:sort.direction||''}).toString()
 const load=useCallback(async()=>{const id=++request.current;try{const d=await api('/api/sales?'+query);if(id===request.current)setData(d)}catch(e){if(id===request.current)setError(e.message)}},[query])
 useEffect(()=>{load();return()=>{request.current++}},[load])
 const edit=async id=>{setError('');try{setForm(await api('/api/sales/'+id))}catch(e){setError(e.message)}}
 const save=async values=>{setBusy(true);setError('');try{await api('/api/sales',{method:'POST',body:JSON.stringify({...values,proof:values.id?undefined:await proofData(values.proof)})});setForm(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="page purchase-archive expense-records sales-page"><div className="expense-toolbar"><BackButton iconOnly fallback={onBack}/><button className={form?'active':''} onClick={()=>{setError('');setForm({})}}>{t('sales.add')}</button>{['from','to'].map(k=><label key={k}>{t('sales.'+k)}<input type="date" value={range[k]} onChange={e=>setRange({...range,[k]:e.target.value})}/></label>)}<button className="record-icon-button" title={t('sales.export')} aria-label={t('sales.export')} onClick={()=>window.location.href='/api/sales/export.xlsx?'+query}><RecordDownloadIcon/></button></div>{error&&!form&&<p role="alert" className="data-error">{error}</p>}
 <div className="archive-table" ref={ref}><table className="expense-table"><thead><tr>{salesColumns.map(k=><FilterHeader key={k} label={k==='documentNumber'?numberLabel:t('sales.'+k)} open={open===k} onOpen={()=>setOpen(k)} onClose={()=>setOpen(null)} value={filters[k]??null} options={(data?.filterOptions?.[k]||['']).map(v=>({value:v,label:v===''?t('sales.blank'):['settlementDate','deliveryDate'].includes(k)?displayDate(v):v}))} onChange={v=>setFilters({...filters,[k]:v})} sortDirection={sort.key===k?sort.direction:null} onSort={d=>setSort(d?{key:k,direction:d}:{})}/>) }<th>{t('sales.photo')}</th></tr></thead><tbody>{data?.items.map(row=><tr key={row.rowKey}>{salesColumns.map(k=><td key={k} data-i18n-raw>{['billNumber','documentNumber'].includes(k)&&row[k]?<button className="sales-link" onClick={()=>edit(row.id)}>{row[k]}</button>:['settlementDate','deliveryDate'].includes(k)?displayDate(row[k]):row[k]||'—'}</td>)}<td><a href={'/api/sales/'+row.id+'/photo'} target="_blank" rel="noreferrer">{t('sales.view')}</a></td></tr>)}</tbody></table>{data&&!data.items.length&&<p>{t('sales.empty')}</p>}</div><TableBottomScroll scrollRef={ref}/>{form&&<SalesForm key={form.id||'new'} initial={form} masters={data||{}} busy={busy} error={error} onClose={()=>{if(!busy)setForm(null)}} onSave={save}/>}</div>
}
export function SalesForm({initial={},masters={},busy,onClose,onSave,error}){
 const{t}=useI18n(),lastAuto=useRef({}),linesRef=useRef(null),[lineIssue,setLineIssue]=useState(null),[recognizedPreview,setRecognizedPreview]=useState(''),[recognition,setRecognition]=useState(null),[form,setForm]=useState({buyerId:'',vehicleId:'',billNumber:'',settlementDate:'',total:'',rounding:'0.00',remarks:'',lines:[emptyLine()],...initial,reviewed:false}),[proof,setProof]=useState(null),[processing,setProcessing]=useState(false),[reading,setReading]=useState(false),[status,setStatus]=useState(''),[ocrError,setOcrError]=useState(''),[retry,setRetry]=useState(0),[preview,setPreview]=useState('')
 const update=(key,value)=>{delete lastAuto.current[key];setLineIssue(null);setForm(f=>({...f,[key]:value,reviewed:false}))}
 useEffect(()=>{if(!proof){setPreview('');return}const url=URL.createObjectURL(proof.blob);setPreview(url);return()=>URL.revokeObjectURL(url)},[proof])
 useEffect(()=>{let active=true;if(!proof){setRecognizedPreview('');setRecognition(null);return}setRecognizedPreview('');setRecognition(null);setReading(true);setStatus('reading');setOcrError('');setForm(f=>({...f,reviewed:false}));proofData(proof).then(p=>api('/api/sales/recognize',{method:'POST',body:JSON.stringify({proof:p})})).then(result=>{if(!active)return;setStatus(result.status);setRecognition(result);setRecognizedPreview(result.previewDataUrl||'');const previous=lastAuto.current;setForm(f=>mergeSalesRecognition(f,result.fields,previous));lastAuto.current=result.fields||{}}).catch(e=>{if(active){setOcrError(e.message);setStatus('unreadable')}}).finally(()=>{if(active)setReading(false)});return()=>{active=false}},[proof,retry])
 const salePrices=(masters.salePrices||[]).filter(item=>item.buyerId==null||String(item.buyerId)===String(form.buyerId))
 const productChoices=[...new Set([...(masters.productNames||[]),...salePrices.map(item=>item.description),...form.lines.map(line=>line.description)].filter(Boolean))]
 const pricesFor=description=>[...new Set([...salePrices.filter(item=>item.description.toLowerCase()===String(description||'').trim().toLowerCase()).map(item=>item.unitPrice),...form.lines.filter(line=>line.description.toLowerCase()===String(description||'').trim().toLowerCase()).map(line=>line.unitPrice)].filter(Boolean))]
 const changeLine=(index,k,value)=>{delete lastAuto.current.lines;setLineIssue(null);const options=k==='description'?pricesFor(value):[],suggestedPrice=options.length===1?options[0]:null;setForm(f=>({...f,reviewed:false,lines:f.lines.map((l,i)=>{if(i!==index)return l;const next={...l,[k]:value};if(k==='description')next.unitPrice=suggestedPrice||'';if((['weightKg','unitPrice'].includes(k)||k==='description')&&next.weightKg)next.amount=next.unitPrice?(salesLineCents(next.weightKg,next.unitPrice)/100).toFixed(2):'';return next})}))}
 const submit=e=>{e.preventDefault();if(locked||!matches||!form.reviewed||!initial.id&&!proof)return;const issue=findLineIssue(form.lines,form.settlementDate,t);if(issue){setLineIssue(issue);linesRef.current?.querySelectorAll('fieldset')[issue.index]?.scrollIntoView({block:'center',behavior:'smooth'});return}setLineIssue(null);onSave({...form,proof})}
 const sum=form.lines.reduce((n,l)=>n+Math.round(Number(l.amount||0)*100),0)+Math.round(Number(form.rounding||0)*100),matches=Math.round(Number(form.total)*100)===sum&&sum>0
 const locked=busy||processing||reading
 const photoUrl=initial.id?'/api/sales/'+initial.id+'/photo':recognizedPreview||preview
 return <div className="cash-modal sales-modal" role="dialog" aria-modal="true" aria-label={t('sales.title')}><form onSubmit={submit}><header><h2>{t('sales.title')}</h2><button type="button" disabled={locked} onClick={onClose}>×</button></header><div className="sales-review-grid"><div>{!initial.id&&<><ProofPhotoPicker preserveJpeg value={proof} onChange={setProof} onBusyChange={setProcessing} disabled={busy||reading}/>{status&&<p role="status">{t('sales.ocr.'+status)}</p>}{recognition?.rotation>0&&<p>{t('sales.rotated')}</p>}{recognition&&!form.buyerId&&<p role="status">{t('sales.factory.'+(recognition.factoryMatch||'unreadable'))}{recognition.fields?.factoryText&&<span data-i18n-raw> · {recognition.fields.factoryText}</span>}</p>}{proof&&!reading&&<button type="button" disabled={busy} onClick={()=>setRetry(x=>x+1)}>{t('sales.retry')}</button>}</>}{photoUrl&&<a href={photoUrl} target="_blank" rel="noreferrer"><img className="sales-proof" src={photoUrl} alt={t('sales.photo')}/></a>}{ocrError&&<p role="alert">{ocrError}</p>}<p>{t('sales.reviewHelp')}</p></div><div className="sales-fields">
 {['buyerId','vehicleId'].map(k=><label key={k}>{t(k==='buyerId'?'sales.buyerName':'sales.vehiclePlate')}<select required disabled={locked} value={form[k]} onChange={e=>update(k,e.target.value)}><option value="">{t('sales.select')}</option>{initial.id&&!(k==='buyerId'?masters.buyers||[]:masters.vehicles||[]).some(x=>String(x.id)===String(initial[k]))&&<option value={initial[k]}>{k==='buyerId'?initial.buyerName:initial.vehiclePlate}</option>}{(k==='buyerId'?masters.buyers||[]:masters.vehicles||[]).map(x=><option key={x.id} value={x.id}>{x.name||x.plate||x.code}</option>)}</select></label>)}
 {form.documentNumber&&<p data-i18n-raw><b>{form.documentNumber}</b></p>}{['billNumber','settlementDate','total','rounding','remarks'].map(k=><label key={k}>{t('sales.'+k)}<input disabled={locked} required={k!=='remarks'} type={k==='settlementDate'?'date':['total','rounding'].includes(k)?'number':'text'} step={['total','rounding'].includes(k)?'.01':undefined} value={form[k]} onChange={e=>update(k,e.target.value)}/></label>)}
 </div></div><div className="sales-lines" ref={linesRef}>{form.lines.map((line,i)=><fieldset key={i}><legend>{t('sales.line')} {i+1}</legend>{['deliveryDate','slipNumber','description','weightKg','unitPrice','amount'].map(k=><label key={k}>{t('sales.'+k)}
 {k==='description'&&<select className="sales-choice" disabled={locked} value="" onChange={e=>changeLine(i,k,e.target.value)}><option value="">{t('sales.chooseProduct')}</option>{productChoices.map(name=><option key={name} value={name}>{name}</option>)}</select>}
 {k==='unitPrice'&&<select className="sales-choice" disabled={locked||!pricesFor(line.description).length} value={pricesFor(line.description).includes(line.unitPrice)?line.unitPrice:''} onChange={e=>changeLine(i,k,e.target.value)}><option value="">{t('sales.choosePrice')}</option>{pricesFor(line.description).map(price=><option key={price} value={price}>RM {price}/kg</option>)}</select>}
 <input required disabled={locked} type={k==='deliveryDate'?'date':['weightKg','unitPrice','amount'].includes(k)?'number':'text'} step={k==='weightKg'?'.001':k==='unitPrice'?'.000001':k==='amount'?'.01':undefined} value={line[k]} onChange={e=>changeLine(i,k,e.target.value)}/></label>)}{lineIssue?.index===i&&<p role="alert" className="data-error">{lineIssue.message}</p>}<button type="button" disabled={locked||form.lines.length===1} onClick={()=>update('lines',form.lines.filter((_,j)=>j!==i))}>{t('sales.remove')}</button></fieldset>)}</div><button type="button" disabled={locked||form.lines.length>=100} onClick={()=>update('lines',[...form.lines,emptyLine()])}>{t('sales.addLine')}</button><p>{t('sales.calculated')}: RM {(sum/100).toFixed(2)} {!matches&&t('sales.mismatch')}</p><label className="sales-confirm"><input type="checkbox" disabled={locked} checked={form.reviewed} onChange={e=>setForm({...form,reviewed:e.target.checked})}/>{t('sales.confirm')}</label>{error&&<p role="alert" className="data-error">{error}</p>}<footer><button type="button" disabled={locked} onClick={onClose}>{t('sales.cancel')}</button><button disabled={locked||!matches||!form.reviewed||!initial.id&&!proof}>{t('sales.save')}</button></footer></form></div>
}
