import {useUi} from './i18n.jsx'
import {useEffect,useRef,useState} from 'react'
import {apiRequest as api} from './apiClient.js'
import {collectHighAccuracyPosition} from './highAccuracyGps.js'
import GoogleMapPreview from './GoogleMapPreview.jsx'
import {parseCoordinates,validCoordinatePair} from './gpsCoordinates.js'
import './SharedGpsInput.css'
import FormActionBar from './FormActionBar.jsx'

export default function SharedGpsInput({resetKey='',...props}){return <SharedGpsInputState key={resetKey||'shared-gps-input'} {...props}/>}

function SharedGpsInputState({latitude='',longitude='',address='',gpsSource='',onChange,allowDevice=true,readOnly=false,className=''}){
  const ui=useUi()

  const[paste,setPaste]=useState(''),[mapSearch,setMapSearch]=useState(address||''),[candidates,setCandidates]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[pickerOpen,setPickerOpen]=useState(false),[draft,setDraft]=useState({latitude:String(latitude??''),longitude:String(longitude??''),address}),[draftSource,setDraftSource]=useState(gpsSource||'')
  const generation=useRef(0)
  useEffect(()=>setDraft({latitude:String(latitude??''),longitude:String(longitude??''),address}),[latitude,longitude,address])
  useEffect(()=>{if(address&&!mapSearch.trim())setMapSearch(address)},[address,mapSearch])
  useEffect(()=>()=>{generation.current+=1},[])
  const reverse=async(position,source,commit=true)=>{const requestGeneration=generation.current;setBusy('address');setError('');try{const result=await api(`/api/gps-collection/reverse-geocode?latitude=${encodeURIComponent(position.latitude)}&longitude=${encodeURIComponent(position.longitude)}`);if(requestGeneration!==generation.current)return;const next={...position,address:result.address||'',addressComponents:result,gpsSource:source};setDraft(current=>({...current,...next}));setDraftSource(source);if(commit)onChange(next)}catch(item){if(requestGeneration!==generation.current)return;setError(ui("Coordinates kept; address lookup failed: {0}", {0: item.message}));const next={...position,gpsSource:source};setDraft(current=>({...current,...next}));setDraftSource(source);if(commit)onChange(next)}finally{if(requestGeneration===generation.current)setBusy('')}}
  const commitManual=async()=>{try{const position=parseCoordinates(paste);await reverse(position,'manual_coordinates')}catch(item){setError(item.message)}}
  const updateField=(key,value)=>{setDraft(current=>({...current,[key]:value}));setError('');const next={...draft,[key]:value};if(validCoordinatePair(next.latitude,next.longitude))void reverse({latitude:next.latitude,longitude:next.longitude},'manual_coordinates')}
  const getDevice=async()=>{setBusy('gps');setError('');try{const reading=await collectHighAccuracyPosition(navigator.geolocation);await reverse({latitude:reading.latitude,longitude:reading.longitude},'device')}catch(item){setError(item.message)}finally{setBusy('')}}
  const select=position=>{setDraft(current=>({...current,...position}));setDraftSource('map_selection');void reverse(position,'map_selection',false)}
  const chooseCandidate=async candidate=>{setCandidates([]);setMapSearch(candidate.address);await reverse({latitude:candidate.latitude,longitude:candidate.longitude},'map_selection',false)}
  const searchMap=async(query=mapSearch)=>{if(!query.trim())return setError(ui("Enter an address to search"));const requestGeneration=generation.current;setBusy('search');setError('');setCandidates([]);try{const result=await api(`/api/gps-collection/geocode?address=${encodeURIComponent(query.trim())}`),items=result.candidates||[];if(requestGeneration!==generation.current)return;if(items.length===1)await chooseCandidate(items[0]);else setCandidates(items)}catch(item){if(requestGeneration===generation.current)setError(item.message)}finally{if(requestGeneration===generation.current)setBusy('')}}
  const findAddress=()=>{const query=String(address||draft.address||'').trim();setPickerOpen(true);setMapSearch(query);if(query)void searchMap(query)}
  const useLocation=()=>{if(!validCoordinatePair(draft.latitude,draft.longitude))return setError(ui("Select a valid location on the map"));onChange({...draft,gpsSource:'map_selection'});setPickerOpen(false)}
  return <section className={`shared-gps-input ${className}`.trim()}>
    <div className="shared-gps-coordinates"><label>{ui("Latitude")}<input aria-label={ui("Latitude")} inputMode="decimal" readOnly={readOnly} value={draft.latitude} onChange={event=>updateField('latitude',event.target.value)}/></label><label>{ui("Longitude")}<input aria-label={ui("Longitude")} inputMode="decimal" readOnly={readOnly} value={draft.longitude} onChange={event=>updateField('longitude',event.target.value)}/></label></div>
    {!readOnly&&<><label className="shared-gps-paste">{ui("Paste Coordinates")}<input value={paste} placeholder="" onChange={event=>setPaste(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();void commitManual()}}}/></label><div className="shared-gps-actions">{allowDevice&&<button type="button" disabled={Boolean(busy)} onClick={getDevice}>{busy==='gps'?ui("Getting GPS…"):ui("Get Current GPS")}</button>}<button type="button" disabled={!paste.trim()||Boolean(busy)} onClick={commitManual}>{ui("Use Pasted Coordinates")}</button><button type="button" disabled={!String(address||draft.address||'').trim()||Boolean(busy)} onClick={findAddress}>{ui("Find on Map")}</button><button type="button" onClick={()=>setPickerOpen(true)}>{ui("Select on Map")}</button></div></>}
    <small>{ui("GPS Source:")}{draftSource||ui("Not set")}</small>{busy==='address'&&<small>{ui("Finding address…")}</small>}{error&&<div className="data-error" role="alert">{ui(error)}</div>}
    {pickerOpen&&<div className="shared-gps-map-dialog" role="dialog" aria-modal="true" aria-label={ui("Select GPS on map")}><div><header><h3>{ui("Select on Map")}</h3><button type="button" onClick={()=>setPickerOpen(false)}>×</button></header><div className="shared-gps-map-search"><input aria-label={ui("Search map")} placeholder={ui("Search address or place")} value={mapSearch} onChange={event=>setMapSearch(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();void searchMap()}}}/><button type="button" disabled={busy==='search'} onClick={()=>searchMap()}>{busy==='search'?ui("Searching…"):ui("Find on Map")}</button></div>{candidates.length>1&&<div className="shared-gps-candidates" role="list" aria-label={ui("Address search results")}>{candidates.map(candidate=><button type="button" role="listitem" key={candidate.id} onClick={()=>chooseCandidate(candidate)}><b><span data-i18n-raw>{candidate.name}</span></b><span><span data-i18n-raw>{candidate.address}</span></span></button>)}</div>}<GoogleMapPreview latitude={draft.latitude} longitude={draft.longitude} initialCenter={{lat:1.5533,lng:110.3592}} onMapClick={select} onPositionAdjusted={select}/><small>{ui("Search, pan or zoom, switch Map / Satellite, then click the map or drag the marker.")}</small><FormActionBar><button type="button" onClick={()=>setPickerOpen(false)}>{ui("Cancel")}</button><button type="button" className="primary" disabled={!validCoordinatePair(draft.latitude,draft.longitude)||Boolean(busy)} onClick={useLocation}>{ui("Use This Location")}</button></FormActionBar></div></div>}
  </section>
}
