import { useCallback, useEffect, useState } from 'react'
import {kuchingDate} from '../shared/kuchingTime.js'

const today=kuchingDate
const api=async(url,options={})=>{const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const x=await r.json();if(!r.ok)throw new Error(x.error||'操作失败');return x}
const statuses={new:'新请求',awaiting_supervisor:'等待主管',awaiting_customer_account:'等待建立账号',scheduled:'已排车',approved:'已批准',published:'已发布',completed:'已完成',rejected:'已拒绝',cancelled:'已取消'}

export default function SpecialRequestsPage({onOpenPlanner,currentUser}){
  const[items,setItems]=useState([]),[pendingLocations,setPendingLocations]=useState([]),[search,setSearch]=useState(''),[nearby,setNearby]=useState({latitude:'',longitude:''}),[matches,setMatches]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[form,setForm]=useState({requestedCollectionDate:today(),createdBy:currentUser.name,locationSource:'Customer WhatsApp',promisedToCustomer:false})
  const load=useCallback(()=>Promise.all([api('/api/special-requests'),api('/api/temporary-locations?status=pending_supervisor')]).then(([requests,locations])=>{setItems(requests.items);setPendingLocations(locations.items)}).catch(e=>setError(e.message)),[]);useEffect(()=>{load()},[load])
  const find=async()=>{try{const q=new URLSearchParams({search});if(nearby.latitude&&nearby.longitude){q.set('latitude',nearby.latitude);q.set('longitude',nearby.longitude);q.set('radiusMeters','3000')}setMatches((await api(`/api/special-requests/customer-search?${q}`)).items)}catch(e){setError(e.message)}}
  const submit=async(e)=>{e.preventDefault();setError('');try{const result=await api('/api/special-requests',{method:'POST',body:JSON.stringify({...form,existingBranchId:selected?.internalId,temporaryLatitude:form.temporaryLatitude?Number(form.temporaryLatitude):undefined,temporaryLongitude:form.temporaryLongitude?Number(form.temporaryLongitude):undefined,estimatedWeightKg:form.estimatedWeightKg?Number(form.estimatedWeightKg):undefined})});setMessage(result.deduplicated?'相同请求已经存在，未重复建立。':'临时收货请求已建立。');setSelected(null);load()}catch(e2){setError(e2.message)}}
  const schedule=async(item)=>{const date=prompt('安排日期（YYYY-MM-DD）',item.requestedCollectionDate);if(!date)return;try{await api(`/api/special-requests/${item.id}/schedule`,{method:'POST',body:JSON.stringify({date,tripNumber:1,scheduledBy:currentUser.name})});setMessage('请求已加入指定日期草稿；如果该日已批准，系统已要求重新批准。');load()}catch(e){setError(e.message)}}
  const adopt=async(location)=>{try{const result=await api(`/api/temporary-locations/${location.id}/adopt`,{method:'POST',body:JSON.stringify({adoptedBy:currentUser.name})});setMessage(result.distanceWarning?'已采用为正式 GPS，但与原 GPS 相距超过 500m，请再次核对。':'已由主管采用为正式 GPS。');load()}catch(e){setError(e.message)}}
  return <div className="page special-page"><div className="planner-title"><div><em>SPECIAL COLLECTION REQUESTS</em><h1>临时收货请求</h1><p>先查找现有分店；找不到才建立潜在新客户，并在发布前补齐 Jodoo 正式账号。</p></div><button onClick={onOpenPlanner}>查看一周排车</button></div>{message&&<div className="planner-message">✓ {message}</div>}{error&&<div className="data-error">{error}</div>}
    <div className="special-layout"><form className="request-form" onSubmit={submit}><h2>建立请求</h2><label>先搜索现有客户／分店<div className="search-row"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="名称、CustomerID、BranchID、电话、地址"/><button type="button" onClick={find}>搜索</button></div></label><div className="nearby-search"><span>GPS 附近（3km）</span><input type="number" step="any" placeholder="Latitude" value={nearby.latitude} onChange={e=>setNearby({...nearby,latitude:e.target.value})}/><input type="number" step="any" placeholder="Longitude" value={nearby.longitude} onChange={e=>setNearby({...nearby,longitude:e.target.value})}/><button type="button" onClick={find}>查附近</button></div>{matches.length>0&&<div className="customer-matches">{matches.map(x=><button type="button" className={selected?.internalId===x.internalId?'selected':''} key={x.internalId} onClick={()=>setSelected(x)}><b>{x.customerName} · {x.branchName}</b><small>{x.customerId} / {x.branchId} · {x.area||'未分区'} · {x.paymentType||'未设付款'} · RM {x.occPrice??'—'}{x.distanceMeters!=null?` · ${Math.round(x.distanceMeters)}m`:''}</small></button>)}</div>}{selected?<div className="selected-customer"><b>Existing Customer Request</b><span>{selected.customerId} / {selected.branchId}</span><small>{selected.paymentType} · OCC {selected.occPrice} · GPS {selected.latitude??'—'}, {selected.longitude??'—'}</small><button type="button" onClick={()=>setSelected(null)}>改为新客户</button></div>:<><h3>Potential New Customer</h3><label>临时客户名称<input required value={form.temporaryCustomerName||''} onChange={e=>setForm({...form,temporaryCustomerName:e.target.value})}/></label><div className="form-grid"><label>联系人<input value={form.contactPerson||''} onChange={e=>setForm({...form,contactPerson:e.target.value})}/></label><label>电话<input value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>WhatsApp<input value={form.whatsapp||''} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></label><label>Location 来源<select value={form.locationSource} onChange={e=>setForm({...form,locationSource:e.target.value})}>{['Customer WhatsApp','Customer Phone','Manual Entry','Driver Captured','Supervisor Confirmed'].map(x=><option key={x}>{x}</option>)}</select></label><label>临时 Latitude<input type="number" step="any" value={form.temporaryLatitude||''} onChange={e=>setForm({...form,temporaryLatitude:e.target.value})}/></label><label>临时 Longitude<input type="number" step="any" value={form.temporaryLongitude||''} onChange={e=>setForm({...form,temporaryLongitude:e.target.value})}/></label></div><label>地址<textarea value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Google Maps / Location Link<input value={form.locationLink||''} onChange={e=>setForm({...form,locationLink:e.target.value})}/></label></>}
      <div className="form-grid"><label>要求收货日期<input required type="date" value={form.requestedCollectionDate} onChange={e=>setForm({...form,requestedCollectionDate:e.target.value})}/></label><label>预计重量（kg）<input type="number" value={form.estimatedWeightKg||''} onChange={e=>setForm({...form,estimatedWeightKg:e.target.value})}/></label><label>登记来源<select value={form.createdBy} onChange={e=>setForm({...form,createdBy:e.target.value})}>{['Office','Supervisor','Driver','Phone','WhatsApp'].map(x=><option key={x}>{x}</option>)}</select></label><label className="promise-check"><input type="checkbox" checked={form.promisedToCustomer} onChange={e=>setForm({...form,promisedToCustomer:e.target.checked})}/> 已承诺客户</label></div><label>特别要求／备注<textarea value={form.specialRequirement||''} onChange={e=>setForm({...form,specialRequirement:e.target.value})}/></label><button className="submit-request">建立临时请求</button></form>
      <section className="request-list"><div><h2>请求清单</h2><span>{items.length} 笔</span></div>{pendingLocations.length>0&&<div className="gps-review"><h3>现场 GPS 待主管确认</h3>{pendingLocations.map(x=><p key={x.id}><span><b>{x.branchName||x.temporaryCustomerName||'未连接分店'}</b><small>{x.latitude}, {x.longitude} · {x.location_source}</small></span><button onClick={()=>adopt(x)}>采用为正式 GPS</button></p>)}</div>}{items.map(item=><article className={item.promisedToCustomer?'promised':''} key={item.id}><header><span>{item.promisedToCustomer?'客户承诺':'一般请求'}</span><b>{statuses[item.status]||item.status}</b></header><h3>{item.customerName||item.temporaryCustomerName||item.branchName}</h3><p>{item.requestType==='existing'?'Existing Customer Request':'Potential New Customer'} · {item.requestedCollectionDate}</p>{item.requestType==='existing'?<small>{item.customerId} / {item.branchId} · {item.paymentType} · OCC {item.occPrice}</small>:<small>{item.accountStatus?.replaceAll('_',' ')} · {item.address||item.locationLink||'缺地址或 Location'}</small>}<footer><button onClick={()=>schedule(item)}>加入指定日期路线</button></footer></article>)}</section></div>
  </div>
}
