import {useEffect,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest} from './apiClient.js'
import CenteredNotice from './CenteredNotice.jsx'
const copy={
 zh:{title:'其他客户',help:'按名称搜索或按固定路线筛选。仅列出当天没有任务的有效客户；加入后只收这一天，不修改固定排程。',search:'客户／分店／路线名称',route:'固定路线',all:'全部路线',none:'未分配路线',empty:'没有符合条件的客户',loading:'正在读取客户…',retry:'重新读取',selected:'已选其他客户',remove:'移除'},
 en:{title:'Other customers',help:'Search names or filter by fixed route. Only active customers without work on this date are listed. This adds a one-day collection without changing recurring schedules.',search:'Customer / branch / route name',route:'Fixed route',all:'All routes',none:'No assigned route',empty:'No matching customers',loading:'Loading customers…',retry:'Reload',selected:'Selected other customers',remove:'Remove'},
 ms:{title:'Pelanggan lain',help:'Cari nama atau tapis mengikut laluan tetap. Hanya pelanggan aktif tanpa tugasan pada tarikh ini dipaparkan. Kutipan ini untuk satu hari sahaja tanpa mengubah jadual tetap.',search:'Nama pelanggan / cawangan / laluan',route:'Laluan tetap',all:'Semua laluan',none:'Tiada laluan',empty:'Tiada pelanggan sepadan',loading:'Memuatkan pelanggan…',retry:'Muat semula',selected:'Pelanggan lain dipilih',remove:'Buang'}
}
export default function SupportOtherCustomers({date,selected,onChange,disabled}){
 const{language}=useI18n(),m=copy[language]||copy.en
 const[data,setData]=useState({items:[],routes:[]}),[search,setSearch]=useState(''),[route,setRoute]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0)
 useEffect(()=>{let alive=true;setLoading(true);setError('');apiRequest(`/api/dispatch/day/${date}/support-customers`).then(r=>{if(alive)setData(r)}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[date,revision])
 const names=b=>(b.routeNumbers||[]).map(n=>data.routes.find(r=>r.routeNumber===n)?.name||String(n)).join(' / ')
 const filtered=data.items.filter(b=>(!route||(route==='none'?!b.routeNumbers.length:b.routeNumbers.includes(Number(route))))&&`${b.customerName} ${b.branchName} ${b.branchCode} ${names(b)}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()))
 return <fieldset className="support-other" disabled={disabled}><legend>{m.title}</legend><p>{m.help}</p>{error&&<CenteredNotice>{error}</CenteredNotice>}<label>{m.search}<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>{m.route}<select value={route} onChange={e=>setRoute(e.target.value)}><option value="">{m.all}</option><option value="none">{m.none}</option>{data.routes.map(r=><option key={r.routeNumber} value={r.routeNumber} data-i18n-raw>{r.name}</option>)}</select></label><button type="button" disabled={loading} onClick={()=>setRevision(n=>n+1)}>{m.retry}</button>{loading?<p role="status">{m.loading}</p>:<div className="support-other-results">{filtered.map(b=><label className="support-option" key={b.id}><input type="checkbox" checked={selected.some(s=>s.id===b.id)} onChange={e=>onChange(e.target.checked?[...selected,b]:selected.filter(s=>s.id!==b.id))}/><span data-i18n-raw>{b.customerName} · {b.branchName||b.branchCode} · {names(b)}</span></label>)}{!filtered.length&&<p>{m.empty}</p>}</div>}<p>{m.selected}: {selected.length}</p>{selected.map(b=><div key={b.id}><span data-i18n-raw>{b.customerName} · {b.branchName||b.branchCode}</span> <button type="button" onClick={()=>onChange(selected.filter(s=>s.id!==b.id))}>{m.remove}</button></div>)}</fieldset>
}
