import SupportOtherCustomers from './SupportOtherCustomers.jsx'
import {useRef,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest} from './apiClient.js'
import CenteredNotice from './CenteredNotice.jsx'
import {formatDateDisplay} from './dateDisplay.js'
import './SupportVehicle.css'
const copy={
 zh:{title:'增加支援车辆',vehicle:'支援车辆',driver:'司机',crew:'跟车员',choose:'请选择',customers:'交给支援车的客户',remaining:'原车保留',selected:'支援车负责',save:'确认分配',close:'关闭',saving:'保存中…',help:'可从多个路线选择，只调整所选日期。请勾选未开始收货的客户，每条原路线至少保留一间客户。保存后请批准支援路线；原路线若尚未出车，也需重新批准。',saved:'已分配支援车辆，请检查路线并批准。',SUPPORT_PERMISSION:'没有派车管理权限。',SUPPORT_SELECTION:'请选择车辆、司机和客户，人员不能重复，每条原路线至少保留一间客户。',SUPPORT_STALE:'排程已变化。请关闭后重新打开，再选择客户。',SUPPORT_PROTECTED:'客户已有执行记录、单据或已停用，不能转给支援车。',SUPPORT_PENDING:'客户有待审批申请，请先处理。',SUPPORT_VEHICLE:'车辆当天已有任务、已出发或不可用，请选另一辆。',SUPPORT_STAFF:'人员当天已被安排、请假或角色不符，请重新选择。',SUPPORT_CAPACITY:'当天五个路线位置已用完，暂时不能再新增独立支援路线。'},
 en:{title:'Add support vehicle',vehicle:'Support vehicle',driver:'Driver',crew:'Attendants',choose:'Select',customers:'Customers for support vehicle',remaining:'Original vehicle keeps',selected:'Support vehicle takes',save:'Confirm assignment',close:'Close',saving:'Saving…',help:'Select across multiple routes for this date only. Select untouched customers and leave at least one customer on each original route. Approve the support route after saving; reapprove the original route if it has not departed.',saved:'Support assigned. Review and approve the routes.',SUPPORT_PERMISSION:'Dispatch management permission is required.',SUPPORT_SELECTION:'Select a vehicle, driver and customers. Staff must be distinct; leave at least one customer on each original route.',SUPPORT_STALE:'The plan changed. Close and reopen this panel to select again.',SUPPORT_PROTECTED:'A customer has work or documents, or is inactive, and cannot be transferred.',SUPPORT_PENDING:'Resolve pending customer requests first.',SUPPORT_VEHICLE:'This vehicle has work, has departed or is unavailable. Select another.',SUPPORT_STAFF:'Staff are assigned elsewhere, on leave or ineligible. Select again.',SUPPORT_CAPACITY:'All five daily route slots are occupied; another independent support route cannot be added yet.'},
 ms:{title:'Tambah kenderaan bantuan',vehicle:'Kenderaan bantuan',driver:'Pemandu',crew:'Kelindan',choose:'Pilih',customers:'Pelanggan untuk kenderaan bantuan',remaining:'Kenderaan asal kekal',selected:'Kenderaan bantuan ambil',save:'Sahkan tugasan',close:'Tutup',saving:'Menyimpan…',help:'Pilih daripada beberapa laluan untuk tarikh ini sahaja. Pilih pelanggan yang belum dimulakan dan tinggalkan sekurang-kurangnya seorang pelanggan pada setiap laluan asal. Luluskan laluan bantuan selepas simpan; luluskan semula laluan asal jika belum berlepas.',saved:'Kenderaan bantuan ditugaskan. Semak dan luluskan laluan.',SUPPORT_PERMISSION:'Kebenaran pengurusan penghantaran diperlukan.',SUPPORT_SELECTION:'Pilih kenderaan, pemandu dan pelanggan. Pekerja tidak boleh berulang; tinggalkan sekurang-kurangnya seorang pelanggan pada setiap laluan asal.',SUPPORT_STALE:'Jadual berubah. Tutup dan buka semula panel untuk memilih lagi.',SUPPORT_PROTECTED:'Pelanggan mempunyai rekod kerja, dokumen atau tidak aktif dan tidak boleh dipindahkan.',SUPPORT_PENDING:'Selesaikan permintaan pelanggan yang tertunda dahulu.',SUPPORT_VEHICLE:'Kenderaan ada tugasan, telah berlepas atau tidak tersedia. Pilih yang lain.',SUPPORT_STAFF:'Pekerja sudah ditugaskan, bercuti atau tidak layak. Pilih semula.',SUPPORT_CAPACITY:'Kelima-lima slot laluan harian sudah digunakan; laluan bantuan tambahan belum boleh diwujudkan.'}
}
export default function SupportVehicle({day,vehicles,employees,disabled=false}){
 const{language}=useI18n(),m=copy[language]||copy.en
 const[open,setOpen]=useState(false),[vehicle,setVehicle]=useState(''),[driver,setDriver]=useState(''),[crew,setCrew]=useState([]),[stops,setStops]=useState([]),[snapshot,setSnapshot]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),lock=useRef(false)
 const [otherCustomers,setOtherCustomers]=useState([])
 const available=vehicles.filter(v=>['available','active'].includes(v.status)&&(!v.isTemporary||v.temporaryDate===day.dispatch_date)&&!(day.routeBoards||[]).some(r=>r.vehicleId===v.id&&r.customerCount>0))
 const staff=employees.filter(e=>e.isActive&&e.employmentStatus==='active'),drivers=staff.filter(e=>['driver','supervisor'].includes(String(e.role).toLowerCase())||e.additionalRoles?.includes('Driver')),attendants=staff.filter(e=>['assistant','crew','attendant / crew'].includes(String(e.role).toLowerCase())||e.additionalRoles?.includes('Attendant / Crew'))
 const save=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await apiRequest(`/api/dispatch/day/${day.dispatch_date}/support`,{method:'POST',body:JSON.stringify({vehicleId:Number(vehicle),driverId:Number(driver),assistantIds:crew,stopIds:stops,branchIds:otherCustomers.map(b=>b.id),expectedRevision:snapshot.revision})});setOpen(false);setMessage(m.saved);window.dispatchEvent(new Event('kcs-handover-saved'))}catch(e){setError(e.code==='SUPPORT_CUSTOMER_STALE'?({zh:'部分客户已被安排或已停用，请重新读取客户后选择。',en:'Some customers are now scheduled or inactive. Reload the customer list and select again.',ms:'Sesetengah pelanggan sudah dijadualkan atau tidak aktif. Muat semula senarai dan pilih lagi.'}[language]||m.SUPPORT_STALE):m[e.code]||e.message)}finally{lock.current=false;setBusy(false)}}
 const toggle=()=>{if(open){setOpen(false);return}setSnapshot({revision:day.revision,routes:(day.routeBoards||[]).filter(r=>r.customerCount>0)});setVehicle('');setDriver('');setCrew([]);setStops([]);setOtherCustomers([]);setError('');setMessage('');setOpen(true)}
 return <div className="support-vehicle"><button type="button" disabled={disabled||busy} aria-expanded={open} onClick={toggle}>{m.title}</button>{message&&<p role="status">{message}</p>}{error&&<CenteredNotice>{error}</CenteredNotice>}{open&&<div className="support-editor"><p>{formatDateDisplay(day.dispatch_date)} · {m.help}</p><fieldset disabled={busy}><label>{m.vehicle}<select value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">{m.choose}</option>{available.map(v=><option key={v.id} value={v.id} data-i18n-raw>{v.registrationNumber||v.vehicleCode}</option>)}</select></label><label>{m.driver}<select value={driver} onChange={e=>{setDriver(e.target.value);setCrew(c=>c.filter(id=>id!==Number(e.target.value)))}}><option value="">{m.choose}</option>{drivers.map(e=><option key={e.id} value={e.id} data-i18n-raw>{e.name}</option>)}</select></label><fieldset><legend>{m.crew}</legend>{attendants.map(e=><label className="support-option" key={e.id}><input type="checkbox" disabled={Number(driver)===e.id||crew.length>=2&&!crew.includes(e.id)} checked={crew.includes(e.id)} onChange={ev=>setCrew(c=>ev.target.checked?[...c,e.id]:c.filter(id=>id!==e.id))}/><span data-i18n-raw>{e.name}</span></label>)}</fieldset><fieldset><legend>{m.customers}</legend>{snapshot.routes.map(group=><fieldset key={group.routeNumber} className="support-route-group"><legend data-i18n-raw>{group.name||`Route ${group.routeNumber}`} · {group.registrationNumber||'—'}</legend>{group.stops.map(s=><label className="support-option" key={s.id}><input type="checkbox" disabled={!['locked','available'].includes(s.status)||s.hasBill||s.arrivedAt||s.completedAt} checked={stops.includes(s.id)} onChange={e=>setStops(v=>e.target.checked?[...v,s.id]:v.filter(id=>id!==s.id))}/><span data-i18n-raw>{s.customerName} · {s.branchName||s.branchId}</span></label>)}<p>{m.remaining}: {group.stops.length-group.stops.filter(s=>stops.includes(s.id)).length} · {m.selected}: {group.stops.filter(s=>stops.includes(s.id)).length}</p></fieldset>)}</fieldset><SupportOtherCustomers date={day.dispatch_date} selected={otherCustomers} onChange={setOtherCustomers} disabled={busy}/><p>{m.selected}: {stops.length+otherCustomers.length}</p><button data-support-save type="button" disabled={!vehicle||!driver||(!stops.length&&!otherCustomers.length)||snapshot.routes.some(r=>r.stops.length>0&&r.stops.every(s=>stops.includes(s.id)))} onClick={save}>{busy?m.saving:m.save}</button><button type="button" onClick={()=>setOpen(false)}>{m.close}</button></fieldset></div>}</div>
}
