import {useCallback,useEffect,useState} from 'react'
import {apiRequest as api} from './apiClient.js'
import {useI18n} from './i18n.jsx'
import {collectHighAccuracyPosition} from './highAccuracyGps.js'
import GoogleMapPreview from './GoogleMapPreview.jsx'
import './TemporaryCustomerIntakes.css'

const post=(url,data)=>api(url,{method:'POST',body:JSON.stringify(data)})
export function TemporaryCustomerMobile({account,BillingPanel}){
 const{t}=useI18n(),key=`kcs-intake-draft-${account.employeeId||account.id}`
 const[data,setData]=useState({items:[],trips:[]}),[draft,setDraft]=useState(()=>{try{return JSON.parse(sessionStorage.getItem(key))||{name:'',phone:'',requestKey:crypto.randomUUID()}}catch{return{name:'',phone:'',requestKey:crypto.randomUUID()}}}),[tripId,setTripId]=useState(''),[gps,setGps]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState(null)
 const load=useCallback(async()=>{const next=await api('/api/mobile/customer-intakes');setData(next);setTripId(id=>next.trips.some(r=>String(r.id)===String(id))?id:next.trips.length===1?String(next.trips[0].id):'')},[])
 useEffect(()=>{load().catch(e=>setError(e.message))},[load])
 useEffect(()=>{sessionStorage.setItem(key,JSON.stringify(draft))},[key,draft])
 const run=async action=>{setBusy(true);setError('');try{await action();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const capture=()=>run(async()=>{try{const reading=await collectHighAccuracyPosition(navigator.geolocation);setGps(reading);setDraft(d=>({...d,latitude:reading.latitude,longitude:reading.longitude}))}catch{throw Error(t('intake.gpsFailed'))}})
 const arrive=async(stopId,reading)=>{const p=reading||await collectHighAccuracyPosition(navigator.geolocation);await post(`/api/mobile/stops/${stopId}/arrive`,{latitude:p.latitude,longitude:p.longitude,accuracy:p.accuracyM,captured_at:p.deviceCapturedAt})}
 const create=e=>{e.preventDefault();return run(async()=>{
  const result=await post('/api/mobile/customer-intakes',{...draft,tripId:Number(tripId)})
  setSelected(result.id);setDraft({name:'',phone:'',requestKey:crypto.randomUUID()});setGps(null)
  try{await arrive(result.stopId,gps)}finally{await load()}
 })}
 const active=data.items.find(i=>i.id===selected)
 return <section className="temporary-intakes"><h1>{t('intake.title')}</h1><p>{t('intake.help')}</p>{error&&<p role="alert" className="auth-error">{error}</p>}
 {!active?<><form onSubmit={create}><fieldset disabled={busy}><label>{t('intake.name')}<input required maxLength={200} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>{t('intake.phone')}<input type="tel" maxLength={60} value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>{t('intake.trip')}<select required value={tripId} onChange={e=>setTripId(e.target.value)}><option value="">{t('intake.choose')}</option>{data.trips.map(r=><option key={r.id} value={r.id} data-i18n-raw>{r.plate||r.vehicleCode} · Trip {r.tripNumber}</option>)}</select></label>{!data.trips.length&&<p>{t('intake.noTrip')}</p>}<button type="button" onClick={capture}>{t('intake.capture')}</button>{draft.latitude!=null&&<><GoogleMapPreview latitude={draft.latitude} longitude={draft.longitude} onPositionAdjusted={p=>setDraft(d=>({...d,latitude:p.latitude,longitude:p.longitude}))}/><p>{t('intake.checkMap')} {gps?`±${gps.accuracyM}m`:''}</p>{gps?.accuracyM>20&&<p role="status">{t('intake.poorGps')}</p>}</>}<p>{t('intake.cash')}</p><button type="submit" disabled={!tripId||draft.latitude==null||!draft.name.trim()}>{busy?t('intake.saving'):t('intake.start')}</button></fieldset></form><h2>{t('intake.records')}</h2>{data.items.map(i=><button key={i.id} type="button" className="intake-record" onClick={()=>setSelected(i.id)}><b data-i18n-raw>{i.name}</b><span>{i.serviceDate} · {t(`intake.${i.status}`)} · {i.billNumber||t('intake.draft')}</span></button>)}</>:<article><button type="button" onClick={()=>setSelected(null)}>{t('intake.back')}</button><h2 data-i18n-raw>{active.name}</h2><p>{active.serviceDate} · {active.plate} · {t(`intake.${active.status}`)}</p><GoogleMapPreview latitude={active.latitude} longitude={active.longitude}/>{active.billId&&<p>{t('intake.notified')}</p>}{active.status!=='cancelled'&&<>{!active.arrivedAt&&active.stopStatus!=='completed'?<button disabled={busy} onClick={()=>run(()=>arrive(active.stopId))}>{t('intake.arrive')}</button>:<BillingPanel key={active.stopId} stop={{id:active.stopId,billCreated:Boolean(active.billId),paymentProofUploaded:Boolean(active.paymentProofUploaded)}} onChanged={load} readOnly={active.stopStatus==='completed'}/>} {active.billId&&active.stopStatus!=='completed'&&<button disabled={busy||!active.paymentProofUploaded} onClick={()=>run(()=>post(`/api/mobile/stops/${active.stopId}/complete`,{}))}>{t('intake.complete')}</button>}{active.status==='draft'&&!active.billId&&<button disabled={busy} onClick={()=>{if(window.confirm(t('intake.cancelConfirm')))run(()=>post(`/api/mobile/customer-intakes/${active.id}/cancel`,{}))}}>{t('intake.cancelDraft')}</button>}</>}</article>}
 </section>
}

function IntakeReviewRow({item,onChanged}){
 const{t}=useI18n(),[decision,setDecision]=useState('one_time'),[reason,setReason]=useState(''),[search,setSearch]=useState(''),[matches,setMatches]=useState([]),[target,setTarget]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const find=async()=>{setBusy(true);setError('');setTarget('');try{setMatches((await api(`/api/customer-intakes/matches?search=${encodeURIComponent(search)}`)).items)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{await post(`/api/customer-intakes/${item.id}/review`,{decision,reason,branchId:target?Number(target):null});await onChanged()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <article><h3 data-i18n-raw>{item.name}</h3><p>{item.phone||'—'} · {item.driverName} · {item.plate} · {item.serviceDate}</p><a href={`https://www.google.com/maps?q=${item.latitude},${item.longitude}`} target="_blank" rel="noreferrer">{t('intake.map')}</a><p>{item.billNumber||t('intake.voided')} · RM {(Number(item.totalCents||0)/100).toFixed(2)} · {item.paymentProofUploaded?t('intake.proofYes'):t('intake.proofNo')}</p>{item.items.map((p,index)=><p key={index}><span data-i18n-raw>{p.name}</span> · {p.quantity} × RM {(p.unitPriceCents/100).toFixed(2)}</p>)}
 {item.status==='pending'?<form onSubmit={save}><fieldset disabled={busy}><label>{t('intake.decision')}<select value={decision} onChange={e=>setDecision(e.target.value)}>{['one_time','formal','linked'].map(s=><option key={s} value={s}>{t(`intake.${s}`)}</option>)}</select></label>{decision==='formal'&&<p>{t('intake.formalHelp')}</p>}{decision==='linked'&&<><label>{t('intake.search')}<input value={search} onChange={e=>{setSearch(e.target.value);setTarget('');setMatches([])}}/></label><button type="button" onClick={find} disabled={search.trim().length<2}>{t('intake.find')}</button><label>{t('intake.target')}<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">{t('intake.choose')}</option>{matches.map(m=><option key={m.id} value={m.id} data-i18n-raw>{m.code} · {m.customerName} · {m.name} · {m.phone||m.address||''}</option>)}</select></label></>}<label>{t('intake.reason')}<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={!item.billId||!reason.trim()||(decision==='linked'&&!target)}>{t('intake.save')}</button></fieldset>{error&&<p role="alert">{error}</p>}</form>:<p>{t(`intake.${item.status}`)} · {item.linkedCode} {item.linkedName} · {item.reviewed_by} · {item.review_reason}</p>}</article>
}
export function TemporaryCustomerReviews(){
 const{t}=useI18n(),[items,setItems]=useState([]),[history,setHistory]=useState(false),[error,setError]=useState('')
 const load=useCallback(async()=>{const r=await api(`/api/customer-intakes?history=${history}`);setItems(r.items);setError('')},[history])
 useEffect(()=>{let alive=true;const refresh=()=>load().catch(e=>{if(alive)setError(e.message)});void refresh();const timer=setInterval(refresh,10000);return()=>{alive=false;clearInterval(timer)}},[load])
 return <section className="temporary-intakes intake-review"><header><h2>{t('intake.reviewTitle')} ({items.length})</h2><button onClick={()=>setHistory(!history)}>{t(history?'intake.pending':'intake.history')}</button></header>{error&&<p role="alert">{error}</p>}{!items.length&&<p>{t('intake.empty')}</p>}{items.map(i=><IntakeReviewRow key={i.id} item={i} onChanged={load}/>)}</section>
}
