import {useEffect,useRef,useState} from 'react'
import {useI18n} from './i18n.jsx'
import {apiRequest} from './apiClient.js'
import {kuchingDate} from '../shared/kuchingTime.js'
import './TripExceptions.css'
const words={
 zh:{title:'行程异常处理',date:'行程日期',refresh:'刷新',close:'关闭',hint:'按日期检查所有进行中的行程，包括手机隐藏的站点。取消仅适用于已关闭且未执行的站点，不计为收货完成。',empty:'该日没有进行中的行程。',trip:'行程',stop:'站点',state:'状态',cancel:'取消关闭客户站点',complete:'确认结束行程',reason:'处理原因（必填）',submit:'确认处理',back:'返回',ready:'全部站点已处理，可由司机结束；必要时管理人员填写原因结束。',saved:'处理已保存。',changed:'记录已变化或仍有保护条件，请刷新后检查。',history:'处理记录（最近200笔）',closed_unused:'客户已关闭，尚未执行：填写原因取消本站。',closed_protected:'客户已关闭，但有执行、凭证或处理记录：保留记录，先核对客户状态及原记录；无法处理时联系系统负责人。',approval:'有待审批申请：先到总览或派车审批区处理。',inactive:'客户非启用状态：先核对客户资料与原站点，不可直接取消。',proof:'现金付款证明未上传：由司机补传凭证。',arrival:'尚未到店：由司机处理；无货或改期须按流程申请。',bill:'已到店但未有有效单据：由司机检查开单或无货流程。',finish_stop:'已有单据：由司机确认完成本站。'},
 en:{title:'Trip exceptions',date:'Trip date',refresh:'Refresh',close:'Close',hint:'Review every running trip for this date, including stops hidden on mobile. Only untouched stops for closed branches can be cancelled; they are not counted as collected.',empty:'No running trips for this date.',trip:'Trip',stop:'Stop',state:'Status',cancel:'Cancel closed branch stop',complete:'Confirm trip completion',reason:'Reason (required)',submit:'Confirm action',back:'Back',ready:'All stops are handled. The driver can finish; management may finish with a reason when necessary.',saved:'Action saved.',changed:'The record changed or is protected. Refresh and review.',history:'Action history (latest 200)',closed_unused:'Closed branch, untouched stop: enter a reason to cancel.',closed_protected:'Closed branch with execution, evidence or processing history: preserve records and review branch status and original records. Contact the system owner if unresolved.',approval:'An approval is pending: review it in Overview or dispatch approvals.',inactive:'Branch is not active: review branch details and the original stop; direct cancellation is unavailable.',proof:'Cash proof is missing: ask the driver to upload it.',arrival:'Not arrived: the driver must handle the stop or request No Goods / rescheduling.',bill:'Arrived without an issued bill: ask the driver to check billing or No Goods.',finish_stop:'Bill recorded: ask the driver to complete this stop.'},
 ms:{title:'Penyelesaian masalah perjalanan',date:'Tarikh perjalanan',refresh:'Muat semula',close:'Tutup',hint:'Semak semua perjalanan yang sedang berjalan, termasuk hentian tersembunyi pada telefon. Hanya hentian belum dilaksanakan bagi cawangan ditutup boleh dibatalkan; tidak dikira sebagai kutipan.',empty:'Tiada perjalanan sedang berjalan pada tarikh ini.',trip:'Perjalanan',stop:'Hentian',state:'Status',cancel:'Batalkan hentian cawangan ditutup',complete:'Sahkan tamat perjalanan',reason:'Sebab (wajib)',submit:'Sahkan tindakan',back:'Kembali',ready:'Semua hentian telah diuruskan. Pemandu boleh tamatkan perjalanan; pihak pengurusan boleh menamatkannya dengan sebab jika perlu.',saved:'Tindakan disimpan.',changed:'Rekod telah berubah atau dilindungi. Muat semula dan semak.',history:'Sejarah tindakan (200 terkini)',closed_unused:'Cawangan ditutup, hentian belum dilaksanakan: isi sebab untuk membatalkan.',closed_protected:'Cawangan ditutup dengan rekod pelaksanaan, bukti atau pemprosesan: kekalkan rekod dan semak status cawangan serta rekod asal. Hubungi pengurus sistem jika belum selesai.',approval:'Permohonan menunggu kelulusan: semak di Gambaran Keseluruhan atau kelulusan penghantaran.',inactive:'Cawangan tidak aktif: semak maklumat cawangan dan hentian asal; pembatalan terus tidak dibenarkan.',proof:'Bukti bayaran tunai belum dimuat naik: minta pemandu memuat naik.',arrival:'Belum tiba: pemandu perlu uruskan hentian atau mohon Tiada Barang / perubahan tarikh.',bill:'Sudah tiba tanpa bil sah: minta pemandu semak bil atau Tiada Barang.',finish_stop:'Bil telah direkodkan: minta pemandu selesaikan hentian.'}}
export default function TripExceptions({onSaved}){
 const{language}=useI18n(),w=words[language]||words.en,[open,setOpen]=useState(false),[date,setDate]=useState(kuchingDate),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[action,setAction]=useState(null),[reason,setReason]=useState(''),sequence=useRef(0),entry=useRef(null),dialog=useRef(null)
 const load=async()=>{const seq=++sequence.current;setBusy(true);setError('');try{const result=await apiRequest('/api/dispatch/trip-exceptions?date='+date);if(seq===sequence.current)setData(result)}catch(e){if(seq===sequence.current)setError(e.message)}finally{if(seq===sequence.current)setBusy(false)}}
 useEffect(()=>{if(open){setData(null);setAction(null);setReason('');load();dialog.current?.focus()}},[open,date])
 const close=()=>{if(busy||action)return;setOpen(false);entry.current?.focus()}
 const choose=(kind,item)=>{setAction({kind,id:item.id,label:kind==='cancel'?item.branch_name:w.trip+' #'+item.id});setReason('');setMessage('')}
 const submit=async e=>{e.preventDefault();if(busy||!reason.trim())return;setBusy(true);setError('');try{await apiRequest(`/api/dispatch/trip-exceptions/${action.kind==='cancel'?'stops':'trips'}/${action.id}/${action.kind}`,{method:'POST',body:JSON.stringify({reason})});setAction(null);setReason('');setMessage(w.saved);onSaved?.();await load()}catch(e){setError(['CONFLICT','INVALID_STATUS'].includes(e.code)?w.changed:e.message)}finally{setBusy(false)}}
 const keyDown=e=>{if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab'){const els=[...dialog.current.querySelectorAll('button:not(:disabled),input:not(:disabled),textarea:not(:disabled)')];const first=els[0],last=els.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}
 return <><button ref={entry} type="button" title={w.title} aria-label={w.title} onClick={()=>setOpen(true)}>⚠ {w.title}</button>{open&&<div className="trip-exception-backdrop" onClick={e=>{if(e.target===e.currentTarget)close()}}><section className="trip-exception-dialog" ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-label={w.title} onKeyDown={keyDown}><header><h2>{w.title}</h2><button type="button" aria-label={w.close} title={w.close} disabled={busy||!!action} onClick={close}>×</button></header><div className="trip-exception-body"><p>{w.hint}</p><label>{w.date}<input type="date" max={kuchingDate()} value={date} disabled={busy||!!action} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/></label><button type="button" disabled={busy||!!action} onClick={load}>{w.refresh}</button>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{action?<form onSubmit={submit}><h3>{w[action.kind==='cancel'?'cancel':'complete']}</h3><p data-i18n-raw>{action.label}</p><label>{w.reason}<textarea required maxLength={500} disabled={busy} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()}>{w.submit}</button><button type="button" title={w.back} aria-label={w.back} disabled={busy} onClick={()=>setAction(null)}>←</button></form>:<>{data&&!data.items.length&&<p>{w.empty}</p>}{data?.items.map(t=><article key={t.id}><h3 data-i18n-raw>{t.registration_number||'—'} · {t.driver_name||'—'}</h3><p>{w.trip} {t.trip_number} · #{t.id} · {t.dispatch_date}</p>{t.canComplete&&<><p>{w.ready}</p><button type="button" disabled={busy} onClick={()=>choose('complete',t)}>{w.complete}</button></>}{t.stops.map(s=><div className="trip-exception-stop" key={s.id}><b data-i18n-raw>{s.stop_sequence}. {s.branch_name||'—'}</b><small>{w.stop} #{s.id}</small><p>{w[s.issue]}</p>{s.canCancel&&<button type="button" disabled={busy||date>kuchingDate()} onClick={()=>choose('cancel',s)}>{w.cancel}</button>}</div>)}</article>)}<details><summary>{w.history}</summary>{data?.history.map((h,i)=><p key={i} data-i18n-raw>{h.created_at} UTC · {h.details.actorName||h.actor} · {w.trip} #{h.details.tripId} · {w[h.change_type==='trip_exception_cancel'?'cancel':'complete']} #{h.entity_id} · {h.details.reason}</p>)}</details></>}</div></section></div>}</>
}
