import {useCallback,useEffect,useState} from 'react'
import {apiRequest as api} from './apiClient.js'
import {formatBranchId,formatCustomerId} from '../shared/typedIds.js'
import {useI18n} from './i18n.jsx'
import './MasterDataPage.css'

export default function UnlinkedBranchesPage(){
  const{t}=useI18n(),[data,setData]=useState({items:[],summary:{}}),[customers,setCustomers]=useState([]),[search,setSearch]=useState(''),[linking,setLinking]=useState(null),[form,setForm]=useState({customerId:'',reason:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const load=useCallback(async()=>{try{const[result,parents]=await Promise.all([api(`/api/unlinked-branches?search=${encodeURIComponent(search)}`),api('/api/customers?pageSize=500')]);setData(result);setCustomers(parents.items||[])}catch(item){setError(item.message)}},[search])
  useEffect(()=>{const timer=setTimeout(()=>void load(),200);return()=>clearTimeout(timer)},[load])
  const link=async event=>{event.preventDefault();if(!window.confirm(`${formatBranchId(linking.branchId)} → ${formatCustomerId(form.customerId)}?`))return;setBusy(true);setError('');try{await api(`/api/unlinked-branches/${encodeURIComponent(linking.branchId)}/link`,{method:'POST',body:JSON.stringify(form)});setLinking(null);setForm({customerId:'',reason:''});await load()}catch(item){setError(item.message)}finally{setBusy(false)}}
  return <section className="master-workspace unlinked-review"><header><div><h2>{t('unlinked.title')}</h2><p>{t('unlinked.help')}</p></div><div className="unlinked-summary"><span>{t('unlinked.total')}: <b>{data.summary.totalBranches||0}</b></span><span>{t('unlinked.linked')}: <b>{data.summary.linkedBranches||0}</b></span><span>{t('unlinked.unlinked')}: <b>{data.summary.unlinkedBranches||0}</b></span></div></header><div className="master-filters"><input aria-label={t('common.search')} value={search} onChange={event=>setSearch(event.target.value)} placeholder={t('unlinked.search')}/></div>{error&&<div className="data-error">{error}</div>}<div className="customer-master-table"><table><thead><tr><th>{t('list.branchId')}</th><th>{t('list.branchName')}</th><th>{t('list.area')}</th><th>{t('list.address')}</th><th>{t('list.lifecycleStatus')}</th><th>{t('list.gpsStatus')}</th><th>{t('list.actions')}</th></tr></thead><tbody>{data.items.map(item=><tr key={item.branchId}><td>{formatBranchId(item.branchId)}</td><td data-i18n-raw>{item.branchName||'—'}</td><td data-i18n-raw>{item.area||'—'}</td><td data-i18n-raw>{item.address||'—'}</td><td>{t(`branchLifecycle.status.${item.lifecycleStatus||'ACTIVE'}`)}</td><td>{t(`list.gps.${item.officialLatitude!=null&&item.officialLongitude!=null?'set':'notSet'}`)}</td><td><button onClick={()=>{setLinking(item);setForm({customerId:'',reason:''})}}>{t('unlinked.linkAction')}</button></td></tr>)}</tbody></table></div>{!data.items.length&&<div className="master-empty-state">{t('unlinked.empty')}</div>}{linking&&<div className="master-modal"><form onSubmit={link}><header><div><h2>{t('unlinked.linkAction')}</h2><small>{formatBranchId(linking.branchId)} — <span data-i18n-raw>{linking.branchName}</span></small></div><button type="button" onClick={()=>setLinking(null)}>×</button></header><div className="editor-fields"><label>{t('unlinked.parent')}<select required value={form.customerId} onChange={event=>setForm({...form,customerId:event.target.value})}><option value="">—</option>{customers.map(customer=><option key={customer.customerId} value={customer.customerId}>{formatCustomerId(customer.customerId)} — {customer.customerName}</option>)}</select></label><label>{t('unlinked.reason')}<textarea required value={form.reason} onChange={event=>setForm({...form,reason:event.target.value})}/></label></div><p className="permission-note">{t('unlinked.safety')}</p><footer><button type="button" onClick={()=>setLinking(null)}>{t('common.cancel')}</button><button className="primary" disabled={busy}>{busy?t('common.saving'):t('common.confirm')}</button></footer></form></div>}</section>
}
