import { useCallback, useEffect, useState } from 'react'
import './VehicleDetailPage.css'
import {apiRequest as api} from './apiClient.js'

const filePayload=file=>new Promise((resolve,reject)=>{if(!file)return resolve(null);const reader=new FileReader();reader.onload=()=>resolve({name:file.name,dataUrl:reader.result});reader.onerror=reject;reader.readAsDataURL(file)})
const money=value=>value==null?'—':`RM ${Number(value).toFixed(2)}`
const value=value=>value==null||value===''?'—':value

export default function VehicleDetailPage({vehicleId,resources,onBack,currentUser}){
  const[detail,setDetail]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  const load=useCallback(()=>api(`/api/vehicles/${vehicleId}`).then(setDetail).catch(item=>setError(item.message)),[vehicleId]);useEffect(()=>{load()},[load])
  const save=async(url,body)=>{setBusy(true);setError('');try{await api(url,{method:url===`/api/vehicles/${vehicleId}`?'PATCH':'POST',body:JSON.stringify({...body,changedBy:currentUser.name,updatedBy:currentUser.name,uploadedBy:currentUser.name})});setMessage('Saved successfully.');await load()}catch(item){setError(item.message)}finally{setBusy(false)}}
  if(!detail)return <div className="page"><button onClick={onBack}>Back</button>{error||'Loading vehicle data…'}</div>
  const sold=detail.status==='sold',isOwnerAdmin=currentUser.role==='owner_admin',canManage=['owner_admin','operations_admin'].includes(currentUser.role)||currentUser.permissions?.includes('vehicle_manage'),canViewDocuments=['owner_admin','operations_admin','supervisor','office'].includes(currentUser.role)
  return <div className="page vehicle-detail-page"><button className="vehicle-back" onClick={onBack}>Back</button><header className="vehicle-detail-title"><div><em>VEHICLE MANAGEMENT</em><h1>{detail.vehicleCode} — {detail.registrationNumber}</h1><p>{sold?'Sold vehicle: history only, excluded from dispatch, maintenance or compliance reminders.':'Drivers are linked through daily dispatch records, does not permanently bind a vehicle.'}</p></div><span className={`vehicle-state ${detail.status}`}>{detail.status}</span></header>{message&&<div className="planner-message">✓ {message}</div>}{error&&<div className="data-error">{error}</div>}
    <nav className="vehicle-tabs" aria-label="Vehicle detail sections"><a href="#vehicle-overview">Overview</a><a href="#vehicle-registration">Registration Details</a><a href="#vehicle-operations">Operational Details</a>{canViewDocuments&&<a href="#vehicle-documents">Documents</a>}<a href="#vehicle-history">History / Audit</a></nav>
    <section id="vehicle-overview" className="vehicle-record-section"><header><h2>Overview</h2></header><p>{detail.vehicleName||detail.brand||'—'} · KCS operational capacity {value(detail.capacityKg)} kg · {detail.status}</p></section>
    <div id="vehicle-registration"><BasicForm detail={detail} readOnly={!isOwnerAdmin} disabled={busy||sold} save={body=>save(`/api/vehicles/${vehicleId}`,body)}/></div>
    <div id="vehicle-operations"><OperationalVehicleForm detail={detail} disabled={busy||sold||!canManage} save={body=>save(`/api/vehicles/${vehicleId}`,body)}/>
    {!sold&&<Compliance detail={detail.compliance||{}} disabled={busy} save={body=>save(`/api/vehicles/${vehicleId}/compliance`,body)}/>} 
    <Maintenance records={detail.maintenanceRecords} disabled={busy||sold} save={body=>save(`/api/vehicles/${vehicleId}/maintenance`,body)}/>
    <Fuel records={detail.fuelRecords} employees={resources?.employees||[]} disabled={busy||sold} save={body=>save(`/api/vehicles/${vehicleId}/fuel`,body)}/>
    <Tyres records={detail.tyreRecords} disabled={busy||sold} save={body=>save(`/api/vehicles/${vehicleId}/tyres`,body)}/>
    <Usage records={detail.usageHistory} employees={resources?.employees||[]} disabled={busy||sold} save={body=>save(`/api/vehicles/${vehicleId}/usage`,body)}/>
    </div>
    {canViewDocuments&&<div id="vehicle-documents"><Documents records={detail.documents||[]} disabled={busy||sold||!canManage} save={body=>save(`/api/vehicles/${vehicleId}/documents`,body)} reload={load}/></div>}
    <section id="vehicle-history" className="vehicle-record-section"><header><h2>Vehicle Status History</h2><p>Vehicle Status History</p></header><RecordTable headers={['Changed At','Previous','New','Reason','Changed By']} rows={detail.statusHistory.map(row=>[row.changedAt,row.previousStatus,row.newStatus,row.reason,row.changedBy])}/></section>
  </div>
}

const registrationDisplayFields=[['vehicleCode','Vehicle Number'],['registrationNumber','Registration Plate'],['vehicleName','Vehicle Name'],['registeredOwner','Registered Owner'],['brand','Make / Brand'],['model','Model'],['chassisNumber','Chassis Number'],['engineNumber','Engine Number'],['fuelType','Fuel'],['engineCapacityCc','Engine Capacity cc'],['vehicleOrigin','Vehicle Origin'],['vehicleClass','Vehicle Class'],['vehicleType','Body Type'],['manufactureYear','Manufacture Year'],['registrationDate','Registration Date'],['grossVehicleWeightKg','JPJ GVW kg'],['unladenWeightKg','JPJ Tare kg']]
function BasicForm({detail,readOnly,disabled,save}){
  const[state,setState]=useState({vehicleCode:detail.vehicleCode,registrationNumber:detail.registrationNumber||'',vehicleName:detail.vehicleName||'',registeredOwner:detail.registeredOwner||'',brand:detail.brand||'',model:detail.model||'',manufactureYear:detail.manufactureYear||'',registrationDate:detail.registrationDate||'',vehicleType:detail.vehicleType||'',chassisNumber:detail.chassisNumber||'',engineNumber:detail.engineNumber||'',fuelType:detail.fuelType||'',engineCapacityCc:detail.engineCapacityCc||'',vehicleOrigin:detail.vehicleOrigin||'',vehicleClass:detail.vehicleClass||'',grossVehicleWeightKg:detail.grossVehicleWeightKg||'',unladenWeightKg:detail.unladenWeightKg||'',capacityKg:detail.capacityKg||'',status:detail.status,defaultBaseLocationId:detail.defaultBaseLocationId||'',preferredZoneIds:detail.preferredZones.map(item=>item.id),remark:detail.remark||'',reason:''})
  const field=(key,label,type='text')=><label>{label}<input type={type} value={state[key]} disabled={disabled} onChange={event=>setState({...state,[key]:event.target.value})}/></label>
  if(readOnly)return <section className="vehicle-record-section vehicle-registration-readonly"><header><h2>Registration Details</h2><p><strong>Read Only</strong> — only the Owner Administrator may change vehicle registration details.</p></header><dl>{registrationDisplayFields.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{value(detail[key])}</dd></div>)}</dl></section>
  return <section className="vehicle-record-section"><header><h2>Registration Details</h2><p>JPJ GVW/Tare remain separate from KCS operational capacity.</p></header><form className="vehicle-basic-grid" onSubmit={event=>{event.preventDefault();save({...state,manufactureYear:state.manufactureYear?Number(state.manufactureYear):null,engineCapacityCc:state.engineCapacityCc?Number(state.engineCapacityCc):null,grossVehicleWeightKg:state.grossVehicleWeightKg?Number(state.grossVehicleWeightKg):null,unladenWeightKg:state.unladenWeightKg?Number(state.unladenWeightKg):null})}}>{field('vehicleCode','Vehicle Number')}{field('registrationNumber','Registration Plate')}{field('vehicleName','Vehicle Name')}{field('registeredOwner','Registered Owner')}{field('brand','Make / Brand')}{field('model','Model')}{field('chassisNumber','Chassis Number')}{field('engineNumber','Engine Number')}{field('fuelType','Fuel')}{field('engineCapacityCc','Engine Capacity cc','number')}{field('vehicleOrigin','Vehicle Origin')}{field('vehicleClass','Vehicle Class')}{field('vehicleType','Body Type')}{field('manufactureYear','Manufacture Year','number')}{field('registrationDate','Registration Date','date')}{field('grossVehicleWeightKg','JPJ GVW kg','number')}{field('unladenWeightKg','JPJ Tare kg','number')}{field('reason','Reason')}<button disabled={disabled}>Save Registration Changes</button></form></section>
}

function OperationalVehicleForm({detail,disabled,save}){const[state,setState]=useState({capacityKg:detail.capacityKg??'',remark:detail.remark||'',reason:''});return <RecordSection title="Operational Details" note="Operational capacity and remarks continue to use Vehicle management permission."><form className="record-form" onSubmit={event=>{event.preventDefault();save({capacityKg:state.capacityKg===''?null:Number(state.capacityKg),remark:state.remark,reason:state.reason||'Vehicle operational update'})}}><input type="number" placeholder="Operational Capacity kg" value={state.capacityKg} onChange={event=>setState({...state,capacityKg:event.target.value})}/><input placeholder="Operational Remark" value={state.remark} onChange={event=>setState({...state,remark:event.target.value})}/><input placeholder="Reason" value={state.reason} onChange={event=>setState({...state,reason:event.target.value})}/><button disabled={disabled}>Save Operational Details</button></form></RecordSection>}

function Compliance({detail,disabled,save}){const[state,setState]=useState(detail);const fields=[['puspakomDueDate','Puspakom'],['roadTaxDueDate','Road Tax'],['insuranceDueDate','Insurance'],['loanPaymentDueDate','Loan Payment'],['nextServiceDate','Next Service']];return <section className="vehicle-record-section"><header><h2>Compliance and due-date reminders</h2><p>30  days yellow, 14  days orange, 7  days red; overdue items show a severe warning.</p></header><div className="reminder-grid">{fields.map(([key,label])=><label className={`reminder-card ${detail[`${key}Alert`]?.level||''}`} key={key}><span>{label}</span><input type="date" value={state[key]||''} onChange={event=>setState({...state,[key]:event.target.value})}/><b>{detail[`${key}Alert`]?.message||'Not set'}</b></label>)}</div><form className="record-inline" onSubmit={event=>{event.preventDefault();save(state)}}><label>Next Service Mileage<input type="number" value={state.nextServiceMileage||''} onChange={event=>setState({...state,nextServiceMileage:event.target.value})}/></label><button disabled={disabled}>Save reminders</button></form></section>}

function Maintenance({records,disabled,save}){const[state,setState]=useState({date:'',mileage:'',faultDescription:'',repairWork:'',partsReplaced:'',workshop:'',labourCost:'',partsCost:'',downtimeStart:'',downtimeEnd:'',approvedBy:'',followUpDate:'',invoiceAttachment:null,beforePhoto:null,afterPhoto:null});const submit=async event=>{event.preventDefault();await save({...state,invoiceAttachment:await filePayload(state.invoiceAttachment),beforePhoto:await filePayload(state.beforePhoto),afterPhoto:await filePayload(state.afterPhoto)});setState({...state,date:'',faultDescription:'',repairWork:'',invoiceAttachment:null,beforePhoto:null,afterPhoto:null})};return <RecordSection title="Maintenance Records" note="Invoices and before/after repair photos are stored only in local data/uploads."><form className="record-form" onSubmit={submit}><input required type="date" value={state.date} onChange={e=>setState({...state,date:e.target.value})}/>{['mileage','faultDescription','repairWork','partsReplaced','workshop','labourCost','partsCost','downtimeStart','downtimeEnd','approvedBy','followUpDate'].map(key=><input key={key} type={key.includes('Cost')||key==='mileage'?'number':key.includes('Date')?'date':'text'} placeholder={key} value={state[key]} onChange={e=>setState({...state,[key]:e.target.value})}/>)}<File label="Invoice" onChange={file=>setState({...state,invoiceAttachment:file})}/><File label="Before Photo" image onChange={file=>setState({...state,beforePhoto:file})}/><File label="After Photo" image onChange={file=>setState({...state,afterPhoto:file})}/><button disabled={disabled}>Add maintenance record</button></form><RecordTable headers={['Date','Mileage','Fault','Repair','Workshop','Labour','Parts','Total','Invoice','Before / After','Downtime','Approved','Follow-up']} rows={records.map(row=>[row.maintenanceDate,value(row.mileage),value(row.faultDescription),value(row.repairWork),value(row.workshop),money(row.labourCost),money(row.partsCost),money(row.totalCost),value(row.invoiceOriginalName),`${value(row.beforePhotoOriginalName)} / ${value(row.afterPhotoOriginalName)}`,`${value(row.downtimeStart)} / ${value(row.downtimeEnd)}`,value(row.approvedBy),value(row.followUpDate)])}/></RecordSection>}

function Fuel({records,employees,disabled,save}){const[state,setState]=useState({dateTime:'',driverId:'',mileage:'',fuelStation:'',litres:'',pricePerLitre:'',totalAmount:'',fullTank:true,relatedDispatchDate:'',receiptPhoto:null});const submit=async event=>{event.preventDefault();await save({...state,receiptPhoto:await filePayload(state.receiptPhoto)});setState({...state,dateTime:'',receiptPhoto:null})};return <RecordSection title="Fuel Records"><form className="record-form" onSubmit={submit}><input required type="datetime-local" value={state.dateTime} onChange={e=>setState({...state,dateTime:e.target.value})}/><select value={state.driverId} onChange={e=>setState({...state,driverId:e.target.value})}><option value="">Driver</option>{employees.filter(item=>String(item.jobRole).toLowerCase()==='driver').map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>{['mileage','fuelStation','litres','pricePerLitre','totalAmount'].map(key=><input key={key} type={key==='fuelStation'?'text':'number'} placeholder={key} value={state[key]} onChange={e=>setState({...state,[key]:e.target.value})}/>)}<input type="date" value={state.relatedDispatchDate} onChange={e=>setState({...state,relatedDispatchDate:e.target.value})}/><label><input type="checkbox" checked={state.fullTank} onChange={e=>setState({...state,fullTank:e.target.checked})}/> Full Tank</label><File label="Receipt" image onChange={file=>setState({...state,receiptPhoto:file})}/><button disabled={disabled}>Add fuel record</button></form><RecordTable headers={['Date/Time','Driver ID','Mileage','Station','Litres','Price/L','Total','Receipt','Full Tank','Dispatch']} rows={records.map(row=>[row.fuelAt,value(row.driverId),value(row.mileage),value(row.fuelStation),value(row.litres),money(row.pricePerLitre),money(row.totalAmount),value(row.receiptOriginalName),row.fullTank?'Yes':'No',value(row.relatedDispatchDate)])}/></RecordSection>}

function Tyres({records,disabled,save}){const[state,setState]=useState({tyrePosition:'',brand:'',installDate:'',installMileage:'',cost:'',repairRotationHistory:'',replacementDate:'',photo:null});const submit=async event=>{event.preventDefault();await save({...state,photo:await filePayload(state.photo)});setState({...state,tyrePosition:'',photo:null})};return <RecordSection title="Tyre Records"><form className="record-form" onSubmit={submit}>{['tyrePosition','brand','installDate','installMileage','cost','repairRotationHistory','replacementDate'].map(key=><input required={key==='tyrePosition'} key={key} type={key.includes('Date')?'date':['installMileage','cost'].includes(key)?'number':'text'} placeholder={key} value={state[key]} onChange={e=>setState({...state,[key]:e.target.value})}/>)}<File label="Photo" image onChange={file=>setState({...state,photo:file})}/><button disabled={disabled}>Add tyre record</button></form><RecordTable headers={['Position','Brand','Install Date','Mileage','Cost','Repair/Rotation','Replacement','Photo']} rows={records.map(row=>[row.tyrePosition,value(row.brand),value(row.installDate),value(row.installMileage),money(row.cost),value(row.repairRotationHistory),value(row.replacementDate),value(row.photoOriginalName)])}/></RecordSection>}

function Usage({records,employees,disabled,save}){const[state,setState]=useState({dispatchDate:'',driverId:'',tripsCompleted:'',collectionWeightKg:'',kilometres:'',fuelCost:'',downtimeHours:'',incidents:''});return <RecordSection title="Vehicle Usage History"><form className="record-form" onSubmit={event=>{event.preventDefault();save(state)}}><input required type="date" value={state.dispatchDate} onChange={e=>setState({...state,dispatchDate:e.target.value})}/><select value={state.driverId} onChange={e=>setState({...state,driverId:e.target.value})}><option value="">Driver</option>{employees.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>{['tripsCompleted','collectionWeightKg','kilometres','fuelCost','downtimeHours'].map(key=><input key={key} type="number" placeholder={key} value={state[key]} onChange={e=>setState({...state,[key]:e.target.value})}/>)}<input placeholder="Incidents" value={state.incidents} onChange={e=>setState({...state,incidents:e.target.value})}/><button disabled={disabled}>Save</button></form><RecordTable headers={['Dispatch','Driver ID','Trips','Weight kg','KM','Fuel Cost','Downtime h','Incidents']} rows={records.map(row=>[row.dispatchDate,value(row.driverId),row.tripsCompleted,value(row.collectionWeightKg),value(row.kilometres),money(row.fuelCost),value(row.downtimeHours),value(row.incidents)])}/></RecordSection>}

function Documents({records,disabled,save,reload}){const[state,setState]=useState({documentType:'ownership_certificate',title:'',documentDate:'',expiryDate:'',remark:'',file:null});const submit=async event=>{event.preventDefault();await save({...state,file:await filePayload(state.file)});setState({...state,title:'',remark:'',file:null})};const replace=async(row,file)=>{if(!file)return;await api(`/api/vehicle-documents/${row.id}/replace`,{method:'POST',body:JSON.stringify({file:await filePayload(file),remark:'Replacement version'})});await reload()};return <RecordSection title="Vehicle Documents" note="Authenticated office access only. Previous versions are retained."><form className="record-form" onSubmit={submit}><select value={state.documentType} onChange={e=>setState({...state,documentType:e.target.value})}>{['ownership_certificate','road_tax','insurance','puspakom','permit_license','other'].map(item=><option key={item}>{item}</option>)}</select><input placeholder="Title" value={state.title} onChange={e=>setState({...state,title:e.target.value})}/><input placeholder="Remark" value={state.remark} onChange={e=>setState({...state,remark:e.target.value})}/><input type="date" value={state.documentDate} onChange={e=>setState({...state,documentDate:e.target.value})}/><input type="date" value={state.expiryDate} onChange={e=>setState({...state,expiryDate:e.target.value})}/><File label="File" onChange={file=>setState({...state,file})}/><button disabled={disabled}>Upload file</button></form><RecordTable headers={['Type','Version','Status','File','Uploaded By / At','Size','SHA-256','Remark','Actions']} rows={records.map(row=>[row.documentType,row.versionNumber,row.isCurrent?'Current':'Previous',row.originalName,`${value(row.uploadedBy)} / ${row.uploadedAt}`,`${row.sizeBytes} bytes`,row.sha256||'—',value(row.remark),<span key={row.id}><a href={`/api/vehicle-documents/${row.id}/preview`} target="_blank" rel="noreferrer">Preview</a> · <a href={`/api/vehicle-documents/${row.id}/download`}>Download</a>{row.isCurrent&&!disabled&&<label> · Replace<input hidden type="file" accept="image/jpeg,image/png,application/pdf" onChange={event=>replace(row,event.target.files[0])}/></label>}</span>])}/></RecordSection>}

function File({label,image=false,onChange}){return <label className="record-file">{label}<input type="file" accept={image?'image/jpeg,image/png,image/webp':'image/jpeg,image/png,application/pdf'} onChange={event=>onChange(event.target.files[0]||null)}/></label>}
function RecordSection({title,note,children}){return <section className="vehicle-record-section"><header><h2>{title}</h2>{note&&<p>{note}</p>}</header>{children}</section>}
function RecordTable({headers,rows}){return <div className="vehicle-table"><table><thead><tr>{headers.map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,index)=><tr key={index}>{row.map((item,cell)=><td key={cell}>{item}</td>)}</tr>):<tr><td colSpan={headers.length}>No matching data.</td></tr>}</tbody></table></div>}
