import { useCallback, useEffect, useState } from 'react'
import './VehicleDetailPage.css'

const api=async(url,options={})=>{const response=await fetch(url,{headers:{'Content-Type':'application/json'},...options}),data=await response.json();if(!response.ok)throw new Error(data.error||'操作失败');return data}
const filePayload=file=>new Promise((resolve,reject)=>{if(!file)return resolve(null);const reader=new FileReader();reader.onload=()=>resolve({name:file.name,dataUrl:reader.result});reader.onerror=reject;reader.readAsDataURL(file)})
const money=value=>value==null?'—':`RM ${Number(value).toFixed(2)}`
const value=value=>value==null||value===''?'—':value

export default function VehicleDetailPage({vehicleId,resources,onBack,currentUser}){
  const[detail,setDetail]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  const load=useCallback(()=>api(`/api/vehicles/${vehicleId}`).then(setDetail).catch(item=>setError(item.message)),[vehicleId]);useEffect(()=>{load()},[load])
  const save=async(url,body)=>{setBusy(true);setError('');try{await api(url,{method:url===`/api/vehicles/${vehicleId}`?'PATCH':'POST',body:JSON.stringify({...body,changedBy:currentUser.name,updatedBy:currentUser.name,uploadedBy:currentUser.name})});setMessage('车辆资料已保存。');await load()}catch(item){setError(item.message)}finally{setBusy(false)}}
  if(!detail)return <div className="page"><button onClick={onBack}>← 返回 Vehicle Master</button>{error||'车辆资料载入中…'}</div>
  const sold=detail.status==='sold'
  return <div className="page vehicle-detail-page"><button className="vehicle-back" onClick={onBack}>← 返回 Vehicle Master</button><header className="vehicle-detail-title"><div><em>VEHICLE MANAGEMENT</em><h1>{detail.vehicleCode} — {detail.registrationNumber}</h1><p>{sold?'已出售车辆：仅保留历史，不参加派车、保养或法定提醒。':'司机按每天派车记录关联，不会永久绑定车辆。'}</p></div><span className={`vehicle-state ${detail.status}`}>{detail.status}</span></header>{message&&<div className="planner-message">✓ {message}</div>}{error&&<div className="data-error">{error}</div>}
    <BasicForm detail={detail} resources={resources} disabled={busy||sold} save={body=>save(`/api/vehicles/${vehicleId}`,body)}/>
    {!sold&&<Compliance detail={detail.compliance||{}} disabled={busy} save={body=>save(`/api/vehicles/${vehicleId}/compliance`,body)}/>} 
    <Maintenance records={detail.maintenanceRecords} disabled={busy||sold} save={body=>save(`/api/vehicles/${vehicleId}/maintenance`,body)}/>
    <Fuel records={detail.fuelRecords} employees={resources?.employees||[]} disabled={busy||sold} save={body=>save(`/api/vehicles/${vehicleId}/fuel`,body)}/>
    <Tyres records={detail.tyreRecords} disabled={busy||sold} save={body=>save(`/api/vehicles/${vehicleId}/tyres`,body)}/>
    <Usage records={detail.usageHistory} employees={resources?.employees||[]} disabled={busy||sold} save={body=>save(`/api/vehicles/${vehicleId}/usage`,body)}/>
    <Documents records={detail.documents} disabled={busy||sold} save={body=>save(`/api/vehicles/${vehicleId}/documents`,body)}/>
    <section className="vehicle-record-section"><header><h2>Vehicle Status History</h2><p>状态变动不可删除。</p></header><RecordTable headers={['Changed At','Previous','New','Reason','Changed By']} rows={detail.statusHistory.map(row=>[row.changedAt,row.previousStatus,row.newStatus,row.reason,row.changedBy])}/></section>
  </div>
}

function BasicForm({detail,resources,disabled,save}){
  const[state,setState]=useState({vehicleCode:detail.vehicleCode,registrationNumber:detail.registrationNumber||'',vehicleName:detail.vehicleName||'',brand:detail.brand||'',model:detail.model||'',manufactureYear:detail.manufactureYear||'',registrationDate:detail.registrationDate||'',vehicleType:detail.vehicleType||'',chassisNumber:detail.chassisNumber||'',engineNumber:detail.engineNumber||'',grossVehicleWeightKg:detail.grossVehicleWeightKg||'',unladenWeightKg:detail.unladenWeightKg||'',capacityKg:detail.capacityKg||'',status:detail.status,defaultBaseLocationId:detail.defaultBaseLocationId||'',preferredZoneIds:detail.preferredZones.map(item=>item.id),remark:detail.remark||''})
  const field=(key,label,type='text')=><label>{label}<input type={type} value={state[key]} disabled={disabled} onChange={event=>setState({...state,[key]:event.target.value})}/></label>
  return <section className="vehicle-record-section"><header><h2>基本资料</h2><p>Current Driver：{detail.currentDriver?`${detail.currentDriver.name}（最近派车 ${detail.currentDriver.dispatchDate}）`:'未分配'}；这不是永久绑定。</p></header><form className="vehicle-basic-grid" onSubmit={event=>{event.preventDefault();save({...state,manufactureYear:state.manufactureYear?Number(state.manufactureYear):null,grossVehicleWeightKg:state.grossVehicleWeightKg?Number(state.grossVehicleWeightKg):null,unladenWeightKg:state.unladenWeightKg?Number(state.unladenWeightKg):null,capacityKg:state.capacityKg?Number(state.capacityKg):null,defaultBaseLocationId:Number(state.defaultBaseLocationId)||null})}}>{field('vehicleCode','Vehicle Number')}{field('registrationNumber','Registration Number')}{field('vehicleName','Vehicle Name')}{field('brand','Brand')}{field('model','Model')}{field('manufactureYear','Manufacture Year','number')}{field('registrationDate','Registration Date','date')}{field('vehicleType','Vehicle Type')}{field('chassisNumber','Chassis Number')}{field('engineNumber','Engine Number')}{field('grossVehicleWeightKg','Gross Vehicle Weight kg','number')}{field('unladenWeightKg','Unladen Weight kg','number')}{field('capacityKg','Operational Capacity kg','number')}<label>Status<select value={state.status} disabled={disabled} onChange={event=>setState({...state,status:event.target.value})}><option value="available">Available</option><option value="active">Active</option><option value="maintenance">Maintenance</option><option value="inactive">Inactive</option><option value="sold">Sold</option></select></label><label>Default Base<select value={state.defaultBaseLocationId} disabled={disabled} onChange={event=>setState({...state,defaultBaseLocationId:event.target.value})}><option value="">未设置</option>{resources?.locations?.filter(item=>item.isActive).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Usual Zones<select multiple value={state.preferredZoneIds.map(String)} disabled={disabled} onChange={event=>setState({...state,preferredZoneIds:[...event.target.selectedOptions].map(option=>Number(option.value))})}>{resources?.zoneGroups?.filter(item=>item.isActive).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="vehicle-wide">Remark<textarea value={state.remark} disabled={disabled} onChange={event=>setState({...state,remark:event.target.value})}/></label><button disabled={disabled}>保存基本资料</button></form></section>
}

function Compliance({detail,disabled,save}){const[state,setState]=useState(detail);const fields=[['puspakomDueDate','Puspakom'],['roadTaxDueDate','Road Tax'],['insuranceDueDate','Insurance'],['loanPaymentDueDate','Loan Payment'],['nextServiceDate','Next Service']];return <section className="vehicle-record-section"><header><h2>法定与到期提醒</h2><p>30 天黄、14 天橙、7 天红；过期显示严重警告。</p></header><div className="reminder-grid">{fields.map(([key,label])=><label className={`reminder-card ${detail[`${key}Alert`]?.level||''}`} key={key}><span>{label}</span><input type="date" value={state[key]||''} onChange={event=>setState({...state,[key]:event.target.value})}/><b>{detail[`${key}Alert`]?.message||'未设置'}</b></label>)}</div><form className="record-inline" onSubmit={event=>{event.preventDefault();save(state)}}><label>Next Service Mileage<input type="number" value={state.nextServiceMileage||''} onChange={event=>setState({...state,nextServiceMileage:event.target.value})}/></label><button disabled={disabled}>保存提醒</button></form></section>}

function Maintenance({records,disabled,save}){const[state,setState]=useState({date:'',mileage:'',faultDescription:'',repairWork:'',partsReplaced:'',workshop:'',labourCost:'',partsCost:'',downtimeStart:'',downtimeEnd:'',approvedBy:'',followUpDate:'',invoiceAttachment:null,beforePhoto:null,afterPhoto:null});const submit=async event=>{event.preventDefault();await save({...state,invoiceAttachment:await filePayload(state.invoiceAttachment),beforePhoto:await filePayload(state.beforePhoto),afterPhoto:await filePayload(state.afterPhoto)});setState({...state,date:'',faultDescription:'',repairWork:'',invoiceAttachment:null,beforePhoto:null,afterPhoto:null})};return <RecordSection title="Maintenance Records" note="发票及维修前后照片只保存于本机 data/uploads。"><form className="record-form" onSubmit={submit}><input required type="date" value={state.date} onChange={e=>setState({...state,date:e.target.value})}/>{['mileage','faultDescription','repairWork','partsReplaced','workshop','labourCost','partsCost','downtimeStart','downtimeEnd','approvedBy','followUpDate'].map(key=><input key={key} type={key.includes('Cost')||key==='mileage'?'number':key.includes('Date')?'date':'text'} placeholder={key} value={state[key]} onChange={e=>setState({...state,[key]:e.target.value})}/>)}<File label="Invoice" onChange={file=>setState({...state,invoiceAttachment:file})}/><File label="Before Photo" image onChange={file=>setState({...state,beforePhoto:file})}/><File label="After Photo" image onChange={file=>setState({...state,afterPhoto:file})}/><button disabled={disabled}>新增保养记录</button></form><RecordTable headers={['Date','Mileage','Fault','Repair','Workshop','Labour','Parts','Total','Invoice','Before / After','Downtime','Approved','Follow-up']} rows={records.map(row=>[row.maintenanceDate,value(row.mileage),value(row.faultDescription),value(row.repairWork),value(row.workshop),money(row.labourCost),money(row.partsCost),money(row.totalCost),value(row.invoiceOriginalName),`${value(row.beforePhotoOriginalName)} / ${value(row.afterPhotoOriginalName)}`,`${value(row.downtimeStart)} / ${value(row.downtimeEnd)}`,value(row.approvedBy),value(row.followUpDate)])}/></RecordSection>}

function Fuel({records,employees,disabled,save}){const[state,setState]=useState({dateTime:'',driverId:'',mileage:'',fuelStation:'',litres:'',pricePerLitre:'',totalAmount:'',fullTank:true,relatedDispatchDate:'',receiptPhoto:null});const submit=async event=>{event.preventDefault();await save({...state,receiptPhoto:await filePayload(state.receiptPhoto)});setState({...state,dateTime:'',receiptPhoto:null})};return <RecordSection title="Fuel Records"><form className="record-form" onSubmit={submit}><input required type="datetime-local" value={state.dateTime} onChange={e=>setState({...state,dateTime:e.target.value})}/><select value={state.driverId} onChange={e=>setState({...state,driverId:e.target.value})}><option value="">Driver</option>{employees.filter(item=>String(item.jobRole).toLowerCase()==='driver').map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>{['mileage','fuelStation','litres','pricePerLitre','totalAmount'].map(key=><input key={key} type={key==='fuelStation'?'text':'number'} placeholder={key} value={state[key]} onChange={e=>setState({...state,[key]:e.target.value})}/>)}<input type="date" value={state.relatedDispatchDate} onChange={e=>setState({...state,relatedDispatchDate:e.target.value})}/><label><input type="checkbox" checked={state.fullTank} onChange={e=>setState({...state,fullTank:e.target.checked})}/> Full Tank</label><File label="Receipt" image onChange={file=>setState({...state,receiptPhoto:file})}/><button disabled={disabled}>新增加油记录</button></form><RecordTable headers={['Date/Time','Driver ID','Mileage','Station','Litres','Price/L','Total','Receipt','Full Tank','Dispatch']} rows={records.map(row=>[row.fuelAt,value(row.driverId),value(row.mileage),value(row.fuelStation),value(row.litres),money(row.pricePerLitre),money(row.totalAmount),value(row.receiptOriginalName),row.fullTank?'Yes':'No',value(row.relatedDispatchDate)])}/></RecordSection>}

function Tyres({records,disabled,save}){const[state,setState]=useState({tyrePosition:'',brand:'',installDate:'',installMileage:'',cost:'',repairRotationHistory:'',replacementDate:'',photo:null});const submit=async event=>{event.preventDefault();await save({...state,photo:await filePayload(state.photo)});setState({...state,tyrePosition:'',photo:null})};return <RecordSection title="Tyre Records"><form className="record-form" onSubmit={submit}>{['tyrePosition','brand','installDate','installMileage','cost','repairRotationHistory','replacementDate'].map(key=><input required={key==='tyrePosition'} key={key} type={key.includes('Date')?'date':['installMileage','cost'].includes(key)?'number':'text'} placeholder={key} value={state[key]} onChange={e=>setState({...state,[key]:e.target.value})}/>)}<File label="Photo" image onChange={file=>setState({...state,photo:file})}/><button disabled={disabled}>新增轮胎记录</button></form><RecordTable headers={['Position','Brand','Install Date','Mileage','Cost','Repair/Rotation','Replacement','Photo']} rows={records.map(row=>[row.tyrePosition,value(row.brand),value(row.installDate),value(row.installMileage),money(row.cost),value(row.repairRotationHistory),value(row.replacementDate),value(row.photoOriginalName)])}/></RecordSection>}

function Usage({records,employees,disabled,save}){const[state,setState]=useState({dispatchDate:'',driverId:'',tripsCompleted:'',collectionWeightKg:'',kilometres:'',fuelCost:'',downtimeHours:'',incidents:''});return <RecordSection title="Vehicle Usage History"><form className="record-form" onSubmit={event=>{event.preventDefault();save(state)}}><input required type="date" value={state.dispatchDate} onChange={e=>setState({...state,dispatchDate:e.target.value})}/><select value={state.driverId} onChange={e=>setState({...state,driverId:e.target.value})}><option value="">Driver</option>{employees.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>{['tripsCompleted','collectionWeightKg','kilometres','fuelCost','downtimeHours'].map(key=><input key={key} type="number" placeholder={key} value={state[key]} onChange={e=>setState({...state,[key]:e.target.value})}/>)}<input placeholder="Incidents" value={state.incidents} onChange={e=>setState({...state,incidents:e.target.value})}/><button disabled={disabled}>保存使用记录</button></form><RecordTable headers={['Dispatch','Driver ID','Trips','Weight kg','KM','Fuel Cost','Downtime h','Incidents']} rows={records.map(row=>[row.dispatchDate,value(row.driverId),row.tripsCompleted,value(row.collectionWeightKg),value(row.kilometres),money(row.fuelCost),value(row.downtimeHours),value(row.incidents)])}/></RecordSection>}

function Documents({records,disabled,save}){const[state,setState]=useState({documentType:'jpj_registration',title:'',documentDate:'',expiryDate:'',file:null});const submit=async event=>{event.preventDefault();await save({...state,file:await filePayload(state.file)});setState({...state,title:'',file:null})};return <RecordSection title="Vehicle Documents" note="JPJ、Puspakom、保险、Road Tax、融资、维修、轮胎及事故文件。"><form className="record-form" onSubmit={submit}><select value={state.documentType} onChange={e=>setState({...state,documentType:e.target.value})}>{['jpj_registration','puspakom','insurance','road_tax','financing','repair_invoice','tyre_invoice','accident_document'].map(item=><option key={item}>{item}</option>)}</select><input placeholder="Title" value={state.title} onChange={e=>setState({...state,title:e.target.value})}/><input type="date" value={state.documentDate} onChange={e=>setState({...state,documentDate:e.target.value})}/><input type="date" value={state.expiryDate} onChange={e=>setState({...state,expiryDate:e.target.value})}/><File label="File" onChange={file=>setState({...state,file})}/><button disabled={disabled}>上传文件</button></form><RecordTable headers={['Type','Title','File','Document Date','Expiry','Uploaded']} rows={records.map(row=>[row.documentType,value(row.title),row.originalName,value(row.documentDate),value(row.expiryDate),row.uploadedAt])}/></RecordSection>}

function File({label,image=false,onChange}){return <label className="record-file">{label}<input type="file" accept={image?'image/jpeg,image/png,image/webp':'image/jpeg,image/png,image/webp,application/pdf'} onChange={event=>onChange(event.target.files[0]||null)}/></label>}
function RecordSection({title,note,children}){return <section className="vehicle-record-section"><header><h2>{title}</h2>{note&&<p>{note}</p>}</header>{children}</section>}
function RecordTable({headers,rows}){return <div className="vehicle-table"><table><thead><tr>{headers.map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,index)=><tr key={index}>{row.map((item,cell)=><td key={cell}>{item}</td>)}</tr>):<tr><td colSpan={headers.length}>暂无记录</td></tr>}</tbody></table></div>}
