import {canManageDispatch} from '../shared/dispatchAccess.js'
import {useUi} from './i18n.jsx'
import {DispatchPlanningReview,DispatchScheduleTools} from './DispatchScheduleTools.jsx'
import RouteCustomerList from './RouteCustomerList.jsx'
import RouteUnloadingRecords from './RouteUnloadingRecords.jsx'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import './Planner.css'
import {kuchingDate} from '../shared/kuchingTime.js'
import {useI18n} from './i18n.jsx'
import {apiRequest as request} from './apiClient.js'
import {formatBranchId,formatCustomerId} from '../shared/typedIds.js'
import {MAX_ASSIGNED_CREW} from '../shared/dispatchRules.js'
import SharedGpsInput from './SharedGpsInput.jsx'
import FormActionBar from './FormActionBar.jsx'
import RouteOptimizationMap from './RouteOptimizationMap.jsx'

const routeDateWeekday=new Intl.DateTimeFormat('en-MY',{weekday:'long',timeZone:'Asia/Kuching'})
const formatRouteDate=(date,ui)=>`${date} (${ui(routeDateWeekday.format(new Date(`${date}T00:00:00+08:00`)))})`
const localDate=kuchingDate
const vehicleStatus={available:'Available',active:'Active',maintenance:'Maintenance',inactive:'Inactive',sold:'Sold'}
const employmentStatus={active:'Active',on_leave:'On Leave',inactive:'Inactive'}
const usableVehicle=(vehicle,date)=>['available','active'].includes(vehicle.status)&&(!vehicle.isTemporary||vehicle.temporaryDate===date)
const usableEmployee=(employee)=>Boolean(employee.isActive)&&employee.employmentStatus==='active'
const vehicleLabel=(item,ui)=>`${item.vehicleCode||item.vehicle} — ${item.registrationNumber||ui('Registration plate not set')} — ${ui(vehicleStatus[item.status]||item.status)}`

export default function WeeklyDispatchPage({currentUser}){
  const ui=useUi()

  const{t}=useI18n()
  const[reviewDate,setReviewDate]=useState(()=>{const date=sessionStorage.getItem('kcs-review-planner-date');sessionStorage.removeItem('kcs-review-planner-date');return /^\d{4}-\d{2}-\d{2}$/.test(date||'')?date:null})
  const[displayMode,setDisplayMode]=useState('dispatch'),[selectedWeekDate,setSelectedWeekDate]=useState(reviewDate||localDate()),[selectedRouteNumber,setSelectedRouteNumber]=useState(1),[data,setData]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  const canEditDispatch=canManageDispatch(currentUser)
  const canManageVehicles=['owner_admin','operations_admin'].includes(currentUser.systemRole)||currentUser.permissions?.includes('vehicle_manage')
  const canApproveDefer=canManageDispatch(currentUser)
  const loadSequence=useRef(0)
  const load=useCallback(async()=>{const sequence=++loadSequence.current;setError('');try{
    const result=await request(reviewDate?`/api/dispatch/week?startDate=${reviewDate}`:canEditDispatch?'/api/dispatch/ensure-rolling-week':`/api/dispatch/week?startDate=${localDate()}`,!reviewDate&&canEditDispatch?{method:'POST'}:undefined)
    if(sequence===loadSequence.current)setData(result)
  }catch(e){if(sequence===loadSequence.current)setError(e.message)}},[canEditDispatch,reviewDate])
  useEffect(()=>{load()},[load])
  useEffect(()=>{const refresh=()=>load();window.addEventListener('kcs-handover-saved',refresh);return()=>window.removeEventListener('kcs-handover-saved',refresh)},[load])
  useEffect(()=>{const wake=()=>{if(document.visibilityState==='visible')load()};const timer=setInterval(load,10000);window.addEventListener('focus',load);document.addEventListener('visibilitychange',wake);return()=>{clearInterval(timer);window.removeEventListener('focus',load);document.removeEventListener('visibilitychange',wake)}},[load])
  const act=async(date,action,reason='')=>{setBusy(true);setMessage('');try{await request(`/api/dispatch/day/${date}/${action}`,{method:'POST',body:JSON.stringify({[action==='approve'?'approvedBy':'reopenedBy']:currentUser.name,reason})});setMessage(`${date} ${action==='approve'?'approved':'approval withdrawn'}.`);await load()}catch(e){setError(e.message);await load();throw e}finally{setBusy(false)}}
  const patchStop=async(id,body)=>{try{await request(`/api/dispatch/stops/${id}`,{method:'PATCH',body:JSON.stringify({...body,changedBy:currentUser.name})});await load()}catch(e){setError(e.message)}}
  const patchTrip=async(id,body)=>{try{await request(`/api/dispatch/trips/${id}`,{method:'PATCH',body:JSON.stringify(body)});setMessage(ui("Start Location updated."));await load()}catch(e){setError(e.message);throw e}}
  const assignStopsToRoute=async(date,group,routeNumber)=>{const scrollTop=window.scrollY;try{await request(`/api/dispatch/day/${date}/assign-route`,{method:'POST',body:JSON.stringify({areaId:group.areaId??`zone:${group.zoneGroupId}`,stopIds:group.stops.map(stop=>stop.id),routeNumber,changedBy:currentUser.name})});setMessage(ui("{0} 的 {1} 家客户已分配到 Route {2}。", {0: group.zoneGroupName||group.areaName, 1: group.customerCount, 2: routeNumber}));await load();requestAnimationFrame(()=>window.scrollTo(0,scrollTop));return true}catch(e){setError(e.message);throw e}}
  const handleDrop=async(event,body)=>{event.preventDefault();const id=event.dataTransfer.getData('text/stop-id');if(id)await patchStop(id,body)}
  const assignVehicle=async(date,vehicleId,body)=>{try{await request(`/api/dispatch/day/${date}/vehicle/${vehicleId}`,{method:'PATCH',body:JSON.stringify({...body,changedBy:currentUser.name})});await load()}catch(e){setError(e.message)}}
  const assignRoute=async(date,routeNumber,vehicleId)=>{try{await request(`/api/dispatch/day/${date}/route/${routeNumber}/vehicle`,{method:'PATCH',body:JSON.stringify({vehicleId:vehicleId||null})});setMessage(ui("Route {0} 已{1}；客户与顺序没有改变。", {0: routeNumber, 1: ui(vehicleId?'整条分配到所选车辆':'解除当天车辆分配')}));await load()}catch(e){setError(e.message)}}
  const renameRoute=async(routeNumber,currentName)=>{const name=prompt(ui("请输入新的 Route 名称："),currentName);if(name==null||!name.trim()||name.trim()===currentName)return;try{await request(`/api/dispatch/routes/${routeNumber}`,{method:'PATCH',body:JSON.stringify({name:name.trim()})});setMessage(ui("Route {0} 已改名为 {1}。", {0: routeNumber, 1: name.trim()}));await load()}catch(e){setError(e.message)}}
  const reorderRouteCustomer=async(date,routeNumber,stopId,direction)=>{try{await request(`/api/dispatch/day/${date}/route/${routeNumber}/reorder`,{method:'POST',body:JSON.stringify({stopId,direction})});setMessage(ui("客户顺序已保存；以后同一星期会跟随这个排列。"));await load()}catch(e){setError(e.message)}}
  const approveSingleRoute=async(date,routeNumber)=>{try{const check=await request(`/api/dispatch/day/${date}/route/${routeNumber}/approval-check`);if(!check.ok)throw new Error(check.issues.map(item=>ui(item.message)).join(' '));await request(`/api/dispatch/day/${date}/route/${routeNumber}/approve`,{method:'POST',body:JSON.stringify({reason:'Route checked and ready'})});setMessage(ui("Route {0} 已单独批准。", {0: routeNumber}));await load()}catch(e){setError(e.message)}}
  const withdrawDayApproval=async(date,routeNumber)=>{const reason=prompt(ui("请输入撤回批准的原因："),ui("需要修改路线"));if(!reason?.trim())return;setBusy(true);setError('');try{await request(`/api/dispatch/day/${date}/route/${routeNumber}/reopen`,{method:'POST',body:JSON.stringify({reason:reason.trim()})});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const transferVehicle=async(date,sourceVehicleId,vehicles)=>{const available=vehicles.filter(item=>item.id!==sourceVehicleId&&usableVehicle(item,date));const answer=prompt(ui("Enter target vehicle number or plate: {0}", {0: available.map(item=>vehicleLabel(item,ui)).join('\n')}),'QAV3468');if(!answer)return;const normalized=answer.replace(/[\s-]/g,'').toLowerCase(),target=available.find(item=>[item.vehicleCode,item.registrationNumber,String(item.id)].some(itemValue=>String(itemValue||'').replace(/[\s-]/g,'').toLowerCase()===normalized));if(!target){setError(ui("No available target vehicle"));return}const setSourceMaintenance=confirm(ui("After route transfer, Set the original vehicle to Maintenance？")),reason=prompt(ui("Enter the transfer reason:"),ui("Vehicle breakdown／Replace vehicle"))||'Vehicle transfer';try{await request(`/api/dispatch/day/${date}/vehicle/${sourceVehicleId}/transfer`,{method:'POST',body:JSON.stringify({targetVehicleId:target.id,transferDriver:true,setSourceMaintenance,reason,changedBy:currentUser.name})});setMessage(ui("Trip, Customer routes and driver transferred to {0}.", {0: vehicleLabel(target,ui)}));await load()}catch(e){setError(e.message)}}
  const addTemporaryVehicle=async(date)=>{const vehicleCode=prompt(ui("Temporary vehicle number:"),`Temporary Lorry (${date})`);if(!vehicleCode)return;try{await request('/api/vehicles/temporary',{method:'POST',body:JSON.stringify({date,vehicleCode})});setMessage(ui("{0} added for {1}.", {0: vehicleCode, 1: date}));await load()}catch(e){setError(e.message)}}
  const addPermanentVehicle=async(date)=>{const vehicleCode=prompt(ui("Permanent vehicle number:"));if(!vehicleCode)return;const registrationNumber=prompt(ui("Registration plate (must be unique):"));if(!registrationNumber)return;const capacity=prompt(ui("Capacity (kg, optional):"),'');if(capacity!==''&&(!Number.isFinite(Number(capacity))||Number(capacity)<0)){setError(ui("Capacity must be a non-negative number."));return}try{await request('/api/vehicles',{method:'POST',body:JSON.stringify({dispatchDate:date,vehicleCode,registrationNumber,capacityKg:capacity===''?null:Number(capacity)})});setMessage(ui("{0} added permanently and selected for {1}.", {0: vehicleCode, 1: date}));await load()}catch(e){setError(e.message)}}
  const moveStop=async(day,stop,targetVehicleId)=>{setError('');try{await request(`/api/dispatch/stops/${stop.id}/move-vehicle`,{method:'POST',body:JSON.stringify({targetVehicleId,expectedRevision:day.revision,reason:'Supervisor moved one route stop'})});setMessage(ui("{0} moved to another vehicle.", {0: stop.branchName||`Stop ${stop.id}`}));await load()}catch(e){setError(e.message);await load()}}
  const decideDefer=async(item,decision)=>{const reason=prompt(t(decision==='approve'?'deferApproval.approveReason':'deferApproval.rejectReason'));if(!reason)return;setBusy(true);setError('');try{await request(`/api/dispatch/defer-requests/${item.id}/${decision}`,{method:'POST',body:JSON.stringify({reason})});setMessage(t(decision==='approve'?'deferApproval.approvedMessage':'deferApproval.rejectedMessage',{branch:item.branchName}));await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const activeWeekDate=data?.days?.some(day=>day.dispatch_date===selectedWeekDate)?selectedWeekDate:data?.days?.[0]?.dispatch_date
  const visibleDays=displayMode==='route'?(data?.days||[]):(data?.days||[]).filter(day=>day.dispatch_date===activeWeekDate)
  const prepareReviewDay=async()=>{setBusy(true);setError('');try{await request('/api/dispatch/generate-day',{method:'POST',body:JSON.stringify({payload:{startDate:reviewDate,onlyMissing:true}})});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <div className="page planner-page">
    <label className="planner-date-picker">{t('dateReview.date')}<input type="date" value={reviewDate||localDate()} onChange={e=>{if(e.target.value){setReviewDate(e.target.value);setSelectedWeekDate(e.target.value)}}}/></label>
    {reviewDate&&data&&!data.days.some(d=>d.dispatch_date===reviewDate)&&<section className="planner-message"><p>{reviewDate} · {t('dateReview.missingDay')}</p>{canEditDispatch&&<button disabled={busy} onClick={prepareReviewDay}>{t('dateReview.prepareDay')}</button>}</section>}
    <div className="planner-navigation"><div className="planner-toolbar planner-view-toolbar"><div><button className={displayMode==='dispatch'?'active':''} onClick={()=>setDisplayMode('dispatch')}>{ui("派车")}</button><button className={displayMode==='route'?'active':''} onClick={()=>setDisplayMode('route')}>{ui("Route")}</button></div></div>{data?.days?.length>0&&(displayMode==='dispatch'?<WeekDayTabs days={data.days} selectedDate={activeWeekDate} onSelect={setSelectedWeekDate}/>:<RouteWeekTabs days={data.days} selectedRouteNumber={selectedRouteNumber} onSelect={setSelectedRouteNumber}/>)}</div>
    {message&&<div className="planner-message">✓ {ui(message)}</div>}{error&&<div className="data-error">{ui(error)}</div>}
    {data&&canEditDispatch&&<DispatchPlanningReview data={data}/>}
    {!data?<div className="data-loading">{t('planner.loading')}</div>:<div className={displayMode==='route'?'route-week-board':'week-board week-board--single-day'}>{data.days.length===0?<div className="empty-week"><h2>{t('planner.empty')}</h2><p>{t('planner.emptyHelp')}</p></div>:visibleDays.map(day=><DayColumn days={data.days} canHandover={canManageDispatch(currentUser)} key={day.id} day={day} displayMode={displayMode} selectedRouteNumber={selectedRouteNumber} vehicles={data.vehicles||[]} employees={data.employees||[]} buyers={data.buyers||[]} endLocations={data.endLocations||[]} busy={busy} hasUnsavedChanges={false} patchStop={patchStop} patchTrip={patchTrip} handleDrop={handleDrop} assignStopsToRoute={assignStopsToRoute} assignRoute={assignRoute} renameRoute={renameRoute} reorderRouteCustomer={reorderRouteCustomer} approveSingleRoute={approveSingleRoute} withdrawDayApproval={withdrawDayApproval} assignVehicle={assignVehicle} transferVehicle={transferVehicle} addTemporaryVehicle={addTemporaryVehicle} addPermanentVehicle={addPermanentVehicle} moveStop={moveStop} decideDefer={decideDefer} canApproveDefer={canApproveDefer} canEditDispatch={canEditDispatch} canManageVehicles={canManageVehicles}/>)}</div>}
  </div>
}

function WeekDayTabs({days,selectedDate,onSelect}){
  const ui=useUi()

  const{language}=useI18n()
  const formatter=new Intl.DateTimeFormat(language==='zh'?'zh-MY':language==='ms'?'ms-MY':'en-MY',{month:'numeric',day:'numeric',weekday:'short',timeZone:'Asia/Kuching'})
  return <nav className="week-day-tabs" aria-label={ui("一周派车日期")}>{days.map(day=>{const customerRoutes=(day.routeBoards||[]).filter(route=>route.customerCount>0),approved=customerRoutes.length>0&&customerRoutes.every(route=>route.approvalStatus==='approved');return <button type="button" key={day.dispatch_date} className={`${day.dispatch_date===selectedDate?'active ':''}${approved?'approved':''}`.trim()} aria-pressed={day.dispatch_date===selectedDate} onClick={()=>onSelect(day.dispatch_date)}><strong>{formatter.format(new Date(`${day.dispatch_date}T00:00:00+08:00`))}</strong><small>{day.routeBoards?.reduce((sum,route)=>sum+(route.customerCount||0),0)||day.stops?.length||0}{ui("家")}{approved?ui("· ✓ 已批准"):''}</small></button>})}</nav>
}

function RouteWeekTabs({days,selectedRouteNumber,onSelect}){
  const ui=useUi()

  const routes=days[0]?.routeBoards||[]
  return <nav className="week-day-tabs route-week-tabs" aria-label={ui("Route 1 至 5")}>{routes.map(route=>{const number=route.routeNumber;return <button type="button" key={number} className={number===selectedRouteNumber?'active':''} aria-pressed={number===selectedRouteNumber} onClick={()=>onSelect(number)}><strong><span data-i18n-raw>{route?.name||ui("Route {0}", {0: number})}</span></strong><small>{ui("查看七天")}</small></button>})}</nav>
}

function DayColumn({days,canHandover,day,displayMode,selectedRouteNumber,vehicles,employees,buyers,endLocations,busy,hasUnsavedChanges,patchStop,patchTrip,handleDrop,assignStopsToRoute,assignRoute,renameRoute,reorderRouteCustomer,approveSingleRoute,withdrawDayApproval,assignVehicle,transferVehicle,addTemporaryVehicle,addPermanentVehicle,moveStop,decideDefer,canApproveDefer,canEditDispatch,canManageVehicles}){
  const ui=useUi()

  const[selectedVehicleId,setSelectedVehicleId]=useState(day.vehicleBoards[0]?.id??null)
  useEffect(()=>{if(!day.vehicleBoards.some(board=>board.id===selectedVehicleId))setSelectedVehicleId(day.vehicleBoards[0]?.id??null)},[day.dispatch_date,day.vehicleBoards,selectedVehicleId])
  const selectedBoard=day.vehicleBoards.find(board=>board.id===selectedVehicleId)||day.vehicleBoards[0]
  const renderOperations=route=><RouteOperations day={day} route={route} employees={employees} buyers={buyers} endLocations={endLocations} patchStop={patchStop} patchTrip={patchTrip} assignVehicle={assignVehicle} moveStop={moveStop} canEditDispatch={canEditDispatch}/>
  return <section className={`day-column vehicle-day ${day.status}`}>
    {day.noGoodsNotices?.length>0&&<details><summary>{ui("客户通知无货 · 无需到店（")}{day.noGoodsNotices.length}）</summary>{day.noGoodsNotices.map(stop=><div key={stop.id}><b><span data-i18n-raw>{stop.branchName}</span></b><p>{stop.reason}</p>{canEditDispatch&&<DispatchScheduleTools stop={stop} day={day} days={days} routeNumber={stop.routeNumber} notice/>}</div>)}</details>}
    {displayMode==='route'?<RouteAssignmentPanel days={days} renderOperations={renderOperations} canHandover={canHandover} employees={employees} day={day} routeNumber={selectedRouteNumber} vehicles={vehicles} onAssign={assignRoute} onRename={renameRoute} onReorder={reorderRouteCustomer} onApprove={approveSingleRoute} onWithdraw={routeNumber=>withdrawDayApproval(day.dispatch_date,routeNumber)} busy={busy} hasUnsavedChanges={hasUnsavedChanges} canEdit={canEditDispatch}/>:<><RouteDispatchOverview day={day} vehicles={vehicles} days={days} renderOperations={renderOperations} canHandover={canHandover} employees={employees} onAssign={assignRoute} onRename={renameRoute} onReorder={reorderRouteCustomer} onApprove={approveSingleRoute} onWithdraw={routeNumber=>withdrawDayApproval(day.dispatch_date,routeNumber)} busy={busy} hasUnsavedChanges={hasUnsavedChanges} canEdit={canEditDispatch}/>{canApproveDefer&&<DeferApprovalPanel items={day.deferRequests||[]} busy={busy} onDecide={decideDefer}/>}<UnassignedPool day={day} patchStop={patchStop} assignStopsToRoute={assignStopsToRoute}/><div className="vehicle-tabs-row"><VehicleTabs boards={day.vehicleBoards} selectedVehicleId={selectedBoard?.id} onSelect={setSelectedVehicleId}/>{canManageVehicles&&canEditDispatch&&<div className="vehicle-create-actions"><button disabled={day.status!=='draft'} title={day.status!=='draft'?ui("Withdraw Approval first"):ui("Add permanent vehicle")} onClick={()=>addPermanentVehicle(day.dispatch_date)}>{ui("＋ 长期车")}</button><button disabled={day.status!=='draft'} title={day.status!=='draft'?ui("Withdraw Approval first"):ui("Add temporary vehicle for this date")} onClick={()=>addTemporaryVehicle(day.dispatch_date)}>{ui("＋ 临时车")}</button></div>}</div><div className="vehicle-board-list">{selectedBoard&&<VehicleBoard key={selectedBoard.id} day={day} board={selectedBoard} allBoards={day.vehicleBoards} vehicles={vehicles} employees={employees} buyers={buyers} endLocations={endLocations} patchStop={patchStop} patchTrip={patchTrip} handleDrop={handleDrop} assignVehicle={assignVehicle} transferVehicle={transferVehicle} moveStop={moveStop} canEditDispatch={canEditDispatch}/>}</div>{day.specialRequests.filter(item=>item.requestType==='potential_new').map(item=><div className={`special-route ${item.promisedToCustomer?'promised':''}`} key={item.id}><b>{item.promisedToCustomer?ui("Customer promise ·"):''}<span data-i18n-raw>{item.customerName}</span></b><small>{ui("Potential new customer · Trip")}{item.tripNumber||'—'}</small>{(!item.customerId||!item.branchId||item.occPrice==null||!item.paymentType)&&<span>{ui("Warning")}</span>}</div>)}</>}
  </section>
}

function RouteDispatchOverview(props){
  const ui=useUi()

  return <div aria-label={ui("当天 Route 总览")}><RouteAssignmentPanel {...props}/></div>
}

function DeferApprovalPanel({items,busy,onDecide}){
  const ui=useUi()
  const{t}=useI18n()
  const pending=items.filter(item=>item.status==='pending')
  if(!pending.length)return null
  return <section className="defer-approval-panel"><header><strong>{t('deferApproval.title')}</strong><span>{pending.length}</span></header>{pending.map(item=><article key={item.id}><div><b>{item.stopSequence}. <span data-i18n-raw>{item.customerName}</span> — <span data-i18n-raw>{item.branchName}</span></b><small>{item.vehicleName||'Vehicle'} · <span data-i18n-raw>{item.driverName}</span> · {t('mobile.expectedReturnTime')} {item.expectedReturnTime}</small><small>{ui(item.reason||'other')}</small></div><button type="button" disabled={busy} onClick={()=>onDecide(item,'approve')}>{t('deferApproval.approve')}</button><button type="button" disabled={busy} onClick={()=>onDecide(item,'reject')}>{t('deferApproval.reject')}</button></article>)}</section>
}

function VehicleTabs({boards,selectedVehicleId,onSelect}){
  const ui=useUi()

  if(!boards.length)return <p className="vehicle-tabs-empty">{ui("No vehicles available for this date.")}</p>
  return <nav className="vehicle-tabs" role="tablist" aria-label={ui("Vehicles available for this date")}>{boards.map(board=><button type="button" role="tab" aria-selected={board.id===selectedVehicleId} className={board.id===selectedVehicleId?'active':''} key={board.id} onClick={()=>onSelect(board.id)}><span data-i18n-raw>{board.registrationNumber||board.vehicle}</span></button>)}</nav>
}

// Kept for historical route-optimization audit access; fixed Route 1–5 no longer renders it.
// oxlint-disable-next-line no-unused-vars
function OptimizationControls({day,vehicles,disabled}){
  const ui=useUi()

  const{t}=useI18n(),[preview,setPreview]=useState(null),[open,setOpen]=useState(false),[working,setWorking]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[excluded,setExcluded]=useState([])
  const eligible=vehicles.filter(vehicle=>usableVehicle(vehicle,day.dispatch_date))
  const create=useCallback(async(mode='day',tripId=null)=>{setWorking(true);setError('');try{const result=await request('/api/dispatch/optimization/preview',{method:'POST',body:JSON.stringify({date:day.dispatch_date,mode,tripId,excludedVehicleIds:excluded})});setPreview(result);setOpen(true)}catch(e){setError(e.message)}finally{setWorking(false)}},[day.dispatch_date,excluded])
  useEffect(()=>{const handler=event=>{if(event.detail?.date===day.dispatch_date)create('trip',event.detail.tripId)};window.addEventListener('kcs-optimize-trip',handler);return()=>window.removeEventListener('kcs-optimize-trip',handler)},[create,day.dispatch_date])
  const apply=async()=>{if(!reason.trim()){setError(t('optimization.reasonRequired'));return}setWorking(true);try{await request(`/api/dispatch/optimization/${preview.runId}/apply`,{method:'POST',body:JSON.stringify({reason,expectedRevision:day.revision})});location.reload()}catch(e){setError(e.message);setWorking(false)}}
  return <section className="optimization-actions"><div><button className="primary" disabled={disabled||working||day.status!=='draft'} onClick={()=>create()}>{working?t('optimization.working'):t('optimization.dayAction')}</button><small>{t('optimization.roadLabel')}</small></div><details><summary>{t('optimization.vehicleSelection')}</summary>{eligible.map(vehicle=><label key={vehicle.id}><input type="checkbox" checked={!excluded.includes(vehicle.id)} onChange={()=>setExcluded(value=>value.includes(vehicle.id)?value.filter(id=>id!==vehicle.id):[...value,vehicle.id])}/>{vehicleLabel(vehicle,ui)}</label>)}</details><AvailabilityManager date={day.dispatch_date}/><OptimizationRuleReview/>{error&&<p className="data-error">{ui(error)}</p>}
    {open&&preview&&<div className="optimization-modal" role="dialog" aria-modal="true" aria-label={t('optimization.previewTitle')}><div><header><div><h3>{t('optimization.previewTitle')}</h3><small>{preview.provider}{preview.cached?` · ${t('optimization.cached')}`:''}</small></div><button onClick={()=>setOpen(false)}>×</button></header><RouteOptimizationMap routes={preview.routes||[]}/><div className="optimization-metrics"><span><b>{preview.metrics?.totalDistanceMeters?`${(preview.metrics.totalDistanceMeters/1000).toFixed(1)} km`:'—'}</b>{t('optimization.distance')}</span><span><b>{preview.metrics?.totalDurationSeconds?`${Math.round(preview.metrics.totalDurationSeconds/60)} min`:'—'}</b>{t('optimization.duration')}</span><span><b>{preview.proposed?.length||0}</b>{t('optimization.assigned')}</span><span><b>{preview.unassigned?.length||0}</b>{t('optimization.unassigned')}</span></div>{preview.comparison?.available?<div className="optimization-savings"><span><b>{(preview.comparison.currentDistanceMeters/1000).toFixed(1)} km</b>{t('optimization.currentRoad')}</span><span><b>{(preview.comparison.proposedDistanceMeters/1000).toFixed(1)} km</b>{t('optimization.proposedRoad')}</span><span><b>{(preview.comparison.distanceSavingsMeters/1000).toFixed(1)} km · {Math.round(preview.comparison.durationSavingsSeconds/60)} min</b>{t('optimization.savings')}</span></div>:<p>{t('optimization.savings')}: {t('common.notAvailable')}</p>}{(preview.horizons||[]).some(item=>item.source==='default_fallback')&&<small>{t('optimization.fallbackHours')}</small>}<div className="optimization-compare"><section><h4>{t('optimization.proposed')}</h4>{eligible.map(vehicle=><div key={vehicle.id}><strong>{vehicleLabel(vehicle,ui)}</strong>{(preview.proposed||[]).filter(item=>item.vehicleId===vehicle.id).sort((a,b)=>a.sequence-b.sequence).map(item=>{const stop=day.stops.find(row=>row.id===item.stopId),oldVehicle=eligible.find(row=>row.id===stop?.vehicleId);return <small key={item.stopId}>#{item.sequence} · <span data-i18n-raw>{stop?.branchName||ui("Stop {0}", {0: item.stopId})}</span> · {oldVehicle?vehicleLabel(oldVehicle,ui):t('optimization.unassigned')} → {vehicleLabel(vehicle,ui)}</small>})}</div>)}</section><section><h4>{t('optimization.warnings')}</h4>{(preview.warnings||[]).map((warning,index)=><p key={`${warning.code}-${index}`}>{ui(warning.message)}</p>)}{(preview.unassigned||[]).map(item=><p key={item.stopId}>{ui("Stop")}{item.stopId}: {ui(item.reason)}</p>)}</section></div><label>{t('optimization.applyReason')}<textarea value={reason} onChange={event=>setReason(event.target.value)}/></label><div className="approval-modal-actions"><button onClick={()=>setOpen(false)}>{t('common.cancel')}</button><button className="primary" disabled={working||preview.unassigned?.length>0} onClick={apply}>{t('optimization.apply')}</button></div></div></div>}
  </section>
}

function AvailabilityManager({date}){
 const ui=useUi()
const{t}=useI18n(),[data,setData]=useState({vehicles:[],employees:[]}),[open,setOpen]=useState(false),[message,setMessage]=useState('');const load=useCallback(()=>request(`/api/dispatch/optimization/availability?date=${date}`).then(setData).catch(()=>setData({vehicles:[],employees:[]})),[date]);useEffect(()=>{if(open)load()},[open,load]);const update=(kind,id,field,value)=>setData(current=>({...current,[kind]:current[kind].map(item=>item[`${kind.slice(0,-1)}Id`]===id?{...item,[field]:value}:item)}));const save=async(kind,row)=>{if(!row.reason?.trim()){setMessage(t('optimization.availabilityReason'));return}const id=row[`${kind}Id`];await request(`/api/dispatch/optimization/availability/${kind}/${id}`,{method:'PUT',body:JSON.stringify({date,status:row.status,startTime:row.startTime||null,endTime:row.endTime||null,reason:row.reason})});setMessage(t('optimization.availabilitySaved'));await load()};const rows=(kind,items)=>items.map(row=>{const id=row[`${kind}Id`],name=row.vehicleCode||row.employeeName;return <div key={`${kind}-${id}`}><b data-i18n-raw>{name}</b><select aria-label={t('optimization.availabilityStatus')} value={row.status} onChange={event=>update(`${kind}s`,id,'status',event.target.value)}><option value="available">{t('optimization.available')}</option><option value="excluded">{t('optimization.excluded')}</option>{kind==='vehicle'?<option value="maintenance">{t('optimization.maintenance')}</option>:<option value="leave">{t('optimization.leave')}</option>}<option value="off_duty">{t('optimization.offDuty')}</option></select><input type="time" aria-label={t('optimization.startTime')} value={row.startTime||''} onChange={event=>update(`${kind}s`,id,'startTime',event.target.value)}/><input type="time" aria-label={t('optimization.endTime')} value={row.endTime||''} onChange={event=>update(`${kind}s`,id,'endTime',event.target.value)}/><input placeholder={t('optimization.availabilityReason')} value={row.reason||''} onChange={event=>update(`${kind}s`,id,'reason',event.target.value)}/><button type="button" onClick={()=>save(kind,row)}>{t('common.save')}</button></div>});return <details className="optimization-availability" open={open} onToggle={event=>setOpen(event.currentTarget.open)}><summary>{t('optimization.availability')}</summary>{message&&<small>{ui(message)}</small>}<h4>{t('optimization.vehicles')}</h4><div>{rows('vehicle',data.vehicles)}</div><h4>{t('optimization.crew')}</h4><div>{rows('employee',data.employees)}</div></details>}
function OptimizationRuleReview(){
 const ui=useUi()
const{t}=useI18n(),[items,setItems]=useState([]),[open,setOpen]=useState(false);const load=useCallback(()=>request('/api/dispatch/optimization/rules?status=proposed').then(data=>setItems(data.items||[])).catch(()=>setItems([])),[]);useEffect(()=>{if(open)load()},[open,load]);const decide=async(item,status)=>{const reason=prompt(t('optimization.ruleDecisionReason'));if(!reason)return;await request(`/api/dispatch/optimization/rules/${item.id}`,{method:'PATCH',body:JSON.stringify({status,reason})});await load()};return <details className="optimization-rule-review" open={open} onToggle={event=>setOpen(event.currentTarget.open)}><summary>{t('optimization.ruleSuggestions')} ({items.length})</summary>{items.map(item=><article key={item.id}><b>{item.rule_type}</b><span>{ui(item.reason)}</span>{item.rule?.supportingFeedbackCount&&<small>{t('optimization.supportingOverrides',{count:item.rule.supportingFeedbackCount})}</small>}<button onClick={()=>decide(item,'approved')}>{t('optimization.approveRule')}</button><button onClick={()=>decide(item,'rejected')}>{t('optimization.rejectRule')}</button></article>)}</details>}

function RouteHandover({day,route,vehicles,employees}){
  const ui=useUi()

  const[open,setOpen]=useState(false),[vehicleId,setVehicleId]=useState(String(route.vehicleId||'')),[driverId,setDriverId]=useState(''),[reason,setReason]=useState(''),[working,setWorking]=useState(false),[error,setError]=useState('')
  const show=()=>{setVehicleId(String(route.vehicleId));setDriverId(String(day.vehicleBoards.find(v=>v.id===route.vehicleId)?.driverId||''));setError('');setOpen(true)}
  const save=async()=>{setWorking(true);setError('');try{await request(`/api/dispatch/day/${day.dispatch_date}/route/${route.routeNumber}/handover`,{method:'POST',body:JSON.stringify({vehicleId:Number(vehicleId),driverId:Number(driverId),reason,expectedRevision:day.revision})});setOpen(false);setReason('');window.dispatchEvent(new Event('kcs-handover-saved'))}catch(e){setError(e.message)}finally{setWorking(false)}}
  return <div><button type="button" onClick={show}>{ui("调整当天车辆／司机")}</button>{open&&<div role="group" aria-label={ui("当天交接")}><p>{ui("只影响当天。旧单据归属不变，明天安排不变。")}</p><label>{ui("车辆")}<select value={vehicleId} disabled={working} onChange={e=>setVehicleId(e.target.value)}>{vehicles.filter(v=>usableVehicle(v,day.dispatch_date)).map(v=><option key={v.id} value={v.id} data-i18n-raw>{v.registrationNumber||v.vehicleCode}</option>)}</select></label><label>{ui("接手司机")}<select value={driverId} disabled={working} onChange={e=>setDriverId(e.target.value)}><option value="">{ui("选择司机")}</option>{employees.filter(e=>usableEmployee(e)&&(['driver','supervisor'].includes(String(e.role).toLowerCase())||e.additionalRoles?.includes('Driver'))).map(e=><option key={e.id} value={e.id} data-i18n-raw>{e.name}</option>)}</select></label><label>{ui("调整原因")}<input value={reason} disabled={working} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert" className="data-error">{ui(error)}</p>}<button type="button" disabled={working||!vehicleId||!driverId||!reason.trim()} onClick={save}>{working?ui("保存中…"):ui("确认当天调整")}</button><button type="button" disabled={working} onClick={()=>setOpen(false)}>{ui("取消")}</button></div>}</div>
}

function RouteAssignmentPanel({days=[],renderOperations,canHandover=false,day,routeNumber,vehicles,employees=[],onAssign,onRename,onReorder,onApprove,onWithdraw,busy,hasUnsavedChanges,canEdit}){
  const ui=useUi(),{t}=useI18n()

  const selectedRoute=day.sundayGrouped?({1:4,5:2}[routeNumber]||routeNumber):routeNumber,allRoutes=day.routeBoards||[],routes=allRoutes.filter(route=>(!day.sundayGrouped||[2,4].includes(route.routeNumber)||route.customerCount>0)&&(!selectedRoute||route.routeNumber===selectedRoute)),used=new Map(allRoutes.filter(route=>route.vehicleId).map(route=>[route.vehicleId,route.routeNumber])),editable=canEdit&&['draft','reapproval_required'].includes(day.status),approvable=canEdit&&['draft','reapproval_required','in_progress'].includes(day.status)
  return <section className="route-assignment-panel">{day.sundayGrouped&&<p>{ui("星期日两组合并收货，每周轮班。换车、换人只影响这个星期日。")}</p>}<div className="route-assignment-grid">{routes.map(route=><details key={route.routeNumber} className={`route-assignment-card ${route.approvalStatus==='approved'?'approved':''}`}><summary><span className="route-name-row"><b data-i18n-raw>{route.name}</b>{!day.sundayGrouped&&<button type="button" className="route-name-edit" disabled={!canEdit} onClick={event=>{event.preventDefault();event.stopPropagation();onRename(route.routeNumber,route.name)}}>{ui("改名")}</button>}</span><span>{route.customerCount}{ui("家")}</span><strong><span data-i18n-raw>{route.vehicleId?(route.registrationNumber||route.vehicle||ui("未设车牌")):ui("当天未分配车辆")}</span></strong><small className="route-service-date">{formatRouteDate(day.dispatch_date,ui)}</small><em className={`route-approval-status ${route.approvalStatus}`}>{route.approvalStatus==='approved'?ui("已批准"):route.approvalStatus==='reapproval_required'?ui("需要重新批准"):route.approvalStatus==='empty'?ui("当天没有客户"):ui("尚未批准")}</em></summary><div className="route-card-actions">{route.approvalStatus==='approved'&&canEdit&&<button type="button" disabled={busy||hasUnsavedChanges} onClick={()=>onWithdraw(route.routeNumber)}>{t('route.withdraw')}</button>}{route.customerCount>0&&route.approvalStatus!=='approved'&&<button type="button" className="primary" disabled={!approvable||!route.vehicleId} onClick={()=>onApprove(day.dispatch_date,route.routeNumber)}>{ui("批准这条 Route")}</button>}</div>{canHandover&&day.dispatch_date===localDate()&&day.status!=='completed'&&route.vehicleId&&<RouteHandover day={day} route={route} vehicles={vehicles} employees={employees}/>}<label>{ui("当天执行车辆")}<select value={route.vehicleId||''} disabled={!editable||route.customerCount===0} onChange={event=>onAssign(day.dispatch_date,route.routeNumber,event.target.value?Number(event.target.value):null)}><option value="">{ui("未分配")}</option>{vehicles.filter(item=>usableVehicle(item,day.dispatch_date)).map(vehicle=>{const occupied=used.get(vehicle.id);return <option key={vehicle.id} value={vehicle.id} disabled={occupied&&occupied!==route.routeNumber} data-i18n-raw>{vehicle.registrationNumber||vehicle.vehicleCode||vehicle.vehicle}{occupied&&occupied!==route.routeNumber?ui("· 已给 Route {0}", {0: occupied}):''}</option>})}</select></label>{renderOperations?.(route)}<RouteCustomerList day={day} route={route} days={days} canEdit={canEdit} onReorder={onReorder} busy={busy}/><RouteUnloadingRecords date={day.dispatch_date} routeNumber={route.routeNumber} revision={day.revision}/></details>)}</div></section>
}

function UnassignedPool({day,patchStop,assignStopsToRoute}){
  const ui=useUi()
const stops=day.extraUnassignedStops||[];return <section className="unassigned-pool"><header><strong>{ui("Route 以外的临时客户")}</strong><span>{stops.length}{ui("· Zone只用于查看地理位置")}</span></header>{stops.length===0?<p>{ui("没有 Route 以外的临时客户。")}</p>:<div className="zone-pool-list">{day.unassignedZones.map(zone=><ZonePool key={zone.zoneGroupId} day={day} zone={zone} patchStop={patchStop} assignStopsToRoute={assignStopsToRoute}/>)}</div>}</section>}

function ZonePool({day,zone,patchStop,assignStopsToRoute}){
  const ui=useUi()

  const[open,setOpen]=useState(false)
  return <section className="zone-pool"><header><div className="zone-drag"><b>{zone.zoneGroupName}</b><small>{ui("地理 Zone ·")}{zone.areaCount}{ui("Areas")}</small></div><div className="zone-actions"><RoutePicker routes={day.routeBoards||[]} onChoose={routeNumber=>assignStopsToRoute(day.dispatch_date,zone,routeNumber)}/><button className="zone-toggle" onClick={()=>setOpen(!open)}>{open?'Collapse':'Expand'} {open?'▴':'▾'}</button></div></header><div className="area-metrics"><span><b>{zone.customerCount}</b>{ui("Customer")}</span><span><b>{zone.weightedCustomerCount?`${zone.estimatedWeightKg} kg`:'—'}</b>{ui("Estimated weight")}</span><span><b>{zone.missingGpsCount}</b>{ui("Missing GPS")}</span><span><b>{zone.timeRestrictionCount}</b>{ui("Time constraints")}</span></div>{open&&<div className="area-pool-list">{zone.areas.map(group=><AreaPool key={group.areaId??'none'} day={day} group={group} routes={day.routeBoards||[]} patchStop={patchStop} assignStopsToRoute={assignStopsToRoute}/>)}</div>}</section>
}

function AreaPool({day,group,routes,patchStop,assignStopsToRoute}){
  const ui=useUi()

  return <section className="area-pool"><header><div className="area-drag"><b><span data-i18n-raw>{group.areaName}</span></b><small>{ui("地理 Area")}</small></div><RoutePicker routes={routes} onChoose={routeNumber=>assignStopsToRoute(day.dispatch_date,group,routeNumber)}/></header><div className="area-metrics"><span><b>{group.customerCount}</b>{ui("Customer")}</span><span><b>{group.weightedCustomerCount?`${group.estimatedWeightKg} kg`:'—'}</b>{ui("Estimated weight")}</span><span><b>{group.missingGpsCount}</b>{ui("Missing GPS")}</span><span><b>{group.timeRestrictionCount}</b>{ui("Time constraints")}</span></div><div className="area-stops">{group.stops.map(stop=><StopCard key={stop.id} stop={stop} patchStop={patchStop}/>)}</div></section>
}

function useOutsideClose(open,onClose){
  const rootRef=useRef(null)
  useEffect(()=>{if(!open)return undefined;const close=event=>{if(!rootRef.current?.contains(event.target))onClose()};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[open,onClose])
  return rootRef
}

function RoutePicker({routes,onChoose}){
  const ui=useUi()

  const[open,setOpen]=useState(false),[working,setWorking]=useState(false),[localError,setLocalError]=useState(''),close=useCallback(()=>setOpen(false),[]),rootRef=useOutsideClose(open,close)
  const choose=async routeNumber=>{setWorking(true);setLocalError('');try{await onChoose(routeNumber);setOpen(false)}catch(error){setLocalError(error.message)}finally{setWorking(false)}}
  return <div className="resource-picker" ref={rootRef}><button type="button" className="picker-trigger" disabled={working} onClick={()=>setOpen(value=>!value)}>{ui("未分配 Route ▾")}</button>{open&&<div className="picker-panel route-picker-panel">{localError&&<p className="route-picker-error">{ui(localError)}</p>}<div>{routes.map(route=><button type="button" key={route.routeNumber} disabled={working} onClick={()=>choose(route.routeNumber)}><strong><span data-i18n-raw>{route.name||ui("Route {0}", {0: route.routeNumber})}</span></strong><small>{route.customerCount||0}{ui("家")}<span data-i18n-raw>{route.registrationNumber?` · ${route.registrationNumber}`:''}</span></small></button>)}</div></div>}</div>
}

function RouteOperations({day,route,employees,buyers,endLocations,patchTrip,assignVehicle,canEditDispatch}){
  const ui=useUi()

  const board=day.vehicleBoards.find(item=>item.id===route.vehicleId)
  if(!board)return null
  const editable=canEditDispatch&&['draft','reapproval_required'].includes(day.status)
  const slots=board.slots.filter(slot=>slot.tripId&&slot.stops.some(stop=>stop.routeNumber===route.routeNumber))
  return <div className="route-operations">
    {editable?<div className="vehicle-crew"><DriverPicker board={board} allBoards={day.vehicleBoards} employees={employees} onChange={driverId=>assignVehicle(day.dispatch_date,board.id,{driverId})}/><AssistantPicker board={board} employees={employees} onChange={assistantIds=>assignVehicle(day.dispatch_date,board.id,{assistantIds})}/></div>:<p>{ui("司机：")}{board.driver||ui("未分配")}{ui("· Attendant：")}<span data-i18n-raw>{board.assistants.map(item=>item.name).join(', ')||ui("未分配")}</span></p>}
    {slots.length>0&&<details><summary>{ui("收货设置")}</summary>{slots.map(slot=><div key={slot.tripId}>
      {editable&&<StartLocationControl slot={slot} driverId={board.driverId} onSave={payload=>patchTrip(slot.tripId,payload)}/>}
      {editable&&<TripCommercialControl slot={slot} buyers={buyers} endLocations={endLocations} onSave={payload=>patchTrip(slot.tripId,payload)}/>}
    </div>)}</details>}
  </div>
}

function VehicleBoard({day,board,allBoards,vehicles,employees,assignVehicle,transferVehicle}){
  const ui=useUi()

  const update=(body)=>assignVehicle(day.dispatch_date,board.id,body)
  const recommended=board.preferredAreas?.filter(area=>board.areas.includes(area))||[]
  return <article id={`dispatch-${day.id}-vehicle-${board.id}`} className="vehicle-board"><header><div><strong>{vehicleLabel(board,ui)}</strong><small>{board.capacityKg?`${board.capacityKg} kg`:ui("Capacity not set")}{ui("· Base")}<span data-i18n-raw>{board.defaultBase||ui("Not set")}</span> · {board.customerCount}{ui("Stops ·")}{board.weightedStopCount?ui("{0} kg estimated", {0: board.estimatedWeightKg}):ui("weight not set")}{board.missingWeightCount?ui("· {0} missing weight", {0: board.missingWeightCount}):''}{board.overCapacity?<b className="route-warning">{ui("· Over capacity")}</b>:''}</small></div><span>{board.areas.length?board.areas.join(', '):ui("Unassigned Area")}{recommended.length?ui("· recommendation match {0}", {0: recommended.join(', ')}):''}{board.customerCount>0&&<button className="transfer-vehicle" onClick={()=>transferVehicle(day.dispatch_date,board.id,vehicles)}>{ui("Transfer entire vehicle plan")}</button>}</span></header><div className="vehicle-crew"><DriverPicker board={board} allBoards={allBoards} employees={employees} onChange={driverId=>update({driverId})}/><AssistantPicker board={board} employees={employees} onChange={assistantIds=>update({assistantIds})}/></div></article>
}

function TripCommercialControl({slot,buyers,endLocations,onSave}){
  const ui=useUi()

  const[buyerId,setBuyerId]=useState(slot.buyerReferenceId?String(slot.buyerReferenceId):''),[endId,setEndId]=useState(slot.endLocationReferenceId?String(slot.endLocationReferenceId):''),[reason,setReason]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const ordered=useMemo(()=>[...endLocations].sort((a,b)=>Number(b.buyerReferenceId===Number(buyerId))-Number(a.buyerReferenceId===Number(buyerId))||a.locationName.localeCompare(b.locationName)),[endLocations,buyerId])
  const save=async()=>{if(!reason.trim()){setError(ui("Change Reason is required"));return}setSaving(true);setError('');try{await onSave({buyerPayer:buyerId?{referenceId:Number(buyerId)}:null,primaryEndLocation:endId?{referenceId:Number(endId)}:null,reason:reason.trim()});setReason('')}catch(e){setError(e.message)}finally{setSaving(false)}}
  return <div className="trip-commercial"><label>{ui("Buyer / Payer")}<select aria-label={ui("Trip {0} Buyer / Payer", {0: slot.tripNumber})} value={buyerId} onChange={event=>setBuyerId(event.target.value)}><option value="">{ui("Not selected")}</option>{buyers.map(item=><option key={item.id} value={item.id}>{item.buyerCode} — {item.buyerName}</option>)}</select></label><label>{ui("Primary End Location")}<select aria-label={ui("Trip {0} Primary End Location", {0: slot.tripNumber})} value={endId} onChange={event=>setEndId(event.target.value)}><option value="">{ui("Not selected")}</option>{ordered.map(item=><option key={item.id} value={item.id} data-i18n-raw>{item.buyerReferenceId===Number(buyerId)?ui("Recommended ·"):''}{item.parentName?`${item.parentName} — `:''}{item.locationName}{ui("· GPS Set")}</option>)}</select></label>{endId&&<small><span data-i18n-raw>{ordered.find(item=>String(item.id)===endId)?.address||ui("Address not set")}</span></small>}<label>{ui("Change Reason")}<input value={reason} onChange={event=>setReason(event.target.value)}/></label>{error&&<small className="data-error">{ui(error)}</small>}<button type="button" disabled={saving} onClick={save}>{saving?ui("Saving…"):ui("Save Buyer & End Location")}</button></div>
}

function StartLocationControl({slot,driverId,onSave}){
  const ui=useUi()

  const[open,setOpen]=useState(false),[options,setOptions]=useState(null),[type,setType]=useState(slot.startLocationType||'factory'),[saved,setSaved]=useState(''),[custom,setCustom]=useState({name:'',address:'',latitude:'',longitude:'',gpsSource:''}),[reason,setReason]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false)
  const show=async()=>{setOpen(true);setError('');try{setOptions(await request(`/api/dispatch/start-location-options${driverId?`?driverId=${driverId}`:''}`))}catch(reason){setError(reason.message)}}
  const submit=async()=>{if(!reason.trim()){setError(ui("Change Reason is required"));return}let startLocation={type};if(type==='employee_home')startLocation={type,referenceId:driverId};if(type==='saved_location'){const[referenceType,referenceId]=saved.split(':');startLocation={type,referenceType,referenceId:Number(referenceId)}}if(type==='custom')startLocation={type,...custom};setSaving(true);setError('');try{await onSave({startLocation,reason:`${reason.trim()}${custom.gpsSource?` · GPS source: ${custom.gpsSource}`:''}`});setOpen(false)}catch(reasonError){setError(reasonError.message)}finally{setSaving(false)}}
  return <div className="trip-start-location"><button type="button" className="start-location-trigger" onClick={show}><b>{ui("Start Location")}</b><span>{slot.startLocationName||ui("Factory not set")}</span></button>{open&&<div className="start-location-dialog" role="dialog" aria-modal="true" aria-label={ui("Start Location")}><div><header><h3>{ui("Start Location · Trip")}{slot.tripNumber}</h3><button type="button" onClick={()=>setOpen(false)}>×</button></header><label>{ui("Type")}<select value={type} onChange={event=>setType(event.target.value)}><option value="factory">{ui("Factory")}</option><option value="employee_home">{ui("Employee Home")}</option><option value="saved_location">{ui("Saved Location")}</option><option value="custom">{ui("Custom Location")}</option></select></label>{type==='factory'&&<p>{options?.factory?ui("Factory — {0} · GPS Set", {0: options.factory.startLocationName}):ui("Company Yard GPS is not set")}</p>}{type==='employee_home'&&<p>{options?.employeeHome?.startLocationName?ui("{0} · Home GPS Set", {0: options.employeeHome.startLocationName}):(options?.employeeHome?.message||ui("Select a Driver"))}</p>}{type==='saved_location'&&<label>{ui("Saved Location")}<select value={saved} onChange={event=>setSaved(event.target.value)}><option value="">{ui("Select a GPS-enabled location")}</option>{(options?.savedLocations||[]).map(item=><option key={`${item.startLocationReferenceType}:${item.startLocationReferenceId}`} value={`${item.startLocationReferenceType}:${item.startLocationReferenceId}`}>{item.startLocationName}</option>)}</select></label>}{type==='custom'&&<><label>{ui("Name")}<input value={custom.name} onChange={event=>setCustom(value=>({...value,name:event.target.value}))}/></label><label>{ui("Address")}<textarea value={custom.address} onChange={event=>setCustom(value=>({...value,address:event.target.value}))}/></label><SharedGpsInput resetKey={`dispatch-start:${slot.id||slot.dispatchId||slot.tripNumber}`} latitude={custom.latitude} longitude={custom.longitude} address={custom.address} gpsSource={custom.gpsSource} onChange={change=>setCustom(value=>({...value,latitude:change.latitude,longitude:change.longitude,address:change.address??value.address,gpsSource:change.gpsSource}))}/></>}<label>{ui("Change Reason")}<input value={reason} onChange={event=>setReason(event.target.value)}/></label>{error&&<p className="data-error">{ui(error)}</p>}<FormActionBar><button type="button" onClick={()=>setOpen(false)}>{ui("Cancel")}</button><button type="button" className="primary" disabled={saving} onClick={submit}>{saving?ui("Saving…"):ui("Save Start Location")}</button></FormActionBar></div></div>}</div>
}

function DriverPicker({board,allBoards,employees,onChange}){
  const ui=useUi()

  const[open,setOpen]=useState(false),[search,setSearch]=useState('')
  const close=useCallback(()=>setOpen(false),[]),rootRef=useOutsideClose(open,close)
  const drivers=useMemo(()=>employees.filter(item=>(['driver','supervisor'].includes(String(item.role||'').toLowerCase())||item.additionalRoles?.includes('Driver'))&&`${item.name} ${item.employeeCode||''}`.toLowerCase().includes(search.toLowerCase())),[employees,search])
  return <div className="resource-picker" ref={rootRef}><button className={`picker-trigger ${!board.driverId?'missing':''}`} onClick={()=>setOpen(!open)}>{board.driver||ui("Unassigned driver")} ▾</button>{open&&<div className="picker-panel employee-picker-panel"><input autoFocus placeholder={ui("Search driver name or employee number")} value={search} onChange={event=>setSearch(event.target.value)}/>{board.driverId&&<button className="release-assignment" onClick={()=>{onChange(null);setOpen(false)}}>{ui("Release current driver assignment")}</button>}<div>{drivers.map(item=>{const other=allBoards.find(vehicle=>vehicle.id!==board.id&&vehicle.driverId===item.id),disabled=!usableEmployee(item)||Boolean(other);return <button key={item.id} disabled={disabled} onClick={()=>{onChange(item.id);setOpen(false)}}><strong><span data-i18n-raw>{item.name}</span> · {item.employeeCode||ui("No employee code")}</strong><small>{ui(employmentStatus[item.employmentStatus]||item.employmentStatus)}{ui("· Base")}<span data-i18n-raw>{item.defaultBase||ui("Not set")}</span>{ui("· Area")}<span data-i18n-raw>{item.defaultArea||ui("Not set")}</span></small><small>{other?ui("Assigned today: {0}", {0: vehicleLabel(other,ui)}):ui("Not assigned to another vehicle today")}{!usableEmployee(item)?ui("· Unavailable"):''}</small></button>})}{drivers.length===0&&<p>{ui("Employee Master No Driver")}</p>}</div></div>}</div>
}

function AssistantPicker({board,employees,onChange}){
  const ui=useUi()

  const[open,setOpen]=useState(false),[search,setSearch]=useState(''),[selected,setSelected]=useState(board.assistantIds)
  const close=useCallback(()=>setOpen(false),[]),rootRef=useOutsideClose(open,close)
  useEffect(()=>{setSelected(board.assistantIds)},[board.assistantIds])
  const crew=useMemo(()=>employees.filter(item=>(['assistant','crew','attendant / crew'].includes(String(item.role||'').toLowerCase())||item.additionalRoles?.includes('Attendant / Crew'))&&`${item.name} ${item.employeeCode||''}`.toLowerCase().includes(search.toLowerCase())),[employees,search])
  const toggle=(id)=>{const next=selected.includes(id)?selected.filter(item=>item!==id):selected.length<MAX_ASSIGNED_CREW?[...selected,id]:selected;if(next===selected)return;setSelected(next);onChange(next)}
  return <div className="resource-picker" ref={rootRef}><button className={`picker-trigger ${!selected.length?'missing':''}`} onClick={()=>setOpen(!open)}><span data-i18n-raw>{board.assistants.length?board.assistants.map(item=>item.name).join(', '):ui("Unassigned crew")}</span> · {selected.length}/{MAX_ASSIGNED_CREW} ▾</button>{open&&<div className="picker-panel employee-picker-panel"><input autoFocus placeholder={ui("Search crew name or employee number")} value={search} onChange={event=>setSearch(event.target.value)}/><div>{crew.map(item=>{const checked=selected.includes(item.id),limitReached=!checked&&selected.length>=MAX_ASSIGNED_CREW,disabled=!usableEmployee(item)||limitReached;return <button key={item.id} disabled={disabled} onClick={()=>toggle(item.id)}><strong>{checked?'☑':'☐'} <span data-i18n-raw>{item.name}</span> · {item.employeeCode||ui("No employee code")}</strong><small>{ui(item.role)} · {ui(employmentStatus[item.employmentStatus]||item.employmentStatus)}{ui("· Base")}<span data-i18n-raw>{item.defaultBase||ui("Not set")}</span>{ui("· Area")}<span data-i18n-raw>{item.defaultArea||ui("Not set")}</span>{!usableEmployee(item)?ui("· Unavailable"):limitReached?ui("· Maximum 2 crew selected"):''}</small></button>})}{crew.length===0&&<p>{ui("Employee Master No Assistant/Crew")}</p>}</div></div>}</div>
}

function StopCard({stop,patchStop,day,board,targetBoards=[],moveStop,canEditDispatch=false}){
  const ui=useUi()

  const gps=Number.isFinite(stop.latitude)&&Number.isFinite(stop.longitude)&&stop.latitude!==0&&stop.longitude!==0,[target,setTarget]=useState('')
  const targets=targetBoards.filter(item=>item.id!==board?.id)
  return <div className={`route-stop ${stop.sequenceLocked?'sequence-locked':''}`} draggable={!stop.sequenceLocked&&day?.status==='draft'&&canEditDispatch} onDragStart={event=>event.dataTransfer.setData('text/stop-id',String(stop.id))}><i>{stop.stopSequence}</i><span><b>{formatBranchId(stop.branchId)} — <span data-i18n-raw>{stop.branchName||ui("Unnamed branch")}</span></b><small>{formatCustomerId(stop.customerId)} — <span data-i18n-raw>{stop.customerName||ui("Unmatched customer")}</span> · <span data-i18n-raw>{stop.area||ui("Unassigned area")}</span> · {stop.estimatedWeightKg!=null?`${stop.estimatedWeightKg} kg`:ui("Weight not set")} · {gps?ui("GPS✓"):ui("GPS missing")}</small>{stop.timeRestriction&&<small className="route-warning">{ui("Time restriction:")}{stop.timeRestriction}</small>}</span>{canEditDispatch&&board&&<div className="stop-actions"><select aria-label={ui("Move {0} to another vehicle", {0: stop.branchName})} value={target} disabled={day.status!=='draft'} onChange={event=>setTarget(event.target.value)}><option value="">{ui("移到其他车辆")}</option>{targets.map(item=><option key={item.id} value={item.id} data-i18n-raw>{item.vehicle} · {item.registrationNumber||ui("No plate")}</option>)}</select><button type="button" disabled={day.status!=='draft'||!target} title={day.status!=='draft'?ui("Withdraw Approval first"):ui("Move this route stop")} onClick={()=>{moveStop(day,stop,Number(target));setTarget('')}}>{ui("Move")}</button></div>}<button title={ui("Lock sequence")} onClick={()=>patchStop(stop.id,{sequenceLocked:!stop.sequenceLocked})}>{stop.sequenceLocked?'🔒':'○'}</button></div>
}

export {WeekDayTabs,RouteWeekTabs,RouteAssignmentPanel,DriverPicker,AssistantPicker,StopCard}
