import { useCallback, useEffect, useMemo, useState } from 'react'
import './Planner.css'
import {addCalendarDays,kuchingDate,shortcutForDate} from '../shared/kuchingTime.js'
import {useI18n} from './i18n.jsx'
import {apiRequest as request} from './apiClient.js'
import {formatBranchId,formatCustomerId} from '../shared/typedIds.js'
import {MAX_ASSIGNED_CREW} from '../shared/dispatchRules.js'
import SharedGpsInput from './SharedGpsInput.jsx'
import FormActionBar from './FormActionBar.jsx'
import RouteOptimizationMap from './RouteOptimizationMap.jsx'

const localDate=kuchingDate
const addDays=addCalendarDays
const labels={draft:'Draft',pending_approval:'Pending Approval',approved:'Approved',published:'Published',in_progress:'In Progress',completed:'Completed',reapproval_required:'Reapproval Required'}
const vehicleStatus={available:'Available',active:'Active',maintenance:'Maintenance',inactive:'Inactive',sold:'Sold'}
const employmentStatus={active:'Active',on_leave:'On Leave',inactive:'Inactive'}
const usableVehicle=(vehicle,date)=>['available','active'].includes(vehicle.status)&&(!vehicle.isTemporary||vehicle.temporaryDate===date)
const usableEmployee=(employee)=>Boolean(employee.isActive)&&employee.employmentStatus==='active'
const vehicleLabel=(item)=>`${item.vehicleCode||item.vehicle} — ${item.registrationNumber||'Registration plate not set'} — ${vehicleStatus[item.status]||item.status}`
const defaultVehiclePoolLabel=(vehicleIds=[],vehicles,t)=>vehicleIds.length?vehicleIds.map(vehicleId=>{const vehicle=vehicles.find(item=>Number(item.id)===Number(vehicleId));return vehicle?`${vehicle.vehicleCode||vehicle.vehicle} — ${vehicle.registrationNumber||t('common.notSet')}`:t('defaultVehicle.unavailable')}).join(' · '):t('defaultVehicle.noneAssigned')

export default function WeeklyDispatchPage({onOpenSpecial,currentUser}){
  const{t}=useI18n()
  const[selectedDate,setSelectedDate]=useState(localDate()),[viewMode,setViewMode]=useState('single'),[data,setData]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  const[selectedStops,setSelectedStops]=useState([]),[pendingAdjustments,setPendingAdjustments]=useState([])
  const canEditDispatch=['owner_admin','operations_admin','supervisor'].includes(currentUser.systemRole)||currentUser.permissions?.includes('schedule_manage')
  const canManageVehicles=['owner_admin','operations_admin'].includes(currentUser.systemRole)||currentUser.permissions?.includes('vehicle_manage')
  const load=useCallback(async()=>{setError('');try{const result=await request(viewMode==='week'?`/api/dispatch/week?startDate=${selectedDate}`:`/api/dispatch/day/${selectedDate}`);setData(viewMode==='week'?result:{days:[result],vehicles:result.vehicles,employees:result.employees,locations:result.locations,areas:result.areas,buyers:result.buyers,endLocations:result.endLocations})}catch(e){setData({days:[],vehicles:[],employees:[],locations:[],areas:[],buyers:[],endLocations:[]});if(!(viewMode==='single'&&e.status===404&&e.code==='NOT_FOUND'))setError(e.message)}},[selectedDate,viewMode])
  useEffect(()=>{load()},[load])
  const chooseSingle=(offset)=>{setSelectedDate(addDays(localDate(),offset));setViewMode('single')}
  const describeWeekError=error=>{const details=Array.isArray(error.details)?error.details:[];if(!details.length)return error.message;const lines=details.slice(0,8).map(item=>{const blockers=(item.blockers||[]).slice(0,2).map(blocker=>blocker.message||blocker.code).filter(Boolean).join('；');return `${item.date||''}${blockers?`：${blockers}`:item.stopId?`：Stop ${item.stopId} ${item.reason||''}`:''}`}).filter(Boolean);return `${error.message}${lines.length?`\n${lines.join('\n')}`:''}`}
  const autoArrangeWeek=async()=>{setBusy(true);setMessage('');setError('');try{const result=await request('/api/dispatch/optimization/week/auto-apply',{method:'POST',body:JSON.stringify({startDate:selectedDate})});setMessage(`未来7天已自动安排：${result.totals?.assigned||0} 个站点已分车并按道路顺序排列。`);await load();return result}catch(e){setError(describeWeekError(e));throw e}finally{setBusy(false)}}
  const generate=async()=>{setBusy(true);setMessage('');setError('');try{const result=await request(viewMode==='week'?'/api/dispatch/generate-week':'/api/dispatch/generate-day',{method:'POST',body:JSON.stringify({startDate:selectedDate,generatedBy:currentUser.name})});if(viewMode==='week'){const arranged=await request('/api/dispatch/optimization/week/auto-apply',{method:'POST',body:JSON.stringify({startDate:selectedDate})});setMessage(`未来7天草稿及路线已完成：${arranged.totals?.assigned||0} 个站点已自动分车和排序。`)}else setMessage('Selected-date draft updated.');await load()}catch(e){setError(describeWeekError(e))}finally{setBusy(false)}}
  const act=async(date,action,reason='')=>{setBusy(true);setMessage('');try{await request(`/api/dispatch/day/${date}/${action}`,{method:'POST',body:JSON.stringify({[action==='approve'?'approvedBy':'reopenedBy']:currentUser.name,reason})});setMessage(`${date} ${action==='approve'?'approved':'approval withdrawn'}.`);await load()}catch(e){setError(e.message);await load();throw e}finally{setBusy(false)}}
  const patchStop=async(id,body)=>{try{await request(`/api/dispatch/stops/${id}`,{method:'PATCH',body:JSON.stringify({...body,changedBy:currentUser.name})});await load()}catch(e){setError(e.message)}}
  const patchTrip=async(id,body)=>{try{await request(`/api/dispatch/trips/${id}`,{method:'PATCH',body:JSON.stringify(body)});setMessage('Start Location updated.');await load()}catch(e){setError(e.message);throw e}}
  const assignArea=async(date,group,vehicleId,tripNumber=1)=>{try{await request(`/api/dispatch/day/${date}/assign-area`,{method:'POST',body:JSON.stringify({areaId:group.areaId??`zone:${group.zoneGroupId}`,stopIds:group.stops.map(stop=>stop.id),vehicleId,tripNumber,changedBy:currentUser.name})});setMessage(`${group.zoneGroupName||group.areaName}  of  ${group.customerCount} customers assigned.`);await load()}catch(e){setError(e.message)}}
  const handleDrop=async(event,body)=>{event.preventDefault();const areaData=event.dataTransfer.getData('text/area-stops');if(areaData){if(body.unassigned)return;const group=JSON.parse(areaData);return assignArea(body.date,group,body.vehicleId,body.tripNumber)}const id=event.dataTransfer.getData('text/stop-id');if(id)await patchStop(id,body)}
  const assignVehicle=async(date,vehicleId,body)=>{try{await request(`/api/dispatch/day/${date}/vehicle/${vehicleId}`,{method:'PATCH',body:JSON.stringify({...body,changedBy:currentUser.name})});await load()}catch(e){setError(e.message)}}
  const transferVehicle=async(date,sourceVehicleId,vehicles)=>{const available=vehicles.filter(item=>item.id!==sourceVehicleId&&usableVehicle(item,date));const answer=prompt(`Enter target vehicle number or plate: \n${available.map(item=>vehicleLabel(item)).join('\n')}`,'QAV3468');if(!answer)return;const normalized=answer.replace(/[\s-]/g,'').toLowerCase(),target=available.find(item=>[item.vehicleCode,item.registrationNumber,String(item.id)].some(itemValue=>String(itemValue||'').replace(/[\s-]/g,'').toLowerCase()===normalized));if(!target){setError('No available target vehicle');return}const setSourceMaintenance=confirm('After route transfer, Set the original vehicle to  Maintenance？'),reason=prompt('Enter the transfer reason: ','Vehicle breakdown／Replace vehicle')||'Vehicle transfer';try{await request(`/api/dispatch/day/${date}/vehicle/${sourceVehicleId}/transfer`,{method:'POST',body:JSON.stringify({targetVehicleId:target.id,transferDriver:true,setSourceMaintenance,reason,changedBy:currentUser.name})});setMessage(`Trip, Customer routes and driver transferred to  ${vehicleLabel(target)}.`);await load()}catch(e){setError(e.message)}}
  const addTemporaryVehicle=async(date)=>{const vehicleCode=prompt('Temporary vehicle number: ',`Temporary Lorry (${date})`);if(!vehicleCode)return;try{await request('/api/vehicles/temporary',{method:'POST',body:JSON.stringify({date,vehicleCode})});setMessage(`${vehicleCode} added for ${date}.`);await load()}catch(e){setError(e.message)}}
  const addPermanentVehicle=async(date)=>{const vehicleCode=prompt('Permanent vehicle number: ');if(!vehicleCode)return;const registrationNumber=prompt('Registration plate (must be unique): ');if(!registrationNumber)return;const capacity=prompt('Capacity (kg, optional): ','');if(capacity!==''&&(!Number.isFinite(Number(capacity))||Number(capacity)<0)){setError('Capacity must be a non-negative number.');return}try{await request('/api/vehicles',{method:'POST',body:JSON.stringify({dispatchDate:date,vehicleCode,registrationNumber,capacityKg:capacity===''?null:Number(capacity)})});setMessage(`${vehicleCode} added permanently and selected for ${date}.`);await load()}catch(e){setError(e.message)}}
  const moveStop=async(day,stop,targetVehicleId)=>{setError('');try{await request(`/api/dispatch/stops/${stop.id}/move-vehicle`,{method:'POST',body:JSON.stringify({targetVehicleId,expectedRevision:day.revision,reason:'Supervisor moved one route stop'})});setMessage(`${stop.branchName||`Stop ${stop.id}`} moved to another vehicle.`);await load()}catch(e){setError(e.message);await load()}}
  const saveDraftAdjustments=async(reason)=>{setBusy(true);setError('');try{const result=await request('/api/dispatch/draft-adjustments',{method:'POST',body:JSON.stringify({adjustments:pendingAdjustments,reason})});setMessage(`${result.updated} draft Stop changes saved.`);setPendingAdjustments([]);setSelectedStops([]);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <div className="page planner-page"><div className="planner-title planner-actions"><button onClick={onOpenSpecial}>{t('planner.special')}</button></div>
    <div className="planner-toolbar"><div><button className={viewMode==='single'&&shortcutForDate(selectedDate)==='today'?'active':''} onClick={()=>chooseSingle(0)}>{t('planner.today')}</button><button className={viewMode==='single'&&shortcutForDate(selectedDate)==='tomorrow'?'active':''} onClick={()=>chooseSingle(1)}>{t('planner.tomorrow')}</button><button className={viewMode==='single'&&shortcutForDate(selectedDate)==='day_after_tomorrow'?'active':''} onClick={()=>chooseSingle(2)}>{t('planner.dayAfter')}</button><button className={viewMode==='week'?'active':''} onClick={()=>{setSelectedDate(localDate());setViewMode('week')}}>{t('planner.week')}</button></div><label>{viewMode==='week'?'7-day start date':t('planner.otherDate')} <input aria-label={viewMode==='week'?'7-day start date':t('planner.otherDate')} type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}/></label><button className="primary" disabled={busy} onClick={generate}>{busy?t('common.processing'):t(viewMode==='week'?'planner.updateWeek':'planner.updateDay')}</button></div>
    {message&&<div className="planner-message">✓ {message}</div>}{error&&<div className="data-error">{error}</div>}
    {viewMode==='week'&&data?.days?.length===7&&<WeekOptimizationPanel days={data.days} busy={busy||pendingAdjustments.length>0} onArrange={autoArrangeWeek}/>}
    {viewMode==='week'&&data?.days?.length>0&&<DraftAdjustmentPanel data={data} selectedStops={selectedStops} setSelectedStops={setSelectedStops} pending={pendingAdjustments} setPending={setPendingAdjustments} busy={busy} onSave={saveDraftAdjustments}/>}
    {!data?<div className="data-loading">{t('planner.loading')}</div>:<div className={viewMode==='week'?'week-board':'single-day-board'}>{data.days.length===0?<div className="empty-week"><h2>{t('planner.empty')}</h2><p>{t('planner.emptyHelp')}</p></div>:data.days.map(day=><DayColumn key={day.id} day={day} vehicles={data.vehicles||[]} employees={data.employees||[]} buyers={data.buyers||[]} endLocations={data.endLocations||[]} busy={busy} act={act} hasUnsavedChanges={pendingAdjustments.length>0} patchStop={patchStop} patchTrip={patchTrip} handleDrop={handleDrop} assignArea={assignArea} assignVehicle={assignVehicle} transferVehicle={transferVehicle} addTemporaryVehicle={addTemporaryVehicle} addPermanentVehicle={addPermanentVehicle} moveStop={moveStop} canEditDispatch={canEditDispatch} canManageVehicles={canManageVehicles}/>)}</div>}
  </div>
}

function WeekOptimizationPanel({days,busy,onArrange}){
  const{t}=useI18n(),allDraft=days.every(day=>day.status==='draft')
  return <section className="week-optimization"><div><h2>{t('optimization.weekTitle')}</h2><p>{t('optimization.weekHelp')}</p></div><button className="primary" disabled={busy||!allDraft} onClick={()=>onArrange().catch(()=>{})}>{busy?t('optimization.weekWorking'):t('optimization.weekAction')}</button>{!allDraft&&<p className="data-error">{t('optimization.weekDraftRequired')}</p>}</section>
}

function DraftAdjustmentPanel({data,selectedStops,setSelectedStops,pending,setPending,busy,onSave}){
  const[date,setDate]=useState(''),[dateMode,setDateMode]=useState('occurrence'),[vehicleId,setVehicleId]=useState(''),[tripNumber,setTripNumber]=useState('1'),[unassigned,setUnassigned]=useState(false),[reason,setReason]=useState(''),[area,setArea]=useState('')
  const stops=useMemo(()=>data.days.flatMap(day=>day.stops.map(stop=>({...stop,serviceDate:day.dispatch_date,dayStatus:day.status}))),[data])
  const editable=stops.filter(stop=>stop.dayStatus==='draft'&&stop.status!=='cancelled'),areas=[...new Set(editable.map(stop=>stop.area||'Unassigned area'))].sort()
  const toggle=id=>setSelectedStops(selectedStops.includes(id)?selectedStops.filter(item=>item!==id):[...selectedStops,id])
  const selectArea=value=>{setArea(value);setSelectedStops(editable.filter(stop=>(stop.area||'Unassigned area')===value).map(stop=>stop.id))}
  const stage=()=>{const picked=editable.filter(stop=>selectedStops.includes(stop.id));if(!picked.length)return
    setPending(previous=>{const byId=new Map(previous.map(item=>[item.stopId,item]));for(const stop of picked)byId.set(stop.id,{...(byId.get(stop.id)||{}),stopId:stop.id,serviceDate:date||stop.serviceDate,dateMode,vehicleId:unassigned?null:Number(vehicleId)||null,tripNumber:unassigned?0:Number(tripNumber),unassigned});return[...byId.values()]})
  }
  const move=(index,delta)=>{const next=[...pending],target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setPending(next.map((item,position)=>({...item,stopSequence:position+1})))}
  const activeVehicles=(data.vehicles||[]).filter(vehicle=>['available','active'].includes(vehicle.status))
  return <details className="draft-adjustment-panel"><summary><strong>需要时才打开：人工调整车辆、日期或顺序</strong><small>{pending.length?` · ${pending.length} 项未保存`:' · 系统自动安排后，如有不满意才使用'}</small></summary><div className="draft-adjustment-content"><header><div><strong>Supervisor Draft Adjustments</strong><small>{selectedStops.length} Stops selected · {pending.length} unsaved changes</small></div><button disabled={busy||!pending.length||!reason.trim()} onClick={()=>onSave(reason)}>Save all changes</button></header>
    <div className="draft-adjustment-controls"><label>Area<select value={area} onChange={event=>selectArea(event.target.value)}><option value="">Select an Area</option>{areas.map(item=><option key={item}>{item}</option>)}</select></label><label>Service date<input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label>Date change<select value={dateMode} onChange={event=>setDateMode(event.target.value)}><option value="occurrence">This occurrence only</option><option value="recurring">Change recurring schedule</option></select></label><label>Vehicle<select disabled={unassigned} value={vehicleId} onChange={event=>setVehicleId(event.target.value)}><option value="">Select Active vehicle</option>{activeVehicles.map(item=><option key={item.id} value={item.id}>{vehicleLabel(item)}</option>)}</select></label><label>Trip<select disabled={unassigned} value={tripNumber} onChange={event=>setTripNumber(event.target.value)}>{[1,2,3].map(item=><option key={item}>{item}</option>)}</select></label><label className="draft-unassigned"><input type="checkbox" checked={unassigned} onChange={event=>setUnassigned(event.target.checked)}/> Move to Unassigned</label><button type="button" onClick={stage}>Stage selected Stops</button></div>
    <div className="draft-stop-selector">{editable.map(stop=><label key={stop.id}><input type="checkbox" checked={selectedStops.includes(stop.id)} onChange={()=>toggle(stop.id)}/><span>{stop.serviceDate} · {stop.customerName} / {stop.branchName} · {stop.area||'Unassigned area'} · {stop.estimatedWeightKg==null?'Weight not set':`${stop.estimatedWeightKg} kg`}</span></label>)}</div>
    {pending.length>0&&<div className="pending-adjustments">{pending.map((item,index)=>{const stop=stops.find(row=>row.id===item.stopId);return <div key={item.stopId}><span>{stop?.branchName||item.stopId} → {item.serviceDate} · {item.unassigned?'Unassigned':`Vehicle ${item.vehicleId||'not set'} / Trip ${item.tripNumber}`}</span><button type="button" onClick={()=>move(index,-1)}>Move Up</button><button type="button" onClick={()=>move(index,1)}>Move Down</button><button type="button" onClick={()=>setPending(pending.filter(row=>row.stopId!==item.stopId))}>Remove</button></div>})}</div>}
    <label className="draft-reason">Reason<textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="Reason is required for Audit"/></label>
  </div></details>
}

function DayColumn({day,vehicles,employees,buyers,endLocations,busy,act,hasUnsavedChanges,patchStop,patchTrip,handleDrop,assignArea,assignVehicle,transferVehicle,addTemporaryVehicle,addPermanentVehicle,moveStop,canEditDispatch,canManageVehicles}){
  const{language}=useI18n()
  const[selectedVehicleId,setSelectedVehicleId]=useState(day.vehicleBoards[0]?.id??null)
  useEffect(()=>{if(!day.vehicleBoards.some(board=>board.id===selectedVehicleId))setSelectedVehicleId(day.vehicleBoards[0]?.id??null)},[day.dispatch_date,day.vehicleBoards,selectedVehicleId])
  const selectedBoard=day.vehicleBoards.find(board=>board.id===selectedVehicleId)||day.vehicleBoards[0]
  const date=new Date(`${day.dispatch_date}T00:00:00Z`),title=date.toLocaleDateString(language==='zh'?'zh-MY':language==='ms'?'ms-MY':'en-MY',{timeZone:'UTC',month:'numeric',day:'numeric',weekday:'short'})
  const summary=day.previewSummary||{stopCount:day.stops.length,estimatedWeightKg:0,weightedStopCount:0,missingWeightCount:day.stops.length,missingGpsCount:0,timeRestrictionCount:0,unassignedCount:day.unassignedStops.length,warningCount:day.warningCount}
  return <section className={`day-column vehicle-day ${day.status}`}><header><div><small>{day.dispatch_date}</small><h2>{title}</h2></div><span>{labels[day.status]||day.status}</span></header><div className="day-metrics preview-metrics"><span><b>{summary.stopCount+day.specialRequests.length}</b> Stops</span><span><b>{summary.weightedStopCount?`${summary.estimatedWeightKg} kg`:'—'}</b> Estimated</span><span><b>{summary.unassignedCount}</b> Unassigned</span><span><b>{summary.missingWeightCount}</b> Weight missing</span><span><b>{summary.missingGpsCount}</b> GPS missing</span><span><b>{summary.warningCount}</b> Warnings</span><span><b>v{day.revision}</b> Revision</span></div>
    <DayApprovalControls day={day} busy={busy} hasUnsavedChanges={hasUnsavedChanges} act={act}/>
    <UnassignedPool day={day} vehicles={vehicles} patchStop={patchStop} handleDrop={handleDrop} assignArea={assignArea}/>
    {canManageVehicles&&canEditDispatch&&<div className="vehicle-create-actions"><button disabled={day.status!=='draft'} title={day.status!=='draft'?'Withdraw Approval first':''} onClick={()=>addPermanentVehicle(day.dispatch_date)}>＋ Add permanent vehicle</button><button disabled={day.status!=='draft'} title={day.status!=='draft'?'Withdraw Approval first':''} onClick={()=>addTemporaryVehicle(day.dispatch_date)}>＋ Add temporary vehicle for this date</button></div>}
    <VehicleTabs boards={day.vehicleBoards} selectedVehicleId={selectedBoard?.id} onSelect={setSelectedVehicleId}/>
    <div className="vehicle-board-list">{selectedBoard&&<VehicleBoard key={selectedBoard.id} day={day} board={selectedBoard} allBoards={day.vehicleBoards} vehicles={vehicles} employees={employees} buyers={buyers} endLocations={endLocations} patchStop={patchStop} patchTrip={patchTrip} handleDrop={handleDrop} assignVehicle={assignVehicle} transferVehicle={transferVehicle} moveStop={moveStop} canEditDispatch={canEditDispatch}/>}</div>
    {day.specialRequests.filter(item=>item.requestType==='potential_new').map(item=><div className={`special-route ${item.promisedToCustomer?'promised':''}`} key={item.id}><b>{item.promisedToCustomer?'Customer promise · ':''}{item.customerName}</b><small>Potential new customer · Trip {item.tripNumber||'—'}</small>{(!item.customerId||!item.branchId||item.occPrice==null||!item.paymentType)&&<span>Warning</span>}</div>)}
  </section>
}

function VehicleTabs({boards,selectedVehicleId,onSelect}){
  if(!boards.length)return <p className="vehicle-tabs-empty">No vehicles available for this date.</p>
  return <nav className="vehicle-tabs" role="tablist" aria-label="Vehicles available for this date">{boards.map(board=><button type="button" role="tab" aria-selected={board.id===selectedVehicleId} className={board.id===selectedVehicleId?'active':''} key={board.id} onClick={()=>onSelect(board.id)}>{board.vehicle} · {board.registrationNumber||'No plate'} <small>{board.customerCount} stops</small></button>)}</nav>
}

function OptimizationControls({day,vehicles,disabled}){
  const{t}=useI18n(),[preview,setPreview]=useState(null),[open,setOpen]=useState(false),[working,setWorking]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[excluded,setExcluded]=useState([])
  const eligible=vehicles.filter(vehicle=>usableVehicle(vehicle,day.dispatch_date))
  const create=useCallback(async(mode='day',tripId=null)=>{setWorking(true);setError('');try{const result=await request('/api/dispatch/optimization/preview',{method:'POST',body:JSON.stringify({date:day.dispatch_date,mode,tripId,excludedVehicleIds:excluded})});setPreview(result);setOpen(true)}catch(e){setError(e.message)}finally{setWorking(false)}},[day.dispatch_date,excluded])
  useEffect(()=>{const handler=event=>{if(event.detail?.date===day.dispatch_date)create('trip',event.detail.tripId)};window.addEventListener('kcs-optimize-trip',handler);return()=>window.removeEventListener('kcs-optimize-trip',handler)},[create,day.dispatch_date])
  const apply=async()=>{if(!reason.trim()){setError(t('optimization.reasonRequired'));return}setWorking(true);try{await request(`/api/dispatch/optimization/${preview.runId}/apply`,{method:'POST',body:JSON.stringify({reason,expectedRevision:day.revision})});location.reload()}catch(e){setError(e.message);setWorking(false)}}
  return <section className="optimization-actions"><div><button className="primary" disabled={disabled||working||day.status!=='draft'} onClick={()=>create()}>{working?t('optimization.working'):t('optimization.dayAction')}</button><small>{t('optimization.roadLabel')}</small></div><details><summary>{t('optimization.vehicleSelection')}</summary>{eligible.map(vehicle=><label key={vehicle.id}><input type="checkbox" checked={!excluded.includes(vehicle.id)} onChange={()=>setExcluded(value=>value.includes(vehicle.id)?value.filter(id=>id!==vehicle.id):[...value,vehicle.id])}/>{vehicleLabel(vehicle)}</label>)}</details><AvailabilityManager date={day.dispatch_date}/><OptimizationRuleReview/>{error&&<p className="data-error">{error}</p>}
    {open&&preview&&<div className="optimization-modal" role="dialog" aria-modal="true" aria-label={t('optimization.previewTitle')}><div><header><div><h3>{t('optimization.previewTitle')}</h3><small>{preview.provider}{preview.cached?` · ${t('optimization.cached')}`:''}</small></div><button onClick={()=>setOpen(false)}>×</button></header><RouteOptimizationMap routes={preview.routes||[]}/><div className="optimization-metrics"><span><b>{preview.metrics?.totalDistanceMeters?`${(preview.metrics.totalDistanceMeters/1000).toFixed(1)} km`:'—'}</b>{t('optimization.distance')}</span><span><b>{preview.metrics?.totalDurationSeconds?`${Math.round(preview.metrics.totalDurationSeconds/60)} min`:'—'}</b>{t('optimization.duration')}</span><span><b>{preview.proposed?.length||0}</b>{t('optimization.assigned')}</span><span><b>{preview.unassigned?.length||0}</b>{t('optimization.unassigned')}</span></div>{preview.comparison?.available?<div className="optimization-savings"><span><b>{(preview.comparison.currentDistanceMeters/1000).toFixed(1)} km</b>{t('optimization.currentRoad')}</span><span><b>{(preview.comparison.proposedDistanceMeters/1000).toFixed(1)} km</b>{t('optimization.proposedRoad')}</span><span><b>{(preview.comparison.distanceSavingsMeters/1000).toFixed(1)} km · {Math.round(preview.comparison.durationSavingsSeconds/60)} min</b>{t('optimization.savings')}</span></div>:<p>{t('optimization.savings')}: {t('common.notAvailable')}</p>}{(preview.horizons||[]).some(item=>item.source==='default_fallback')&&<small>{t('optimization.fallbackHours')}</small>}<div className="optimization-compare"><section><h4>{t('optimization.proposed')}</h4>{eligible.map(vehicle=><div key={vehicle.id}><strong>{vehicleLabel(vehicle)}</strong>{(preview.proposed||[]).filter(item=>item.vehicleId===vehicle.id).sort((a,b)=>a.sequence-b.sequence).map(item=>{const stop=day.stops.find(row=>row.id===item.stopId),oldVehicle=eligible.find(row=>row.id===stop?.vehicleId);return <small key={item.stopId}>#{item.sequence} · <span data-i18n-raw>{stop?.branchName||`Stop ${item.stopId}`}</span> · {oldVehicle?vehicleLabel(oldVehicle):t('optimization.unassigned')} → {vehicleLabel(vehicle)}</small>})}</div>)}</section><section><h4>{t('optimization.warnings')}</h4>{(preview.warnings||[]).map((warning,index)=><p key={`${warning.code}-${index}`}>{warning.message}</p>)}{(preview.unassigned||[]).map(item=><p key={item.stopId}>Stop {item.stopId}: {item.reason}</p>)}</section></div><label>{t('optimization.applyReason')}<textarea value={reason} onChange={event=>setReason(event.target.value)}/></label><div className="approval-modal-actions"><button onClick={()=>setOpen(false)}>{t('common.cancel')}</button><button className="primary" disabled={working||preview.unassigned?.length>0} onClick={apply}>{t('optimization.apply')}</button></div></div></div>}
  </section>
}

function AvailabilityManager({date}){const{t}=useI18n(),[data,setData]=useState({vehicles:[],employees:[]}),[open,setOpen]=useState(false),[message,setMessage]=useState('');const load=useCallback(()=>request(`/api/dispatch/optimization/availability?date=${date}`).then(setData).catch(()=>setData({vehicles:[],employees:[]})),[date]);useEffect(()=>{if(open)load()},[open,load]);const update=(kind,id,field,value)=>setData(current=>({...current,[kind]:current[kind].map(item=>item[`${kind.slice(0,-1)}Id`]===id?{...item,[field]:value}:item)}));const save=async(kind,row)=>{if(!row.reason?.trim()){setMessage(t('optimization.availabilityReason'));return}const id=row[`${kind}Id`];await request(`/api/dispatch/optimization/availability/${kind}/${id}`,{method:'PUT',body:JSON.stringify({date,status:row.status,startTime:row.startTime||null,endTime:row.endTime||null,reason:row.reason})});setMessage(t('optimization.availabilitySaved'));await load()};const rows=(kind,items)=>items.map(row=>{const id=row[`${kind}Id`],name=row.vehicleCode||row.employeeName;return <div key={`${kind}-${id}`}><b data-i18n-raw>{name}</b><select aria-label={t('optimization.availabilityStatus')} value={row.status} onChange={event=>update(`${kind}s`,id,'status',event.target.value)}><option value="available">{t('optimization.available')}</option><option value="excluded">{t('optimization.excluded')}</option>{kind==='vehicle'?<option value="maintenance">{t('optimization.maintenance')}</option>:<option value="leave">{t('optimization.leave')}</option>}<option value="off_duty">{t('optimization.offDuty')}</option></select><input type="time" aria-label={t('optimization.startTime')} value={row.startTime||''} onChange={event=>update(`${kind}s`,id,'startTime',event.target.value)}/><input type="time" aria-label={t('optimization.endTime')} value={row.endTime||''} onChange={event=>update(`${kind}s`,id,'endTime',event.target.value)}/><input placeholder={t('optimization.availabilityReason')} value={row.reason||''} onChange={event=>update(`${kind}s`,id,'reason',event.target.value)}/><button type="button" onClick={()=>save(kind,row)}>{t('common.save')}</button></div>});return <details className="optimization-availability" open={open} onToggle={event=>setOpen(event.currentTarget.open)}><summary>{t('optimization.availability')}</summary>{message&&<small>{message}</small>}<h4>{t('optimization.vehicles')}</h4><div>{rows('vehicle',data.vehicles)}</div><h4>{t('optimization.crew')}</h4><div>{rows('employee',data.employees)}</div></details>}
function OptimizationRuleReview(){const{t}=useI18n(),[items,setItems]=useState([]),[open,setOpen]=useState(false);const load=useCallback(()=>request('/api/dispatch/optimization/rules?status=proposed').then(data=>setItems(data.items||[])).catch(()=>setItems([])),[]);useEffect(()=>{if(open)load()},[open,load]);const decide=async(item,status)=>{const reason=prompt(t('optimization.ruleDecisionReason'));if(!reason)return;await request(`/api/dispatch/optimization/rules/${item.id}`,{method:'PATCH',body:JSON.stringify({status,reason})});await load()};return <details className="optimization-rule-review" open={open} onToggle={event=>setOpen(event.currentTarget.open)}><summary>{t('optimization.ruleSuggestions')} ({items.length})</summary>{items.map(item=><article key={item.id}><b>{item.rule_type}</b><span>{item.reason}</span>{item.rule?.supportingFeedbackCount&&<small>{t('optimization.supportingOverrides',{count:item.rule.supportingFeedbackCount})}</small>}<button onClick={()=>decide(item,'approved')}>{t('optimization.approveRule')}</button><button onClick={()=>decide(item,'rejected')}>{t('optimization.rejectRule')}</button></article>)}</details>}

function DayApprovalControls({day,busy,hasUnsavedChanges,act}){
  const[mode,setMode]=useState(''),[reason,setReason]=useState(''),[check,setCheck]=useState(null),[checking,setChecking]=useState(false),[localError,setLocalError]=useState('')
  const openApproval=async()=>{if(hasUnsavedChanges){setLocalError('Save all pending Draft changes before approval.');return}setChecking(true);setLocalError('');try{setCheck(await request(`/api/dispatch/day/${day.dispatch_date}/approval-check`));setMode('approve')}catch(error){setLocalError(error.message)}finally{setChecking(false)}}
  const submit=async()=>{if(!reason.trim()){setLocalError(`${mode==='approve'?'Approval':'Withdrawal'} reason is required.`);return}try{await act(day.dispatch_date,mode==='approve'?'approve':'reopen',reason);setMode('');setReason('');setCheck(null)}catch(error){setLocalError(error.message)}}
  const summary=check?.summary||day.previewSummary
  return <div className="day-approval"><div className="day-actions">{['draft','reapproval_required'].includes(day.status)&&<button disabled={busy||checking||hasUnsavedChanges||day.unassignedStops.length>0} onClick={openApproval}>{checking?'Checking…':'Approve Day'}</button>}{day.status==='approved'&&<button disabled={busy} onClick={()=>{setMode('withdraw');setLocalError('')}}>Withdraw Approval</button>}</div>{day.status==='approved'&&<small className="approval-stamp">Approved by {day.approvedBy||'Supervisor'} · {day.approvedAt||'time unavailable'}</small>}{hasUnsavedChanges&&<small className="approval-warning">Save pending Draft changes before approval.</small>}{localError&&<div className="approval-error">{localError}</div>}
    {mode&&<div className="approval-modal" role="dialog" aria-modal="true" aria-label={mode==='approve'?'Approve Day':'Withdraw Approval'}><div><h3>{mode==='approve'?`Approve ${day.dispatch_date}`:`Withdraw approval for ${day.dispatch_date}`}</h3>{mode==='approve'&&<><div className="approval-summary"><span><b>{summary.stopCount}</b> Stops</span><span><b>{summary.stopCount-summary.unassignedCount}</b> Assigned</span><span><b>{summary.unassignedCount}</b> Unassigned</span><span><b>{summary.vehicleCount??day.vehicleBoards.filter(item=>item.customerCount).length}</b> Vehicles</span><span><b>{summary.weightedStopCount?`${summary.estimatedWeightKg} kg`:'Not set'}</b> Estimated</span><span><b>{summary.missingGpsCount}</b> GPS warnings</span><span><b>{summary.missingWeightCount}</b> Weight warnings</span><span><b>{summary.timeRestrictionCount}</b> Time restrictions</span></div><div className="approval-trips">{(summary.trips||day.vehicleBoards.flatMap(board=>board.slots.filter(slot=>slot.stopCount).map(slot=>({vehicle:board.vehicle,tripNumber:slot.tripNumber,stopCount:slot.stopCount,estimatedWeightKg:slot.estimatedWeightKg,missingWeightCount:slot.missingWeightCount})))).map((trip,index)=><small key={`${trip.vehicleId||trip.vehicle}-${trip.tripNumber}-${index}`}>{trip.vehicle} · Trip {trip.tripNumber}: {trip.stopCount} Stops · {trip.missingWeightCount?`${trip.estimatedWeightKg} kg + ${trip.missingWeightCount} weight not set`:`${trip.estimatedWeightKg} kg`}</small>)}</div>{check&&!check.ok&&<div className="approval-error">{check.issues.map(item=><p key={`${item.code}-${item.stopId||''}`}>{item.message}</p>)}</div>}</>}
      <label>{mode==='approve'?'Approval reason / remarks':'Withdrawal reason'}<textarea value={reason} onChange={event=>setReason(event.target.value)} autoFocus/></label><div className="approval-modal-actions"><button onClick={()=>{setMode('');setReason('');setCheck(null)}}>Cancel</button><button className="primary" disabled={busy||(mode==='approve'&&!check?.ok)} onClick={submit}>{mode==='approve'?'Confirm Approval':'Confirm Withdrawal'}</button></div></div></div>}
  </div>
}

function UnassignedPool({day,vehicles,patchStop,handleDrop,assignArea}){return <section className="unassigned-pool" onDragOver={event=>event.preventDefault()} onDrop={event=>handleDrop(event,{date:day.dispatch_date,unassigned:true})}><header><strong>Unassigned customer pool</strong><span>{day.unassignedStops.length}  · Zone Group → Area → Customer</span></header>{day.unassignedStops.length===0?<p>All customers are assigned to vehicles.</p>:<div className="zone-pool-list">{day.unassignedZones.map(zone=><ZonePool key={zone.zoneGroupId} day={day} zone={zone} vehicles={vehicles} patchStop={patchStop} assignArea={assignArea}/>)}</div>}</section>}

function ZonePool({day,zone,vehicles,patchStop,assignArea}){
  const{t}=useI18n(),[open,setOpen]=useState(false)
  const dragZone=(event)=>event.dataTransfer.setData('text/area-stops',JSON.stringify({zoneGroupId:zone.zoneGroupId,zoneGroupName:zone.zoneGroupName,customerCount:zone.customerCount,stops:zone.stops.map(stop=>({id:stop.id}))}))
  return <section className="zone-pool"><header><div className="zone-drag" draggable onDragStart={dragZone} title="Drag entire Zone Group to vehicle Trip"><b>{zone.zoneGroupName}</b><small>⠿ Drag entire Zone · {zone.areaCount} Areas</small><small>{t('defaultVehicle.plural')}: {defaultVehiclePoolLabel(zone.defaultVehicleIds,vehicles,t)} · {t('defaultVehicle.changeToday')}</small></div><div className="zone-actions"><VehiclePicker date={day.dispatch_date} vehicles={vehicles} onChoose={vehicleId=>assignArea(day.dispatch_date,zone,vehicleId,1)}/><button className="zone-toggle" onClick={()=>setOpen(!open)}>{open?'Collapse':'Expand'} {open?'▴':'▾'}</button></div></header><div className="area-metrics"><span><b>{zone.customerCount}</b> Customer</span><span><b>{zone.weightedCustomerCount?`${zone.estimatedWeightKg} kg`:'—'}</b> Estimated weight</span><span><b>{zone.missingGpsCount}</b> Missing GPS</span><span><b>{zone.timeRestrictionCount}</b> Time constraints</span></div>{open&&<div className="area-pool-list">{zone.areas.map(group=><AreaPool key={group.areaId??'none'} day={day} group={group} vehicles={vehicles} patchStop={patchStop} assignArea={assignArea}/>)}</div>}</section>
}

function AreaPool({day,group,vehicles,patchStop,assignArea}){
  const{t}=useI18n()
  const dragArea=(event)=>event.dataTransfer.setData('text/area-stops',JSON.stringify({areaId:group.areaId,areaName:group.areaName,customerCount:group.customerCount,stops:group.stops.map(stop=>({id:stop.id}))}))
  return <section className="area-pool"><header><div className="area-drag" draggable onDragStart={dragArea} title="Drag entire Area to vehicle Trip"><b>{group.areaName}</b><small>⠿ Drag entire Area</small><small>{t('defaultVehicle.plural')}: {defaultVehiclePoolLabel(group.defaultVehicleIds,vehicles,t)} · {t('defaultVehicle.changeToday')}</small></div><VehiclePicker date={day.dispatch_date} vehicles={vehicles} onChoose={vehicleId=>assignArea(day.dispatch_date,group,vehicleId,1)}/></header><div className="area-metrics"><span><b>{group.customerCount}</b> Customer</span><span><b>{group.weightedCustomerCount?`${group.estimatedWeightKg} kg`:'—'}</b> Estimated weight</span><span><b>{group.missingGpsCount}</b> Missing GPS</span><span><b>{group.timeRestrictionCount}</b> Time constraints</span></div><div className="area-stops">{group.stops.map(stop=><StopCard key={stop.id} stop={stop} patchStop={patchStop}/>)}</div></section>
}

function VehiclePicker({date,vehicles,onChoose}){
  const[open,setOpen]=useState(false),[search,setSearch]=useState(''),[showUnavailable,setShowUnavailable]=useState(false)
  const choices=vehicles.filter(item=>(showUnavailable||usableVehicle(item,date))&&`${item.vehicleCode} ${item.vehicleName||''} ${item.registrationNumber||''}`.toLowerCase().includes(search.toLowerCase()))
  return <div className="resource-picker"><button className="picker-trigger" onClick={()=>setOpen(!open)}>Unassigned vehicle</button>{open&&<div className="picker-panel vehicle-picker-panel"><input autoFocus placeholder="Search vehicle number or name" value={search} onChange={event=>setSearch(event.target.value)}/><label className="show-unavailable"><input type="checkbox" checked={showUnavailable} onChange={event=>setShowUnavailable(event.target.checked)}/> Show maintenance / inactive vehicles</label><div>{choices.map(item=>{const disabled=!usableVehicle(item,date);return <button key={item.id} disabled={disabled} onClick={()=>{onChoose(item.id);setOpen(false)}}><strong>{vehicleLabel(item)}</strong><small>Capacity {item.capacityKg?`${item.capacityKg} kg`:'—'} · {vehicleStatus[item.status]||item.status}{disabled?' (Cannot select)':''}</small><small>Base {item.defaultBase||'Not set'} · Usual Areas {item.preferredAreas.join(', ')||'Not set'}</small></button>})}{choices.length===0&&<p>No matching vehicles</p>}</div></div>}</div>
}

function VehicleBoard({day,board,allBoards,vehicles,employees,buyers,endLocations,patchStop,patchTrip,handleDrop,assignVehicle,transferVehicle,moveStop,canEditDispatch}){
  const{t}=useI18n()
  const update=(body)=>assignVehicle(day.dispatch_date,board.id,body)
  const recommended=board.preferredAreas?.filter(area=>board.areas.includes(area))||[]
  return <article id={`dispatch-${day.id}-vehicle-${board.id}`} className="vehicle-board"><header><div><strong>{vehicleLabel(board)}</strong><small>{board.capacityKg?`${board.capacityKg} kg`:'Capacity not set'} · Base {board.defaultBase||'Not set'} · {board.customerCount} Stops · {board.weightedStopCount?`${board.estimatedWeightKg} kg estimated`:'weight not set'}{board.missingWeightCount?` · ${board.missingWeightCount} missing weight`:''}{board.overCapacity?<b className="route-warning"> · Over capacity</b>:''}</small></div><span>{board.areas.length?board.areas.join(', '):'Unassigned Area'}{recommended.length?` · recommendation match ${recommended.join(', ')}`:''}{board.customerCount>0&&<button className="transfer-vehicle" onClick={()=>transferVehicle(day.dispatch_date,board.id,vehicles)}>Transfer entire vehicle plan</button>}</span></header><div className="vehicle-crew"><DriverPicker board={board} allBoards={allBoards} employees={employees} onChange={driverId=>update({driverId})}/><AssistantPicker board={board} employees={employees} onChange={assistantIds=>update({assistantIds})}/></div><div className="vehicle-trips">{board.slots.map(slot=><section key={slot.tripNumber} onDragOver={event=>event.preventDefault()} onDrop={event=>handleDrop(event,{date:day.dispatch_date,vehicleId:board.id,tripNumber:slot.tripNumber,stopSequence:slot.stops.length+1})}><header><strong>Trip {slot.tripNumber}</strong><span>{slot.stopCount}</span></header>{day.status==='draft'&&slot.tripId&&slot.stopCount>1&&<button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('kcs-optimize-trip',{detail:{date:day.dispatch_date,tripId:slot.tripId}}))}>{t('optimization.tripAction')}</button>}<small className="trip-metrics">{slot.weightedStopCount?`${slot.estimatedWeightKg} kg estimated`:'Weight not set'}{slot.missingWeightCount?` · ${slot.missingWeightCount} missing`:''}</small>{slot.tripId&&<><StartLocationControl slot={slot} driverId={board.driverId} onSave={payload=>patchTrip(slot.tripId,payload)}/><TripCommercialControl slot={slot} buyers={buyers} endLocations={endLocations} onSave={payload=>patchTrip(slot.tripId,payload)}/></>} {slot.stops.length===0?<p>Drop a Zone, Area or customer here</p>:slot.stops.map((stop,index)=><div key={stop.id} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.stopPropagation();handleDrop(event,{date:day.dispatch_date,vehicleId:board.id,tripNumber:slot.tripNumber,stopSequence:index+1})}}><StopCard stop={stop} patchStop={patchStop} day={day} board={board} targetBoards={allBoards} moveStop={moveStop} canEditDispatch={canEditDispatch}/></div>)}</section>)}</div></article>
}

function TripCommercialControl({slot,buyers,endLocations,onSave}){
  const[buyerId,setBuyerId]=useState(slot.buyerReferenceId?String(slot.buyerReferenceId):''),[endId,setEndId]=useState(slot.endLocationReferenceId?String(slot.endLocationReferenceId):''),[reason,setReason]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const ordered=useMemo(()=>[...endLocations].sort((a,b)=>Number(b.buyerReferenceId===Number(buyerId))-Number(a.buyerReferenceId===Number(buyerId))||a.locationName.localeCompare(b.locationName)),[endLocations,buyerId])
  const save=async()=>{if(!reason.trim()){setError('Change Reason is required');return}setSaving(true);setError('');try{await onSave({buyerPayer:buyerId?{referenceId:Number(buyerId)}:null,primaryEndLocation:endId?{referenceId:Number(endId)}:null,reason:reason.trim()});setReason('')}catch(e){setError(e.message)}finally{setSaving(false)}}
  return <div className="trip-commercial"><label>Buyer / Payer<select aria-label={`Trip ${slot.tripNumber} Buyer / Payer`} value={buyerId} onChange={event=>setBuyerId(event.target.value)}><option value="">Not selected</option>{buyers.map(item=><option key={item.id} value={item.id}>{item.buyerCode} — {item.buyerName}</option>)}</select></label><label>Primary End Location<select aria-label={`Trip ${slot.tripNumber} Primary End Location`} value={endId} onChange={event=>setEndId(event.target.value)}><option value="">Not selected</option>{ordered.map(item=><option key={item.id} value={item.id}>{item.buyerReferenceId===Number(buyerId)?'Recommended · ':''}{item.parentName?`${item.parentName} — `:''}{item.locationName} · GPS Set</option>)}</select></label>{endId&&<small>{ordered.find(item=>String(item.id)===endId)?.address||'Address not set'}</small>}<label>Change Reason<input value={reason} onChange={event=>setReason(event.target.value)}/></label>{error&&<small className="data-error">{error}</small>}<button type="button" disabled={saving} onClick={save}>{saving?'Saving…':'Save Buyer & End Location'}</button></div>
}

function StartLocationControl({slot,driverId,onSave}){
  const[open,setOpen]=useState(false),[options,setOptions]=useState(null),[type,setType]=useState(slot.startLocationType||'factory'),[saved,setSaved]=useState(''),[custom,setCustom]=useState({name:'',address:'',latitude:'',longitude:'',gpsSource:''}),[reason,setReason]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false)
  const show=async()=>{setOpen(true);setError('');try{setOptions(await request(`/api/dispatch/start-location-options${driverId?`?driverId=${driverId}`:''}`))}catch(reason){setError(reason.message)}}
  const submit=async()=>{if(!reason.trim()){setError('Change Reason is required');return}let startLocation={type};if(type==='employee_home')startLocation={type,referenceId:driverId};if(type==='saved_location'){const[referenceType,referenceId]=saved.split(':');startLocation={type,referenceType,referenceId:Number(referenceId)}}if(type==='custom')startLocation={type,...custom};setSaving(true);setError('');try{await onSave({startLocation,reason:`${reason.trim()}${custom.gpsSource?` · GPS source: ${custom.gpsSource}`:''}`});setOpen(false)}catch(reasonError){setError(reasonError.message)}finally{setSaving(false)}}
  return <div className="trip-start-location"><button type="button" className="start-location-trigger" onClick={show}><b>Start Location</b><span>{slot.startLocationName||'Factory not set'}</span><small>{slot.startLatitude!=null?`GPS Set · ${slot.startAddress||'Address not set'}`:'GPS Not Set'}</small></button>{open&&<div className="start-location-dialog" role="dialog" aria-modal="true" aria-label="Start Location"><div><header><h3>Start Location · Trip {slot.tripNumber}</h3><button type="button" onClick={()=>setOpen(false)}>×</button></header><label>Type<select value={type} onChange={event=>setType(event.target.value)}><option value="factory">Factory</option><option value="employee_home">Employee Home</option><option value="saved_location">Saved Location</option><option value="custom">Custom Location</option></select></label>{type==='factory'&&<p>{options?.factory?`Factory — ${options.factory.startLocationName} · ${options.factory.startAddress||'Address not set'} · GPS Set`:'Company Yard GPS is not set'}</p>}{type==='employee_home'&&<p>{options?.employeeHome?.startLocationName?`${options.employeeHome.startLocationName} · Home GPS Set`:(options?.employeeHome?.message||'Select a Driver')}</p>}{type==='saved_location'&&<label>Saved Location<select value={saved} onChange={event=>setSaved(event.target.value)}><option value="">Select a GPS-enabled location</option>{(options?.savedLocations||[]).map(item=><option key={`${item.startLocationReferenceType}:${item.startLocationReferenceId}`} value={`${item.startLocationReferenceType}:${item.startLocationReferenceId}`}>{item.startLocationName} — {item.startAddress||'Address not set'}</option>)}</select></label>}{type==='custom'&&<><label>Name<input value={custom.name} onChange={event=>setCustom(value=>({...value,name:event.target.value}))}/></label><label>Address<textarea value={custom.address} onChange={event=>setCustom(value=>({...value,address:event.target.value}))}/></label><SharedGpsInput resetKey={`dispatch-start:${slot.id||slot.dispatchId||slot.tripNumber}`} latitude={custom.latitude} longitude={custom.longitude} address={custom.address} gpsSource={custom.gpsSource} onChange={change=>setCustom(value=>({...value,latitude:change.latitude,longitude:change.longitude,address:change.address??value.address,gpsSource:change.gpsSource}))}/></>}<label>Change Reason<input value={reason} onChange={event=>setReason(event.target.value)}/></label>{error&&<p className="data-error">{error}</p>}<FormActionBar><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button type="button" className="primary" disabled={saving} onClick={submit}>{saving?'Saving…':'Save Start Location'}</button></FormActionBar></div></div>}</div>
}

function DriverPicker({board,allBoards,employees,onChange}){
  const[open,setOpen]=useState(false),[search,setSearch]=useState('')
  const drivers=useMemo(()=>employees.filter(item=>(String(item.role||'').toLowerCase()==='driver'||item.additionalRoles?.includes('Driver'))&&`${item.name} ${item.employeeCode||''}`.toLowerCase().includes(search.toLowerCase())),[employees,search])
  return <div className="resource-picker"><button className={`picker-trigger ${!board.driverId?'missing':''}`} onClick={()=>setOpen(!open)}>{board.driver||'Unassigned driver'} ▾</button>{open&&<div className="picker-panel employee-picker-panel"><input autoFocus placeholder="Search driver name or employee number" value={search} onChange={event=>setSearch(event.target.value)}/>{board.driverId&&<button className="release-assignment" onClick={()=>{onChange(null);setOpen(false)}}>Release current driver assignment</button>}<div>{drivers.map(item=>{const other=allBoards.find(vehicle=>vehicle.id!==board.id&&vehicle.driverId===item.id),disabled=!usableEmployee(item)||Boolean(other);return <button key={item.id} disabled={disabled} onClick={()=>{onChange(item.id);setOpen(false)}}><strong>{item.name} · {item.employeeCode||'No employee code'}</strong><small>{employmentStatus[item.employmentStatus]||item.employmentStatus} · Base {item.defaultBase||'Not set'} · Area {item.defaultArea||'Not set'}</small><small>{other?`Assigned today: ${vehicleLabel(other)}`:'Not assigned to another vehicle today'}{!usableEmployee(item)?' · Unavailable':''}</small></button>})}{drivers.length===0&&<p>Employee Master No  Driver</p>}</div></div>}</div>
}

function AssistantPicker({board,employees,onChange}){
  const[open,setOpen]=useState(false),[search,setSearch]=useState(''),[selected,setSelected]=useState(board.assistantIds)
  useEffect(()=>{setSelected(board.assistantIds)},[board.assistantIds])
  const crew=useMemo(()=>employees.filter(item=>(['assistant','crew','attendant / crew'].includes(String(item.role||'').toLowerCase())||item.additionalRoles?.includes('Attendant / Crew'))&&`${item.name} ${item.employeeCode||''}`.toLowerCase().includes(search.toLowerCase())),[employees,search])
  const toggle=(id)=>{const next=selected.includes(id)?selected.filter(item=>item!==id):selected.length<MAX_ASSIGNED_CREW?[...selected,id]:selected;if(next===selected)return;setSelected(next);onChange(next)}
  return <div className="resource-picker"><button className={`picker-trigger ${!selected.length?'missing':''}`} onClick={()=>setOpen(!open)}>{board.assistants.length?board.assistants.map(item=>item.name).join(', '):'Unassigned crew'} · {selected.length}/{MAX_ASSIGNED_CREW} ▾</button>{open&&<div className="picker-panel employee-picker-panel"><input autoFocus placeholder="Search crew name or employee number" value={search} onChange={event=>setSearch(event.target.value)}/><div>{crew.map(item=>{const checked=selected.includes(item.id),limitReached=!checked&&selected.length>=MAX_ASSIGNED_CREW,disabled=!usableEmployee(item)||limitReached;return <button key={item.id} disabled={disabled} onClick={()=>toggle(item.id)}><strong>{checked?'☑':'☐'} {item.name} · {item.employeeCode||'No employee code'}</strong><small>{item.role} · {employmentStatus[item.employmentStatus]||item.employmentStatus} · Base {item.defaultBase||'Not set'} · Area {item.defaultArea||'Not set'}{!usableEmployee(item)?' · Unavailable':limitReached?' · Maximum 2 crew selected':''}</small></button>})}{crew.length===0&&<p>Employee Master No  Assistant/Crew</p>}</div></div>}</div>
}

function StopCard({stop,patchStop,day,board,targetBoards=[],moveStop,canEditDispatch=false}){
  const gps=Number.isFinite(stop.latitude)&&Number.isFinite(stop.longitude)&&stop.latitude!==0&&stop.longitude!==0,[target,setTarget]=useState('')
  const targets=targetBoards.filter(item=>item.id!==board?.id)
  return <div className={`route-stop ${stop.sequenceLocked?'sequence-locked':''}`} draggable={!stop.sequenceLocked&&day?.status==='draft'&&canEditDispatch} onDragStart={event=>event.dataTransfer.setData('text/stop-id',String(stop.id))}><i>{stop.stopSequence}</i><span><b>{formatBranchId(stop.branchId)} — {stop.branchName||'Unnamed branch'}</b><small>{formatCustomerId(stop.customerId)} — {stop.customerName||'Unmatched customer'} · {stop.area||'Unassigned area'} · {stop.estimatedWeightKg!=null?`${stop.estimatedWeightKg} kg`:'Weight not set'} · {gps?'GPS✓':'GPS missing'}</small>{stop.timeRestriction&&<small className="route-warning">Time restriction: {stop.timeRestriction}</small>}</span>{canEditDispatch&&board&&<div className="stop-actions"><select aria-label={`Move ${stop.branchName} to another vehicle`} value={target} disabled={day.status!=='draft'} onChange={event=>setTarget(event.target.value)}><option value="">移到其他车辆</option>{targets.map(item=><option key={item.id} value={item.id}>{item.vehicle} · {item.registrationNumber||'No plate'}</option>)}</select><button type="button" disabled={day.status!=='draft'||!target} title={day.status!=='draft'?'Withdraw Approval first':'Move this route stop'} onClick={()=>{moveStop(day,stop,Number(target));setTarget('')}}>Move</button></div>}<button title="Lock sequence" onClick={()=>patchStop(stop.id,{sequenceLocked:!stop.sequenceLocked})}>{stop.sequenceLocked?'🔒':'○'}</button></div>
}
