import RouteCustomerList from './RouteCustomerList.jsx'
import RouteUnloadingRecords from './RouteUnloadingRecords.jsx'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import './Planner.css'
import {kuchingDate} from '../shared/kuchingTime.js'
import {useI18n} from './i18n.jsx'
import {apiRequest as request} from './apiClient.js'
import {formatBranchId,formatCustomerId} from '../shared/typedIds.js'
import {MAX_ASSIGNED_CREW} from '../shared/dispatchRules.js'
import SharedGpsInput from './SharedGpsInput.jsx'
import FormActionBar from './FormActionBar.jsx'
import RouteOptimizationMap from './RouteOptimizationMap.jsx'

const localDate=kuchingDate
const vehicleStatus={available:'Available',active:'Active',maintenance:'Maintenance',inactive:'Inactive',sold:'Sold'}
const employmentStatus={active:'Active',on_leave:'On Leave',inactive:'Inactive'}
const usableVehicle=(vehicle,date)=>['available','active'].includes(vehicle.status)&&(!vehicle.isTemporary||vehicle.temporaryDate===date)
const usableEmployee=(employee)=>Boolean(employee.isActive)&&employee.employmentStatus==='active'
const vehicleLabel=(item)=>`${item.vehicleCode||item.vehicle} — ${item.registrationNumber||'Registration plate not set'} — ${vehicleStatus[item.status]||item.status}`

export default function WeeklyDispatchPage({currentUser}){
  const{t}=useI18n()
  const[displayMode,setDisplayMode]=useState('dispatch'),[selectedWeekDate,setSelectedWeekDate]=useState(localDate()),[selectedRouteNumber,setSelectedRouteNumber]=useState(1),[data,setData]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  const canEditDispatch=['owner_admin','operations_admin','supervisor'].includes(currentUser.systemRole)||currentUser.permissions?.includes('schedule_manage')
  const canManageVehicles=['owner_admin','operations_admin'].includes(currentUser.systemRole)||currentUser.permissions?.includes('vehicle_manage')
  const canApproveDefer=['owner','owner_admin','operations_admin','supervisor'].includes(currentUser.systemRole||currentUser.role)
  const loadSequence=useRef(0)
  const load=useCallback(async()=>{const sequence=++loadSequence.current;setError('');try{
    const result=await request(canEditDispatch?'/api/dispatch/ensure-rolling-week':`/api/dispatch/week?startDate=${localDate()}`,canEditDispatch?{method:'POST'}:undefined)
    if(sequence===loadSequence.current)setData(result)
  }catch(e){if(sequence===loadSequence.current)setError(e.message)}},[canEditDispatch])
  useEffect(()=>{load()},[load])
  useEffect(()=>{const refresh=()=>load();window.addEventListener('kcs-handover-saved',refresh);return()=>window.removeEventListener('kcs-handover-saved',refresh)},[load])
  useEffect(()=>{const wake=()=>{if(document.visibilityState==='visible')load()};const timer=setInterval(load,10000);window.addEventListener('focus',load);document.addEventListener('visibilitychange',wake);return()=>{clearInterval(timer);window.removeEventListener('focus',load);document.removeEventListener('visibilitychange',wake)}},[load])
  const act=async(date,action,reason='')=>{setBusy(true);setMessage('');try{await request(`/api/dispatch/day/${date}/${action}`,{method:'POST',body:JSON.stringify({[action==='approve'?'approvedBy':'reopenedBy']:currentUser.name,reason})});setMessage(`${date} ${action==='approve'?'approved':'approval withdrawn'}.`);await load()}catch(e){setError(e.message);await load();throw e}finally{setBusy(false)}}
  const patchStop=async(id,body)=>{try{await request(`/api/dispatch/stops/${id}`,{method:'PATCH',body:JSON.stringify({...body,changedBy:currentUser.name})});await load()}catch(e){setError(e.message)}}
  const patchTrip=async(id,body)=>{try{await request(`/api/dispatch/trips/${id}`,{method:'PATCH',body:JSON.stringify(body)});setMessage('Start Location updated.');await load()}catch(e){setError(e.message);throw e}}
  const assignStopsToRoute=async(date,group,routeNumber)=>{const scrollTop=window.scrollY;try{await request(`/api/dispatch/day/${date}/assign-route`,{method:'POST',body:JSON.stringify({areaId:group.areaId??`zone:${group.zoneGroupId}`,stopIds:group.stops.map(stop=>stop.id),routeNumber,changedBy:currentUser.name})});setMessage(`${group.zoneGroupName||group.areaName} 的 ${group.customerCount} 家客户已分配到 Route ${routeNumber}。`);await load();requestAnimationFrame(()=>window.scrollTo(0,scrollTop));return true}catch(e){setError(e.message);throw e}}
  const handleDrop=async(event,body)=>{event.preventDefault();const id=event.dataTransfer.getData('text/stop-id');if(id)await patchStop(id,body)}
  const assignVehicle=async(date,vehicleId,body)=>{try{await request(`/api/dispatch/day/${date}/vehicle/${vehicleId}`,{method:'PATCH',body:JSON.stringify({...body,changedBy:currentUser.name})});await load()}catch(e){setError(e.message)}}
  const assignRoute=async(date,routeNumber,vehicleId)=>{try{await request(`/api/dispatch/day/${date}/route/${routeNumber}/vehicle`,{method:'PATCH',body:JSON.stringify({vehicleId:vehicleId||null})});setMessage(`Route ${routeNumber} 已${vehicleId?'整条分配到所选车辆':'解除当天车辆分配'}；客户与顺序没有改变。`);await load()}catch(e){setError(e.message)}}
  const renameRoute=async(routeNumber,currentName)=>{const name=prompt('请输入新的 Route 名称：',currentName);if(name==null||!name.trim()||name.trim()===currentName)return;try{await request(`/api/dispatch/routes/${routeNumber}`,{method:'PATCH',body:JSON.stringify({name:name.trim()})});setMessage(`Route ${routeNumber} 已改名为 ${name.trim()}。`);await load()}catch(e){setError(e.message)}}
  const reorderRouteCustomer=async(date,routeNumber,stopId,direction)=>{try{await request(`/api/dispatch/day/${date}/route/${routeNumber}/reorder`,{method:'POST',body:JSON.stringify({stopId,direction})});setMessage('客户顺序已保存；以后同一星期会跟随这个排列。');await load()}catch(e){setError(e.message)}}
  const approveSingleRoute=async(date,routeNumber)=>{try{const check=await request(`/api/dispatch/day/${date}/route/${routeNumber}/approval-check`);if(!check.ok)throw new Error(check.issues.map(item=>item.message).join(' '));await request(`/api/dispatch/day/${date}/route/${routeNumber}/approve`,{method:'POST',body:JSON.stringify({reason:'Route checked and ready'})});setMessage(`Route ${routeNumber} 已单独批准。`);await load()}catch(e){setError(e.message)}}
  const withdrawDayApproval=async(date)=>{const reason=prompt('请输入撤回批准的原因：','需要修改路线');if(!reason?.trim())return;try{await act(date,'reopen',reason.trim())}catch{/* act already displays the error */}}
  const transferVehicle=async(date,sourceVehicleId,vehicles)=>{const available=vehicles.filter(item=>item.id!==sourceVehicleId&&usableVehicle(item,date));const answer=prompt(`Enter target vehicle number or plate: \n${available.map(item=>vehicleLabel(item)).join('\n')}`,'QAV3468');if(!answer)return;const normalized=answer.replace(/[\s-]/g,'').toLowerCase(),target=available.find(item=>[item.vehicleCode,item.registrationNumber,String(item.id)].some(itemValue=>String(itemValue||'').replace(/[\s-]/g,'').toLowerCase()===normalized));if(!target){setError('No available target vehicle');return}const setSourceMaintenance=confirm('After route transfer, Set the original vehicle to  Maintenance？'),reason=prompt('Enter the transfer reason: ','Vehicle breakdown／Replace vehicle')||'Vehicle transfer';try{await request(`/api/dispatch/day/${date}/vehicle/${sourceVehicleId}/transfer`,{method:'POST',body:JSON.stringify({targetVehicleId:target.id,transferDriver:true,setSourceMaintenance,reason,changedBy:currentUser.name})});setMessage(`Trip, Customer routes and driver transferred to  ${vehicleLabel(target)}.`);await load()}catch(e){setError(e.message)}}
  const addTemporaryVehicle=async(date)=>{const vehicleCode=prompt('Temporary vehicle number: ',`Temporary Lorry (${date})`);if(!vehicleCode)return;try{await request('/api/vehicles/temporary',{method:'POST',body:JSON.stringify({date,vehicleCode})});setMessage(`${vehicleCode} added for ${date}.`);await load()}catch(e){setError(e.message)}}
  const addPermanentVehicle=async(date)=>{const vehicleCode=prompt('Permanent vehicle number: ');if(!vehicleCode)return;const registrationNumber=prompt('Registration plate (must be unique): ');if(!registrationNumber)return;const capacity=prompt('Capacity (kg, optional): ','');if(capacity!==''&&(!Number.isFinite(Number(capacity))||Number(capacity)<0)){setError('Capacity must be a non-negative number.');return}try{await request('/api/vehicles',{method:'POST',body:JSON.stringify({dispatchDate:date,vehicleCode,registrationNumber,capacityKg:capacity===''?null:Number(capacity)})});setMessage(`${vehicleCode} added permanently and selected for ${date}.`);await load()}catch(e){setError(e.message)}}
  const moveStop=async(day,stop,targetVehicleId)=>{setError('');try{await request(`/api/dispatch/stops/${stop.id}/move-vehicle`,{method:'POST',body:JSON.stringify({targetVehicleId,expectedRevision:day.revision,reason:'Supervisor moved one route stop'})});setMessage(`${stop.branchName||`Stop ${stop.id}`} moved to another vehicle.`);await load()}catch(e){setError(e.message);await load()}}
  const decideDefer=async(item,decision)=>{const reason=prompt(t(decision==='approve'?'deferApproval.approveReason':'deferApproval.rejectReason'));if(!reason)return;setBusy(true);setError('');try{await request(`/api/dispatch/defer-requests/${item.id}/${decision}`,{method:'POST',body:JSON.stringify({reason})});setMessage(t(decision==='approve'?'deferApproval.approvedMessage':'deferApproval.rejectedMessage',{branch:item.branchName}));await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const activeWeekDate=data?.days?.some(day=>day.dispatch_date===selectedWeekDate)?selectedWeekDate:data?.days?.[0]?.dispatch_date
  const visibleDays=displayMode==='route'?(data?.days||[]):(data?.days||[]).filter(day=>day.dispatch_date===activeWeekDate)
  return <div className="page planner-page">
    <div className="planner-navigation"><div className="planner-toolbar planner-view-toolbar"><div><button className={displayMode==='dispatch'?'active':''} onClick={()=>setDisplayMode('dispatch')}>派车</button><button className={displayMode==='route'?'active':''} onClick={()=>setDisplayMode('route')}>Route</button></div></div>{data?.days?.length>0&&(displayMode==='dispatch'?<WeekDayTabs days={data.days} selectedDate={activeWeekDate} onSelect={setSelectedWeekDate}/>:<RouteWeekTabs days={data.days} selectedRouteNumber={selectedRouteNumber} onSelect={setSelectedRouteNumber}/>)}</div>
    {message&&<div className="planner-message">✓ {message}</div>}{error&&<div className="data-error">{error}</div>}
    {!data?<div className="data-loading">{t('planner.loading')}</div>:<div className={displayMode==='route'?'route-week-board':'week-board week-board--single-day'}>{data.days.length===0?<div className="empty-week"><h2>{t('planner.empty')}</h2><p>{t('planner.emptyHelp')}</p></div>:visibleDays.map(day=><DayColumn days={data.days} canHandover={['owner_admin','operations_admin','supervisor'].includes(currentUser.systemRole||currentUser.role)} key={day.id} day={day} displayMode={displayMode} selectedRouteNumber={selectedRouteNumber} vehicles={data.vehicles||[]} employees={data.employees||[]} buyers={data.buyers||[]} endLocations={data.endLocations||[]} busy={busy} hasUnsavedChanges={false} patchStop={patchStop} patchTrip={patchTrip} handleDrop={handleDrop} assignStopsToRoute={assignStopsToRoute} assignRoute={assignRoute} renameRoute={renameRoute} reorderRouteCustomer={reorderRouteCustomer} approveSingleRoute={approveSingleRoute} withdrawDayApproval={withdrawDayApproval} assignVehicle={assignVehicle} transferVehicle={transferVehicle} addTemporaryVehicle={addTemporaryVehicle} addPermanentVehicle={addPermanentVehicle} moveStop={moveStop} decideDefer={decideDefer} canApproveDefer={canApproveDefer} canEditDispatch={canEditDispatch} canManageVehicles={canManageVehicles}/>)}</div>}
  </div>
}

function WeekDayTabs({days,selectedDate,onSelect}){
  const formatter=new Intl.DateTimeFormat('zh-MY',{month:'numeric',day:'numeric',weekday:'short',timeZone:'Asia/Kuching'})
  return <nav className="week-day-tabs" aria-label="一周派车日期">{days.map(day=>{const customerRoutes=(day.routeBoards||[]).filter(route=>route.customerCount>0),approved=customerRoutes.length>0&&customerRoutes.every(route=>route.approvalStatus==='approved');return <button type="button" key={day.dispatch_date} className={`${day.dispatch_date===selectedDate?'active ':''}${approved?'approved':''}`.trim()} aria-pressed={day.dispatch_date===selectedDate} onClick={()=>onSelect(day.dispatch_date)}><strong>{formatter.format(new Date(`${day.dispatch_date}T00:00:00+08:00`))}</strong><small>{day.routeBoards?.reduce((sum,route)=>sum+(route.customerCount||0),0)||day.stops?.length||0} 家{approved?' · ✓ 已批准':''}</small></button>})}</nav>
}

function RouteWeekTabs({days,selectedRouteNumber,onSelect}){
  const routes=days[0]?.routeBoards||[]
  return <nav className="week-day-tabs route-week-tabs" aria-label="Route 1 至 5">{[1,2,3,4,5].map(number=>{const route=routes.find(item=>item.routeNumber===number);return <button type="button" key={number} className={number===selectedRouteNumber?'active':''} aria-pressed={number===selectedRouteNumber} onClick={()=>onSelect(number)}><strong>{route?.name||`Route ${number}`}</strong><small>查看七天</small></button>})}</nav>
}

function DayColumn({days,canHandover,day,displayMode,selectedRouteNumber,vehicles,employees,buyers,endLocations,busy,hasUnsavedChanges,patchStop,patchTrip,handleDrop,assignStopsToRoute,assignRoute,renameRoute,reorderRouteCustomer,approveSingleRoute,withdrawDayApproval,assignVehicle,transferVehicle,addTemporaryVehicle,addPermanentVehicle,moveStop,decideDefer,canApproveDefer,canEditDispatch,canManageVehicles}){
  const[selectedVehicleId,setSelectedVehicleId]=useState(day.vehicleBoards[0]?.id??null)
  useEffect(()=>{if(!day.vehicleBoards.some(board=>board.id===selectedVehicleId))setSelectedVehicleId(day.vehicleBoards[0]?.id??null)},[day.dispatch_date,day.vehicleBoards,selectedVehicleId])
  const selectedBoard=day.vehicleBoards.find(board=>board.id===selectedVehicleId)||day.vehicleBoards[0]
  const renderOperations=route=><RouteOperations day={day} route={route} employees={employees} buyers={buyers} endLocations={endLocations} patchStop={patchStop} patchTrip={patchTrip} assignVehicle={assignVehicle} moveStop={moveStop} canEditDispatch={canEditDispatch}/>
  return <section className={`day-column vehicle-day ${day.status}`}>
    {displayMode==='route'?<RouteAssignmentPanel days={days} renderOperations={renderOperations} canHandover={canHandover} employees={employees} day={day} routeNumber={selectedRouteNumber} vehicles={vehicles} onAssign={assignRoute} onRename={renameRoute} onReorder={reorderRouteCustomer} onApprove={approveSingleRoute} onWithdraw={()=>withdrawDayApproval(day.dispatch_date)} busy={busy} hasUnsavedChanges={hasUnsavedChanges} canEdit={canEditDispatch}/>:<><RouteDispatchOverview day={day} vehicles={vehicles} days={days} renderOperations={renderOperations} canHandover={canHandover} employees={employees} onAssign={assignRoute} onRename={renameRoute} onReorder={reorderRouteCustomer} onApprove={approveSingleRoute} onWithdraw={()=>withdrawDayApproval(day.dispatch_date)} busy={busy} hasUnsavedChanges={hasUnsavedChanges} canEdit={canEditDispatch}/>{canApproveDefer&&<DeferApprovalPanel items={day.deferRequests||[]} busy={busy} onDecide={decideDefer}/>}<UnassignedPool day={day} patchStop={patchStop} assignStopsToRoute={assignStopsToRoute}/><div className="vehicle-tabs-row"><VehicleTabs boards={day.vehicleBoards} selectedVehicleId={selectedBoard?.id} onSelect={setSelectedVehicleId}/>{canManageVehicles&&canEditDispatch&&<div className="vehicle-create-actions"><button disabled={day.status!=='draft'} title={day.status!=='draft'?'Withdraw Approval first':'Add permanent vehicle'} onClick={()=>addPermanentVehicle(day.dispatch_date)}>＋ 长期车</button><button disabled={day.status!=='draft'} title={day.status!=='draft'?'Withdraw Approval first':'Add temporary vehicle for this date'} onClick={()=>addTemporaryVehicle(day.dispatch_date)}>＋ 临时车</button></div>}</div><div className="vehicle-board-list">{selectedBoard&&<VehicleBoard key={selectedBoard.id} day={day} board={selectedBoard} allBoards={day.vehicleBoards} vehicles={vehicles} employees={employees} buyers={buyers} endLocations={endLocations} patchStop={patchStop} patchTrip={patchTrip} handleDrop={handleDrop} assignVehicle={assignVehicle} transferVehicle={transferVehicle} moveStop={moveStop} canEditDispatch={canEditDispatch}/>}</div>{day.specialRequests.filter(item=>item.requestType==='potential_new').map(item=><div className={`special-route ${item.promisedToCustomer?'promised':''}`} key={item.id}><b>{item.promisedToCustomer?'Customer promise · ':''}{item.customerName}</b><small>Potential new customer · Trip {item.tripNumber||'—'}</small>{(!item.customerId||!item.branchId||item.occPrice==null||!item.paymentType)&&<span>Warning</span>}</div>)}</>}
  </section>
}

function RouteDispatchOverview(props){
  return <div aria-label="当天 Route 总览"><RouteAssignmentPanel {...props}/></div>
}

function DeferApprovalPanel({items,busy,onDecide}){
  const{t}=useI18n()
  const pending=items.filter(item=>item.status==='pending')
  if(!pending.length)return null
  return <section className="defer-approval-panel"><header><strong>{t('deferApproval.title')}</strong><span>{pending.length}</span></header>{pending.map(item=><article key={item.id}><div><b>{item.stopSequence}. {item.customerName} — {item.branchName}</b><small>{item.vehicleName||'Vehicle'} · {item.driverName} · {t('mobile.expectedReturnTime')} {item.expectedReturnTime}</small><small>{String(item.reason||'other').replaceAll('_',' ')}</small></div><button type="button" disabled={busy} onClick={()=>onDecide(item,'approve')}>{t('deferApproval.approve')}</button><button type="button" disabled={busy} onClick={()=>onDecide(item,'reject')}>{t('deferApproval.reject')}</button></article>)}</section>
}

function VehicleTabs({boards,selectedVehicleId,onSelect}){
  if(!boards.length)return <p className="vehicle-tabs-empty">No vehicles available for this date.</p>
  return <nav className="vehicle-tabs" role="tablist" aria-label="Vehicles available for this date">{boards.map(board=><button type="button" role="tab" aria-selected={board.id===selectedVehicleId} className={board.id===selectedVehicleId?'active':''} key={board.id} onClick={()=>onSelect(board.id)}>{board.registrationNumber||board.vehicle}</button>)}</nav>
}

// Kept for historical route-optimization audit access; fixed Route 1–5 no longer renders it.
// oxlint-disable-next-line no-unused-vars
function OptimizationControls({day,vehicles,disabled}){
  const{t}=useI18n(),[preview,setPreview]=useState(null),[open,setOpen]=useState(false),[working,setWorking]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[excluded,setExcluded]=useState([])
  const eligible=vehicles.filter(vehicle=>usableVehicle(vehicle,day.dispatch_date))
  const create=useCallback(async(mode='day',tripId=null)=>{setWorking(true);setError('');try{const result=await request('/api/dispatch/optimization/preview',{method:'POST',body:JSON.stringify({date:day.dispatch_date,mode,tripId,excludedVehicleIds:excluded})});setPreview(result);setOpen(true)}catch(e){setError(e.message)}finally{setWorking(false)}},[day.dispatch_date,excluded])
  useEffect(()=>{const handler=event=>{if(event.detail?.date===day.dispatch_date)create('trip',event.detail.tripId)};window.addEventListener('kcs-optimize-trip',handler);return()=>window.removeEventListener('kcs-optimize-trip',handler)},[create,day.dispatch_date])
  const apply=async()=>{if(!reason.trim()){setError(t('optimization.reasonRequired'));return}setWorking(true);try{await request(`/api/dispatch/optimization/${preview.runId}/apply`,{method:'POST',body:JSON.stringify({reason,expectedRevision:day.revision})});location.reload()}catch(e){setError(e.message);setWorking(false)}}
  return <section className="optimization-actions"><div><button className="primary" disabled={disabled||working||day.status!=='draft'} onClick={()=>create()}>{working?t('optimization.working'):t('optimization.dayAction')}</button><small>{t('optimization.roadLabel')}</small></div><details><summary>{t('optimization.vehicleSelection')}</summary>{eligible.map(vehicle=><label key={vehicle.id}><input type="checkbox" checked={!excluded.includes(vehicle.id)} onChange={()=>setExcluded(value=>value.includes(vehicle.id)?value.filter(id=>id!==vehicle.id):[...value,vehicle.id])}/>{vehicleLabel(vehicle)}</label>)}</details><AvailabilityManager date={day.dispatch_date}/><OptimizationRuleReview/>{error&&<p className="data-error">{error}</p>}
    {open&&preview&&<div className="optimization-modal" role="dialog" aria-modal="true" aria-label={t('optimization.previewTitle')}><div><header><div><h3>{t('optimization.previewTitle')}</h3><small>{preview.provider}{preview.cached?` · ${t('optimization.cached')}`:''}</small></div><button onClick={()=>setOpen(false)}>×</button></header><RouteOptimizationMap routes={preview.routes||[]}/><div className="optimization-metrics"><span><b>{preview.metrics?.totalDistanceMeters?`${(preview.metrics.totalDistanceMeters/1000).toFixed(1)} km`:'—'}</b>{t('optimization.distance')}</span><span><b>{preview.metrics?.totalDurationSeconds?`${Math.round(preview.metrics.totalDurationSeconds/60)} min`:'—'}</b>{t('optimization.duration')}</span><span><b>{preview.proposed?.length||0}</b>{t('optimization.assigned')}</span><span><b>{preview.unassigned?.length||0}</b>{t('optimization.unassigned')}</span></div>{preview.comparison?.available?<div className="optimization-savings"><span><b>{(preview.comparison.currentDistanceMeters/1000).toFixed(1)} km</b>{t('optimization.currentRoad')}</span><span><b>{(preview.comparison.proposedDistanceMeters/1000).toFixed(1)} km</b>{t('optimization.proposedRoad')}</span><span><b>{(preview.comparison.distanceSavingsMeters/1000).toFixed(1)} km · {Math.round(preview.comparison.durationSavingsSeconds/60)} min</b>{t('optimization.savings')}</span></div>:<p>{t('optimization.savings')}: {t('common.notAvailable')}</p>}{(preview.horizons||[]).some(item=>item.source==='default_fallback')&&<small>{t('optimization.fallbackHours')}</small>}<div className="optimization-compare"><section><h4>{t('optimization.proposed')}</h4>{eligible.map(vehicle=><div key={vehicle.id}><strong>{vehicleLabel(vehicle)}</strong>{(preview.proposed||[]).filter(item=>item.vehicleId===vehicle.id).sort((a,b)=>a.sequence-b.sequence).map(item=>{const stop=day.stops.find(row=>row.id===item.stopId),oldVehicle=eligible.find(row=>row.id===stop?.vehicleId);return <small key={item.stopId}>#{item.sequence} · <span data-i18n-raw>{stop?.branchName||`Stop ${item.stopId}`}</span> · {oldVehicle?vehicleLabel(oldVehicle):t('optimization.unassigned')} → {vehicleLabel(vehicle)}</small>})}</div>)}</section><section><h4>{t('optimization.warnings')}</h4>{(preview.warnings||[]).map((warning,index)=><p key={`${warning.code}-${index}`}>{warning.message}</p>)}{(preview.unassigned||[]).map(item=><p key={item.stopId}>Stop {item.stopId}: {item.reason}</p>)}</section></div><label>{t('optimization.applyReason')}<textarea value={reason} onChange={event=>setReason(event.target.value)}/></label><div className="approval-modal-actions"><button onClick={()=>setOpen(false)}>{t('common.cancel')}</button><button className="primary" disabled={working||preview.unassigned?.length>0} onClick={apply}>{t('optimization.apply')}</button></div></div></div>}
  </section>
}

function AvailabilityManager({date}){const{t}=useI18n(),[data,setData]=useState({vehicles:[],employees:[]}),[open,setOpen]=useState(false),[message,setMessage]=useState('');const load=useCallback(()=>request(`/api/dispatch/optimization/availability?date=${date}`).then(setData).catch(()=>setData({vehicles:[],employees:[]})),[date]);useEffect(()=>{if(open)load()},[open,load]);const update=(kind,id,field,value)=>setData(current=>({...current,[kind]:current[kind].map(item=>item[`${kind.slice(0,-1)}Id`]===id?{...item,[field]:value}:item)}));const save=async(kind,row)=>{if(!row.reason?.trim()){setMessage(t('optimization.availabilityReason'));return}const id=row[`${kind}Id`];await request(`/api/dispatch/optimization/availability/${kind}/${id}`,{method:'PUT',body:JSON.stringify({date,status:row.status,startTime:row.startTime||null,endTime:row.endTime||null,reason:row.reason})});setMessage(t('optimization.availabilitySaved'));await load()};const rows=(kind,items)=>items.map(row=>{const id=row[`${kind}Id`],name=row.vehicleCode||row.employeeName;return <div key={`${kind}-${id}`}><b data-i18n-raw>{name}</b><select aria-label={t('optimization.availabilityStatus')} value={row.status} onChange={event=>update(`${kind}s`,id,'status',event.target.value)}><option value="available">{t('optimization.available')}</option><option value="excluded">{t('optimization.excluded')}</option>{kind==='vehicle'?<option value="maintenance">{t('optimization.maintenance')}</option>:<option value="leave">{t('optimization.leave')}</option>}<option value="off_duty">{t('optimization.offDuty')}</option></select><input type="time" aria-label={t('optimization.startTime')} value={row.startTime||''} onChange={event=>update(`${kind}s`,id,'startTime',event.target.value)}/><input type="time" aria-label={t('optimization.endTime')} value={row.endTime||''} onChange={event=>update(`${kind}s`,id,'endTime',event.target.value)}/><input placeholder={t('optimization.availabilityReason')} value={row.reason||''} onChange={event=>update(`${kind}s`,id,'reason',event.target.value)}/><button type="button" onClick={()=>save(kind,row)}>{t('common.save')}</button></div>});return <details className="optimization-availability" open={open} onToggle={event=>setOpen(event.currentTarget.open)}><summary>{t('optimization.availability')}</summary>{message&&<small>{message}</small>}<h4>{t('optimization.vehicles')}</h4><div>{rows('vehicle',data.vehicles)}</div><h4>{t('optimization.crew')}</h4><div>{rows('employee',data.employees)}</div></details>}
function OptimizationRuleReview(){const{t}=useI18n(),[items,setItems]=useState([]),[open,setOpen]=useState(false);const load=useCallback(()=>request('/api/dispatch/optimization/rules?status=proposed').then(data=>setItems(data.items||[])).catch(()=>setItems([])),[]);useEffect(()=>{if(open)load()},[open,load]);const decide=async(item,status)=>{const reason=prompt(t('optimization.ruleDecisionReason'));if(!reason)return;await request(`/api/dispatch/optimization/rules/${item.id}`,{method:'PATCH',body:JSON.stringify({status,reason})});await load()};return <details className="optimization-rule-review" open={open} onToggle={event=>setOpen(event.currentTarget.open)}><summary>{t('optimization.ruleSuggestions')} ({items.length})</summary>{items.map(item=><article key={item.id}><b>{item.rule_type}</b><span>{item.reason}</span>{item.rule?.supportingFeedbackCount&&<small>{t('optimization.supportingOverrides',{count:item.rule.supportingFeedbackCount})}</small>}<button onClick={()=>decide(item,'approved')}>{t('optimization.approveRule')}</button><button onClick={()=>decide(item,'rejected')}>{t('optimization.rejectRule')}</button></article>)}</details>}

function RouteHandover({day,route,vehicles,employees}){
  const[open,setOpen]=useState(false),[vehicleId,setVehicleId]=useState(String(route.vehicleId||'')),[driverId,setDriverId]=useState(''),[reason,setReason]=useState(''),[working,setWorking]=useState(false),[error,setError]=useState('')
  const show=()=>{setVehicleId(String(route.vehicleId));setDriverId(String(day.vehicleBoards.find(v=>v.id===route.vehicleId)?.driverId||''));setError('');setOpen(true)}
  const save=async()=>{setWorking(true);setError('');try{await request(`/api/dispatch/day/${day.dispatch_date}/route/${route.routeNumber}/handover`,{method:'POST',body:JSON.stringify({vehicleId:Number(vehicleId),driverId:Number(driverId),reason,expectedRevision:day.revision})});setOpen(false);setReason('');window.dispatchEvent(new Event('kcs-handover-saved'))}catch(e){setError(e.message)}finally{setWorking(false)}}
  return <div><button type="button" onClick={show}>调整当天车辆／司机</button>{open&&<div role="group" aria-label="当天交接"><p>只影响当天。旧单据归属不变，明天安排不变。</p><label>车辆<select value={vehicleId} disabled={working} onChange={e=>setVehicleId(e.target.value)}>{vehicles.filter(v=>usableVehicle(v,day.dispatch_date)).map(v=><option key={v.id} value={v.id}>{v.registrationNumber||v.vehicleCode}</option>)}</select></label><label>接手司机<select value={driverId} disabled={working} onChange={e=>setDriverId(e.target.value)}><option value="">选择司机</option>{employees.filter(e=>usableEmployee(e)&&(['driver','supervisor'].includes(String(e.role).toLowerCase())||e.additionalRoles?.includes('Driver'))).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>调整原因<input value={reason} disabled={working} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert" className="data-error">{error}</p>}<button type="button" disabled={working||!vehicleId||!driverId||!reason.trim()} onClick={save}>{working?'保存中…':'确认当天调整'}</button><button type="button" disabled={working} onClick={()=>setOpen(false)}>取消</button></div>}</div>
}

function RouteAssignmentPanel({days=[],renderOperations,canHandover=false,day,routeNumber,vehicles,employees=[],onAssign,onRename,onReorder,onApprove,onWithdraw,busy,hasUnsavedChanges,canEdit}){
  const allRoutes=day.routeBoards||[],routes=allRoutes.filter(route=>!routeNumber||route.routeNumber===routeNumber),used=new Map(allRoutes.filter(route=>route.vehicleId).map(route=>[route.vehicleId,route.routeNumber])),editable=canEdit&&['draft','reapproval_required'].includes(day.status),approvable=canEdit&&['draft','reapproval_required','in_progress'].includes(day.status)
  return <section className="route-assignment-panel">{day.status==='approved'&&<header><button type="button" disabled={busy||hasUnsavedChanges} onClick={onWithdraw}>撤回当天批准</button></header>}<div className="route-assignment-grid">{routes.map(route=><details key={route.routeNumber} className={`route-assignment-card ${route.approvalStatus==='approved'?'approved':''}`}><summary><b>{route.name}</b><span>{route.customerCount} 家</span><strong>{route.vehicleId?(route.registrationNumber||route.vehicle||'未设车牌'):'当天未分配车辆'}</strong><small className="route-service-date">{day.dispatch_date}</small><em className={`route-approval-status ${route.approvalStatus}`}>{route.approvalStatus==='approved'?'已批准':route.approvalStatus==='reapproval_required'?'需要重新批准':route.approvalStatus==='empty'?'当天没有客户':'尚未批准'}</em></summary><div className="route-card-actions"><button type="button" className="route-name-edit" disabled={!canEdit} onClick={()=>onRename(route.routeNumber,route.name)}>改名</button>{route.customerCount>0&&route.approvalStatus!=='approved'&&<button type="button" className="primary" disabled={!approvable||!route.vehicleId} onClick={()=>onApprove(day.dispatch_date,route.routeNumber)}>批准这条 Route</button>}</div>{canHandover&&day.dispatch_date===localDate()&&day.status!=='completed'&&route.vehicleId&&<RouteHandover day={day} route={route} vehicles={vehicles} employees={employees}/>}<label>当天执行车辆<select value={route.vehicleId||''} disabled={!editable||route.customerCount===0} onChange={event=>onAssign(day.dispatch_date,route.routeNumber,event.target.value?Number(event.target.value):null)}><option value="">未分配</option>{vehicles.filter(item=>usableVehicle(item,day.dispatch_date)).map(vehicle=>{const occupied=used.get(vehicle.id);return <option key={vehicle.id} value={vehicle.id} disabled={occupied&&occupied!==route.routeNumber}>{vehicle.registrationNumber||vehicle.vehicleCode||vehicle.vehicle}{occupied&&occupied!==route.routeNumber?` · 已给 Route ${occupied}`:''}</option>})}</select></label>{renderOperations?.(route)}<RouteCustomerList day={day} route={route} days={days} canEdit={canEdit} onReorder={onReorder} busy={busy}/><RouteUnloadingRecords date={day.dispatch_date} routeNumber={route.routeNumber} revision={day.revision}/></details>)}</div></section>
}

function UnassignedPool({day,patchStop,assignStopsToRoute}){const stops=day.extraUnassignedStops||[];return <section className="unassigned-pool"><header><strong>Route 以外的临时客户</strong><span>{stops.length} · Zone只用于查看地理位置</span></header>{stops.length===0?<p>没有 Route 以外的临时客户。</p>:<div className="zone-pool-list">{day.unassignedZones.map(zone=><ZonePool key={zone.zoneGroupId} day={day} zone={zone} patchStop={patchStop} assignStopsToRoute={assignStopsToRoute}/>)}</div>}</section>}

function ZonePool({day,zone,patchStop,assignStopsToRoute}){
  const[open,setOpen]=useState(false)
  return <section className="zone-pool"><header><div className="zone-drag"><b>{zone.zoneGroupName}</b><small>地理 Zone · {zone.areaCount} Areas</small></div><div className="zone-actions"><RoutePicker routes={day.routeBoards||[]} onChoose={routeNumber=>assignStopsToRoute(day.dispatch_date,zone,routeNumber)}/><button className="zone-toggle" onClick={()=>setOpen(!open)}>{open?'Collapse':'Expand'} {open?'▴':'▾'}</button></div></header><div className="area-metrics"><span><b>{zone.customerCount}</b> Customer</span><span><b>{zone.weightedCustomerCount?`${zone.estimatedWeightKg} kg`:'—'}</b> Estimated weight</span><span><b>{zone.missingGpsCount}</b> Missing GPS</span><span><b>{zone.timeRestrictionCount}</b> Time constraints</span></div>{open&&<div className="area-pool-list">{zone.areas.map(group=><AreaPool key={group.areaId??'none'} day={day} group={group} routes={day.routeBoards||[]} patchStop={patchStop} assignStopsToRoute={assignStopsToRoute}/>)}</div>}</section>
}

function AreaPool({day,group,routes,patchStop,assignStopsToRoute}){
  return <section className="area-pool"><header><div className="area-drag"><b>{group.areaName}</b><small>地理 Area</small></div><RoutePicker routes={routes} onChoose={routeNumber=>assignStopsToRoute(day.dispatch_date,group,routeNumber)}/></header><div className="area-metrics"><span><b>{group.customerCount}</b> Customer</span><span><b>{group.weightedCustomerCount?`${group.estimatedWeightKg} kg`:'—'}</b> Estimated weight</span><span><b>{group.missingGpsCount}</b> Missing GPS</span><span><b>{group.timeRestrictionCount}</b> Time constraints</span></div><div className="area-stops">{group.stops.map(stop=><StopCard key={stop.id} stop={stop} patchStop={patchStop}/>)}</div></section>
}

function useOutsideClose(open,onClose){
  const rootRef=useRef(null)
  useEffect(()=>{if(!open)return undefined;const close=event=>{if(!rootRef.current?.contains(event.target))onClose()};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[open,onClose])
  return rootRef
}

function RoutePicker({routes,onChoose}){
  const[open,setOpen]=useState(false),[working,setWorking]=useState(false),[localError,setLocalError]=useState(''),close=useCallback(()=>setOpen(false),[]),rootRef=useOutsideClose(open,close)
  const choose=async routeNumber=>{setWorking(true);setLocalError('');try{await onChoose(routeNumber);setOpen(false)}catch(error){setLocalError(error.message)}finally{setWorking(false)}}
  return <div className="resource-picker" ref={rootRef}><button type="button" className="picker-trigger" disabled={working} onClick={()=>setOpen(value=>!value)}>未分配 Route ▾</button>{open&&<div className="picker-panel route-picker-panel">{localError&&<p className="route-picker-error">{localError}</p>}<div>{routes.map(route=><button type="button" key={route.routeNumber} disabled={working} onClick={()=>choose(route.routeNumber)}><strong>{route.name||`Route ${route.routeNumber}`}</strong><small>{route.customerCount||0} 家{route.registrationNumber?` · ${route.registrationNumber}`:''}</small></button>)}</div></div>}</div>
}

function RouteOperations({day,route,employees,buyers,endLocations,patchTrip,assignVehicle,canEditDispatch}){
  const board=day.vehicleBoards.find(item=>item.id===route.vehicleId)
  if(!board)return null
  const editable=canEditDispatch&&['draft','reapproval_required'].includes(day.status)
  const slots=board.slots.filter(slot=>slot.tripId&&slot.stops.some(stop=>stop.routeNumber===route.routeNumber))
  return <div className="route-operations">
    {editable?<div className="vehicle-crew"><DriverPicker board={board} allBoards={day.vehicleBoards} employees={employees} onChange={driverId=>assignVehicle(day.dispatch_date,board.id,{driverId})}/><AssistantPicker board={board} employees={employees} onChange={assistantIds=>assignVehicle(day.dispatch_date,board.id,{assistantIds})}/></div>:<p>司机：{board.driver||'未分配'} · Attendant：{board.assistants.map(item=>item.name).join(', ')||'未分配'}</p>}
    {slots.length>0&&<details><summary>收货设置</summary>{slots.map(slot=><div key={slot.tripId}>
      {editable&&<StartLocationControl slot={slot} driverId={board.driverId} onSave={payload=>patchTrip(slot.tripId,payload)}/>}
      {editable&&<TripCommercialControl slot={slot} buyers={buyers} endLocations={endLocations} onSave={payload=>patchTrip(slot.tripId,payload)}/>}
    </div>)}</details>}
  </div>
}

function VehicleBoard({day,board,allBoards,vehicles,employees,assignVehicle,transferVehicle}){
  const update=(body)=>assignVehicle(day.dispatch_date,board.id,body)
  const recommended=board.preferredAreas?.filter(area=>board.areas.includes(area))||[]
  return <article id={`dispatch-${day.id}-vehicle-${board.id}`} className="vehicle-board"><header><div><strong>{vehicleLabel(board)}</strong><small>{board.capacityKg?`${board.capacityKg} kg`:'Capacity not set'} · Base {board.defaultBase||'Not set'} · {board.customerCount} Stops · {board.weightedStopCount?`${board.estimatedWeightKg} kg estimated`:'weight not set'}{board.missingWeightCount?` · ${board.missingWeightCount} missing weight`:''}{board.overCapacity?<b className="route-warning"> · Over capacity</b>:''}</small></div><span>{board.areas.length?board.areas.join(', '):'Unassigned Area'}{recommended.length?` · recommendation match ${recommended.join(', ')}`:''}{board.customerCount>0&&<button className="transfer-vehicle" onClick={()=>transferVehicle(day.dispatch_date,board.id,vehicles)}>Transfer entire vehicle plan</button>}</span></header><div className="vehicle-crew"><DriverPicker board={board} allBoards={allBoards} employees={employees} onChange={driverId=>update({driverId})}/><AssistantPicker board={board} employees={employees} onChange={assistantIds=>update({assistantIds})}/></div></article>
}

function TripCommercialControl({slot,buyers,endLocations,onSave}){
  const[buyerId,setBuyerId]=useState(slot.buyerReferenceId?String(slot.buyerReferenceId):''),[endId,setEndId]=useState(slot.endLocationReferenceId?String(slot.endLocationReferenceId):''),[reason,setReason]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const ordered=useMemo(()=>[...endLocations].sort((a,b)=>Number(b.buyerReferenceId===Number(buyerId))-Number(a.buyerReferenceId===Number(buyerId))||a.locationName.localeCompare(b.locationName)),[endLocations,buyerId])
  const save=async()=>{if(!reason.trim()){setError('Change Reason is required');return}setSaving(true);setError('');try{await onSave({buyerPayer:buyerId?{referenceId:Number(buyerId)}:null,primaryEndLocation:endId?{referenceId:Number(endId)}:null,reason:reason.trim()});setReason('')}catch(e){setError(e.message)}finally{setSaving(false)}}
  return <div className="trip-commercial"><label>Buyer / Payer<select aria-label={`Trip ${slot.tripNumber} Buyer / Payer`} value={buyerId} onChange={event=>setBuyerId(event.target.value)}><option value="">Not selected</option>{buyers.map(item=><option key={item.id} value={item.id}>{item.buyerCode} — {item.buyerName}</option>)}</select></label><label>Primary End Location<select aria-label={`Trip ${slot.tripNumber} Primary End Location`} value={endId} onChange={event=>setEndId(event.target.value)}><option value="">Not selected</option>{ordered.map(item=><option key={item.id} value={item.id}>{item.buyerReferenceId===Number(buyerId)?'Recommended · ':''}{item.parentName?`${item.parentName} — `:''}{item.locationName} · GPS Set</option>)}</select></label>{endId&&<small>{ordered.find(item=>String(item.id)===endId)?.address||'Address not set'}</small>}<label>Change Reason<input value={reason} onChange={event=>setReason(event.target.value)}/></label>{error&&<small className="data-error">{error}</small>}<button type="button" disabled={saving} onClick={save}>{saving?'Saving…':'Save Buyer & End Location'}</button></div>
}

function StartLocationControl({slot,driverId,onSave}){
  const[open,setOpen]=useState(false),[options,setOptions]=useState(null),[type,setType]=useState(slot.startLocationType||'factory'),[saved,setSaved]=useState(''),[custom,setCustom]=useState({name:'',address:'',latitude:'',longitude:'',gpsSource:''}),[reason,setReason]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false)
  const show=async()=>{setOpen(true);setError('');try{setOptions(await request(`/api/dispatch/start-location-options${driverId?`?driverId=${driverId}`:''}`))}catch(reason){setError(reason.message)}}
  const submit=async()=>{if(!reason.trim()){setError('Change Reason is required');return}let startLocation={type};if(type==='employee_home')startLocation={type,referenceId:driverId};if(type==='saved_location'){const[referenceType,referenceId]=saved.split(':');startLocation={type,referenceType,referenceId:Number(referenceId)}}if(type==='custom')startLocation={type,...custom};setSaving(true);setError('');try{await onSave({startLocation,reason:`${reason.trim()}${custom.gpsSource?` · GPS source: ${custom.gpsSource}`:''}`});setOpen(false)}catch(reasonError){setError(reasonError.message)}finally{setSaving(false)}}
  return <div className="trip-start-location"><button type="button" className="start-location-trigger" onClick={show}><b>Start Location</b><span>{slot.startLocationName||'Factory not set'}</span></button>{open&&<div className="start-location-dialog" role="dialog" aria-modal="true" aria-label="Start Location"><div><header><h3>Start Location · Trip {slot.tripNumber}</h3><button type="button" onClick={()=>setOpen(false)}>×</button></header><label>Type<select value={type} onChange={event=>setType(event.target.value)}><option value="factory">Factory</option><option value="employee_home">Employee Home</option><option value="saved_location">Saved Location</option><option value="custom">Custom Location</option></select></label>{type==='factory'&&<p>{options?.factory?`Factory — ${options.factory.startLocationName} · GPS Set`:'Company Yard GPS is not set'}</p>}{type==='employee_home'&&<p>{options?.employeeHome?.startLocationName?`${options.employeeHome.startLocationName} · Home GPS Set`:(options?.employeeHome?.message||'Select a Driver')}</p>}{type==='saved_location'&&<label>Saved Location<select value={saved} onChange={event=>setSaved(event.target.value)}><option value="">Select a GPS-enabled location</option>{(options?.savedLocations||[]).map(item=><option key={`${item.startLocationReferenceType}:${item.startLocationReferenceId}`} value={`${item.startLocationReferenceType}:${item.startLocationReferenceId}`}>{item.startLocationName}</option>)}</select></label>}{type==='custom'&&<><label>Name<input value={custom.name} onChange={event=>setCustom(value=>({...value,name:event.target.value}))}/></label><label>Address<textarea value={custom.address} onChange={event=>setCustom(value=>({...value,address:event.target.value}))}/></label><SharedGpsInput resetKey={`dispatch-start:${slot.id||slot.dispatchId||slot.tripNumber}`} latitude={custom.latitude} longitude={custom.longitude} address={custom.address} gpsSource={custom.gpsSource} onChange={change=>setCustom(value=>({...value,latitude:change.latitude,longitude:change.longitude,address:change.address??value.address,gpsSource:change.gpsSource}))}/></>}<label>Change Reason<input value={reason} onChange={event=>setReason(event.target.value)}/></label>{error&&<p className="data-error">{error}</p>}<FormActionBar><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button type="button" className="primary" disabled={saving} onClick={submit}>{saving?'Saving…':'Save Start Location'}</button></FormActionBar></div></div>}</div>
}

function DriverPicker({board,allBoards,employees,onChange}){
  const[open,setOpen]=useState(false),[search,setSearch]=useState('')
  const close=useCallback(()=>setOpen(false),[]),rootRef=useOutsideClose(open,close)
  const drivers=useMemo(()=>employees.filter(item=>(['driver','supervisor'].includes(String(item.role||'').toLowerCase())||item.additionalRoles?.includes('Driver'))&&`${item.name} ${item.employeeCode||''}`.toLowerCase().includes(search.toLowerCase())),[employees,search])
  return <div className="resource-picker" ref={rootRef}><button className={`picker-trigger ${!board.driverId?'missing':''}`} onClick={()=>setOpen(!open)}>{board.driver||'Unassigned driver'} ▾</button>{open&&<div className="picker-panel employee-picker-panel"><input autoFocus placeholder="Search driver name or employee number" value={search} onChange={event=>setSearch(event.target.value)}/>{board.driverId&&<button className="release-assignment" onClick={()=>{onChange(null);setOpen(false)}}>Release current driver assignment</button>}<div>{drivers.map(item=>{const other=allBoards.find(vehicle=>vehicle.id!==board.id&&vehicle.driverId===item.id),disabled=!usableEmployee(item)||Boolean(other);return <button key={item.id} disabled={disabled} onClick={()=>{onChange(item.id);setOpen(false)}}><strong>{item.name} · {item.employeeCode||'No employee code'}</strong><small>{employmentStatus[item.employmentStatus]||item.employmentStatus} · Base {item.defaultBase||'Not set'} · Area {item.defaultArea||'Not set'}</small><small>{other?`Assigned today: ${vehicleLabel(other)}`:'Not assigned to another vehicle today'}{!usableEmployee(item)?' · Unavailable':''}</small></button>})}{drivers.length===0&&<p>Employee Master No  Driver</p>}</div></div>}</div>
}

function AssistantPicker({board,employees,onChange}){
  const[open,setOpen]=useState(false),[search,setSearch]=useState(''),[selected,setSelected]=useState(board.assistantIds)
  const close=useCallback(()=>setOpen(false),[]),rootRef=useOutsideClose(open,close)
  useEffect(()=>{setSelected(board.assistantIds)},[board.assistantIds])
  const crew=useMemo(()=>employees.filter(item=>(['assistant','crew','attendant / crew'].includes(String(item.role||'').toLowerCase())||item.additionalRoles?.includes('Attendant / Crew'))&&`${item.name} ${item.employeeCode||''}`.toLowerCase().includes(search.toLowerCase())),[employees,search])
  const toggle=(id)=>{const next=selected.includes(id)?selected.filter(item=>item!==id):selected.length<MAX_ASSIGNED_CREW?[...selected,id]:selected;if(next===selected)return;setSelected(next);onChange(next)}
  return <div className="resource-picker" ref={rootRef}><button className={`picker-trigger ${!selected.length?'missing':''}`} onClick={()=>setOpen(!open)}>{board.assistants.length?board.assistants.map(item=>item.name).join(', '):'Unassigned crew'} · {selected.length}/{MAX_ASSIGNED_CREW} ▾</button>{open&&<div className="picker-panel employee-picker-panel"><input autoFocus placeholder="Search crew name or employee number" value={search} onChange={event=>setSearch(event.target.value)}/><div>{crew.map(item=>{const checked=selected.includes(item.id),limitReached=!checked&&selected.length>=MAX_ASSIGNED_CREW,disabled=!usableEmployee(item)||limitReached;return <button key={item.id} disabled={disabled} onClick={()=>toggle(item.id)}><strong>{checked?'☑':'☐'} {item.name} · {item.employeeCode||'No employee code'}</strong><small>{item.role} · {employmentStatus[item.employmentStatus]||item.employmentStatus} · Base {item.defaultBase||'Not set'} · Area {item.defaultArea||'Not set'}{!usableEmployee(item)?' · Unavailable':limitReached?' · Maximum 2 crew selected':''}</small></button>})}{crew.length===0&&<p>Employee Master No  Assistant/Crew</p>}</div></div>}</div>
}

function StopCard({stop,patchStop,day,board,targetBoards=[],moveStop,canEditDispatch=false}){
  const gps=Number.isFinite(stop.latitude)&&Number.isFinite(stop.longitude)&&stop.latitude!==0&&stop.longitude!==0,[target,setTarget]=useState('')
  const targets=targetBoards.filter(item=>item.id!==board?.id)
  return <div className={`route-stop ${stop.sequenceLocked?'sequence-locked':''}`} draggable={!stop.sequenceLocked&&day?.status==='draft'&&canEditDispatch} onDragStart={event=>event.dataTransfer.setData('text/stop-id',String(stop.id))}><i>{stop.stopSequence}</i><span><b>{formatBranchId(stop.branchId)} — {stop.branchName||'Unnamed branch'}</b><small>{formatCustomerId(stop.customerId)} — {stop.customerName||'Unmatched customer'} · {stop.area||'Unassigned area'} · {stop.estimatedWeightKg!=null?`${stop.estimatedWeightKg} kg`:'Weight not set'} · {gps?'GPS✓':'GPS missing'}</small>{stop.timeRestriction&&<small className="route-warning">Time restriction: {stop.timeRestriction}</small>}</span>{canEditDispatch&&board&&<div className="stop-actions"><select aria-label={`Move ${stop.branchName} to another vehicle`} value={target} disabled={day.status!=='draft'} onChange={event=>setTarget(event.target.value)}><option value="">移到其他车辆</option>{targets.map(item=><option key={item.id} value={item.id}>{item.vehicle} · {item.registrationNumber||'No plate'}</option>)}</select><button type="button" disabled={day.status!=='draft'||!target} title={day.status!=='draft'?'Withdraw Approval first':'Move this route stop'} onClick={()=>{moveStop(day,stop,Number(target));setTarget('')}}>Move</button></div>}<button title="Lock sequence" onClick={()=>patchStop(stop.id,{sequenceLocked:!stop.sequenceLocked})}>{stop.sequenceLocked?'🔒':'○'}</button></div>
}
