import {useCallback,useEffect,useState} from 'react'
import {apiRequest} from './apiClient.js'
import {useI18n} from './i18n.jsx'
import {kuchingDate} from '../shared/kuchingTime.js'
import OutsideCloseDetails from './OutsideCloseDetails.jsx'
import './WorkClose.css'
const words={
 zh:{title:'申请结束今日工作',queue:'结束工作申请',hint:'一次提交本行程全部区域的未完成客户。主管安排改期或转车并批准后，才会结束行程。',reason:'原因（必填）',send:'提交申请',refresh:'刷新',pending:'已申请，等待主管处理',approved:'主管已批准结束',rejected:'申请已退回',protected:'以下客户须先处理原记录',proof:'缺现金付款凭证',bill:'已有单据，请完成本站',work:'已有收货或凭证记录，请先处理',approval:'另有待审批申请',inactive:'客户未启用，请主管核对',remaining:'尚未收货客户',empty:'没有未完成客户',review:'审核／统一安排',date:'改至日期（仅本次）',route:'路线',transfer:'转给其他车辆',reschedule:'改期',all:'统一应用至尚未收货客户',target:'接收车辆／司机',choose:'请选择',approve:'安排客户并批准结束',reject:'退回申请',saved:'已保存处理结果',failed:'未能完成，请刷新并检查客户记录、目标路线或车辆；原申请与记录仍保留。',stale:'记录已变化，请刷新并重新核对安排。',required:'请填写原因。',blocked:'先完成有单据／收货记录的客户，并处理其他待审批申请，再刷新审核。',dateError:'请选择今天之后的日期。',targetError:'接收车辆必须是今天正在执行的其他行程。',notice:'未收货客户不会计为已收货。固定收货周期不变；行程结束也不会补写客户到达或收货时间。',load:'正在读取…',trip:'行程',apply:'统一安排',changed:'刷新会重新载入客户清单，请核对后再批准。'},
 en:{title:'Request to finish today’s work',queue:'Finish-work requests',hint:'Submit all unfinished customers across this trip’s areas once. The trip ends after management arranges rescheduling or another vehicle and approves.',reason:'Reason (required)',send:'Submit request',refresh:'Refresh',pending:'Requested — awaiting management',approved:'Management approved completion',rejected:'Request rejected',protected:'Resolve these original records first',proof:'Cash payment proof missing',bill:'Bill exists — complete this stop',work:'Collection or evidence exists — resolve first',approval:'Another approval is pending',inactive:'Inactive customer — management review needed',remaining:'Customers not yet collected',empty:'No unfinished customers',review:'Review / arrange together',date:'Move to date (once only)',route:'Route',transfer:'Transfer to another vehicle',reschedule:'Reschedule',all:'Apply to all untouched customers',target:'Receiving vehicle / driver',choose:'Please select',approve:'Arrange customers and approve completion',reject:'Reject request',saved:'Decision saved',failed:'Unable to finish. Refresh and review customer records, target route or vehicle. The request and records are retained.',stale:'Records changed. Refresh and review the arrangements again.',required:'Enter a reason.',blocked:'Finish customers with bills or collection records and resolve other pending approvals, then refresh this review.',dateError:'Choose a date after today.',targetError:'Choose another running trip for today.',notice:'Uncollected customers are not counted as collected. Fixed recurrence is unchanged. Ending the trip does not create customer arrival or collection times.',load:'Loading…',trip:'Trip',apply:'Arrange together',changed:'Refresh reloads the customer list. Check the arrangements before approving.'},
 ms:{title:'Mohon tamat kerja hari ini',queue:'Permohonan tamat kerja',hint:'Hantar semua pelanggan belum selesai dari semua kawasan perjalanan ini sekali. Perjalanan tamat selepas pihak pengurusan mengatur tarikh atau kenderaan lain dan meluluskan.',reason:'Sebab (wajib)',send:'Hantar permohonan',refresh:'Muat semula',pending:'Telah dimohon — menunggu pengurusan',approved:'Pengurusan meluluskan tamat perjalanan',rejected:'Permohonan ditolak',protected:'Selesaikan rekod asal ini dahulu',proof:'Bukti bayaran tunai belum dimuat naik',bill:'Bil sudah ada — selesaikan hentian ini',work:'Rekod kutipan atau bukti sudah ada — uruskan dahulu',approval:'Permohonan lain menunggu kelulusan',inactive:'Pelanggan tidak aktif — perlu semakan pengurusan',remaining:'Pelanggan belum dikutip',empty:'Tiada pelanggan belum selesai',review:'Semak / atur bersama',date:'Pindah ke tarikh (sekali sahaja)',route:'Laluan',transfer:'Pindah ke kenderaan lain',reschedule:'Tukar tarikh',all:'Gunakan untuk semua pelanggan belum dikutip',target:'Kenderaan / pemandu penerima',choose:'Sila pilih',approve:'Atur pelanggan dan luluskan tamat',reject:'Tolak permohonan',saved:'Keputusan disimpan',failed:'Tidak dapat diselesaikan. Muat semula dan semak rekod pelanggan, laluan atau kenderaan sasaran. Permohonan dan rekod dikekalkan.',stale:'Rekod berubah. Muat semula dan semak aturan lagi.',required:'Isi sebab.',blocked:'Selesaikan pelanggan yang mempunyai bil atau rekod kutipan serta kelulusan lain, kemudian muat semula.',dateError:'Pilih tarikh selepas hari ini.',targetError:'Pilih perjalanan lain yang sedang berjalan hari ini.',notice:'Pelanggan belum dikutip tidak dikira sebagai telah dikutip. Jadual tetap tidak berubah. Tamat perjalanan tidak mencipta waktu ketibaan atau kutipan pelanggan.',load:'Memuatkan…',trip:'Perjalanan',apply:'Atur bersama',changed:'Muat semula senarai pelanggan. Semak aturan sebelum meluluskan.'}}
const tomorrow=()=>{const d=new Date(kuchingDate()+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}
const errorText=(e,w)=>({WORK_CLOSE_STALE:w.stale,WORK_CLOSE_REASON:w.required,WORK_CLOSE_PROTECTED:w.blocked,WORK_CLOSE_DATE:w.dateError,WORK_CLOSE_TARGET:w.targetError}[e.code]||(e.code?.startsWith('WORK_CLOSE_')?w.failed:e.message||w.failed))
function StopList({rows,w}){return rows.map(s=><p key={s.id}><b data-i18n-raw>{s.branchCode} · {s.name}</b>{s.issue&&<> — {w[s.issue]}</>}</p>)}
export function WorkCloseRequest({tripId,onSaved}){
 const{language}=useI18n(),w=words[language]||words.en,[data,setData]=useState(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=async()=>{setBusy(true);try{setData(await apiRequest(`/api/mobile/trips/${tripId}/work-close`));setError('')}catch(e){setError(errorText(e,w))}finally{setBusy(false)}}
 const submit=async e=>{e.preventDefault();setBusy(true);try{await apiRequest(`/api/mobile/trips/${tripId}/work-close`,{method:'POST',body:JSON.stringify({reason,version:data.version})});setReason('');await load();onSaved?.()}catch(e){setError(errorText(e,w))}finally{setBusy(false)}}
 return <OutsideCloseDetails className="work-close" busy={busy} dirty={!!reason} onToggle={e=>{if(e.currentTarget.open&&!data&&!busy)void load()}}><summary>{w.title}</summary><p>{w.hint}</p>{error&&<p role="alert">{error}</p>}<button type="button" disabled={busy} onClick={load}>{w.refresh}</button>{!data?<p>{w.load}</p>:<>{data.request&&<p role="status">{w[data.request.status]}{data.request.reviewReason&&<> · <span data-i18n-raw>{data.request.reviewReason}</span></>}</p>}<h4>{w.remaining} ({data.stops.filter(s=>s.canArrange).length})</h4><StopList rows={data.stops.filter(s=>s.canArrange)} w={w}/>{data.stops.some(s=>!s.canArrange)&&<><h4>{w.protected}</h4><StopList rows={data.stops.filter(s=>!s.canArrange)} w={w}/></>}{data.tripStatus==='in_progress'&&data.request?.status!=='pending'&&<form onSubmit={submit}><label>{w.reason}<textarea required maxLength={500} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()}>{w.send}</button></form>}</>}</OutsideCloseDetails>
}
function Review({item,targets,onSaved,w}){
 const[data,setData]=useState(item),[date,setDate]=useState(tomorrow),[routes,setRoutes]=useState([]),[actions,setActions]=useState({}),[kind,setKind]=useState('reschedule'),[target,setTarget]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let alive=true;setRoutes([]);apiRequest('/api/dispatch/date-requests/options?date='+date).then(r=>{if(alive)setRoutes(r.routes||[])}).catch(()=>{});return()=>{alive=false}},[date])
 const eligible=data.stops.filter(s=>s.canArrange),blocked=data.stops.some(s=>!s.canArrange),choices=targets.filter(t=>t.tripId!==data.tripId)
 const action=s=>actions[s.id]||{kind:'reschedule',routeNumber:s.routeNumber||'',tripId:''}
 const change=(s,patch)=>setActions(a=>({...a,[s.id]:{...action(s),...patch}}))
 const valid=eligible.every(s=>{const a=action(s);return a.kind==='reschedule'?date>kuchingDate()&&routes.some(r=>r.routeNumber===Number(a.routeNumber)):data.date===kuchingDate()&&choices.some(t=>t.tripId===Number(a.tripId))})
 const reload=async()=>{setBusy(true);try{const result=await apiRequest('/api/dispatch/work-close');const current=result.items.find(r=>r.id===item.id);if(current){setData(current);setError('')}else onSaved();}catch(e){setError(errorText(e,w))}finally{setBusy(false)}}
 const decide=async decision=>{setBusy(true);setError('');try{await apiRequest('/api/dispatch/work-close/'+data.id,{method:'POST',body:JSON.stringify({decision,reason,version:data.version,actions:eligible.map(s=>({...action(s),stopId:s.id,targetDate:date}))})});onSaved()}catch(e){setError(errorText(e,w))}finally{setBusy(false)}}
 return <OutsideCloseDetails className="work-close" busy={busy} dirty={!!reason||Object.keys(actions).length>0}><summary>{w.review}</summary><p>{w.notice}</p><button type="button" disabled={busy} onClick={reload}>{w.refresh}</button><small>{w.changed}</small>{blocked&&<><h4>{w.protected}</h4><StopList rows={data.stops.filter(s=>!s.canArrange)} w={w}/><p>{w.blocked}</p></>}
 {eligible.length>0&&<><div className="work-close-fields"><label>{w.date}<input type="date" min={tomorrow()} value={date} disabled={busy} onChange={e=>setDate(e.target.value)}/></label><label>{w.apply}<select disabled={busy} value={kind} onChange={e=>setKind(e.target.value)}><option value="reschedule">{w.reschedule}</option><option value="transfer">{w.transfer}</option></select></label>{kind==='transfer'&&<label>{w.target}<select value={target} disabled={busy} onChange={e=>setTarget(e.target.value)}><option value="">{w.choose}</option>{choices.map(t=><option key={t.tripId} value={t.tripId}>{t.plate} · {t.driverName}</option>)}</select></label>}<button type="button" disabled={busy} onClick={()=>setActions(Object.fromEntries(eligible.map(s=>[s.id,{...action(s),kind,tripId:target}])))}>{w.all}</button></div><h4>{w.remaining} ({eligible.length})</h4>{eligible.map(s=>{const a=action(s);return <div className="work-close-row" key={s.id}><b data-i18n-raw>{s.branchCode} · {s.name}</b><label>{w.apply}<select disabled={busy} value={a.kind} onChange={e=>change(s,{kind:e.target.value})}><option value="reschedule">{w.reschedule}</option><option value="transfer">{w.transfer}</option></select></label>{a.kind==='reschedule'?<label>{w.route}<select disabled={busy} value={a.routeNumber} onChange={e=>change(s,{routeNumber:Number(e.target.value)})}><option value="">{w.choose}</option>{routes.map(r=><option key={r.routeNumber} value={r.routeNumber}>{r.name}</option>)}</select></label>:<label>{w.target}<select disabled={busy} value={a.tripId} onChange={e=>change(s,{tripId:Number(e.target.value)})}><option value="">{w.choose}</option>{choices.map(t=><option key={t.tripId} value={t.tripId}>{t.plate} · {t.driverName}</option>)}</select></label>}</div>})}</>}
 {!data.stops.length&&<p>{w.empty}</p>}<label>{w.reason}<textarea maxLength={500} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button type="button" disabled={busy||!reason.trim()||blocked||!valid} onClick={()=>decide('approved')}>{w.approve}</button><button type="button" disabled={busy||!reason.trim()} onClick={()=>decide('rejected')}>{w.reject}</button></OutsideCloseDetails>
}
export function WorkCloseApprovals({onSaved}){
 const{language}=useI18n(),w=words[language]||words.en,[data,setData]=useState({items:[],targets:[]}),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=useCallback(async()=>{try{setData(await apiRequest('/api/dispatch/work-close'));setError('')}catch{setError('failed')}},[])
 useEffect(()=>{void load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[load])
 const saved=()=>{setMessage(w.saved);void load();onSaved?.()}
 if(!data.items.length&&!error&&!message)return null
 return <section className="dashboard-approvals work-close"><h3>{w.queue} ({data.items.length})</h3>{error&&<p role="alert">{w[error]}</p>}{message&&<p role="status">{message}</p>}{data.items.map(r=><article key={r.id}><h4 data-i18n-raw>{r.driverName} · {r.plate}</h4><p>{r.date} · {w.trip} #{r.tripId}</p><p data-i18n-raw>{r.reason}</p><Review item={r} targets={data.targets} onSaved={saved} w={w}/></article>)}</section>
}
