import { useEffect, useMemo, useState } from 'react'
import './ZoneGroupManager.css'
import {apiRequest} from './apiClient.js'
import {useI18n} from './i18n.jsx'
import {validateZoneRename} from './zoneRenameValidation.js'
import {formatBranchId,formatCustomerId} from '../shared/typedIds.js'

const request=url=>apiRequest(url)
const gpsText=branch=>Number.isFinite(branch.latitude)&&Number.isFinite(branch.longitude)&&!(branch.latitude===0&&branch.longitude===0)?`${branch.latitude}, ${branch.longitude}`:'Missing official  GPS'

function ZoneRenameModal({group,name,error,saving,onNameChange,onCancel,onSave}){
  const{t}=useI18n()
  if(!group)return null
  const submit=event=>{event.preventDefault();const validationError=validateZoneRename(name,t);onSave(validationError?'':name.trim(),validationError)}
  return <div className="zone-rename-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&!saving&&onCancel()}>
    <section className="zone-rename-modal" role="dialog" aria-modal="true" aria-labelledby="zone-rename-title">
      <form onSubmit={submit} noValidate>
        <header><div><small>{t('zone.renameDialog')}</small><h3 id="zone-rename-title">{t('zone.renameTitle')}</h3></div><button type="button" aria-label={t('common.close')} title={t('common.close')} disabled={saving} onClick={onCancel}>×</button></header>
        <dl><dt>{t('zone.currentName')}</dt><dd data-i18n-raw>{group.name}</dd></dl>
        <label>{t('zone.newName')}<input autoFocus value={name} onInput={event=>onNameChange(event.currentTarget.value)} onChange={event=>onNameChange(event.target.value)} aria-invalid={Boolean(error)} aria-describedby={error?'zone-rename-error':'zone-rename-help'} placeholder={t('zone.newName')} disabled={saving}/></label>
        <p id="zone-rename-help" className="hint">{t('zone.renameHelp')}</p>
        {error&&<p id="zone-rename-error" className="detail-error" role="alert">{error}</p>}
        <footer><button type="button" disabled={saving} onClick={onCancel}>{t('common.cancel')}</button><button type="submit" disabled={saving}>{saving?t('common.saving'):t('zone.renameSave')}</button></footer>
      </form>
    </section>
  </div>
}

export default function ZoneGroupManager({groups,areas,vehicles,save,currentUser,pageError}){
  const{t}=useI18n()
  const canManageAreas=['owner_admin','operations_admin','supervisor'].includes(currentUser.systemRole)||currentUser.permissions?.includes('schedule_manage')
  const[form,setForm]=useState({name:'',code:'',sortOrder:''}),[search,setSearch]=useState(''),[selected,setSelected]=useState([]),[status,setStatus]=useState('pending'),[zoneFilter,setZoneFilter]=useState('all'),[gpsFilter,setGpsFilter]=useState('all'),[sort,setSort]=useState('name'),[detailId,setDetailId]=useState(null),[detail,setDetail]=useState(null),[detailError,setDetailError]=useState(''),[bulkZone,setBulkZone]=useState(''),[metricDetail,setMetricDetail]=useState(null),[metricVersion,setMetricVersion]=useState(0)
  const[renameTarget,setRenameTarget]=useState(null),[renameName,setRenameName]=useState(''),[renameError,setRenameError]=useState(''),[renameSaving,setRenameSaving]=useState(false),[showCreate,setShowCreate]=useState(false)
  const[moveBusy,setMoveBusy]=useState(false),[moveError,setMoveError]=useState(''),[moveSuccess,setMoveSuccess]=useState(''),[moveAttempted,setMoveAttempted]=useState(false)
  useEffect(()=>{if(!detailId){setDetail(null);return}setDetail(null);setDetailError('');request(`/api/areas/${detailId}/zone-confirmation`).then(setDetail).catch(error=>setDetailError(error.message))},[detailId,areas])
  const filtered=useMemo(()=>areas.filter(area=>{
    const matchesSearch=`${area.name} ${area.areaId||''} ${area.zoneGroup}`.toLowerCase().includes(search.toLowerCase())
    const matchesStatus=status==='all'||(status==='pending'&&area.zoneAssignmentStatus!=='confirmed')||(status==='confirmed'&&area.zoneAssignmentStatus==='confirmed')
    const matchesZone=zoneFilter==='all'||area.zoneGroupId===Number(zoneFilter)
    const matchesGps=gpsFilter==='all'||(gpsFilter==='with'&&area.gpsBranchCount>0)||(gpsFilter==='missing'&&area.gpsBranchCount<area.branchCount)
    return matchesSearch&&matchesStatus&&matchesZone&&matchesGps
  }).sort((a,b)=>sort==='customers_desc'?b.customerCount-a.customerCount:sort==='customers_asc'?a.customerCount-b.customerCount:a.name.localeCompare(b.name)),[areas,search,status,zoneFilter,gpsFilter,sort])
  const create=async event=>{event.preventDefault();if(!form.name.trim())return;const ok=await save('/api/zone-groups','POST',{...form,sortOrder:form.sortOrder?Number(form.sortOrder):undefined});if(ok){setForm({name:'',code:'',sortOrder:''});setShowCreate(false)}}
  useEffect(()=>{if(renameTarget&&pageError)setRenameError(pageError)},[pageError,renameTarget])
  const openRename=group=>{setRenameTarget(group);setRenameName(group.name);setRenameError('')}
  const closeRename=()=>{if(renameSaving)return;setRenameTarget(null);setRenameName('');setRenameError('')}
  const submitRename=async(name,validationError)=>{
    if(validationError){setRenameError(validationError);return}
    if(name===renameTarget?.name){closeRename();return}
    setRenameError('');setRenameSaving(true)
    const ok=await save(`/api/zone-groups/${renameTarget.id}`,'PATCH',{name,successMessage:t('zone.renameSuccess')})
    setRenameSaving(false)
    if(ok)closeRename();else setRenameError(current=>current||t('common.operationFailed'))
  }
  const merge=group=>{const choices=groups.filter(item=>item.id!==group.id&&item.isActive).map(item=>`${item.id}: ${item.name}`).join('\n'),targetZoneId=Number(prompt(`Move  ${group.name} Merge into which  Zone？\n${choices}`,'')||0);if(targetZoneId&&confirm(`Confirm moving all Area and deactivate ${group.name}？Moved  Area remain pending confirmation, history snapshots remain unchanged.`))save('/api/zone-groups/merge','POST',{sourceZoneIds:[group.id],targetZoneId})}
  const split=group=>{const areaIds=selected.filter(id=>areas.find(area=>area.id===id)?.zoneGroupId===group.id);if(!areaIds.length){alert('First select the  Zone, items to split Area.');return}const name=prompt('New  Zone Group Name','');if(name)save('/api/zone-groups/split','POST',{sourceZoneId:group.id,name,areaIds})}
  const toggle=id=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])
  const selectVisible=()=>setSelected(current=>[...new Set([...current,...filtered.map(area=>area.id)])])
  useEffect(()=>{if(moveAttempted&&pageError)setMoveError(pageError)},[pageError,moveAttempted])
  const move=async(areaIds,zoneGroupId,reason='Zone Area Confirmation adjustment')=>{
    setMoveAttempted(true);setMoveError('');setMoveSuccess('')
    if(!areaIds.length){setMoveError('Select at least one Area.');return false}
    if(!zoneGroupId){setMoveError('Select a target Zone Group.');return false}
    const targetId=Number(zoneGroupId),selectedAreas=areaIds.map(id=>areas.find(area=>area.id===id)).filter(Boolean)
    if(selectedAreas.some(area=>area.zoneGroupId===targetId)){setMoveError('The target Zone Group must be different from every selected Area current Zone Group.');return false}
    setMoveBusy(true)
    try{
      const ok=await save('/api/areas/bulk-zone-group','POST',{areaIds,zoneGroupId:targetId,reason,successMessage:`Moved ${areaIds.length} Area; assignment adjusted, awaiting Supervisor confirmation.`})
      if(ok){setSelected([]);setBulkZone('');setMoveSuccess(`Successfully moved ${areaIds.length} Area${areaIds.length===1?'':'s'}; assignment adjusted, awaiting Supervisor confirmation.`)}
      else setMoveError(current=>current||'The Areas could not be moved. No Areas were changed.')
      return ok
    }finally{setMoveBusy(false)}
  }
  const confirmAreas=async(areaIds,confirmed)=>{
    setMoveError('');setMoveSuccess('')
    if(!areaIds.length){setMoveError('Select at least one Area.');return false}
    const ok=await save('/api/areas/bulk-confirmation','POST',{areaIds,confirmed,successMessage:`${areaIds.length} Area assignment${areaIds.length===1?'':'s'} ${confirmed?'confirmed':'returned to pending confirmation'}.`})
    if(ok){setSelected([]);setMoveSuccess(`${areaIds.length} Area assignment${areaIds.length===1?'':'s'} ${confirmed?'confirmed':'returned to pending confirmation'}.`)}
    else setMoveError('The Area confirmation could not be changed. No Areas were changed.')
    return ok
  }
  const confirmMetricArea=async id=>{const ok=await confirmAreas([id],true);if(ok)setMetricVersion(value=>value+1);return ok}
  const moveMetricAreas=async(areaIds,zoneGroupId,reason)=>{const ok=await move(areaIds,zoneGroupId,reason);if(ok)setMetricVersion(value=>value+1);return ok}
  return <section className="master-section zone-manager"><header><div><h2>Zone Group Management</h2><p>Zone Groups and Area assignment confirmation are managed separately.</p></div><button className="primary" onClick={()=>setShowCreate(true)}>＋ Add Zone Group</button></header>
    {showCreate&&<div className="zone-rename-backdrop"><section className="zone-rename-modal" role="dialog" aria-modal="true"><form onSubmit={create}><header><h3>Add Zone Group</h3><button type="button" onClick={()=>setShowCreate(false)}>×</button></header><label>Zone Group Name<input autoFocus required value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Code (optional)<input placeholder="Auto-generated when empty" value={form.code} onChange={event=>setForm({...form,code:event.target.value})}/></label><label>Display Order (optional)<input type="number" placeholder="Placed last when empty" value={form.sortOrder} onChange={event=>setForm({...form,sortOrder:event.target.value})}/></label><footer><button type="button" onClick={()=>setShowCreate(false)}>Cancel</button><button>Save</button></footer></form></section></div>}
    <div className="zone-summary dynamic-zones">{groups.map(group=><article key={group.id} className={group.isActive?'':'inactive-zone'}><strong data-i18n-raw>{group.name}</strong><small data-i18n-raw>{group.code}</small><div className="zone-card-metrics"><MetricButton value={group.areaCount} label="Total Areas" onClick={()=>setMetricDetail({zoneId:group.id,zoneName:group.name,metric:'areas'})}/><MetricButton value={group.confirmedAreaCount} label="Confirmed" onClick={()=>setMetricDetail({zoneId:group.id,zoneName:group.name,metric:'confirmed'})}/><MetricButton value={group.pendingAreaCount} label="Pending confirmation" onClick={()=>setMetricDetail({zoneId:group.id,zoneName:group.name,metric:'pending'})}/><MetricButton value={group.branchCount} label="Customer Branch" onClick={()=>setMetricDetail({zoneId:group.id,zoneName:group.name,metric:'branches'})}/><MetricButton value={group.gpsBranchCount} label="Official GPS" onClick={()=>setMetricDetail({zoneId:group.id,zoneName:group.name,metric:'official_gps'})}/><MetricButton value={group.missingGpsBranchCount} label="Missing GPS" onClick={()=>setMetricDetail({zoneId:group.id,zoneName:group.name,metric:'missing_gps'})}/><MetricButton value={group.scheduledBranchCount??group.scheduledCustomerCount} label="Scheduled customers" onClick={()=>setMetricDetail({zoneId:group.id,zoneName:group.name,metric:'scheduled'})}/></div><label>Order <input type="number" defaultValue={group.sortOrder} onBlur={event=>{const sortOrder=Number(event.target.value);if(sortOrder!==group.sortOrder)save(`/api/zone-groups/${group.id}`,'PATCH',{sortOrder})}}/></label><div className="zone-card-actions"><button onClick={()=>openRename(group)}>{t('common.rename')}</button><button onClick={()=>save(`/api/zone-groups/${group.id}/${group.isActive?'deactivate':'reactivate'}`,'POST',{})}>{group.isActive?'Deactivate':'Reactivate'}</button><button disabled={!group.isActive} onClick={()=>merge(group)}>Merge</button><button disabled={!group.isActive} onClick={()=>split(group)}>Split selected Areas</button></div><ZoneDefaultVehicles group={group} vehicles={vehicles} canManage={canManageAreas} save={save}/></article>)}</div>
    <div className="zone-area-filters"><input placeholder="Search Area / AreaID / Zone" value={search} onChange={event=>setSearch(event.target.value)}/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="pending">Pending confirmation</option><option value="confirmed">Confirmed</option><option value="all">All</option></select><select value={zoneFilter} onChange={event=>setZoneFilter(event.target.value)}><option value="all">All Zones</option>{groups.map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select><select value={gpsFilter} onChange={event=>setGpsFilter(event.target.value)}><option value="all">All GPS statuses</option><option value="with">At least one official GPS</option><option value="missing">Includes Branch with missing GPS</option></select><select value={sort} onChange={event=>setSort(event.target.value)}><option value="name">Sort by Area name</option><option value="customers_desc">Customer count: high to low</option><option value="customers_asc">Customer count: low to high</option></select></div>
    <div className="zone-bulk-toolbar"><span>{t('zone.counts',{shown:filtered.length,selected:selected.length})}</span><button onClick={selectVisible}>Select current filtered results</button><button onClick={()=>{setSelected([]);setMoveError('');setMoveSuccess('')}}>Clear selection</button><select value={bulkZone} onChange={event=>{setBulkZone(event.target.value);setMoveError('');setMoveSuccess('')}}><option value="">Move to selected Zone</option>{groups.filter(group=>group.isActive).map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select><button disabled={moveBusy} onClick={()=>move(selected,bulkZone)}>{moveBusy?'Moving Areas…':'Move selected Areas (pending confirmation)'}</button><button disabled={!selected.length} onClick={()=>confirmAreas(selected,true)}>Confirm assignment</button><button disabled={!selected.length} onClick={()=>confirmAreas(selected,false)}>Revoke confirmation</button></div>
    {moveError&&<p className="detail-error zone-move-feedback" role="alert">{moveError}</p>}
    {moveSuccess&&<p className="planner-message zone-move-feedback" role="status">✓ {moveSuccess}</p>}
    <div className="zone-confirmation-layout"><div className="zone-area-list">{filtered.map(area=><article key={area.id} className={area.zoneAssignmentStatus==='pending_confirmation'?'pending-area':''}><input aria-label={`Select ${area.name}`} type="checkbox" checked={selected.includes(area.id)} onChange={()=>toggle(area.id)}/><button className="area-open" onClick={()=>setDetailId(area.id)}><b>{area.name}</b><small>{area.areaId||'None AreaID'} · {area.customerCount} customers / {area.branchCount} branches · GPS {area.gpsBranchCount}/{area.branchCount}</small></button><span className={area.zoneAssignmentStatus==='confirmed'?'area-confirmed':'area-pending'}>{area.zoneAssignmentStatus==='confirmed'?'Confirmed':'Pending confirmation'}</span><select value={area.zoneGroupId} onChange={event=>move([area.id],event.target.value)}>{groups.filter(group=>group.isActive).map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select><button onClick={()=>confirmAreas([area.id],area.zoneAssignmentStatus!=='confirmed')}>{area.zoneAssignmentStatus==='confirmed'?'Revoke confirmation':'Confirm assignment'}</button></article>)}</div>{detailId&&<AreaDetail detail={detail} error={detailError} onClose={()=>setDetailId(null)}/>}</div>
    {metricDetail&&<ZoneMetricDrawer selection={metricDetail} groups={groups} canManage={canManageAreas} refreshVersion={metricVersion} onConfirm={confirmMetricArea} onMove={moveMetricAreas} onClose={()=>setMetricDetail(null)}/>}
    <ZoneRenameModal group={renameTarget} name={renameName} error={renameError} saving={renameSaving} onNameChange={value=>{setRenameName(value);if(renameError)setRenameError('')}} onCancel={closeRename} onSave={submitRename}/>
  </section>
}

function ZoneDefaultVehicles({group,vehicles=[],canManage,save}){
  const{t}=useI18n(),saved=group.defaultVehicles||[],[draft,setDraft]=useState(saved.map(item=>String(item.id))),[reason,setReason]=useState('')
  useEffect(()=>setDraft((group.defaultVehicles||[]).map(item=>String(item.id))),[group.defaultVehicles])
  const eligible=vehicles.filter(vehicle=>!vehicle.isTemporary&&['available','active'].includes(vehicle.status)),label=vehicle=>`${vehicle.vehicleCode||vehicle.vehicleName} — ${vehicle.registrationNumber||t('common.notSet')}`
  const change=(index,value)=>setDraft(current=>current.map((item,i)=>i===index?value:item)),remove=index=>setDraft(current=>current.filter((_,i)=>i!==index)),submit=async()=>{const ids=draft.filter(Boolean).map(Number);if(new Set(ids).size!==ids.length||!reason.trim())return;const ok=await save(`/api/zone-groups/${group.id}/default-vehicles`,'PUT',{vehicleIds:ids,reason:reason.trim(),successMessage:t('defaultVehicle.poolUpdated')});if(ok)setReason('')}
  return <section className="zone-default-vehicles"><h4>{t('defaultVehicle.plural')}</h4>{!draft.length&&<p>{t('defaultVehicle.noneAssigned')}</p>}{draft.map((value,index)=>{const current=saved.find(item=>String(item.id)===value),options=eligible.filter(item=>String(item.id)===value||!draft.includes(String(item.id)));return <div className="zone-default-vehicle-row" key={`${group.id}-${index}`}><select aria-label={`${t('defaultVehicle.plural')} ${index+1}`} disabled={!canManage} value={value} onChange={event=>change(index,event.target.value)}><option value="">{t('defaultVehicle.unassigned')}</option>{current&&!current.isAvailable&&!options.some(item=>item.id===current.id)&&<option value={current.id}>{label(current)} — {t('defaultVehicle.unavailable')}</option>}{options.map(vehicle=><option key={vehicle.id} value={vehicle.id}>{label(vehicle)}</option>)}</select>{current&&!current.isAvailable&&<small>{t('defaultVehicle.unavailable')}</small>}{canManage&&<button type="button" onClick={()=>remove(index)}>{t('defaultVehicle.remove')}</button>}</div>})}{canManage&&<>{draft.length<3&&<button type="button" onClick={()=>setDraft(current=>[...current,''])}>{t('defaultVehicle.add')}</button>}{draft.length>=3&&<small>{t('defaultVehicle.maximum')}</small>}<input aria-label={t('defaultVehicle.reason')} placeholder={t('defaultVehicle.reason')} value={reason} onChange={event=>setReason(event.target.value)}/><button type="button" disabled={!reason.trim()||draft.some(item=>!item)||new Set(draft).size!==draft.length} onClick={submit}>{t('defaultVehicle.update')}</button></>}</section>
}

function MetricButton({value,label,onClick}){return <button type="button" className="zone-metric-button" onClick={onClick}><b>{value}</b><span>{label}</span><small>View details</small></button>}

function ZoneMetricDrawer({selection,groups,canManage,refreshVersion,onConfirm,onMove,onClose}){
  const[search,setSearch]=useState(''),[areaId,setAreaId]=useState(''),[sort,setSort]=useState('name'),[view,setView]=useState('area'),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState([]),[targetZone,setTargetZone]=useState(''),[reason,setReason]=useState(''),[success,setSuccess]=useState('')
  const areaMode=['areas','confirmed','pending'].includes(selection.metric)
  useEffect(()=>{const params=new URLSearchParams({metric:selection.metric,view,search,sort});if(areaId)params.set('areaId',areaId);setData(null);setError('');request(`/api/zone-groups/${selection.zoneId}/metric-details?${params}`).then(setData).catch(item=>setError(item.message))},[selection,search,areaId,sort,view,refreshVersion])
  useEffect(()=>{setSelected([]);setTargetZone('');setReason('');setSuccess('')},[selection])
  const toggle=id=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])
  const selectFiltered=()=>setSelected(current=>[...new Set([...current,...(data?.items||[]).map(item=>item.id)])])
  const confirmArea=async id=>{setBusy(true);setError('');setSuccess('');try{const ok=await onConfirm(id);if(ok)setSuccess('Area assignment confirmed.');else setError('The Area assignment could not be confirmed.')}finally{setBusy(false)}}
  const moveSelected=async()=>{
    const target=groups.find(group=>group.id===Number(targetZone));if(!selected.length||!target||!reason.trim())return
    const message=`Confirm moving ${selected.length}  Area？\nSource  Zone: ${selection.zoneName}\nTarget  Zone: ${target.name}\n\nAfter moving this is shown as “Assignment adjusted／Pending confirmation”.`
    if(!confirm(message))return
    setBusy(true);setError('');setSuccess('')
    try{const ok=await onMove(selected,target.id,reason.trim());if(ok){setSuccess(`Successfully moved ${selected.length}  Area to ${target.name}; Assignment adjusted, awaiting reconfirmation.`);setSelected([]);setTargetZone('');setReason('')}}finally{setBusy(false)}
  }
  const areaRows=areaMode||(selection.metric==='official_gps'&&data?.view!=='branch')
  return <div className="zone-metric-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&onClose()}>
    <aside className="zone-metric-drawer" role="dialog" aria-modal="true" aria-label={`${selection.zoneName} — ${data?.label||'Statistics details'}`}>
      <header><div><small>ZONE STATISTIC DETAIL</small><h3>{selection.zoneName} — {data?.label||'Loading…'}</h3>{data&&<p>Total  {data.total} items · currently shown {data.filteredCount} items</p>}</div><button onClick={onClose}>Close</button></header>
      <div className="zone-metric-filters"><input aria-label="Search details" placeholder="Search Area, customer name or BranchID" value={search} onChange={event=>setSearch(event.target.value)}/><select aria-label="By  Area filter" value={areaId} onChange={event=>setAreaId(event.target.value)}><option value="">All Area</option>{data?.areas.map(area=><option key={area.id} value={area.id}>{area.name}</option>)}</select><select aria-label="Detail sort" value={sort} onChange={event=>setSort(event.target.value)}><option value="name">Area / Branch Name</option><option value="branches_desc">Customer Branch descending</option><option value="gps_desc">official GPS descending</option><option value="customer">Customer Name</option><option value="branch_id">BranchID</option></select>{selection.metric==='official_gps'&&<div className="metric-view-switch"><button className={view==='area'?'active':''} onClick={()=>setView('area')}>By  Area summary</button><button className={view==='branch'?'active':''} onClick={()=>setView('branch')}>By  Customer Branch</button></div>}</div>
      {areaMode&&canManage&&<div className="metric-bulk-toolbar"><span>Selected <b>{selected.length}</b>  Area</span><button onClick={selectFiltered} disabled={!data?.items.length}>Select all current filtered results</button><button onClick={()=>setSelected([])} disabled={!selected.length}>Clear selection</button><select aria-label="Target  Zone" value={targetZone} onChange={event=>setTargetZone(event.target.value)}><option value="">Select target Zone</option>{groups.filter(group=>group.isActive&&group.id!==selection.zoneId).map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select><input aria-label="Move reason" placeholder="Movement reason (required)" value={reason} onChange={event=>setReason(event.target.value)}/><button className="metric-move-button" disabled={busy||!selected.length||!targetZone||!reason.trim()} onClick={moveSelected}>Move to selected Zone</button></div>}
      {areaMode&&!canManage&&<p className="metric-permission-note">You do not have permission to perform this action.</p>}
      {success&&<div className="metric-success">✓ {success}</div>}
      {error?<p className="detail-error">{error}</p>:!data?<p className="metric-loading">Loading…</p>:data.items.length===0?<p className="metric-loading">No matching data.</p>:areaRows?<SelectableAreaMetricTable items={data.items} selectable={areaMode&&canManage} selected={selected} toggle={toggle} pending={selection.metric==='pending'} busy={busy} onConfirm={confirmArea}/>:<BranchMetricTable items={data.items} metric={selection.metric}/>}</aside>
  </div>
}

function SelectableAreaMetricTable({items,selectable,selected,toggle,pending,busy,onConfirm}){return <div className="metric-table-wrap"><table><thead><tr>{selectable&&<th>Select</th>}<th>Area Name / ID</th><th>Current Zone</th>{pending&&<th>Current official Zone</th>}<th>Customer Branch</th><th>official GPS</th><th>Missing GPS</th><th>Confirmation status</th>{pending&&<th>Actions</th>}</tr></thead><tbody>{items.map(item=><tr key={item.id}>{selectable&&<td><input aria-label={`Select ${item.areaName}`} type="checkbox" checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/></td>}<td><b>{item.areaName}</b><small>{item.areaId||'None Area ID'}</small></td><td>{item.currentZone}</td>{pending&&<td>{item.formalZone}</td>}<td>{item.branchCount}</td><td>{item.officialGpsCount}</td><td>{item.missingGpsCount}</td><td><span className={item.zoneAssignmentStatus==='confirmed'?'area-confirmed':'area-pending'}>{item.zoneAssignmentStatus==='confirmed'?'Confirmed':'Assignment adjusted／Pending confirmation'}</span></td>{pending&&<td><button disabled={busy} onClick={()=>confirm('Confirm this  Area  current  Zone assignment？')&&onConfirm(item.id)}>Confirm assignment</button></td>}</tr>)}</tbody></table></div>}

// Kept temporarily for compatibility with older hot-reloaded sessions.
// oxlint-disable-next-line no-unused-vars
function ZoneMetricDrawerLegacy({selection,refreshVersion,onConfirm,onClose}){
  const[search,setSearch]=useState(''),[areaId,setAreaId]=useState(''),[sort,setSort]=useState('name'),[view,setView]=useState('area'),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{const params=new URLSearchParams({metric:selection.metric,view,search,sort});if(areaId)params.set('areaId',areaId);setData(null);setError('');request(`/api/zone-groups/${selection.zoneId}/metric-details?${params}`).then(setData).catch(item=>setError(item.message))},[selection,search,areaId,sort,view,refreshVersion])
  const confirmArea=async id=>{setBusy(true);try{await onConfirm(id)}finally{setBusy(false)}}
  const areaRows=['areas','confirmed','pending'].includes(selection.metric)||(selection.metric==='official_gps'&&data?.view!=='branch')
  return <div className="zone-metric-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside className="zone-metric-drawer" role="dialog" aria-modal="true" aria-label={`${selection.zoneName} — ${data?.label||'Statistics details'}`}><header><div><small>ZONE STATISTIC DETAIL</small><h3>{selection.zoneName} — {data?.label||'Loading…'}</h3>{data&&<p>Total  {data.total} items · currently shown {data.filteredCount} items</p>}</div><button onClick={onClose}>Close</button></header><div className="zone-metric-filters"><input aria-label="Search details" placeholder="Search Area, customer name or BranchID" value={search} onChange={event=>setSearch(event.target.value)}/><select aria-label="By  Area filter" value={areaId} onChange={event=>setAreaId(event.target.value)}><option value="">All Area</option>{data?.areas.map(area=><option key={area.id} value={area.id}>{area.name}</option>)}</select><select aria-label="Detail sort" value={sort} onChange={event=>setSort(event.target.value)}><option value="name">Area / Branch Name</option><option value="branches_desc">Customer Branch descending</option><option value="gps_desc">official GPS descending</option><option value="customer">Customer Name</option><option value="branch_id">BranchID</option></select>{selection.metric==='official_gps'&&<div className="metric-view-switch"><button className={view==='area'?'active':''} onClick={()=>setView('area')}>By  Area summary</button><button className={view==='branch'?'active':''} onClick={()=>setView('branch')}>By  Customer Branch</button></div>}</div>{error?<p className="detail-error">{error}</p>:!data?<p className="metric-loading">Loading…</p>:data.items.length===0?<p className="metric-loading">No matching data.</p>:areaRows?<AreaMetricTable items={data.items} pending={selection.metric==='pending'} busy={busy} onConfirm={confirmArea}/>:<BranchMetricTable items={data.items} metric={selection.metric}/>}</aside></div>
}

function AreaMetricTable({items,pending,busy,onConfirm}){return <div className="metric-table-wrap"><table><thead><tr><th>Area Name / ID</th>{pending&&<><th>Current suggestion Zone</th><th>Current official Zone</th></>}<th>Customer Branch</th><th>official GPS</th><th>Missing GPS</th><th>Confirmation status</th>{pending&&<th>Actions</th>}</tr></thead><tbody>{items.map(item=><tr key={item.id}><td><b>{item.areaName}</b><small>{item.areaId||'None Area ID'}</small></td>{pending&&<><td>{item.currentZone}</td><td>{item.formalZone}</td></>}<td>{item.branchCount}</td><td>{item.officialGpsCount}</td><td>{item.missingGpsCount}</td><td><span className={item.zoneAssignmentStatus==='confirmed'?'area-confirmed':'area-pending'}>{item.zoneAssignmentStatus==='confirmed'?'Confirmed':'Pending confirmation'}</span></td>{pending&&<td><button disabled={busy} onClick={()=>confirm('Confirm this  Area  current  Zone assignment？')&&onConfirm(item.id)}>Confirm assignment</button></td>}</tr>)}</tbody></table></div>}

function BranchMetricTable({items,metric}){const openGps=item=>window.location.assign(`?page=location-zone&tab=locations&branch=${encodeURIComponent(item.branchId)}`);return <div className="metric-table-wrap"><table><thead><tr><th>Customer / Branch</th><th>Customer ID / Branch ID</th><th>Area</th>{metric==='scheduled'?<><th>Collection Frequency</th><th>Assigned Weekdays</th><th>GPS Status</th></>:<><th>GPS Status</th>{metric==='missing_gps'&&<th>Temporary GPS</th>}<th>Schedule Status</th></>}</tr></thead><tbody>{items.map(item=>{const schedules=item.schedules||[],collectable=metric==='missing_gps'&&!item.hasOfficialGps&&!item.hasTemporaryGps;return <tr key={item.id} className={collectable?'gps-collectable-row':''} role={collectable?'button':undefined} tabIndex={collectable?0:undefined} onClick={collectable?()=>openGps(item):undefined} onKeyDown={collectable?event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openGps(item)}}:undefined}><td><b>{item.customerName||'Unmatched customer'}</b><small>{item.branchName||'Unnamed branch'}</small></td><td><b>{formatCustomerId(item.customerId)||'—'}</b><small>{formatBranchId(item.branchId)||'—'}</small></td><td>{item.areaName||'—'}</td>{metric==='scheduled'?<><td>{[...new Set(schedules.map(schedule=>schedule.frequency||'Not stated'))].join(', ')}</td><td>{[...new Set(schedules.map(schedule=>schedule.assignedWeekdays||'Not specified'))].join(', ')}</td><td>{item.hasOfficialGps?'Available official GPS':'Missing GPS'}</td></>:<><td>{item.hasOfficialGps?'Available official GPS':'Missing GPS'}</td>{metric==='missing_gps'&&<td>{item.hasTemporaryGps?'Pending Approval':'GPS Not Collected'}</td>}<td>{schedules.length?'Has official schedule':'No official schedule'}</td></>}</tr>})}</tbody></table></div>}

function AreaDetail({detail,error,onClose}){return <aside className="area-detail"><header><div><small>AREA CONFIRMATION DETAIL</small><h3>{detail?.name||'Area Loading data…'}</h3></div><button onClick={onClose}>Close</button></header>{error?<p className="detail-error">{error}</p>:!detail?<p>Loading…</p>:<><div className="area-detail-summary"><span><b>{detail.zoneGroup||'—'}</b>Current Zone</span><span><b>{detail.zoneAssignmentStatus==='confirmed'?'Confirmed':'Pending confirmation'}</b>Assignment status</span><span><b>{detail.customerCount??0}</b>Customer</span><span><b>{detail.branchCount??0}</b>branches</span><span><b>{detail.gpsBranchCount??0}</b>Official GPS</span><span><b>{detail.missingGpsBranchCount??0}</b>Missing GPS</span><span><b>{detail.history.dispatchCount??0}</b>Historical dispatch count</span><span><b>{detail.history.collectedWeightKg==null?'—':`${detail.history.collectedWeightKg} kg`}</b>Historical collection weight</span></div><h4>Customer Branches</h4><div className="area-branches">{detail.branches.length===0?<p>This Area currently has no branches.</p>:detail.branches.map(branch=><article key={branch.id}><strong>{formatBranchId(branch.branchId)} — {branch.branchName||'Unnamed branch'}</strong><small>{formatCustomerId(branch.customerId)} — {branch.customerName||'Unmatched customer'}</small><p>{branch.address||'—'}</p><p>{gpsText(branch)}</p><div>{branch.schedules.length?branch.schedules.map(schedule=><span key={schedule.scheduleId}>{schedule.frequency||'Frequency not stated'} · {schedule.dayOfWeek||'Weekday not specified'}</span>):<span>No fixed schedule</span>}</div></article>)}</div><h4>Adjacent Areas (estimated from existing official GPS)</h4>{detail.adjacentAreas.length?<div className="adjacent-areas">{detail.adjacentAreas.map(area=><span key={area.id}><b>{area.name}</b>{area.zoneGroup||'—'} · about {area.distanceKm} km</span>)}</div>:<p>Existing GPS data is insufficient to calculate this.</p>}</>}</aside>}
