import { useMemo, useState } from 'react'
import './ZoneGroupManager.css'

export default function ZoneGroupManager({groups,areas,save}){
  const[form,setForm]=useState({name:'',code:'',sortOrder:''}),[search,setSearch]=useState(''),[selected,setSelected]=useState([])
  const filtered=useMemo(()=>areas.filter(area=>`${area.name} ${area.areaId||''} ${area.zoneGroup}`.toLowerCase().includes(search.toLowerCase())),[areas,search])
  const create=event=>{event.preventDefault();if(!form.name.trim())return;save('/api/zone-groups','POST',{...form,sortOrder:form.sortOrder?Number(form.sortOrder):undefined});setForm({name:'',code:'',sortOrder:''})}
  const rename=group=>{const name=prompt('Zone Group Name',group.name);if(name&&name!==group.name)save(`/api/zone-groups/${group.id}`,'PATCH',{name})}
  const merge=group=>{const choices=groups.filter(item=>item.id!==group.id&&item.isActive).map(item=>`${item.id}: ${item.name}`).join('\n'),targetZoneId=Number(prompt(`把 ${group.name} 合并到哪一个 Zone？\n${choices}`,'')||0);if(targetZoneId&&confirm(`确认把 ${group.name} 的所有 Area 合并到目标 Zone？旧 Zone 会停用，历史快照不变。`))save('/api/zone-groups/merge','POST',{sourceZoneIds:[group.id],targetZoneId})}
  const split=group=>{const areaIds=selected.filter(id=>areas.find(area=>area.id===id)?.zoneGroupId===group.id);if(!areaIds.length){alert('请先勾选属于该 Zone、需要拆出的 Area。');return}const name=prompt('新 Zone Group Name','');if(name)save('/api/zone-groups/split','POST',{sourceZoneId:group.id,name,areaIds})}
  const toggle=id=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])
  return <section className="master-section zone-manager"><header><h2>Zone Group 管理</h2><p>Zone 数量没有上限。Zone 只作营运分类，不绑定车辆或司机；移动 Area 不会修改 BranchID、GPS 或固定排程。</p></header><form onSubmit={create}><input required placeholder="新 Zone 名称" value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/><input placeholder="Code（可留空自动产生）" value={form.code} onChange={event=>setForm({...form,code:event.target.value})}/><input type="number" placeholder="显示顺序" value={form.sortOrder} onChange={event=>setForm({...form,sortOrder:event.target.value})}/><button>新增 Zone Group</button></form><div className="zone-summary dynamic-zones">{groups.map(group=><article key={group.id} className={group.isActive?'':'inactive-zone'}><strong>{group.name}</strong><small>{group.code} · {group.areaCount} Areas · {group.pendingAreaCount||0} 待确认</small><label>顺序 <input type="number" defaultValue={group.sortOrder} onBlur={event=>{const sortOrder=Number(event.target.value);if(sortOrder!==group.sortOrder)save(`/api/zone-groups/${group.id}`,'PATCH',{sortOrder})}}/></label><div><button onClick={()=>rename(group)}>改名</button><button onClick={()=>save(`/api/zone-groups/${group.id}/${group.isActive?'deactivate':'reactivate'}`,'POST',{})}>{group.isActive?'停用':'重新启用'}</button><button disabled={!group.isActive} onClick={()=>merge(group)}>合并</button><button disabled={!group.isActive} onClick={()=>split(group)}>拆分勾选 Area</button></div></article>)}</div><div className="zone-area-toolbar"><input placeholder="搜索 Area / AreaID / Zone" value={search} onChange={event=>setSearch(event.target.value)}/><span>已勾选 {selected.length} 个 Area</span></div><div className="zone-area-list">{filtered.map(area=><label key={area.id} className={area.zoneAssignmentStatus==='pending_confirmation'?'pending-area':''}><input type="checkbox" checked={selected.includes(area.id)} onChange={()=>toggle(area.id)}/><span><b>{area.name}</b><small>{area.areaId||'无 AreaID'} · {area.zoneAssignmentStatus==='confirmed'?'已确认':'待确认'}</small></span><select value={area.zoneGroupId} onChange={event=>save(`/api/areas/${area.id}/zone-group`,'PATCH',{zoneGroupId:Number(event.target.value)})}>{groups.filter(group=>group.isActive).map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select>{area.zoneAssignmentStatus!=='confirmed'&&<button onClick={()=>save(`/api/areas/${area.id}/zone-group`,'PATCH',{zoneGroupId:area.zoneGroupId})}>确认当前归属</button>}</label>)}</div></section>
}
