import { useEffect, useMemo, useState } from 'react'
import './ZoneGroupManager.css'

const request=async url=>{const response=await fetch(url),data=await response.json();if(!response.ok)throw new Error(data.error||'资料载入失败');return data}
const gpsText=branch=>Number.isFinite(branch.latitude)&&Number.isFinite(branch.longitude)&&!(branch.latitude===0&&branch.longitude===0)?`${branch.latitude}, ${branch.longitude}`:'缺少正式 GPS'

export default function ZoneGroupManager({groups,areas,save}){
  const[form,setForm]=useState({name:'',code:'',sortOrder:''}),[search,setSearch]=useState(''),[selected,setSelected]=useState([]),[status,setStatus]=useState('pending'),[zoneFilter,setZoneFilter]=useState('all'),[gpsFilter,setGpsFilter]=useState('all'),[sort,setSort]=useState('name'),[detailId,setDetailId]=useState(null),[detail,setDetail]=useState(null),[detailError,setDetailError]=useState(''),[bulkZone,setBulkZone]=useState('')
  useEffect(()=>{if(!detailId){setDetail(null);return}setDetail(null);setDetailError('');request(`/api/areas/${detailId}/zone-confirmation`).then(setDetail).catch(error=>setDetailError(error.message))},[detailId,areas])
  const filtered=useMemo(()=>areas.filter(area=>{
    const matchesSearch=`${area.name} ${area.areaId||''} ${area.zoneGroup}`.toLowerCase().includes(search.toLowerCase())
    const matchesStatus=status==='all'||(status==='pending'&&area.zoneAssignmentStatus!=='confirmed')||(status==='confirmed'&&area.zoneAssignmentStatus==='confirmed')
    const matchesZone=zoneFilter==='all'||area.zoneGroupId===Number(zoneFilter)
    const matchesGps=gpsFilter==='all'||(gpsFilter==='with'&&area.gpsBranchCount>0)||(gpsFilter==='missing'&&area.gpsBranchCount<area.branchCount)
    return matchesSearch&&matchesStatus&&matchesZone&&matchesGps
  }).sort((a,b)=>sort==='customers_desc'?b.customerCount-a.customerCount:sort==='customers_asc'?a.customerCount-b.customerCount:a.name.localeCompare(b.name)),[areas,search,status,zoneFilter,gpsFilter,sort])
  const create=async event=>{event.preventDefault();if(!form.name.trim())return;await save('/api/zone-groups','POST',{...form,sortOrder:form.sortOrder?Number(form.sortOrder):undefined});setForm({name:'',code:'',sortOrder:''})}
  const rename=group=>{const name=prompt('Zone Group Name',group.name);if(name&&name!==group.name)save(`/api/zone-groups/${group.id}`,'PATCH',{name})}
  const merge=group=>{const choices=groups.filter(item=>item.id!==group.id&&item.isActive).map(item=>`${item.id}: ${item.name}`).join('\n'),targetZoneId=Number(prompt(`把 ${group.name} 合并到哪一个 Zone？\n${choices}`,'')||0);if(targetZoneId&&confirm(`确认移动所有 Area 并停用 ${group.name}？移动后的 Area 会保持待确认，历史快照不变。`))save('/api/zone-groups/merge','POST',{sourceZoneIds:[group.id],targetZoneId})}
  const split=group=>{const areaIds=selected.filter(id=>areas.find(area=>area.id===id)?.zoneGroupId===group.id);if(!areaIds.length){alert('请先勾选属于该 Zone、需要拆出的 Area。');return}const name=prompt('新 Zone Group Name','');if(name)save('/api/zone-groups/split','POST',{sourceZoneId:group.id,name,areaIds})}
  const toggle=id=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])
  const selectVisible=()=>setSelected(current=>[...new Set([...current,...filtered.map(area=>area.id)])])
  const move=async(areaIds,zoneGroupId)=>{if(!areaIds.length||!zoneGroupId)return;await save('/api/areas/bulk-zone-group','POST',{areaIds,zoneGroupId:Number(zoneGroupId)});setSelected([])}
  const confirmAreas=async(areaIds,confirmed)=>{if(!areaIds.length)return;await save('/api/areas/bulk-confirmation','POST',{areaIds,confirmed});setSelected([])}
  return <section className="master-section zone-manager"><header><h2>Zone Area Confirmation</h2><p>移动 Area 只建立待确认归属；主管另按“确认归属”后，新路线才采用新 Zone。BranchID、CustomerID、GPS、固定排程与历史派车不会被修改。</p></header>
    <form onSubmit={create}><input required placeholder="新 Zone 名称" value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/><input placeholder="Code（可留空自动产生）" value={form.code} onChange={event=>setForm({...form,code:event.target.value})}/><input type="number" placeholder="显示顺序" value={form.sortOrder} onChange={event=>setForm({...form,sortOrder:event.target.value})}/><button>新增 Zone Group</button></form>
    <div className="zone-summary dynamic-zones">{groups.map(group=><article key={group.id} className={group.isActive?'':'inactive-zone'}><strong>{group.name}</strong><small>{group.code}</small><div className="zone-card-metrics"><span><b>{group.areaCount}</b>Area 总数</span><span><b>{group.confirmedAreaCount}</b>已确认</span><span><b>{group.pendingAreaCount}</b>待确认</span><span><b>{group.branchCount}</b>Customer Branch</span><span><b>{group.gpsBranchCount}</b>有正式 GPS</span><span><b>{group.missingGpsBranchCount}</b>缺少 GPS</span><span><b>{group.scheduledCustomerCount}</b>已排程客户</span></div><label>顺序 <input type="number" defaultValue={group.sortOrder} onBlur={event=>{const sortOrder=Number(event.target.value);if(sortOrder!==group.sortOrder)save(`/api/zone-groups/${group.id}`,'PATCH',{sortOrder})}}/></label><div className="zone-card-actions"><button onClick={()=>rename(group)}>改名</button><button onClick={()=>save(`/api/zone-groups/${group.id}/${group.isActive?'deactivate':'reactivate'}`,'POST',{})}>{group.isActive?'停用':'重新启用'}</button><button disabled={!group.isActive} onClick={()=>merge(group)}>合并</button><button disabled={!group.isActive} onClick={()=>split(group)}>拆分勾选 Area</button></div></article>)}</div>
    <div className="zone-area-filters"><input placeholder="搜索 Area / AreaID / Zone" value={search} onChange={event=>setSearch(event.target.value)}/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="pending">只看待确认</option><option value="confirmed">只看已确认</option><option value="all">全部状态</option></select><select value={zoneFilter} onChange={event=>setZoneFilter(event.target.value)}><option value="all">全部 Zone</option>{groups.map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select><select value={gpsFilter} onChange={event=>setGpsFilter(event.target.value)}><option value="all">全部 GPS 状态</option><option value="with">至少一个正式 GPS</option><option value="missing">包含缺 GPS Branch</option></select><select value={sort} onChange={event=>setSort(event.target.value)}><option value="name">Area 名称排序</option><option value="customers_desc">客户数量：多到少</option><option value="customers_asc">客户数量：少到多</option></select></div>
    <div className="zone-bulk-toolbar"><span>显示 {filtered.length} 个 · 已勾选 {selected.length} 个</span><button onClick={selectVisible}>勾选当前筛选结果</button><button onClick={()=>setSelected([])}>清除勾选</button><select value={bulkZone} onChange={event=>setBulkZone(event.target.value)}><option value="">移动到指定 Zone</option>{groups.filter(group=>group.isActive).map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select><button disabled={!selected.length||!bulkZone} onClick={()=>move(selected,bulkZone)}>批量移动（保持待确认）</button><button disabled={!selected.length} onClick={()=>confirmAreas(selected,true)}>确认归属</button><button disabled={!selected.length} onClick={()=>confirmAreas(selected,false)}>撤销确认</button></div>
    <div className="zone-confirmation-layout"><div className="zone-area-list">{filtered.map(area=><article key={area.id} className={area.zoneAssignmentStatus==='pending_confirmation'?'pending-area':''}><input aria-label={`选择 ${area.name}`} type="checkbox" checked={selected.includes(area.id)} onChange={()=>toggle(area.id)}/><button className="area-open" onClick={()=>setDetailId(area.id)}><b>{area.name}</b><small>{area.areaId||'无 AreaID'} · {area.customerCount} 客户 / {area.branchCount} 分店 · GPS {area.gpsBranchCount}/{area.branchCount}</small></button><span className={area.zoneAssignmentStatus==='confirmed'?'area-confirmed':'area-pending'}>{area.zoneAssignmentStatus==='confirmed'?'已确认':'待确认'}</span><select value={area.zoneGroupId} onChange={event=>move([area.id],event.target.value)}>{groups.filter(group=>group.isActive).map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select><button onClick={()=>confirmAreas([area.id],area.zoneAssignmentStatus!=='confirmed')}>{area.zoneAssignmentStatus==='confirmed'?'撤销确认':'确认归属'}</button></article>)}</div>{detailId&&<AreaDetail detail={detail} error={detailError} onClose={()=>setDetailId(null)}/>}</div>
  </section>
}

function AreaDetail({detail,error,onClose}){return <aside className="area-detail"><header><div><small>AREA CONFIRMATION DETAIL</small><h3>{detail?.name||'Area 资料载入中…'}</h3></div><button onClick={onClose}>关闭</button></header>{error?<p className="detail-error">{error}</p>:!detail?<p>载入中…</p>:<><div className="area-detail-summary"><span><b>{detail.zoneGroup}</b>当前 Zone</span><span><b>{detail.zoneAssignmentStatus==='confirmed'?'已确认':'待确认'}</b>归属状态</span><span><b>{detail.customerCount}</b>客户</span><span><b>{detail.branchCount}</b>分店</span><span><b>{detail.gpsBranchCount}</b>有正式 GPS</span><span><b>{detail.missingGpsBranchCount}</b>缺 GPS</span><span><b>{detail.history.dispatchCount}</b>历史派车次数</span><span><b>{detail.history.collectedWeightKg==null?'—':`${detail.history.collectedWeightKg} kg`}</b>历史收货重量</span></div><h4>客户与分店</h4><div className="area-branches">{detail.branches.length===0?<p>这个 Area 暂时没有分店。</p>:detail.branches.map(branch=><article key={branch.id}><strong>{branch.branchName||'未命名分店'}</strong><small>{branch.customerName||'未匹配客户'} · {branch.branchId||'无 BranchID'}</small><p>{branch.address||'无地址'}</p><p>{gpsText(branch)}</p><div>{branch.schedules.length?branch.schedules.map(schedule=><span key={schedule.scheduleId}>{schedule.frequency||'未注明周期'} · {schedule.dayOfWeek||'未指定星期'}</span>):<span>没有固定排程</span>}</div></article>)}</div><h4>相邻 Area（按现有正式 GPS 估算）</h4>{detail.adjacentAreas.length?<div className="adjacent-areas">{detail.adjacentAreas.map(area=><span key={area.id}><b>{area.name}</b>{area.zoneGroup} · 约 {area.distanceKm} km</span>)}</div>:<p>现有 GPS 资料不足，暂时无法计算。</p>}</>}</aside>}
